### ISSUE TITLE
[TOC]: Vertical Table of Contents text to change based on each sections background theme

### ISSUE THREAD

**Issue by druckerk** [carbon-design-system/carbon-for-ibm-dotcom#10027]
### The problem

Corresponding JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2558

The problem is the [Vertical Table of Conten](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-table-of-contents--default)t (TOC) components text does not change color as it scrolls through sections with a darker theme. The Vertical TOC is set to theme white; the TOC does not have the option to change themes. 

Example image: 
![image-2022-08-24-13-32-26-825](https://user-images.githubusercontent.com/88403358/217600620-094880bc-5e84-4875-803d-0a76930e051f.png)

### The solution

Is there a way to add functionality to the vertical TOC to change the text color to match the section's background theme?

### Application/website

AEM

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

Ideally, we would like it done soon. But, let us know if this option is possible for the TOC component. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@druckerk Thanks for opening this feature request issue! @jwitkowski79 Can you include our design solution specs for this feature?

**Comment by jwitkowski79** [comment]
Hey everyone! So putting some ideas explored down here for discussion. After talking with @andy-blum, some of them will difficult to implement and others pose accessibility issues. I would love to have @oliviaflory eyes on this too as it may change the interaction and design of the TOC in the C4IBM.com library. Not every solution is something we'd recommend but putting them here for discussion. If there are other options or ideas that I haven't explored, please feel free to add them

**Option 1**
Color of the text and indicators change to a dark theme as the TOC interacts with the dark themed component. the idea was to use CSS filters but after talking with @andy-blum about this, it may not be possible. This would be the preferable way to move forward.
![Option 1](https://user-images.githubusercontent.com/2040791/217637027-21d2f55c-d066-497c-81c5-70909f4a465c.jpg)

**Option 2**
Color of the text and indicators change to a dark theme as each line in the TOC or each individual TOC title interacts with the dark themed component. Again, this may pose the same issues above and we might have accessibility issues as certain multi line titles wouldn't be fully readable until the entire TOC item is on the dark themed component
![Option 2](https://user-images.githubusercontent.com/2040791/217637631-67e25d20-bf04-4ee8-aa5b-fb9292bfd3c7.jpg)

**Option 3**
If there isn't a way to change each TOC title as it interacts with the dark themed component, another option would be to put a background behind the TOC. This solution is not ideal as it creates some odd negative space and makes everything feel crammed into the space but attaching the example here to point out that it was explored. This is the least favorite option
![Option 3](https://user-images.githubusercontent.com/2040791/217638522-ef21b8fb-a163-4654-8e85-1f1cd34cb7ed.jpg)


**Option 4**
Change the z-index of the TOC as it interacts with the dark themed component so the vertical TOC goes behind the dark themed component. @andy-blum pointed out as this would create accessibility issues as items will still be focusable but don't actually appear on the page
![Option 4](https://user-images.githubusercontent.com/2040791/217638564-ea88a772-d7ce-453b-aebb-51556df8e0b7.jpg)

**Comment by andy-blum** [comment]
Thanks, @jwitkowski79 

I wanted to add some perspective to each of these.

## Option 1: Mix Blend Mode

This is the cleanest, most accessible way to implement this, but it does not appear to have any meaningful impact between unrelated web components. Additionally, changing the colors this way would likely result in colors that are not a part of the carbon design language as the changed colors are changed mathematically, and not swapped out for some pre-decided color choice.

[mix-blend-mode demo](https://css-tricks.com/reverse-text-color-mix-blend-mode/)

## Option 2: Lots of JavaScript

This is the most _realistic_ way to make the request happen, but it falls short of ideal and comes with a cost.

Implementing this solution would likely require an IntersectionObserver _per link item_ to manually change the color when a certain overlap ratio is encountered. This, however, will be extremely difficult (if not impossible) to implement for several reasons:

1. The full-bleed color is created using a box shadow that stretches the width of the viewport, and not the actual DOM element itself. This means the intersection needs to actually happen _to the right_ of each link
2. IntersectionObservers can only watch for the intersection of elements with the scroll container element ancestors, in this case the `<html>` or `<body>` elements, so we'd need to set the Observer's root margin as relative to the viewport, and re-create the observer any time the browser is resized or scrolls in a way that moves the TOC links.
3. The combination of the two points above will make for a considerable load of blocking JS on the main thread causing potential performance issues

## Option 3: Adding a background color

This is the compromise option where authors are allowed to use multiple themes in the same TOC grouping. It's dead simple, and will remain accessible.

## Option 4: Z-indexing the TOC links

In my opinion this is not an option. This will have serious accessibility violations.

## Option 5: Prohibiting use of mixed-themes in TOC sections

This wasn't mentioned, but I think needs further consideration. With Options 1 and 2 having considerable development challenges, option 3 falling short of design approval, and option 4 failing accessibility, _simply not allowing mixed themes_ might be the right answer.

**Comment by oliviaflory** [comment]
Hey @jwitkowski79 I have a few follow up questions that would help our team evaluate this feature request:

1. Do you have any examples of full page templates we could look at for this feature? 
2. Would this color change be applied mid-page or is the only use case for the last section/block of the page (ie the Take the next step)?
3. I'm a bit surprised to see the dark section considering the brand direction of light and bright, would the team consider a `gray 10` background?

**Comment by andy-blum** [comment]
Just added the corresponding JIRA ticket to the issue description

**Comment by jwitkowski79** [comment]
@oliviaflory Hello! 

1. Here's a link to a page that development has setup: [https://dev-publish.np-roks.cms.cis.ibm.net/qa/learn-page-testing-mr-sep-](https://dev-publish.np-roks.cms.cis.ibm.net/qa/learn-page-testing-mr-sep-). I'm not sure if you can see it because it's in AEM? If not, I can share my screen. 
2. The theme change can be applied to any component in AEM, so technically it could also appear mid page. 
3. Agreed! But in AEM, the theme isn't applied at the page level but instead at the component level, it is possible for an author to choose a "dark themed" component even though we would recommend against it. Because of this, we discussed that there should be a solution for this scenario in the system for accessibility purposes, even though it would rarely occur. We also are unsure if the brand team would want to use a dark themed component in the future for experimentation purposes since they work somewhat outside of the recommended templates in order to experiment and gather data on what's is working.

**Comment by oliviaflory** [comment]
Thanks for the examples @jwitkowski79 I can see the page! Running this by the accessibility team and will follow up after
