### ISSUE TITLE
Fix custom-elements.json

### ISSUE THREAD

**Issue by jogibear9988** [carbon-design-system/carbon-for-ibm-dotcom#10024]
### Description

The custom-elements.json seems to be an old version, and the path in the manifest links to the .ts files, but according to the spec it should link to the .js files (it also only makes sense, cause the .js files are the ones that get used).

I need the correct spec for the components to work in my designer: https://node-projects.github.io/web-component-designer-demo/index.html

### Component(s) impacted

all

### Browser

Chrome

### Carbon for IBM.com version

current

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

a designer

### Package

@carbon/web-components

### CodeSandbox example

no sample

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by emyarod** [comment]
Can you explain more about what you mean by the spec needing to link to .js files? For reference, the [playground examples for web-component-analyzer](https://runem.github.io/web-component-analyzer/) also link to .ts files 

but just as a heads up, web-component-analyzer emits this message on every use, so it may be brittle to depend on:

```
!!!!!!!!!!!!!  WARNING !!!!!!!!!!!!!
The custom-elements.json format is for experimental purposes. You can expect changes to this format.
Please follow and contribute to the discussion at:
  - https://github.com/webcomponents/custom-elements-json
  - https://github.com/w3c/webcomponents/issues/776
!!!!!!!!!!!!!  WARNING !!!!!!!!!!!!!
```

**Comment by jogibear9988** [comment]
This was wrong, see: 
https://github.com/webcomponents/custom-elements-manifest/issues/96#issuecomment-1037495021

For example, my designer uses the manifest to load the components, but a browser could not load .ts files

**Comment by emyarod** [comment]
I only see a discussion in your link but I'm not finding the resolution. Either we would have to migrate off of web-component-analyzer or there needs to be an issue opened on that repo instead to correct the analyzer's behavior, is that right?

**Comment by justinfagnani** [comment]
The module paths need to link to where users and tools can actually import the element from. For TypeScript projects that is _not_the source file. web-components-analyzer is indeed incorrect here. The Lit team is working on a new analyzer that outputs the correct paths (most of the time, if you don't have a different build step after TypeScript). It should be ready enough to generate manifests soon: https://github.com/lit/lit/tree/main/packages/labs/analyzer

**Comment by emyarod** [comment]
thank you for the clarification! So it looks like the next steps here would be to open an issue against web-components-analyzer, and in the meantime we will also keep an eye on the Lit team's analyzer for a possible migration

**Comment by abdonrd** [comment]
@jeffchew @kennylam looks like the v2 version has the same problem.

Could you review it? Thank you!
