### ISSUE TITLE
[Content group banner] Rename component

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10032]
`Content group banner` was named based off of using the same heading styling as other `content group` components, but does not look and function like other `content groups`. 

Since our goal is to simplify the number of overall components, we can separate `content group banner` from the other components so that it's clear that the `content group` components are designed for a specific purpose and behave the same way. 

The goal for this component is to create a pause in the page content to relay a message. This is different from `universal banner`.

**Follow on:**
- Change name and references on website (including .yaml file)
- Change name in Figma kit
- Change name on imported Sketch kit
- Func specs

**Comment by oliviaflory** [comment]
Notes from review Feb 13:

V1 vs V2
- can create duplicate & rename within v1, will have to keep existing and add deprecation announcement
- Could wait to rename in v2 (easier transition/less work(?))

Name ideas:
- Inline banner
- Content banner
- In page banner
- CTA banner

**Comment by oliviaflory** [comment]
### Decision:  `in page banner`

- [ ] update in the dev story
