### ISSUE TITLE
[Feature card – medium] v2 check

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10138]
For `feature card – medium` we need to check for these updates in v2:
* Ensure that the color scheme property is set to `regular` by default
* Ensure that the icon orientation is to the right in v2
* Add border 
* update all tokens to v11

**[Design specs](https://www.figma.com/file/29lZzs4QtVwho2OM6OapT9/UI-component--feature--card--design-specs-2.0.0?node-id=10%3A2939&t=8mx6iEd8IIgkyLRQ-1)**

- [ ]  Review PR

**Comment by oliviaflory** [comment]
Rich worked with Andrew while the component was in development, this should be good
