### ISSUE TITLE
[Card link] Merge with card + type exploration

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10133]
`Card link` was created as a one-off component to provide a CTA at the end of a piece of content. To more streamline the design system, we want to merge `card link` into a variant of `card`, rather than existing as its own component.

**[Card link design specs](https://www.figma.com/file/Kd7fzuA0bd6VIqykFCnmk4/UI-pattern--card-link--visual-specs--1.1.0?t=O7fuzLuQo1khBLVK-1)**
**[Card design specs](https://www.figma.com/file/iYaBsuyCTOKjhZIXLMA83u/UI-component--card--visual-specs-v3.2?node-id=32%3A6019&t=Sl5EtKaGFLenn8po-1)**

Sync with dev
- [ ] Explore how `card link` should be merged with `card` – separate variant? Toggle for only one variant?

Design
- [ ] Add border
- [ ] Consider heading-03 instead of heading-02
- [ ] Do teams use body copy in card link?
- [ ] Review updates with Jeannie, Olivia, Rich
- [ ] Write design specs story

**Comment by oliviaflory** [comment]
Closing, adopters could use Card default if they wanted to use the exp heading 03 for a card link
