### ISSUE TITLE
[Filter panel] Review accessibility

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10132]
The `filter panel` was added to the repo, but needs to be reviewed from an accessibility angle. We should discuss with Mike Gower or other resources, and note any opportunities to update the component for better accessibility.

**[Design specs](https://www.figma.com/file/qxRIeYWHfiAaW8JLWGYm5f/UI-component--filter-panel--visual-specs--v1.0?node-id=0%3A1&t=dXOgg7vx4v9RGy5W-1)**

- [ ] Review `filter panel` with accessibility SME
- [ ] Create issue based on a11y feedback

**Comment by oliviaflory** [comment]
### Review w Michael in Design crit 5/25
[Figma file](https://www.figma.com/file/mzfn7lpNrZWEhxmgoL2NDS/UI-component--filter-panel?type=design&node-id=110%3A3219&t=BQTJuE8iucc0UD7v-1)

**Keyboard**
- All tab stops are not ideal for the user, tedious
- Accordions at tab stops is promising
   - Checkboxes are also tab stops
       - Checkbox should not be arrow key navigation because the  
   - include guidance to not open all accordions in consideration for accessibility guidance
- Option for filter panel to be a screen region is also promising
- Recommend user testing of both options for low vision and blind users to see which is more preferable

**Single select reveals**
- Not great to reveal additional single selects when there is no indication that there are more 
- Looks like a multi select tree
   - Yes, but it's a multi select AND single select
   - Suggestion from Michael: could have each filter category as a separate tree 
- Do more research to see if we can find other instances of this pattern
- 
- Interesting filter panel from WCAG: https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_overview
