### ISSUE TITLE
[Horizontal rule] Contrast naming

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10139]
Currently, we use `low-contrast`, `medium-contrast`, and `high-contrast` to describe our `horizontal rule`'s contrast property. We should review this naming and ensure we align with Carbon core's naming.

Carbon border names:
- strong
- what is medium?
- subtle 

Additional:
- review naming implications with the developers

**[Design specs](https://www.figma.com/file/KoWNzmht96tub6ifyTTTpC/UI-component--horizontal-rule--1.0.1?node-id=1%3A4255&t=7enPaWKxsdFK323O-1)**

- [x]  Explore alternate naming
- [x]  Review with Jeannie, Olivia, and Rich
- [ ]  Update design specs
- [x]  Create Figma kit story
- [ ]  Create website update story
- [ ]  Create dev story

**Comment by oliviaflory** [comment]
No medium contrast token in v11

Propose to System squad:
- Add `border-medium` contrast token to replace `border-tile-01` token
- Use border-strong, border-medium, border-subtle

**Comment by RichKummer** [comment]
## Design crit 08/17/23

- We should still align contrast names around Carbon core.
- The `$border-strong-01` option is too close to current `medium-contrast`, only differing in the gray100 theme. 
- We should deprecate the `medium-contrast` option, and instead point adopters in v2 to use `high-contrast` (or the new Dotcom contrast name)

**Comment by RichKummer** [comment]
## Options

**Option 01: Reflects Carbon core token names**
- `subtle`
- `strong`

**Option 02: Retain contrast in naming**
- `subtle-contrast`
- `strong-contrast`

**Option 03: 1-to-1 with core token names**
- `$border-subtle-01`
- `$border-strong-01`
