### ISSUE TITLE
[Tag link] Clickable differentiator

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10135]
**To do:**
- [ ] Meet with AEM
- [ ] Discuss tag link and breadcrumb usage in `lead space`
- [ ] Discuss moving tag link to read-only. Are there implications for this route?
---

The `tag link` component can link users to other pages, unlike the current Carbon `tag` component. However, it does not have clear styling that indicates that the `tag link` would function differently. We should explore style options to better communicate that difference to the user. Consider border to show interactivity, along with updated interactive states.

Discussed 03/01/23 in Design Office Hours

**[Design specs](https://www.figma.com/file/NUFuuSCiKajRYm2SDPsKuC/UI-component--tag-link--visual-specs--1.0.0?node-id=1%3A22&t=44AlbtaPoQTCQ6il-1)**
**[Carbon clickable tag discussion](https://github.com/carbon-design-system/carbon/discussions/11215)**

**Comment by oliviaflory** [comment]
### Next steps
- [ ] Schedule a meeting with AEM
   - Discuss usage of tag link with Lead space
   - Is it utilized?
   - Could it be non-interactive to showcase dual hierarchy?
-  [ ] Tag link
   - Would it be horrible for AEM if we deprecated?
   - Double check with Gower how bad of a no-no is a tag link?

**Comment by oliviaflory** [comment]
### AEM notes
- _I don’t expect to see this being used very often, especially given the current issues with how our pages are organized. With that being said, I don’t expect them to be clickable._
- _We have NOT been specifying the tags in any of our template work. I know that the tags are available in AEM (and we have been specifying them for consistently when we extend the leadspaces in AEM) — but we don't have a use for them.  If people are following template guidance, usage should be zero in AEM — but is there is  usage, it should be EXTREMELY low._

**Comment by oliviaflory** [comment]
### Updates

- deprecating `tag link` and `tag group`
- lead space will use carbon read-only `tag` 
- card will use carbon read-only `tag`
