### ISSUE TITLE
[Image] Aspect ratio and removing border

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10141]
Our `image` component is intended to be flexible to display images at different aspect ratios. We should explore additional aspect ratios that `image` could appear in. We also should explore removing the border on `image` to align with accessibility enhancements.

**[Design specs](https://www.figma.com/file/yHgbUIu3x275nHfl48ffpG/UI-component--image--1.2--specs?node-id=1%3A964&t=ErXCWtSzjRn7cYSd-1)**

- [x] Explore additional aspect ratios
- [x] Explore removing the border as an option
- [x] Explore lightbox button: use an icon button? 
- [x]  Review with Jeannie, Olivia, and Rich
- [x]  Create design specs issue

**Comment by oliviaflory** [comment]
### Additional notes:
- Compare with Card in card 
- Border / no border
- If image is clickable would it use darker border like Tile?
- Lightbox button styling
   -  currently: dark
   - Should we use the icon button styling? (ref copy button) gray 10
   - Or primary?
   - type of Icon – AEM and Charts uses a different icon for expanding

**Comment by RichKummer** [comment]
Aspect ratios
* On the [IDL guidance site](https://www.ibm.com/design/language/photography/tips-and-techniques#aspect-ratio), the only listed aspect ratio we are missing is `3:2`

**Comment by RichKummer** [comment]
## Prototype feedback
[Figma prototype](https://www.figma.com/proto/FPfB8Fpa70INNOg2tCu2gs/Image-v2?page-id=402%3A3434&node-id=457-6814&viewport=3432%2C-328%2C0.35&scaling=min-zoom&starting-point-node-id=457%3A6814)
* Like the 85% version.
* Motion needs to be considered across the system if we were to apply it.
* Consider using a `cursor: zoom-in` style to change the cursor to a zoom icon. This reinforces the interaction.

**Michael feedback:**
> Since the icon is not itself the control, I did want to make the point that it doesn’t have to be nearly as prominent as this, in my opinion. Even the 70% starts at 7:1 and bumps up to 18:1 contrast. For accessibility alone, there is no reason it couldn’t be a lot less pronounced.
Like I said yesterday, if this were, say, a play video button, I think I’d be pushing for the icon to actually BE the control and get the focus, instead of the image (for example, since the focus goes to the image, no one on magnification is even going to see the icon) but even then it doesn’t have to be nearly as contrasted.
One thought I had today is that you’re assessing a quite dark and light image, but I think it’s probably a good idea to find a mid-tone image — or is there some rule that the image’s background must be in a certain range? Ultimately, I think it’s the contrast between the icon background and the icon symbol that provides the sufficient contrast here, so it matters a lot less if the square shape doesn’t contrast much with the image.
These are just musings. Ultimate message for accessibility: since there ain’t any text, 3:1 is all you have to meet — and you need to ensure the focus indicator also gets 3:1 minimum when it’s there. (Oh, and in the case where the icon did get the focus, we’d be getting a tooltip, which would also really help make it prominent.) (
