### ISSUE TITLE
[Card – logo] Logo placement

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10144]
The `card – logo` displays a logo asset at the top of the card, but may not be ideal. We need to be clear on how to use the component so it displays the logo in an easily readable way. At a lower priority, we should explore displaying the logo at the bottom.

Do we also include an icon to be in line with other card variants?

**[Card design specs](https://www.figma.com/file/iYaBsuyCTOKjhZIXLMA83u/UI-component--card--visual-specs-v3.2?node-id=32%3A6019&t=Sl5EtKaGFLenn8po-1)**

- [ ]  Design exploration
- [ ]  Review with Jeannie, Olivia, and Rich
- [ ]  Update design specs
- [ ]  Create Figma kit story
- [ ]  Update website with guidance
- [ ]  Create dev story

**Comment by oliviaflory** [comment]
Borrow from Juan <3

**Comment by oliviaflory** [comment]
complete
