### ISSUE TITLE
[Tabs extended with media] Merge with tabs extended and section heading optional

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10150]
We currently maintain two separate components with `tabs extended` in the name. We should explore a way to simplify the design system by merging `tabs extended media` into `tabs extended`

- Do we need a separate variant?
- How should this be merged?

We should also explore creating a knob for the section heading, increasing the flexibility of `tabs extended`.

**[Design specs](https://www.figma.com/file/AgvJ8iIHQ2VjCDtuRYZhIa/Layout-component--tabs-extended-media--visual-specs--1.2?t=oa6MO0p8bvKCQI3h-1)**

- [ ] Explore merging and section heading knob
- [ ]  Review with Jeannie, Olivia, and Rich
- [ ]  Update design specs
- [ ]  Create Figma kit story
- [ ]  Create website update story
- [ ]  Create dev story

**Comment by oliviaflory** [comment]
Tabs extended with media was deprecated in v2, adopters will now utilize tabs extended and add content item row on their own
