### ISSUE TITLE
[Content item horizontal] Rename

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10161]
The current `content item horizontal` has some shared visual elements with `content item`, but does not function in the same way. We should consider renaming or restructuring so that the difference is clear.

**[Design specs](https://www.figma.com/file/OlZyYZk5odev7dtjDiKT6j/Layout-component--content-item-horizontal--visual-specs--2.3?t=oa6MO0p8bvKCQI3h-6)** 

- [x] Explore renaming/restructuring for clarity
- [x]  Review with Jeannie, Olivia, and Rich
- [ ]  Update design specs
- [x]  Create Figma kit story
- [x]  Create website update story
- [x]  Create dev story

**Comment by oliviaflory** [comment]
Proposal: Content row
