### ISSUE TITLE
Masthead customProfilelogin

### ISSUE THREAD

**Issue by Stefan8412** [carbon-design-system/carbon-for-ibm-dotcom#10193]
### Description

we are using customProfileLogin which is working for most of languages but not working e.g for French language, if you try to login on https://www.ibm.com/docs/en you see correct "url" but when you are on French site https://www.ibm.com/docs/fr default ibm url is used

### Component(s) impacted

masthead/customProfileLogin[](url)
![Screenshot 2023-03-06 at 16 40 22](https://user-images.githubusercontent.com/57751227/223159308-19705726-b366-435c-858d-94619b822631.png)
![Screenshot 2023-03-06 at 16 43 49](https://user-images.githubusercontent.com/57751227/223159339-d0b72d23-3dac-434c-9b15-89cee66d2da5.png)

### Browser

Chrome, Safari, Firefox

### Carbon for IBM.com version

 "@carbon/ibmdotcom-react": "1.32.1",

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

https://www.ibm.com/docs/fr

### Package

@carbon/ibmdotcom-react, @carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/react/?path=/docs/components-masthead--default

### Steps to reproduce the issue (if applicable)

go to: https://www.ibm.com/docs/en , try to log in, hover over login button and see customProfileLogin url-which is correct
go to: https://www.ibm.com/docs/cs, try to log in, hover over login button and see customProfileLogin url-which is correct

go to: https://www.ibm.com/docs/fr, try to log in, hover over login button and see customProfileLogin url -which is not correct
got to: https://www.ibm.com/docs/it, try to log in, hover over login button and see customProfileLogin url -which is not correct

for some languages customProfileLogin url is set up correctly for some languages no

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
Can you share the code for where and how you are passing in the `customProfileLogin` prop to the Masthead?

**Comment by Stefan8412** [comment]
<Masthead
                  navigation={mastheadLinks}
                  platform={{
                    name: kcGlobals.translation['masthead.IBMDocumentation'],
                    url: `${window.location.origin}/${contextPath}/${language}`,
                  }}
                  hasProfile={!kcGlobals.darkshop}
                  customProfileLogin={profileLogin}
                  hasSearch={hasSearchBar}
                  placeHolderText={placeholder}
                  searchOpenOnload={searchbarOpen}
                  searchNoRedirect
                  customTypeaheadApi={debounceAsyncCall(docsTypeahead, 3)}
                  multiSection
                  initialSearchTerm={searchQuery ? searchQuery : null}
                />

**Comment by Stefan8412** [comment]
please add this "id" also to other translation files: arabic,italian,german,spanish,korean,russian

**Comment by annawen1** [comment]
PR with the translation team has been opened to add the `id` field missing in several translation files: https://github.ibm.com/webstandards/ibm-dotcom-translations/pull/869

@Stefan8412 please review and follow up with the translation team

**Comment by Stefan8412** [comment]
@annawen1 ,issue can be closed, customProfileLogin works as expected, thanks
