### ISSUE TITLE
[Component] Card – pictogram v2 updates

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10199]
### The problem

Going into v2, there are a few updates to `card – pictogram`:

- [x] Like the rest of `card`, there is an added border to align with [Carbon's v11 tile enhancement](https://carbondesignsystem.com/components/tile/usage/)

- [x] The hover reveal when using body copy is being removed. Instead, `card – pictogram` will have required heading and optional body copy that is displayed all in one view. If only heading is included, the dimensions of the card are locked, but if body copy is added, the card's height will expand to accommodate the added copy.
- [x]  Note that the pictogram should be bottom-aligned by default, with the option to swap to top-aligned. See #10195
- [x] Add arrow icon
- [x] Remove `outlined card` from Card style (storybook)
- [x] v11 color token updates
- [x] v11 type token updates 
- [x] heading changes to fixed style `$heading-03`

**[See updated design specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10195)**

![Card pictogram – specs](https://user-images.githubusercontent.com/15643582/223496094-1926c41f-3b1e-4558-903b-f51cd1bc85e0.png)

### Application/website

C4IBM.com

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

v2 updates

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by tlalka** [comment]
I reported a bug that is relevant to this component: #10960
