### ISSUE TITLE
[Figma] Card – pictogram v2 updates for border and hover

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10201]
**[Updated design specs](https://www.figma.com/file/oip4K9G1z0v7tLNBbDZzdr/Card-specs?node-id=148%3A5391&t=Q2X2shvChWMqko6f-1)**

We need to update the Figma design kit with the changes coming to `card – pictogram` in v2:
1. Like the rest of `card`, there is an added border to align with [Carbon's v11 tile enhancement](https://carbondesignsystem.com/components/tile/usage/). There will also be an icon in the lower right to match the other `card` components.
2. The hover reveal when using body copy is being removed. Instead, `card – pictogram` will have required heading and optional body copy that is displayed all in one view. If only heading is included, the dimensions of the card are locked, but if body copy is added, the card's height will expand to accommodate the added copy.
3. Note that the pictogram should be bottom-aligned by default, with the option to swap to top-aligned. See #10195

**Comment by oliviaflory** [comment]
In Figma!
