### ISSUE TITLE
[Video Player]: Address console errors when video player is being used within <dds-tabs-extended-media>

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#10228]
### Description

- The following are console errors we discovered when using the video media within `<dds-tabs-extended-media>`.
- Code Sandbox: https://codesandbox.io/s/purple-hill-x0xm5e?file=/index.html | https://x0xm5e.csb.app/

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'backgroundMode')
    at F.value (video-player-container.js:112:48423)
    at F.performUpdate (lit-element.js:228:6778)
    at F._enqueueUpdate (lit-element.js:228:6289)
```
- The video-player-container was previously using ownerDocument where getRootNode() should have been. This lead to a problem where .getElementById was returning null and then we tried to access non-existent properties of null.
- The video-player on firstUpdated wants to use it's parent container's value of backgroundMode. This was wrongly assuming a video-container always existed as a parent and that it's value of backgroundMode is always set
- Related JIRA ticket - https://jsw.ibm.com/browse/ADCMS-2137
![Screen Shot 2023-03-13 at 3 17 25 PM](https://user-images.githubusercontent.com/1815714/224812803-c6e2e328-30d9-461d-abf3-edb5dbb90739.png)

### Component(s) impacted

Video Player

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v1.44.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM, Code Sandbox

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/purple-hill-x0xm5e?file=/index.html

### Steps to reproduce the issue (if applicable)

- Click on the second tab
- Check browser console errors

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
.
