### ISSUE TITLE
enabled-range option on date-picker - weird behavior using CDN

### ISSUE THREAD

**Issue by smitan1394** [carbon-design-system/carbon-for-ibm-dotcom#10236]
### Description

when I try the knobs on the story it works fine. But when I try it with CDN, on my page, it's strangely causing a value of "2023-03-10/2023-03-20" to show me a calendar for year 2028 and the month of August.

### Component(s) impacted

enabled-range option on date-picker

### Browser

Firefox

### Carbon for IBM.com version

v1.29.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

https://wwwstage.ibm.com/university/power/

### Package

@carbon/web-components

### CodeSandbox example

https://web-components.carbondesignsystem.com/?path=/docs/components-date-picker--range-with-calendar

### Steps to reproduce the issue (if applicable)

no sandbox given in docs, I tried using CDN version v1.29.0 and the code given in docs - enabled-range option

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
the issue is that the default date format is 'm/d/Y' so either changing the enabled-range value to "3-10-2023/3-20-2023" OR setting the date-format attribute to 'Y/m/d' works

I will open a PR to make the knob description more clear
