### ISSUE TITLE
[Tab Index Tabbing bug]

### ISSUE THREAD

**Issue by mo-alaa** [carbon-design-system/carbon-for-ibm-dotcom#10265]
### Description

There are 3 issues with the tab index; I attached a video for that.

The issues happen while tabbing through (using tab button) the tab index:

1. Tab never goes to the second tab.
2. When we hit tab one more time, it goes to the tab container (div with “bx--tab-content” class), not the actual contents (carousel card).
3. Also, it makes a strange outline on that div, I believe a workaround for this can be setting the outline of this class “bx--tab-content” on focus to “initial”, but I can’t do this from my side because it’s in shadow DOM.

### Component(s) impacted

https://user-images.githubusercontent.com/41386480/227885934-2d3a8a6e-2f0f-4284-be06-ce69a46656aa.mp4

### Browser

Chrome

### Carbon for IBM.com version

v1.28.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

ibm.com/impact

### Package

@carbon/web-components

### CodeSandbox example

https://codesandbox.io/s/nice-mendel-cmxi0b

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
This tabbing pattern matches [the recommended UI patterns of the W3CWAI](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/).

When a tab has focus, tabs can be switched using the arrow keys and enter. Tabbing should move focus into the selected tab panel.
