### ISSUE TITLE
[Documentation not shown properly]: @carbon/ibmdotcom-web-components storybook

### ISSUE THREAD

**Issue by FlashGooden** [carbon-design-system/carbon-for-ibm-dotcom#10282]
### Description

The coding documentation on the `Getting Started` page is showing the `typeof` primitives instead of proper command documentation. 

<img width="1146" alt="Screenshot 2023-03-29 at 11 57 39 AM" src="https://user-images.githubusercontent.com/12440399/228597499-350c10d2-b4b8-43cb-a88d-254eafc30f31.png">

### Component(s) impacted

Storybook `Getting Started` Page
<img width="1146" alt="Screenshot 2023-03-29 at 11 57 39 AM" src="https://user-images.githubusercontent.com/12440399/228597499-350c10d2-b4b8-43cb-a88d-254eafc30f31.png">

### Browser

Chrome

### Carbon for IBM.com version

v1.29.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

IBM Widgets

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/react/?path=/story/overview-getting-started--page&knob-Aria-label:=Pictogram%20description&knob-Card%20Eyebrow%20(eyebrow):=Label&knob-Card%20Heading%20(heading):=Standard%20Bank%20Group%20prepares%20to%20embrace%20Africa%E2%80%99s%20AI%20opportunity&knob-Card%20Href%20(href):=https://example.com&knob-Card%20heading%20(heading):=Explore%20AI%20use%20cases%20in%20all%20industries&knob-Card%20href%20(href):=https://example.com&knob-Card%20type:=Card%20-%20default&knob-Cards%20per%20row:=dds-ce-demo-devenv--cards-in-row-3&knob-Grid%20mode:=collapsed&knob-Heading%20(heading):=Lorem%20ipsum%20dolor%20sit&knob-Image%20alt%20text%20(alt):=Image%20alt%20text&knob-Image%20src%20(defaultSrc):=3d9ceb3516be4517e20a044ca4722e6f.jpg&knob-Link%20with%20Icon%20copy:=Lorem%20ipsum%20dolor&knob-Link%20with%20Icon%20href:=https://example.com&knob-Number%20of%20cards=5&knob-Number%20of%20cards:=5&knob-Offset:=0&knob-Pictogram%20(required)=Desktop&knob-Pictogram%20color:=blue

### Steps to reproduce the issue (if applicable)

Head to : [Getting Started](https://www.ibm.com/standards/carbon/web-components/react/?path=/story/overview-getting-started--page&knob-Aria-label:=Pictogram%20description&knob-Card%20Eyebrow%20(eyebrow):=Label&knob-Card%20Heading%20(heading):=Standard%20Bank%20Group%20prepares%20to%20embrace%20Africa%E2%80%99s%20AI%20opportunity&knob-Card%20Href%20(href):=https://example.com&knob-Card%20heading%20(heading):=Explore%20AI%20use%20cases%20in%20all%20industries&knob-Card%20href%20(href):=https://example.com&knob-Card%20type:=Card%20-%20default&knob-Cards%20per%20row:=dds-ce-demo-devenv--cards-in-row-3&knob-Grid%20mode:=collapsed&knob-Heading%20(heading):=Lorem%20ipsum%20dolor%20sit&knob-Image%20alt%20text%20(alt):=Image%20alt%20text&knob-Image%20src%20(defaultSrc):=3d9ceb3516be4517e20a044ca4722e6f.jpg&knob-Link%20with%20Icon%20copy:=Lorem%20ipsum%20dolor&knob-Link%20with%20Icon%20href:=https://example.com&knob-Number%20of%20cards=5&knob-Number%20of%20cards:=5&knob-Offset:=0&knob-Pictogram%20(required)=Desktop&knob-Pictogram%20color:=blue)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by osenbach** [comment]
Until fixed, does it make sense to paste the instructions here?

**Comment by jeffchew** [comment]
This is referencing the following README:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/README.md

@kennylam is this in an upcoming sprint to fix?
