### ISSUE TITLE
[ToC horizontal] research and exploration

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10323]
## The Problem
Horizontal ToC and Tabs have the same visual stying which may cause some confusion for the user if the appear of the same page.

**ToC Horizontal**
<img width="1093" alt="Screenshot 2023-04-10 at 3 48 34 PM" src="https://user-images.githubusercontent.com/45692622/230985131-4ad91966-63ae-4a40-a971-42a63eb4c8e0.png">

**Tabs contained**
<img width="453" alt="Screenshot 2023-04-10 at 3 49 35 PM" src="https://user-images.githubusercontent.com/45692622/230985147-021cb531-7757-44dd-9647-8275652916e2.png">

### Notes from the review with accessibility team
Horizontal TOCs need some disambiguation with tablists. But there are clear differences in navigation and interaction
1. For the tablist, the entire tabpanel is updated when a tabitem is activated. Focus does not move from the tablist on activation,BUT pressing Tab once should move the user to either the entire tabpanel, or to the first item with focus in the tabpanel.
2. Unlike a tabpanel, activating a TOC item does not alter/replace content on the page; it simply repositions the user.
3. Also unlike a tabpanel, the focus does not stay in the TOC when activated. It repositions to the top of the content in the main viewing area (as discussed under 1c above).
4. One possible way of disambiguating the two constructs is to handle the focus interaction and visual cueing on the whole component (the tablist takes a single tab stop and is navigated by arrow keys; the TOC is a series of individual tabstops)
5. There is SOME possibility of consideration a TOC as a continuum between tabpanels, content switches and TOCs; however, we did not explore this at all.
6. A simple solution is to not allow horizontal TOCs (they were offered to appease the Drupal, and their main advantage is that it does not take up horizontal space)
7. Discussed a potential to do a dropdown TOC which may be easier to differentiate
8. Discussed the idea of not ‘deprecating’ but not promoting it.

ACTION: Determine what options we have to prioritize work (not just for TOC but for any component). Is it tactically valid to de-prioritize one thing as well as prioritize something else for remediation?

## Next steps
- [x] Review use case
   - [x] Do we need a horizontal TOC?
      -  We've seen AEM and other teams utilize this variant, we would like to give it a shot to re-design before deprecating.
   - [ ] Sync with AEM
- [x] Design exploration

### Design exploration

**Reference previous materials**
- Anchor link [research](https://ibm.ent.box.com/folder/125209461240?s=7uwea74prz96dv699bk2wo5vqccvp1jz) Mural + Box note
- [ToC horizontal explorations](https://ibm.ent.box.com/folder/125209461240?s=7uwea74prz96dv699bk2wo5vqccvp1jz) from Olivia first rounds
- Gatsby explorations (need to get from Jeannie
- [Drupal example](https://www.ibm.com/about?lnk=flathl)

**Research**
- Look for other examples throughout other websites
   - See if [original sites researched](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1603978906503?sender=oliviaflory3358&key=e058cb19-fe51-47de-8c8a-d340e4ee5548) in 2021 are still utilizing anchor links
   - Consider how many levels of navigation there are on the page

**Considerations**
- Cannot look like tabs or other navigation like UI shell or Dotcom masthead
- How many levels of navigation will we see on a page? 
  - L0 (required)
  - L1 (optional, but becoming more common?)
  - L2 (table of contents)

**Comment by RichKummer** [comment]
**[Figma research and explo](https://www.figma.com/file/LXkFJXaeY81NXFwkcwI4ul/Horizontal-ToC-Research?type=design&node-id=0%3A1&t=cg78Q6qdJmxHmLMk-1)**

1. For accessibility, [Ram brought up](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10322#issuecomment-1588264607) using arrow keys to navigate a tab structure. We're also moving in that direction with table of contents -vertical, and the horizontal version could work exactly the same. This doesn't do enough in my opinion to differentiate `ToC` from `tabs` visually (still worth exploring).
2.

**Comment by RichKummer** [comment]
## Design crit 06/16/23
- Gower – make sure as you are tabbing content on the page, the start of the page content should be *below* the `ToC` . This way it’s visible as user is tabbing.
    - Need to make sure **selected** state and **focus** state can co-exist. The user needs to be able to arrow through selections and tell which is focused and which is selected.
- Use same tab functionality as vertical – they should be identical (use the tab region, arrow through selections)
- Mike feedback – vertical and horizontal variants should ideally look visually similar. Explore bringing the two orientations into alignment.
- Anna – Carbon doesn’t use shadows, but perhaps we could use shadows when user scrolls and it stickies at the top of the screen(this happens currently).
- Tracey – for vertical indicator, you could explore using motion to shift the selection state.
- Explore:
    - (Mike’s feedback) use underline, try dark underline with dark selection in vertical
        - Gray and white
    - Floating shadow version
    - Similar to current but with dark gray as selection
        - Gray and white
    - Vertical indicator - blue and gray 100
        - Gray and white
- We should also look at how does it behave beyond max? Extend width of window or lock to grid?
