### ISSUE TITLE
[Number input]: Formatted input for decimal numbers not working

### ISSUE THREAD

**Issue by lyyka** [carbon-design-system/carbon-for-ibm-dotcom#10331]
### Description

Expected: When using `bx-number-input` with `step="0.01"`, typing in "2,55" (in that order), the input should accept that

What happened instead: Typing "," (a comma) returns typing cursor to the beginning of the input. So typing in 2, then comma will result in just "2" with typing cursor before "2". Typing a comma again will result in ",2".

### Component(s) impacted

bx-number-input

### Browser

Chrome

### Carbon for IBM.com version

1.26.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

internal tools

### Package

@carbon/web-components

### CodeSandbox example

Codesandbox for bx-number-input does not compile

### Steps to reproduce the issue (if applicable)

Typing "," (a comma) returns typing cursor to the beginning of the input. So typing in 2, then comma will result in just "2" with typing cursor before "2". Typing a comma again will result in ",2".

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@lyyka the `@carbon/web-components` package follows the functional and design specifications from the `@carbon/react` package. `NumberInput` does not accept commas in the React version of the component - it's not a valid number. If you'd like to discuss this feature request further, you can do that [here](https://github.com/carbon-design-system/carbon).
