### ISSUE TITLE
White background for side navigation

### ISSUE THREAD

**Issue by Arunkarthik13** [carbon-design-system/carbon-for-ibm-dotcom#10348]
### The problem

I am getting grey color for side navigation and background also same when I am clicking side navigation link. I want to change this one. The url I am using is: https://web-components.carbondesignsystem.com/

### The solution

I want white background for side navigation when it clicked

### Application/website

IBMLink

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Hi @Arunkarthik13 the intended color for a selected item within the side navigation is gray to ensure the user can distinguish which link or sub-item is selected or active. We do not recommend changing the colors as they have been carefully selected to ensure they are consistent across all IBM products and pass accessibility requirements.

![Screenshot 2023-04-17 at 10 22 01 AM](https://user-images.githubusercontent.com/45692622/232516086-5283bca5-d05d-4963-b068-16fad4598d07.png)


Here is an example of the expected design based on the white theme or gray 10 theme:

**White theme example**
![Screenshot 2023-04-17 at 10 26 16 AM](https://user-images.githubusercontent.com/45692622/232516456-7feaea90-6283-4731-838a-9afb19d65497.png)

**Gray 10 theme example**
![Screenshot 2023-04-17 at 10 26 30 AM](https://user-images.githubusercontent.com/45692622/232516505-9bc49b45-281a-41af-91ba-e66f9369dfee.png)
