### ISSUE TITLE
Bug in 1.26.0 Datepicker

### ISSUE THREAD

**Issue by crichtonibm** [carbon-design-system/carbon-for-ibm-dotcom#10341]
### Description

Seems a bug in 1.26.0 for Date picker that was not there in 1.21.0.  Visit: https://web-components.carbondesignsystem.com/?path=/story/components-date-picker--single-with-calendar  and open and select a date. It will work as expected and fire the event. Open it again and try to select another date. It fires the event, but does NOT actually select the value. Then click again and it WILL select date and fire yet again.

### Component(s) impacted

bx-date-picker. Use the 1.26.0 story to verify issue as described above: https://web-components.carbondesignsystem.com/?path=/story/components-date-picker--single-with-calendar

### Browser

Chrome, Firefox

### Carbon for IBM.com version

v1.26.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

IBM Customer Connect (https://www.ibm.com/technologyconnect)

### Package

@carbon/ibmdotcom-web-components, @carbon/web-components

### CodeSandbox example

https://web-components.carbondesignsystem.com/?path=/story/components-date-picker--single-with-calendar

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by sillysillyc** [comment]
same problem

**Comment by kennylam** [comment]
Fixed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10603.
