### ISSUE TITLE
[Label not being set]: Label-text attribute does not work on date-picker-input

### ISSUE THREAD

**Issue by lyyka** [carbon-design-system/carbon-for-ibm-dotcom#10355]
### Description

Label-text attribute does not work on date-picker-input, label is not displayed at all

Expectation is for the label to be set

### Component(s) impacted

date-picker-input

### Browser

Chrome

### Carbon for IBM.com version

1.26.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

internal app

### Package

@carbon/web-components

### CodeSandbox example

/

### Steps to reproduce the issue (if applicable)

set label-text attribute on date-picker-input

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by IgnacioBecerra** [comment]
Issue seems to have been resolved for a while now, closing.
