### ISSUE TITLE
Add subitems to the table of contents

### ISSUE THREAD

**Issue by radarfox** [carbon-design-system/carbon-for-ibm-dotcom#10363]
### The problem

We have the new feature request coming from out design team. We would like to add subitems to selected ToC items. Having the single level of subitems should work for us for now (no need for subitems in subitems), but it might be nice to keep the API compatible with multiple levels, so they can be added in the future.

We would like to use it for the following pages:

- [Research areas of labs](https://research.ibm.com/labs/india#research-areas)
- [Headings entered by researchers in their profiles](https://research.ibm.com/people/abu-sebastian) (we are still considering this)

We are using the React implementation of ToC.

### The solution

![2023-04-20](https://user-images.githubusercontent.com/16005791/233314188-2da7b9ea-1c62-44fc-ad95-44ddd648c27b.png)

On SM and MD breakpoints, subitems could be implemented with [the `<optgroup>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup).

Showing / hiding of subitems on LG and larger breakpoints could be probably accomplished, by adding / removing some property (like `hideItems`) from the parent item. But we are open to some other approach to this problem, that would satisfy our needs.

```
const headingItems = [
  {
    type: 'local',
    copy: 'DevOps',
    cta: {
      href: 'https://github.com/carbon-design-system/carbon-web-components',
    },
    // We would set the following prop to `false` (default), when the user would reach certain `scrollTop`.
    hideItems: true,
    items: [
      {  type: 'local', copy: 'Foo', ... },
      {  type: 'local', copy: 'Bar', ... },
    ],
  },
];
```

### Application/website

https://research.ibm.com/

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

Upcoming release would be great. Some labs are already using this "research areas" section and there are more labs that will be migrated soon.

### Examples

- [Here, is the list of some similar ToC libraries, most of them have subitems.](https://www.jqueryscript.net/blog/best-table-contents-plugins.html)
- [`react-toc` have subitems controlled by `highestHeadingLevel` and `lowestHeadingLevel`](https://github.com/K-Sato1995/react-toc)
- [`rehype-toc` is also having subitems generated from different heading levels](https://github.com/JS-DevTools/rehype-toc)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Closing due to no response
