### ISSUE TITLE
Left alignment of Lead Space with search 

### ISSUE THREAD

**Issue by StefanieSchraub** [carbon-design-system/carbon-for-ibm-dotcom#10364]
### The problem

Currently the **Lead Space with search bar** is centred on the page and the header is in bold large font. 

All our webpages on a microsite are left aligned in the header section. Except the one webpage that has a search bar. If we strictly follow the Carbon Design template for "Lead space with search bar", we have to use it a center aligned on that page. 

### The solution

My request is to add and  allow a "Lead space with search bar" Carbon design that is left aligned so it is consistent with the pages on the rest of our microsite. 

### Application/website

https://www.ibm.com/about/software-licensing/product_search

### Business priority

High Priority = pressing release

### What time frame would this ideally be needed by (if applicable)

A fast approval that Carbon design for the lead space with search bar can also be used in left alignment. Later to add an example of it to the carbo design guidelines. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by mjabbink** [comment]
I have a different proposal first.

- [ ] To adjust the headline text in the Search lead space so it is in the same place as the other lead space title copy (reference image below)

- [ ] Update text in Search lead space to with the following:

Search IBM licensing & ordering information

or

Search IBM offerings, licensing & ordering information

Title type should all be the same styling: same  size, same weight (Plex Sans Light)

<img width="1627" alt="Screenshot 2023-04-21 at 1 57 23 PM" src="https://user-images.githubusercontent.com/32881239/233714076-8fa5abf8-bcd2-40d5-b3d8-4b473f58b089.png">
———
<img width="1590" alt="Screenshot 2023-04-21 at 1 44 25 PM" src="https://user-images.githubusercontent.com/32881239/233714116-c1cba0c1-1c62-48e9-912e-744c7fb14a47.png">

**Comment by mjabbink** [comment]
The placement in the center columns is less of an issue since it intends to align with the results. Having the title “shift’ to the right right to maintain vertical alignment and integrity to the content adds dynamics and supports content and column-driven typography.

Once the above `priority` issues are resolved, we can take another look to see if placing the title to “also” be in the left side of the lead space is a good variation to add in the future. For now, the centered placement is less of an issue than implementing the details I outlined.

**Comment by StefanieSchraub** [comment]
Thanks for the advice, @mjabbink 
Did your suggestion mean to only have the descriptive lines on the page header or have "Product Search" in light and the descriptive text in same height and weight? 

<img width="418" alt="image" src="https://user-images.githubusercontent.com/25322302/234037195-10ce2f36-f152-4480-b847-33ce162e1cb0.png">
