### ISSUE TITLE
[Image]: Enable aspect-ratio on the <dds-image> so that it aligns with the SVG viewbox

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#10380]
**JIRA ticket:** https://jsw.ibm.com/browse/ADCMS-3234

----------

### The problem

- From **Daniel Ratzenböck** - See slack thread (https://ibm-marketing-comms.slack.com/archives/G01LKRP5RB6/p1682066909914929)
  - On AEM we now provide the option for authors to select a crop for SVGs for different breakpoints. Using the `#svgView`  parameter in the source sets. I am then picking the `viewBox` per breakpoint. https://www.w3.org/TR/SVG2/linking.html#SVGFragmentIdentifiersDefinitions.
  - The problem is that if I don't set width and height on the `img` tag the svg will always render with its original aspect ratio. E.g. the SVG is 16:9, but the viewbox is 1:1 - the svg in the image tag will defer the 1:1 viewbox and scale it to 16:9. To bypass that I am setting the `aspect-ratio` css attribute to 1/1  on the `dds-image` .
  - But this works only if there is no caption ("heading" attribute).

### The solution

- Add an `aspect-ratio` prop/attribute on the `<dds-image>` that allows adopters to find the image container aspect ratio (eg. 1:1, 16:9) that aligns with the picking of the viewBox per breakpoint.

### Application/website

AEM

### Business priority

Medium Priority = upcoming release but is not pressing

### Examples

- Daniel, can you provide screenshots or a test page of what you’re seeing in AEM? Thanks!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by dratzenboeck-ibm** [comment]
As requested the screenshots. You see even though I set the aspect ratio on `dds-image` to a landscape aspect ratio the svg renders in portrait. The aspect-ratio on `dds-image` is ignored (only if the `heading` attribute is set).
![image](https://user-images.githubusercontent.com/85555103/233935935-ffe46912-299f-4315-8537-0b951d4eac94.png)

It works fine if there is no caption:
![image](https://user-images.githubusercontent.com/85555103/233936311-ee4bf2ce-4700-4649-893c-a3213035d6bb.png)

If the `aspect-ratio` is passed down to the `img` tag in the shadowroot it would work. This is my current workaround:
```
const IMAGES_WITH_CAPTION = "dds-image[heading]";

function passAspectRatioToImg(element) {
    let aspectRatio = getComputedStyle(element).aspectRatio;
    if (aspectRatio && parseFloat(aspectRatio)) {
        let img = element.shadowRoot.querySelector(".bx--image__img");
        img.style.aspectRatio = aspectRatio;
    }
}

function processImages() {
    const elements = document.querySelectorAll(IMAGES_WITH_CAPTION);
    elements.forEach(passAspectRatioToImg);
}

if (document.readyState !== "loading") {
    processImages();
} else {
    document.addEventListener("DOMContentLoaded", processImages);
}
```

**Comment by proeung** [comment]
@dratzenboeck-ibm Thank you for sharing your workaround for this issue! I'm adding this to our queue for this sprint.
