### ISSUE TITLE
[Homepage v2][Search Bar]: Integrating a next.js app into a web component

### ISSUE THREAD

**Issue by andy-blum** [carbon-design-system/carbon-for-ibm-dotcom#10406]
JIRA ticket: https://jsw.ibm.com/browse/ADCMS-3252

---------
### Summary

Part of the ibm.com homepage v2 design efforts are placing a product search bar in a leadspace component. The search bar at ibm.com/products appears to be a `next.js` app.

What recommendations/questions does your team have?

### Design Specs
- Figma specs - https://www.figma.com/file/uG4Q1olV9VaAJo5eTQXpkV/IBM.com?node-id=1810-207918&t=jOEKz1k2HhqtI6hl-0

![Screen Shot 2023-04-27 at 11 40 26 AM](https://user-images.githubusercontent.com/1815714/234915022-463cb1ea-43bc-4daa-8983-8e055ae6b1cf.png)
![LG - Products](https://user-images.githubusercontent.com/1815714/234915056-45106d1a-f31e-429e-a73e-c48116210052.jpg)

### Name and organization

AEM

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment]
@andy-blum Have you been in contact already with Dave McDuff or Nixon Cheaz?  I believe the search team built the product search as a service as its used on the developer.ibm.com site too.

**Comment by andy-blum** [comment]
I have not - I did just speak with @kennylam & team in the engineering office hours and they said we might be able to use the search-with-typeahead component with a custom endpoint.
