### ISSUE TITLE
[cwc-v2] Wrong button size

### ISSUE THREAD

**Issue by abdonrd** [carbon-design-system/carbon-for-ibm-dotcom#10428]
### Description

Looks like there is a wrong button size in the `@carbon/web-components` v2 beta:

Note that I manually change the button size to 400px.

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/beta/carbon-web-components-v2/?path=/story/components-button--default:
<img width="1449" alt="Screenshot 2023-05-06 at 11 29 56 AM" src="https://user-images.githubusercontent.com/1007051/236633418-e43c22f8-2d4b-486f-9f5b-86deb35fb03b.png">

https://web-components.carbondesignsystem.com/?path=/story/components-button--default:
<img width="1449" alt="Screenshot 2023-05-06 at 11 29 59 AM" src="https://user-images.githubusercontent.com/1007051/236633419-af5463a2-6ecf-4c63-a33d-6a5d55b8c97b.png">

### Component(s) impacted

Button

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v2 beta

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

-

### Package

@carbon/web-components

### CodeSandbox example

-

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by abdonrd** [comment]
Fixed with a `flex-grow: 1;` in the native `part="button"`.

**Comment by oliviaflory** [comment]
@abdonrd Could you provide any additional information on what you are expecting the button width to be? 

Buttons are intended to be flexible, with a 64px padding on the right side, so the v2 storybook is working as expected.

![Image](https://user-images.githubusercontent.com/45692622/236854900-ef8b0e0a-756b-440c-93ab-b3db2c36f45a.png)

**Comment by abdonrd** [comment]
Thanks for the answer, @oliviaflory!

When we apply a custom width (`width: 400px;`) to the button in v1, the button width is 400px:
<img width="1449" alt="Screenshot 2023-05-06 at 11 29 59 AM" src="https://user-images.githubusercontent.com/1007051/236633419-af5463a2-6ecf-4c63-a33d-6a5d55b8c97b.png">
(https://web-components.carbondesignsystem.com/?path=/story/components-button--default)

When we apply a custom width (`width: 400px;`) to the button in v2, the button width is 400px, but the blue background don't change:
<img width="1449" alt="Screenshot 2023-05-06 at 11 29 56 AM" src="https://user-images.githubusercontent.com/1007051/236633418-e43c22f8-2d4b-486f-9f5b-86deb35fb03b.png">
<img width="1382" alt="Screenshot 2023-05-08 at 11 34 20 AM" src="https://user-images.githubusercontent.com/1007051/236866447-bb80fdd7-deaa-48d9-9b03-7ecc00a10727.png">
(https://carbon-design-system.github.io/carbon-for-ibm-dotcom/beta/carbon-web-components-v2/?path=/story/components-button--default)

We expect to fill the 400px like:

<img width="1382" alt="Screenshot 2023-05-08 at 11 34 52 AM" src="https://user-images.githubusercontent.com/1007051/236866620-90ee4ce4-8ff2-4739-8712-f40b376086c6.png">

**Comment by oliviaflory** [comment]
@abdonrd thank you for the clarification. I will check with our development team to ensure the button is behaving correctly.

Please be sure to read the [button alignment documentation](https://carbondesignsystem.com/components/button/usage/#alignment) from the Carbon website and ensure your use-case for defining a custom button width is following our guidance. It's unusual that we'd set a fixed width like 400px, but is difficult to know the context of the buttons placement without a screen shot of your in-product experience.
- We would typically let the button width be defined by the text content within the button. 
- Alternatively the button can be "fluid" and align to the grid or other components.

**Comment by abdonrd** [comment]
@oliviaflory I can share this screenshot:

<img width="979" alt="Screenshot 2023-05-08 at 12 39 23 PM" src="https://user-images.githubusercontent.com/1007051/236880830-76fc66d5-4b14-46ed-aa9b-2e3b82291740.png">

When we update to v2:

<img width="981" alt="Screenshot 2023-05-08 at 12 42 22 PM" src="https://user-images.githubusercontent.com/1007051/236881267-1dbc7b84-debc-489b-96e4-c7d73d40e370.png">

**Comment by oliviaflory** [comment]
@kennylam going to pass this back to you to size and schedule. The screen shots immediately above show the issue they're having in context.

**Comment by abdonrd** [comment]
Sharing an example:

https://stackblitz.com/edit/vitejs-vite-1cq7x7?file=index.html

**Comment by abdonrd** [comment]
Closed by https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10615
