### ISSUE TITLE
[NextJS template]: v2 of project should use react wrappers

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10479]
As Carbon for IBM.com v2 will no longer support React, the [carbon-for-ibm-dotcom-nextjs-template](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template) application should be updated to use web component React Wrappers.

**Comment by oliviaflory** [comment]
- Not critical for v2 launch
- Might not necessarily need, we could utilize the test app
