### ISSUE TITLE
[WC Select]: Select options do not appear in the right place when using non-desktop view

### ISSUE THREAD

**Issue by DoaaRadwan** [carbon-design-system/carbon-for-ibm-dotcom#10487]
### Description

When clicking the select web component, the options appear in the top left of the screen (very far away from the select) when using mobile view (not desktop view) on chromium-based browsers

You can see it in the Items per page picker in pagination controls in the image below 

![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/24454169/bccd1038-4200-44b0-af3b-55fbfb3d1a3f)

### Component(s) impacted

Web components: [Select](https://carbondesignsystem.com/components/select/usage)
Web components: [Pagination](https://carbondesignsystem.com/components/pagination/usage)

### Browser

Chrome, Microsoft Edge

### Carbon for IBM.com version

v1.27.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

st4sd

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbondesignsystem.com/components/select/usage/#live-demo

### Steps to reproduce the issue (if applicable)

https://carbondesignsystem.com/components/pagination/usage#live-demo
https://carbondesignsystem.com/components/select/usage/#live-demo

Open inspect and responsive then click the select item 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ariellalgilmore** [comment]
Hi @DoaaRadwan , this looks like a chrome specific issue for responsive mode. if you test on an actual device the select options work properly 



![Image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/20210594/236a4811-eee9-4d93-8893-fd88c4e5f286)



![Image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/20210594/01659924-e4fa-47c9-95d8-cd70d79fb870)
