### ISSUE TITLE
[Cloud Masthead]: Correct masthead links for test cloud docs

### ISSUE THREAD

**Issue by Kieran-Muller** [carbon-design-system/carbon-for-ibm-dotcom#10488]
### Description

Within the IBM internal domain https://test.cloud.ibm.com/docs the `Docs` link within the navigation bar should be for `test.cloud.ibm.com/docs` and not `cloud.ibm.com/docs`. It should be consistent to the domain the user is on. When looking for test.cloud.ibm.com related items, it makes sense to use links that keep users within that domain as it contains information specific to the test cloud environment not found in the [cloud.ibm.com/docs](http://cloud.ibm.com/docs) domain. 

Feel free to Slack me on internal channels if necessary.

### Component(s) impacted

This effects the component: [packages/web-components/src/components/masthead/cloud](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/71b5a4dd409a1fc4cb1ad33dc2f7546b49ae9134/packages/web-components/src/components/masthead/cloud)

### Browser

Firefox

### Carbon for IBM.com version

n/a

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

test.cloud.ibm.com/docs

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

Not possible.

### Steps to reproduce the issue (if applicable)

This is an IBM internal problem for those who have access to https://test.cloud.ibm.com. 

To reproduce, go to https://test.cloud.ibm.com/docs or any subsequent docs page and click the "Docs" link in the masthead. This will then take you to the https://cloud.ibm.com/docs site.

### Release date (if applicable)

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@andy-blum @jkaeser FYI.
