### ISSUE TITLE
Autocomplete attribute from bx-input is not working in Firefox

### ISSUE THREAD

**Issue by Arunkarthik13** [carbon-design-system/carbon-for-ibm-dotcom#10498]
### Description

In my code autocomplete is on for bx-input and I continuously searching one field in chrome and firefox. In chrome when I'm selecting same field getting previous search but not in Firefox. Please help me to resolve

### Component(s) impacted

The code I'm using:
![bx-input](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/30830178/c71a8f8e-0128-4969-b838-e952c3c850ef)

When I'm inspecting input field in chrome:
![autocomplete_Chrome](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/30830178/81ac6ef2-0f04-40bf-8cbb-3201d6e5adc2)

When I'm inspecting same field in firefox getting below: 
![automcomplete_firefox](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/30830178/c64b494c-77ad-488d-8bbe-f096fb996aa0)

### Browser

Chrome, Firefox

### Carbon for IBM.com version

v1.21.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

IBMLink

### Package

@carbon/web-components

### CodeSandbox example

Code provided above

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ariellalgilmore** [comment]
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10540
