### ISSUE TITLE
[Masthead footer offline support]: Footer crashes when running in offline electron

### ISSUE THREAD

**Issue by Properko** [carbon-design-system/carbon-for-ibm-dotcom#10503]
### Description

We're packaging our IBM Documentation site in a [standalone offline package](https://www.ibm.com/docs/en/offline) for viewing docs. It can be run over intranet with web browsers, or on a single machine in electron.

If the user's machine doesn't have internet access, the Footer component is not able to download the necessary files and crashes. 

The following network calls fail and prevent the footer from working:
- https://1.www.s81c.com/common/carbon-for-ibm-dotcom/translations/masthead-footer/usen.json
- https://1.www.s81c.com/common/js/dynamicnav/www/countrylist/jsononly/usen-utf8.json

Can you bundle at least some minimal fallback files directly with the component, please, or is there another carbon library we can bundle that will provide this fallback?
_(We'd prefer a way to avoid the network calls completely, is that possible?)_ 

Expected:
<img width="1778" alt="image" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/8216356/fc52c8bb-8c78-4155-b19b-39b08442778b">

Actual:
<img width="1778" alt="image" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/8216356/44110fb5-e7a3-4600-9644-49d806ddcdc7">

### Component(s) impacted

Footer

### Carbon for IBM.com version

^1.33 - 1.47

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

https://www.ibm.com/docs/en/offline

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

Enable network request blocking in chrome here
https://uhsr6q-3000.csb.app/
![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/8216356/81f54440-254f-4dea-93d7-40743f97d673)

Source: https://codesandbox.io/p/sandbox/naughty-beaver-uhsr6q?file=%2Fsrc%2FApp.js

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@Properko We could implement a fallback to render the footer if the data doesn't load. @oliviaflory @RichKummer something like this?



![Image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/909118/d5619cd1-23d6-4233-b502-ee0db4cf85cf)

**Comment by Properko** [comment]
> @Properko We could implement a fallback to render the footer if the data doesn't load. @oliviaflory @RichKummer something like this?
> 
> ![Image](https://user-images.githubusercontent.com/909118/242055908-d5619cd1-23d6-4233-b502-ee0db4cf85cf.png)

Preventing the crash would be better than nothing IMO. But is there any way you could also provide the language switcher? We use it to let the user switch the language of the app and content. Otherwise we'll prolly have to code our own footer.

**Comment by kennylam** [comment]
Currently there is no method to bundle localized versions of the footer. The only way would be to fork and add the capability to load the data from another (local) endpoint. But if the app is offline, what will happen when a user clicks a link?

**Comment by Properko** [comment]
It'll open an external browser with the link, which will fail to load the site.
The language switcher is entirely local though. We only populate it with languages that the app is available in. 
In languageCallback we reload the page so the UI and content loads with the chosen language.

**Comment by Properko** [comment]
Forking would probably be overkill as we only use the micro footer.
If it's difficult/not sensible for you to support the offline use-case you can close this and we'll probably roll our own footer imitating the carbon style.
Thank you :)

**Comment by kennylam** [comment]
Ok yes, sounds good. There aren't any plans for offline data but if anything changes we will reach out!
