### ISSUE TITLE
[content-block-cards with-video]: Kaltura thumbnails not sized properly

### ISSUE THREAD

**Issue by andy-blum** [carbon-design-system/carbon-for-ibm-dotcom#10522]
### Description

JIRA: https://jsw.ibm.com/browse/ADCMS-3370

card-cta video thumbnails appear blurry

### Component(s) impacted

Card-CTA video type, as seen on https://ibm.com/products/envizi/resources

<img width="1201" alt="Screenshot 2023-05-30 at 11 06 37 AM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/25532785/9b4a1684-c2eb-47cd-88e4-26c1361e86ca">

---

This may be limited to the card-cta component, as the video-player-container seems unaffected at https://www.ibm.com/products/envizi/scope-1-2-ghg-accounting-reporting

<img width="783" alt="Screenshot 2023-05-30 at 11 08 34 AM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/25532785/d2908b59-d6f8-4bae-9274-93b0e9586ee4">

### Browser

Chrome

### Carbon for IBM.com version

v1.46.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://ibm.com/products/envizi/resources

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by m4olivei** [comment]
Fixed and merged to main.
