### ISSUE TITLE
[Footer] color exploration

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10559]

**Comment by RichKummer** [comment]
**[Figma exploration](https://www.figma.com/file/2zfgWaWHSIZeK3lzwNOE5o/Footer-color-exploration?type=design&node-id=0%3A1&mode=design&t=RUlUhxghvt4c0nPU-1)**

**Comment by RichKummer** [comment]
## Overview:
* Our goal is to explore color schemes for the footer that fit within the lighter and brighter branding. Currently, Footer is locked to the gray 90 theme.
* Should footer match the page theme? This way, it wouldn’t be a jarring transition on any page.

## Layout explo
* Current version leans to the right to match content. If we go this route, perhaps we could remove a border or two (looks overcomplicated with multiple borders)
* We could also spread the links across more columns, creating additional breathing room.
* Border on top might be necessary to separate more cleanly from page content.
* Leaning towards using an alt tertiary button for locale selector to fit visually among the rest of the Footer elements. We cannot use a link with icon.
* Leaning towards using an alt tertiary button for locale selector to fit visually among the rest of the Footer elements. We cannot use a link with icon.

**Comment by RichKummer** [comment]
# Design crit 06-29-23
## Layout
* Between the right clustered and full-width versions, the right clustered links use an exaggerated margin which helps the logo stand out.
* Cloud has their own footer, which uses a full-width design with limited links out.
* As the footer changes the number, organization, or density of links, the right clustered version may be more forgiving/resilient. Full-width might get difficult if the links become unbalanced.

## Accessibility
* As users scroll through a page and encounter a high contrast moment, some users may find that disruptive from an accessibility perspective. More reason to consider either on-theme footers or adjacent-theme footers.

## Next steps
* We should talk to the IA guild to see what changes they might be considering. If they are looking to make drastic changes, we should consider that in the redesign.

**Comment by RichKummer** [comment]
## Adjunct link treatment

1. Adjunct links always appear in the last four columns
2. Adjunct links always appear below the secondary links as a new row
3. Adjunct links are added and wrapped to the next row if needed.

![Image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/15643582/1ea6aa87-eeb1-422b-b039-344f906811fa)
