### ISSUE TITLE
[Pagination selection doesn't match actual rows shown]: pagination items per page selection shows 5 when the actual rows showing are 10

### ISSUE THREAD

**Issue by DoaaRadwan** [carbon-design-system/carbon-for-ibm-dotcom#10553]
### Description

In [pagination](https://web-components.carbondesignsystem.com/?path=/docs/components-pagination--default) `bx-pagination` when used with the [data table](https://web-components.carbondesignsystem.com/?path=/docs/components-data-table--sortable-with-pagination) the `:page-size` doesn't match the `bx-page-sizes-select` selected `option` (what is displayed on the screen to the user as the selected value in the drop down menu) on reload of the table. 

![Screenshot 2023-06-12 at 9 58 47 am](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/24454169/06bf6c15-7a6f-4f3c-8c45-ebf3e8b5dd14)

![Screenshot 2023-06-12 at 10 19 38 am](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/24454169/fe6bc40e-c631-49bf-b223-8325ed1658ce)

If the user chooses 10 and the table is reloaded though a `v-if  v-else` the table will show 10 rows (since the variable for `:page-size` doesn't get reseted) while the items per page selection returns back to default to 5. The selection can't be changed in code, so there is no work around.

### Component(s) impacted

1. [Data table](https://web-components.carbondesignsystem.com/?path=/docs/components-data-table--sortable-with-pagination)
2. [Pagination](https://web-components.carbondesignsystem.com/?path=/docs/components-pagination--default) 

### Browser

Chrome

### Carbon for IBM.com version

v1.27.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

https://registry.st4sd.res.ibm.com/registry-ui/

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/carbon-web-components/examples/codesandbox/basic/components/data-table

### Steps to reproduce the issue (if applicable)

1. Have more than 10 rows in a data table.
2. Have the options for the selection be 5 10 20
3. Have a v-if v-else on the table
4. If user selects 10 rows then v-if v-else triggers 
5. When table renders back the actual rows showing will remain 10
6. But the selection will be 5

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by m4olivei** [comment]
Also note that for v2 of CWC, although there is a knob intended to set `page-size`, the story as it's written doesn't actually use the knob, so it's hard to do the same testing. I'll get a PR up to correct that. After we get that in place, I don't think we'll see the same issue in v2, there has [been some refactoring there.](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10420). After that's sorted out, I also have a fix in mind for v1 that I'll get up a PR for as well.

**Comment by m4olivei** [comment]
> Also note that for v2 of CWC, although there is a knob intended to set page-size, the story as it's written doesn't actually use the knob, so it's hard to do the same testing. I'll get a PR up to correct that.

I've filed and issue and PR for this:

Issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10882
PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10883
