### ISSUE TITLE
[web-components]: audit DOM node sizes for all components

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10563]
This issue tracks the effort to audit DOM node sizes for all components in the `@carbon/ibmdotcom-web-components` package. Some components have an excessively high node count which not only impacts performance, but some adopter teams are reporting adverse effects on tooling such as analytics.

Once the components are prioritized work can begin in optimizing the code. This work has already been done to the `masthead` component via lazy loading components that are not in use (see work [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9582)).

**Comment by IgnacioBecerra** [comment]
Audit completed, can be found here:
https://ibm.box.com/s/3ldm506qnnrygzljhc23a56n1j66u8kf
