### ISSUE TITLE
[Grid alignment]: Noticing grid alignment issues using the Carbon for IBM.com CDN artifacts

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#10579]
### Description

When reworking the IBM.com Web Standards page (https://www.ibm.com/standards/web), it was noticed that there seems to be some alignment issues with various Content Block components inside the dotcom container. Interestingly, the alignment of the Leadspace is fine.

Related PR with some discussion around it:
https://github.ibm.com/webstandards/standards-website/pull/24

![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1641214/60e98b4a-d6a6-430e-9b2e-e80ddd245bc0)

![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1641214/18c8dcb6-7db3-49ee-88ba-63426d28cb82)

![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1641214/eec770ac-0f7b-470e-9668-12d1391ff8b5)

### Component(s) impacted

Various content block components.

### Browser

Chrome

### Carbon for IBM.com version

Latest (using the latest tag for CDN links)

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://www.ibm.com/standards/web

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/standards/web

### Steps to reproduce the issue (if applicable)

Source code here:
https://github.ibm.com/webstandards/standards-website/blob/main/src/index.html

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ariellalgilmore** [comment]
Hey @jeffchew , this can be fixed by wrapping the `content-section` components in with divs containing `bx--grid` and `bx--row. See example: https://stackblitz.com/edit/web-platform-8k7jjp?file=index.html. i'll create a pr in the standards-website repo with the update
