### ISSUE TITLE
IBM.com style models

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#1058]
### User story
As an IBM.com user, I'd like to be able to navigate through IBM.com pages in a consistent and coherent way where I don't have to learn how to use IBM.com on every page I land on.

### Notes
Both the current IBM.com and the new IBM.com pages coming out of our immediate adopters are very organic with room for better alignment with each other. In order to mitigate this issue, we need to create style models for different sections or stages of IBM.com. Some initial studies have been done, which is available on this [Abstract project](https://share.goabstract.com/e92b9f27-2e95-4ef8-ad0d-f056f692fa56?).

### Acceptance criteria
- [ ] Style models have been created for the initial adopters (DGC squads +)

**Comment by RobertaJHahn** [comment]
Closing as this work is managed on the Ideation Board.
