### ISSUE TITLE
[cwc-v2]: The tertiary buttons doesn't have the right color when dark theme

### ISSUE THREAD

**Issue by abdonrd** [carbon-design-system/carbon-for-ibm-dotcom#10604]
### Description

We have this:

<img width="392" alt="Screenshot 2023-06-26 at 4 04 14 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/5190327b-6471-4b39-875a-178cf4016bb8">

When we expect this:

<img width="382" alt="Screenshot 2023-06-26 at 4 05 06 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/737feeb1-b235-455f-aea6-70caa2d6da7b">

### Component(s) impacted

button

### Carbon for IBM.com version

v2 beta

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

-

### Package

@carbon/web-components

### CodeSandbox example

https://stackblitz.com/edit/github-gkn31f-t9dbqi?file=assets%2Fmain.scss

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
This should be a relatively easy style (token) fix: we could reference the styles on the [Carbon website](https://carbondesignsystem.com/components/button/style#tertiary-button)

**Comment by abdonrd** [comment]
We have the same issue with other components like tags:

https://stackblitz.com/edit/github-gkn31f-arsqkc?file=app.vue

<img width="465" alt="Screenshot 2023-07-14 at 7 27 25 AM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/1c74c514-458d-4dc1-8c92-d74aaa55308f">

**Comment by annawen1** [comment]
This happens with the button/tag/notification components as they have specific theming tokens - the solution we have for now would be to have the adopter import those 3 component styles from `@carbon/styles`. PR with documentation coming

**Comment by abdonrd** [comment]
@annawen1 is it possible to import only the tokens and not all component styles?

**Comment by ariellalgilmore** [comment]
@abdonrd a pr was just open here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10758. but for example you would just need to import `'@carbon/styles/scss/components/button';` for button

**Comment by abdonrd** [comment]
@ariellalgilmore but this import all the button styles, not just the button tokens, right?

**Comment by abdonrd** [comment]
Something like this?

```scss
@use '@carbon/styles/scss/components/tag/tokens' as tag-tokens;
@include theme.add-component-tokens(tag-tokens.$tag-tokens);
```

**Comment by ariellalgilmore** [comment]
oh yes. we will update to the above^. thanks @abdonrd
