### ISSUE TITLE
[cwc-v2]: Allow change the `cds-side-nav` width

### ISSUE THREAD

**Issue by abdonrd** [carbon-design-system/carbon-for-ibm-dotcom#10613]
### Description

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/beta/carbon-web-components-v2/?path=/story/components-ui-shell--header-base-w-navigation-actions-and-side-nav

![Screenshot 2023-06-27 at 4 36 03 PM](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/507448ba-e5a2-4d62-b74b-7ffd695ac870)

Currently, changing the width it's not allowed (at least in a way offered by the component itself) because there is no part and/or custom property to do it.

### Component(s) impacted

UI Shell

### Carbon for IBM.com version

v2 beta

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Package

@carbon/web-components

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by abdonrd** [comment]
We should take into account that, in addition to the `width`, there is also a `max-width`.

**Comment by abdonrd** [comment]
@oliviaflory any update on this? Thank you!

**Comment by oliviaflory** [comment]
Hi @abdonrd apologies that this fell off my radar! Would one of your designers be able to answer the question from our previous [Slack thread](https://ibm-studios.slack.com/archives/C0M053VPT/p1688061073344899?thread_ts=1687973692.097669&cid=C0M053VPT)? _Does your team have a proposal for how this would affect the page grid? I assume this is a grid influencer panel?_ 

The UI shell and left panel are core building blocks of the design system and have a lot of thought and logic behind how they behave and perform with our grid, we have to be really thoughtful about opening up something like the max width of the left panel. So having a proposal and example of how it could effect other screens would be really helpful. Thank you!

**Comment by atalle** [comment]
Hi @oliviaflory! I'm a designer who works with @abdonrd. I'm happy to to think through the implications of this update, although I don't fully understand what we need to consider with regards to max-width. Can you explain that? 

Also, we're only increasing the width of the fixed panel by 16px to accommodate a second icon. Would you want me to explore a panel width that's wider than 272px, or is this width okay? 

Lastly, my team does not have other product screens that would be impacted by this update. Do you have any mockups / layouts with influencer panels I could solve for, so I don't have to create a design from scratch?

**Comment by atalle** [comment]
Hi @jeanservaas! Thank you so much for following up here. This is definitely not a Sev 1 problem, not sure why it was tagged that way. In all honesty, I was pulled into this late yesterday and should have dug into the issue before asking my questions.

@abdonrd and I discussed alternative treatments and decided to revert back to the default width and wrap titles to two lines to preserve legibility.

Please feel free to close this issue. Thanks! 

![Screenshot 2023-07-19 at 10 43 27 AM](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/66145951/81267137-e7f3-462f-96da-1c2851e40067)

**Comment by oliviaflory** [comment]
Thanks @atalle, @abdonrd, and @jeanservaas !
