### ISSUE TITLE
Tab size too small for translated terms and wrong word division

### ISSUE THREAD

**Issue by StefanieSchraub** [carbon-design-system/carbon-for-ibm-dotcom#10645]
### Description

This is an issue with translations that can require more the 25% additional space. The tab is on two lines but the word division is wrong. 
Can we

1. make the width of a tab extend automatically with the length of the word if two lines don't suffice 
2. use standard word division according to their language rules and not because the line ends including the - as word separator?

example see screenshots
Licensing Guides
translates to German
Lizenzierungsleitfäden

which is displayed on UI in two lines as
Lizenzierunsleitf
äden

But the word can only be split in the following ways
Lizen-zie-rungs-leit-fä-den
Benutzerhandbücher as User Guides can only be split as
Be-nutzer-hand-bü-cher

### Component(s) impacted

Tab width does not autosize

![image (12)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/25322302/741cba9a-d635-41f0-8e5f-6cca3946657c)

Workaround is to manually divide the words at the correct places but that is only acceptable short term. The problem can occur in other languages as well that have compound words rather than single words making up compounds. 

### Browser

Safari, Firefox

### Carbon for IBM.com version

most recent

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://www.ibm.com/about/software-licensing/de-de/licensing/guides

### Package

@carbon/ibmdotcom-web-components, @carbon/web-components

### CodeSandbox example

n/a see link

### Steps to reproduce the issue (if applicable)

switch to the German language on the website if it defaults to English. 

### Release date (if applicable)

live

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
https://github.com/mdn/browser-compat-data/issues/18987 says the chrome info is out-of-date, and points to this [chromium code search](https://source.chromium.org/chromium/chromium/src/+/main:third_party/hyphenation-patterns/hyb/). If that's indeed the case, then chrome/edge/ff/safari should support the majority of IBM's supported language/browser combinations.
