### ISSUE TITLE
[Locale modal]: optimize component to lower DOM node count

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10657]
[JIRA](https://jsw.ibm.com/browse/ADCMS-3579)

Currently this component has a DOM node count which can be lowered. Solutions to consider are removing duplicate/unnecessary nodes and lazy loading content.

Node audit

| Nodes| Comments | Inters |
|--------|--------|--------|
| 2734 | 770 | 1155 |

**Comment by ljcarot** [comment]
@kennylam might be good time to redesign the locale modal

**Comment by andy-blum** [comment]
@kennylam @ljcarot I think there's work on this underway from @areagan1030

**Comment by areagan1030** [comment]
@kennylam @ljcarot @andy-blum Yes, we do have some work in the pipeline being guided by Joseph Dombroski. Putting a push on getting this to a good spot, so we can set up some time to share with Carbon team and keep this moving forward.
