### ISSUE TITLE
[Dropdown]: Able to change siblings and skeleton tag name WebComponents

### ISSUE THREAD

**Issue by nolrinale** [carbon-design-system/carbon-for-ibm-dotcom#10660]
### The problem

Per this example
https://codesandbox.io/p/sandbox/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/carbon-web-components/examples/codesandbox/styling/custom-style?file=%2Findex.html%3A1%2C1

It is possible to extend the main dropdown component class and rename it's tag and apply new styles, however is not possible to achieve this with it's siblings <my-dropdown-item> neither the skeleton component <my-dropdown-skeleton>

However if you manually extend the BXDropdownItem or BXDropdownSkeleton component you will lose all the component functionality.

### The solution

Several companies seem to be using Carbon these days and their design systems with WebComponents and internal procedures forces the developers to change all the tag names of all the components, my proposal is to allow for these kind of compound components to allow easily to rename their tags including their siblings tags to match the naming scheme from 3rd party design systems 

### Application/website

Government

### Business priority

High Priority = pressing release

### What time frame would this ideally be needed by (if applicable)

Well this is a fairly big project but is not the first time I see this as in previous work experiences in my circle of companies everyone seem to be using Carbon these days as well so I think more and more people will begin to request more from Carbon from all kinds of companies and projects. 

### Examples

In this example
https://codesandbox.io/p/sandbox/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/carbon-web-components/examples/codesandbox/styling/custom-style?file=%2Findex.html%3A1%2C1

Ideally you want to be able to change the tag names of the siblings just like the example changes the tag name of the parent component <my-dropdown> in this case. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
Issue tracked in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10677
