### ISSUE TITLE
[Content block media]: optimize component to lower DOM node count

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10668]
Currently this component has a DOM node count which can be lowered. Solutions to consider are removing duplicate/unnecessary nodes and lazy loading content.

| Component | Nodes| Comments | Inters |
|--------|--------|--------|--------|
| Content block media - with link list | 1542 | 264 | 759 |
| Content block media | 1333 | 231 | 643 |

**Comment by andy-blum** [comment]
I don't think this component is worth attempting to optimize - it's DOM size is a symptom of being a suite of other components
