### ISSUE TITLE
[docs]: update `@carbon/web-components` documentation for v2

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10676]
With the upcoming production release of `@carbon/web-components` v2, all documentation must be updated.

```[tasklist]
### Things to look out for
- [ ] update Storybook docs examples
- [ ] update any path changes
- [ ] update new, removed, or changed components and component names
```

**Comment by annawen1** [comment]
Closing this ticket and adding to this [epic](https://github.com/orgs/carbon-design-system/projects/56/views/1?filterQuery=&pane=issue&itemId=33709751) instead
