### ISSUE TITLE
[Tabs extended]: optimize component to lower DOM node count

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10672]
Currently this component has a DOM node count which can be lowered. Solutions to consider are removing duplicate/unnecessary nodes and lazy loading content.

| Component | Nodes| Comments | Inters |
|--------|--------|--------|--------|
| Tabs extended | 883 | 141 | 458 |

**Comment by andy-blum** [comment]
Fixed in #10650
