### ISSUE TITLE
[Card group - with card in card]: optimize component to lower DOM node count

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10670]
Currently this component has a DOM node count which can be lowered. Solutions to consider are removing duplicate/unnecessary nodes and lazy loading content.

| Component | Nodes| Comments | Inters |
|--------|--------|--------|--------|
| Card group - with card in card and media | 844 | 118 | 475 |
| Card group - with card in card | 673 | 100 | 382 |

**Comment by andy-blum** [comment]
I don't think this component is worth attempting to optimize - it's DOM size is a symptom of being a suite of other components
