### ISSUE TITLE
[cwc-v2] The ui shell app switcher does not open

### ISSUE THREAD

**Issue by abdonrd** [carbon-design-system/carbon-for-ibm-dotcom#10695]
### Summary

Do you know how to use the ui shell app switcher?

It looks like the storybook it's now working.

Thanks!

### Relevant information

The story `Header Base w/ Actions and Switcher` from `@carbon/web-components@2.0.0-rc`:

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/rc/carbon-web-components-v2/?path=/story/components-ui-shell--header-base-w-actions-switcher

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/fef4d07e-7532-48f3-b7bf-5cef2bd6d58f

The story `Header Base w/ Actions and Switcher` from `@carbon/react`:

https://react.carbondesignsystem.com/?path=/story/components-ui-shell--header-base-w-actions-and-switcher

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/ee576665-75b5-4a64-b579-9ed9efd5866c

### Name and organization

IBM

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@abdonrd Looks like this is a bug.

**Comment by abdonrd** [comment]
@kennylam I just create https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10710

But I'm not sure how you want to manage the change of the `expanded` property.
Does the ui-shell offer something like the `cds-header-menu-button` for the panel?

**Comment by abdonrd** [comment]
@kennylam another option could be add a new property to the `cds-header-menu-button` to change the icon and event to work with the `cds-header-panel` instead of the `cds-side-nav`?

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/feat/cwc-v2/packages/carbon-web-components/src/components/ui-shell/header-menu-button.ts

**Comment by abdonrd** [comment]
@kennylam another question... Could we add the overlay to the panel?

### The `cds-side-nav` overlay

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/dce7e62d-69d2-46ab-9a40-d247ad8f8fef

### The missing `cds-header-panel` overlay

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/3dcee4e0-1ebb-42c3-acb2-db019d381ac6

**Comment by annawen1** [comment]
@abdonrd Answering above question, I believe the `header-panel` has a different function to the `side-nav` where user can still visually access information on the page while the panel is open. With the `side-nav` focus is maintained on the navigation. I'm sure the Carbon core team can answer better than I can, I would say if you're expecting certain styles or features and they aren't present in the [Carbon core React storybook](https://react.carbondesignsystem.com/?path=/docs/getting-started-welcome--welcome) you can ask in the #carbon-design-system slack channel as we don't make the design decisions for the Carbon core components, we only ensure that our web components `@carbon/web-components` package is in sync with their React counterparts 😄

**Comment by abdonrd** [comment]
@annawen1 got it, thanks!
