### ISSUE TITLE
[@carbon/web-components]: compile list of improvments in v2

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10698]
Create list of improvements in v2 of `@carbon/web-components`.

```[tasklist]
### Tasks
- [ ] build times
- [ ] file sizes (artifacts, modules, CDN, etc)
- [ ] page load/draw times
```

**Comment by abdonrd** [comment]
Nice tool to check the npm package size: https://pkg-size.dev

- https://pkg-size.dev/@carbon%2Fweb-components
  - Install size: 49MB / 14 packages
  - Bundle size: 2MB minified (235KB gzip) / 293 modules

- https://pkg-size.dev/@carbon%2Fweb-components@2.0.0-rc.2
  - Install size: 78MB / 26 packages
  - Bundle size: 2.2MB minified (273KB gzip) / 336 modules
