### ISSUE TITLE
Ability to add custom items to masthead profile

### ISSUE THREAD

**Issue by kshah11** [carbon-design-system/carbon-for-ibm-dotcom#10704]
### The problem

I am not able to add custom items to the masthead profile

### The solution

Ability to add custom menu items to the masthead profile - use case would be to add a 'Portal settings' for our page; as opposed to have it in the left hand menu where it feels out of place

### Application/website

ideas.ibm.com

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

We want to add our user preferences/settings page as part of the coming iterations, so as soon as this feature would be be available would be great

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment]
@kshah11 Your site does not appear to be responsive on mobile . Have you built this site using the Carbon grid?

**Comment by kshah11** [comment]
@ljcarot yes we have used the carbon grid

**Comment by kennylam** [comment]
@andy-blum FYI

**Comment by andy-blum** [comment]
After consultation with @areagan1030 and her team, we're electing to close this issue. The masthead is a global, foundational component and customizations are not aligned with that purpose.

**Comment by areagan1030** [comment]
This was also captured on PMOWEB-666, which I have also cancelled.
