### ISSUE TITLE
[Lead space centered] Image placement enhancement

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10727]
Future enhancement beyond v2 launch.

The current dotcom `lead space centered` keeps the background media behind the heading content in desktop breakpoints, and drops the background media on smaller breakpoints. The product imagery guild is seeking a way to have the background media appear below the heading content across breakpoints, to better showcase product UI in a device frame. 

We should explore a new variant for `lead space centered` that allows for this orientation/placement across breakpoints.

![Image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/15643582/edaa07f1-bd63-431e-a2ee-b7df1de71f3d)

**Comment by oliviaflory** [comment]
Component working as expected (proposal above), but need to open a bug on v2 behavior for large breakpoint
