### ISSUE TITLE
[Pricing Table]: Not visible in the Components list, nested under Pictogram

### ISSUE THREAD

**Issue by iBetaChantelle** [carbon-design-system/carbon-for-ibm-dotcom#10737]
JIRA: https://jsw.ibm.com/browse/ADCMS-3666

### Description

Expected:
When viewing the Web Components int he Storybook ( )User expects to find the Pricing Table in the Components list where it can be expanded and the component easily viewed.

Actual Result:
When viewing the Web Components in the Storybook, the Components list does not display "Pricing Table" as one of the listed components.  However, if the user searches for the Pricing Table component they will find the pricing table component examples is nested under the Pictogram Item after the search result for Pricing Table is selected. (See Screenshot)

Steps to Reproduce:
1. Launch https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/
2. Examine the Components list for the "Pricing Table" 
3. Observe the "Pricing Table" is not visible in the list of Components
4. Input into the "Find Components" search field : Pricing Table
5. Select the "Pricing Table" from the results
6. Observe the Pricing Table component examples are shown nested under the "Pictogram" in the components list

![Screenshot 2023-07-25 083002](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4239003/c4c83bee-ef53-4ad4-9a83-455253e5380f)
![Screenshot 2023-07-25 083023](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4239003/4ac1b63b-9c03-4844-97b8-c666ed8542c1)
![PricingTableMissingFromList](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4239003/774b7ae9-8720-4445-92a3-94197194271c)

### Component(s) impacted

Pictogram Item in the Components List
Pricing Table

### Carbon for IBM.com version

v1.49.0-rc.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

QA -C4IBM library testing

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

None

### Steps to reproduce the issue (if applicable)

Steps to Reproduce:
1. Launch https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/
2. Examine the Components list for the "Pricing Table" 
3. Observe the "Pricing Table" is not visible in the list of Components
4. Input into the "Find Components" search field : Pricing Table
5. Select the "Pricing Table" from the results
6. Observe the Pricing Table component examples are shown nested under the "Pictogram" in the components list

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@andy-blum FYI

**Comment by andy-blum** [comment]
@marcelojcs will be doing this work.
