### ISSUE TITLE
[Web Components Styling]: Wondering how to style carbon web components with inline or CSS styles

### ISSUE THREAD

**Issue by aaronmg241** [carbon-design-system/carbon-for-ibm-dotcom#10776]
### Summary

Hello,

I am just attempting to change the color of the <bx-btn> web component so that it has a border/text color of red. I've tried adding styles with the "styles" inline property, adding a custom CSS class, and targeting the generated CSS class (.bx--btn--tertiary), but none of these seem to work.

Just wondering if anyone has any insight on how to best accomplish this. I am using the Web Component library in a Flask app rendering HTML with Jinja2.

Any help is greatly appreciated!

Aaron

### Name and organization

Aaron

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Hi @aaronmg241! Carbon web components provides the tertiary button in a `danger` variant with a red border and text as seen in the [storybook](https://web-components.carbondesignsystem.com/?path=/story/components-button--default) under the `button kind` knobs: 
<img width="946" alt="Screenshot 2023-08-07 at 10 46 49 AM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/45692622/dc70774c-13dc-4ce0-b406-e13b7ae0f876">
