### ISSUE TITLE
[Content Item Horizontal w/ Featured Media]: Horizontal overflow on `sm` breakpoint

### ISSUE THREAD

**Issue by andy-blum** [carbon-design-system/carbon-for-ibm-dotcom#10841]
JIRA: https://jsw.ibm.com/browse/ADCMS-3757

### Description

When the viewport is less than 383px wide, the featured media item overflows its container and causes a horizontal scrollbar to appear. This is because the featured media item is placed on a grid four columns wide, but is told to span 12 columns. The grid auto-creates grid tracks 5-12 and the grid-gaps stack up causing the item to overflow its container.

Component at <383px

<img width="307" alt="Screenshot 2023-08-17 at 12 46 05 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/25532785/b1d0e2ea-11ea-40f8-90d2-91758bdbdee6">

<img width="370" alt="Screenshot 2023-08-17 at 12 45 44 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/25532785/f2d8165c-6f4c-4c2c-9181-ef7c4a281291">

Component at 1055px:
<img width="1056" alt="Screenshot 2023-08-17 at 12 45 25 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/25532785/e14e7e46-fabe-4357-8a3a-0db856935fad">

Component at 1056px:
<img width="1055" alt="Screenshot 2023-08-17 at 12 45 14 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/25532785/48f2e988-e064-4327-abfc-96f80616f607">

### Component(s) impacted

Content Item Horizontal

### Browser

Chrome

### Carbon for IBM.com version

latest v1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/iframe.html?id=components-content-item-horizontal--with-media-featured&viewMode=story

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Completed in Release 1.50 and in this PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10857
