### ISSUE TITLE
[Component] update Scroll animations to v2

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10854]
Update component tokens to Carbon v11. Refer to migration docs [here](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md#carbonmotion).

**Comment by ShatilKhan** [comment]
Hi, can I work on this?

**Comment by kennylam** [comment]
> Hi, can I work on this?

Sure!
