### ISSUE TITLE
Upgrade Carbon for IBM.com and Angular 11

### ISSUE THREAD

**Issue by nayeem-s1** [carbon-design-system/carbon-for-ibm-dotcom#10909]
### Description

I was trying to upgarde from angular 10 to 11, While upgradation i'm getting the below errors in IBM.com web components v14.0. 

Error: node_modules/@carbon/ibmdotcom-web-components/es/components/footer/language-selector-desktop.d.ts:9:16 - error TS2304: Cannot find name 'DDSLanguageSelectorDesktop'.

9 export default DDSLanguageSelectorDesktop;
         ~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@carbon/ibmdotcom-web-components/es/components/footer/language-selector-mobile.d.ts:9:16 - error TS2304: Cannot find name 'DDSLanguageSelectorMobile'.

9 export default DDSLanguageSelectorMobile;
         ~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@carbon/ibmdotcom-web-components/es/components/search-with-typeahead/scoped-search-dropdown-mobile.d.ts:9:16 - error TS2304: Cannot find name 'DDSScopedSearchDropdownMobile'.

9 export default DDSScopedSearchDropdownMobile;
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: node_modules/@carbon/ibmdotcom-web-components/es/internal/vendor/@carbon/web-components/components/input/input.d.ts:746:9 - error TS2611: 'value' is defined as a property in class '{ _getValidityMessage(state: string): string; _testValidity(): string; invalid: boolean; required: boolean; requiredValidityMessage: string; validityMessage: string; value: string; ... 288 more ...; focus(options?: FocusOptions): void; } & { ...; } & LitElement', but is overridden here in 'BXInput' as an accessor.

746   get value(): string;

### Component(s) impacted

@carbon/ibmdotcom-web-components, @carbon/web-components

### Browser

Chrome

### Carbon for IBM.com version

1.14.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

N/A

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://stackblitz-starters-ncahhg.stackblitz.io

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
Hi @nayeem-s1, this was resolved in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11069.
