### ISSUE TITLE
[DDSDotcomShellContainer navigation links]: Navigation displays default 

### ISSUE THREAD

**Issue by kshah11** [carbon-design-system/carbon-for-ibm-dotcom#10900]
### Description

When setting custom navLinks, the masthead still shows the default values

### Component(s) impacted

DDSDotcomShellContainer
Stackblitz example: https://stackblitz.com/edit/github-setaig?file=src%2Findex.js 

### Browser

Chrome

### Carbon for IBM.com version

v1.34.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

ideas.ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://stackblitz.com/edit/github-setaig?file=src%2Findex.js 

### Steps to reproduce the issue (if applicable)

Create a blank component
Set custom `navLinks` values
In some cases, the links are loaded as default, in other cases when the page is refreshed they change to the default 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@kshah11 Custom navigation links should be passed to `masthead` and not `dotcom-shell`. We'll double-check the documentation to make sure this is clear.

https://stackblitz.com/edit/github-setaig-zvbu7h

**Comment by kshah11** [comment]
@kennylam thanks!
I seem to be getting a tsx error when trying to replicate the above, are you able to help with this?
`
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: ComponentProps | Readonly<ComponentProps>): DDSMastheadComposite', gave the following error.
    Type '{ title: string; titleEnglish: string; url: string; }[]' is not assignable to type 'string'.
  Overload 2 of 2, '(props: ComponentProps, context: any): DDSMastheadComposite', gave the following error.
    Type '{ title: string; titleEnglish: string; url: string; }[]' is not assignable to type 'string'.
`
