### ISSUE TITLE
[Web-components] Checkbox implementation differs from figma

### ISSUE THREAD

**Issue by korgan00** [carbon-design-system/carbon-for-ibm-dotcom#10910]
### Description

I was trying to implement a form using radio buttons and checkboxes and I saw that they are so different between them and looking at the Figma file, I saw some differences between the implementation and the Figma library.

| Element  | Figma | Implementation |
| ------------- | ------------- | ------------- |
| Padding between label-text and checkbox  |  8px (0.5rem) | 6px (0.375rem)  |
| Checkbox margins  | all: 0.125rem  | left: 0.1875rem  the rest: 0.125rem |
| <label> tag  | none (the min-height can be inferred if the checkbox is not `absolute`) | `min-height: 1.5rem; padding-top: 0.1875rem; padding-left: 1.25rem;`  |
| host margin-bottom | none | 0.25rem |
| screen capture | ![Captura de pantalla 2023-09-05 a las 18 54 52](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4138279/1bb4b812-4447-40b3-b288-c1131a0e2d86) | ![Captura de pantalla 2023-09-05 a las 19 02 54](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4138279/40ec4edd-6282-48d4-82a6-125716891930) |

### Component(s) impacted

Checkbox

### Carbon for IBM.com version

v2.0.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

IBM Quantum Learning

### Package

@carbon/web-components

### CodeSandbox example

https://web-components.carbondesignsystem.com/?path=/story/components-checkbox--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RichKummer** [comment]
Hey @korgan00 , same thing as #10911. Can you create this ticket in the [carbon react repo](https://github.com/carbon-design-system/carbon/issues/new/choose)?

**Comment by korgan00** [comment]
Looking at the react implementation, the differences from here are bigger. I think it is related to `box-sizing`.

**Comment by abdonrd** [comment]
Fixed here: https://github.com/carbon-design-system/carbon/issues/14628

So updating the version should solve it here.
