### ISSUE TITLE
[Web-components]: Radio-button implementation differs from figma

### ISSUE THREAD

**Issue by korgan00** [carbon-design-system/carbon-for-ibm-dotcom#10911]
### Description

I was trying to implement a form using radio buttons and checkboxes and I saw that they are so different between them and looking at the Figma file, I saw some differences between the implementation and the Figma library.

| Element  | Figma | Implementation |
| ------------- | ------------- | ------------- |
| radio margins  | vector image  | top 0.0625rem, right: 0.5rem, bottom: 0.125rem, left: 0.125rem |
| Spacing between label-text and radio  |  8px (0.5rem) | none (uses radio button right margin but it is 8px and it should be 8+2px because of the extra margin  |
| total height | 20px | 21px |
| screen capture |  ![Captura de pantalla 2023-09-05 a las 19 36 10](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4138279/cf8bea73-64c6-4e51-8efc-5b36c405f326) | ![Captura de pantalla 2023-09-05 a las 19 38 02](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4138279/85ca675c-4735-4ba0-97e4-cb1a67990c0c) |

Additionally. Not directly related to Figma design, if I try to set the radio button full width, it is centered instead of right aligned. The intention is to have full-width interactions and some icons on the right side.
It would be good to have `<label>` tag with a `part` in order to edit this behavior.

![Captura de pantalla 2023-09-05 a las 19 42 50](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4138279/4fa62b84-dfbf-4d50-9392-8ea4a4217c8c)

### Component(s) impacted

Radio-button

### Carbon for IBM.com version

v2.0.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

IBM Quantum Learning

### Package

@carbon/web-components

### CodeSandbox example

https://web-components.carbondesignsystem.com/?path=/story/components-radio-button--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RichKummer** [comment]
Hey @korgan00 , thanks for surfacing this. It looks like these differences are present in both react and web components. Can you create this ticket in the [carbon react repo](https://github.com/carbon-design-system/carbon/issues/new/choose)? This way there's parity in any design changes across react and wc. Thank you!
