### ISSUE TITLE
Bug on Masthead's Megamenu

### ISSUE THREAD

**Issue by mo-alaa** [carbon-design-system/carbon-for-ibm-dotcom#10922]
### Description

In the Dotcomshell of the web components, I noticed the megamenu opens like a modal, I remember this wasn't the behavior in the carbon-react library.
You can see in the video that the megamenu (as if it) appears twice on close.

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/41386480/3b919f7c-099d-4be9-97d6-3fb9ad2001df

### Component(s) impacted

DotcomShell

### Browser

Chrome

### Carbon for IBM.com version

v1.35.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

ibm.com/impact

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/p/sandbox/dotcomshell-web-components-ms797t?file=%2Fsrc%2Findex.js%3A58%2C33

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@mo-alaa This is has been the default behavior of the `megamenu` since its introduction.
