### ISSUE TITLE
[Web-components]: cds-side-nav-menu > menu-body has a max-height

### ISSUE THREAD

**Issue by korgan00** [carbon-design-system/carbon-for-ibm-dotcom#10936]
### Description

The `menu-body` `part` in the `cds-side-nav-menu` has a `max-height: 93.75rem` and we are having an issue with that because it is hiding some elements. We solved it with css correction, but I don't know if you are aware of it.

It seems quite arbitrary. Is there any specific reason?

I know it has a `max-height: 0` on not-expanded state. It can be solved with a `max-height: none` instead of `93.75rem`.

### Component(s) impacted

UIShell / cds-side-nav-menu

### Carbon for IBM.com version

v2.0.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

IBM Quantum Learning

### Package

@carbon/web-components

### CodeSandbox example

https://stackblitz.com/edit/github-kqdr6r?file=index.html

### Steps to reproduce the issue (if applicable)

Create a sidenav and fill it with a lot of items.

In the case of the stackblitz that I created, elements over 46 are hidden, there are 59.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by abdonrd** [comment]
@kennylam I see you self-assigned here. Any ETA to fix it? Thanks! 🙏

**Comment by abdonrd** [comment]
Any news here? Thanks!

**Comment by kennylam** [comment]
@abdonrd @korgan00 This will be included in `v2.4.0`, which will release Feb 26!
