### ISSUE TITLE
[DDSVideoPlayerContainerMixin player options customization]: Allow easier customization of Kaltura params

### ISSUE THREAD

**Issue by m4olivei** [carbon-design-system/carbon-for-ibm-dotcom#10942]
JIRA: https://jsw.ibm.com/browse/ADCMS-3952

### The problem

Recently we were given new designs for a compoent using background video. We needed to make customizations to the DDSVideoPlayerContainerMixin in order to achieve the results we needed. Video in this case is purely background / ambient video, requiring:

* No captions track. Video has no sound, and also set to muted. Hide captions track.
* No CTAs. Specifically midstream card that pops up bottom left, and end cards

### The solution

To achieve this in C4AEM, we were forced to wholesale override the `DDSVideoPlayerContainerMixin._embedVideoImpl` method and make the adjustments to the params in our copy / pasta 🍝 overriden method.

### Application/website

ibm.com

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### What time frame would this ideally be needed by (if applicable)

This would be a nice to have improvement so we could maintain less duplicate code.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
C4AEM PR Link: https://github.ibm.com/webstandards/carbon-for-aem/pull/106
