### ISSUE TITLE
[RTL]: Carbon carousel RTL issue

### ISSUE THREAD

**Issue by marianserafimovibm** [carbon-design-system/carbon-for-ibm-dotcom#10950]
[JIRA](https://jsw.ibm.com/browse/ADCMS-4075)

### Description

Hello
I'm working on replacing yourlearning.ibm.com home page carousel with carbon carousel.
Carbon carousel is set up, and it's working right, but we have a problem with RTL styling.
In documentation says that we only have to configure webpack to load rtl.css.js files, but it doesn't work for me. The styles are loaded to the browser.

**NOTE:** carousel pagination carets should be flipped horizontally

### Component(s) impacted

Here is the carousel we have to replace:
![first](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/145344451/5a8b7bfb-fe89-4de2-b509-11ef4a2e5c0c)
This is how it looks like by simply setting up carbon carousel. It works well for LTR version: 
![second](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/145344451/ad38acc9-b815-4b5c-b69a-ae3d5e0c8d43)
When RTL is enabled it looks like this:
![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/145344451/5c076c92-7443-438d-b5ad-fe7046f1f336)

Here are the lines of code we are using: 
![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/145344451/65f7c5af-faa4-4832-8e84-e34e56f79337)
![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/145344451/ccc9a3c0-bd4a-4d1e-a8ca-11ccd4ffce80)

### Browser

Chrome

### Carbon for IBM.com version

"@carbon/ibmdotcom-web-components": "^1.33.0",

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

yourlearning.ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/?path=/story/components-carousel--default

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by m4olivei** [comment]
Noting that this issue is reproducible on the [Canary Storybook](https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/iframe.html?args=&id=components-carousel--default&viewMode=story) instance:

![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/191049/b68af9b9-2fe6-406c-87ab-cc420ea66b0f)

To reproduce, visit the link, open Chrome dev tools and add the `dir="rtl"` attribute to the `<html>` tag.

**Comment by m4olivei** [comment]
@marianserafimovibm if you have a moment, please review the open PR https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11030. Testing instructions are in the PR description. Thanks!

**Comment by marianserafimovibm** [comment]
@m4olivei Will message you once it is tested. Thanks for your effort.
