### ISSUE TITLE
[cwc feature-flags]: add feature flag capabilities

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#11048]
Currently the `@carbon/web-components` package has no feature flag capabilities for creating experimental components and features. This should be added to the v2 version of the package.

**Comment by annawen1** [comment]
[Jenkins job](https://dbg-digital-design-team-jenkins.swg-devops.com/job/Carbon%20for%20IBM.com%20-%20Deploy%20Preview%20-%20Carbon%20Web%20Components%20-%20Experimental/) created to create experimental deploy previews for CWC as well

**Comment by mattrosno** [comment]
@annawen1 should this issue be closed? It looks like the linked PR didn't auto-close it.

**Comment by annawen1** [comment]
Yep, I went ahead and closed it
