### ISSUE TITLE
slider pointer styles

### ISSUE THREAD

**Issue by PabloAznarez** [carbon-design-system/carbon-for-ibm-dotcom#11272]
### Description

Pointer styles are not sowing correctly the size of pointer

### Component(s) impacted

slider

### Browser

Chrome

### Carbon for IBM.com version

2.1.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

internal enterprise app

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://web-components.carbondesignsystem.com/?path=/story/components-slider--default

### Steps to reproduce the issue (if applicable)

not steps needed

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kuri-sun** [comment]
I will take a look at this one thanks!

**Comment by siaikin** [comment]
hi @kuri-sun  在我升级了 @carbon/web-components 后，遇到了同样的问题。我发现这是因为 @carbon/styles 增加一个 slider 功能后引起了。

https://github.com/carbon-design-system/carbon/commit/8263d2cc6#diff-6984dfc76afe987e58459262c247747221b41c376dda4babbc316a4df4cb7dadL93

`cds--slider__thumb` 的 width/height 设置被删除了。

**Comment by annawen1** [comment]
Issue should be fixed in @carbon/web-components v2.1.1
