### ISSUE TITLE
Accordion with attribute open don't open content

### ISSUE THREAD

**Issue by PabloAznarez** [carbon-design-system/carbon-for-ibm-dotcom#11273]
### Description

When I add the open attribute to the accordion item the content does not expand correctly

### Component(s) impacted

accordion

### Browser

Chrome

### Carbon for IBM.com version

2.1.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

internal enterprise app

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://jsfiddle.net/pasblin/4s9tpgum/5/

### Steps to reproduce the issue (if applicable)

See in reproduccion example

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by IgnacioBecerra** [comment]
This has been fixed in `v2.2.0` , here is the jfiddle using the latest CDN version:
https://jsfiddle.net/brna7spw/14/
