### ISSUE TITLE
New web-components version (v2.1.0) doesn't load

### ISSUE THREAD

**Issue by abdonrd** [carbon-design-system/carbon-for-ibm-dotcom#11274]
### Description

When update from v2.0.1 to [v2.1.0](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/releases/tag/%40carbon/web-components%402.1.0), importing components gives an error:

```
[vite-node] [ERR_LOAD_URL] @carbon/web-components/es/components/button/button.js

at @carbon/web-components/es/components/button/button.js
```

✅ Application with `@carbon/web-components@2.0.1`:
https://stackblitz.com/edit/github-gkn31f-tzrvfj?file=package.json

<img width="1506" alt="Screenshot 2023-12-26 at 2 16 44 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/55390bd1-ba1f-4fe9-a9cd-465cd5318dc8">

❌ Application with `@carbon/web-components@2.1.0`:
https://stackblitz.com/edit/github-gkn31f-gn6xrr?file=package.json

<img width="1508" alt="Screenshot 2023-12-26 at 2 16 39 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/5b43b803-ad99-45ed-832a-861ec49ca30d">

### Component(s) impacted

All.

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

IBM Quantum

### Package

@carbon/web-components

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by abdonrd** [comment]
Reviewing changes in the `package.json`, why private?

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/72142f06ea627484a439203d3895491cd59594a9/packages/carbon-web-components/package.json#L3

**Comment by abdonrd** [comment]
This is the diffing I found:

<img width="618" alt="Screenshot 2023-12-26 at 2 40 58 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/8fe2d602-7148-4666-a4f4-523579873142">

---

Why this?

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/72142f06ea627484a439203d3895491cd59594a9/packages/carbon-web-components/package.json#L20

`lib` is only have `.js.map` files:

<img width="345" alt="Screenshot 2023-12-26 at 2 44 04 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/67c0ad15-d773-41e7-a3f3-20dca1366a65">

**Comment by abdonrd** [comment]
It works if I change from:

```json
    "./es/components/*": {
      "node": "./lib/components/*",
      "default": "./es/components/*"
    },
```

To:

```json
    "./es/components/*": {
      "default": "./es/components/*"
    },
```

**Comment by jeffchew** [comment]
@kennylam @ariellalgilmore @annawen1 this may have happened after we merged in. 

> Reviewing changes in the `package.json`, why private?
> 
> https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/72142f06ea627484a439203d3895491cd59594a9/packages/carbon-web-components/package.json#L3

@kennylam Not sure if we need this anymore now that everything is merged in?

**Comment by abdonrd** [comment]
Fixed by https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11283
And released here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/releases/tag/%40carbon/web-components%402.1.1
