### ISSUE TITLE
[Web Components V2]: Web components it's not working on v2.

### ISSUE THREAD

**Issue by fbianca** [carbon-design-system/carbon-for-ibm-dotcom#11278]
### Description

I have tried to use two components expressive modal and the video one and it seems that it's not working as it should. I tried to use any other components but none have worked on v2 for me. I have also tried to create a brand new page to test it ouy, but nothing worked as well. For the record I was using the CDN import

### Component(s) impacted

All of them.

### Browser

Chrome

### Carbon for IBM.com version

v2

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

N/A

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://stackblitz.com/edit/web-platform-swue7d?file=index.html

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ariellalgilmore** [comment]
https://stackblitz.com/edit/web-platform-nj22rv?file=index.html

v2 latest tag is working now
