### ISSUE TITLE
[Carbon web components sources]: Where can I find web components sources

### ISSUE THREAD

**Issue by ko1ebayev** [carbon-design-system/carbon-for-ibm-dotcom#11281]
### Summary

As doc says, web components are supported by open-source community team, how can I participate in it?

### Relevant information

<img width="1391" alt="image" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/47644077/fa464b91-678e-4cbb-8974-afebbd980849">
Link in box redirects me to this page - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/new/choose

### Name and organization

Vlad Kolebayev
1inch Network

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
Hi @ko1ebayev! You can find the web components package repository [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/carbon-web-components). If you'd like to contribute, it would be easiest to filter issues with the [package: carbon web components](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues?q=is%3Aissue+is%3Aopen+label%3A%22package%3A+carbon+web+components%22) label. Thanks!

**Comment by ko1ebayev** [comment]
thank you @kennylam, I will contribute soon
carbon components look cool!
