### ISSUE TITLE
[web-components]: RTL issues on masthead

### ISSUE THREAD

**Issue by NicoletaBordea** [carbon-design-system/carbon-for-ibm-dotcom#11342]
### Description

there are several issues found for RTL languages:
1. user can not see the inserted string in search field and also the placeholder is not entirely visible
2. the suggestions are wrongly displayed (wrong order of letters, I will add a screenshot)
3. the position of x button and search icon is not correct 

![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/69757761/09787351-08fe-4443-b85e-37875fcc8297)

also another small issue for the custom typeahead (not rtl), it is bolding the first letter in the search text also in the title of the section, which is wrong. For example here I typed in cloud, and is bolding all c in the title of the section in suggestions:

<img width="382" alt="Screenshot 2024-01-04 at 16 51 05" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/69757761/742074cf-d1eb-40f7-8aac-709bcccc6791">

### Component(s) impacted

masthead

### Browser

Chrome

### Carbon for IBM.com version

v2.0.0-rc.3

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

ibm docs

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

-

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ingridsamakova** [comment]
Any ETA on this issue when it will be fixed? thank you
