### ISSUE TITLE
Dispatch an event when the header checkbox (check/uncheck all rows) is used on a DataTable with Selection

### ISSUE THREAD

**Issue by dave-wood** [carbon-design-system/carbon-for-ibm-dotcom#11350]
### The problem

With a DataTable, if you use the selection feature to add a checkbox to each table row, you also get a check-all checkbox added to the header row, which checks all the row checkboxes.
Checking a table row checkbox dispatches a `cds-table-row-change-selection` event, however checking the header checkbox does not dispatch any event.

### The solution

It would be useful if the header checkbox also dispatches an event. Perhaps both events could also include a count of how many rows have been selected.

### Application/website

Various tools for UK Labs

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by IgnacioBecerra** [comment]
@dave-wood The event that you're looking for is `cds-table-row-all-selected`

This event fires upon clicking the header row's checkbox, and includes an array of the currently selected rows. We will be putting out an update that has all the available events in our docs in the next release.

**Comment by dave-wood** [comment]
Great thank you
