### ISSUE TITLE
[v1 - bx-input]: web-components 1.34+ broke value display in bx-input

### ISSUE THREAD

**Issue by AlessandroPomponio** [carbon-design-system/carbon-for-ibm-dotcom#11391]
### Description

Up to version v1.33.0 it is possible to set a default value in `bx-input` that will be displayed and set. Since version 1.34.0 this functionality is broken and displays no value.

### Component(s) impacted

bx-input

### Browser

Microsoft Edge

### Carbon for IBM.com version

1.35.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

Simulation Toolkit for Scientific Discovery

### Package

@carbon/ibmdotcom-web-components, @carbon/web-components

### CodeSandbox example

https://codesandbox.io/p/sandbox/zen-https-ctcd82

### Steps to reproduce the issue (if applicable)

Upgrade the version of the input component used in the code sandbox example to 1.34.0+

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by cedricpelle** [comment]
I have the same issue on my Application : IBM Terms

**Comment by cedricpelle** [comment]
are you able to reproduce, and do you have an outlook ?
