### ISSUE TITLE
Setting default sorted column in data-table doesn't work (and table toolbar disappears if a table title added)

### ISSUE THREAD

**Issue by dave-wood** [carbon-design-system/carbon-for-ibm-dotcom#11451]
### Description

It doesn't appear to be possible to set a column in a data-table to be sorted by default. adding `sort-direction="ascending"` makes the column unsortable rather than making that column sorted.
```
      <cds-table-head>
        <cds-table-header-row>
          <cds-table-header-cell>Name</cds-table-header-cell>
          <cds-table-header-cell sort-direction="ascending">Status</cds-table-header-cell>
        </cds-table-header-row>
      </cds-table-head>
```

The documentation suggests this to sort the first column. However that just produces an error of `Uncaught TypeError: document.querySelectorAll(...)[0].shadowRoot is null`
```
document
  .querySelectorAll('cds-table-header-cell')[0]
  .shadowRoot.querySelector('button')
  .click();
```

Additionally, if you have a table with a toolbar, the toolbar isn't displayed if you also use the `cds-table-header-title` option. So it's not possible to have a title on a table that has a toolbar.
`<cds-table-header-title slot="title">DataTable</cds-table-header-title>`

### Component(s) impacted

cds-table

### Browser

Firefox

### Carbon for IBM.com version

v2/latest

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Various tools for UK Labs

### Package

@carbon/web-components

### CodeSandbox example

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by sangeethababu9223** [comment]
Hi @dave-wood,
Could you please provide a stackblitz / sandbox link for the issue with toolbar when `cds-table-header-title` is present?
I just checked in storybook and also tried to re-create the issue in stackblitz and via CDN but couldn't do so. It would be really helpful if you could provide a reference for the issue.
Thanks

**Comment by dave-wood** [comment]
@sangeethababu9223 I just did some more testing, and it looks like this is a Firefox bug. It actually works as intended in Edge.

Try this Code Sandbox: https://codesandbox.io/p/devbox/angry-fermi-cdh3h5

The middle table is supposed to show both a title and a toolbar (with the search field).  In Edge that works fine, however in Firefox it only displays the title, not the toolbar.  If you look at the 3rd table on that page, the only difference from the middle table is that I removed the title but left in the toolbar, and in Firefox the toolbar does display. So clearly, in Firefox, you can't have both a title and a toolbar.

Firefox:
![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/28702332/6d44404c-cc0d-412d-921d-a6baa0e454ef)

Edge:
![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/28702332/3bd8a31a-2d97-4bc2-848d-9f25b42e481c)

**Comment by IgnacioBecerra** [comment]
@dave-wood Would you be able to open a different issue for the title/toolbar problem? Thanks!

**Comment by dave-wood** [comment]
Added Issue #11473 for Title/Toolbar problem
