### ISSUE TITLE
Notification hideCloseButton Property does not work

### ISSUE THREAD

**Issue by dave-wood** [carbon-design-system/carbon-for-ibm-dotcom#11470]
### Description

For a Notification component, eg `<cds-actionable-notification>` there is an attribute listed in the documentation called `hideCloseButton` but it doesn't hide the [X] close icon, which it presumably is meant to?

`  <cds-actionable-notification
    style="min-width: 30rem; margin-bottom: .5rem"
    title="Notification title"
    subtitle="Subtitle text goes here."
    **hideCloseButton**
  >`

![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/28702332/edbc6abf-689e-41b5-9007-6855611df318)

### Component(s) impacted

Notification

### Browser

Firefox, Microsoft Edge

### Carbon for IBM.com version

v2.2.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Various tools for UK Labs

### Package

@carbon/web-components

### CodeSandbox example

https://codesandbox.io/p/sandbox/sharp-smoke-sn9l6d

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ariellalgilmore** [comment]
The property should be `hide-close-button`

**Comment by dave-wood** [comment]
ok thanks
