### ISSUE TITLE
Table of contents component does not display horizontally

### ISSUE THREAD

**Issue by poonhub** [carbon-design-system/carbon-for-ibm-dotcom#11535]
### Description

Table of contents component, https://www.ibm.com/standards/carbon/web-components/react/?path=/story/components-table-of-contents--horizontal, does not display horizontally.

### Component(s) impacted

C4DTableOfContents

### Carbon for IBM.com version

2.3.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

https://www.ibm.com/software/reports/compatibility/clarity/index.html

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/react/?path=/story/components-table-of-contents--horizontal

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
The storybook and stackblitz examples need to be updated. The issue was the attribute name was set as `layout` when it should be `toc-layout`
