### ISSUE TITLE
[v1 | dds-image]: CDN asset does not load dds-image-item sub-component

### ISSUE THREAD

**Issue by andy-blum** [carbon-design-system/carbon-for-ibm-dotcom#11552]
[ADCMS-4632](https://jsw.ibm.com/browse/ADCMS-4632)

### Description

When loading dds-image from CDN endpoint the `<dds-image-item>` sub component is not loaded.

Additionally (but perhaps unrelated?), the `<dds-image>` component does not display images without the `default-src` attribute present.

### Component(s) impacted

dds-image, dds-image-item

### Browser

Firefox

### Carbon for IBM.com version

v1-latest

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

AEM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codepen.io/andy-blum/pen/LYaaovP?editors=1010

### Steps to reproduce the issue (if applicable)

HTML
```html
<script type="module" src="https://1.www.s81c.com/common/carbon-for-ibm-dotcom/tag/v1/latest/image.min.js"></script>

<dds-image alt="Image alt text" default-src="https://fpoimg.com/672x336?text=2:1&bg_color=53ee96&text_color=161616">
  <dds-image-item media="(min-wiidth:672px)" srcset="https://fpoimg.com/672x336?text=2:1&bg_color=ee5396&text_color=161616">
  </dds-image-item>
  <dds-image-item media="(min-wiidth:400px)" srcset="https://fpoimg.com/672x336?text=2:1&bg_color=ee5396&text_color=161616">
  </dds-image-item>
  <dds-image-item media="(min-wiidth:320px)" srcset="https://fpoimg.com/672x336?text=2:1&bg_color=ee5396&text_color=161616">
  </dds-image-item>
</dds-image>
```

JS
```js
customElements.get('dds-image');
// class n { ... }

customElements.get('dds-image-item');
// undefined
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by m4olivei** [comment]
This was fixed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11564
