### ISSUE TITLE
[Button Group Style Import]: Button stylesheet imports relative `carbon-web-components`

### ISSUE THREAD

**Issue by ccwilson-us-ibm-com** [carbon-design-system/carbon-for-ibm-dotcom#11570]
### Description

I'm attempting to use the Carbon for IBM.com styles as they are packaged in `@carbon/ibmdotcom-styles`.  When I compile my sass which imports the styles for the Button Group component (`@import '@carbon/ibmdotcom-styles/scss/components/button-group';`) or any other sass that also imports the button group styles, I get an sass compile error.  The error is caused by the button styles (packages/styles/scss/components/button/_button.scss) which contains a relative path on an `@use` statement to `../../../../carbon-web-components/src/components/button/button`.  The `carbon-web-components` directory doesn't exist in my installed `node_modules`.  The `@carbon/carbon-web-components` package is deprecated.  The current `carbon-web-components` package in your repository is installed as `@carbon/web-components`.

I found a closed issue that seemed similar but contains no easily accessible fix or work around: #5093 

### Component(s) impacted

Styles for Button and any component styling that depends on them.

**Note:** The required Stackblitz link below doesn't really demonstrate the issue.  I'm not sure how to construct a Stackblitz instance that include a Sass/Scss compile step.

### Browser

Chrome, Firefox

### Carbon for IBM.com version

v2.3.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

Carbon for Salesforce

### Package

@carbon/ibmdotcom-styles

### CodeSandbox example

**Note:** The required Stackblitz link doesn't really demonstrate the issue. I'm not sure how to construct a Stackblitz instance that include a Sass/Scss compile step.

https://stackblitz.com/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/examples/stackblitz/components/button

### Steps to reproduce the issue (if applicable)

Compile a sass style sheet with `@import '@carbon/ibmdotcom-styles/scss/components/button-group';`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ariellalgilmore** [comment]
Hi @ccwilson-us-ibm-com, could you give us a little more context on how you are using the v2 styles package? Are you trying to extend the button-group component and adjust the styles?

**Comment by ccwilson-us-ibm-com** [comment]
Hi.  Sorry for the late reply. I'm attempting to re-use the styles for Salesforce LWC components.  So I can have a button group component that runs in Salesforce with matching styling to the Carbon for IBM.com component.  So I'm using the sass/scss to import/use the IBM.com button group style sass/scss and the and any extra styles adjustments necessary for LWC.

But using `@use "@carbon/ibmdotcom-styles/scss/components/button-group"` in my sass and attempting to compile into css for my button group component causes an error when the ibmdotcom-styles tries to import `../../../../carbon-web-components/src/components/button/button` which doesn't exist when install the package from npm.
