### ISSUE TITLE
IconButton is always showing tooltip

### ISSUE THREAD

**Issue by GuilleS4T** [carbon-design-system/carbon-for-ibm-dotcom#11601]
### Description

Using cds-icon-button with no tooltip props display the tooltip empty in hover event always.
![Captura de pantalla 2024-02-29 a las 14 46 52](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/141831306/a3d2e812-1689-421f-af50-cf7d09684148)

### Component(s) impacted

IconButton
https://web-components.carbondesignsystem.com/?path=/story/components-icon-button--default&globals=outline:true

### Browser

Chrome

### Carbon for IBM.com version

2.4.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

custom enterprise app in science4tech

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://web-components.carbondesignsystem.com/?path=/story/components-icon-button--default&globals=outline:true

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ariellalgilmore** [comment]
The tooltip is required for the icon button. @carbon/react shows the same results.

"In this situation, it's important that the button itself is labeled in a way that can be understandable by mouse, keyboard, and screen readers. As a result, this component makes it easy to create accessible icon buttons"

![Image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/20210594/82ebd317-85a1-4a64-bf66-9e4e1a082a51)
