### ISSUE TITLE
[Combo-box]: Module not found error

### ISSUE THREAD

**Issue by gyalogmixi** [carbon-design-system/carbon-for-ibm-dotcom#11635]
### Description

For a project I use Laravel Mix as a wrapper for Webpack. When I call `npm run production` I encounter this error.

> ERROR in ./node_modules/@carbon/web-components/es/components/combo-box/combo-box.js 25:0-54
Module not found: Error: Package path ./directives/if-defined is not exported from package /workspace/node_modules/lit (see exports field in /workspace/node_modules/lit/package.json)
Did you miss the leading dot in 'resolve.extensions'? Did you mean '[".*",".wasm",".mjs",".js",".jsx",".json"]' instead of '["*",".wasm",".mjs",".js",".jsx",".json"]'?

### Component(s) impacted

Combo-box
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/2a94433970d4f35a6b7dea0c92264477a5056ce4/packages/carbon-web-components/src/components/combo-box/combo-box.ts#L20

When I change it to `import { ifDefined } from 'lit/directives/if-defined.js';`  it works fine.

### Carbon for IBM.com version

2.5.0

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

custom web application

### Package

@carbon/web-components

### CodeSandbox example

https://codesandbox.io/p/sandbox/modest-fermi-fgs9hv

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by nolrinale** [comment]
@kennylam Can confirm this is happening in our project as well, we are unable to fully compile carbon web components to use into our project anymore. Using Vite + Storybook 7 btw
