### ISSUE TITLE
[Question]: Is there a way to disable the auto-focus on first item of Carbon v1 Overflow Menu?

### ISSUE THREAD

**Issue by Dusty-Willow** [carbon-design-system/carbon-for-ibm-dotcom#11677]
### Question for Carbon

**Type:** Carbon Web Components
**Component:** Overflow Menu
**Version:** 1.28.0

It seems like Carbon's v1 Overflow Menu component has a built-in auto-focus feature that focuses on the first item of the menu when it is opened. This leads to jerky movement along the page if the overflow menu being opened is lower down on a user's screen. Is there any way to disable the automatic focus for this component?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by ariellalgilmore** [comment]
Hi, if you try updating to 1.38.0 for the CDN versions then it will resolve your issue: https://stackblitz.com/edit/stackblitz-starters-2qxlfv?file=index.html

**Comment by Dusty-Willow** [comment]
That does fix the issue, though I was hoping not to have to change versions since I'll have to double check whether the change in version changes the functionality of the application in any other way. Is there a way for me to find notes on changes between different versions of the web components for reference?

**Comment by ariellalgilmore** [comment]
You can look at all of our releases here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/releases and see the changelog between each release. SInce you are using the web component CDN's the components are encapsulated, so you should only need to test the web component that you are updating the CDN's version too and it shouldn't effect other components

**Comment by Dusty-Willow** [comment]
Will do. Thank you for the help and the informative response!
