### ISSUE TITLE
Typo with aria-label that creates a11y issues with the toggle-switch web component

### ISSUE THREAD

**Issue by CalinaCristian** [carbon-design-system/carbon-for-ibm-dotcom#11969]
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/148003119ddc3325af971b5beda629db209c4098/packages/carbon-web-components/src/components/toggle/toggle.ts#L147

There is this typo in the toggle switch web component that's causing issues with a11y.

It's also in [the snapshots](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/148003119ddc3325af971b5beda629db209c4098/packages/carbon-web-components/tests/snapshots/cds-toggle.md?plain=1#L10).

**Comment by thekevinhunt** [comment]
I also just encountered this.  Seems like the fix should be easy.
