### ISSUE TITLE
[data table inside selectable data table]: data table inside selectable data table is selectable

### ISSUE THREAD

**Issue by DoofisS** [carbon-design-system/carbon-for-ibm-dotcom#12015]
### Description

when you have expandable and selectable data table and you want to have a data table in expanded row inner dt will automatically be selectable idk if this is the default behavior if yes then how can we disable it cause what if I don't need inner dt to be selectable and I also don't really see adding hide-checkbox prop for every line as a good solution cause it still produce bugs then even when hidden

here some examples and a video of how it works

if you are pressing row checkbox it will not select checkboxes on dt that is inside the expandable row
![image](https://github.com/user-attachments/assets/76b1df8b-7224-4404-8a7f-5e113aa9b15d)
but if you will press select all it will select even the checkboxes inside the expandable row 
![image](https://github.com/user-attachments/assets/b3efd684-316e-4a69-a9df-0f298e29449f)
if we try to hide checkbox on a dt that is inside the expandable row cause we don't need it and then we press select all it still will check the checkboxes of the inner dt even the checkboxes are hidden
![image](https://github.com/user-attachments/assets/61b9382f-2ed0-40a0-ab0b-1e1efff5bfff)
![image](https://github.com/user-attachments/assets/28d69377-2b38-4f92-b7f2-aef0e7fdf5d9)
 

https://github.com/user-attachments/assets/924221aa-f561-495f-a50e-7a8635584012

### Component(s) impacted

data table, expandable, selectable

### Carbon for IBM.com version

@carbon/web-components 2.12.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

Any project with dt

### Package

@carbon/web-components

### CodeSandbox example

https://codesandbox.io/p/sandbox/5mnty4?file=%2Findex.html

### Steps to reproduce the issue (if applicable)

https://codesandbox.io/p/sandbox/5mnty4?file=%2Findex.html

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by gyalogmixi** [comment]
I do have a similar case, but there is a workaround. Here is a [CodeSandbox example](https://codesandbox.io/p/devbox/trusting-mopsa-nm4nqg?file=%2Fsrc%2Findex.js)
