### ISSUE TITLE
[card-group-item]: color-scheme doesn't work correctly

### ISSUE THREAD

**Issue by andy-blum** [carbon-design-system/carbon-for-ibm-dotcom#12080]
### Description

[Figma Specs for inverse cards](https://www.figma.com/design/oip4K9G1z0v7tLNBbDZzdr/Card-specs-v2?node-id=20-4662&t=ANH9LQPEcxOGajfN-4)

Expected:
![Image](https://github.com/user-attachments/assets/1c06f292-1c05-4500-a1a9-891e86774515)

Actual:
![Image](https://github.com/user-attachments/assets/5cccfcaa-5c6b-43ac-b3dd-7fb0b0fb2be6)

### Component(s) impacted

c4d-card-group-item, potentially other card elements

### Browser

Firefox

### Carbon for IBM.com version

v2-latest

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

ibm.com

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

https://card-group-subgrid--carbon-demos.netlify.app/

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by Valentin-Sorin-Nicolae** [comment]
Draft PR open - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/12138
