### ISSUE TITLE
[Functional Specs] Media - manager Component

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#1631]
#### User Story
> As a `[user role below]`:
An IBM.com developer

> I need to:
a way to easily switch between different media types

> so that I can:
easily build a pattern that allows multiple options.

#### Acceptance criteria
 - [ ] Functional specs written
 - [ ] Shared with Design and Development reviewed and approved
 - [ ] Additional stories created if necessary

**Comment by RobertaJHahn** [comment]
Iceboxing all Media - manager issues.

**Comment by RobertaJHahn** [comment]
Decided to close all of the Media manager issues.
