### ISSUE TITLE
Color Theme is not a Prop for Content Block Patterns

### ISSUE THREAD

**Issue by kexuibm** [carbon-design-system/carbon-for-ibm-dotcom#1637]
This epic contains links to the issues that complete the color theme work.

**Comment by jeffchew** [comment]
Hi @kexuibm ,

Themes for these patterns are not in MVP and only support white theme at the moment. Some design work and study still needs to be explored for the other non-white themes. Does this block your injestion process?

cc: @ljcarot @RobertaJHahn @larahanlon2 @wonilsuhibm

**Comment by kexuibm** [comment]
Hey Jeff, it does not block the ingestion process but it will force us to re-ingest if/when any of those 4 patterns would get assigned to any color theme other than white.   And that regenerated template would need to be redeployed to Production if it had already gone out with the MVP.

**Comment by RobertaJHahn** [comment]
Out of date.  Closing.
