### ISSUE TITLE
Perform an audit of the ibm.com Library for the Arabic development

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#1639]
#### User Story

> As a `[user role below]`:
DDS Development Lead / Architect

> I need to:
understand the scope of the work required to render Arabic web pages properly

> so that I can:
properly instruct the scrum master and developers regarding the work involved

#### Additional information

 - The design research will inform the work for this issue.  (#1638)
 - RTL is configured using a global setting.  
- [React RTL Storybook link](https://ibmdotcom-react-rtl.mybluemix.net/?path=/story/components-footer--default)
- [Web Components Storybook link](https://ibmdotcom-web-components-rtl.mybluemix.net/?path=/story/overview-getting-started--page)

#### Acceptance criteria
 - [ ] List of the changes required to each component and pattern to support Arabic web pages
 - [ ] _{{State another}}_
 - [ ] _{{And another}}_

**Comment by ljcarot** [comment]
Re-opening since closed by stalebot.  Still need this audit. Who should conduct audit? Design? Dev? BA?@RobertaJHahn @jeffchew @wonilsuhibm

**Comment by RobertaJHahn** [comment]
@ljcarot Included in our Leadership meeting agenda.  Might need to talk about priorities.  Design resources are booked in the current sprint.

**Comment by RobertaJHahn** [comment]
Next step:  Linda to send the RTL storybook link to Amid for his review.

**Comment by jeffchew** [comment]
Let's keep this one open, but figure out next steps on our testing on this @ljcarot @wonilsuhibm @RobertaJHahn .

**Comment by RobertaJHahn** [comment]
Created a calendar reminder for Jan 7, 2021 to include the planning in the Leadership meeting agenda.
