### ISSUE TITLE
Video player Carbon version (birthday cake version)

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#1724]
### Our story
This is to update the default Kaltura video player interface with IDL specs such as icons, containers, colors, etc.

The design from the Brand team and the func specs from the content team are on this [Box folder](https://ibm.box.com/s/0iou7yl21n58whoqhil1n1gbbjdqjlud)

**Comment by RobertaJHahn** [comment]
Closing as all linked issues are closed.
