### ISSUE TITLE
Create the Locale Modal for Vanilla

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#2123]
#### User Story

> As a `[user role below]`:
IBM.com Library adopter

> I need to:
have a footer with the locale button

> so that I can:
integrate the IBM.com Library approved footer in my non-React application

#### Additional information

 - This component was originally created in the Fall of 2019.  The original issues are included in the IBM Enterprise Digital Design System Github.  
 - [Locale Selector component MVP link](https://github.ibm.com/webstandards/digital-design/issues/1077)
 - [Locale Selector enhancements included in release 2](https://github.ibm.com/webstandards/digital-design/issues/1804)

#### Acceptance criteria
 - [ ] _{{State acceptance criteria}}_
 - [ ] _{{State another}}_
 - [ ] _{{And another}}_

**Comment by RobertaJHahn** [comment]
@kennylam This work has been deprioritized.  Removing from this sprint.

**Comment by RobertaJHahn** [comment]
Closing.  Vanilla components are no longer being developed.
