### ISSUE TITLE
Component - LightBoxMediaViewer - Close icon is overlapping with scroll up icon. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#2187]
## Detailed description

Issue :- When user tries to scroll using scroll "/\" up icon, close icon is overlapping with it. 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/10f52296-8736-4492-94dc-c1fa7734d543)

**Comment by RobertaJHahn** [comment]
@Praveen-sr @chetankan Doesn't this only happen beginning at a specific breakpoint?  Can you add the steps to recreate.  Thanks.

**Comment by Praveen-sr** [comment]
@RobertaJHahn Steps to reproduce :
1. Open storybook and navigate to LightboxMediaViewer
2. On knobs, set the image ratio to 1280*720 (16:9) or 200*750(15:4)
3. Go to full Screen mode
4. Try to scroll up using the scroll up icon 
![image](https://user-images.githubusercontent.com/60002341/80377366-d0671d00-88b8-11ea-8525-01cc24e154b0.png)


Scroll up and close icon are overlapping.

**Comment by RobertaJHahn** [comment]
@wonilsuhibm    Wonil has done some design spacing studies and can provide direction on the spacing realignment.

**Comment by RobertaJHahn** [comment]
Wonil would like to have a study done.  Issues will be created on the Ideation board to make the design decision.  This issue will be moved to Icebox pending the study results.

**Comment by RobertaJHahn** [comment]
Moving this issue to Icebox pending the design studies work included in the Ideation repo [issue #49](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/49)

**Comment by RobertaJHahn** [comment]
Closing.  behavior does not block user from closing.
