### ISSUE TITLE
Component: LightboxMediaViewer and CTA - greyed out scrollbar is displayed on ratio 2:1 (1024*512)

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#2460]
## Detailed description

Device : Windows 
Browser : Chrome

Issue on LightboxMediaViewer and CTA sections.

Issue :- Scroll bar is displayed on ratio 2:1 (1024*512),  which is not required.

Expected : When the copy text is large the scroll option must be activated.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/33e66959-8606-4c72-b5af-0698b84f6648)

**Comment by kennylam** [comment]
@Praveen-sr Which storybook environment are you seeing this on? I tried both below and cannot reproduce in Windows Chrome.

http://ibmdotcom-react.mybluemix.net/?path=/story/components-lightboxmediaviewer--default

http://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-lightboxmediaviewer--default

**Comment by RaphaelAmadeu** [comment]
This issue is happening due to `overflow`, as it's set to auto, it's going to have some resolutions that will display a blank scrollbar, I don't know if this is a bug by itself.

cc: @kennylam @jeffchew

**Comment by NSDrowned** [comment]
Hello @Praveen-sr, does this issue still apply? I tested but couldn't reproduce.

**Comment by NSDrowned** [comment]
Hello @Praveen-sr, any update on this one?

**Comment by Praveen-sr** [comment]
@NSDrowned Re tested this on web components staging, still the issue exists. Scroll bar appears for 2:1 ratio

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/a8d92abe-5401-4b12-9080-4c199533cc1c)

On React for 2:1
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/f301f864-09b8-496f-abe4-ccc85954068d)

CC @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Closing based on the comments in the PR 5640.  Not a suitable fix.
