### ISSUE TITLE
Investigate Percy integration with integration tests

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#2464]
### The problem

As we run integration tests, it's nice to have visual regression tests in there, too.

### The solution

Integrate Percy to integration tests (#2461).

**Acceptance criteria**

- [ ] Build integration test that was introduced in #2462 sends some screenshots to Percy

**Comment by jeffchew** [comment]
Documentation on running percy snapshots in Puppeteer: https://docs.percy.io/docs/puppeteer

**Comment by RobertaJHahn** [comment]
Work is done.  Closing
