### ISSUE TITLE
Check specs to see if we have the correct default values in our React components

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#2508]
Follow-up of #2422.

### The problem

From @jeffchew in #2498:

> > One thing I think this work is surfacing is the lack of `defaultProps` in a bunch of our patterns/components. We'll probably need to go back and doublecheck the specs and set those for the ones that are missing.

### The solution

From @asudoh:

> Great point @jeffchew - Any ideas on how we can best move forward with this...? Probably gathering the specs, reviewing them, and compare with the status quo of the code...?

Most likely. The patterns especially should have corresponding functional specs we can refer to. For components though, we might need to make those determinations from the engineering side.

**Comment by RobertaJHahn** [comment]
This epic will be included in the engineering Huddle meeting.

**Comment by RobertaJHahn** [comment]
No Longer a priority
