### ISSUE TITLE
Left Navigation component

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#256]
_hahnrob created the following on Jun 20:_  

 This is an Epic that contains links to all of the work required to create the left navigation component 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1081_

**Comment by jeffchew** [comment]
_On Aug 27, spbokma commented:_
Concepts sketched out during a meeting between Wonil, Jeff and Scott on 8/26
![screen shot 2019-08-27 at 12 49 58 pm](https://media.github.ibm.com/user/2785/files/d9879080-c8ca-11e9-866a-cfd71d0f179a)

It continue discussing naming, layout, structure, usage, governance and what it looks like across the different grid/browser sizes

**Comment by RobertaJHahn** [comment]
Reboot is working on this design work as part of the eco system.
