### ISSUE TITLE
CTA card (Card link) aspect ratio is showing wrong

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#2571]
## Detailed description

> Describe in detail the issue you're having.
The CTA card is supposed to have 2:1 aspect ratio. Currently that aspect ratio breaks in some break points.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

It's a bug.

> Is this issue related to a specific component?

It's happening in multiple components and patterns:
- [Content group with media](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-contentblockmedia--default)
- [Content group with media with side elements](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-contentblockmedia--with-aside-elements)
- [Content group mixed](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-contentblockmixed--default)
- [Content group mixed with a side elements](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-contentblockmixed--with-aside-elements)
- [Content block segmented](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-contentblocksegmented--default)
- [Content block segmented with side elements](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-contentblocksegmented--default)
- [Content block simple](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-contentblocksimple--default)
- [Content group simple](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-contentgroupsimple--default)
- [Logo grid](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/patterns-blocks-logogrid--default)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The CTA card should maintain the 2:1 aspect ratio.

> What browser are you working in?

Chrome 83.0.4103.61 (Official Build) (64-bit) on Mac OS X ver 10.15.4 (19E287)

> What version of the IBM.com Library are you using?
The latest canary.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com reboot

## Steps to reproduce the issue

1. go to the above-linked storybook pages
2. resize the browser window

**Comment by RaphaelAmadeu** [comment]
@wonilsuhibm 
I've checked all these patterns in our [canary](http://ibmdotcom-react-canary.mybluemix.net/) deployment and the aspect ratio seems fine for all of them except for `LogoGrid`, where it follows the size of the images, how should we handle the `CardLink` in this pattern?

**Comment by guilhermelMoraes** [comment]
@wonilsuhibm confirming what Raph said above, the `CardLink` is maintaining its aspect ratio as expected. 

FYI @RobertaJHahn
