### ISSUE TITLE
Automate the update of latest IBM.com Library packages in NextJS boilerplate

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#2662]
#### User Story

> As a `[user role below]`:
IBM.com Library adopter

> I need to:
ensure the latest IBM.com Library is includes in the NextJS boilerplate

> so that I can:
clone the repo and begin building my application right away

#### Additional information

 - We can use a command like so to check: `npm outdated @carbon/ibmdotcom-react --json`. This outputs something like:

```
{
  "@carbon/ibmdotcom-react": {
    "current": "1.7.0-alpha.3916",
    "wanted": "1.7.0",
    "latest": "1.7.0",
    "location": "node_modules/@carbon/ibmdotcom-react"
  }
}
```

If `current !== latest`, then run `yarn update-staging` and then commit as `ibmdotcom-bot`.
 - We can run this periodically, perhaps every night.
- https://github.com/carbon-design-system/ibm-dotcom-library-nextjs-template

#### Acceptance criteria
 - [ ] Add CI task that runs on a regular schedule to check and update for latest set in package.json

**Comment by RobertaJHahn** [comment]
@annawen1 Moving this issue to the next sprint and release as it is a low priority.
