### ISSUE TITLE
Pattern: Content group horizontal: Spacing fixes

### ISSUE THREAD

**Issue by ltitle** [carbon-design-system/carbon-for-ibm-dotcom#2669]
## Content group horizontal: Spacing fixes

> Describe in detail the issue you're having.

Responsive spacing does not match visual specs for top of pattern and between title and children

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Content group horizontal pattern

> What did you expect to happen? What happened instead? What would you like to
> see changed?

### Top of pattern spacing:

**As seen in Storybook:**
Spacing on top of pattern is maintaining 64px on Medium breakpoint 

![image](https://user-images.githubusercontent.com/57198117/83899451-7adb2700-a726-11ea-8b58-f0942f16bd46.png)

**Expected from visual specs:**
Large, XL and Max breakpoint use 64px spacing on top of pattern
Medium and Small breakpoint use 32px on top of pattern

Medium breakpoint visual specs:

![image](https://user-images.githubusercontent.com/57198117/83899560-a827d500-a726-11ea-966f-7ea037698971.png)

----------------

### Space between Title and children

**As seen in Storybook:**
Space between pattern title and children is 48px on Max, XL, and Large breakpoints:

![image](https://user-images.githubusercontent.com/57198117/83900115-8bd86800-a727-11ea-86fd-3fc63482d0d7.png)

Space between pattern title and children is 32px on Medium and Small breakpoints:

![image](https://user-images.githubusercontent.com/57198117/83900020-66e3f500-a727-11ea-873f-ea99c4e438d4.png)

**Expected from visual specs:**
Space between pattern title and children is 96px on Max, XL, and Large breakpoints:

![image](https://user-images.githubusercontent.com/57198117/83900648-e2de3d00-a727-11ea-8810-1a019880e5bb.png)

Space between pattern title and children is 64px on Medium and Small breakpoints:

![image](https://user-images.githubusercontent.com/57198117/83900805-eec9ff00-a727-11ea-9874-b7b658181713.png)

> What browser are you working in?

Chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM.com Reboot

## Steps to reproduce the issue

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/2333/index.html?path=/story/patterns-blocks-contentgrouphorizontal--default

**Comment by RobertaJHahn** [comment]
6/17/2020:  decided not to make this "on off" change to fix the spacing.  There is spacing strategy work underway.  Ideation Board Issue #35:  https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/35

**Comment by RobertaJHahn** [comment]
One off issue.  Closing
