### ISSUE TITLE
Component - CTA - Keyboard - After activating the close icon in the model page, focus not set on the triggering element .

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#2724]
## Detailed description

Issue :- After activating the close icon in the model page, focus not set on the triggering element .

Expected :-  Focus should set on the triggering element. Which is a folgers coffee link.

**Comment by RobertaJHahn** [comment]
@kennylam Moving this to sprint 20-19, based on the discussions in Modany's engineering meeting

**Comment by RobertaJHahn** [comment]
@kennylam Moving this sev 4 to next sprint

**Comment by jeffchew** [comment]
@Praveen-sr can you retest this to see if this is still an issue?

**Comment by Praveen-sr** [comment]
Re tested above bug, now Focus is set on the triggering element. Working fine.
@jeffchew cc @RobertaJHahn
