### ISSUE TITLE
Content strategy for the wedding cake website 

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#273]
_chsanche created the following on Jun 28:_  

 ### User story

As a DDS website designer, I need a content strategy for the next-gen website so that I can ensure we have a clear vision on what we are going to work on to ensure we provide correct and relevant content for our adopters.

### Notes

- Based on the workshop outcome, we will build the next-gen website with the Gatsby template and will have the full IA with the Carbon content merged together as one design system website.

### Acceptance criteria

- [ ] A content strategy for the website created and agreed by stakeholders - Linda and Wonil. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1142_

**Comment by JennySanchez** [comment]
The strategy has changed with the Carbon discussions and this EPIC will be closed.
