### ISSUE TITLE
Ideation: Wedding cake website mental model options

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#274]
_chsanche created the following on Jul 02:_  

 # As a DDS designer, I need to view all the mental models possible with the Carbon team and agreed on which model to move forward with so that I can work on the new website without confusion.

## Additional information
Mental models for the new website created by Scott and can be viewed [here](https://ibm.box.com/s/28jxi600apo1ozpmj4cgdqbqgafu5bbg) and work file can be found [here folder](https://ibm.box.com/s/o29gmil8617hkole5ykbllzjn2h2lwmu).

## Acceptance criteria
- [x] Share the mental models with the Carbon team for feedback
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1168_

**Comment by jeffchew** [comment]
_On Jul 02, chsanche commented:_
@spbokma @Wonil-Suh1 
**FYI:** This task issue existed for us to get feedback on mental models.
Our review with Jeannie is scheduled for the 15th and I will remind her next week as suggested by Wonil.

**Comment by jeffchew** [comment]
_On Jul 13, chsanche commented:_
**Planning update:**
We will meet internally on Monday (07-15) and meet with the Carbon Team on Tuesday (07-16).

**Comment by jeffchew** [comment]
_On Jul 16, chsanche commented:_
Sketch work file saved on [BOX](https://ibm.box.com/s/o29gmil8617hkole5ykbllzjn2h2lwmu).

---


![singlesite- meaning](https://media.github.ibm.com/user/5181/files/cf07b080-a7ce-11e9-8d18-33755172a528)
![singlesite-opt1](https://media.github.ibm.com/user/5181/files/cfa04700-a7ce-11e9-8aba-5eceb5fc80e9)
![singlesite-opt2](https://media.github.ibm.com/user/5181/files/cfa04700-a7ce-11e9-9b12-8e195504200f)
![singlesite-opt3](https://media.github.ibm.com/user/5181/files/d038dd80-a7ce-11e9-973d-e67244cea3d7)
![singlesite-opt4](https://media.github.ibm.com/user/5181/files/d038dd80-a7ce-11e9-857d-966f480baa45)
![singlesite-opt5](https://media.github.ibm.com/user/5181/files/d0d17400-a7ce-11e9-8ccd-7ac79b3447da)
![singlesite-opt6](https://media.github.ibm.com/user/5181/files/d0d17400-a7ce-11e9-8cd6-0421b4e1b0fe)

**Comment by jeffchew** [comment]
_On Jul 16, chsanche commented:_
👉 Follow-up meeting scheduled for Thursday 07/18/2019 1:30 to 2 pm (CST)

**Comment by jeffchew** [comment]
_On Jul 17, chsanche commented:_
✏️  **Definitions for Model Model-AI Guidance** started and worked on by @Benjamin-Hansen1 can be viewed on [BOX](https://ibm.box.com/s/nr6rw8ry6nnyxka2rajvif1hg4j65x0l).

**Comment by jeffchew** [comment]
_On Jul 19, chsanche commented:_
👉  Moving the task issue from Sprint 13 to Sprint 14 as recommended since we need one more round of discussion with the Carbon Team next week.

**Comment by jeffchew** [comment]
_On Jul 22, Wonil-Suh1 commented:_
Detaching from design strategy and attaching to content strategy.

**Comment by jeffchew** [comment]
_On Jul 24, chsanche commented:_
**Update:**
Based on the discussion yesterday, it's confirmed that Carbon is not ready to start the IA work for the wedding cake website and no timeline defined as well. 

In order to keep the collaboration going, Jan agreed to meet on a regular cadence so we can keep each other informed on the timeline changes and progress related to the IA work and more.

@Wonil-Suh1 @spbokma Let me know what do you two think, but I think we should close this task issue and keep the IA in the back burner for a few sprints.

**Comment by jeffchew** [comment]
_On Jul 25, Wonil-Suh1 commented:_
Okay. We should define this as an ideation epic to keep it on our radar, and focus on the cup cake.

**Comment by jeffchew** [comment]
_On Jul 25, chsanche commented:_
Sounds good @Wonil-Suh1.

**Comment by jeffchew** [comment]
_On Aug 06, chsanche commented:_
👉 Round two ideation Sketch file can be found on [BOX](https://ibm.box.com/s/27dwgg00qmv0g4l8glu7cmwnjwoj6c4g).

**Comment by JennySanchez** [comment]
The strategy has changed with the Carbon discussions and this EPIC will be closed.
