### ISSUE TITLE
Audit of error pages

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#277]
_vladislav-saling created the following on Jul 10:_  

 Our team owns generic error pages displayed on ibm.com. Webmaster team asked us to review the messaging, if it still makes sense. 

Examples:
https://www.ibm.com/common/errorpages/300.html
https://www.ibm.com/common/errorpages/303.html
https://www.ibm.com/common/errorpages/305.html
https://www.ibm.com/common/errorpages/307.html
https://www.ibm.com/common/errorpages/400.html
https://www.ibm.com/common/errorpages/401.html
https://www.ibm.com/common/errorpages/402.html
https://www.ibm.com/common/errorpages/403.html
https://www.ibm.com/common/errorpages/404.html
https://www.ibm.com/common/errorpages/405.html
https://www.ibm.com/common/errorpages/406.html
https://www.ibm.com/common/errorpages/407.html
https://www.ibm.com/common/errorpages/408.html
https://www.ibm.com/common/errorpages/409.html
https://www.ibm.com/common/errorpages/410.html
https://www.ibm.com/common/errorpages/411.html
https://www.ibm.com/common/errorpages/412.html
https://www.ibm.com/common/errorpages/413.html
https://www.ibm.com/common/errorpages/414.html
https://www.ibm.com/common/errorpages/415.html
https://www.ibm.com/common/errorpages/416.html
https://www.ibm.com/common/errorpages/417.html
https://www.ibm.com/common/errorpages/500.html
https://www.ibm.com/common/errorpages/501.html
https://www.ibm.com/common/errorpages/502.html
https://www.ibm.com/common/errorpages/503.html
https://www.ibm.com/common/errorpages/504.html
https://www.ibm.com/common/errorpages/505.html

I suggested, that we might want to do that as part of future redesign, when ibm.com will be moving to IDL. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1209_

**Comment by jeffchew** [comment]
_On Jul 15, Wonil-Suh1 commented:_
Carbon's design proposal here: [Sketch](https://ibm.box.com/s/b0j21z8k2x6f09ml91991ynj0hkzlzkf). This is for product experience and carbon site, but we can leverage this design.

**Comment by jeffchew** [comment]
_On Aug 13, waferjon commented:_
Hi all - is there any update as to when this error page messaging review might be done and changes made if required?  Thanks for your help....John

**Comment by jeffchew** [comment]
_On Aug 13, Wonil-Suh1 commented:_
Thanks for capturing this. Will pick up this work with a UX story (#1448).

**Comment by jeffchew** [comment]
_On Aug 13, Wonil-Suh1 commented:_
@vladislav-saling @waferjon are there any other types of error pages?

**Comment by jeffchew** [comment]
_On Aug 15, waferjon commented:_
@Wonil-Suh1 Hi Wonil,  similar pages exist for intranet as well.  I imagine if the external ones are changed then the changes may apply internally for w3 also. I don't know if your team covers w3 though. 
Intranet Web sites
http://w3.ibm.com/common/errorpages/errorpages.zip

**Comment by jeffchew** [comment]
_On Aug 15, Wonil-Suh1 commented:_
@waferjon are there proper URLs where I can see the pages? The HTML files open broken for now.

But to your point, w3 error pages would be CIO's scope.

**Comment by jeffchew** [comment]
_On Aug 16, waferjon commented:_
Hi Wonil thanks for clarifying re the w3 error pages. I'll chase that with the w3 team.  Perhaps they can copy the messages from the www structure when those are revised.    
For your other question, I don't have access to the proper URL's for those w3 error messages.  All I have is the zip file messages for each error condition. 

regards,
John

**Comment by JennySanchez** [comment]
@wonilsuhibm Is this audit done? It looks like the audit is done and we need to have the next step action items created?

**Comment by oliviaflory** [comment]
Duplicate
