### ISSUE TITLE
React: Make modules tree-shakable

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#2879]
### The problem

Though we know that `import { namedImport } from 'package-name'` has negative effects on application bundle size and build time and we have migrated away from it in our internal code, it's easier to use for our adopters and still want to provide good support for this usage.

### The solution

* Add `/*#__PURE__*/` annotations (with wrapping contents in IIFE as necessary).
* Upgrade to latest Babel for [better React component optimization](https://www.infoq.com/news/2020/05/babel-7-10-react-treeshaking/).

**Comment by jeffchew** [comment]
@RobertaJHahn @asudoh moving this one out.

**Comment by RobertaJHahn** [comment]
@asudoh Is this work closed?  Looks like the linked PR is closed.

**Comment by asudoh** [comment]
Thank you for asking @RobertaJHahn - Followed up in team Slack.

**Comment by RobertaJHahn** [comment]
Decided to move to `icebox` in the March 22, 2021 engineering issues refinement meeting.
