### ISSUE TITLE
Utilities: Make modules tree-shakable

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#2880]
### The problem

Though we know that `import { namedImport } from 'package-name'` has negative effects on application bundle size and build time and we have migrated away from it in our internal code, it's easier to use for our adopters and still want to provide good support for this usage.

### The solution

Add `/*#__PURE__*/` annotations (with wrapping contents in IIFE as necessary).

#### Additional Information

- https://babeljs.io/blog/2018/08/27/7.0.0#pure-annotation-support

**Comment by RobertaJHahn** [comment]
Decided to move to `icebox` in the March 22, 2021 engineering issues refinement meeting.

**Comment by RobertaJHahn** [comment]
Jeff to discuss in engineering huddle.
