### ISSUE TITLE
Service: Create the Profile service functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#2890]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Profile` functional specs 

> so that I can:
so that I can properly code the `Profile` service

#### Additional information

  - The Profile service has been developed.  This story is to document the Profile service that exists today as the baseline for future changes.  The functional specs should include the kind of data that is returned, including the PII permissions

#### Acceptance criteria
 - [ ] Documented `Profile` functional specifications

**Comment by photodow** [comment]
not stale

**Comment by RobertaJHahn** [comment]
Old, no longer needed.
