### ISSUE TITLE
Website: cupcake IA & navigation

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#303]
_Wonil-Suh1 created the following on Aug 02:_  

 This story is to create overall IA and navigation model of the new cupcake site.

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1348_

**Comment by jeffchew** [comment]
_On Aug 08, chsanche commented:_
@hahnrob I think this task issue should be an Epic.

**Comment by RobertaJHahn** [comment]
This issue should be changed based on the call with Carbon on Friday, Nov 1.

**Comment by JennySanchez** [comment]
This Epic is no longer relevant to our work or priority and will be closed.
FYI: @RobertaJHahn
