### ISSUE TITLE
Correct aChecker accessibility errors

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#3032]
aChecker is an automated accessibility testing tool.  When run against the ibm.com Library / Storybook patterns and components, an error report was generated.  This epic will be used to track the work to address and investigate the findings.

#### Additional Information
- `karma-accessiblity-checker` code repo: https://github.com/IBMa/equal-access
- How to run our automation and debug the errors: https://github.com/carbon-design-system/ibm-dotcom-library/blob/280aece/packages/react/docs/a11y-compliance-tests.md
- `karma-accessiblity-checker` log example: https://ibm.biz/BdqgA3
- [a11y compliance test report](https://github.com/carbon-design-system/ibm-dotcom-library/runs/899964294?check_suite_focus=true)

**Comment by RobertaJHahn** [comment]
@asudoh Hi Akira, we talked about the work to address the aChecker findings.  I created this epic to track and manage the work.  Could you do a couple of things for me?  

- Could you add aChecker informational links to the Additional Information section of this epic.  I would like to have a link to the tool along with overview and technical documentation in one place.  

- Could you put the aChecker report in the [QA testing docs Box folder](https://ibm.ent.box.com/folder/100897002419) and add the link to the Additional Information section as well.  

Thanks.

**Comment by RobertaJHahn** [comment]
@asudoh Hi Akira, A couple of aChecker questions came up this week.  1)  Is it possible to create an accessibility report that scores the overall compliance of a site or group of web pages?  2) How configurable is the tool?  If these questions might be better covered in a short meeting, Let me know.  Maybe it would be good to do a short demo and Q&A meeting?  I could also add this topic to an existing meeting.  Maybe the engineering meeting on Monday, July 20 and include Linda in that meeting.

cc:  @jeffchew @ljcarot

**Comment by asudoh** [comment]
@RobertaJHahn Interesting questions:

1. `aChecker` doesn't seem to have a notion of "a11y score", but it can report the number of violations, potential violations, etc and compare it to the number the elements `aChecker` scanned.
2. The only configurable options in `aChecker` is the a11y ruleset to use.

Here are some screenshots of the GUI version of `aChecker` (the CI version and the GUI version do the same thing behind the scene):

![image](https://user-images.githubusercontent.com/1259051/87485609-222b7200-c674-11ea-92a6-9565ef0522aa.png)
![image](https://user-images.githubusercontent.com/1259051/87485654-45eeb800-c674-11ea-926a-a313c5dc55d7.png)

**Comment by RobertaJHahn** [comment]
Next step:  Linda will ask Nigel if there is someone who uses aChecker that can help us with next steps for the tool.  We currently feel that someone has to go through the report, find the `red x` entries to create bugs.

**Comment by asudoh** [comment]
Good questions, `aChecker` has only two severity categories, which are, "violation" and "potential violation". And 2) is yes for "potential violation".

**Comment by RobertaJHahn** [comment]
Closing for inaction.  Addressing the accessibility compliance based on the QA reviews done by the India team members.
