### ISSUE TITLE
Create the design checklist for whenever we upgrade Carbon

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#3121]
#### User Story

> As a `[user role below]`:
IBM.com Library Designer

> I need to:
follow all necessary steps when upgrading Carbon in the IBM.com Library

> so that I can:
not skip any important steps

#### Additional information

  - The documentation will be done in a Box Note that is included in the [Team Operation Processes folder](https://ibm.ent.box.com/folder/73421610286)
 - The documentation should identify design and website tasks for both pre and post Carbon upgrade

#### Acceptance criteria
 - [ ] Have a documented list of design items to do whenever we upgrade Carbon
 - [ ] Determine how we can integrate this into our regular workflow

**Comment by JennySanchez** [comment]
**Note:** Based on the Sprint planning conversation, designers will get together to discuss what we think we should have from the requirement perspective. Reserved time to start the discussion on Design Huddle this Friday.

**Comment by JennySanchez** [comment]
Box document created for Friday's discussion - https://ibm.box.com/s/kmzswikkf7p4d1h9fxw4gfbqsy7tc6iy

**Comment by JennySanchez** [comment]
Designers met today and start adding items to the [BOX document](https://ibm.box.com/s/kmzswikkf7p4d1h9fxw4gfbqsy7tc6iy). Based on the discussion, we need to get the development team's input and Wonil sign up as one of the discussion items for the design huddle next week


.![Screen Shot 2021-02-05 at 4.49.47 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/82ae056e-ef13-44cb-b03e-68cf2e7d2a48)
