### ISSUE TITLE
Pattern: CalloutData - Issues related to "Data" and "Short copy" fields

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#3136]
## Detailed description

Issue 1:- Large text (11 characters) on "Data" field makes "short copy" section missing and not visible for the user.

Issue 2:-  In 'Short Copy' field if more than 300 chars are entered in that case 16px spacing is not getting maintained between text and container.![Spacing issue between container and text.jpg](https://images.zenhubusercontent.com/5e21a841639f517d456f7e43/6e6521d8-4a7d-4f4b-b40b-9521b2c08fb8)

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/c63a2ed6-4bd2-416c-a8af-a799dec8569e)

**Comment by RobertaJHahn** [comment]
Lara will reach out to Reboot to mention that if the large content increases, the font may have to get smaller.

**Comment by larahanlon2** [comment]
Reached out to Lila to let her know about our latest discussions.

**Comment by larahanlon2** [comment]
Lila noted that this pattern has not been used yet and that she would like to do some iterations on the minimum height based on user feedback. She agreed to explore type style explorations and character count when revisiting the design of this pattern. She will also get a second opinion from content strategists on her team.

**Comment by ljcarot** [comment]
I'd like to recommend we icebox this until we hear back from design on this.  Let's remove the severity, bug and dev labels and replace with design label @RobertaJHahn
