### ISSUE TITLE
Website content publishing template (for Component - MVP version)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom#3151]
#### User Story

> As an Carbon for IBM.com adopter, 

> I need a way to learn more about the (Name of the Pattern here) component

> so that I can utilize the component to my day to day work.

#### Additional information

- Take a look at the [storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/overview-getting-started--page) - so you know how the component works.   You will also use Storybook as a reference to accurately include the images in the Sketch file.
- Download this [Sketch template](https://ibm.box.com/s/66v0t127kdgo3xqt3u5f7dl56skpealk) to your machine to make the updates. Please review the image set up and the best practices in the file as well.  Name the Sketch file with the following convention: Name of the pattern + version. ex: `Feature card block v1.0`
- Navigate to the visual spec file within this [Carbon for IBM.com Box folder](https://ibm.box.com/s/vo3u9mxn8y7a5d7zoqvrvz7aalbf2yu3) and find the spec file under Components folder - The image that works successfully for most patterns is the 1312px image.  Adjustments may be needed to have this image accurately reflect the Storybook designs.
- Once complete, save the revised Sketch file in the Components folder / sub-folder [here](https://ibm.box.com/s/pyu51d278bp1nv1kvgpo8zsp53wvx5x3).
- Export the individual images with a 2X setting, saving them into the Layout Pattern sub-folder that contains the Sketch file.  These exported images will be used when creating the Markdown for publishing
 - Use this Sketch file to create the Markdown version of the web page in [Github](https://github.com/carbon-design-system/ibm-dotcom-library-website/tree/master/src/pages/patterns).
    - Find the .mdx file for the Layout Pattern assigned
    - Copy the content from the Sketch file into the .mdx file
    - Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
    - When ready to deploy, include Jenny, Linda, Jeff and Wonil as a PR Reviewers and Approvers.
    - Jenny will review and merge the PR

#### Acceptance criteria
- [ ] Content crafting is done.
- [ ] Asset image creation is done.
- [ ] Page design is done.
- [ ] Publishing with markdowns is done.
- [ ] QA'd by Jenny
- [ ] Web page preview is approved by Linda, Jeff and Wonil
- [ ] Web page is published

**Comment by JennySanchez** [comment]
@RobertaJHahn We can close this issue.

**Comment by RobertaJHahn** [comment]
No longer needed.  Closing
