### ISSUE TITLE
[Cards] Revisit card aspect ratio

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#3270]
During Product landing page's implementation phase, we noticed the cards in DDS library do not observe any **aspect ratio**. Original design intent is to always follow one of the aspect ratios https://www.ibm.com/design/language/2x-grid/#aspect-relationships. 

**Current:** 
![image](https://user-images.githubusercontent.com/15144993/88405458-4df9d680-cd9d-11ea-9b37-9e4453a31980.png)

**Expected (wireframe):** 
![image](https://user-images.githubusercontent.com/15144993/88405611-84cfec80-cd9d-11ea-99ee-9b03589bf23d.png)

Slack discussion on this issue: 
FYI @photodow 

![image](https://user-images.githubusercontent.com/15144993/88404396-d4adb400-cd9b-11ea-81dd-3465597e4b27.png)

![image](https://user-images.githubusercontent.com/15144993/88404162-800a3900-cd9b-11ea-90c7-c8817e1fb573.png)

**Comment by RobertaJHahn** [comment]
Next step:  This issue will be used for the Engineering exploration.  If a solution is available, then will be turned into an Epic and related issues will be created.  Adding to the Engineering meeting agenda.
