### ISSUE TITLE
Web component:  MegaMenu desktop and mobile Prod QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#3281]
_**This work is a follow-on to the development work done to create the same React version.  The React development was managed under epic (#3120)**_

#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `MegaMenu`

> I need to:
have a version of the component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- **See the Epic for the Design and Functional specs information**
-  Desktop Dev issue (#3284)
-  Mobile Dev issue (#3849)
- Once development is finished the updated code is available in the [**Web Components Canary Environment**](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/overview-getting-started--page) for testing.
- The [**React canary environment**](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/overview-getting-started--page) component should be used for comparison

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Component is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by annawen1** [comment]
@Praveen-sr The Megamenu web component has been developed. You can test here: https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-masthead--default

CC: @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Prod QA testing of desktop has started

**Comment by RobertaJHahn** [comment]
Msg from Kenny posted to Dev issue:  @RobertaJHahn @Praveen-sr This is ready for QA http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-masthead--default

**Comment by Praveen-sr** [comment]
@RobertaJHahn Prod QA testing and accessibility testing has be completed.
