### ISSUE TITLE
Web component: MegaMenu Menu Visual QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#3283]
_**This work is a follow-on to the development work done to create / change the same React version.  The React development was managed under epic (#3120)**_

#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `MegaMenu`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- Dev Issue (#3284)
- [Storybook link](TBD)

 #### Tasks
Ensure the `MegaMenu MVP` component has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by annawen1** [comment]
@oliviaflory The megamenu web component has been developed. You can view here: https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-masthead--default
