### ISSUE TITLE
Web Component: Develop MegaMenu desktop version from the React version - Group 3

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#3284]
_**This work is a follow-on to the development work done to create / change the same React version.  The React development was managed under epic (#3120)**_

#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `web components MegaMenu desktop version`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- This work was scheduled under the old process where the React version was developed first.
- **See the Epic for the Design and Functional specs information**
- Design QA testing issue (#3283)
- Prod QA testing issue (#3281)

#### Acceptance criteria
- [x] Include README for the web component and corresponding styles
- [x] Use corresponding React styles in styles package
- [x] Do not create knobs in Storybook that include JSON objects
- [x] Break out Storybook stories into multiple variation stories, if applicable
- [x] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [x] Minimum 80% unit test coverage
- [x] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [x] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [x] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
- [x] The Storybook link is added to the Design QA issue for their testing
- [x] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by jeffchew** [comment]
@RobertaJHahn most likely won't get to this one, moving this one out. cc: @annawen1

**Comment by RobertaJHahn** [comment]
@annawen1 Hi Anna, based on our conversation about the fluid nature of the design requests, I have moved this development issue out to sprint 20-21.
