### ISSUE TITLE
LinkwithIcon: position left svg

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#3389]
## Detailed description

> Describe in detail the issue you're having.

For the react component `LinkwithIcon` it keeps rendering the right arrow icon svg even when placed on the left side for storybook. On your local machine the left arrow icon is rendered correctly. 

Also, when opening `LinkwithIcon` in a new window in storybook set to disabled.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

LinkwithIcon

> What did you expect to happen? What happened instead? What would you like to
> see changed?

expected to see left icon like "<- Link text"

## Steps to reproduce the issue

1. go to https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-linkwithicon--default
2. iconPosition to left (notice wrong icon)
3. open in new window (notice disabled link)

## Additional information

<img width="955" alt="Screen Shot 2020-07-30 at 2 04 55 PM" src="https://user-images.githubusercontent.com/20210594/89070972-b6f7c600-d32a-11ea-858b-93c096fa7ec1.png">

**Comment by diegomarcuz** [comment]
This is what I found for this issue (I couldn't fix it): 
- On staging environment icon position isn't correct, but disable feature is fine
- On official environment icon position isn't correct, but disable feature is fine
- On my local icon position is fine (as Ari said), but disable feature isn't.

**Comment by jeffchew** [comment]
A lot of time has been spent on this issue (with a few devs looking into this), and we see this behavior happening in the static deployments but not in local development. As this is a low priority issue, making the decision to close this.
