### ISSUE TITLE
Web Component:  Locale modal needs link with icon

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/carbon-for-ibm-dotcom#3446]
### The problem
DDS designers updated the locale selector eyebrow to `link with icon` component.

### The solution
In the original design, the locale selector had a gray eyebrow that allows users to navigate back to the first screen. However, designers felt that using the `link with icon` component would be a more consistent experience for users and would utilize the system better.

### Additional information

Current Storybook implementation:
<img width="823" alt="Screen Shot 2020-08-05 at 11 05 52 AM" src="https://user-images.githubusercontent.com/53093550/89431265-af129a00-d70d-11ea-90de-10dcff140780.png">

Updated design specs:
<img width="1009" alt="Screen Shot 2020-08-05 at 11 09 11 AM" src="https://user-images.githubusercontent.com/53093550/89431281-b33eb780-d70d-11ea-856c-d9b382116566.png">

**Comment by guilhermelMoraes** [comment]
@IgnacioBecerra said this is a duplicate. Here's his PR #4568
