### ISSUE TITLE
Error pages: UX design

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#348]
_Wonil-Suh1 created the following on Aug 13:_  

 ### User story
As a user, I need to be informed of the error that occurred and the next steps.

### Notes
Details on the current error pages is captured in the epic, https://github.com/carbon-design-system/ibm-dotcom-library/issues/348.

Examples of http error pages are captured in this story (#1209).

### Acceptance criteria
- [ ] Wireframes with content have been produced
- [ ] Wireframes have been reviewed by content strategists
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1446_

**Comment by oliviaflory** [comment]
Duplicate
