### ISSUE TITLE
Researching Locale banner logic 

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/carbon-for-ibm-dotcom#3493]
#### User Story

> As a `[designer for the locale banner]`:

> I need to:
understand if the locale banner logic works with current design

> so that I can:
build a functional locale banner with the current logic.

#### Acceptance criteria
 - [ ] _{{Identifying any concerns with the logic}}_
 - [ ] _{{Review work with designer}}_
 - [ ] _{{Compare documented logic with existing logic in v18}}_

Files for locale banner can be found here: https://ibm.ent.box.com/folder/113158587587

**Comment by shixiedesign** [comment]
Deprecating locale change banner after google analytics reveal most people simply stay on current locale page. So the hypothesis of the banner that people need to change locale is not right. This banner is not needed.
