### ISSUE TITLE
Mega menu mobile – text wrap

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#3518]
### The problem
_{{A clear and concise description of what the problem this new feature is trying to solve. (ex. I'm always frustrated when...)}}_

When content is longer than the width of the mobile or medium breakpoint menu, the text is cut off with ellipses and the user cannot read the entire description (example below).

<img width="332" alt="Screen Shot 2020-08-11 at 9 50 50 AM" src="https://user-images.githubusercontent.com/45692622/89923409-8dfaef00-dbce-11ea-8149-c35d15236c5a.png">

### The solution
_{{A clear and concise description of what you want to happen}}_

I would like the menu to allow text to wrap onto a second line.

<img width="403" alt="Screen Shot 2020-08-11 at 12 32 26 PM" src="https://user-images.githubusercontent.com/45692622/89923654-e6ca8780-dbce-11ea-9a6a-afaea0c21d7d.png">

I had included these specs in the original design, however Kenny informed me Carbon handles long text with the ellipses. 

~[02 mega menu reusable pieces mobile@1x.pdf](https://github.com/carbon-design-system/ibm-dotcom-library/files/5058182/02.mega.menu.reusable.pieces.mobile%401x.pdf)~

Link to mega menu spec folder: https://ibm.ent.box.com/folder/118692148518
*Note: page 6 and 7 of the PDF show examples of text wrap*

### Additional information
 _{{Please provide any additional information or resources for reference}}_
 - Functional Spec changes are not needed.
 -

**Comment by RobertaJHahn** [comment]
Request is to support text wrap rather than ellipses

Steps:
DDS Dev to implement the override
Dev to submit request to Carbon to support this feature

Create an epic

1. Dev issue
design issue
Visual QA
Prod QA

.

**Comment by oliviaflory** [comment]
Link to mega menu spec folder: https://ibm.ent.box.com/folder/118692148518
Note: page 6 and 7 show examples of text wrap
