### ISSUE TITLE
Issues related to Table of Contents Component

### ISSUE THREAD

**Issue by sabhareesan** [carbon-design-system/carbon-for-ibm-dotcom#3526]
**1. The heading in TOC is hidden during page scroll. (All browsers)**
![chrome-capture (6)](https://user-images.githubusercontent.com/23634668/89978380-032bfa00-dc8b-11ea-9782-2802cc20473f.gif)

**2. The menu items are also getting hidden during page scroll (Only in Safari)**

**3. Hamburger icon in mobile view is not clickable**
![image](https://user-images.githubusercontent.com/23634668/89978503-4ab28600-dc8b-11ea-8e77-ca99f7ea05fa.png)

**4.In Mobile View, when clicked on "Jump to..." from the menu an error is thrown**
![image](https://user-images.githubusercontent.com/23634668/89978581-759cda00-dc8b-11ea-8be0-45028935fc7d.png)
Error
![image](https://user-images.githubusercontent.com/23634668/89978636-949b6c00-dc8b-11ea-969b-e778ba6c02ad.png)

**Comment by RobertaJHahn** [comment]
Adopter is Profile

Break down into 4 issues:  #1 and FR with priority of Low, #2  Bug Sev 3, #3 may be a dup, if not Sev 3, #4 sev 4

**Comment by sabhareesan** [comment]
@RobertaJHahn can you please provide the issue numbers for the above defects are tracked.

**Comment by RobertaJHahn** [comment]
@sabhareesan  I started to break this bug into 4 as mention in the comment above.  Unfortunately, there are too many questions that I don't have the answers to.  When creating a bug you should use the Bug Report template.  When reporting a bug.  Could you please break this down into 4 separate bugs using the template?  

Create a new issue and select the Bug Report template in the top row.  

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/cdebc6b7-9101-4620-8a7e-56fbbc769c1d)
