### ISSUE TITLE
Footer only showing US, no alternate countries

### ISSUE THREAD

**Issue by flatcoding** [carbon-design-system/carbon-for-ibm-dotcom#3573]
## Detailed description

> Describe in detail the issue you're having.
The Footer is only showing up with US content. Country selector predefine to US, and no alternate links available.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Footer

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Footer adapts to passed locale. Country selector should include all alternate links.

> What browser are you working in?
E.g. FF / Chrome, latest version.

> What version of the IBM.com Library are you using?
V1.9, react, next.js template

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Storage Digital Platform - about to go live, any immediate help appreciated.

## Steps to reproduce the issue

Use ibmdotcom library for react / next.js, V1.9
Use standard _apps.js
Pass cc-lc parameters from URL to footer props

## Additional information

![2020-08-14 11_30_16-Mozilla Firefox (Private Browsing)](https://user-images.githubusercontent.com/47025385/90235458-9dbe4180-de21-11ea-96cd-f2fce40c4cc7.png)
![2020-08-14 11_29_59-Mozilla Firefox (Private Browsing)](https://user-images.githubusercontent.com/47025385/90235461-9e56d800-de21-11ea-9bf4-690271b343be.png)

**Comment by andysherman2121** [comment]
Hi @flatcoding you can set the link alternatives to fix this issue. The documentation can be found via this link http://ibmdotcom-react.mybluemix.net/?path=/docs/overview-building-for-ibm-dot-com--page
