### ISSUE TITLE
November 2020 Release Plan (v1.13.0) 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#3598]
# Timeline

- **November 13, 2020**: Code freeze
- **November 16-24, 2020**: Release Candidate(s) and testing
- **November 25, 2020**: Full Release

# Features

## Global

- Upgrade to latest Carbon (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4272)

### Features
- **card-section**:  introducing web component versions (#4471)
- **content-group-cards**:  create web component (#4487)
- **leaving-ibm**:  Leaving IBM modal web component (#4453)
- **content-group-horizontal**:  create web component (#4435)
- **Masthead**:  add mobile megamenu (#4443)
- **megamenu**:  megamenu desktop web component (#4384)
- **cta-section**:  web component version (#4338)
- **callout with media**:  web component version (#4343)
- **content-item-horizontal**:  create web component (#4389)
- **logo-grid**:  web component created (#4371)
- **logo-grid**:  web component created (#4287)
- **content-section**:  web-component version (#4275)
- **image-with-caption**:  support responsive image (#4312)
- **callout-quote**:  web-component created  (#4228)
- **leadspace**:  leadspace web component (#4084)
- **feature-flag**:  adding feature flag capability in web components (#4220)

### Fixes
- **modal**:  remove close button offset for full-width mode (#4299)
- **Images**:  update FPO images url (#4482)
- **cta-section**:  aligning link list with other text elements (#4461)
- **feature-card**:  fix icon position (#4412)
- **image-with-caption**:  a11y fixes (#4395)
- **Footer**:  update readme (#4409)
- **content-block**:  fix layout (#4397)
- **styles**:  ensure dds-prefix variable is included (#4396)
- **table-of-contents**:  ensure anchor is visible upon jump-to-content (#4297)
- **button-group**:  eliminate duplicate outline (#4350)
- **button-group**:  fixed focus outline going past the buttons on web components (#4348)
- **quote**:  fixed spacing for closing quote (#4288)
- **feature-card-block-medium**:  update web component layout (#4323)
- **table-of-contents**:  fix header space (#4298)
- **card link**:  focus styles (#4318)
- **quote**:  adjust quote grid classes in storybook (#4304)
- **locale-modal**:  ensure input field is cleared on reset (#4296)
- **masthead-search**:  stop toggling active state on focus (#4295)
- **linklist**:  fix linklist focus styles (#4271)
- **table-of-contents**:  support dark theme (#4213)
- **footer**:  ensure IBM logo icon is visible (#4226)
- **feature-card**:  remove redundant flex-wrap (#4176)
- **masthead-search**:  re-apply #3932 (#4227)

### Features
- **Masthead**:  add search custom events (#4460)
- **megamenu**:  megamenu desktop web component (#4384)
- **Masthead**:  React masthead alternate logo and tooltip options (#4401)
- **leadspace-with-search**:  introducing new pattern (behind feature flag) (#3987)
- **overflow**:  add animation and update snapshots (#4305)
- **leadspace**:  leadspace web component (#4084)
- **LightboxMediaViewer**:  allow user override vid title/desc (#4238)
- **feature-flag**:  adding feature flag capability in web components (#4220)

### Fixes
- **cardgroup**:  update sameheight selectors (#4484)
- **masthead**:  add aria-hidden to overflow nav carets (#4489)
- **Images**:  update FPO images url (#4482)
- **Footer**:  update readme (#4409)
- **masthead**:  remove console errors (#4404)
- **masthead**:  overflow tabbing adjusted (#4381)
- **language-selector**:  update language selector to use select (#4335)
- **masthead**:  update overflow scrolling positions (#4333)
- **feature-card-block-medium**:  update web component layout (#4323)
- **masthead**:  selected item accessible to screen reader (#4302)
- **megamenu**:  added protection to fix layout problem (#4290)
- **lightbox-m-viewer**:  adding again `autoPlay` to video (#4289)
- **Masthead**:  have nav item render with selected styles in mobile nav (#4259)
- **lightbox-m-viewer**:  removing autoplay from VideoPlayer (#4258)
- **modal**:  add primary focus on open (#4242)
- **table-of-contents**:  support dark theme (#4213)
- **footer**:  ensure IBM logo icon is visible (#4226)

### Features
- **content-group-cards**:  create web component (#4487)
- **content-group-horizontal**:  create web component (#4435)
- **megamenu**:  megamenu desktop web component (#4384)
- **cta-section**:  web component version (#4338)
- **Masthead**:  React masthead alternate logo and tooltip options (#4401)
- **callout with media**:  web component version (#4343)
- **content-item-horizontal**:  create web component (#4389)
- **logo-grid**:  web component created (#4371)
- **leadspace-with-search**:  introducing new pattern (behind feature flag) (#3987)
- **logo-grid**:  web component created (#4287)
- **overflow**:  add animation and update snapshots (#4305)
- **tag**:  expressive theme update (#4166)
- **callout-quote**:  web-component created  (#4228)
- **leadspace**:  leadspace web component (#4084)

### Fixes
- **modal**:  remove close button offset for full-width mode (#4299)
- **feature-card**:  fix icon position (#4412)
- **megamenu**:  fix scrollbar styles (#4417)
- **Footer**:  fix micro footer button css (#4415)
- **styles**:  ensure dds-prefix variable is included (#4396)
- **content-item-horizontal**:  fix heading styling (#4402)
- **content-group-mixed**:  fix pictogram item row on md breakpoint (#4282)
- **table-of-contents**:  ensure anchor is visible upon jump-to-content (#4297)
- **language-selector**:  update language selector to use select (#4335)
- **masthead**:  update overflow scrolling positions (#4333)
- **quote**:  fixed spacing for closing quote (#4288)
- **feature-card-block-medium**:  update web component layout (#4323)
- **table-of-contents**:  fix header space (#4298)
- **card link**:  focus styles (#4318)
- **megamenu**:  added protection to fix layout problem (#4290)
- **linklist**:  fix linklist focus styles (#4271)
- **FeatureCard**:  remove unused styles (#4243)
- **Masthead**:  have nav item render with selected styles in mobile nav (#4259)
- **table-of-contents**:  support dark theme (#4213)
- **footer**:  ensure IBM logo icon is visible (#4226)
- **feature-card**:  remove redundant flex-wrap (#4176)

### Features
- **Masthead**:  React masthead alternate logo and tooltip options (#4401)
- **locale**:  introducing cache busting logic (#4325)
- **translation**:  introduce cache busting logic (#4240)

**Comment by annawen1** [comment]
V1.13.0 has been released
