### ISSUE TITLE
Icon as eyebrow in Card component

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon-for-ibm-dotcom#3605]
We would like to use the Card in IBM docs project and display an icon in place of eyebrow,
as
![image](https://user-images.githubusercontent.com/15310250/90486547-6a3d2900-e139-11ea-8fdb-6cdf1ee49be7.png)

**Comment by wonilsuhibm** [comment]
Hi Miri, can you attach an example or design please?

**Comment by kyjak** [comment]
Just use the eyebrow={<Settings32/>}  in any card.
where Settings32 is a react icon from carbon. the Card component already displays this with no problem, 
that's why I suggested just to edit the proptype for eyebrow to Object, to get rid of the error in console.

result looks like this 
![image](https://user-images.githubusercontent.com/15310250/90521325-b2287400-e16a-11ea-96e1-7ef2650154c1.png)

**Comment by RobertaJHahn** [comment]
Wonil will talk to Andree Proulx.

**Comment by RobertaJHahn** [comment]
meeting scheduled week of sept 21

**Comment by wonilsuhibm** [comment]
Per agreement with Andrée, the Card with pictogram component will be used instead of this. 

For details, see this FR:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4093

**Comment by RobertaJHahn** [comment]
Closing based on Wonil's comments above.  The future pictogram variations work will be managed under epic (#4093)
