### ISSUE TITLE
Language selector as a separate component

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon-for-ibm-dotcom#3606]
In case KC does a custom footer, which is very likely, we need to move the language selector out of the default dotcom footer.
Can language selector be exported as a separate component?

**Comment by wonilsuhibm** [comment]
@kyjak Please work with us to figure out the custom footer. All IBM.com pages must adopter one of the three footer variants for consistency. But if there are needs for updated design, please work with us.

**Comment by kyjak** [comment]
This is what we have designed, as you can see there is a "micro" dotcom footer, and above that KC footer with language selector.
This is the reason we'd like to move out the language selector and place it elsewhere.
![image](https://user-images.githubusercontent.com/15310250/90536097-e6586080-e17b-11ea-9a42-cee29620f94b.png)

**Comment by wonilsuhibm** [comment]
@kyjak we do have a Carbon version of the micro footer being developed at the moment. Design specs and Sketch file is here: https://ibm.box.com/s/nsbccv6jigfw78uwq3r0242qks1x1f87

WIll this work for you?

**Comment by kyjak** [comment]
Andree Proulx has to confirm this. However, the problem is how to use dotcom language selector in the KC footer.

**Comment by RobertaJHahn** [comment]
@kyjak  Can you set up a meeting with Andree, Linda, Wonil and Jeff to talk about the solution and designs.

**Comment by kyjak** [comment]
yes, will do

**Comment by aiproulx** [comment]
@wonilsuhibm we want to use the standard micro footer, but the request is to support a language selector in the footer, instead of a Geo.
Can you provide a hook for us (KC) to insert a custom language selector instead of the Geo selector?

**Comment by RobertaJHahn** [comment]
No longer needed.  Closing
