### ISSUE TITLE
React:  Customizable 8-bar IBM logo in the Carbon Masthead

### ISSUE THREAD

**Issue by ilrina** [carbon-design-system/carbon-for-ibm-dotcom#3667]
### The problem
U.S. home page has been using a customized 8-bar IBM logo in the Masthead in response to significant cultural moments. The change consists of a new logo file with color changes and an addition of the tool tip with a message. The changes are local to the U.S. home page. The ask is for these changes to become global.

Our metrics show a significant amount of clicks on the IBM logo on the home page that result in reloading the home page. To mitigate this frustrating experience, we are using the tool tips pattern to add a message. The Pride Month message contained a link to the Pride page.

![Screen Shot 2020-08-20 at 10 17 49 AM](https://user-images.githubusercontent.com/6701695/90791595-66470d80-e2d7-11ea-8eb4-63c7ad4de3bd.png)

### The solution
1)  US Home Page:  
     - Ability to replace the logo file
     - Ability to add the tool tip overlay with a message
     - Ability to have a contextual link in the tool tip 
2)  Logo file change on the U.S. home page is global, it changes the logo on all ibm.com pages.

### Additional information
- [Functional specs Box link](https://ibm.ent.box.com/folder/59063660753)
- **Committed for the November release**

There are several concerns.

For the U.S. pages:
- The logo on all U.S. pages other than the home page has to link to the U.S. home page

For the GEO pages:
- U.S. cultural moments might not have any significance in some GEOs. The GEOs should be able to have an exception from the logo change
- The logo on pages other than local home pages has to link to the local home pages
- If used, the tool tip overlay with the message in English would have to be translated. It will add cost and complexity. If possible, the tool tip overlay should be optional.

_The details in this Feature Request have been changed to include details from issue (#3666)_

**Comment by RobertaJHahn** [comment]
@photodow Could you add links to the functional specs we reviewed in the meeting earlier today?  Add the `func specs done` label and let me know so that I can closed this sprint.

**Comment by photodow** [comment]
Here you go @RobertaJHahn 

https://ibm.box.com/s/njtdtyhj16bvs0hrdoq2xtcyg720ttxm
