### ISSUE TITLE
Create Lead space pattern page for website

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/carbon-for-ibm-dotcom#3703]
#### User Story

> As a `[user role below]`:
IBM.com Library adopter

> I need to:
Understand what Lead space patterns are and where they are used on ibm.com

> so that I can:
ensure my designs adhere to best practices

#### Additional information
- This is one of the most popular patterns seen on ibm.com (and other web/digital platforms)
- There is MVP WIP content available [here](https://ibm.invisionapp.com/share/2PO04US6CX9#/319576751_Pattern-Intro-V5) that was created for future state prototype.

#### Acceptance criteria
- [ ] Lara creates the In-page navigation pattern MVP page
- [ ] Jenny reviews the content 
- [ ] Wonil reviews and approves the content before publishing

**Comment by larahanlon2** [comment]
This is dependent on [Lead space research over on the Ideation board](https://github.com/carbon-design-system/digital-design-ideation/issues/127). The outcome of the research story (focusing on things like height, user mindsets) will help to inform the guidelines of the pattern we publish on the site.

**Comment by larahanlon2** [comment]
Draft content can be found here: https://ibm.ent.box.com/notes/725421390623

**Comment by larahanlon2** [comment]
Draft mockup can be found here: https://ibm.box.com/s/mukebu21clvkkz3wofnaw06iqpo9u8t3

![pattern--lead-spaces--v1 0](https://user-images.githubusercontent.com/53093550/94940736-e6998a80-04a1-11eb-94e4-549fd66aa151.jpg)

**Comment by JennySanchez** [comment]
@RobertaJHahn The Lead space: variation research #127 on the ideation board needs to be done before the publishing can start, as discussed in the Sprint Planning meeting today. Let's move this to Sprint 20-23 to allow the research work to be done in Sprint 20-22 (starting next Monday).

**Comment by wonilsuhibm** [comment]
Updated Sketch file with the latest thinking and the dimensions that define lead spaces here: 
https://ibm.box.com/s/27nfxovqcoktv49li79vpka2h7dgh2xi

### The dimensions
- Where the page is on the journey, rough segments (early, mid, checkout, post-purchase, etc)
- Which page type within each segment (product listing, solution, home page, etc)
- Expressive VS productive lead spaces
- Centered VS left-aligned

### Potential MVP content suggestion
- Section 1: The dimensions of a lead space
- Section 2: Lead space size standards
- Section 3: Content alignment standards (left, centered)

**Comment by JennySanchez** [comment]
@wonilsuhibm The draft MVP version of the Lead Space patterns page content is in markdown and ready for edits as discussed. 
See [PR 729](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/729) for detail.



The initial design shared with you via Slack yesterday is included below.
![patterns-leadspace-MVP-v1.0.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/2fe5413b-cecb-466c-af4e-9ba9c2cdb3ed)

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/carbon-for-ibm-dotcom-website #733](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/733) via [**ZenHub**](https://www.zenhub.com/)
