### ISSUE TITLE
Component: CTA section - Primary button is smaller compared to secondary button.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#3708]
## Detailed description

URL: https://ibmdotcom-react-staging.mybluemix.net/

On iPhone - Safari & chrome browsers

Issue : Primary button is appears smaller compared to secondary button.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/12da184f-7f4d-464f-a097-66729df5527a)

**Comment by RobertaJHahn** [comment]
This bug is similar to (#3709).  Same developer may want to pick up both.

**Comment by IgnacioBecerra** [comment]
Seems like both this issue and #3709 have been solved.
