### ISSUE TITLE
Component: CTA - Video button is smaller compared to second button

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#3709]
## Detailed description

URL: https://ibmdotcom-react-staging.mybluemix.net/

On iPhone - Safari & chrome browsers

Issue : Video button is smaller compared to another button

## Steps to reproduce the issue

1. Open react staging link on iPhone and navigate to CTA 
2. In Knobs, change button 1 to video
3.  Now verify the button sizing.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/d3553cea-002c-42f6-8c35-78cf7217a3f8)

**Comment by RobertaJHahn** [comment]
This bug is similar to (#3708).  Same developer may want to pick up both.
