### ISSUE TITLE
Component: Micro Footer - With tab/shift-tab focus is going to the mentioned elements which is a non interactive element.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#3813]
## Detailed description

Issue : With tab/shift-tab focus is going to the mentioned elements which is a non interactive element.

Expected : Focus should not go to the non interactive element. If it’s a interactive element make it operable thru keyboard.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/228f55c1-80dc-4814-ad2f-4836d1221d2b)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/50a0ad3f-9d0e-48c6-a1ff-466cd140832e)

**Comment by IgnacioBecerra** [comment]
I think this issue has been fixed already, can't seem to replicate it.

**Comment by kennylam** [comment]
@Praveen-sr this has been resolved
