### ISSUE TITLE
Component: Lightbox Media Viewer - Allow title & description to be customized when using video

### ISSUE THREAD

**Issue by rsebade** [carbon-design-system/carbon-for-ibm-dotcom#3848]
### The problem
The current component loads the title and description directly from media center via the API. As an adopter of the library we would like the ability to tailor these content sections to our users, rather than the default title and description provided.

### The solution
Allow the user to pass props in to override the title and description provided by the API.

**Comment by RobertaJHahn** [comment]
@rsebade would you be interested in making this change and contributing it back?

**Comment by RobertaJHahn** [comment]
Roberta will schedule a meeting to talk to Ryan about contribution model.  Ryan, Jeff invitees.

**Comment by RobertaJHahn** [comment]
Meeting scheduled Monday, Sep 28.

**Comment by RobertaJHahn** [comment]
Ryan has volunteered to make these changes.  Assigned the issue to him.  He will work on it in sprint 20-20.

**Comment by RobertaJHahn** [comment]
@rsebade I am moving this to the next sprint.  Have you worked on this feature request?  We link the PR's to the issues so that we know when dev has finished their work.

**Comment by rsebade** [comment]
Hey @RobertaJHahn , sorry about the delay, I just submitted a pull request!
