### ISSUE TITLE
Web Components: Develop MegaMenu Mobile version from the React version - Group 3

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#3849]
_**This work is a follow-on to the development work done to create / change the same React version.  The React development was managed under epic (#3120)**_

#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `web components MegaMenu mobile version`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- This work was scheduled under the old process where the React version was developed first.
- **See the Epic for the Design and Functional specs information**
- Design QA testing issue (#3283)
- Prod QA testing issue (#3281)

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Use corresponding React styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Design QA issue, tagging Wonil and Roberta, when development is finished
- [ ] The Storybook link is added to the Design QA issue for their testing
- [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by RobertaJHahn** [comment]
@kennylam As we discussed in the meeting earlier today, I am moving this development out to sprint 20-21.  Hopefully the Reboot change requests will slow down by then.

**Comment by kennylam** [comment]
@RobertaJHahn @Praveen-sr This is ready for QA http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-masthead--default
