### ISSUE TITLE
Component: Mega Menu - Clicking on menu options, links seem to vibrate(shift there position).

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#3865]
## Detailed description

On Windows - Firefox & chrome 
Issue: 

1. On Mega menu, clicking on menu options, links seem to vibrate(shift there position).
2. On few menu options, grey scroll is displayed. here scroll is not needed. Ex - "Explore more & COVID-19"

Note: On Mac - safari, chrome & Firefox above issue does not exist.
## Additional information

![Scroll.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/1704a0b6-cffa-4155-b39c-226272f76660)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/29374a90-bca9-406a-ad11-3ae129341483)

**Comment by kennylam** [comment]
@RobertaJHahn @Praveen-sr This has been fixed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4417

See http://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--default
