### ISSUE TITLE
React:    Masthead Overflow feature request

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#3873]
This epic will contain a description of the overall scope, development instructions and links to all of the issues required to complete the work.

#### Additional Information
- Olivia is working on the design.
- [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/59063660753?s=mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1)

#### Acceptance criteria
- [ ] Additional stories are created, if needed, for any work to be done in future sprints. 
- [ ] Designs and functional specs are reviewed with the DDS developers for sizing and issue refinement.

**Comment by photodow** [comment]
Here are the functional specs.

https://ibm.box.com/s/h99kmmqe260ibrb8of8pu8rxizemlypt
