### ISSUE TITLE
Errors on console when including ibm-common.js

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon-for-ibm-dotcom#3879]
We followed the instructions for building IBM.com pages:
https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/docs/building-for-ibm-dotcom.md

Now we see errors on the console:
![Screenshot 2020-09-09 at 09 52 58](https://user-images.githubusercontent.com/50624181/92570489-45dcf400-f282-11ea-80f1-3d01a983f17a.png)

Are these severe errors or can we ignore them?

**Comment by KJaspers** [comment]
I forgot to mention that we see the error in our development environment: www.blueworkscloud.com
We didn't try it in our production environment yet: www.bpm.ibmcloud.com

Maybe we should use a different //1.www.s81c.com/common/stats/ibm-common.js include for a development environment after all? Or just ignore the errors?

**Comment by kennylam** [comment]
Hi @KJaspers, are you using an ad blocker? Many elements of `ibm-common` will be blocked if you are. Is it possible to check with ad blockers disabled, or on another browser?

**Comment by RobertaJHahn** [comment]
No response from the adopter.  Closing
