### ISSUE TITLE
Masthead L0 active link: blue underline should be wider

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/carbon-for-ibm-dotcom#3911]
## Detailed description

**Describe in detail the issue you're having.**
The active blue underline, when displaying in the L0, should fill the same with as the background hover fill. Currently, it looks 1px too short on both the left and right.

<img width="356" alt="Screen Shot 2020-09-10 at 1 35 46 PM" src="https://user-images.githubusercontent.com/53093550/92785625-92552c00-f375-11ea-8471-f772b35b44a3.png">

**Is this a feature request (new component, new icon), a bug, or a general issue?**
Design defect

**Is this issue related to a specific component?**
Masthead L0

**What did you expect to happen? What happened instead? What would you like to see changed?**

As per design specs, the blue underline should fill the same with as the background hover fill. Example:
<img width="428" alt="Screen Shot 2020-09-10 at 2 56 17 PM" src="https://user-images.githubusercontent.com/53093550/92786047-eb24c480-f375-11ea-96a4-83e513534a28.png">

In Storybook, when I hover or select other L0 menu items there is a visible gap appearing between the two states:
<img width="1117" alt="Screen Shot 2020-09-10 at 1 35 27 PM" src="https://user-images.githubusercontent.com/53093550/92786477-45be2080-f376-11ea-9ac3-e72e44213369.png">

**What browser are you working in?**
Chrome

## Steps to reproduce the issue

1. Open canary version of masthead https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--default
2. Hover on the active L0 item to show the background hover state at the same time.

**Comment by motou** [comment]
![Screen Shot 2020-10-02 at 12 43 29](https://user-images.githubusercontent.com/1215956/94915318-f9fe2300-04ac-11eb-9f50-101fa80b7022.png)

This issue comes from the 2px wide transparent borders. Is there any reason that there is the 4px space between menu items?

**Comment by annawen1** [comment]
Hi @motou Thanks for taking a look at this! The reason why we have the 2px transparent borders is because in the `active` state, the border colors change from transparent to the blue.

<img width="1017" alt="Screen Shot 2020-10-06 at 3 25 10 PM" src="https://user-images.githubusercontent.com/54281166/95250565-48caf600-07e8-11eb-80fe-d271b2e20b7e.png">

**Comment by motou** [comment]
Okay, then the bug comes from transparent borders. They should have zero width or be set as none. I can raise a PR to fix it

**Comment by RobertaJHahn** [comment]
@motou If you create a PR with the fix, could you link it to this issue, please.  Thank you.

**Comment by ariellalgilmore** [comment]
@annawen1 fixed this ![Screen Shot 2020-11-25 at 9.43.12 AM.png](https://images.zenhubusercontent.com/5ee7ae1cc40147132b286905/f73f80a3-c181-4229-9cfa-ea0c9d3be7e0)
