### ISSUE TITLE
Masthead L0 active link: selected menu item knob not working in a new tab

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/carbon-for-ibm-dotcom#3912]
## Detailed description

**Describe in detail the issue you're having.**
**In Storybook,** when I change the `selected menu item` knob, the update renders correctly in the same view but if I open the page in a new tab the active state is missing.

<img width="1665" alt="Screen Shot 2020-09-10 at 3 01 31 PM" src="https://user-images.githubusercontent.com/53093550/92787325-fcba9c00-f376-11ea-8163-05488190b883.png">

**Is this a feature request (new component, new icon), a bug, or a general issue?**
This could be Storybook issue, not sure.

**Is this issue related to a specific component?**
Masthead L0

**What did you expect to happen? What happened instead? What would you like to see changed?**
In this example, I expected to see a blue underline below `Products & Solutions` when I opened the page in a new tab.

**What browser are you working in?**
Chrome

## Steps to reproduce the issue

1. Open the masthead here: https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--default
2. Change the `selected menu item` knob at the bottom of add-ons panel to reflect one of the L0 menu items
3. Once you see the update, click on the 'open canvas in new tab' icon in the top right of Storybook

**Comment by annawen1** [comment]
Yep this is a storybook issue, specifically with special characters like `&`. If you try changing the `selected menu item` knob to a menu item that does not contain `&` (ie. Explore more) and then open a new tab, the blue underline will appear correctly.

**Comment by asudoh** [comment]
Refs storybookjs/storybook#11641.

**Comment by ariellalgilmore** [comment]
As @asudoh comment references, this has been fixed and can be closed now.
