### ISSUE TITLE
React: Create / Change ?component name? (behind feature flag) template

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#3925]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `?component name?`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- **See the Epic (#TBD ) for the Design and Functional specs information**
- Prod QA testing issue (TBD)
- Feature flag documentation: https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/react/docs/feature-flags.md

#### Acceptance criteria
- [ ] Built as a pure React component/variant
- [ ] Build behind a feature flag
- [ ] Include README for the react component and corresponding styles
- [ ] Add any necessary stable selectors
- [ ] A comment is posted in the Prod QA issue, tagging Praveen, when development is finished

**Comment by RobertaJHahn** [comment]
Will be moving away from support of Pure React components.  Closing this epic and all linked issues.
