### ISSUE TITLE
[Contact module] Web Components: Contact module - embedded

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#3927]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create the `Contact module - embedded`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Prod QA testing issue (#3953)
- Add the service to the services package

<img width="1583" alt="Screen Shot 2020-09-11 at 5 13 33 PM" src="https://user-images.githubusercontent.com/1641214/92973408-24326700-f452-11ea-8190-5d823cf16df7.png">

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] Update the e2e test scripts, if needed. 
- [ ] Confirm e2e test results have no major errors.
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by guilhermelMoraes** [comment]
As discussed on 11/05/2020 during the squad stand up, we'll move this component to the ice-box. The contact module is available for the [Products](https://www.ibm.com/testing/products/) and [Support](https://www.ibm.com/testing/support/) pages, both used for A/B testing. 
Here are a few useful links: 
 - [Products landing page visual specs (includes the contact module)](https://app.abstract.com/projects/dc3a681e-de39-4658-89e1-c507dc505fd2/branches/master/collections/831cfc48-d959-448f-a6c8-ddcd100b8ce3);
 - [Products landing page (contact module code)](https://github.ibm.com/ibm-com-reboot/products-page/blob/master/components/how-can-we-help.js);
 - [Support landing page visual specs (includes the contact module)](https://app.abstract.com/projects/a9777162-2e91-4b05-a55f-1f6580d62cba/branches/master/collections/030ccb56-82cb-483e-8b3a-74e7c0b31550);
 - [Support landing page (contact module code)](https://github.ibm.com/ibm-com-reboot/support-page/blob/master/components/contact-us.js).

CC: @RobertaJHahn @jeffchew
