### ISSUE TITLE
React: Lead space - with search (behind feature flag)

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#3929]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create the `Lead space - with search`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- **See the Epic for the Design and Functional specs information**
- Prod QA testing issue (#3954)
- Feature flag documentation: https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/react/docs/feature-flags.md
- Redirect url should be a prop that can be configured, the query should be appended as a query param to the defined redirect url before redirecting

<img width="1583" alt="Screen Shot 2020-09-11 at 5 10 15 PM" src="https://user-images.githubusercontent.com/1641214/92973227-b5550e00-f451-11ea-9da5-4b802a9596f6.png">

#### Acceptance criteria
- [ ] Built as a pure React component/variant
- [ ] Build behind a feature flag
- [ ] Include README for the react component and corresponding styles
- [ ] Add any necessary stable selectors
- [ ] A comment is posted in the Prod QA issue, tagging Praveen, when development is finished

**Comment by guilhermelMoraes** [comment]
@jeffchew how should we proceed regarding the search input? For the Support L0 page, we've decided only to pass the search term as a query parameter to  https://www.ibm.com/support/home/search-results. 
Also, the buttons here are neither following design nor behavior from `ButtonGroup`.

**Comment by jeffchew** [comment]
There's two possibilities for the search input:

1) Configurable redirect url, which will append the query param for the search query
2) Custom callback that will provide the query into the custom method

The buttons I'm wondering if we should work with design to make it compliant with the buttongroup?

**Comment by guilhermelMoraes** [comment]
@jeffchew there are any problems if we follow with both? The 1st one looks simpler - which is good, could cover a few use cases. The 2nd one could be used in more specific ways, maybe. 

For the buttons, I think we can discuss it with the design team as well. What do you think?

**Comment by jeffchew** [comment]
@guilhermelMoraes I don't see a problem with both, we can have 1 be the default behavior, and if 2 is defined, that will be used instead.

**Comment by guilhermelMoraes** [comment]
@jeffchew okay, cool! Search input resolved! What about the buttons?

**Comment by jeffchew** [comment]
@guilhermelMoraes can we rope in @wonilsuhibm @oliviaflory @larahanlon2 @jacobottesen-dgc @JennySanchez

**Comment by shixiedesign** [comment]
Hi! Here are latest specs on Leadspace with Search. Please note that we decided to not allow CTA buttons in the leadspace when Search is present, and content will always be centered on lg breakpoint and up. 
For design & spec (Abstract collection link): https://share.goabstract.com/c2c6f203-2172-4bc3-b406-8783d54ad81d

Example design at xlg: 
![image](https://user-images.githubusercontent.com/15144993/96599643-217f2900-12be-11eb-8725-3fb2b2819224.png)

Example spec: 
![image](https://user-images.githubusercontent.com/15144993/96599569-11674980-12be-11eb-804d-82c333cd7873.png)

**Comment by mfearer94** [comment]
@jeffchew @RobertaJHahn I was working on the content model for this component and wanted to see if this matched what you are working on? Thanks
### Content Model
**Headline** (Required) - Simple Text
**Sub-Headline** (Optional) - Simple Text
**Desktop Placeholder Text** (Optional) - Simple Text defaulted as "Search"
**Mobile Placeholder Text** (Optional) - Simple Text defaults to whatever Desktop is if not provided
**Typeahead (Required)** - Boolean with True = Typeahead provided, False = No Typeahead (Default)
### Optional Considerations
**Inverse (Required)** - Boolean with True = Inverse, False = Not Inverse (Default)
**Image (Optional)** - Matches aspect ratios and dimensions of current leadspace component

**Comment by RobertaJHahn** [comment]
@guilhermelMoraes I am moving this issue to sprint 20-22 as it appears the PR is not merged.  Could you also take a look at the comment from mfearer94 above.  Thanks.

**Comment by guilhermelMoraes** [comment]
@mfearer94 would you please provide more details about it? The visual specs provided by Shixie to me on Abstract do not refer to an Image either Inverse theme. Also, it would be good to have more details on this typeahead feature. 

FYI @jeffchew

**Comment by shixiedesign** [comment]
Hey @guilhermelMoraes typeahead doesn't have spec yet and the optional items Michael listed may be a future feature request. Seems like this item is moved to next sprint? Please coordinate with @lily-kenney Lila and Charlie if this needs to be added to my sprint.

**Comment by mfearer94** [comment]
@guilhermelMoraes @jeffchew Sure thing. Shixie answered the question about image and inverse pretty well. I added those in as they are a part of current leadspace components. I added them in as future considerations as it might help to have those in consideration while developing this component. 

When it comes to typeahead, you can see it currently on the support site: https://www.ibm.com/support/home/?lnk=hpmls_busu
It's essentially allowing for a dropdown with potential search terms being populated. For a search field that is front and center, it is likely that typeahead will be involved, but is not required as there is a dependency on the search platform utilized.

Please let me know if you have any other questions.
