### ISSUE TITLE
Component: Promo banner (behind a feature flag) - limited scope Prod QA testing 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#3952]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `Promo banner`

> I need to:
have an early version of the pattern or component that has been tested for Tier 1 browsers and platforms

> so that I can:
use the pattern on an ibm.com web page or in a cms template to gather design metrics to validate or change the existing design

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1 and 13.3
- Browsers to be tested:  **Desktop:** Chrome, Firefox, Safari, Edge, **Mobile:** Chrome and Safari  **Tablet:** Chrome and Safari
- [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- **See the Epic for the Design specs information.  Functional specs are not created for patterns behind a feature flag**
- Dev issue (#3928) 
- ** If Web Components, once development is finished, the updated code is available on the [Experimental URL](https://ibmdotcom-web-components-experimental.mybluemix.net/?path=/story/overview-getting-started--page) for testing.**
- ** If React, once development is finished, the updated code is available on the [Experimental URL](https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/overview-getting-started--page) for testing.**

#### Acceptance criteria
- [ ] All Tier 1 browser versions are tested
- [ ] All Tier 1 operating systems are tested
- [ ] All Tier 1 devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by guilhermelMoraes** [comment]
@Praveen-sr the development is finished! Can you please test the new pattern `PromoBanner`? 
Here's the [link to the deploy preview](https://ibmdotcom-react-experimental.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/3944/index.html?path=/story/components-promobanner--default), with the latest changes incorporated.
Here are the [visual specs](https://share.goabstract.com/3316d1ab-421e-487c-a624-9e5eb655ec9d?collectionLayerId=dd10dfb7-71be-4c98-9562-73c151d3236b&mode=design). 
Here's the [pull request](https://github.com/carbon-design-system/ibm-dotcom-library/pull/3944) with all the changes.

Please, tell me if you need anything else for testing.  Thank you!

**Comment by RobertaJHahn** [comment]
@guilhermelMoraes Praveen does not have access to the visual specs link included in your Sept 15, 2020 message above.  Could you create a pdf and post a new link.  Thanks.

**Comment by shixiedesign** [comment]
Abstract link was broken so here's the updated one: 
https://share.goabstract.com/e8e37d87-13f0-4f62-8aef-cc5e29fb602f?collectionLayerId=31ed9e9e-7362-4727-be79-621b19cfb54b&mode=design
PDF: 
[redhat-band-specs.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/5532912/redhat-band-specs.pdf)

**Comment by Praveen-sr** [comment]
@shixiedesign Thank you!

**Comment by RobertaJHahn** [comment]
Team decided that Prod QA testing will not be done on components that are available behind the feature flag.  Closing
