### ISSUE TITLE
Add cache busting logic for TranslationAPI and LocaleAPI

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#3959]
#### User Story

> As a `[user role below]`:
IBM.com User

> I need to:
be sure I have the latest version of the IBM.com Masthead/Footer navigation information

> so that I can:
always have the latest navigation data during my IBM.com browsing experience

#### Additional information

 - The TranslationAPI stashes the data into sessionStorage and serves up from there. Currently, there is no cache clearing policy in place, and assumes it will be refreshed when the browser is restarted.
 - A timestamp can probably be set and added to the saved object in sessionStorage, then compare that to current time
 - Decision is to expire the sessionStorage after 2 hours

#### Acceptance criteria
 - [ ] Adding cache clearing logic to the TranslationAPI and LocaleAPI

**Comment by IgnacioBecerra** [comment]
I'll be splitting this into two PRs, one for Translation and another for Locale.
