### ISSUE TITLE
Investigate the implementation of the expressive theme with carbon-web-components

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#3982]
#### User Story

> As a `[user role below]`:
Carbon Web Components adopter

> I need to:
apply the expressive theme to Carbon

> so that I can:
have my application not be productive themed with Carbon

#### Additional information

 - Current implementation for React: https://carbon-expressive.mybluemix.net
 - Might be overthinking it, but we would need to think of how the expressive theme is applied since styles are set in the shadowDOM
- We might want to activate percy.io but this can be done in a separate issue. We already have an issue for activating percy on `carbon-web-components`, which we have deferred for now.

#### Acceptance criteria
 - [ ] Create an expressive theme storybook for `carbon-web-components`
 - [ ] Any documentation necessary for adopters to implement

**Comment by RobertaJHahn** [comment]
This work should be scheduled after Carbon Core Expressive components are released.  The updates will be needed to upstream Carbon web components.

**Comment by shixiedesign** [comment]
Since upgrading Carbon 10.35 is done, the Core expressive components are out and available. This issue can be triaged again.

**Comment by RobertaJHahn** [comment]
5/18 Team Huddle agenda

**Comment by RobertaJHahn** [comment]
**May 18, 2021 Meeting notes:**  
Carbon expressive components:  Carbon for ibm.com implementation planning (Jeff & Shixie) 

- Issue 3982 

- Epic: 5944 Expressive theme removal

High level dev tasks:

- Create feature branch to stage the work (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6121)

- add deprecation notice when an adopter uses the theme

- Remove the theme as an import in Carbon for IBM.com (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6122)

- Identify components where styles need to be updated to use the proper tokens, as well as using the expressive versions of upstream Carbon components

- Update carbon-web-components to make use of the expressive moments new in Carbon core (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/3982)

- Remove expressive specific components in Carbon for IBM.com web components and use the upstream expressive components

**Comment by jeffchew** [comment]
@RobertaJHahn let's add to the next refinement meeting for sizing.
