### ISSUE TITLE
Table of contents: TOC selection bar does not stick to top of the page.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#3989]
## Detailed description

On Mobile & tabs

On react-staging, NextJS pages

Issue: Table of contents, selection bar does not stick to top of the page.

## Additional information

![TOC.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/995ef856-f9e3-4ae1-8782-d1ad27906d52)

**Comment by ariellalgilmore** [comment]
This looks like a duplicate and @kennylam closed it in this [issue](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/4334)
