### ISSUE TITLE
Mega menu: Change the design specs to wrap menu content when longer than the mobile or medium breakpoint

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4001]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the updated `Mega menu` design specs

> so that I can:
correctly change the  `Mega menu` component 

#### Additional Information
-  **See epic for feature request details**

#### Acceptance Criteria
- [x] A Sketch file is created or updated with the `Mega menu` design and specs
- [x] The design specs and pdf version are added to the `Mega menu` Box folder 
- [x] Update the Agile Board epic with the spec link

**Comment by oliviaflory** [comment]
Link to mega menu spec folder: https://ibm.ent.box.com/folder/118692148518
Note: page 6 and 7 show examples of text wrap

**Comment by oliviaflory** [comment]
not stale

**Comment by oliviaflory** [comment]
specs are in the epic issue
