### ISSUE TITLE
[Masthead] Left-nav - Wrap menu content when longer than the mobile or medium breakpoint - DDS Consulting

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4003]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
change the `left-nav`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic #3518 for the Design and Functional specs information**
- Visual QA testing issue (#4004 )
- Prod QA testing issue (#4005 )

----
- Hybrid Cloud developer: @andy-blum 
- HC Jira ticket: https://jsw.ibm.com/browse/HC-2167
- Engineering estimate:  5
- DDS consultant:   Andrew Wang

----

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json)
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Design QA issue, tagging Designer, when development is finished
- [ ] The Storybook link is added to the Design QA issue for their testing
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by proeung** [comment]
@RobertaJHahn Can you let me know the DDS engineer consultant who will be helping us out with this feature request?

**Comment by annawen1** [comment]
seems to be the same ticket as this one: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4000

**Comment by RobertaJHahn** [comment]
@proeung Andrew Wang has picked up this issue.

cc:  @emyarod
