### ISSUE TITLE
Web Component: Masthead menu text wrap enhancement Visual QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4004]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Mega menu`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- Web component dev issue (#4003)

 #### Tasks
Ensure the `Mega menu` component has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by RobertaJHahn** [comment]
Design documentation complete.. Moving this dev issue into dev backlog.

**Comment by RobertaJHahn** [comment]
Closing as this web site content update is not needed.  The text wrap happens automatically when the users are using their mobile devices.

**Comment by shixiedesign** [comment]
Moving out since React fix is not done yet.
