### ISSUE TITLE
Adding a Hotjar heatmap triggers to each of mega menu tabs -- ibm.com Reboot project

### ISSUE THREAD

**Issue by olchowo** [carbon-design-system/carbon-for-ibm-dotcom#4006]
### The problem
Since August 31st ibm.com/us-en users have an opportunity to use new Carbon mega menu. We would like to use Hotjar heatmaps to learn, how the users are interacting with this new design. 
Those insights are important for further iterations of the mega menu and for work on other elements of overall IBM web navigational system, conducted by design team. 
Heatmaps are part of ongoing user research & Hotjar is the easiest to use tool that can generate them. Those heatmaps will be very valuable for us, so thank you in advance for your help on this matter.

### The solution
US homepage already have a Hotjar widget that allows us to map the user behaviour. Dynamic page elements though, like overlays, in this case: mega menu tabs, require a special JS trigger to be recognized and mapped by the tool. 
Please add following piece of code to JS function opening each of tabs:

for Products&Solutions tab: hj('trigger', 'MM_products-solutions');
for Services&Consulting tab: hj('trigger', 'MM_services-consulting');
for Learn&Support tab: hj('trigger', 'MM_learn-support');
for Explore more tab: hj('trigger', 'MM_explore-more');

When the code is deployed I will be able to set separate Hotjar heatmaps using each of those triggers. 

We've discussed this request with Anna Wen and Jeff Chew & they found a way to convert this into piece of code reusable for future purposes. Please check the chat transcript attached to this ticket.

### Additional information
 - Hotjar documentation page related to that request: https://help.hotjar.com/hc/en-us/articles/115011867948-How-to-Use-JavaScript-to-Trigger-Heatmaps
 - chat transcript:
[reboot-MM_hotjar__chat-transcript-18sep2020.txt](https://github.com/carbon-design-system/ibm-dotcom-library/files/5247293/reboot-MM_hotjar__chat-transcript-18sep2020.txt)
 - Thank you :)

**Comment by RobertaJHahn** [comment]
@annawen1 @jeffchew Can you add additional details to this issue?  Thanks.
