### ISSUE TITLE
Component: Review / Update Masthead L1 design specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4013]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the `Masthead L1` design specs

> so that I can:
correctly change the `Masthead L1` component 

#### Additional Information
- The developers will be removing the white background version of the Masthead L1 from behind the feature flag.  The designs should be up to date for their work.
- This will be a "lift & shift" of the v18 Masthead
 - The documentation should be specific to the white background MH version included in the [Support Page].  This issue is to create a proper version of the white theme design specs.  
- [Masthead L1 Agile epic link](#4007)
- [Masthead L1 Box folder](https://ibm.ent.box.com/folder/118448193520)
- [Sample Support test page](https://www.ibm.com/testing/support/)

#### Acceptance Criteria
- [x] A Sketch file is updated with the `Masthead L1` design and specs
- [x] The design specs and pdf version are added to the Box folder 
- [x] Add Box folder link to the website content if it exists

**Comment by oliviaflory** [comment]
WIP files uploaded to Box for review

**Comment by oliviaflory** [comment]
## Review notes and questions

### Design decisions
Wonil & Olivia reviewed
1. Update dropdown width to 360px and allow for text wrap within the dropdown
2. Ecosystem indicator should be optionally clickable/selectable in case there is a scenario where the first page is "overview" within the L1
3. Talk to dev team about including selected state for dropdown and items within a dropdown, see example of the scenario within the [Analytics page](https://www.ibm.com/analytics/services) if you select `Services` dropdown and `Data and AI Expert labs` the L1 labels do not change and the dropdown does not currently indicate where the user is.

### Questions after functional review
James and Olivia reviewed

4. We stated `If there is an L1 the L0 should be blank`. James asked: _Do we want to enforce this or have it be a guideline?_ 
I wonder if this is something we should confirm with the Reboot team, maybe loop in Keegan? My guess would be we want to enforce this based on the 'normalization' work happening within the IA, but what happens to someone like Cloud who has their own configuration of L1?

5. Follow up to design decision 3 above, James asked: _Should selected dropdown be programatic or set by the adopter?_

6. _On tablet and mobile should the L0 hide when the user scrolls down, and appear again when the user scrolls up?_ 
IMO, yes, this would follow the same behavior as defined for desktop. It would also save _some_ screen area for mobile, and allows quick access for the L0 if you scroll up a bit. Follow on question: _does this work ok with sticky TOC on Mobile?_ 


cc @wonilsuhibm @photodow

**Comment by wonilsuhibm** [comment]
@oliviaflory @photodow Thank you for the comments. Let me try:

4. It should've enforced. That's part of the navigation normalization effort.

5. Going back to the rationale behind number 4, I'd say do it programmatically. So to be clear, if a sub-item is selected on the dropdown, the parent should automatically be selected. Correct?

6. Yes, L0 hides.
