### ISSUE TITLE
Do not overlap the platform label

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon-for-ibm-dotcom#4023]
When having no menu in the masthead, but a simple project label only,
we would like the search box not to overlap the project link. 
![image](https://user-images.githubusercontent.com/15310250/93894680-48623380-fcef-11ea-8ab2-5c2079ed6c7c.png)
![image](https://user-images.githubusercontent.com/15310250/93894696-4d26e780-fcef-11ea-87db-43d62d25b617.png)
so basically the search box would stretch only up to the end of the "Documentation"

#### Additional Information
- **We committed to provide this fix in the December release to KC.**

**Comment by RobertaJHahn** [comment]
Jenny will include this issue in the Oct 2, 2020 design meeting.

**Comment by JennySanchez** [comment]
@RobertaJHahn Shared the issue detail with the designers, overall we recognize this is a bug but not a feature request. We suggest to covert this issue for the bug fix.

**Comment by larahanlon2** [comment]
@RobertaJHahn @wonilsuhibm @JennySanchez confirming as per L0 design spec:

<img width="1340" alt="Screen Shot 2020-10-02 at 4 20 28 PM" src="https://user-images.githubusercontent.com/53093550/94966441-40627a80-04cb-11eb-9034-3a513732e372.png">
