### ISSUE TITLE
Arabic page UI is not mirrored for RTL

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/carbon-for-ibm-dotcom#4026]
[Title]: When observing the page with browser language preference = Arabic, page is not mirrored for RTL

> Describe in detail the issue you're having.
Page should display as mirror to LTR

> Is this a feature request (new component, new icon), a bug, or a general
> issue? Bug

> Is this issue related to a specific component?
Happening on Masthead and Footer at a minimum

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Mirror image

> What browser are you working in?
Chrome latest

> What version of the IBM.com Library are you using? v1.10.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one: https://myibm.ibm.com/profile/dataprivacypreferences/welcome/sa-ar
2. Step two: look at MH and Footer; not mirror image to the English page

![Uploading FireShot Capture 037 - IBM Privacy Preference Center - myibm.ibm.com.png…]()

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment]
@ljcarot I think you were going to review this issue and possibly close.

**Comment by ljcarot** [comment]
It is still a bug

**Comment by RobertaJHahn** [comment]
There are 2 privacy teams.  

This page created by the Privacy Portal team appears to be working.  https://www.ibm.com/privacy/portal/ae-ar

**Comment by RobertaJHahn** [comment]
NextJS environment with RTL enabled:  http://ibmdotcom-nextjs-rtl.mybluemix.net/

**Comment by RobertaJHahn** [comment]
Next step to provide an RTL version of the styles kitchen sink.

**Comment by RobertaJHahn** [comment]
@yellowdragonfly Please see the comments included on this issue.

**Comment by RobertaJHahn** [comment]
Closing as this is a dup of issue (#3984)
