### ISSUE TITLE
Web component: Link list - On mobile, its not stretched to ends of the page.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4027]
## Detailed description

Issue: Link list - On mobile, default and End of sections are not stretched to full page.

Note: On react, its working fine.

## Additional information

Actual:
![Image from iOS.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/6f2621e6-eeef-455f-bef6-b8949f868b75)

Expected:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/dbda0a47-b719-49bc-98bf-ef0ce5578727)

**Comment by asudoh** [comment]
Here's what I see in React storybook, not sure if the behavior, especially with the wider width, is something we should mirror to Web Components. Any thoughts...? Thanks! CC @oliviaflory @JennySanchez @RaphaelAmadeu 

![linklist-responsive-padding](https://user-images.githubusercontent.com/1259051/94703767-2b2a0680-037a-11eb-891a-f15eada7ac9a.gif)

**Comment by asudoh** [comment]
#4379 addresses this issue.
