### ISSUE TITLE
Web component: Link list - External and Video options are not available on web components 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4028]
## Detailed description

Issue: Storybook issue - 
1. External and Video options are not available on web components 
2. On knobs - icon placements not available.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/13b5f59c-5668-4a4c-b554-80d1142eda4b)

**Comment by asudoh** [comment]
CTA code needs some change to work with link list (and thus it's not a bug in link list itself), and I'm looking at it.
