### ISSUE TITLE
Web Components:  Provide Fluid Form training to the DDS engineers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4032]
#### User Story

> As a `[user role below]`:
DDS engineer with the Fluid Form expertise

> I need to:
train my DDS team members in this skill

> so that I can:
share my knowledge and support Agile processes

#### Additional information

 - Engineers to be trained:  Andy, Anna, Ariella, Gui, Ignacio, Kenny and Raph

#### Acceptance criteria
 - [ ] training meetings are conducted
 - [ ] follow-up support is provided as the engineers work on their Fluid Form development assignments

**Comment by RobertaJHahn** [comment]
@asudoh If you could assign story points, that would be great.

**Comment by asudoh** [comment]
@RobertaJHahn Done!
