### ISSUE TITLE
Component: Create Mobile landscape mode alert design specs 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4039]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the `Landscape mode alert` design specs

> so that I can:
correctly create the `mobile landscape mode alert` component 

#### Additional Information
- [mobile landscape mode alert Ideation issue #152 link](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/152)
- **This work is dependent on the Ideation work.**

#### Acceptance Criteria
- [ ] A Sketch file is created or updated with the `mobile landscape mode alert` design and specs
- [ ] Create a Box folder for the `mobile landscape mode alert` (if not already there)
- [ ] The design specs and pdf version are added to the Box folder 
- [ ] Update the Ideation Board epic with the specs link
- [ ] Update the Agile Board epic with the spec link
- [ ] Add Box folder link to the website content if it exists

**Comment by oliviaflory** [comment]
@jacobottesen-dgc I'm not able to see the sketch file, could you update the link for the designs?

**Comment by jacobottesen-dgc** [comment]
@oliviaflory the link should work now

**Comment by RobertaJHahn** [comment]
Moving this issue to Backlog, based on discussions in the Oct 22, 2020 Ideation Planning meeting.

**Comment by RobertaJHahn** [comment]
Closing.  This work is no longer needed.
