### ISSUE TITLE
Web component: Card group - on mobile & tab cards are not stretched to full page.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4043]
## Detailed description

Issue: On mobile & tab cards are not stretched to ends of screen size.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/7f05e7b5-eae4-4fbe-8fe5-162b3b5025e8)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/077ccdbf-05d9-48ba-9872-9ec4eb126795)

**Comment by asudoh** [comment]
#4379 seems to address this issue.
