### ISSUE TITLE
Component: Create Carousel MVP design specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4051]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the `Carousel` design specs

> so that I can:
correctly create the `Carousel` component 

#### Additional Information
- [Carousel Ideation epic 124 link](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/124)
-  Carousel Agile epic (#630)
- This MVP design does includes the cards, 2 buttons and the pageination.   User testing is being conducted for the additional concepts. 

#### Acceptance Criteria
- [x] A Sketch file is created or updated with the `Carousel` design and specs
- [x] Create a Box folder for the `Carousel` (if not already there)
- [x] The design specs and pdf version are added to the Box folder 
- [x] Update the Ideation Board epic with the specs link
- [x] Update the Agile Board epic with the spec link
- [ ] Add Box folder link to the website content if it exists

**Comment by RobertaJHahn** [comment]
Jacob will be performing user testing to provide input to the designs.

**Comment by jacobottesen-dgc** [comment]
During the carousel sync up meeting with Olivia, James and I we came up with these next steps:

- Update carousel control icons from chevron to caret 
- Update user test to be A/B testing showing to options. A. Slider bar with caret icon controls with numbers in the middle. B. Add the pagination component from Carbon expressive as controls 
- Meet with accessibility to discuss tabbing options 
- Try building prototype with tabbing in XD

cc. @wonilsuhibm

**Comment by jacobottesen-dgc** [comment]
Design specs for (MVP) Carousel component are completed and can be viewed below: 

PDF file:
https://ibm.box.com/s/1aj7r0y9j73lvauv6dqtt73d2b6kma6v

Sketch file:
https://ibm.box.com/s/dr4mko4st4q0fv0ezm6my2jqkblfzdkn
