### ISSUE TITLE
Web component: Feature card medium - the focus is going out of the card.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4054]
## Detailed description

Issue: The focus is going out of the card while user clicks on it and while navigating using keyboard.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/4e133767-dd60-4455-aac0-c3e626633f94)

**Comment by jeffchew** [comment]
The `:host` styles should remove the outline.

**Comment by IgnacioBecerra** [comment]
I think this issue may have already been fixed? Not seeing the bug anymore.

**Comment by asudoh** [comment]
Going to Elements tab in Chrome DevTools, right-clicking on `<dds-feature-card-block-medium-card>` and select Force state - `:focus` seems to show an unpleasant border. However, we are considering the removal of `<dds-feature-card-block-medium-card>` itself (#4125) and thus probably we can take a look at this after we address #4125 unless we have a pressing need to fix this.

**Comment by IgnacioBecerra** [comment]
The focused border is different than pictured, but still not what it should be. Thanks for the heads up, Akira, I'll wait until we decide what to do with the medium card in general.

**Comment by kennylam** [comment]
This has been resolved in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4318.

**Comment by RobertaJHahn** [comment]
Closing based on Kenny's comments above.
