### ISSUE TITLE
Web component: Feature card medium - arrow icon on the card is placed on wrong direction. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4055]
## Detailed description

On Mobile and Tab view

Issue: The arrow icon is placed on the wrong side of the card. 
No as per specs.

Note: working fine on react 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/0cb30cbe-3b21-4469-9fce-d3dace887c75)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/ea2888cf-60d5-455b-8331-e6d02835a2f4)

**Comment by asudoh** [comment]
@Praveen-sr Is this still reproducible? Thanks!

![image](https://user-images.githubusercontent.com/1259051/97952244-093ffb80-1de0-11eb-92be-9c61748c725f.png)

**Comment by Praveen-sr** [comment]
@asudoh Yes, the issue still exists on Mobile and Tab.

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/9b6f53cd-bafe-4297-bd29-fa6eb65bbe3c)
