### ISSUE TITLE
Web component: Link List - The link text "Learn more" is not descriptive. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4058]
## Detailed description

Issue: 
The link text "Learn more" is not descriptive. Hence the user does not know the purpose of these links. 

Note: Same issue on react version 

Expected: Provide a descriptive link text. for example: "learn more about XYZ". or some dummy text.

**Comment by kennylam** [comment]
@Praveen-sr Storybook text links are, for the most part, dummy links and placeholders. Unless there is a specific reason highlighting functionality or best practices, this is not real content. I'm going to fix but I don't think issues such as this need to be reported.
