### ISSUE TITLE
On opening and closing megamenu tabs on the Home Page, the category headings (Partners, IBM Research, About IBM, COVID 19) are jumping left/Right

### ISSUE THREAD

**Issue by alainmachu** [carbon-design-system/carbon-for-ibm-dotcom#4067]
On opening and closing megamenu tab Explore More on the Home Page, the category headings (Partners, IBM Research, About IBM, COVID 19) are jumping left/Right

See recording: https://ibm.webex.com/ibm/ldr.php?RCID=c3be4bf243f946228b5623b9070b6edc
Password; YbcGEPR2

> This is a bug

> What browser are you working in? 
Google Chrome is up to date
Version 85.0.4183.121 (Official Build) (64-bit)

## Steps to reproduce the issue

1. Load IBM.com
2. Open tab Explore More
3. Close tab Explore More
4. See the headers jumping left/right

#### Additional Information
- Megamenu shifting left and right when opening/closing might be due to the scrollbar disappearing and reappearing - this is probably more noticeable in windows machines because of the way they display scrollbars. We disable the page scroll when the megamenu is open which makes the scroll bar disappear. Then when you close the megamenu the scrollbar reappears again causing the page content to shift 
- Should be checked across the browsers.  
- Possible solution to investigate:  turn off overflow

**Comment by kennylam** [comment]
Duplicated of #3865
