### ISSUE TITLE
Web Components: On Masthead - search keyword is not retained

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4072]
## Detailed description

React: On Masthead - user enters a keyword and clicks outside (any place on the page), search bar closes and when user again opens it, keyword is retained.

On Web components, this is not retaining the keyword.  Web Components should behave the same as the React version.

## Additional information

![Search_react.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/66f19b4f-f92a-4a47-bd86-86d9331a0a04)

Web components:
![Search_web.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b2a2789f-c924-4615-8752-3e99723ea834)

**Comment by RobertaJHahn** [comment]
Scheduled meeting to discuss design decision Thursday, Oct 8.

**Comment by RobertaJHahn** [comment]
Decision was made to have the web components version behave the same as the react version.  Issue description has been updated to reflect this decision.  Moved to sprint 20-21, release v1.13.0.
