### ISSUE TITLE
React: Masthead - On tab, user clicks on profile and then on search icon, the focus remains on profile icon.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4073]
## Detailed description

On tab - iOS 12, 13, and 14

Issue: User clicks on profile and then on search icon, the focus remains on profile icon.
User has to click on the search field again to enter keyword.

## Additional information

![Search_focus.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/7706fafd-d025-44ce-b2b5-2847fbc8f6bd)

**Comment by kennylam** [comment]
@RobertaJHahn @Praveen-sr Just tested this on an iPad and cannot reproduce on any of our environments. It might have been inadvertently fixed since this issue was opened. Suggest closing.

**Comment by RobertaJHahn** [comment]
Closing based on Kenny's comments above.
