### ISSUE TITLE
React: On Masthead - search bar, enter keyword and delete it by mouse select, search bar closes

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4074]
## Detailed description

Issue: On Masthead - search bar, enter keyword and delete it by mouse select, search bar closes

## Additional information

![Search_del.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/c4bb143e-0cb9-464c-9f36-19b6d1066224)

**Comment by mcastre** [comment]
@RobertaJHahn Hi! Id like to work on this issue.

**Comment by jeffchew** [comment]
@mcastre thank you for participating in `Hacktoberfest`! Looking forward to seeing your PR and feel free to reach out in slack with any questions!

**Comment by mcastre** [comment]
@jeffchew PR has been opened. https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4221

**Comment by jeffchew** [comment]
> @jeffchew PR has been opened. #4221

Thank you, our team will review this! Want to also quickly check, are you an IBMer?

**Comment by mcastre** [comment]
@jeffchew not exactly sure what you mean by an IBMer

**Comment by jeffchew** [comment]
> @jeffchew not exactly sure what you mean by an IBMer

Sounds like you're not then! Would you be able to fill out the following CLA (contributor license agreement):

[Carbon for IBM.com CLA individual.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/5378291/Carbon.for.IBM.com.CLA.individual.pdf)

Can you also e-mail to digdes@us.ibm.com in additional to mailing to us?

We will start reviewing this PR, thank you again!

**Comment by mcastre** [comment]
Sure! Do you want me to fill out the pdf and email it to that email address?

**Comment by jeffchew** [comment]
Yes please, thank you!

**Comment by mcastre** [comment]
@jeffchew ok i sent the agreement to that email

**Comment by jeffchew** [comment]
@mcastre thank you, we received it! 

Our team reviewed your PR and there was some feedback, can you take a look?
