### ISSUE TITLE
Web Component:  Audio Player

### ISSUE THREAD

**Issue by tweenn** [carbon-design-system/carbon-for-ibm-dotcom#4083]
This component will be developed in both Web Components and React as a wrapper.  

-  Corresponding React epic (#5106)

### The problem

Marketing need a way to deliver podcasts and other audio files to their clients.
As Mediacenter/Kaltura is an approved source for hosting audio, we need a way to deliver the kaltura player - within an audio experience - to our clients.

### The solution

1 - We need an IDL compliant layout to build the audio player within Kaltura.
2 - This player, that is already leveraged as the video player, will automagically know based on the media-type that it is rendering an audio (or a video) - in order to render the right visualization / layout
3 - Will be consumed and made available as a component in Carbon For IBM.com

### Additional information

It would be great to have this specs take it account:
- SRT (closed caption) display capable and translatable - optional 
- Thumbnail inclusion - mandatory
- Large scrub bar - larger than a video scrub bar
- Large play/pause interface
- 1.5x, 2x playback rate options
- Current time point displayed on scrub bar
- Markered scrub timeline (1/10+) 
- This audio file will be hosted in the Kaltura application and will be implemented using the Kaltura API.
- [Northstar audio player](https://www.ibm.com/standards/web/v18/design/audio-player/)

This is how Mediacenter's player act when playing an audio-file:
https://pages.github.ibm.com/mediacenter/docs/examples/audio/

- The Kaltura API includes an event within the player that includes the media type.  Media type codes:  1 = video, 2 = image, 5 = audio, 201 = Live stream flash, 202 = Live stream windows media, 203 = Livestream real media and 204 = Livestream quicktime
- The Carbon for ibm.com calls the API to get the description etc...
- The Carbon for ibm.com has to be able to handle both a video and audio source file.  This component may need to be renamed. (possibly supporting video, audio and images)
- [Box folder with sample audio files](https://ibm.ent.box.com/s/paut8w74l9sjqzkkzbqch8vbn3byoba9)
-[Audio Player Box folder](https://ibm.box.com/s/05ndo5nsg3sonc3wyskcbkoi93lhdoor)

Test Audio files included under Partner ID:  1773841
     - [Test Audio - IBM Elevator Pitch Series EP1 - Supply Chain](https://mediacenter.ibm.com/media/Test+Audio+-+IBM+Elevator+Pitch+Series+EP1+Supply+Chain/1_gp572bda)
     - [Test Audio - IBM Elevator Pitch Series EP4 - Automation](https://mediacenter.ibm.com/media/1_6qs3nsvv)

**Comment by RobertaJHahn** [comment]
This request must go through a design study on the Ideation Board.

@tweenn  Do you know when you need this feature?

**Comment by RobertaJHahn** [comment]
There is no ETA for this feature, but has made George Hammer aware that this work is going on.  Ideation design study and final design issues are needed.  

Cory prefers an embedded vs a pop-out design.  Ideally would like to have 1.0x (default), and 1.5x and 2x visible speed options.  

Cory can provide sample audio files.

**Comment by wonilsuhibm** [comment]
Example use case from Smart talks with IBM project: https://ibm.box.com/s/gkxfo5axnbtri0gq2ef4392pmixal0sf

**Comment by tweenn** [comment]
After a meeting with Olivia Flori, Andrew Sherman, Jerry and Cory, I was supposed to add a link to a video with a caption function that show the captions bellow the video box (not on the player).

And here it is: https://video.kaltura.com/media//1_p59fv7ur
