### ISSUE TITLE
Bump up a minimum TypeScript version

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#4101]
### The problem

Currently the minimum TypeScript version `@carbon/ibmdotcom-web-components` requires is `3.7` as `carbon-web-components` does for the sake of Angular `8.0` (The TS version Angular `8.0` supports is `3.6`, but with a minimum guidance our users can use Angular `8.0` with TS `3.7`), but `10.0`, a newer LTS of Angular, has been shipped.

**Note**: This issue does _not_ affect non-TypeScript users.

### The solution

Upgrade the minimum TypeScript version we require, to `3.9`, as Angular `10.0` does.

**Comment by RobertaJHahn** [comment]
Added to the 1/6 engineering huddle meeting agenda.

**Comment by jeffchew** [comment]
The team has decided to downgrade TS to 3.7 as the task for this issue.
