### ISSUE TITLE
React & Web Components:  Research consistency issues across Storybook instances

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4108]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
understand how the container is implemented in both the React and Web Components components

> so that I can:
have a POV to determine the best approach that reduces maintenance and provides consistency across both environments

#### Additional information

 - _{{user research}}_
 - _{{user insights}}_
 - _{{user metrics}}_

#### Acceptance criteria
 - [ ] All React and Web Components components are reviewed

**Comment by asudoh** [comment]
The initial research is available at: https://ibm.biz/Bdq6cD
