### ISSUE TITLE
Pictogram cards:  design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4109]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/125211274776?s=ykv2ukr3twyfx2nrro3rn7ge4iqoz48x)

#### Acceptance Criteria
 - [ ] Visual designs and specs received from Reboot designers
- [ ]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [ ] Meetings conducted with DDS team members to review the designs

**Comment by RobertaJHahn** [comment]
Designs are still being refined.  Scheduling the func specs and design refinement work to the first sprint of 2021 and will move earlier, if needed.

**Comment by lily-kenney** [comment]
Here's the design specs link: https://ibm.box.com/s/ykv2ukr3twyfx2nrro3rn7ge4iqoz48x

**Comment by wonilsuhibm** [comment]
Thank you. 

The DDS design team will take a look. @oliviaflory @JennySanchez @jacobottesen-dgc

**Comment by RobertaJHahn** [comment]
@shixiedesign Could you provide a pdf file of the designs and post it into the Box folder.  The QA team does not have a Sketch license.  

cc:  @wonilsuhibm @lily-kenney

**Comment by RobertaJHahn** [comment]
Scheduled for design review in the Nov 20th meeting.

**Comment by RobertaJHahn** [comment]
Design meeting summary to be added by James.  More design work with Reboot needed.
