### ISSUE TITLE
Quote: Consider removing inverse attribute

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#4122]
### The problem

`<dds-quote>` has `inverse` attribute as its React counterpart has the corresponding property. However, in Carbon core, usage of `inverse` is limited to components that may be used in a components in inverse color scheme (e.g. Carbon core top navigation bar's color scheme) and there may be a case where React `<Quote>` one is merely for theme zoning.

### The solution

Clarify above question. If React `<Quote>` one is merely for theme zoning, remove `inverse` attribute from `<dds-quote>`. If `<dds-quote>` may really be used with components with inverse color scheme, rename `inverse` boolean attribute to `color-scheme` enum attribute so it's forward-compatible with color scheme addition.

**Comment by RaphaelAmadeu** [comment]
I've confirmed with @photodow and `inverse` should remais as is right now, I'll update the PR so it just fixes the inverse funcionality. 

CC: @asudoh , @RobertaJHahn
