### ISSUE TITLE
feature-card-block-medium: Render heading/card by itself

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#4125]
### The problem

`<dds-feature-card-block-medium>` has a separate component, `<dds-feature-card-block-medium-card>` for the card portion and a separate element, `<dds-feature-card-block-medium-heading>` for the heading portion. Accordion to @kennylam, the structure was [for putting the heading portion outside of the card portion](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4125#issuecomment-713820230). @asudoh mentioned offline that it can be done by overriding top-level `render()` method, for example:

```typescript
render() {
  const { _hasHeading: hasHeading, _handleSlotChange: handleSlotChange } = this;
  return html`
    <h3 ?hidden="${!hasHeading}" class="${prefix}--feature-card-block-medium__heading">
      <slot name="heading" @slotchange="${handleSlotChange}"></slot>
    </h3>
    ${super.render()}
  `;
}
```

### The solution

Use above approach, so `<feature-card-block-medium>` can render the heading/card portions by itself, instead of maintaining separate components for heading/card.

**Comment by kennylam** [comment]
Discussed with @asudoh and clarified that the heading should sit outside of the `FeatureCard`, as it should not be part of the link.

**Comment by asudoh** [comment]
Thanks @kennylam for the discussion and for adding above comment! Updated the description and created #4283 to reflect the discussion. Wondering it makes sense; Please don't hesitate to speak up otherwise - Thanks!
