### ISSUE TITLE
Web component: Content Block simple - Visual focus is there but not having sufficient contrast

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4129]
## Detailed description

Issue: Visual focus is there but not having sufficient contrast

For more information please find the below link,
https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Contrast_(Minimum)

Expected Result:
Provide thick and strong visual focus.
1. If, Visual Focus Indicator with 3 CSS px stroke then provide a sufficient contrast that is equal to 3:1. 
2. Visual focus indicator for a link that is a 1 CSS px then provide a sufficient contrast greater than 4.5:1

Note: This defect does not exist in react staging

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/069da1cd-2d19-4d6d-80ea-05107e95d3c8)

**Comment by annawen1** [comment]
@Praveen-sr can you check again? The visual focus looks pretty visible from what I'm seeing. May have been already resolved:

<img width="447" alt="Screen Shot 2020-10-19 at 5 10 49 PM" src="https://user-images.githubusercontent.com/54281166/96512198-209eb680-122e-11eb-8d65-4eca3bd3bd17.png">


https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-content-block-simple--with-aside-elements

**Comment by Praveen-sr** [comment]
@annawen1 Re checked this on Firefox and chrome browsers, 
1. In chrome it is working fine because that is the browser visual focus (inbuilt browser feature)
2. In Firefox, visual focus is there but not having sufficient contrast for "list item & consectetur adipiscing" link

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/1b958c31-6c71-43ca-b2af-ab2c4cddda92)

**Comment by asudoh** [comment]
This is caused by #4327.
