### ISSUE TITLE
Move internal link component to carbon-web-components

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#4143]
### The problem

We currently have an internal link component that works as the base for `<dds-link-with-icon>`, `<dds-card>`, etc. However, a component code, even if it's an abstract class, being in non-component directory makes it hard to implement React wrapper in future.

### The solution

Move it to `carbon-web-components` repo, given most of the code is a workaround for the lack of extensibility of `carbon-web-components`' `<bx-link>`. Or consider making it a mix-in because `<dds-logo-grid-item>` has both features of `<dds-image>` and `<bx-link>`.

**Comment by RobertaJHahn** [comment]
Right now this is not documented in Storybook or Readme's.  It is a non-public API (internal component).
