### ISSUE TITLE
Plan the Expressive Theme Design Kit communication

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4146]
#### User Story

> As a `[user role below]`:
DDS designers

> I need to:
plan for the communication of the design kit

> so that I can:
ensure designers are aware that it is available and how to use it

#### Additional information

 - write release of design kit
 - create slides for presenting at summit
 - add kits to IBM kit parent folder

#### Acceptance criteria
 - [x] Communications strategy decision made

**Comment by oliviaflory** [comment]
Release published on the design kit repo: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-design-kit/releases/tag/Expressive-v1.0.0
