### ISSUE TITLE
Include animation in the Masthead L1 overflow feature

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4164]
### The problem
The existing behavior is jarring for the users when the overflow feature is introduced.  

### Additional information
- **Included the `sprint must have` label as this overflow feature is committed for the Nov release** 
- [IDL Motion UI reference](https://www.ibm.com/design/language/motion-ui/basics/)

**Comment by oliviaflory** [comment]
@ariellalgilmore 

Referencing the [IDL motion guidelines]() let's try: 

Standard easing: `cubic-bezier(0.2, 0, 0.38, 0.9)`
Duration token (productive): `\$transition—base` (100ms)

If it looks too fast we can try the expressive duration of `\$transition—expansion` (150ms)

Please let me know if you have questions, once we land on which duration we want to use I will add it to the [design spec file](https://ibm.ent.box.com/folder/59063660753?s=mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1) for the masthead.

**Comment by asudoh** [comment]
Just FYI, according to below files, above spec seems to translate to `transition: (propertyname) $transition--base motion(standard, productive)`:

https://github.com/carbon-design-system/carbon/blob/v10.21.0/packages/components/src/globals/scss/_motion.scss#L115-L117
https://unpkg.com/browse/carbon-components@10.21.0/scss/globals/scss/vendor/@carbon/elements/scss/motion/motion.scss
