### ISSUE TITLE
Videos are not aware of each other

### ISSUE THREAD

**Issue by stephcard** [carbon-design-system/carbon-for-ibm-dotcom#4168]
Hello! I'm building a smart paper that utilizes the IBM.com Carbon React video component.

I have the following use case:
User plays video A
User plays video B. Upon playing video B, video A should pause

Is there an existing function that handles the above use case?

It's my understanding that we are not supposed to use or reference Kaltura documentation directly, however; the Carbon React docs don't cover multiple videos on one webpage and their behavior.

**Comment by stephcard** [comment]
Hello!

Will this effort provide a function where a video can be programmatically paused? Or should I submit a new ticket?

Use case:
User opens drawer.
User plays video in drawer.
User closes drawer. Upon closing the drawer, the video inside the drawer should pause.

**Comment by asudoh** [comment]
Hi @stephcard it seems a separate issue. Seems that the drawer is not something we maintain (my apologies otherwise), it needs to be solved in adopter-side, by calling below when drawer is closed:

```javascript
document.querySelector('.bx--video-player__video').sendNotification('doStop');
```

**Comment by stephcard** [comment]
Thank you @asudoh! This is exactly was I was looking for but I wasn't sure of the correct selector. Thanks again.

**Comment by ljcarot** [comment]
@asudoh can we update our documentation so it is clear for people

**Comment by asudoh** [comment]
@ljcarot Makes sense! Created: #4339

**Comment by stephcard** [comment]
Hello! Is this fix in the latest release?

**Comment by ljcarot** [comment]
@stephcard Documentation has been updated here: https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/4376/index.html?path=/docs/components-videoplayer--default
