### ISSUE TITLE
React: Masthead - @800px to 920px Platform is not visible

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4172]
## Detailed description

Issue: When user re sizes the browser to 800px to 920px, Platform is not visible

**Comment by RobertaJHahn** [comment]
Seems to be a duplicate of an adopter and adopter Slack request.  Will close this issue as a dup when the bug is submitted by the adopter.

**Comment by kennylam** [comment]
@RobertaJHahn @Praveen-sr This is a duplicate of #4140 and has already been fixed.
