### ISSUE TITLE
Web Components: Align to non-gutter grid line and use CSS grid

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#4174]
### The problem

Some components, like feature card and video player, does not work unless they are put in a Carbon grid or a similar style. OTOH, some components, like callout, creates grid by itself.

### The solution

Understand the rationals behind it. Some possibilities:

* Remove the requirement of grid if possible
* Clearly document the grid requirement
* Having feature card, video player, etc. render grid by itself

**Comment by jeffchew** [comment]
After investigation, @asudoh notes that this is more like 20+ story points and should be converted into an epic. The team discussed and we are ok to move this out of #4100 and will target a future minor release (tentatively v1.1.0).

@RobertaJHahn let's add this to the next engineering refinement meeting to break this work down, tentatively begin the work in sprint 21-02.
