### ISSUE TITLE
Masthead overflow – keyboard should skip overflow buttons

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#4182]
## Detailed description

> Describe in detail the issue you're having.

- **Included the `sprint must have` label as this overflow feature is committed for the Nov release** 

When navigating through the masthead with the keyboard, the overflow buttons are not being skipped and are getting a focus state. 
The functional specs state the overflow buttons should skip focus on keyboard:

<img width="739" alt="Screen Shot 2020-10-08 at 12 14 08 PM" src="https://user-images.githubusercontent.com/45692622/95485602-fc0a2b00-095f-11eb-90ee-e787b8d24236.png">

![overflow button should skip focus Oct-08-2020 12-18-06](https://user-images.githubusercontent.com/45692622/95485957-68852a00-0960-11eb-85f8-08bb3056e4ce.gif)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

masthead

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Should match functional spec

> What browser are you working in?

Chrome
Version 85.0.4183.121 (Official Build) (64-bit)

> What version of the IBM.com Library are you using?

Canary

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

October release

## Steps to reproduce the issue

1. Open in Chrome
2. Use keyboard to navigate through masthead
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by jeffchew** [comment]
@oliviaflory I think I remember that Ram and @Praveen-sr opened a different approach where we would provide a different aria-label that tells what it is, but not hide it. We might need functional spec updates on this @photodow ?

**Comment by wonilsuhibm** [comment]
This isn't just about the screen reader though—the mismatch between what's on the screen and the pagination and functionality will be confusing to users and this does feel like an error.

**Comment by photodow** [comment]
@jeffchew @wonilsuhibm @oliviaflory do we need to set up a short meeting to discuss this? I feel like we're talking about 3 different things, or at least coming at it from 3 different angles and it might be nice to align before we make any changes.

**Comment by oliviaflory** [comment]
That sounds like a good idea @photodow

**Comment by RobertaJHahn** [comment]
Roberta will schedule a meeting next week.

**Comment by RobertaJHahn** [comment]
Update the functional specs to NOT hide the left / right arrow from screen readers, but include an aria label that provides a description of the button behavior.  This is to accommodate to avoid confusion for users with low vision.

@photodow This is no longer a dev bug, but requires an update to the functional specs.

**Comment by oliviaflory** [comment]
After the discussion we had today (10/22) with the accessibility team, Ram would like to review the updates made in #4183 before determining if the overflow buttons should be hidden from screen readers.

**Comment by RobertaJHahn** [comment]
@Praveen-sr Can you retest this to be sure the change works properly.  Thanks.

**Comment by Praveen-sr** [comment]
@oliviaflory @RobertaJHahn @ariellalgilmore We re tested this on [React](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--with-l-1) 

For keyboard user working fine.

For screen reader users:
Mentioned buttons are reachable only in up/down arrow key navigation. These buttons are not reachable in tab/shift tab navigation hence this may be confusing for the screen reader user. 
Since all the menus items are navigable even without accessing overflow buttons, these can be hidden from the screen reader to avoid any confusion. **Hide [using aria-hidden] overflow buttons from the screen reader**. 
Note: this is applicable for both JAWS FF as well as Voiceover iPhone.

**Comment by oliviaflory** [comment]
@Praveen-sr thank you and Ram for the quick feedback

Confirming your recommendation is to:  **Hide [using aria-hidden] overflow buttons from the screen reader**
