### ISSUE TITLE
Web Component: Create Leaving IBM design specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4210]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the `Leaving IBM` design specs

> so that I can:
correctly create the `Leaving IBM` component 

#### Additional Information
- [Leaving IBM Ideation issue #160 link](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/160)

#### Acceptance Criteria
- [x] A Sketch file is created or updated with the `Leaving IBM` design and specs
- [x] Create a Box folder for the `Leaving IBM` (if not already there)
- [x] The design specs and pdf version are added to the Box folder 
- [x] Update the Ideation Board epic with the specs link
- [x] Update the Agile Board epic with the spec link
- [ ] Add Box folder link to the website content if it exists

**Comment by photodow** [comment]
Here are the design specs for the leaving ibm component.

https://ibm.ent.box.com/folder/124606259113
