### ISSUE TITLE
Change the default setting for modal videos to be unmuted

### ISSUE THREAD

**Issue by lily-kenney** [carbon-design-system/carbon-for-ibm-dotcom#4211]
### The problem
Currently, the modal video player is muted by default. See videos on https://www.ibm.com/testing/services/ for reference. From usability perspective, this requires users to perform an extra click of unmuting to hear the videos. This request is to change the default setting to unmuted.

### The solution
Change default setting of video player to unmuted and playing at volume around 20-40%.

Default:  change to unmuted, with option for user to unmute

### Additional information
For more info, please reach out to Jina Yoon.

**Comment by RobertaJHahn** [comment]
Kenny to reach out to Jina for more info.

**Comment by kennylam** [comment]
Hi @lily-kenney @jyoon25, inline embedded videos currently aren't muted by default, whereas videos embedded in a modal are. The difference is because videos in a modal autoplay and best practices are that videos which autoplay should be muted. But looking at it now, I'm not sure videos in a modal need to be muted even if they autoplay, since the modal is explicitly triggered by the user.

@wonilsuhibm @jeffchew thoughts?

**Comment by jyoon25** [comment]
@kennylam  Thanks for confirming! 
I think autoplay with muted is right action because it can prevent several video audio crushes.

**Comment by wonilsuhibm** [comment]
@kennylam @jyoon25 

I wonder if the video should NOT auto-play in a modal:
- Muted autoplay is a clear cut case for embedded autoplaying videos, 
- But in this case, the user did click a button with the intent to watch the video. So muting feels wrong. 
- However, the opening of the modal feels like a big change and could be a bit jarring. 

With these things considered, I am wondering if the video should not autoplay when opening in the modal.

@photodow @oliviaflory @JennySanchez @jacobottesen-dgc @jeffchew any thoughts?

**Comment by JennySanchez** [comment]
@wonilsuhibm Agreed with the video should NOT auto-play or muted in a modal.

**Comment by RobertaJHahn** [comment]
Closing.  We are going to leave the design in place.
