### ISSUE TITLE
Web component: Masthead - search open by default - User tabs and reaches "Profile menu”, the search field disappears.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4216]
## Detailed description

Issue: When the search field is displayed, if we reach the “Profile menu” with the tab key, the search field disappears. Again when we do shift tab from the “Profile menu”, the same appears again. This behavior confuses the user.

Expected: 
 When the user navigates to the next or previous control in the page, the search edit combo should not disappear.

**Comment by asudoh** [comment]
@wonilsuhibm @jeffchew Wanted to double-check what the consensus was; Was it that we use the close button as the only mean to close the search box, or something else? Thanks!

**Comment by asudoh** [comment]
The fix for #4072 ended up with fixing this issue, too. Please speak up if the behavior of latest canary is not desirable.
