### ISSUE TITLE
React: On Footer - Language only - User types any Country/Language, it remains on the selector field 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4225]
## Detailed description

Issue: User types any Country/Language and clicks on 'Enter' key. The text entered remains on the language selector field.

## Additional information

![Footer_lang1.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/384251f2-7aca-4928-8b69-7d75cfd82e71)

**Comment by IgnacioBecerra** [comment]
I looked into this and found that we are using [`ComboBox`](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/ComboBox/ComboBox.js) from Carbon Components, which means we would have to contribute this as a feature instead.

**Comment by jeffchew** [comment]
This is the expected behavior of ComboBox, and currently no adopters have any issues with this behavior. Closing this out.
