### ISSUE TITLE
React: Masthead - Profile menu options are not identified by the screen reader.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4233]
## Detailed description

On Voiceover iPhone/Safari 

Issue: Upon activation of user profile menu, the options are not identified by the screen reader immediately after the triggering element. The options are identified at the end of the page. This issue is found in "dotcom shell react staging" as well.

Expected:
Screen reader should identify the options immediately after the triggering element

**Comment by annawen1** [comment]
@Praveen-sr can this bug be retested? I tested in MacOS VoiceOver and it is reading out the MyIBM link when user opens the profile menu
