### ISSUE TITLE
Hamed alrasheedi

### ISSUE THREAD

**Issue by hamed19901411** [carbon-design-system/carbon-for-ibm-dotcom#4247]
#### User Story

> As a `[user role below]`:

> I need to:

> so that I can:

#### Additional information

 - _{{user research}}_
 - _{{user insights}}_
 - _{{user metrics}}_

#### Acceptance criteria
 - [ ] _{{State acceptance criteria}}_
 - [ ] _{{State another}}_
 - [ ] _{{And another}}_

**Comment by RobertaJHahn** [comment]
No information in this issue.  Closing.
