### ISSUE TITLE
Web component: Table of content - Heading content is not displayed for mobile users.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4263]
## Detailed description

On iPhone and android 10 mobiles 
 
Issue: Table of content - Heading content is not displayed for mobile users.

Note: Working fine on react 

## Additional information

Actual: 
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/7f0b4fca-c1bb-41d2-889d-c22c01c3237f)

On react:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/32d19efe-0e11-488e-a767-ca976b723466)

**Comment by asudoh** [comment]
@Praveen-sr Is this still reproducible? Thanks!

![image](https://user-images.githubusercontent.com/1259051/97130885-001eb100-1786-11eb-95cf-d82dd9cc5141.png)

**Comment by Praveen-sr** [comment]
@asudoh Re tested this on iPhone and Android, 

On iPhone, with iOS 14 - Working fine
On Android, with OS 10 - Working fine 
but 
On iPhone, with iOS 13 - **Not working** 
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/ad007a80-a142-44c5-becf-e01959cf9d23)

**Comment by asudoh** [comment]
Found out that the test with IOS 13 seems to have been done with Safari 13.0. Web Components version of table of contents component requires Safari 13.1, which is available starting with iOS 13.4. BrowserStack does not seem to control the minor version of iOS, but sometimes you'll newer version of iOS13. That said, here's how the test can be done:

1. Open one of iOS13 devices in BrowserStack
2. Open DevTools in BrowserStack (Not Chrome DevTools)
3. Open Console tab
4. Type `navigator.userAgent`
5. See if it tells `Version/13.0.x` or `Version/13.1.x`. If the former, select Stop Session button and go back to 1. If the latter, start testing our table of contents component
