### ISSUE TITLE
Utility:  Create the MVP animation / fade utility

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4281]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create the `animation / fade utility`

> so that I can:
provide the ibm.com adopter developers with a utility that will enable them to include animation in the ibm.com web pages they build

#### Additional information

- **See the Epic for the Design and Functional specs information**
- [design specs for the scroll into view utility](https://ibm.box.com/s/raw94fq6dcfuey786zks0c6mx24kf0cd)
- Prod QA testing issue (#4433)

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Minimum 80% unit test coverage
- [ ] Add this feature to the React NextJS test page for testing
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by jeffchew** [comment]
Look into using Intersection Observer API for this.
