### ISSUE TITLE
feature-card-block-medium: Rename heading slot to block-heading

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#4283]
### The problem

Accordion to @kennylam, feature card block [should put the heading portion outside of the card portion](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4125#issuecomment-713820230), but `<dds-feature-card-block-large>` doesn't do that.

### The solution

Make `<dds-feature-card-block-large>` render the heading portion outside of the card portion. It can be done by overriding top-level `render()` method, for example:

```typescript
render() {
  const { _hasHeading: hasHeading, _handleSlotChange: handleSlotChange } = this;
  return html`
    <h3 ?hidden="${!hasHeading}" class="${prefix}--feature-card-block-large__heading">
      <slot name="heading" @slotchange="${handleSlotChange}"></slot>
    </h3>
    ${super.render()}
  `;
}
```
#### Additional Information
- [Feature Card Block Large functional specs](https://ibm.ent.box.com/file/655898992298?s=lnbirrgqwzxuryy8q6e3lfpt0697o13z)
- [Feature Card Block Large Design Specs](https://ibm.ent.box.com/file/652669833356?s=vt1j7pgq830siebudzh0cqp761t7ghy9)
- [NextJS page](https://ibmdotcom-nextjs-staging.mybluemix.net/solutions.html)
- [Solution Landing Page](http://solution-landing-test.mybluemix.net/)

**Comment by kennylam** [comment]
@asudoh Just to clarify, the function specs for this component do not include a block-level header. I'll update the component README to avoid confusion.

![image](https://user-images.githubusercontent.com/909118/103909763-12945f80-50d2-11eb-87e2-3cd94b8d04f0.png)

cc: @RobertaJHahn

**Comment by asudoh** [comment]
Cool thank you for clarifying @kennylam!
