### ISSUE TITLE
Web component: Leadspace - Specific button size increases whereas other button remain same.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4293]
## Detailed description
On Mobile & tab

Issue: When button text is increased, specific button size is expanded but other button remains same.

Note: Working fine on React 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/3e8da395-c896-439e-b4e3-620451d292ec)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/66e5eb9d-06dc-4eac-8e30-67e7910c3953)

**Comment by asudoh** [comment]
This is a cross-component issue. We are forgoing this issue for now in Web Components codebase so that we can figure out a performant way to set the right width/height. It'd be nice if this is slated for later sprint.

**Comment by asudoh** [comment]
#4700 addresses this issue.
