### ISSUE TITLE
Featured Card Group

### ISSUE THREAD

**Issue by mfearer94** [carbon-design-system/carbon-for-ibm-dotcom#4294]
### The problem
When a user has a group of information in the form of cards, the user might want to elevate one of those cards if it isn't getting enough web traffic or if the information was just released.

### Summary
This proposed pattern elevates an item from the group and helps establish hierarchy to better guide users. Its contents can also easily change as business priorities change.
<hr>

### Design and spec
Please see the comments section for the specs or this ticket: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4373

### Designs
NOTE: These are examples of the designs, but please check the comments section for the official designs.
<img width="300" alt="Screen Shot 2020-12-11 at 3 03 21 PM" src="https://user-images.githubusercontent.com/32109645/101949832-3b543280-3bc2-11eb-880f-86c7b2159927.png"><img width="300" alt="Screen Shot 2020-12-11 at 3 03 39 PM" src="https://user-images.githubusercontent.com/32109645/101949846-4018e680-3bc2-11eb-88de-8c9b390e1fff.png">

<hr>

### Content model
This pattern includes the content model of the _card with image/video_ and inherits the _Card Group_ pattern.

### Featured Card:
- Image or Placeholder Image (Required) - (Desktop/Tablet: 16:9 ratio) (Mobile: 4:3 ratio)
- ALT Text (Optional) - Not needed if image is decorational. This may potentially be populated by ALT Tag associated with image from the DAM (if applicable)
- URL Link of the featured card can either be to a location or can be a video instead
- This content model contains all fields from the _Card Group: Cards_ content model

<hr>

### Additional information
Other than the feature card addition, we are proposing some other changes to the base _Card Group_ pattern below:
1. An option should be added to the card group content model to add (16px for desktop and tablet, 8px for mobile) gutters between the cards. This field would be boolean with the default being set to "True" for the card group with featured card.

**Comment by RobertaJHahn** [comment]
An Ideation issue has been created to support the Reboot design work.  [Issue #175](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/175).

**Comment by jyoon25** [comment]
![image](https://user-images.githubusercontent.com/67110948/101959949-5a5bc000-3bd4-11eb-9b36-fdc79f181a7b.png)
![image](https://user-images.githubusercontent.com/67110948/101959970-63e52800-3bd4-11eb-9012-fbfc295aafb0.png)

pdf link: https://ibm.box.com/s/yh1r97n9qr9d6rd5jhz79c7vxqx7uhan
sketch file link: https://ibm.box.com/s/6emz52gr4cvtqnkbempdwjfmjkcdd250

There is 2 version for featured card.
MVP: 1 big featured card with img & no img cards
Additional features: 1 big featured card with img & img cards

Let me know if you have any comments. Thanks!

cc: @mfearer94 @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Closing this epic and all linked issues as it is several months old and the work has not be prioritized.
