### ISSUE TITLE
Image with caption: Support response image item

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#4300]
### The problem

`<dds-image-with-caption>` does not support adding additional picture sources for smaller screens via `<dds-image-item>` as of today. This is inconsistent with `<dds-image>`. @ccwilson-us-ibm-com's team needs this feature.

### The solution

Implement it.

**Comment by RobertaJHahn** [comment]
This issue will be included in the engineering Huddle meeting.
