### ISSUE TITLE
Event properties support for CardGroup 

### ISSUE THREAD

**Issue by aiproulx** [carbon-design-system/carbon-for-ibm-dotcom#4309]
https://ibm-content-coe.slack.com/archives/C2PLX8GQ6/p1603482829165100

In KC we are using CardSectionSimple, and cards do not support event on click. 

### The problem

Issue is summarized in the Slack thread:
https://ibm-content-coe.slack.com/archives/C2PLX8GQ6/p1603482829165100

Akira Sudoh 
I don’t know much about its background, but what I can see is that <CardSectionSimple> renders <Card>s via <CardGroup>, <CTA>, <CardCTA> and <CardLink>. But <CardGroup> seems to limit the list of props to be sent to <CTA>: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/v1.12.0/packages/react/src/components/CardGroup/CardGroup.js#L85-L102 (edited) 
packages/react/src/components/CardGroup/CardGroup.js:85-102
          <CTA
            style="card"
            key={index}
            customClassName={`${prefix}--card-group__card`}
            image={card.image}
            media={card.media}
            heading={card.heading}
            eyebrow={card.eyebrow}
            copy={card.copy}
            pictogram={card.pictogram}
            cta={{
              ...card.cta,
              icon: {
                src: ArrowRight20,
              },
            }}
            type={card.media ? 'video' : 'local'}
          />

<https://github.com/carbon-design-system/carbon-for-ibm-dotcom|carbon-design-system/carbon-for-ibm-dotcom>carbon-design-system/carbon-for-ibm-dotcom 

### The solution
Support event properties on cards within a card group, such as CardSectionSimple.

**If this request is not a priority, would be team consider adopting KC code contribution to this item?**

**Comment by kennylam** [comment]
@RobertaJHahn @aiproulx I've gone over this with @kyjak and it can be closed. The main issue he was having was applying `sameHeight` to the content elements (header, copy, etc), which has been addressed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/3330/commits/01dc30b2309f3694c8cfca111d14814e10b933e6. The click events can be added to the elements via standard event listeners.
