### ISSUE TITLE
Support for external link icon and custom label, in CTA in card footer

### ISSUE THREAD

**Issue by aiproulx** [carbon-design-system/carbon-for-ibm-dotcom#4310]
https://ibm-content-coe.slack.com/archives/C2PLX8GQ6/p1603482006161400

### The problem
We need to show the link the user is about to click will take them outside of the current IBM Property: external link.

We need to provide custom text label to CTA footer in card, with both custom text and icon.

### The solution
~Allow to support custom text label and icon in CTA of cards.~  Allow to support other icons in CTA of cards (external link)

### Additional information

reference image and discussion in slack channel.
https://ibm-content-coe.slack.com/archives/C2PLX8GQ6/p1603482006161400

**Comment by RobertaJHahn** [comment]
https://www.ibm.com/design/language/iconography/pictograms/design/

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/a5563a75-46c0-4be7-8bcf-6a4a552c0eda)

Scroll to the bottom of the page.  Andree will post an image of their implementation.

**Comment by wonilsuhibm** [comment]
This is the design we agreed to go ahead with.

![Screen Shot 2020-10-28 at 8.30.27 AM.png](https://images.zenhubusercontent.com/5ad8a7dd4b5806bc2bcfcb61/d81c8cd4-c33a-41b1-aec2-fe50af100138)

**Comment by aiproulx** [comment]
yes. The CardSectionSimple component needs to support custom icon, and open the link in a different tab.

**Comment by RobertaJHahn** [comment]
Jeff will include the implementation discussion in the Nov 5 engineering huddle meeting.

**Comment by RobertaJHahn** [comment]
@photodow Could you follow-up and update the functional specs with the agreement supported by Wonil so the dev's know what to build.  Thanks.

**Comment by photodow** [comment]
Sorry for the late response on this.

What I'm seeing here looks very similar to our [Card section — simple](http://ibmdotcom-react.mybluemix.net/?path=/story/components-cardsectionsimple--default) component. It appears to be almost the same content model and the icon should be included with a `type="external"` passed in, but it appears the `type` got hardcoded to `type="local"`. That should be updated though. I'm going to move this back to do this sprint, and notify the development team of the update to this. As for the visual typography, and spacing differences I'll tag these for consideration as we evaluate `Card` component as a whole in [this audit here](https://github.com/carbon-design-system/digital-design-ideation/issues/184) soon.
