### ISSUE TITLE
Add RTL artifact for Web Components gulp builds for CDN

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#4319]
#### User Story

> As a `[user role below]`:
Carbon for IBM.com adopter

> I need to:
have a RTL version of the web components dotcom shell CDN package

> so that I can:
Add RTL support to my application using the CDN version of Carbon for IBM.com Web Components

#### Additional information

 - There is currently a regular build script for generating the LTR bundles for the web components dotcom shell, which is uploaded to the production server for CDN access.
- Script will need to be updated to also provide an rtl version of the script. For example:
```
<script type="module">
  import 'https://www.ibm.com/common/carbon-for-ibm-dotcom/latest/ibmdotcom-web-components-dotcom-shell.rtl.min.js';
</script>
```

#### Acceptance criteria
 - [ ] Create bundle version of the dotcom shell that support RTL
 - [ ] Add to the CI/CD workflow to upload to the production/akamai environments

**Comment by jeffchew** [comment]
@asudoh this is ready for sizing if you have a sense of this. I was looking at the script and seems like there are a couple of ways we can handle this.
 
FYI @RobertaJHahn

**Comment by RobertaJHahn** [comment]
This issue has no assignees or sprint assignment.  @jeffchew Should this issue be assigned to you and @asudoh.  Included in this sprint?

**Comment by jeffchew** [comment]
@RobertaJHahn it's not urgent, we can discuss timing of this in our next engineering refinement

**Comment by jeffchew** [comment]
@asudoh the CI/CD workflow has been updated to upload and cache bust the rtl akamai artifact, but right now we're only uploading `next`, `beta`, and `latest` versions, so there's currently no versions of those tags that have the updated build script yet. We'll wait to see when the beta release this Friday pushes up but I think the work here is done at this point.
