### ISSUE TITLE
Web Components:  Update the Carbon mega menu to accommodate hybrid cloud + AI

### ISSUE THREAD

**Issue by lily-kenney** [carbon-design-system/carbon-for-ibm-dotcom#4322]
### The problem
As part of IBM's business priority to focus on hybrid cloud + AI, the Reboot team is updating the carbon mega menu to reflect this focus. This request is to get development + QA support on making the changes to the carbon mega menu.

### The solution
- Update the mega menu design to add a new area that allows highlights hybrid cloud + AI. 
- This Mega Menu version does not include the animation features:
      1. Back button doesn't have motion
      2. Motion forward overlaps and hides previous behind.
- Motion feature can be seen in this folder
      - [Motion folder for mega menu](https://ibm.box.com/s/bqn9xggrys3gcyuy0q0ubmf0w1b3gwvg)

### Additional information
-  Corresponding React wrapper epic (#4642)
- For this ticket, it'll be for us-en only; geo rollouts will be planned later.
- We anticipate that to support this change, we may need data structural changes and possibly tagging updates to accommodate the changes.
- We'll be running the design through Optimizely tests first to make sure that the design is effective in increasing engagement with hybrid cloud and AI and that  we're not negatively impacting other areas. 
 - [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/118692148518?s=lcjcmdoaz2hnj6gejx7ilafhrvje4k68)
- [Sketch File](https://ibm.ent.box.com/file/750670881989)
- [Design pdf](https://ibm.ent.box.com/file/750672262864?s=kie61ijq4ggvdhi6awjklp09a5ro4sms)

**Comment by ljcarot** [comment]
@photodow Can you please let me know if you will have the Func Spec at end of year?  In planning for dev to start first sprint of next year, we need this.

**Comment by photodow** [comment]
@ljcarot yup, it should be. I met with Shixie on Friday to go over it.
