### ISSUE TITLE
Components: Introduce a component for heading/copy, etc.

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#4326]
### The problem

Most of the components with heading contents in Web Components codebase has a corresponding component for heading contents, for the styling purpose. OTOH `<dds-link-list>` doesn't.

Also, `<dds-image-with-caption>` supports `heading` attribute but it doesn't have a corresponding `<slot>`.

### The solution

Consider introducing a similar one for `<dds-link-list>`. Also scan the codebase to see if we need any more components for heading purpose, for other areas.

### Additional information

Similar thing is seen with `<dds-card>`, etc.

**Comment by RobertaJHahn** [comment]
@asudoh Can this issue be closed?  I looks like all of the linked PRs are merged.

**Comment by asudoh** [comment]
@RobertaJHahn Thank you for checking - Would like to keep this open if possible. Further code inspection is needed to ensure we have finished everything.

**Comment by asudoh** [comment]
@RobertaJHahn This work is complete now. Thanks again for checking!
