### ISSUE TITLE
React: Language selector - On mobile view, drop down options are not visible for user.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4328]
## Detailed description

On Mobile and Tab

Issue: When user clicks on selector, keyboard opens and take most of the screen, due to this drop down options are not visible to user.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/f2060110-c763-4d6d-acff-57819696d0cc)

**Comment by guilhermelMoraes** [comment]
@Praveen-sr would you please provide more details about this one? I'm using [this link](http://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-footer--default-language-only) for testing and I'm not being able to reproduce it on my mobile or Browserstack. The language selector is working as expected.

**Comment by Praveen-sr** [comment]
@guilhermelMoraes Now in language selector for mobile is changed to default mobile selector so its working as expected.
Thanks!
