### ISSUE TITLE
Mega menu: Hybrid cloud & AI updated designs & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4336]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/118692148518?s=lcjcmdoaz2hnj6gejx7ilafhrvje4k68)
- [Sketch File](https://ibm.ent.box.com/file/750670881989)
- [Design pdf](https://ibm.ent.box.com/file/750672262864?s=kie61ijq4ggvdhi6awjklp09a5ro4sms)

#### Acceptance Criteria
 - [ ] Visual designs and specs received from Reboot designers
- [ ]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [ ] Meetings conducted with DDS team members to review the designs

**Comment by RobertaJHahn** [comment]
Reboot design available on Friday, Dec 4.  Roberta adding to the Dec 7 engineering meeting agenda.  James to work on the Func specs in sprint 20-25.

**Comment by RobertaJHahn** [comment]
Reviewed the designs with Shixie.

- Another optimizely test is going to be performed (with or without essentials)
- Data change is needed for the new links
- The data file is not owned by DDS.  Tina Williams has to be informed.  Shixie will let Lily know.

**Comment by RobertaJHahn** [comment]
Dec 7, 2020 Slack message from Shixie:

Hey Roberta, seems like Lily was able to clarify all the questions over slack just now. Here's what I've got and lemme know if this is everything yall need:

- Ideally done for Jan release
- The current Optimizely "test" was mostly for pushibg the new megamenu out early so don't have the wait for it to finish. If we wanna test the "the Essentials" label we will do it after.
- Lily is gonna talk to Tina W. Though I think she would just be letting her know. Detailed coordination like when to push merge etc might need to come from your team?

**Comment by wonilsuhibm** [comment]
This design has been reviewed and approved. Thank you @shixiedesign .
