### ISSUE TITLE
video player caption styles

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#4342]
## Detailed description

> Describe in detail the issue you're having.
The web component`DDSVideoPlayerContainer` is structured in a way where `.#{$prefix}--video-player__video-caption` styles are not accessible if `DDSVideoPlayerContainer` is used in another component such as `DDSCalloutWithMedia`

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
bug

> Is this issue related to a specific component?
Video Player

**Comment by asudoh** [comment]
Thanks @ariellalgilmore for entering this! A couple of options I can think of are:

1. Split out the caption portion of `<dds-video-player>`
2. Creating an inheritance of `<dds-video-player>` for callout with media
