### ISSUE TITLE
Web Components | Add Stable Selectors to CTA

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#4358]
## Detailed description

> Describe in detail the issue you're having.

Stable selectors and prop table are missing for `dds-cta`

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

`dds-cta`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Full documentation on stable selectors.

**Comment by asudoh** [comment]
@jeffchew `<dds-cta>` does not exist. Also I couldn't find any stable selectors defined in React CTA codebase. Any pointers? Thanks!

**Comment by asudoh** [comment]
Given `<dds-cta>` does not exist. React CTA component itself does not have `data-autoid`, either. That said, will be superseded by: #4366, #4357 and #4361.
