### ISSUE TITLE
Web Components | Add Stable Selectors to Image

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#4364]
## Detailed description

> Describe in detail the issue you're having.

Stable selectors and prop table are missing for `dds-image`

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

`dds-image`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Full documentation on stable selectors.

**Comment by asudoh** [comment]
`<Image>` has `data-autoid="dds--image__longdescription"`. It doesn't seems to actually represent what it does, and thus porting it to Web Components doesn't make sense. The recommendation for analytics is using `<dds-image>` tag.
