### ISSUE TITLE
Web Components | Add Stable Selectors to Quote

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#4368]
## Detailed description

> Describe in detail the issue you're having.

Stable selectors are missing for `dds-quote`

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

`dds-quote`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Full documentation on stable selectors, and add stable selectors for any applicable sub components.

**Comment by asudoh** [comment]
I see `data-autoid` on `<dds-quote>`:

![image](https://user-images.githubusercontent.com/1259051/97761672-a6353700-1b49-11eb-9866-9184dca56766.png)
