### ISSUE TITLE
Web Components | Add Stable Selectors to Video Player

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#4369]
## Detailed description

> Describe in detail the issue you're having.

Stable selectors are missing for `dds-video-player`

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

`dds-video-player`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Full documentation on stable selectors, and add stable selectors for any applicable sub components.

**Comment by asudoh** [comment]
React `<VideoPlayer>` has one `data-autoid` in its inner content `<div class="bx--video-player__video-container">`. Web Components versions renders it in Shadow DOM and thus analytics, etc. cannot access the element via `data-autoid`. So the suggestion is simply using `<dds-video-player>` tag to find the video player.
