### ISSUE TITLE
Featured Card Group design & design specs provided by Reboot designers

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4373]
#### Notes

  -  The Reboot team is responsible for creating the visual designs and design specs for most of the patterns included in the Solutions page.  This issue is to track the transition of the Reboot design work to the DDS design & engineering team members.

#### Additional Information
 - [Visual Designs & Design Specs Box folder link]

#### Acceptance Criteria
 - [ ] Visual designs and specs received from Reboot designers
- [ ]  A pdf file is created and placed in the Box folder with the updated Sketch file
 - [ ] Meetings conducted with DDS team members to review the designs

**Comment by jyoon25** [comment]
![image](https://user-images.githubusercontent.com/67110948/101959949-5a5bc000-3bd4-11eb-9b36-fdc79f181a7b.png)
![image](https://user-images.githubusercontent.com/67110948/101959970-63e52800-3bd4-11eb-9012-fbfc295aafb0.png)

pdf link: https://ibm.box.com/s/yh1r97n9qr9d6rd5jhz79c7vxqx7uhan
sketch file link: https://ibm.box.com/s/6emz52gr4cvtqnkbempdwjfmjkcdd250

There is 2 version for featured card.
MVP: 1 big featured card with img & no img cards
Additional features: 1 big featured card with img & img cards

Let me know if you have any comments. Thanks!

cc: @lily-kenney @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Closing this issue as the design work has not been prioritized in several months.
