### ISSUE TITLE
Masthead search events/callbacks for react

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon-for-ibm-dotcom#4398]
IBMDOCS needs callbacks/events similar to the web-components version of masthead search.
- on query string change
- on X button press
- on Search button press

**Comment by RobertaJHahn** [comment]
Andree has asked for this by the end of the month.  (Nov release - code freeze is Nov 13)

**Comment by RobertaJHahn** [comment]
@kyjak  We have assigned this work to the next sprint and the Nov release.  (Nov 25)

**Comment by kyjak** [comment]
I tried the functionality, all good but hitting ENTER key in the search bar activates still an IBM search and the search icon click is not fired.

**Comment by ljcarot** [comment]
What version were you testing on?

**Comment by kyjak** [comment]
1.13.0-rc.1
