### ISSUE TITLE
Web component: Content group simple - arrow link is not visible on the card

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4408]
## Detailed description

Issue: Content group simple - arrow link is not visible on the card

Note: When we select Jump option on card and open in new tab, card is not operable.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/5fc06c7e-9548-4e1e-ac9e-67acdf23484f)

**Comment by guilhermelMoraes** [comment]
Not happening anymore. 

[Web-components canary](http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-content-group-simple--default)

<img width="1249" alt="Screen Shot 2021-01-05 at 12 13 50" src="https://user-images.githubusercontent.com/42848561/103663086-7b070380-4f4f-11eb-9b0d-063416dea268.png">
