### ISSUE TITLE
Create a Carbon PR to contribute the DDS Link with icon component

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4416]
#### User Story

> As a `[user role below]`:
DDS engineer

> I need to:
submit the Link with icon component to Carbon 

> so that I can:
find out whether Carbon will accept the DDS component in their repo

#### Additional information

 - Reach out to Matt Rosno and Joshua Black to take a look at the Link with icon component before creating the PR
 - It they aren't interested, close this issue.

#### Acceptance criteria
 - [ ] Carbon makes decision about whether they will add this component to their repo

**Comment by guilhermelMoraes** [comment]
Issue created on Carbon's end, as following Matt Rosno suggestion: https://github.com/carbon-design-system/carbon/issues/7708
