### ISSUE TITLE
Content block simple/segmented/media/cards Leadspace block unmatched left/right margin at medium breakpoint

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4420]
## Detailed description

> Describe in detail the issue you're having.

Content block simple/segmented, content block - cards and Leadspace block do not match at the medium breakpoint

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/6d703b2f-6a2f-4ca1-b471-5a5c1742a3ee)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?  Bug

> Is this issue related to a specific component?
[content block segmented](http://ibmdotcom-react-canary.mybluemix.net/iframe.html?id=components-contentblocksegmented--default)
[content block media](http://ibmdotcom-react-canary.mybluemix.net/iframe.html?id=components-contentblockmedia--default)
[Leadspace block](http://ibmdotcom-react-canary.mybluemix.net/iframe.html?id=components-leadspaceblock--default)

####Additional Information
- [React Storybook Study Box note](https://ibm.ent.box.com/notes/736875354683)

**Comment by guilhermelMoraes** [comment]
Not happening anymore. Tested on [canary](http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-cta--button)
