### ISSUE TITLE
Dotcom shell:  Some content has a right margin and some does not

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4422]
## Detailed description

> Describe in detail the issue you're having.

Some content in the Dotcom shell has a right margin and some does not

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/a1df1425-09d5-4d10-830a-531b80729204)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?  Bug

> Is this issue related to a specific component?
[dotcom shell](http://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-dotcom-shell--default)

####Additional Information
- [React Storybook Study Box note](https://ibm.ent.box.com/notes/736875354683)

**Comment by guilhermelMoraes** [comment]
Not happening anymore. Checked locally and on canary.
