### ISSUE TITLE
Storybook: Use Plex in manager

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#4423]
### The problem

The manager UI in our Storybook uses the following font:

* React: Storybook default font, which is _not_ Plex
* Web Components: Uses Plex only in Chrome, Storybook default font for other browsers

### The solution

Use Plex across the board

**Comment by jeffchew** [comment]
As mentioned, this is probably best configured in Storybook theming: https://storybook.js.org/docs/react/configure/theming

Wonder if we should add as part of `storybook-addon-theme` package?

**Comment by jeffchew** [comment]
and another note, we might want to work with design to also see if they want to change things like color theme as well to match IBM colors.

**Comment by asudoh** [comment]
@jeffchew Right, #4424 uses `@storybook/theming`. I have seen an attempt to make Storybook manager UI look more like Carbon, including color scheme, but it seems to have been unsuccessful. We may want to do long-term investigation to see how much Storybook has evolved since then. BTW `storybook-addon-theme` is for the UI setting Carbon color theme, instead of the theme content.
