### ISSUE TITLE
L0 Masthead load lag

### ISSUE THREAD

**Issue by elliotttrice** [carbon-design-system/carbon-for-ibm-dotcom#4428]
## Detailed description

> The L0 masthead loads a few seconds after home page loads

> Is this a feature request (new component, new icon), a bug, or a general
> Bug

> Is this issue related to a specific component? Masthead L0

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Masthead should load with homepage

> What browser are you working in?  Don't know.  Rooney reported to me.

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

enter ibm.com into url

.

## Additional information
[Screen Recording 2020-11-06 at 2.03.11 PM.mov.zip](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/5503101/Screen.Recording.2020-11-06.at.2.03.11.PM.mov.zip)

**Comment by elliotttrice** [comment]
Forgot to mention this.  We are running a multivariate test with Products and Solutions megamenu.  Not sure if this is impacting.

I have not been able to replicate the issue.  This came from Rooney

**Comment by elliotttrice** [comment]
Browser: Safari

**Comment by jeffchew** [comment]
The resolution is that this is only happening in a preview URL and not production. Closing this.

@ljcarot @RobertaJHahn
