### ISSUE TITLE
[Footnotes section]

### ISSUE THREAD

**Issue by mfearer94** [carbon-design-system/carbon-for-ibm-dotcom#4434]
### The problem
Pages that include citations to other web pages, research papers, books, etc. don't have a templated way of getting added to a page. The current implementation on IBM.com does not have a standard and most of it is a minimal implementation of having non-interactive in-line citations.

### Summary
This proposed pattern creates a consistent citation/footnote experience so users know how to quickly find the citations they are looking for.
<hr>

### Designs
NOTE: These designs are completed by the Reboot team, but could be changed upon further review

LINK: https://ibm.invisionapp.com/share/SJO0NCJWKDE
![image](https://user-images.githubusercontent.com/32109645/98585954-02a8fc80-2296-11eb-8647-66f7342e1eba.png)
![Footnote_1](https://user-images.githubusercontent.com/32109645/98602780-072ddf00-22af-11eb-9ed5-5358d75f02f8.jpg)
![Footnote_2](https://user-images.githubusercontent.com/32109645/98602788-08f7a280-22af-11eb-8002-45b0c7284836.jpg)
![Footnote_3](https://user-images.githubusercontent.com/32109645/98602794-0b59fc80-22af-11eb-9483-1f701ee823dd.jpg)
See comments for Sketch file and research presentation

<hr>

### Content model
This pattern includes the modal from the Carbon Design System.
Ref: http://carbon-for-ibm-dotcom.mybluemix.net/components/expressive-modal/

### Footnote Container:
- Title (Required) - Simple Text (Max: 50 characters). Default = "References"

### Footnote Item:
- Reference (Required) - Rich-Text (Max: None)
- Anchor Tag (Required) - Simple Text. This is used to link the inline citation to the reference in the modal

<hr>

### Functional Requirements
- Citation is shown in a superscript
- The citation has a hover state
- When selected, the user is shown a modal
- If the list of references is taller than the screen, the user is taken directly to the clicked upon citation
- The above occurs for all screen widths and will show the reference at the top of the screen unless there is not enough room below the citation
- The modal contains the following:
1. Title - This uses the label styling
2. All sources
NOTE: The citation clicked upon is highlighted in the modal. This highlight disappears after a period of time (~1 second)
3. If a user clicks on a hyperlink, they are taken to the link in a NEW tab
4. When the “X” is selected, the modal is closed

Mobile Consideration: The modal takes over the entire screen

<hr>

### Potential CMS Implementation
![Footnote Options](https://user-images.githubusercontent.com/32109645/98582268-bdce9700-2290-11eb-8970-f331722f1beb.png)

<hr>

### Accessibility
- We need to look into the background of the selected citation in the references modal. We need to make sure there is no accessibility violation. Currently there is an accessibility violation for AA when the theme is "White" and there is a link that is being highlighted. There is no violation on Gray 10, 90, or 100. We are using "link-01" for the text color and "highlight" for the highlighted background.
- On mobile, we need to make sure the hit area is big enough for the inline citation. We are using the superscript as Wikipedia uses that and we didn't see any direct accessibility violation. However, we should make sure there is no violation and if there is, we should increase the hit area of use normal text instead of superscript.

### Additional information
Frequently asked questions about this design:
1. Why not use an accordion at the bottom - IBM.com is not a citation heavy website and they are secondary content
2. Why not use tooltips - The tooltips added unnecessary complexity to the citations. Also, since the citations are secondary content, it also seemed unnecessary to enable a tooltip when the user can quickly see the citations by clicking on the in-line number.
3. Disappearance of Citation Highlight - This is utilized to improve interactivity with the references in the modal
4. Why not provide a specific citation format - There are 11 major citation formats that are used across disciplines, the most notable being APA, MLA, and Chicago. With the variety and there being no known standard across IBM, we need to allow free form citation fields.
5. Why use the modal - The modal was used because IBM.com does not offer a lot of citations and so they are secondary content. The modal is part of Carbon already so this reduces development time and it offers a way for users to quickly see all references. Also, we won't have to make variations for what page type the citations live on as the modal is the same overlay no matter what the page type is.
6. Why not have a view all references CTA - To include this, we would have to make variations for different page types which increases complexity. Also, we are not restricting anyone from viewing the references as they can see them all by clicking on any inline citation. By not including a CTA to view all, we are only reducing page real estate for the references.

**Comment by mfearer94** [comment]
**Presentation with research is here:**
[Footnotes Presentation and Research.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/5513618/Footnotes.Presentation.and.Research.pdf)

**Comment by mfearer94** [comment]
Link to the Sketch File - https://ibm.ent.box.com/file/739701759810?s=lfopxsavw6lgxu0e08rp67ibf684p5wb

**Comment by wonilsuhibm** [comment]
@mfearer94 Thank you. A few question:
- Are you guys planning to provide specs?
- Can you also provide the design studies you have done, including all of the rejected design explorations please?
- Is the selected state accessible? (the blue background)

**Comment by RobertaJHahn** [comment]
Additional discussions needed with Reboot for design feedback and tech feasibility.  Convert to an epic and begin the process to have the BA.  Dev and designer are needed for additional discussions mentioned.

**Comment by mfearer94** [comment]
@wonilsuhibm Great questions and thank you for your quick response.
1. When you mean specs, do you mean a functional specs document that has usually been done by the DDS team?
2. I have added some information in the "Additional Information" section of why we didn't go down other paths. I'm asking Jina to add any designs she has that didn't make it.
3. I added a note about the state of accessibility for the highlight in the design details above. It seems there is an accessibility issue only for the White theme when using "link-01" and "highlight".

**Comment by jyoon25** [comment]
@wonilsuhibm  Here's answers for Qs. Thanks.
1. Specs are from https://ibmdotcom-react.mybluemix.net/?path=/story/components-expressive-modal--default
2. Here's footnote sketch file with old design variations: https://ibm.box.com/s/rvsm5ekh65e1x5zv9408r2zf9h44i72y

**Comment by wonilsuhibm** [comment]
AfterBurner team agreed to go ahead with this design as the standard.

**Questions**
- How to implement this?
- Who will develop this?

**Comment by RobertaJHahn** [comment]
Wonil will with Sandeep to submit a summarized feature request for the Footnote component.  This request will be moved through our process.

**Comment by ljcarot** [comment]
@shixiedesign Per product detail page review, do we want to move this out of Icebox?

**Comment by RobertaJHahn** [comment]
Discussed with Shixie.  Will work on the Footer v2 enhancement work first.

**Comment by RobertaJHahn** [comment]
Removed from icebox,  design (have), func specs, WC dev and React wrapper, QA, website, no e2e test issue
