### ISSUE TITLE
Web component: Content item horizontal - With tab/shift tab we are able to reach to the mentioned elements but there is no visual focus at all.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4439]
# Detailed description

Issue: 
Learn more link
Microservices and containers link
With tab/shift tab we are able to reach to the mentioned elements but there is no visual focus at all.

Expected:
Provide thick and strong visual focus.
1. If, Visual Focus Indicator with 3 CSS px stroke then provide a sufficient contrast that is equal to 3:1. 
2. Visual focus indicator for a link that is a 1 CSS px then provide a sufficient contrast greater than 4.5:1

**Comment by annawen1** [comment]
The focus state is visible, however there seems to be some extra padding when focused:
<img width="897" alt="Screen Shot 2020-11-30 at 4 53 57 PM" src="https://user-images.githubusercontent.com/54281166/100672366-d7af4700-332f-11eb-81b8-17b95aff7550.png">

The PR I have opened fixes this issue.
