### ISSUE TITLE
Masthead underline shape

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#4440]
## Detailed description

The blue underline that shows the currently active menu item has angled ends (see the attached image).

The ends should be flat (see the attached image)

## Steps to reproduce the issue

1. Open this [StoryBook page](https://ibmdotcom-react.mybluemix.net/?path=/story/components-masthead--default)
2. Check both ends of the underline.

## Additional information
- A screenshot has been added as a comment below.

**Comment by wonilsuhibm** [comment]
<img width="1471" alt="Screen Shot 2020-11-10 at 8 23 19 AM" src="https://user-images.githubusercontent.com/30183447/98679720-6c74e500-232e-11eb-9f07-6f50c3d87f83.png">

**Comment by oliviaflory** [comment]
Not sure if this is helpful, but it looks like the Carbon UI shell header is getting around the angled underline with 2px of space on either side of the blue highlight/selected state, example screen shot below. 

Note: it looks like there is a 1px border or something below the focus and highlight.

Link to [Carbon React storybook](https://react.carbondesignsystem.com/?path=/story/ui-shell--header-base-w-navigation)

<img width="760" alt="Screen Shot 2020-11-10 at 8 38 44 AM" src="https://user-images.githubusercontent.com/45692622/98686574-b6fa5f80-2336-11eb-89e3-4e5f533cf2e9.png">

<img width="708" alt="Screen Shot 2020-11-10 at 9 26 42 AM" src="https://user-images.githubusercontent.com/45692622/98686719-e315e080-2336-11eb-8855-fb8774285e00.png">
