### ISSUE TITLE
Carbon masthead preview

### ISSUE THREAD

**Issue by nodhamm** [carbon-design-system/carbon-for-ibm-dotcom#4458]
> As a `[user role below]`:
IBMer

> I need to:
be able to preview Carbon masthead prior publishing

> so that I can:
share the view with QA team and requester for a revision and confirmation everything works properly

#### Additional information

There is already Jenkins bot to generate preview for former Northstar masthead.
Note: Carbon allows to use masthead from Northstar on Carbon page, so having all 3 options available will be perfect but not necessary.

#### Acceptance criteria
Able to preview masthead preview in both - Northstar and Carbon. Can be different URLs

**Comment by jeffchew** [comment]
@kennylam I have it all working now, hope you didn't get too far on this. I'm opening up a PR shortly and have the Jenkins job in place too.

**Comment by jeffchew** [comment]
@nodhamm the deploy previews are now available for Carbon, you can see it in action here: https://github.ibm.com/webstandards/ibm-dotcom-translations/pull/227
