### ISSUE TITLE
Web component: CTA section -with link list - the links are not left aligned, as per specs.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4475]
## Detailed description

Issue: CTA section -with link list - the links are not left aligned, as per specs

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/85cfce1b-f074-4f3e-9de3-ebad351f8038)

Specs:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/4197e5a0-964c-4b01-8cc3-3ffbaaffbe1b)

**Comment by IgnacioBecerra** [comment]
This issue has now been fixed in #4461.
