### ISSUE TITLE
Web components: mega menu arrow icons not vertically centered with text

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#4492]
## Detailed description

> Describe in detail the issue you're having.

The arrow icons on all of the Category heading are not vertically centered with the text, they are too low

The arrow icons on the CTAs at the bottom of the Products & Services and Services & Solutions menu are not vertically centered with the text, they are too high.

**As-is (Safari)**
![Screen Shot 2020-11-13 at 4.00.39 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/3a32bcdb-46d1-4582-82ed-7fd23a495935)

**What it should look like (Chrome)**
![Screen Shot 2020-11-13 at 4.05.44 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/80361976-2f6e-4cae-9d6a-bdbe95819d0e)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

Mega menu 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

Safari Version 14.0 (15610.1.28.1.9, 15610)

> What version of Carbon for IBM.com are you using?

[Canary](https://ibmdotcom-web-components-canary.mybluemix.net/iframe.html?id=components-masthead--default)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by IgnacioBecerra** [comment]
Seems like this issue has been fixed already?

**Comment by annawen1** [comment]
@IgnacioBecerra I'm seeing the issue on safari on my end - I'm on version Version 14.0.1

**Comment by IgnacioBecerra** [comment]
@annawen1 Ah, my bad, I completely overlooked it was a Safari bug. Thanks for letting me know!
