### ISSUE TITLE
React: Masthead mobile menu chevron icon too small

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#4495]
## Detailed description

> Describe in detail the issue you're having.

The chevron icons on the React component masthead mobile menu are smaller than they should be. You can see in comparison to the Back button the chevron is smaller in the menu items

My hunch is that the mobile menu has 16x16px icons, and React has 20x20px

This is also happening in Web components (#4494) 

<img width="418" alt="Screen Shot 2020-11-12 at 6 04 19 PM" src="https://user-images.githubusercontent.com/45692622/99125609-656e0100-25d2-11eb-900e-5dae2fe48fc0.png">
<img width="418" alt="Screen Shot 2020-11-12 at 6 04 31 PM" src="https://user-images.githubusercontent.com/45692622/99125614-669f2e00-25d2-11eb-9f71-af9bfc5c9e1a.png">

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

React masthead mobile menu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

icons should be 20x20 px

> What browser are you working in?

Chrome

> What version of Carbon for IBM.com are you using?

[React](https://ibmdotcom-react.mybluemix.net/?path=/story/components-masthead--default)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Additional information

- Screenshots or code
- Notes

**Comment by ariellalgilmore** [comment]
Already fixed! Closing cc:@RobertaJHahn
