### ISSUE TITLE
Footer documentation clean up - Target sprint 21-02

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#4496]
#### User Story

> As a `[user role below]`:

user of Carbon for IBM.com

> I need to:

be able to read an understand the documentation and resources provided to me

> so that I can:

use the correct component in my designs / build.

#### Additional information

An adopter reached out to me to ask "**_Which footer is correct?_**" after looking through our various documentations the adopter and I found a number of slight variations and name inconsistencies that made it confusing to know which was "correct"

 **Website**
- "Default" footer is labeled as "Tall" in storybook 
  - Q _Which is correct, default or tall, I thought we had agreed on ~Tall~ **Default**?_
- "Minimal" footer should be "Short"
- Link to Sketch file under Design and Functional specs did not work for the adopter

**Storybook**
- Cookie preferences link is hidden, adopter questioned if this was "optional"
  - Q: _Do we address this requirement through documentation on the website and in Storybook Docs?_
- The variant name on the side panel is "Default", but the Storybook Docs calls Default footer "Tall" under the Props / name 
  - Q _Which is correct, default or tall, I thought we had agreed on ~Tall~ **Default**? See same question in Website_

**Sketch file**
- Sketch file magenta labeling on artboards says "minimal version" and should be "short"
- Sketch artboards should also be renamed from "minimal" to "short" 

**Sketch kit**
_Note: This sketch kit is technically outdated, and needs to be updated to reflect all updates to masthead and footer_
- Footer symbol has 6 legal links, website shows 5, Storybook shows 4.

#### Acceptance criteria
 - [ ] All above questions have been addressed and agreed upon
 - [ ] All documentation has been updated and synchronized

**Comment by RobertaJHahn** [comment]
Engineering support is needed for the Storybook updates.
