### ISSUE TITLE
Masthead and Footer content not getting translated.

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/carbon-for-ibm-dotcom#4505]
@sabhareesan commented on [Tue Nov 17 2020](https://github.com/carbon-design-system/carbon/issues/7300)

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
By changing the locale in the LocaleModel component, the Masthead and Footer content is not getting translated.

> Is this issue related to a specific component?
Locale Model

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The content in the Masthead and Footer needs to be translated when the locale is changed in the Locale Model component 

> What browser are you working in?
FireFox, Chrome, Safari

> What version of the Carbon Design System are you using?
"@carbon/ibmdotcom-react": "^1.12.0"
"carbon-components": "^10.23.2"
"carbon-components-react": "^7.23.2"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Application: IBMid Profile UI (already in Production)
https://www.ibm.com/ibmweb/myibm/profile

## Steps to reproduce the issue
1. Open ProfileUI Page in Firefox (https://www.ibm.com/ibmweb/myibm/profile)
2. Change the locale in Locale Model component

## Additional information

screenshot from the Profile UI page 
![image](https://user-images.githubusercontent.com/23634668/99386861-16d5a500-28f9-11eb-8f12-a8769319e3a8.png)

---

@sabhareesan commented on [Tue Nov 17 2020](https://github.com/carbon-design-system/carbon/issues/7300#issuecomment-728930492)

This issue is related to https://github.com/carbon-design-system/carbon-for-ibm-dotcom repo, can some one help me in transferring this issue.

**Comment by annawen1** [comment]
This was working for my firefox version v79.0
<img width="1742" alt="Screen Shot 2020-11-17 at 10 35 35 AM" src="https://user-images.githubusercontent.com/54281166/99410835-ee31b900-28c0-11eb-9f71-9e929394d588.png">

but once I upgraded to v83.0, I see the Footer does not update to the selected language. The Masthead works fine for in my most updated Firefox version.

**Comment by sabhareesan** [comment]
In **Masthead**, I was referring to the right side list
![image](https://user-images.githubusercontent.com/23634668/99419901-9fb50680-2922-11eb-88a6-65638e9c8a12.png)

This issue can be seen in Safari also.

The **Cookie preferences** link is not getting translated in your case. And also the **Locale Model** does not provide the translated content.
![image](https://user-images.githubusercontent.com/23634668/99420709-8cef0180-2923-11eb-8752-cceb94e91daa.png)

**Comment by annawen1** [comment]
This issue I'm not seeing in Safari or Chrome, only in Firefox - note the locale modal translations are not coming through for all browsers it seems. 

The cookie preferences link is injected by another team, we will have to check in with them

**Comment by kennylam** [comment]
I'm checking in latest FF (83.0) and it's working for me

![image](https://user-images.githubusercontent.com/909118/99545791-c22b3c00-2983-11eb-8a9a-9a7275052b65.png)

![image](https://user-images.githubusercontent.com/909118/99545877-d2431b80-2983-11eb-9494-9548ec730f78.png)


@sabhareesan Can you clear your session storage, cookies, and cache and try again?

**Comment by annawen1** [comment]
Hi @sabhareesan, in addition to clearing your session storage, cookies, and cache - for the translation service, it looks at the DDO for which language to grab the translated content. When looking at the console, it seems the `language` may not be set properly in the DDO? Please see below that when I switched to Chinese in the locale modal, the DDO language still says `en-US`

<img width="855" alt="Screen Shot 2020-11-18 at 10 51 03 AM" src="https://user-images.githubusercontent.com/54281166/99553501-3538b080-298c-11eb-843c-b4b87dc69b39.png">

CC: @asudoh @kennylam

**Comment by kennylam** [comment]
@sabhareesan For comparison, here is a site where the DDO language is set correctly and all translations come through upon switching with the locale selector.
https://myibm.ibm.com/profile/dataprivacypreferences/welcome/us-en

![image](https://user-images.githubusercontent.com/909118/99554850-a9c01f00-298d-11eb-9630-5cc8b2a46cca.png)

**Comment by sabhareesan** [comment]
Thank you @kennylam, @annawen1 for reviewing it.  

We set the DDO language as shown below 
![image](https://user-images.githubusercontent.com/23634668/99666234-bbd6b600-2a90-11eb-9db9-d0a1a18f8909.png)

And this works fine in our stage env (https://wwwstage.ibm.com/ibmweb/myibm/profile), this issue is seen only in Production.
If the translation services are based in DDO it should fail in our stage env, right?

**Comment by annawen1** [comment]
Right, it would also fail in your staging env. I would take a deeper look at what is causing the difference between the two environments.

Closing this ticket as the translation services is working as expected and the issue seems related to deployment.
