### ISSUE TITLE
React: Button group - issues with button sizing and spacing.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4513]
## Detailed description

Issue: 
1. On Tab / Mobile Users edit/update button text, edited button size is bigger compared to other button.
2. Their is no spacing between copy text  

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/17f15b48-0115-40d8-aa34-b662000bea1f)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b8de5bfc-b98d-4362-be20-bd355326fc25)

**Comment by kennylam** [comment]
@Praveen-sr I'm not seeing this in any environment. What does #2 mean - no text spacing?

cc: @RobertaJHahn

**Comment by Praveen-sr** [comment]
@kennylam 
1. Button sizing issue is fixed now.
2. There is no spacing between first and second lines
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/a294c8dd-c1d6-4da7-a567-11a43e170e2c)

**Comment by kennylam** [comment]
@Praveen-sr @RobertaJHahn This copy is for Storybook only. It is not using any of our components or patterns and can be disregarded in terms of layout.

**Comment by RobertaJHahn** [comment]
@kennylam Should this issue continue as a React Storybook bug or can it be closed?
