### ISSUE TITLE
React: Masthead - Issues with mega menu options 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4525]
## Detailed description

Issue: 
1. User clicks on overflow and then clicks on first Menu option,  the IBM logo is covered
~~2. On Custom menu options, user not able to see sub links under the menu but when we hover on it focus goes there.~~

## Additional information

![Masthead2.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/af759450-55e7-444d-b018-f60c4d3b2266)

![Masthead3.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/4726fa9f-030d-434a-bd51-173d94a9426f)

**Comment by annawen1** [comment]
I will create a separate issue for the second item - the custom data not coming through on the megamenu we have confirmed is an issue with storybook itself.
