### ISSUE TITLE
ibm.com language locale selector modal doesn't display in Arabic when the current language is in Arabic

### ISSUE THREAD

**Issue by yellowdragonfly** [carbon-design-system/carbon-for-ibm-dotcom#4528]
ibm.com language locale selector modal doesn't display in Arabic when the current language is in Arabic

version checked V1.13.0-rc.1

**Comment by annawen1** [comment]
hi @yellowdragonfly, the Arabic translations are not available for the locale modal at the moment so it will default to English. We will need to put this in as a request to the translation team

**Comment by ljcarot** [comment]
@kennylam Do we have translations for Arabic in the v18 translation file?

**Comment by kennylam** [comment]
@ljcarot for the masthead/footer we do, but not for the locale modal.

**Comment by RobertaJHahn** [comment]
@kennylam don't forget to provide the final status on this issue, so that I can close.  Thanks.

**Comment by kennylam** [comment]
As mentioned earlier, currently the only official translation is `us-en`. Additional translations for supported locales should be coming soon.

cc: @RobertaJHahn @ljcarot

**Comment by yellowdragonfly** [comment]
@RobertaJHahn Can we keep this ticket open so we can track the progress on this issue?

**Comment by RobertaJHahn** [comment]
@yellowdragonfly We have a dependency on decisions made by the translation team.  Since we don't have control over their schedule or priorities, it might be better if you work directly with them.  Providing input of the business impact could influence their schedule.  We will schedule the work to implement the the new file once it is available.

**Comment by RobertaJHahn** [comment]
@yellowdragonfly The current contact on the translations team is @matias defabio
