### ISSUE TITLE
[Masthead]: React - Custom data option not being displayed properly on storybook

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#4533]
## Detailed description

> Describe in detail the issue you're having.

When toggling the navigation data knob on the Masthead or DotcomShell storybook, the custom data is not appearing correctly. There should be subnav links displaying. The issue seems to be with storybook, maybe the `select` storybook knob?

When setting the custom data as default option in the storybook file, it renders as expected but once user toggles back from "default" to "custom", the custom data renders without the subnav links.

![Masthead3.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/4726fa9f-030d-434a-bd51-173d94a9426f)

**Comment by RobertaJHahn** [comment]
Solution is to create a new MH story.
