### ISSUE TITLE
React: Masthead - Issues with menu options on iPhone Voice over

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4540]
## Detailed description

Issue: 
A. In VO iPhone with Safari, the mentioned menus are announced as "Menuitem" without any label.
B. Upon activation of the level 0 menus, Level 1 menus are displayed visually but screen reader does not identify them. Screen reader identifies only Level 0 Menus.

**Comment by RobertaJHahn** [comment]
Dup of issue (#4526)  Closing.
