### ISSUE TITLE
Web Component: Card component - Pictogram enhancement

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4576]
This epic contains functional and design links that define the scope of the deliverable.  This epic also includes links to all of the work required to deliver the component.

#### Additional Information

-  Corresponding React epic (#4448)
- This version will be limited in scope, as additional features are being researched by the Reboot designers.  The additional changes are managed under epic (#4093), but that work is not included.  Scope:  Pictogram is being added to the bottom left of the card.
- [Design Box folder](https://ibm.ent.box.com/folder/125211274776?s=ykv2ukr3twyfx2nrro3rn7ge4iqoz48x)

**Comment by photodow** [comment]
Functional specs updated

https://ibm.ent.box.com/file/749150538784

**Comment by RobertaJHahn** [comment]
@photodow You have not updated the Change Log at the end of the document so that the engineers can easily understand the updates.  Could you update the change log.  Thanks.

**Comment by photodow** [comment]
@RobertaJHahn thanks for bringing to my attention. I did make the update, but somehow it got overridden with a previous version. Anyway I reverted it, and it should be back to normal.

https://ibm.ent.box.com/file/749150538784
