### ISSUE TITLE
Masthead Search click event enhancement

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon-for-ibm-dotcom#4599]
Currently the event fired when user activates the search from masthead is an info event only.
We need a way to prevent the default action to happen, something like normal events have
e.stopPropagation or e.preventDefault
or simply if the event hook function returns True, it would mean the search was handled and
dotcom would not go to the default ibm.com search.

**Comment by kyjak** [comment]
Adding just to be sure, the same interception should be applied to the keyboard (hitting ENTER) an any other possible submit event that launches the search.

**Comment by RobertaJHahn** [comment]
The KC team is OK with scheduling in the Jan 2021 release

**Comment by RobertaJHahn** [comment]
Functional spec updates are needed.

**Comment by ljcarot** [comment]
Feb 15 is their launch date
