### ISSUE TITLE
Git Template Crafting - General Contribution - Target Dec 18

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom#4605]
#### Objective

Our adopters need a git template to help them get started with the contribution. This task is to create a general template to help the adopters get started. We will refine the template based on the adopter feedback as we go.

#### Steps

- Craft the content for the Git template
- Review it with Roberta and Wonil
- Share with the team to get feedback
- Finalize the template
- Add the template to the repo Git template list
- [Draft issue template](#4604)

#### Acceptance criteria

- [ ] Contribution Git template is ready for the adopter to use

**Comment by JennySanchez** [comment]
@RobertaJHahn @wonilsuhibm 

I took a stab at the Contribution Git Template content below. Please take a look and let me know what do you think.

---




We thank you for your contribution to the Carbon for IBM.com. Before you get started, please make sure you visit the [Contribution section](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/overview) on our website to understand the process and find additional detail you might need to submit your contribution.

### The contribution type
Please select a category for your contribution

[ ] Documentation
[ ] Components
[ ] Patterns
[ ] Others _{{please describe}}_

### The intent
_{{A clear and concise description of what the need or user problem this new contribution is trying to meet or solve (ex. I'm always frustrated when...).}}_

### The solution
_{{A clear and concise description of what you want your contribution to happen}}_

### Contribution information and required documentations
_{{Please add any supporting or required documentations here with a short description to help us get started with your contribution inquiry (ex. Design spec document.)}}_
 - For Documentation contribution, please visit the [Documentation contribution website page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributions/documentation) for detail on what information you need to provide.
 - For Components contribution, please visit the [Components contribution website page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/components) for detail on what information you need to provide.
 - For Patterns contribution, please visit the[ Patterns contribution website page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/patterns) for detail on what information you need to provide.

**Comment by wonilsuhibm** [comment]
@JennySanchez Thank you. This looks great. Some small editorial suggestions around simplifying condensing.

---

Thank you for contributing to Carbon for IBM.com. Before you submit your contribution, please visit the Contribution section on our website to understand the process and requirements.

### Contribution type

Please select one:

[ ] Documentation
[ ] Components
[ ] Patterns
[ ] Others {{please describe}}

### Intent
{{A clear and concise description of what the need or user problem this new contribution is trying to meet or solve (ex. I'm always frustrated when...).}}

### Solution
{{A clear and concise description of what you want your contribution to happen}}

### Contribution information and required documentations
{{Please add any supporting or required documentations here with a short description to help us get started with your contribution inquiry (ex. Design spec document.)}}

- For Documentation contribution, please visit the Documentation contribution website page for detail on what information you need to provide.
- For Components contribution, please visit the Components contribution website page for detail on what information you need to provide.
- For Patterns contribution, please visit the Patterns contribution website page for detail on what information you need to provide.

**Comment by RobertaJHahn** [comment]
@JennySanchez We sometimes have trouble figuring out who submitted the request and what organization they are from.  The open source Github information does not tell us that information.

---

Thank you for contributing to Carbon for IBM.com. Before you submit your contribution, please visit the Contribution section on our website to understand the process and requirements.

### Your information
Name:  {{First and last name}}
Internet Email Address: 
IBM Organization or Company name:   

### Contribution type

Please select one:

[ ] Documentation
[ ] Components
[ ] Patterns
[ ] Others {{please describe}}

### Intent
{{A clear and concise description of what the need or user problem this new contribution is trying to meet or solve (ex. I'm always frustrated when...).}}

### Solution
{{A clear and concise description of what you want your contribution to happen}}

### Contribution information and required documentations
{{Please add any supporting or required documentations here with a short description to help us get started with your contribution inquiry (ex. Design spec document.)}}

- For Documentation contribution, please visit the Documentation contribution website page for detail on what information you need to provide.
- For Components contribution, please visit the Components contribution website page for detail on what information you need to provide.
- For Patterns contribution, please visit the Patterns contribution website page for detail on what information you need to provide.

**Comment by JennySanchez** [comment]
Thank you both for the edits. This looks good. I think we are ready to add the template to the collection. @RobertaJHahn Is Jeff the person we need to reach out to to add this Git template to our [repo](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/new/choose)?

### Contribution Request 💓

Thank you for contributing to Carbon for IBM.com. Before you submit your contribution, please visit the [Contribution section](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/overview/) on our website to understand the process and requirements.
Your information

**Name:** {{First and last name}}
**Internet Email Address:**
**IBM Organization or Company name:**

**Contribution type (please select one):**

[ ] Documentation
[ ] Components
[ ] Patterns
[ ] Others {{please describe}}

### Intent

{{A clear and concise description of what the need or user problem this new contribution is trying to meet or solve (ex. I'm always frustrated when...).}}

### Solution

{{A clear and concise description of what you want your contribution to happen}}
Contribution information and required documentations

{{Please add any supporting or required documentations here with a short description to help us get started with your contribution inquiry (ex. Design spec document.)}}

- For Documentation contribution, please visit the [Documentation contribution website page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributions/documentation/) for detail on what information you need to provide.
- For Components contribution, please visit the [Components contribution website page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/components) for detail on what information you need to provide.
- For Patterns contribution, please visit the [Patterns contribution website page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/patterns) for detail on what information you need to provide.

**Comment by JennySanchez** [comment]
@jeffchew Can you help add the template above to the collection (see screenshot below)? Let me know if you would like me to open a dev task issue for it? Maybe for sprint 21-01? 🙏🙏🙏 Thank you, thank you, thank you!

For the description maybe...
"Contribute things large and small—of code, design, ideas, and guidance."

![Screen Shot 2020-12-15 at 7.55.45 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/594bca0b-2d73-41f9-80bc-9f8330f08fc9)

**Comment by JennySanchez** [comment]
Talked to @jeffchew and he will add the template to the repo. 
@RobertaJHahn Added him to the task issue as agreed during the stand-up today.

**Comment by jeffchew** [comment]
As mentioned offline, we cannot request for name/email as those are PII data. Replacing with the following:

```
Reach out to us on Slack at #carbon-for-ibm-dotcom and provide us the link to this contribution request issue.
```

**Comment by JennySanchez** [comment]
`Updated template`

## Contribution Request 💓

Thank you for contributing to Carbon for IBM.com. Before you submit your contribution, please visit the [Contribution section](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/overview/) on our website to understand the process and requirements.

### Contribution type (please select one):

[ ] Documentation
[ ] Components
[ ] Patterns
[ ] Others {{please describe}}

### Intent

{{A clear and concise description of what the need or user problem this new contribution is trying to meet or solve (ex. I'm always frustrated when...).}}

### Solution

{{A clear and concise description of what you want your contribution to happen}}
Contribution information and required documentations

{{Please add any supporting or required documentations here with a short description to help us get started with your contribution inquiry (ex. Design spec document.)}}

- For Documentation contribution, please visit the [Documentation contribution website page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributions/documentation/) for detail on what information you need to provide.
- For Components contribution, please visit the [Components contribution website page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/components) for detail on what information you need to provide.
- For Patterns contribution, please visit the [Patterns contribution website page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/patterns) for detail on what information you need to provide.

**Comment by JennySanchez** [comment]
Git template added to the collection and can be viewed [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/new/choose).

![Screen Shot 2020-12-18 at 2.17.19 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/b4d9e425-abdb-4957-bda2-082c63811b5c)
