### ISSUE TITLE
Web component: Content block cards, arrow icon on the CTA is not aligned as per specs.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4610]
## Detailed description

Issue:
1. Arrow icon on the CTA is not aligned as per specs.
2. On iPad, arrow icon on the CTA is displayed as text color instead of link

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/dee66383-9be0-42ed-bad6-a480e155ba0c)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/e4c9e0c0-88ee-4eb4-8aa7-fd25b95f1594)

**Comment by asudoh** [comment]
#4662 addresses this issue by using `<dds-card-cta-footer>` to surround the footer icon.
