### ISSUE TITLE
Carbon v10.25.0 style bug: checkbox

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#4622]
## Detailed description
This bug is scheduled in the Jan 2021 release.

It seems that some of our expressive components are having positioning and spacing issues after applying Carbon v10.25.0. The problems are seen here:

https://percy.io/538fc19a/Carbon-Expressive-Theme/builds/7956640

For the checkbox component seen here:

<img width="1933" alt="Screen Shot 2020-12-03 at 2 13 58 PM" src="https://user-images.githubusercontent.com/30183447/101076975-1f251580-3572-11eb-8f18-72799bda32c7.png">

The label needs to be higher per the [design specs](https://ibm.box.com/s/g3hgag5womogmzxa35kd3zv3icbhnq6s)

**Comment by wonilsuhibm** [comment]
<img width="1933" alt="Screen Shot 2020-12-03 at 2 13 58 PM" src="https://user-images.githubusercontent.com/30183447/101076975-1f251580-3572-11eb-8f18-72799bda32c7.png">

**Comment by asudoh** [comment]
Seems to have been caused by carbon-design-system/carbon#7373, and seems intentional.

**Comment by RobertaJHahn** [comment]
Fix must be made in the Expressive Theme
