### ISSUE TITLE
Carbon v10.25.0 style bug: select

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#4623]
## Detailed description

It seems that some of our expressive components are having positioning and spacing issues after applying Carbon v10.25.0. The problems are seen here:

https://percy.io/538fc19a/Carbon-Expressive-Theme/builds/7956640

For the select component seen here:

<img width="1986" alt="Screen Shot 2020-12-03 at 2 19 38 PM" src="https://user-images.githubusercontent.com/30183447/101077474-e33e8000-3572-11eb-89d2-02800d777d94.png">

The select component is stretching to full span.

**Comment by wonilsuhibm** [comment]
<img width="1986" alt="Screen Shot 2020-12-03 at 2 19 38 PM" src="https://user-images.githubusercontent.com/30183447/101077474-e33e8000-3572-11eb-89d2-02800d777d94.png">

**Comment by asudoh** [comment]
Seems to have been caused by carbon-design-system/carbon#7267, and seems intentional.

**Comment by RobertaJHahn** [comment]
Working as designed.
