### ISSUE TITLE
Web component: Locale modal - arrow icon are on wrong side of the card

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4628]
## Detailed description

Issue: 
1. Arrow icon on the cards are on right must be on left side
2. Country name (Americas, Asia pacific, Europe & middle east)  on the cards do not have spacing on the top

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/fb418eda-5413-490e-8b3f-77bbff972cf4)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/afc18d0f-51ec-4226-b357-d86a19da06bd)

**Comment by ljcarot** [comment]
@Praveen-sr thus is locale modal, not microfooter

**Comment by kennylam** [comment]
@Praveen-sr @RobertaJHahn This issue can be reviewed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4637
