### ISSUE TITLE
Web component / React - Locale selector, on click of "Select geographic area" whole page refreshes

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4646]
## Detailed description

Issue: Locale selector, on click of "Select geographic area" whole page refreshes

Note: This issue is on both react and web components. 

## Additional information

![LocalSel.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/74015e33-7aa2-4ca3-93d8-6073702a793d)

**Comment by asudoh** [comment]
#4647 addresses this issue (thanks @IgnacioBecerra!). Checked the staging site of React as well as one of Web Components and I see the bug is not there.
