### ISSUE TITLE
Box folder clean up

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#4648]
### Objectives

This epic is to look at how we are using Box folders and clean up, merge, and set up for 2021.

##### The three folders
We have three Box folders that we have accumulated.
- `Carbon for IBM.com`
- `IBM Digital Design`
- `IBM Digital Design squad`

And we are using these three folders in an inconsistent way. Let's take a look at whether we need all three, and if we do, let's try to define what each folder does and does not.

##### Layout components
Since the restructuring of the UI components and layout components, we have the layout components stored separately. Also within layout components folder, we have block, section, and subpattern folder structures. Let's look at how we can merge or restructure these.

One thought from Wonil: I still think that there is a great value in separating UI components from layout components.

##### Each component folder structure
We agreed on a subfolder structure for each component to be one way, but it seems that we identified additional needs and the need to update our model.

**Comment by oliviaflory** [comment]
I'd suggest a parent folder of `Components` with separate folders for `UI components` and `Layout components`

**Comment by JennySanchez** [comment]
Agreed with @oliviaflory, especially the list of the Components are getting longer and longer.

**Comment by JennySanchez** [comment]
@shixiedesign FYI on this Epic.
