### ISSUE TITLE
React stand alone:  Mega Menu MVP enhancement to accommodate HC + AI updates Visual QA testing 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4655]
_**This development work is also scheduled for the Web Component version. The Web Component development is managed under epic (#4322)**_

#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Mega menu HC + AI enhancement`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- This Mega Menu version does not include the animation features:
      1. Back button doesn't have motion
      2. Motion forward overlaps and hides previous behind.
- Motion feature can be seen in this folder
      - [Motion folder for mega menu](https://ibm.box.com/s/bqn9xggrys3gcyuy0q0ubmf0w1b3gwvg)
- Dev Issue (#4653)
-  - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- See comment posted by engineer when development is finished for the test URL.

 #### Tasks
Ensure the  `Mega menu HC + AI enhancement` component has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by ltitle** [comment]
@RobertaJHahn @jyoon25 Roberta, when will the team be ready for design QA on this?

**Comment by RobertaJHahn** [comment]
@ltitle I reported the schedule for this work in the Reboot Interlock meeting Box Note so that you could plan the staffing. (See the Jan 5 FYI's)  https://ibm.ent.box.com/notes/751503882704?s=4c697jn6p8f3iuovc41t65k0mxkiacg1

You can also know the schedule by looking at the Milestone. This work is scheduled in the third sprint (Feb 1 - 12).

cc:  @jyoon25

**Comment by annawen1** [comment]
@jyoon25 the Megamenu updates for React can be viewed here:
https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--with-custom-navigation

**Comment by jyoon25** [comment]
@annawen1 Here's QA for react. Let me know if you have any comments. Thank you!
QA PDF link: https://ibm.box.com/s/k57zbe7l0ndgq9pitbskkbebmdrohlxb
Original design abstract link: https://share.goabstract.com/6f02a9ae-517f-45b8-b76f-b77273b9a4ad

<img width="374" alt="image" src="https://user-images.githubusercontent.com/67110948/107527840-33dfe400-6b87-11eb-91be-9b30258cda4a.png">

**Comment by annawen1** [comment]
@jyoon25 For the `sm` and `md` breakpoints, you have to click on the "Products & Solutions" menu item to see the submenu - that will match the designs...

<img width="598" alt="Screen Shot 2021-02-10 at 10 23 40 AM" src="https://user-images.githubusercontent.com/54281166/107531010-6c34f180-6b8a-11eb-81f9-d96b9278cac1.png">

**Comment by jyoon25** [comment]
@annawen1  
Can you update design based on original design for 672px and 320px breakpoints? 
I created design QA issue here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5136
Thank you!

<img width="729" alt="image" src="https://user-images.githubusercontent.com/67110948/107532812-47da1480-6b8c-11eb-97f4-d7b366b97f1c.png">

<img width="354" alt="image" src="https://user-images.githubusercontent.com/67110948/107532788-40b30680-6b8c-11eb-9ba9-931768ebbc89.png">

**Comment by jyoon25** [comment]
@annawen1  Thank you! I will remove tablet, mobile visual QA. 
Still have line visual QA part for desktop version. Can you work on it?  Thanks!
I have visual QA here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5136
