### ISSUE TITLE
React stand alone: Mega Menu enhancement to accommodate HC + AI updates Visual QA testing Prod QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4656]
_**This development work is also scheduled for the Web Component version. The Web Component development is managed under epic (#4322)**_

#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `Mega menu HC + AI enhancement`

> I need to:
have a version of the pattern or component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1, 13.3 and 14
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- **See the Epic for the Design and Functional specs information**
 - Dev issue (#4653) 
- ** Once development is finished the updated code is available on the [Canary URL](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/overview-getting-started--page) for testing.**

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Component is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by shixiedesign** [comment]
Designs & spec: https://ibm.box.com/s/kie61ijq4ggvdhi6awjklp09a5ro4sms
Boxfolder: https://ibm.ent.box.com/folder/118692148518?s=lcjcmdoaz2hnj6gejx7ilafhrvje4k68

Example: `md` breakpoint design:
![image](https://user-images.githubusercontent.com/15144993/101505284-2ff2d400-3942-11eb-84a1-41b040a99927.png)

**Comment by annawen1** [comment]
@Praveen-sr development for this has been completed. You can view here under the `Custom Navigation` story:
https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--with-custom-navigation

**Comment by RobertaJHahn** [comment]
Prod QA testing started

**Comment by RobertaJHahn** [comment]
Accessibility testing remains.  Testing should be finished by tomorrow.

**Comment by RobertaJHahn** [comment]
Accessibility testing is finished.  Closing.
