### ISSUE TITLE
Mega Menu engineering support for Translation Data changes to accommodate HC + AI updates

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4672]
#### User Story

> As a `[user role below]`:
DDS engineer

> I need to:
identify the needed changes needed and work with Miroslav Mahdon to provide the modified file

> so that I can:
implement the new design with the globalized version of the page

#### Additional information

 - [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/118692148518?s=lcjcmdoaz2hnj6gejx7ilafhrvje4k68)
- [Sketch File](https://ibm.ent.box.com/file/750670881989)
- [Design pdf](https://ibm.ent.box.com/file/750672262864?s=kie61ijq4ggvdhi6awjklp09a5ro4sms)
- Data changes are additive.  
- Updates are made in the [Translation repo](https://github.ibm.com/webstandards/ibm-dotcom-translations)

#### Acceptance criteria
 - [x] Updates to the translation data file have been identified and provided to Miroslav Mahdon

**Comment by annawen1** [comment]
My proposed data structure changes are pretty minimal as we can use existing fields for the highlighted section title (ex: "The essentials") and the category group descriptions

Only addition here would be the `highlightedLink` boolean field which would render the category links with icon or as plain text link

```
 "menuSections": [
          {
            ---> "heading": "The essentials",
            "menuItems": [
              {
                "title": "Top products & platforms",
                "titleEnglish": "Top products & platforms",
                "url": "https://www.ibm.com/products?lnk=hpmps_bupr",
                "highlighted": true,
                "megapanelContent": {
                  "headingTitle": "Top products & platforms",
                  "headingUrl": "https://www.ibm.com/products?lnk=hpmps_bupr",
                  ---> "description": "Blend cloud and on-premises resources for flexibility and balance",
                  "quickLinks": {
                    "title": "",
                    "links": [
                      {
                        "title": "Db2",
                        "titleEnglish": "Db2",
                        ---> "highlightedLink": true,
                        "url": "https://www.ibm.com/analytics/db2?lnk=hpmps_bupr"
                      },

                      ...
                }
              },

              ...
            ]
          }
 ]
```

CC @jeffchew @kennylam

**Comment by kennylam** [comment]
@annawen1 are `Top products & platforms` and `Artificial intelligence` both under `The essentials`?

**Comment by annawen1** [comment]
@kennylam Ideally I would change it so the data content would match the design we have but it would affect the ibm homepage megamenu content so goal for right now is to just add data/data fields where it is needed for us to start making updates to our megamenu code without effecting the current data for US homepage

**Comment by annawen1** [comment]
I have created a card on the translation team's trello board and communicated those changes to Matias Difabio and Miroslav Mahdon
