### ISSUE TITLE
Carbon v10.25.0 style bug: pagination

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#4681]
## Detailed description

It seems that some of our expressive components are having positioning and spacing issues after applying Carbon v10.25.0. The problems are seen here:

https://percy.io/538fc19a/Carbon-Expressive-Theme/builds/7956640/view/452902015/1280?mode=diff&browser=chrome&snapshot=452902015

I believe the desired padding is 16px as seen on the [component page](https://www.carbondesignsystem.com/components/pagination/style#structure

<img width="1385" alt="Screen Shot 2020-12-09 at 8 17 46 AM" src="https://user-images.githubusercontent.com/30183447/101634843-3d1dca80-39f7-11eb-95aa-d1f30526025e.png">

### Additional information
- Wonil spoke to Carbon core team and confirmed that this is a bug in the core system. Here is the bug report in the core codebase: https://github.com/carbon-design-system/carbon/issues/7424
- The effort for this issue is to monitor when Carbon makes the change and do what is needed to make the change available in the Carbon for ibm.com component(s).

**Comment by wonilsuhibm** [comment]
This has been fixed in the Carbon core: 

https://deploy-preview-7427--carbon-components-react.netlify.app/?path=/story/pagination--multiple-pagination-components

**Comment by jeffchew** [comment]
PR link as a reference: https://github.com/carbon-design-system/carbon/pull/7427

There's no indication on what release this will be in.

**Comment by IgnacioBecerra** [comment]
Looks like the fix was included in the [v10.26.0 release](https://github.com/carbon-design-system/carbon/releases/tag/v10.26.0) (under bug fixes). Moving to Done pipeline.

cc: @RobertaJHahn @jeffchew
