### ISSUE TITLE
[Leaving ibm] Update label text

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#4686]
I think it looks like you're pulling in the correct data, but it looks like we need to make a data update to the [translation api](https://www.ibm.com/common/v18/js/data/jsononly/usen.json) to reflect the design.

———
Here is what I'm seeing 
<img src="https://user-images.githubusercontent.com/3793636/101697403-62cdc280-3a3d-11eb-9022-047ca5a80df4.png" width="300px" />
http://ibmdotcom-web-components.mybluemix.net/iframe.html?id=components-leaving-ibm--default

———
Here is what it should be...
<img src="https://user-images.githubusercontent.com/3793636/101697621-c3f59600-3a3d-11eb-9961-20ad852c8ac9.png" width="300px" />
> 👀 see design specs in additional information

## Additional information

- Leaving ibm [[box](https://ibm.box.com/s/g79wdwdj0syjcfkdlgu5rpwe3zp9s37w)]
- [translation api](https://www.ibm.com/common/v18/js/data/jsononly/usen.json)

**Comment by RobertaJHahn** [comment]
Miroslav and Ivan will work in the translations.  Mira has opened an issue on their Trello board to update the us-en version of the file.  No more for DDS to do.
