### ISSUE TITLE
[Button] typography has wrong line-height

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#4687]
After looking at the Leaving IBM, it looks like our button in at least web components (react appears to be correct) isn't aligned with the correct type token.

———
See here...

<img src="https://user-images.githubusercontent.com/3793636/101695306-fb624380-3a39-11eb-8ac1-be8d738a5461.png" width="300px" />

http://ibmdotcom-web-components.mybluemix.net/?path=/story/components-button--default

———
Here is what it should be...

productive
<img src="https://user-images.githubusercontent.com/3793636/101695778-b7bc0980-3a3a-11eb-9e65-bb13b9dd1214.png" width="300px" />

https://react.carbondesignsystem.com/?path=/story/button--default

expressive (if memory serves me we overrode it to this?)
<img src="https://user-images.githubusercontent.com/3793636/101695595-74fa3180-3a3a-11eb-9112-2659e462e645.png" width="300px" />

https://carbon-expressive.mybluemix.net/?path=/story/buttons--default

## Steps to reproduce the issue

Used [Carbon devtools](https://ibm.biz/carbon-devtools-chrome) typography spec.

## Additional information

- Leaving ibm [[box](https://ibm.box.com/s/g79wdwdj0syjcfkdlgu5rpwe3zp9s37w)]

**Comment by annawen1** [comment]
Hi @photodow, I'm looking on https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-button--default and `line-height` does seem to match the expected `line-height: 22px` from https://carbon-expressive.mybluemix.net/?path=/story/buttons--default

Screenshot from the web-components button:
![Uploading Screen Shot 2020-12-14 at 4.46.03 PM.png…]()

Could it possibly be the devtools is off?

**Comment by photodow** [comment]
Hmm... Always a possibility, but I'm seeing it in computed as well.

![image](https://user-images.githubusercontent.com/3793636/102228705-9f237780-3eb0-11eb-9997-2fb416cfc62a.png)

**Comment by annawen1** [comment]
@photodow hmm when I see the computed value for the `<button>` specifically in the shadow dom, it does show 22px

<img width="1564" alt="Screen Shot 2020-12-16 at 6 01 59 PM" src="https://user-images.githubusercontent.com/54281166/102417010-e4d36380-3fc8-11eb-8768-29c94637fc95.png">
