### ISSUE TITLE
Change profile endpoint on Carbon Masthead for signed in state

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/carbon-for-ibm-dotcom#4701]
**This work must be done by the end of Jan 2021**

IDaaS is being replaced with new ISV.  This change will impact the endpoint that is currently part of the Profile Icon on the masthead which displays if a user is signed out or signed in.

**Describe the solution you'd like** 
Rick McCarty has provided the solution here: 
With respect to the status API calls made by the masthead, these will need some changes  for ISV.

Currently, if the current page is under www.ibm.com, the masthead makes a request to the following endpoint:

https://idaas.iam.ibm.com/v1/mgmt/idaas/user/status/

If the page is under another domain, for example myibm.ibm.com, etc, the call is a bit different - it adds a callback parameter for JSONP to avoid CORS issues:

https://idaas.iam.ibm.com/v1/mgmt/idaas/user/status/?callback=__jp1

With the change to ISV, the new endpoint will be:

https://login.ibm.com/v1/mgmt/idaas/user/status/

Also, ISV will no longer support the "callback=" parameter, meaning that JSONP can no longer be used to get around CORS issues. Instead, we will have to include a more comprehensive list of domains in our ISV configuration to handle CORS.

Original request is here: https://jsw.ibm.com/browse/IRFC-8

**Comment by RobertaJHahn** [comment]
@ljcarot Can you let us know when this ISV change is being made and when our change is required?  Thanks.

**Comment by ljcarot** [comment]
This change is needed now.  The Carbon change should be in January release and v18 can be any time before end of January.  It needs to be done in advance of ISV cut over tentatively set for late January.

**Comment by jeffchew** [comment]
@RobertaJHahn can you add to the next engineering refinement meeting to size? I also will need to get back to Rick McCarty on a whitelist for lower environment testing.

**Comment by RobertaJHahn** [comment]
@jeffchew Done

**Comment by annawen1** [comment]
@jeffchew has provided Ricky with a list of domains we need whitelisted. Waiting for those domains to be whitelisted so we can test the new endpoint locally.
