### ISSUE TITLE
[Research] Run performance tests between React and Web Components

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#4708]
#### User Story

> As a `[user role below]`:
IBM.com offering manager

> I need to:
see page speed test results for Carbon for IBM.com 

> so that I can:
see page load comparisons between Carbon for IBM.com React and Web Components

#### Additional information

 - React can use the NextJS template: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template
 - Web Components can use the application test: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-test
- Test pages should include the dotcom shell, with very light content
- Pages should be hosted in a production-ready environment, using GZIP and high availability (e.g. ibm.com/testing)

#### Acceptance criteria
 - [ ] Create test pages Carbon for IBM.com React, and Carbon for IBM.com Web Components
 - [ ] Run page speed tests in Google PageSpeed Insights (https://developers.google.com/speed/pagespeed/insights/) or WebPageTest (https://www.webpagetest.org/)

**Comment by JennySanchez** [comment]
@jeffchew @kennylam Is this task still relevant?

**Comment by RobertaJHahn** [comment]
Performance metrics are needed.  Issues will be created to identify the metrics needed in 2022.
