### ISSUE TITLE
Web Component: Add Masthead custom L0 navigation - Group 5

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4710]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `Masthead custom L0 navigation`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic for the Design and Functional specs information**
- [React Storybook link](https://ibmdotcom-react.mybluemix.net/?path=/story/components-masthead--default)
- [Visual Designs & Design Specs Box folder link](https://ibm.ent.box.com/folder/59063660753?s=mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1)
- Prod QA testing issue (#4713)

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by asudoh** [comment]
The Web Components version supports custom L0 navigation from the beginning. The instruction/example is available at [here](https://ibm.biz/BdfBFd).
