### ISSUE TITLE
Resource card set up on the IBM.com Web Standards website homepage 

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom#4727]
## Detailed description

> The Resource card set up on the [IBM.com Web Standards website](https://www.ibm.com/standards/web/) homepage has a weird white line around the card.

![Artboard](https://user-images.githubusercontent.com/45213839/102149781-e0764180-3e34-11eb-974f-d01d13367d25.jpg)

> This is a bug.

> This issue is related to the resource card component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The resource card on the dark theme should have a dark line around it and looks like the resource card group on the Carbon website. See screenshot below.

> I looked at the resource card group in Firefox, Chrome, and Safari and they all have the weird white line showing.

## Steps to reproduce the issue

1. Take a look at the [Carbon website](https://www.carbondesignsystem.com/) to find out what is the correct setup
2. Update the Resource card group set up on the IBM.com Web Standards website.
3. Have a DDS designer take a look at the update - Jenny would love to help.
4. If no further changes are needed, close the task issue - yay!

## Additional information

`Currently on the IBM.com Web Standards website`
![Screen Shot 2020-12-14 at 4 59 10 PM](https://user-images.githubusercontent.com/45213839/102149829-fe43a680-3e34-11eb-98aa-8430d4aaaf47.png)

`What is supposed to look like`
![Screen Shot 2020-12-14 at 5 09 09 PM](https://user-images.githubusercontent.com/45213839/102149824-f7b52f00-3e34-11eb-937c-8997d6d823a7.png)

**Comment by RobertaJHahn** [comment]
This page is going through a redesign shortly.  This issue will not be fixed now.
