### ISSUE TITLE
Web component: Content block simple - link list, hyphen and bullets are not visible on Tab & mobile.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4733]
## Detailed description

Issue: Content block simple - link list, hyphen and bullets are not visible on Tab & mobile.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/7da44d2f-68f3-4fb6-8599-ddedb1ad81d7)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/dd4acc18-6d62-4f75-8e5c-ddcba6392f94)

**Comment by guilhermelMoraes** [comment]
@Praveen-sr actually, I think that @asudoh's PR right above fixed this bug. All looking good:
<img width="773" alt="Screen Shot 2021-01-04 at 15 52 13" src="https://user-images.githubusercontent.com/42848561/103568946-3de63700-4ea5-11eb-8c83-fe1b35ad23ad.png">

<img width="530" alt="Screen Shot 2021-01-04 at 15 52 21" src="https://user-images.githubusercontent.com/42848561/103569054-640bd700-4ea5-11eb-8117-ca113b89a168.png">

**Comment by asudoh** [comment]
Thanks @guilhermelMoraes for verifying! Is it possible for you to review the PR, too? Thanks!
