### ISSUE TITLE
Lots and lots of duplicated code

### ISSUE THREAD

**Issue by skycryer** [carbon-design-system/carbon-for-ibm-dotcom#4736]
## Detailed description

There is a lot of duplicated code on the css files when using from npm over https://www.npmjs.com/package/@carbon/ibmdotcom-styles

Version 1.13.0

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I do want to have css not been repeated to save filesize and performance

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM CMS -> final Release ~ March 2021

## Steps to reproduce the issue

If you search for example for 

body {
  font-weight: 400

in css

or body{font-weight:400 

in minified css

you will find 418 entries.

## Additional information

<img width="380" alt="Screenshot 2020-12-17 at 10 57 36" src="https://user-images.githubusercontent.com/3725699/102476595-9327e900-405b-11eb-9931-3606ef687ede.png">
<img width="389" alt="Screenshot 2020-12-17 at 10 56 17" src="https://user-images.githubusercontent.com/3725699/102476611-96bb7000-405b-11eb-8c27-7fa321e0fac0.png">

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu Let's work with this adopter regarding their implementation.

**Comment by RobertaJHahn** [comment]
Can be closed.  Kenny will find the PR and move to Done.

**Comment by kennylam** [comment]
This has been addressed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/2342 and https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/2581
