### ISSUE TITLE
Web component: Content block simple - With tab/shift tab, there is no visual focus on 'Play button '

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4738]
## Detailed description

Issue: With tab/shift tab we are able to reach to the elements but there is no visual focus at all.

Expected:
Provide thick and strong visual focus
1. If, Visual Focus Indicator with 3 CSS px stroke then provide a sufficient contrast that is equal to 3:1. 
2. Visual focus indicator for a link that is a 1 CSS px then provide a sufficient contrast greater than 4.5:1

Note: This issue does exist on the react server as well.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/3e1a41d2-7c2d-4b64-a3a2-6c1d745d6ed0)

**Comment by kennylam** [comment]
@Praveen-sr @wonilsuhibm Since the entire card is the link, is there a need to outline the play icon?

**Comment by kennylam** [comment]
Confirmed with @wonilsuhibm that the play icon should not have its own focus state. The focus state would exist on either the inline video or card link with video.

cc: @RobertaJHahn
