### ISSUE TITLE
IBM.com Web Standard Lead space update - 2021

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom#4747]
👉  **Note:** This task might need to be turned into an EPIC. 👈

### Objectives

IBM.com Web Standard website is updated with the Checklist design and no left negation approach in December 2020. During the design review, Mike and I agreed on the Lead space can be updated (an illustration in either ISO, Flat, or Line style rather than an extra-large UI icon) to represent IDL look and feel better and improve the first impression/experience for adopters.

### Reference for ideation shared by Mike

https://www.ibm.com/cloud/redhat
[https://app.zenhub.com/files/193129061/c21db315-9840-4a05-9858-b8d25f84494c/download](https://app.zenhub.com/files/193129061/c21db315-9840-4a05-9858-b8d25f84494c/download)

![image (2).png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/749b3f18-aa63-43fa-b2c5-cb75e0180048)![Screen Shot 2020-12-15 at 1.32.16 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/659890b3-9a06-4a66-929d-3ea081787b90)![Screen Shot 2020-12-15 at 1.44.25 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/93422d5d-f1b2-4770-87e4-68c807f18dd4)![Screen Shot 2020-12-15 at 1.47.17 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/16a67743-cd25-4ef6-bef3-522225eb25b4)

**Comment by JennySanchez** [comment]
**FYI** - @wonilsuhibm @jeffchew @ljcarot

**Comment by ljcarot** [comment]
@JennySanchez Are those images being proposed as replacements for the current leadspace on the standards site?

**Comment by JennySanchez** [comment]
@ljcarot No. They are visual references/examples from Mike. Wonil is going to work on the image.

**Comment by shixiedesign** [comment]
Hey @JennySanchez is this a requirement from Mike? Considering our work load, we might de-prioritize it and move it to back log. We won't have time to make a new illustration right now. Thoughts? @ljcarot

**Comment by JennySanchez** [comment]
@shixiedesign I agreed with moving it to the backlog. 

FYI: The only reason it has a sprint assigned to it for Sprint 20-04 is bc Wonil mentioned he might be able to work on it or have an existing illustration to work from, so Roberta set the milestone and assigned it to Wonil.

**Comment by shixiedesign** [comment]
Looking into content organization first. We will likely need new illustration later, if needed.
