### ISSUE TITLE
Apply expressive tokens to Carbon for IBM.com component specs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#4750]
#### User Story

> As a `[user role below]`:

DDS designer
> I need to:

update all Carbon for IBM.com components that use productive tokens to use expressive theme tokens 

> so that :

components use one type scale and are more consistent for our adopters

#### Additional information
Here is a list of the components that need updating and which token they should use with the expressive theme applied:

- [ ] **Leaving IBM** label above link --> `$label-01`

- [ ] **callout with media** image caption  --> `$caption-01`
- [ ] **Card** card eyebrow   --> `$label-01`
- [ ] **Card** video duration --> check what type style is being applied, currently seems like it should be 16px
- [ ] **image with caption** image caption --> `$caption-01`
- [ ] **locale modal** modal header label (top right) --> `$label-01`
- [ ] **locale modal** Search heading (this page is available in...) --> `$heading-02`

- [ ] **content item horizontal** content item horizontal item eyebrow --> `$label-01`
- [ ] **video player** video player video caption --> `$caption-01`

- [ ] **logo grid** check if card link should be semibold?  --> `$heading-01 or 02`

**Note**: we will not be removing the productive mixin from the mega menu, decided in #4341 

#### Acceptance criteria
 - [ ] Productive tokens are removed from all component specs listed above
 - [ ] Expressive tokens listed above are applied 
 - [ ] Designer (Olivia) reviewed all changes

**Comment by RobertaJHahn** [comment]
Done.  Closing
