### ISSUE TITLE
Carbon for IBM.com web link does not work on IBM Web standards page

### ISSUE THREAD

**Issue by AnimatIan** [carbon-design-system/carbon-for-ibm-dotcom#4757]
## Detailed description

> Describe in detail the issue you're having.

On the IBM Web standards page, https://www.ibm.com/standards/web/, there is a Resources tile for the link "Carbon for IBM.com": https://www.ibm.com/standards/web/carbon-for-ibm-dotcom. When clicked that returns a 404 error.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Firefox, Chrome, MS Edge

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Open the IBM Web standards page, https://www.ibm.com/standards/web/, 
2. Under Resources, click the tile ["Carbon for IBM.com"](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom)

## Additional information

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment]
standard/web is going to be replaced by the end of Jan.
