### ISSUE TITLE
Partnerworld Landing & Build Page:  Limited scope Prod QA testing 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4760]
#### User Story

> As a `[user role below]`:
DDS developer creating the Partnerworld Landing Page

> I need to:
have an MVP version of the page tested for Tier 1 browsers and platforms

> so that I can:
create a high quality page 

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1, 13.3 and 14
- Browsers to be tested:  **Desktop:** Chrome, Firefox, Safari, Edge, **Mobile:** Chrome and Safari  **Tablet:** Chrome and Safari
- [Create a QA bug in this repo](https://github.ibm.com/partnerworld/partnerworld-landing/issues)
- **[The Partnerworld Landing page](http://partnerworld-landing-staging.mybluemix.net/)**
- **[The Partnerworld/build page](http://partnerworld-landing-staging.mybluemix.net/build/)**
- [Partnerworld designs](https://ibm.ent.box.com/file/753495536312)

#### Acceptance criteria
- [ ] All Tier 1 browser versions are tested
- [ ] All Tier 1 operating systems are tested
- [ ] All Tier 1 devices are tested
- [ ] Defects are recorded and retested when fixed

**Comment by guilhermelMoraes** [comment]
@Praveen-sr the Partner world landing page is ready for your testing. These are some useful links:
 - Page visual specs (please, tell me if you have access to it): https://ibm.ent.box.com/file/753495536312
 - Link for testing: http://partnerworld-landing-staging.mybluemix.net/
