### ISSUE TITLE
Web component: Carousel - Mobile view, user not able to see the cards and pagination 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4762]
## Detailed description

Issue: On Mobile view, user not able to see the cards and pagination. 
User has to scroll left and right to see the cards and pagination.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/fb762d44-3a6f-46c6-b079-766cfd6d2733)

**Comment by asudoh** [comment]
Fix is on the way (#4767). Adopters can also work this around by explicitly setting the width to `<dds-carousel>`.
