### ISSUE TITLE
Web component: Carousel pagination

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4771]
## Detailed description

Issue: Carousel - Discussion about pagination, if all the cards are displayed on the same page.

**Comment by oliviaflory** [comment]
Adding my two cents:

During the QA call the team wondered if we should suppress the pagination controls if all cards are displayed in a single view or same page and therefore there are no additional pages to scroll through, example below: 
<img width="1440" alt="Screen Shot 2020-12-23 at 11 28 23 AM" src="https://user-images.githubusercontent.com/45692622/103018041-88190100-4512-11eb-91c7-851b27e7545a.png">



One possible use case for this could be if a team wanted to use a carousel to conserve scrolling on mobile. Below I've shown an example of a Card Group with 3 cards, that stacks on mobile (left); and an example of Carousel with 3 cards in desktop with suppressed controls and controls shown on mobile.
<img width="1258" alt="Screen Shot 2020-12-23 at 11 50 34 AM" src="https://user-images.githubusercontent.com/45692622/103019860-708f4780-4515-11eb-8131-c9613dc89322.png">


**Things to consider:** 
- Would the above scenario be an experience we recommend? 
  - If so we may want to add some guidelines to the website to indicate utilizing the carousel only when the information is **not critical** for the user to read, and consider the card group as an alternative pattern. _I believe we already have something like this, but should review if we make this change_

- In addition to the pagination, we should consider how many cards we _should_ display on a page at once, see issue #4770. 

- How many minimum cards do we recommend for a carousel? Would this recommendation overrule the idea of suppressing the pagination controls?


cc @photodow would value your thoughts if you haven't seen this discussion yet 🙏
