### ISSUE TITLE
[Masthead] Masthead L1 - Issues with Menu options - DDS Consulting

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4777]
## Detailed description

On JAWS FF
Issue: 1. The options within the mentioned menus are navigable with tab/shift tab keys instead of Up/Down Arrow keys. This behavior does not 
adhere to the aria practices. 
2. Since  "Lorem ipsum dolor" is a link which takes the user to the next page, this can be given as "link" instead of "Menu"

Expected:
1. Either these menus should be made in adherence to ARIA standards. Or an accessible alternate should be given.  Below is the reference link for aria 1.1 examples. Note: We recommend the second approach.  
- [Navigation Menu bar Example | WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html)
- [Example Disclosure for Navigation Menus | WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices/examples/disclosure/disclosure-navigation.html)

2. Remove the menu related property and make it just a link

## Additional information
- [ ] Closed React Mega Menu accessibility navigation issue #4196
     - Removed the "menu" role 
- [ ] Remove the menu role for Web Components

**Engineering info:**  
     - HC engineer: @andy-blum 
     - JC Jira Ticket: https://jsw.ibm.com/browse/HC-2218
     - DDS consulting engineer:

**Comment by jeffchew** [comment]
@Praveen-sr can you retest to see if this is still an issue?

**Comment by Praveen-sr** [comment]
@jeffchew Re tested this on web component staging, the issues still persists.

**Comment by ljcarot** [comment]
@Praveen-sr Thanks for retesting.  @jeffchew should we move to Sprint 13?

**Comment by RobertaJHahn** [comment]
@ljcarot Sprint 13 is full.  Added to sprint 14 and included in the July 27 release.

**Comment by ljcarot** [comment]
Perfect, thank you!

**Comment by RobertaJHahn** [comment]
Moving back to "to be triaged`.  It is bigger than expected.  Include in the 8/30 refinement meeting agenda.

**Comment by Praveen-sr** [comment]
Ram re tested this issue on web component, the 2 issues still persists.
@RobertaJHahn @annawen1
