### ISSUE TITLE
Replace image placeholder with internal image placeholder for Storybooks

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#4778]
## Detailed description

> Describe in detail the issue you're having.

We are getting a lot of false positives in Percy image regression as a lot of times, the images fail to load in snapshot tests. For example:

https://percy.io/538fc19a/Carbon-for-IBM.com-React/builds-next/8187213/changed/465859488?browser=chrome&browser_ids=9&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=320%2C1280

Ideally, we replace this with an internal, home grown image placeholder so we can avoid these false positives.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

All Storybook components with placeholder images

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Consistent placeholder image loading

> What browser are you working in?

Percy/Browserstack

**Comment by jeffchew** [comment]
I was playing around a bit on this one, one solution I looked into is `holder.js` (https://github.com/imsky/holder). Immediately ran into an issue with dynamically regenerating the placeholder images when changing knobs, as the library is not designed to access any elements in the shadow root for re-initializing imagery.

Will have to see if there are other ways around this.

**Comment by wonilsuhibm** [comment]
Can we use images that we produced? I see Helvetica or Arial being used in the current images.

**Comment by jeffchew** [comment]
@wonilsuhibm yes, we can use our own imagery, would the design team be able to provide?

**Comment by wonilsuhibm** [comment]
@jeffchew I have these updated designs going:
![Artboard Copy 43](https://user-images.githubusercontent.com/30183447/103693717-bca3a880-4f67-11eb-9494-aa249206e39e.png)
![Artboard Copy 69](https://user-images.githubusercontent.com/30183447/103693718-bca3a880-4f67-11eb-8b73-446ef982c5e2.png)
![Artboard Copy 64](https://user-images.githubusercontent.com/30183447/103693719-bca3a880-4f67-11eb-9c9e-dbe49bf38ae9.png)
![Artboard Copy 59](https://user-images.githubusercontent.com/30183447/103693720-bca3a880-4f67-11eb-8561-0fdfb8ef59aa.png)
![Artboard Copy 54](https://user-images.githubusercontent.com/30183447/103693721-bca3a880-4f67-11eb-9917-8c7cae18f663.png)
![Artboard Copy 49](https://user-images.githubusercontent.com/30183447/103693722-bd3c3f00-4f67-11eb-884a-7f5250d6657d.png)
![Artboard Copy 38](https://user-images.githubusercontent.com/30183447/103693723-bd3c3f00-4f67-11eb-8c65-0dfd2cf42be4.png)

@JennySanchez @oliviaflory @photodow @kennylam would love to get your thoughts on these options.

**Comment by wonilsuhibm** [comment]
@jeffchew Would it be possible to have a pool of images and have it slightly more realistic representation like this:
<img width="1236" alt="Screen Shot 2021-01-05 at 4 02 44 PM" src="https://user-images.githubusercontent.com/30183447/103698622-98e46080-4f6f-11eb-9f74-990b71a31752.png">

**Comment by wonilsuhibm** [comment]
@oliviaflory @JennySanchez @photodow Here are some other color options too:
![Artboard Copy 55](https://user-images.githubusercontent.com/30183447/103698769-d77a1b00-4f6f-11eb-8a89-616b6fe41166.png)
![Artboard Copy 54](https://user-images.githubusercontent.com/30183447/103698770-d812b180-4f6f-11eb-9036-26fa4a427114.png)
![Artboard Copy 53](https://user-images.githubusercontent.com/30183447/103698771-d812b180-4f6f-11eb-8555-b66d54cfab86.png)
![Artboard Copy 52](https://user-images.githubusercontent.com/30183447/103698773-d812b180-4f6f-11eb-9f7f-c9d909202e45.png)
![Artboard Copy 51](https://user-images.githubusercontent.com/30183447/103698774-d8ab4800-4f6f-11eb-9eb2-ce87b12227eb.png)

**Comment by wonilsuhibm** [comment]
Here is the final proposal:

- A series of photograph with dark overlay + aspect ratio at the center
- 5 standard aspect ratios + lead space  size (1584 x 560)
- 6 different pixel dimensions (320px, 480px, 720px, 960px, 1312px, 1584px)

![fpo-image-example](https://user-images.githubusercontent.com/30183447/103803315-66457100-501e-11eb-914f-248d4ac19271.png)

### Files
[Source Sketch file](https://ibm.box.com/s/yhgbqza6teolk2n92bjta3rpc00shxne)

[PNG outputs](https://ibm.box.com/s/qmz9wsbxe1qhoe5aqsg4jsjm1hsu7974)
