### ISSUE TITLE
Footer does not wrap the links and creates horizontal scrollbar

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon-for-ibm-dotcom#4798]
If you go for example to german translation of DOCS https://ibmdocs-dev.mybluemix.net/de/ssw_aix_72/navigation/commands.html
and open the TOC panel and shrink the page to 1100px width for example, the items in the dotcom footer do not wrap.
I know that without the collapsed/open TOC the footer would fit, but we have a design that is taking horizontal space away from the footer. 

![image](https://user-images.githubusercontent.com/15310250/103524372-c2bd5a80-4e7d-11eb-8cfe-cd8c67c79103.png)

**Comment by RobertaJHahn** [comment]
Added this bug to the Jan 7, 2021 status update meeting agenda.

**Comment by JennySanchez** [comment]
We need to further understand the needs around the design modification of the standard dot come [Footer](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/footer). Let's discuss in the meeting scheduled and align on the next step.

**Comment by dallashudgens** [comment]
@kyjak Why is the TOC extending into the footer? Shouldn't it sit above it? 

Is this still a problem on pages without the TOC? If there's a small width that is smaller than the footer elements?

**Comment by kyjak** [comment]
We received a design like this from Andree Proulx, this is the case only on pages when TOC is present. Otherwise the footer is taking the whole width.

**Comment by dallashudgens** [comment]
I would argue this isn't a bug with the footer component, but how the TOC is implemented. The page content should sit in between the header and the footer. 

@aiproulx can you speak to the design choice for the TOC extending past the main content container and into the footer?

**Comment by ljcarot** [comment]
KC and DDS has a checkin call on Jan 7 at which time we can discuss this issue. The content should sit within the head and footer.

**Comment by RobertaJHahn** [comment]
Andree presented the design and explained the reason for the TOC extending into the Footer space in the status meeting.  Andree and Wonil will take this topic offline to make a decision.

**Comment by kyjak** [comment]
Closing as the decision in the team was to do some css magic and make the footer wrap with styles (or else)
