### ISSUE TITLE
React: Storybook - Add/enable Customizable the 8-bar IBM logo on react version.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4806]
## Detailed description

Issue: 
Add Customizable the 8-bar IBM logo on react version.

**Comment by kennylam** [comment]
@RobertaJHahn @Praveen-sr This was completed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4878
