### ISSUE TITLE
Web component: Masthead - On Tab (S7), Android 10 version - hamburger menu options are not displayed 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4815]
## Detailed description

Issue: On Tab (S7), Android 10 version - hamburger menu options are not displayed.

**Comment by ariellalgilmore** [comment]
This bug seems to be fixed. @Praveen-sr just want to double check.

![Screen Shot 2021-01-08 at 6.40.10 AM.png](https://images.zenhubusercontent.com/5ee7ae1cc40147132b286905/2c2b86f5-6caf-4b79-bd05-2a4635d0c39c)

**Comment by Praveen-sr** [comment]
@ariellalgilmore Re tested this on S7 and S6 tabs, hamburger menu are displayed now. Working as expected.

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/ed6d56d8-1da2-4e69-bc09-5e5e30059171)
