### ISSUE TITLE
Utility: Scroll animation up & down enhancement functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4818]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Scroll animation up & down enhancement` functional specs 

> so that I can:
so that I can properly code the `Scroll animation up & down enhancement` utility that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#4766)**
 - [Design Issue 182](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/digital-design-ideation/182)
 - Development issue (#4280 )
 - [Prototype link](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/digital-design-ideation/182)

#### Acceptance criteria
 - [x] Documented `Scroll animation up & down enhancement` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by photodow** [comment]
Updates are here: https://ibm.box.com/s/jjz5j9gofyqam02lldrbx7el6ekfvttz

**Comment by RobertaJHahn** [comment]
@photodow You have moved this to the review pipeline.  Can I schedule an engineering review and sizing in next Monday's, Feb 1,  meeting?

**Comment by photodow** [comment]
Yeah, we should be good here I think. :+1:

**Comment by RobertaJHahn** [comment]
@photodow I'll add you to the meeting agenda and invite you to the meeting.
