### ISSUE TITLE
Web component: Link list section -  With tab/shift tab we are able to reach to the mentioned element but there is no visual focus at all.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4823]
## Detailed description

Issue:
With tab/shift tab we are able to reach to the mentioned element but there is no visual focus at all.

Expected Result:
Provide thick and strong visual focus.
1. If, Visual Focus Indicator with 3 CSS px stroke then provide a sufficient contrast that is equal to 3:1. 
2. Visual focus indicator for a link that is a 1 CSS px then provide a sufficient contrast greater than 4.5:1

**Comment by ariellalgilmore** [comment]
fixed in this PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4826#event-4182399060
