### ISSUE TITLE
React:  Masthead L0 - Grouped custom typeahead results enhancement

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon-for-ibm-dotcom#4845]
We have several groups of typeahead (search, product, last searches), so we need to forward labels for the groups and typeahead results for them.

![image](https://user-images.githubusercontent.com/15310250/103895952-7da15e80-50f1-11eb-9dd0-88eaf309a62e.png)

#### Additional Information
- Design and functional spec updates are needed.  This work is included under the following issue:
      - [Functional spec change issue](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/4944)
      - [Design spec change issue](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/4945)
- [link to the KC adopter meeting notes](https://ibm.ent.box.com/notes/601531416485)
- Wonil will provide design input by EOD Friday, Jan 22.
- Design QA testing issue (#5006 )
- Prod QA testing issue (#5007 )

#### Acceptance criteria
- [ ] Include README for the react component and corresponding styles
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create matching stable selectors in React component from the corresponding Web Component
- [ ] Create codesandbox example under `/packages/react/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] The Storybook link is added to the Design QA issue for their testing
- [ ] A comment is posted in the Prod QA issue, tagging Praveen, when development is finished

**Comment by RobertaJHahn** [comment]
Type ahead is available, but the grouping is not provided.   Next steps:

1)  Design is needed for the feature to group the keyword suggestions.  The DDS squad would have to investigate the impact to the ibm.com search results.  
2)  Kenny will investigate and begin building the solution.  
3)  Andree will work offline with Wonil to provide the design, sending the designs to Jenny and Wonil for review.

**Comment by wonilsuhibm** [comment]
Here is a design based on standards set in the megamenu:
<img width="1587" alt="Screen Shot 2021-01-07 at 9 01 39 AM" src="https://user-images.githubusercontent.com/30183447/103904675-939c2880-50cb-11eb-8d88-a2535cc37e75.png">

Key points here:
- Groups are separated with solid full-bleed horizontal rules and group headings
- The group heading uses 14px type

The Sketch file is here:
https://ibm.box.com/s/9mmobba8qzu1eszeddjhhaxec9c2wi9i

**Comment by JennySanchez** [comment]
Andress mentioned KC’s search type ahead (in group results) is available and can be viewed on the current site:
https://www.ibm.com/support/knowledgecenter 

![image](https://user-images.githubusercontent.com/45213839/103922706-bf260f80-50d9-11eb-9808-e453d9a3d94c.png)

**Comment by kyjak** [comment]
One more thing, we need to copy typeahead functionality from KC2, if you go here https://www.ibm.com/support/knowledgecenter/sk/search/
and type "aix", the first and last group (if there are 3) are essentially only keywords used for further search, but the second group is a direct link to a product.
Therefore we need the masthread search typeahead to consume also a HREF, rather than plain text keyword.
Or other option, same as the on search click event, fire an event with the typeahead index clicked and let DOCS handle the event and not fire search. Will talk to Kenny on this on Slack.

**Comment by aiproulx** [comment]
Specifications for the presentation of the results:
Same as dot com typeahead for:
1. vertical padding, 
2. font size
3. font treatment: medium, for matching words/characters
4. 20 grey for separator

In addition for the groupings:
1. a full length sparator for the grouping
2. the label of the grouping in grey 40

![image.png](https://images.zenhubusercontent.com/6008269a62eb0097cba9779d/03a3a8a8-eefd-4165-859e-8f3bdda9fa42)

**Comment by RobertaJHahn** [comment]
Jan 20, 2021 Meeting comments:

- Each grouping will have a maximum of 6 each.  This is a total of 18 max

- Design will create a spec document.  Functional spec updates are needed.  New issues will be created to make these updates.

- Wonil is working with Reboot regarding design MH elements.  Target to by end of the week, Jan 22, to provide the spacing and color decisions.

**Comment by RobertaJHahn** [comment]
New issue to update the functional specs:  (#4944 )
New issue to update the design specs:  (#4945 )

cc:  @ljcarot @wonilsuhibm

**Comment by aiproulx** [comment]
Design specifications can be found here, Sketch and PDF:
https://ibm.ent.box.com/folder/130651676188

[masthead--L0--search typeahead - design-specs--v2.3.0.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/5914198/masthead--L0--search.typeahead.-.design-specs--v2.3.0.pdf)

**Comment by aiproulx** [comment]
Reference: Jira task in IBM Documentation: https://jsw.ibm.com/browse/IBMDOCS-786

**Comment by RobertaJHahn** [comment]
Based on Kenny's and Jenny's participation in the KC design and engineering meetings:  The features needed are customized to the KC platform and are not something that we would ever add to the carbon for ibm.com code base.

**Comment by kyjak** [comment]
Typeahead works, there is a minor styling bug in the group title
![image](https://user-images.githubusercontent.com/15310250/107939696-64f55580-6f87-11eb-927c-bfd26037c0ce.png)
