### ISSUE TITLE
Component:  Audio Player Functional Specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4866]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Audio Player` functional specs 

> so that I can:
so that I can properly code the `Audio Player` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#4083)**
 - [Design Issue](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/digital-design-ideation/164)
 - Development issue (#TBD )
 - Visual Designs & Functional Design Specs Box folder link(TBD)

#### Acceptance criteria
 - [ ] Documented `Audio Player` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by photodow** [comment]
This story definitely needs to carry over into sprint 4. This week I worked with Olivia and the team to propose a scoped back version of this work for our first release of an audio player teams can adopt.

> Without focusing on the visual design I took Olivia's visual explorations and looked at how we could stage some of this work starting with as simple as possible, and becoming more complex.
> 
> ![image](https://user-images.githubusercontent.com/3793636/107962345-75e49d80-6f6c-11eb-848e-6c412019230a.png)
> 
> 1. CTA link
CTA link that navigates the user the kaltura to listen to the audio file.
> 
> - Open in Kaltura in new tab
> - play icon
> - Title
> - Length
> 
> 
> 3. Audio faux embed (video as-is mostly)
> 
> - Video player
> - Optional thumbnail
> - Default audio thumbnail
> - 
> 
> 
> 4. CTA embed
> CTA link that toggles play and stop from within the page.
> 
> - Play/(Pause) icon toggle
> - Title
> - Length
> - Progress indicator
> - alternative consumption [Transcript /link to kaltura with transcript (adopter addition via link, or built in?)]
> 
> 
> 5. Audio embed
> 
> - Play/(Pause) icon toggle
> - Title
> - Length
> - Progress indicator
> - alternative consumption [Transcript /link to kaltura with transcript (adopter addition via link, or built in?)]
> ---------- beyond depends on size
> - possible different sizes (sm, md, lg)
> - thumbnail
> - playback speed (2x etc.)
> - fast forward
> - jump forward (8s)
> - fast backward
> - jump backward (8s)
> - transcript download
> - closed captions
> - more information
> 
> 
> 6. CTA popup
> CTA link that pops up a modal with audio embed.
> 
> - Open in Kaltura in new modal
> - play icon
> - Title
> - Length
> 
> 
> 7. Sticky audio embed — (Kaltura builds for their own experience)
> 
> - audio embed full (xlg)
> - sticks to bottom of page
> - communicates with sticky overlay grid influencers
> - persistent when navigating within kaltura
> 
> 
> 8. Persistent sticky audio embed — not practical at the moment
> 
> - audio embed full (xlg)
> - included in dotcom shell across all IBM pages
> - persistent when navigating from one page to another
>
> 9. Data visualization
> With IBM being big into the data and analytics business I think we should be looking at ways to emphasize data, and how we present it. The progress bar is one of those areas that might be one of those opportunities worth exploring more than the average bar we see everywhere.

**Comment by shixiedesign** [comment]
Agreed not to build. Will close.
