### ISSUE TITLE
Web Component:  AEM CMS Request - Link List Styling changes

### ISSUE THREAD

**Issue by sbahl1** [carbon-design-system/carbon-for-ibm-dotcom#4891]
This epic contains functional and design links that define the scope of the deliverable.  This epic also includes links to all of the work required to deliver the component. 

#### Additional Information

-  Corresponding React epic (#4903)
- [Link to the DDS Design spec file in Box](https://ibm.ent.box.com/file/698433449371?s=hgrc62y10kopxdk5z75fcxq48m6ad3vc) Design is on pg 4.

#### Adopter provided info
Currently, Link List with two columns style exists and is being used for AEM CMS team for visual design and template rendering.
The request is for link list to support three columns as well. This is not a replacement of link list of 2 columns. This will be in addition to link list with 2 columns. 

Contributors from AEM CMS side are
- Visual design- Stephanie Homan and Kirby Evans
- Developer - Christian Schimanski
- Tech Point of Contact - Ke Xu
- Program/timeline/dependency management - Sandeep Bahl

Links
1. Related JIRA story is https://jsw.ibm.com/browse/ADCMS-317
2. Related Invision example with title variation (1 line vs 2 line) is here 
https://ibm.invisionapp.com/share/TFO0ORZN9DJ#/319780344_SC_Analytics_Learn_1312px_xlg

Attachments
<img width="1280" alt="Screen Shot 2021-01-13 at 8 30 37 AM" src="https://user-images.githubusercontent.com/57197236/104458681-ae621780-5579-11eb-8533-c7e70f8082b3.png">

**Comment by RobertaJHahn** [comment]
Work needed:  dev work and Prod QA.  Convert to an epic to manage the work.  Design specs on pg 4.

https://ibm.ent.box.com/file/698433449371?s=hgrc62y10kopxdk5z75fcxq48m6ad3vc
