### ISSUE TITLE
Web & React: Card Carousel - On Mobile, "Page size" as 6, user can not see all the cards and pagination does not work

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4919]
## Detailed description

Issue: 
1. On Mobile, "Page size" as 6, user can not see all the cards and pagination does not work
2. On tab and desktop - Page size as 6, the alignment of the cards is not right.

## Additional information

![Car2.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/725ccfd9-f814-46ff-9efd-0dad35986671)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/8e0d1230-f0b0-4bbb-b9cf-4b6288b7383c)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/1a350e08-695f-40d1-834b-8ebdc0858386)

**Comment by asudoh** [comment]
Addressed by: #4921
