### ISSUE TITLE
Web & React: Masthead L1 - On mobile landscape - Hamburger menu is not displayed 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4920]
## Detailed description

On iPhone, iOS 14 
Issue: 
On mobile landscape - Hamburger menu is not displayed. Users cant access the menu options

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b9b50f73-aa02-4b27-b023-47e0fb59285c)

**Comment by kennylam** [comment]
@Praveen-sr @RobertaJHahn I've tested on iOS 14 (iPhone 12 and iPhone 12 Pro) and iOS 13 (iPhone SE) and cannot reproduce this issue.

<img width="1004" alt="Screen Shot 2021-01-19 at 10 39 22" src="https://user-images.githubusercontent.com/909118/105056880-aeaf5680-5a42-11eb-9181-19b464cce489.png">

<img width="981" alt="Screen Shot 2021-01-19 at 10 39 28" src="https://user-images.githubusercontent.com/909118/105056899-b242dd80-5a42-11eb-9f28-94c5a05c24c7.png">
