### ISSUE TITLE
[card group] scroll animation design exploration

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#4929]
#### Overview
Continuing the work of #4873 this work explores the detailed design aspects of introducing scroll animations into this component. We need to figure out what settings are used, when, and too what parts of this component if at all.

Here is a list of components that could potentially be impacted by this work and should be considered at some level.
- Content group with cards
- Card section
- Content block with cards
- Locale modal

#### Acceptance
- [ ] design exploration
- [ ] design review
- [ ] design approval
- [ ] design specs updated

#### Resources
- Scroll animation [[box](https://ibm.box.com/s/s51j07ltae5gr31km38q6no1jfnadlgw)][[codepen](https://codepen.io/photodow/full/vYKaaxK)][[research](https://ibm.box.com/s/mauojg9vq6ordwbtxcb2g0ihbrj3hplq)]
- Scroll into view [[box](https://ibm.box.com/s/4d0l5zddtjdwpkpo3tj34e0ipmpeyj7u)]

**Comment by shixiedesign** [comment]
We've already talked about this one and you've done a second iteration of the motion design. Adding this into Review column to reflect that. I think we are pretty close. Not expecting new work on this issue at this time.

**Comment by photodow** [comment]
See https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5170#issuecomment-882494867
