### ISSUE TITLE
[Content group horizontal] scroll animation design exploration

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#4930]
#### Overview
Continuing the work of #4873 this work explores the detailed design aspects of introducing scroll animations into this component. We need to figure out what settings are used, when, and too what parts of this component if at all.

Here is a list of components that could potentially be impacted by this work and should be considered at some level.
- horizontal item

#### Acceptance
- [ ] design exploration
- [ ] design review
- [ ] design approval
- [ ] design specs updated

#### Resources
- Scroll animation [[box](https://ibm.box.com/s/s51j07ltae5gr31km38q6no1jfnadlgw)][[codepen](https://codepen.io/photodow/full/vYKaaxK)][[research](https://ibm.box.com/s/mauojg9vq6ordwbtxcb2g0ihbrj3hplq)]
- Scroll into view [[box](https://ibm.box.com/s/4d0l5zddtjdwpkpo3tj34e0ipmpeyj7u)]

**Comment by shixiedesign** [comment]
Won't do. Limiting animation to components without big chunks of body copy.
