### ISSUE TITLE
[Card section carousel] Discuss how to avoid adoptors setting too large number of cards per page

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#4940]
### The problem

While `<dds-carousel>` sets the default number of cards per page that best suits the available viewport width, `<dds-carousel>` also allows our adaptors to specify arbitrary number of cards per page, via `page-size` attribute. It caused weird UI caused by extreme `page-size`, as #4918 and #4919 reports.

### The solution

This issue is to discuss how to prevent such misconfiguration. A couple of options I can rattle off are:

1. Define the maximum number of cards per page for different breakpoints, and ignore any `page-size` attribute value that exceeds that maximum number
2. Define several sets of number of cards per page (see below) and have adaptors use such set instead of having them directly set the page size

(Just example of 2., the actual numbers should be determined by design team)

| Configuration | Number of cards per page for `sm` breakpoint | `md` | `lg` |
| ------------- | -------------------------------------------: | ---: | ---: |
| `SMALL`       |                                            2 |    4 |   6  |
| `DEFAULT`     |                                            1 |    2 |   3  |
| `LARGE`       |                                            1 |    1 |   2  |

CC @jeffchew @kennylam @oliviaflory

**Comment by asudoh** [comment]
@RobertaJHahn We have short-term (band-aid) fix for #4918 and #4919 already (#4921) so that January release doesn't have to wait for the resolution of this issue, FYI.

**Comment by oliviaflory** [comment]
My thoughts:

The maximum number of cards or images sort of depends on how many columns of the grid the adopter is using. Adding some examples of my thinking here... I don't know if this is too complicated to achieve in storybook? 

### `16` columns used on desktop view
| Configuration | Number of Cards for `sm` breakpoint | `Md` | `Lg`–`Max`|
| --- | --- | --- | --- |
| Default | 1 | 2 | 4 |
| Large | 1 | 1 | 2 |

<img width="547" alt="Screen Shot 2021-01-21 at 10 31 32 AM" src="https://user-images.githubusercontent.com/45692622/105372812-fdd8c100-5bd3-11eb-93bc-e8af986bfb82.png">
<img width="529" alt="Screen Shot 2021-01-21 at 10 31 39 AM" src="https://user-images.githubusercontent.com/45692622/105372823-016c4800-5bd4-11eb-81ab-a3373b6556a6.png">


### `12` columns used on desktop view
| Configuration | Number of Cards for `sm` breakpoint | `Md` | `Lg`–`Max`|
| --- | --- | --- | --- |
| Default | 1 | 2 | 3 |

<img width="541" alt="Screen Shot 2021-01-21 at 10 31 48 AM" src="https://user-images.githubusercontent.com/45692622/105372859-0d580a00-5bd4-11eb-88d6-5d24b4643f1d.png">



### `8` columns used on desktop view
| Configuration | Number of Cards for `sm` breakpoint | `Md` | `Lg`–`Max`|
| --- | --- | --- | --- |
| Default | 1 | 1 | 2|
| Large | 1 | 1 | 1 |

<img width="531" alt="Screen Shot 2021-01-21 at 10 32 00 AM" src="https://user-images.githubusercontent.com/45692622/105372883-134deb00-5bd4-11eb-997d-1bf995c43768.png">
<img width="535" alt="Screen Shot 2021-01-21 at 10 31 54 AM" src="https://user-images.githubusercontent.com/45692622/105372896-1648db80-5bd4-11eb-93fa-5d2e24c9e296.png">

**Comment by asudoh** [comment]
Thanks @oliviaflory for your thoughts! Sounds that rather preventing our adaptor from using too many cards per page, we want to provide good set of number (of cards per page) as (Storybook) examples. Is it correct?

**Comment by oliviaflory** [comment]
I think so @asudoh, and based on our explorations above, the maximum number or cards per page doesn't exceed 4 (in desktop) at this point.

**Comment by JennySanchez** [comment]
Per @oliviaflory 
The PR following the proposed solution was merged into this last release.
https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/4974

**Comment by JennySanchez** [comment]
**FYI:** @asudoh Adding this conversation to the "**[DDS Team Huddle 2021-03-02](https://ibm.box.com/s/2ydgjm5wep10j288hnivfuximm7w4n13)**" for group discussion

**Comment by shixiedesign** [comment]
Discussed this issue during Team Huddle time today. The decisions are to simply remove knobs and remove any storybook entires that suggests the component will be used with different number of cards per page.
