### ISSUE TITLE
Component: Masthead L0 - Change the design specs to include the grouped custom typeahead results

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#4945]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the `Masthead L0` design specs

> so that I can:
correctly change the `Masthead L0` component 

#### Additional Information
- **This work is in response to a KC Feature Request.  The details and corresponding decisions are documented in issue (#4845 )**
 - Development issue / KC Feature Request  (#4845 )
 - Functional spec change issue (#4944 )
 - [Visual Designs & Functional Design Specs Box folder link](https://ibm.ent.box.com/folder/59063660753?s=mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1)
- [link to the KC adopter meeting notes](https://ibm.ent.box.com/notes/601531416485)
- Wonil will provide design input by EOD Friday, Jan 22.

#### Acceptance Criteria
- [ ] A Sketch file is updated with the `Masthead L0` design and specs
- [ ] The design specs and pdf version are added to the Box folder included above

**Comment by JennySanchez** [comment]
**Task updates:**
- Confirmed with Wonil - This task will be for Andrée, designer on the Knowledge Center Team, to complete with my support.

- I shared the [Design Spec Kit](https://ibm.ent.box.com/s/v300ubv7tjda8xc0o6hl4ya9tigg15ai) and the [Components contribution website page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/components) with her on Friday 01/22/2020. She asked to join the Design Office hour tomorrow for further discussion as the next step.

![Screen Shot 2021-01-26 at 11.45.32 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/8f22e23b-708b-4df8-b437-2e0236e1b74c)

-----

**Note for additional resources to share with her:**

- Final design (see screenshot below) is provided by Wonil and the work file can be found [here](https://ibm.box.com/s/b4o67mr97un5dwvaqnl9iua7dq7rujjp).

![Screen Shot 2021-01-26 at 11.41.41 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/da888e49-d3e6-4ab9-b63c-1e1fbf49b40e)

- Masthead design spec file (masthead--L0--design-specs--v2.3.0) for her to add the Typeahead specing detail can be found [here](https://ibm.box.com/s/b4o67mr97un5dwvaqnl9iua7dq7rujjp).

- For the Design Spec file, things to be included are interactive states, responsive layouts, color tokens (do not use # or RGB color numbers), spacing tokens.

**Comment by JennySanchez** [comment]
@RobertaJHahn Based on the Sprint Planning conversation, we will continue the work in the next sprint and need to update the milestone to be Sprint 20-03. Thank you.

**Comment by JennySanchez** [comment]
The latest spec file from Andree (KC Team) is attached and the work file can be found [here](https://ibm.box.com/s/j01mahi4kfu2xc0gyxyfxure9ixjp9j6).[https://app.zenhub.com/files/193129061/5404db1d-d81a-4507-bfd1-80abf869bf43/download](https://app.zenhub.com/files/193129061/5404db1d-d81a-4507-bfd1-80abf869bf43/download)
