### ISSUE TITLE
menu item doesn't show active state in hamburg menu in masthead

### ISSUE THREAD

**Issue by yellowdragonfly** [carbon-design-system/carbon-for-ibm-dotcom#4971]
talked with Anna Wen on this issue. She was able to reproduce it on current testing environment.

When setting the last menu item link in the masthead to be selected, the item does not have a selected state in the mobile nav, only desktop

DESKTOP:
<img width="1297" alt="Screen Shot 2021-01-21 at 3 26 30 PM" src="https://user-images.githubusercontent.com/54281166/105408578-25904f00-5bfd-11eb-8b16-c64209812e75.png">

MOBILE MENU: (You can see the selected menu item in desktop does not have selected state in mobile)
<img width="649" alt="Screen Shot 2021-01-21 at 3 26 38 PM" src="https://user-images.githubusercontent.com/54281166/105408551-1d381400-5bfd-11eb-91a7-cfbe4abd177c.png">

**Comment by RobertaJHahn** [comment]
@annawen1 Issue is ready to finish the work.  Airtable updated, labels and release added.
