### ISSUE TITLE
Web component: Leadspace - Open canvas in new tab, gives an error page for the user

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4976]
## Detailed description

Issue: 
Leadspace - On knobs, edit/change 'number of buttons' or 'Icon' and then Open canvas in new tab, gives an error page for the user

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/0e60914f-f718-4cf7-833e-c22ec5260d1b)

**Comment by kennylam** [comment]
@Praveen-sr @RobertaJHahn This is ready for testing http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-leadspace--default-with-image
