### ISSUE TITLE
MSC Summit 2021

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#4990]
This epic is to capture and manage the summit deep diver series related work.

The current session list:
https://ibm.box.com/s/4kmj4ygwo8db7cenvdg4fszwhg811n1q

Design team session planning Mural:
https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1611255446531?sender=wonilsuh19286&key=05c53a48-54e9-4e18-96d9-aec710ab5648

**Comment by RobertaJHahn** [comment]
Summit training session and Retro complete.  Closing
