### ISSUE TITLE
Footer - footer link "Privacy" not translated in Hebrew

### ISSUE THREAD

**Issue by Daynssjal** [carbon-design-system/carbon-for-ibm-dotcom#5001]
## Detailed description

> The "Privacy" link text in the Footer component is not translated when the Hebrew language is selected.

> Is this issue related to a specific component?
Footer component:  all types with language only (Tall, Short, Micro)
https://ibmdotcom-react.mybluemix.net/?path=/story/components-footer--default-language-only

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expect the Privacy link to be translated in Hebrew, just like the rest of the links when the selected language is Hebrew. Instead, the link is still in English.

> What browser are you working in?
Chrome, Firefox, Safari, Edge

> What version of Carbon for IBM.com are you using?
1.14.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Knowledge Center team - IBM Documentation

## Additional information

<img width="795" alt="Footer-Privacy-not-translated" src="https://user-images.githubusercontent.com/33804471/105713885-f12dd300-5f1b-11eb-8131-9964dd8eb2b1.PNG">

**Comment by RobertaJHahn** [comment]
Digital Design does not maintain the translation files.  Tina Williams has moved to another role.  

Linda will reach out to Tina Williams for the translation of the word 'Privacy'.  Kenny will update the translation file.
