### ISSUE TITLE
[carbon-design-system/carbon-for-ibm-dotcom] Web component: Card component Pictogram enhancement Visual QA findings

### ISSUE THREAD

**Issue by jyoon25** [carbon-design-system/carbon-for-ibm-dotcom#5011]
QA for the Pictogram card.

Original design abstract link: https://share.goabstract.com/96c3a064-a525-47b7-83e7-a89aeee948e2?collectionLayerId=c2a41eb6-8bfe-4800-b2f2-3c81b922aa10&mode=design
QA PDF: https://ibm.box.com/s/t1d523ubzm38np4ekd3szc7uuhn1lgew

## Detailed description

> Describe in detail the issue you're having.

Design QA for pictogram card

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

General visual QA

> Is this issue related to a specific component?

Pattern: Pictogram card
http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-card--pictogram

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Detailed design QA is attached
QA PDF: https://ibm.box.com/s/t1d523ubzm38np4ekd3szc7uuhn1lgew

## Additional information

- Screenshots or code
- Notes

![image](https://user-images.githubusercontent.com/67110948/105928837-51a03b80-6014-11eb-8d86-0d20c27b0ecf.png)

**Comment by RobertaJHahn** [comment]
CECC / ISCEP adopter has another Card - Pictogram feature request that we are moving forward with under issue (#4927 ).  Closing this issue.
