### ISSUE TITLE
Carbon for ibm.com April 2021 Release Plan (v1.18.0)

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5015]
- **April 13, 2021**: Code freeze
- **April 13 - 20, 2021**: Release Candidate(s) and testing
- **April 21, 2021**: Full Release

## Global
- **carbon**
  - upgrade carbon to v10.32.1 (#5766)

### Breaking change

- **card-in-card**: `<dds-card-in-card-footer>` is replaced with `<dds-card-cta-footer>`
- **cta-section**: `<dds-cta-section>` has various API updates per updated designs
- **callout-with-media**: `<dds-content-block-copy>` is replaced with `<dds-callout-with-media-copy>`

### Features
- **cta-section**
  - created component (#5767)
- **cloud-megamenu**
  - megamenu tabbing functionality foundation (#5751)
- **tabs-extended-media**
  - introduce tabs extended with media component (#5759)
- **cloud-masthead**
  - add cloud-specific container and composite components (#5593)
- **tabs-extended**
  - tabs extended component (#5720)
- **content-group-banner**
  - add content group banner component (#5697)
- **mastheadleftnav**
  - react - refactor mobile left nav and add animations (#5677)
- **video-player-lightbox**
  - media viewer onclick enhancement + video image hover state (8% darken) treatment (#5581)

### Fixes
- **masthead-search**
  - ensure clicking on suggestion works (#5851)
- **callout-with-media**
  - change styles for carbon themes (#5828)
- **locale-modal**
  - prefix selector for input focus (#5822)
- **masthead**
  - ensure search closes properly & close on blur (#5812)
  - overflow appearing in max breakpoint (#5680)
  - enabled search suggestions with custom data (#5582)
- **dotcom-shell**
  - add scroll eventlistener (#5747)
- **card-pictogram**
  - fixed visual bugs & storybook refinements (#5736)
- **card-link**
  - changed style to expressive-heading-02 (#5711)
- **content-block-segmented**
  - fix spacing between copy and cta (#5745)
- **logo-grid**
  - fixed cta link markup to span proper dimensions (#5735)
- **card-in-card**
  - add video variation (#5717)
  - adjust card in card wrapper width on collapsed grid mode (#5494)
- **mastheadl1**
  - deselect l1 title when there is a selected menu item (#5698)
- **language-selector**
  - reimplementing components to fix jaws bug (#5658)
  - fixed micro styles (#5690)
- **content-block-media**
  - removed unnecessary margin-top (#5718)
- **table-of-contents**
  - added smooth scroll in css (#5645)
  - spacing fixes for toc (#5570)
- **back-to-top**
  - fix visibility toggling (#5699)
- **same-height**
  - using same height method for card group & cta section (#5567)
- **card-group**
  - random title percy check (#5703)
- **link-list**
  - various bug fixes (#5689)
  - added proper background on hover and removed underline (#5659)
- **toc**
  - add overflow to horizontal (#5662)
- **callout**
  - changing background-color token (#5528)
- **cardgroup**
  - storybook improvements (#5532)
- **featurecard**
  - multiple bugs and knob removal (#5517)
- **video-player**
  - import image component within video-player component (#5654)
- **content-item-horizontal-media**
  - switched the default alignment fr… (#5571)
- **card-cta**
  - update video image to 4x3 styles (#5515)

### Housekeeping
- **release**
- **percy**
  - adding fixes for false positive percy reports (#5773)
  - setting blank search placeholder in percy (#5738)
  - skipping card group with mixed media in avt (#5656)
- **carbon**
  - upgrade carbon to v10.32.1 (#5766)
  - upgrade to carbon v10.31.0 (#5760)
- **peerdependencies**
  - adding carbon peer dependencies (#5737)
- **global-init**
  - adding globalinit on render of masthead/footer (#5715)
- **dependencies**
  - upgrade `carbon-web-components` (#5712)
  - upgrade `sass-loader` (#5700)
- **readme**
  - updated webpack sass options to use relative paths (#5694)
- **button**
  - removed wc story and renamed to button expressive (#5580)
- **masthead**
  - lock masthead in white theme (#5609)
- **web-components**
  - fix typo (#5610)
- **telemetry**
  - adding carbon telemetry (#5583)
- **e2e**
  - introduce puppeteer to send e2e percy snapshots (#5479)
- **content-group**
  - update base class to new layout (#5480)

### Features
- **cta-section**
  - created component (#5767)
- **masthead**
  - add persistent search (#5524)
- **mastheadleftnav**
  - react - refactor mobile left nav and add animations (#5677)
- **masthead-search**
  - add persistent search term (#5501)

### Fixes
- **callout-with-media**
  - change styles for carbon themes (#5828)
- **mastheadsearch**
  - remove tooltip from search button (#5780)
- **mastheadleftnav**
  - set aria-hidden to unseen menu panels (#5770)
- **card-in-card**
  - add video variation (#5717)
- **mastheadl1**
  - deselect l1 title when there is a selected menu item (#5698)
- **same-height**
  - using same height method for card group & cta section (#5567)
- **masthead**
  - overflow appearing in max breakpoint (#5680)
- **featurecard**
  - multiple bugs and knob removal (#5517)
- **contentblockmedia**
  - feature card cta icon src was being overwritten (#5608)
- **table-of-contents**
  - spacing fixes for toc (#5570)

### Housekeeping
- **release**
- **carbon**
  - upgrade carbon to v10.32.1 (#5766)
  - upgrade to carbon v10.31.0 (#5760)
- **peerdependencies**
  - adding carbon peer dependencies (#5737)
- **percy**
  - disabling cardgroup and masthead search placeholder tests (#5723)
- **dependencies**
  - upgrade `sass-loader` (#5700)
- **e2e**
  - fixes to table of contents and masthead e2e tests (#5624)
  - introduce puppeteer to send e2e percy snapshots (#5479)
- **masthead**
  - lock masthead in white theme (#5609)
- **telemetry**
  - adding carbon telemetry (#5583)
- **featurecardblockmedium**
  - remove array brackets from card object in docs (#5575)
- **back-to-top**
  - fix typo in readme (#5535)

### Features
- **cta-section**
  - created component (#5767)
- **tabs-extended-media**
  - introduce tabs extended with media component (#5759)
- **tabs-extended**
  - tabs extended component (#5720)
- **content-group-banner**
  - add content group banner component (#5697)
- **mastheadleftnav**
  - react - refactor mobile left nav and add animations (#5677)
- **video-player-lightbox**
  - media viewer onclick enhancement + video image hover state (8% darken) treatment (#5581)

### Fixes
- **callout-with-media**
  - change styles for carbon themes (#5828)
- **masthead**
  - use specific selectors to remove tooltip (#5821)
  - overflow appearing in max breakpoint (#5680)
  - using correct token for essentials description text (#5516)
- **masthead-search**
  - overriding carbon core button styles (#5804)
- **mastheadsearch**
  - remove tooltip from search button (#5780)
- **card-pictogram**
  - fixed visual bugs & storybook refinements (#5736)
- **card-link**
  - changed style to expressive-heading-02 (#5711)
- **card-in-card**
  - add video variation (#5717)
  - adjust card in card wrapper width on collapsed grid mode (#5494)
- **mastheadl1**
  - deselect l1 title when there is a selected menu item (#5698)
- **same-height**
  - using same height method for card group & cta section (#5567)
- **file-uploader**
  - icon size fix (#5695)
- **toc**
  - add overflow to horizontal (#5662)
  - missing hover state (#5655)
- **link-list**
  - added proper background on hover and removed underline (#5659)
- **callout**
  - changing background-color token (#5528)
- **featurecard**
  - multiple bugs and knob removal (#5517)
- **table-of-contents**
  - spacing fixes for toc (#5570)

### Housekeeping
- **release**
- **carbon**
  - upgrade carbon to v10.32.1 (#5766)
  - upgrade to carbon v10.31.0 (#5760)
- **peerdependencies**
  - adding carbon peer dependencies (#5737)
- **dependencies**
  - upgrade `carbon-web-components` (#5712)
  - upgrade `sass-loader` (#5700)
- **masthead**
  - lock masthead in white theme (#5609)
- **telemetry**
  - adding carbon telemetry (#5583)

### Features
- **cta-section**
  - created component (#5767)

### Fixes
- **tabs-extended-with-media**
  - videos are now working (#5830)

### Housekeeping
- **release**
- **telemetry**
  - adding carbon telemetry (#5583)

### Features
- **cloud-masthead**
  - add cloud-specific container and composite components (#5593)

### Housekeeping
- **release**
- **settings**
  - updated to 1.18.0
- **carbon**
  - upgrade carbon to v10.32.1 (#5766)
  - upgrade to carbon v10.31.0 (#5760)
- **telemetry**
  - adding carbon telemetry (#5583)

**Comment by jeffchew** [comment]
Successfully released v1.18.0: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/releases/tag/v1.18.0
