### ISSUE TITLE
Web component: Masthead - Hamburger menu @700px, two scroll bar are displayed and grey background style is missing.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5021]
## Detailed description

Issue:
Hamburger menu @700px, two scroll bar are displayed and IBM logo, search and profile on the background are not visible. Grey background style is missing.

## Additional information

Actual :
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b664116c-e28b-4f96-8d72-589709cda85b)

Expected:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/c8994949-a319-4102-9325-a27228014cac)

**Comment by guilhermelMoraes** [comment]
Not happening anymore. @Praveen-sr would you please re-test this one?

**Comment by Praveen-sr** [comment]
@guilhermelMoraes Hey, re tested this, still the issue exists.

![Hamburg.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/d3d1a50d-a492-4d1e-ab89-e3b4b81544e2)
