### ISSUE TITLE
[Masthead/Footer] Load Arabic/Korean/Japanese Plex font family when needed

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5025]
#### User Story

> As a `[user role below]`:
IBM.com user

> I need to:
See Arabic language loaded with the Plex arabic font in the Masthead/Footer

> so that I can:
See the IBM.com header/footer as they were meant to be viewed when in Arabic

#### Additional information

 - Fonts are located at: https://github.com/IBM/plex
- Scope of this work is for the Arabic/Korean/Japanese language 
- Need the ability to load in this font when Arabic is being used in the Masthead/Footer, fallback can be the current non-Arabic Plex font if the application is not loading the arabic font family on the page.
- Akira recommendations included in issue (#5404 )
- CDN artifacts have a repo set up at: https://github.ibm.com/webstandards/plex-cdn
- CDN urls are not finalized yet, but can get the work started
- Will need to target styles and load in the corresponding font family, possibly with this approach: https://developer.mozilla.org/en-US/docs/Web/CSS/:lang
- Additional languages should ideally be conditionally loaded on the page, as the artifacts for Korean and Japanese fonts are large.
 
#### Acceptance criteria
 - [ ] Properly load the arabic/korean/japanese font family when needed in the Masthead and Footer

**Comment by jeffchew** [comment]
@RobertaJHahn can we line this issue up to be sized and staged for work in our next refinement?

cc: @ljcarot @wonilsuhibm

**Comment by RobertaJHahn** [comment]
@jeffchew   Done

cc:  @ljcarot @wonilsuhibm

**Comment by shixiedesign** [comment]
Related bug ticket, https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/5402

**Comment by jeffchew** [comment]
After discussion plus some initial investigation of how fonts are loaded, also doing a check and the generated sass code for font sets like Arabic do not come with unicode-range.

We may have to investigate a way to conditionally load fonts based on the detected language.

**Comment by shixiedesign** [comment]
Would this work be able to include Japanese as well? Mike brought up today that Japanese is just released.

**Comment by ljcarot** [comment]
I added Japanese to title of Issue.

**Comment by ljcarot** [comment]
@jeffchew Will this make these Plex fonts only available for Carbon adopters?

**Comment by jeffchew** [comment]
The CDN artifacts themselves are framework agnostic, so v18 pages can take advantage of those as well.

Non-IBM.com may also be able to take advantage, actually.
