### ISSUE TITLE
[card section carousel]: General tabbing issues

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#5027]
## Detailed description

I'm seeing a number of issues related to tabbing...

1. tabbing doesn't progress panels
2. tabbing doesn't update progression in pagination
3. tabbing sometimes messes up pagination and layout calculations
4. tabbing hidden items if you go away and come back
5. Can't get to the active panel through tabbing (without going through all the cards) after using pagination controls. Should focus be given to the first card after pagination? We should either consider jumping into the active panel, or consider jumping the carousel back to panel one.
6. tabbing and then resizing screen has caused pagination layout issues

## Steps to reproduce the issue

1. Go to card section carousel
2. tab through cards to see behavior.

## Additional information

![Jan-28-2021 13-07-32](https://user-images.githubusercontent.com/3793636/106186795-5d9e1180-616a-11eb-9b5a-a9d569d17a1e.gif)

![Jan-28-2021 12-45-27](https://user-images.githubusercontent.com/3793636/106184181-cf745c00-6166-11eb-8150-b59764ee3204.gif)

> Adding design to this because there may be some unconsidered edge cases here that need to be evaluated.

**Comment by IgnacioBecerra** [comment]
I'm addressing all these issues in #5035. 

The way it currently works is that tabbing goes to the next page automatically, same with shit+tab going back.
https://images.zenhubusercontent.com/193129061/985350a5-89fa-4c3f-863d-09e21dd9ce94/screen_recording_2021_02_04_at_11_54_00_am.mov


If the current page has been changed using the page switch buttons, we can tab into the current cards being presented.
https://images.zenhubusercontent.com/193129061/29492837-195b-4432-9927-1c79cf3df40e/screen_recording_2021_02_04_at_11_58_44_am.mov
