### ISSUE TITLE
[carousel]: lacking swiping on mobile devices

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#5029]
## Detailed description

I wasn't able to swipe left or right to progress the carousel on mobile devices.

## Steps to reproduce the issue

1. Open storybook component on mobile device
2. Swipe left and right.

## Additional information

<img src="https://user-images.githubusercontent.com/3793636/106179143-3b9f9180-6160-11eb-8da6-5b36855ff0fa.gif" width="400px" />

**Comment by RobertaJHahn** [comment]
@Praveen-sr Could you test this bug to reproduce and provide more details for the platform.

**Comment by Praveen-sr** [comment]
@RobertaJHahn  Tested this on phone and tab on web component & React, swiping cards left or right does not progress the card movement.
Same behavior for card carousel component. 
 Note: This is without using pagination.

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/a195a4de-3c0e-4ba0-bb92-6237061ec3b6)
