### ISSUE TITLE
[card section carousel]: small breakpoint horizontal scrolling

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#5030]
## Detailed description

At the `sm` breakpoint in particular there is a horizontal scroll from what appears to be the next hanging card is still around.

## Steps to reproduce the issue

1. navigate to storybook page
2. open up carbon devtools and choose `sm` breakpoint to resize the browser.

## Additional information

<img src="https://user-images.githubusercontent.com/3793636/106178615-9ab0d680-615f-11eb-9cd2-560d9b869252.gif" width="300px" />

**Comment by RobertaJHahn** [comment]
@Praveen-sr Can you retest this bug on the platforms to provide specific detials.

**Comment by Praveen-sr** [comment]
@RobertaJHahn Tested this scenario on Phone, the horizontal scrolling is felt on "Carousel component and Dotcom shell".

![Caro.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/28eae643-f505-444d-9052-57fb024102a1)

Dotcom Shell:
![dotcom.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/d90c5996-7466-4bcd-a7d6-bb1c675d8d99)
