### ISSUE TITLE
[card section carousel]: cards not hanging on grid properly

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#5032]
## Detailed description

For breakpoints `lg` and greater the cards don't lay/hang properly on the grid.

## Steps to reproduce the issue

1. Open up storybook
2. Overlay grid with Carbon devtools

## Additional information

<img src="https://user-images.githubusercontent.com/3793636/106176235-aa7aeb80-615c-11eb-8649-84b61ab0e3c6.png" width="600px" />

##### expected
<img src="https://user-images.githubusercontent.com/3793636/106177222-d64aa100-615d-11eb-832b-1350a601bd31.png" width="400px" />

**Comment by ariellalgilmore** [comment]
update: the grid alignment is correct, but there is an error with the next card not showing as per spec:  ![Screen Shot 2021-02-25 at 2.19.26 PM.png](https://images.zenhubusercontent.com/5ee7ae1cc40147132b286905/8ec077d0-a051-4bb5-b2b5-b14fa683d727)
