### ISSUE TITLE
Footer prop name change

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5049]
## Summary
Inconsistency in footer names within our documentation is confusing adopters.

## Relevant information
_This is a follow on from #4496_ 

**Background**
An adopter reached out to me to ask "Which footer is correct?" after looking through our various documentations the adopter and I found a number of slight variations and name inconsistencies that made it confusing to know which was "correct". 
In #4496 we determined that the Footers should be: `Default`, `Short` and `Micro`. The design specs and Carbon for IBM.com website have been updated.

**Question:** 
Can we change the footer prop from `tall` to `default` to align with how we talk about the footers? In talking with Anna, I wasn't sure if this would be a breaking change or not, and wanted to check with the dev team.

**Another note**
The Docs tab is different between [React](https://ibmdotcom-react.mybluemix.net/?path=/docs/components-footer--default) and [Web component](https://ibmdotcom-web-components.mybluemix.net/?path=/docs/components-footer--default)storybooks, should they be the same? Web components doesn't call out the `tall` prop from what I can see..

**Prop name `Tall`**
<img width="1045" alt="Screen Shot 2021-02-01 at 11 14 44 AM" src="https://user-images.githubusercontent.com/45692622/106485767-f391af00-647e-11eb-817f-618c2226d926.png">

Conversation between me and Anna:
![Screen Shot 2021-02-01 at 11 29 11 AM](https://user-images.githubusercontent.com/45692622/106487561-c7772d80-6480-11eb-980b-5e681ec27993.png)

**Comment by RobertaJHahn** [comment]
Changing the prop from Tall to Default will not break existing adopters implementation.  It is an easy change.  Team agreed to make this changes.
