### ISSUE TITLE
Kaltura:  Design support for MediaCenter to provide a framework that supports the Front End Carbon audio Player styling

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5051]
#### Overview
This is an issue to track the delivery of the Kaltura framework updates needed to continue the testing of the desired designs.

#### Additional Information
- Kaltura delivery date:

**Comment by oliviaflory** [comment]
From Felipe on Feb 3:

Functionalities updated - so speed and sound controls are possible to be abstracted too, just as I thought :smile:
Same URL to preview ( https://pages.github.ibm.com/mediacenter/studies/podcast-page/ )
And page full code ( https://github.ibm.com/MediaCenter/mediacenter.github.ibm.com/blob/master/studies/podcast-page/index.html ) - which is a mess of vanilla html + js + css
