### ISSUE TITLE
Component: Anchor Link functional specifications 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5073]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Anchor Link` functional specs 

> so that I can:
so that I can properly code the `Anchor Link` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5069 )**
 - Design Issue [#173](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/digital-design-ideation/173)
 - Development issue (#5072 )
 - Visual Designs & Functional Design Specs Box folder link(TBD)

#### Acceptance criteria
 - [ ] Documented `Anchor Link` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by photodow** [comment]
Table of contents — horizontal

[Functional specs](https://ibm.box.com/s/txwb4jnir8phxn4xvsuu4t5uml33prvj)
[Prototype sticky example](https://ibm.box.com/s/bnckzywztll5tw4ndbv77sssu7ksvfgz)
[Design specs](https://ibm.box.com/s/3ayj2q4tek6r9l6x8nv47quvwo1au8w4)
