### ISSUE TITLE
Web component: Mega Menu MVP - accommodations for HC + AI updates - Visual QA (Firefox, Chrome)

### ISSUE THREAD

**Issue by jyoon25** [carbon-design-system/carbon-for-ibm-dotcom#5089]
Mega Menu MVP - accommodations for HC + AI updates design QA (Firefox, Chrome)

## Detailed description

> Describe in detail the issue you're having.

Visual design QA

QA pdf link(firefox): https://ibm.box.com/s/dum8331jjkseqibworat5obgitb6u57p
QA pdf link(chrome):https://ibm.box.com/s/1pm7knckcw9t78o2r8f0pay725u0dqeb
Original design abstract link: https://share.goabstract.com/6f02a9ae-517f-45b8-b76f-b77273b9a4ad

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Visual Design QA

> Is this issue related to a specific component?

Mega Menu MVP - accommodations for HC + AI updates

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

Firefox, Chrome

## Additional information

- Screenshots or code
- Notes

<img width="736" alt="image" src="https://user-images.githubusercontent.com/67110948/106848259-9a906980-667e-11eb-85a7-5ea02781cc5b.png">

**Comment by annawen1** [comment]
For the `sm` and `md` breakpoints, the designs are for the "Products & Solutions" menu - so if you click on the "Products & Solutions" menu item after opening up the hamburger menu, you will see that it matches the designs

**Comment by annawen1** [comment]
Spoke with @oliviaflory about the "View all ..." link top border not touching the vertical left panel border - we are going with having the gap as shown in our current implementation of the megamenu 😁
