### ISSUE TITLE
Issue with build while using carbon styles

### ISSUE THREAD

**Issue by siddhiborkar** [carbon-design-system/carbon-for-ibm-dotcom#5093]
## Detailed description
We are using ibm carbon dot com styles in our scss . 

@import '@carbon/ibmdotcom-styles/scss/components/footer/index';
@import '@carbon/ibmdotcom-styles/scss/components/masthead/index';
@import '@carbon/ibmdotcom-styles/scss/components/leadspace/leadspace';
@import '@carbon/ibmdotcom-styles/scss/components/tableofcontents/index';
@import '@carbon/ibmdotcom-styles/scss/patterns/sub-patterns/tableofcontents/index';
@import '@carbon/ibmdotcom-styles/scss/components/card-section-images/card-section-images';

On building our react application using npm run build we see the following issue
 ./src/components/app/App.scss
[1] SassError: File to import not found or unreadable: carbon-components/scss/globals/scss/vars.
[1]         on line 9 of node_modules/@carbon/ibmdotcom-styles/scss/themes/expressive/index.scss
[1]         from line 11 of node_modules/@carbon/ibmdotcom-styles/scss/components/footer/index.scss
[1]         from line 23 of /home/travis/build/dwedge/partner-showcase-viewer/client/src/components/app/App.scss
[1] >> @import 'carbon-components/scss/globals/scss/vars';

We also have SASS_PATH=node_modules:src in our env file.But it did not help.
Could someone help us with this?

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by siddhiborkar** [comment]
Here is the package.json
"@carbon/ibmdotcom-react": "^1.12.0",
    "@carbon/ibmdotcom-styles": "^1.12.0",
    "@carbon/themes": "^10.16.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "@types/carbon-components": "^10.15.0",
    "@types/carbon-components-react": "^7.10.8",
    "@types/jest": "^24.9.1",
    "@types/react": "^16.14.2",
    "@types/react-dom": "^16.9.8",
    "carbon-components": "^10.24.0",
    "carbon-components-react": "^7.17.0",
    "carbon-icons": "^7.0.7",

**Comment by RobertaJHahn** [comment]
This was addressed in a Slack conversation.  Looks like an implementation issue.  Closing

**Comment by biapar** [comment]
I've the same problem. How to solve?
