### ISSUE TITLE
Layout Spacing changes

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#5094]
### The problem
There is concern about the amount of whitespace in the current Learn layout and that it is making the page longer than it needs to be. 

### The solution
The AEM team would like to reduce the spacing on some of these elements.

~1. The AEM team is recommending to update the Leadpace’s top level spacing to 48px top-padding and 64px bottom padding with a max-height of 480px.~
2. The AEM team is recommending to update spacing below section headers from 48px to 32px.
3. The AEM team is recommending to update 2nd-tier spacing from 96px to 64px.

### Additional information
 [Visual reference of spacing updates](https://ibm.box.com/s/mtge0azehfmshphnn12kz3iv9x7vc3vy)
 [ExperienceGuild-Learn Research.pptx (slide 3)](https://ibm.box.com/s/eku9bmzsh0e9cgr5gqw8vwnwdqiwwdgb)
 [ExperienceGuild-Learn Template User Testing (slide 6)](https://ibm.box.com/s/jvz0g15z77abfpmm2il90s82mivit11e)

**Comment by RobertaJHahn** [comment]
Per Wonil:  DDS agreed to these suggested design changes.  These changes can simplify the overall spacing.

**Comment by RobertaJHahn** [comment]
The Feb 12 AEM meeting covered the Solutions page MVP.  There was not time to cover this FR.  Olivia will be on an Away mission with AEM.  @kirbyevans  Is this request part of the Solution page template?  Can you respond to the question posed by Olivia in the Feb 9 comments above?  This request may need additional conversation in a meeting to talk about the implementation approach in an existing meeting or separate meeting.  I can set up the meeting, if a separate meeting is preferred.

**Comment by kirbyevans** [comment]
These changes are needed for the Learn template but also apply to what we are doing for Solution. In regards to Olivia's question, I'm not entirely sure what the distinction between layout and template would be.

**Comment by RobertaJHahn** [comment]
Item #1 above is included in the Lead space variation work (#4753).  Removing from scope of this issue.

Work needed for items 2 & 3:
- Update the design specs
- Dev
- Visual PR QA
- Prod QA
No web site updates needed.

Create a single spacing epic to manage work.

**Comment by shixiedesign** [comment]
Website doesn't mention spacing guidance yet. The only part that will be out of date are the example images of larger components. Eg. https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/content-block-segmented 

Should be part of the website sweep in https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom-website/860
