### ISSUE TITLE
need a way to set REACT_APP_PROFILE_HOST environment variable

### ISSUE THREAD

**Issue by yellowdragonfly** [carbon-design-system/carbon-for-ibm-dotcom#5125]
carbon ibm.com V1.15.0.
We are using ProfileAPI to get the user ibm.com login status. Currently the call points to production environment url. Although the call reads in PROFILE_HOST environment variable to point to different environment, the variable is not a valid REACT environment variable name. So need a way for carbon ibm.com to read in the variable as REACT_APP_PROFILE_HOST in the development environment.

#### Additional Info
- Assess the existing environment variables.  Determine if adding REACT_APP support makes sense.

**Comment by jeffchew** [comment]
This will be in the `v1.17.0` release.
