### ISSUE TITLE
[Video player] Create visual specs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5128]
#### User Story

> As a `[user role below]`:

designer

> I need:

video player specs

> so that I can:

use them in my designs

#### Additional information

Video player and image were combined into Media component, and never broken out into individual spec files after we determined that they would be separate components

Design needs to ensure we have specs for Video player that our adopters can utilize in their designs

*Note: Spacing between video player and the caption will be updated to 8px* #5127

#### Acceptance criteria
 - [x] Spec file created
 - [x] Spec file uploaded to box

**Comment by shixiedesign** [comment]
Done! 
https://ibm.box.com/s/9q7rdj73m32hufcw1xwl1td6nr88rghm
