### ISSUE TITLE
Image & Image with caption specs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5129]
#### User Story

> As a `[user role below]`:

designer

> I need:

image and image with caption specs

> so that I can:

use them in my designs

#### Additional information

Image, Image with caption, and video player were combined into Media component, and never broken out into individual spec files after we determined that they would be separate components

Design needs to ensure we have specs for image and image with caption, at all breakpoints,  that our adopters can utilize in their designs

*Note: Spacing between video player and the caption will be updated to 8px* #5127

**Caption should use `caption-02` token to align with removal of expressive theme** #6186 

#### Acceptance criteria
 - [ ] Spec file created
 - [ ] Spec file uploaded to box

**Comment by shixiedesign** [comment]
This is a duplicate but with useful info!
