### ISSUE TITLE
Web component: Masthead-With custom data - On landscape mode, overflow previous button is not working

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5134]
## Detailed description

Issue:
Masthead - With custom data- On landscape mode, overflow previous button is not working

## Additional information

![Mast-Cust.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/cfe05aeb-d78e-4e60-9477-2e8df3fbe44d)

**Comment by annawen1** [comment]
@Praveen-sr The fix to this bug has been merged, you can test here: https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-masthead--with-custom-data

**Comment by Praveen-sr** [comment]
@annawen1 Re tested this on above link, On landscape mode, overflow previous button is working fine. Thanks

CC @RobertaJHahn
