### ISSUE TITLE
Web component: Masthead-With custom data - Hybrid cloud options are missing from the menu options.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5135]
## Detailed description

Issue: 
Masthead-With custom data - Hybrid cloud menu options are not displayed for the user. 

Steps to Reproduce:
Step1: Click on the Hamburger menu
Step2: Click on the Products & Services Menu
Step3: Click on any sub-menu
Step4: Click on the link present within the sub menu
Step5: Once IBM.com page got loaded, Click on the browser back button and come back to the parent page and click on the Hamburger menu

## Additional information

![Mast-Cust11.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b13200f2-d91b-46bf-9e9b-1621f46cdc34)

**Comment by ariellalgilmore** [comment]
Tested this on my actual IPhone X on 14.4 and was not able to replicate. This might something just in browserstack.

**Comment by annawen1** [comment]
@Praveen-sr I also tested this on my iphone 8 on 14.3 and don't see this happening.

**Comment by Praveen-sr** [comment]
@annawen1 @ariellalgilmore  I tested this scenario on actual iPhone 11 with iOS 14.4, I was able to reproduce it.

https://images.zenhubusercontent.com/193129061/7b157895-a2ae-447b-b144-08aa2eb48472/img_0960.mp4

**Comment by annawen1** [comment]
One thing to note, I do not see this bug happening in the https://www.ibm.com/partners/ page which is using the web components masthead

**Comment by annawen1** [comment]
@Praveen-sr can you test on www.ibm.com/partners and https://ibmdotcom-web-components-html-test.mybluemix.net and see if the bug is reproducible there? I think this may be specific to storybook.
