### ISSUE TITLE
React stand alone: Mega Menu MVP enhancement to accommodate HC + AI updates Visual QA

### ISSUE THREAD

**Issue by jyoon25** [carbon-design-system/carbon-for-ibm-dotcom#5136]
React stand alone: Mega Menu MVP enhancement to accommodate HC + AI updates Visual QA

## Detailed description

> Describe in detail the issue you're having.

Visual design QA

QA PDF link: https://ibm.box.com/s/k57zbe7l0ndgq9pitbskkbebmdrohlxb
Original design abstract link: https://share.goabstract.com/6f02a9ae-517f-45b8-b76f-b77273b9a4ad

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Visual Design QA

> Is this issue related to a specific component?

React stand alone: Mega Menu MVP enhancement to accommodate HC + AI updates
https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--with-custom-navigation

> What browser are you working in?

Chrome

## Additional information

- Screenshots or code
- Notes

<img width="634" alt="image" src="https://user-images.githubusercontent.com/67110948/107534005-815f4f80-6b8d-11eb-9de9-d9307da82c57.png">

**Comment by annawen1** [comment]
@jyoon25 I spoke to Olivia about the "View all ..." link border not touching the vertical border of the left panel, we decided to leave the gap there so that isn't a problem.
