### ISSUE TITLE
Masthead:  Persistently visible searchfield in Masthead searchbar 

### ISSUE THREAD

**Issue by Daynssjal** [carbon-design-system/carbon-for-ibm-dotcom#5152]
### The problem
Hello, we are using the Masthead component with searchbar.
Currently, we can use the **searchOpenOnload** prop to make sure that the searchbar is open after the page loads.
However, if the user clicks elsewhere on the page, the searchbar gets closed.

### The solution
We would like the **Masthead searchbar field to be visible constantly,** no matter the user's interaction with the page.
Example can be seen on https://www.ibm.com/search?lang=en&cc=us&q=api%20 

### Additional information
This feature is requested by the Knowledge Center team.

<img width="724" alt="dotcomsearch" src="https://user-images.githubusercontent.com/33804471/107656493-83580a00-6c84-11eb-8196-c39a3d592396.PNG">

- Because this feature already exists on ibm.com Masthead search, JC is providing the code to Miroslav Krsjak on the KC team.  As of the March 3 adopter status meeting, the KC team will include this feature in their search to meet their release date.  JC will contribute the code to Carbon for ibm.com.  (According to Miro, JC's code is included in a back level version of the Carbon for ibm.com Masthead.)  DDS will include the feature and will perform the QA required.

- [Design and functional specs box folder link](https://ibm.ent.box.com/folder/59063660753?s=mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1)

**Comment by RobertaJHahn** [comment]
Next steps:  functional specs update, no visual design needed, dev & QA, web site content updates made in overall web site work.

**Comment by RobertaJHahn** [comment]
JC can contribute the code during their next sprint which begins next week.  (Feb 22 - Mar 5)
