### ISSUE TITLE
Create Carbon for IBM.com React training module - Code Repository

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5153]
#### User Story

> As a `[user role below]`:
developer

> I need to:
complete training pull requests on how to use Carbon for IBM.com React

> so that I can:
understand how to implement within my IBM.com application

#### Additional information

 - Tutorials are currently available for Carbon core, an example: https://carbondesignsystem.com/developing/react-tutorial/overview
 - The training module should focus more on utilizing Carbon for IBM.com React: https://ibmdotcom-react.mybluemix.net
 - We could possibly also include a segment on using the NextJS template: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template
 - Include a segment on building for IBM.com: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/docs/building-for-ibm-dotcom.md
 - Should create this training somewhere on the Carbon for IBM.com website: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website
 - Repo for the Carbon training app, we will probably need something similar: https://github.com/carbon-design-system/carbon-tutorial
 - Separate story for applying for a digital badge, we will need to add this as an additional page to the tutorial so users know how to apply for it: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5154
 - Scope of this work is the code repository, which should be a companion to the website work: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5237

#### Acceptance criteria
 - [ ] Training module repo created for Carbon for IBM.com React

**Comment by RobertaJHahn** [comment]
Work is managed under epic (#5115).  Planning for all of the work included in the training epic added to the Aug 2, 2021 Engineering refinement meeting.

**Comment by RobertaJHahn** [comment]
Will be moving away from support of Pure React components.  Closing this epic and all linked issues.
