### ISSUE TITLE
Create badge submission page for the Carbon for IBM.com React training module

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5154]
#### User Story

> As a `[user role below]`:
developer

> I need to:
apply for a digital badge on completion of the Carbon for IBM.com React tutorial

> so that I can:
display my digital badge to other IBMers

#### Additional information

 - A final page should be added to the tutorial so developers that complete the training module will know where to apply for the badge
 - We should include a possible survey for developers to fill out when applying for the badge: https://badges.carbondesignsystem.com/badges
- The form detects pull request creation, we may want to do something similar
- Badge website that Carbon uses, we should see if we can leverage anything there:https://github.com/carbon-design-system/carbon-badges

#### Acceptance criteria
 - [ ] Create an application form for completion of the Carbon for IBM.com React tutorial
 - [ ] Detection of pull requests for monitoring completion of the course work

**Comment by RobertaJHahn** [comment]
Will be moving away from support of Pure React components.  Closing this epic and all linked issues.
