### ISSUE TITLE
Web component: Masthead - When user hovers on menu options, grey background is covering the copy text.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5162]
## Detailed description

Issue:
When user hovers on menu options, grey background is covering the short description text.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/c45c0c21-2a8c-4982-97d8-571ec33a1882)

**Comment by NSDrowned** [comment]
@Praveen-sr, can't replicate the error. Could you please provide more information on how to recreate it?

**Comment by Praveen-sr** [comment]
@NSDrowned Re tested this on web components, now we don't have this issue. 

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/e21eb1e6-a815-4b71-9adb-d90e8f1bfebe)
