### ISSUE TITLE
Audit mega menu specs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5166]
#### User Story

Audit the mega menu specs, specifically the text link container, spacing and type tokens used, to ensure they are aligned between the original mega menu specs (v1.1), the Hybrid Cloud update, and the Cloud mega menu.

Lila, Shixie and I worked together to figure out how to best align them, and we need to ensure the specs and code match the tokens and sizing used. 

#### Additional information

 - _{{user research}}_
 - _{{user insights}}_
 - _{{user metrics}}_

#### Acceptance criteria
 - [ ] Review specs from all files
 - [ ] Update to a single spec file, to accommodate HC and other menus?
 - [ ] Update on Box
 - [ ] Ensure code follows the correct specs

**Comment by shixiedesign** [comment]
Still a to do

**Comment by RobertaJHahn** [comment]
No longer needed.
