### ISSUE TITLE
[Lists] scroll animation design exploration

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#5171]
#### Overview
Continuing the work of #4873 this work explores the detailed design aspects of introducing scroll animations into this element. We need to figure out what settings are used, when, and too what parts of this component if at all.

Here is a list of components and elements that could potentially be impacted by this work and should be considered at some level.

- UL
- OL
- checkboxes
- radio buttons
- link list
- table of contents
- Footer nav items
- Locale modal locale search items
- Content group with pictograms
- Content group horizontal

#### Acceptance
- [ ] design exploration
- [ ] design review
- [ ] design approval
- [ ] design specs updated

#### Resources
- Scroll animation [[box](https://ibm.box.com/s/s51j07ltae5gr31km38q6no1jfnadlgw)][[codepen](https://codepen.io/photodow/full/vYKaaxK)][[research](https://ibm.box.com/s/mauojg9vq6ordwbtxcb2g0ihbrj3hplq)]
- Scroll into view [[box](https://ibm.box.com/s/4d0l5zddtjdwpkpo3tj34e0ipmpeyj7u)]

**Comment by RobertaJHahn** [comment]
Caught by Stalebot because it did not have the `icebox` label.  Added the label so that the issue remains in `icebox` until the work can be scheduled.

**Comment by shixiedesign** [comment]
Covered by existing prototype James already done. https://cognitive-app.slack.com/archives/G01CFF8ETPU/p1625777081026300
