### ISSUE TITLE
Web component: Footer - Locale modal -Visually "Select Geographic area" Modal is displayed But Voiceover does not identify this dialog. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5173]
## Detailed description

Issue:
Visually "Select Geographic area" Modal is displayed But Voiceover does not identify this dialog, In Left/Right swipe Voiceover announcing the content from the parent page. 

Note:
This issue is not present in React Staging

**Comment by Praveen-sr** [comment]
@kennylam Ram retested this in iPhone 11 (os 14.4) and 6S OS (13.5) and able to reproduce the defect. 
Below we have mentioned the steps to reproduce:
In Web component staging, activate “Footer default”
Activate "Select geographic area" button. The modal displays
Select any geography. e.g. "Americas". "Location selection" modal appears
Here, activate "Select geographic area" link/button,
Visually the previous dialog appears. (do not touch any ware on the screen). Just Swipe Left/Right with one finger
Voiceover would announce the content from the parent page instead of identifying the modal content.

Note: while trying the same in “react staging” in footer default/short/micro, it works.

**Comment by kennylam** [comment]
This has been resolved in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5189.
