### ISSUE TITLE
React Masthead creates Unhandled Runtime Error (Network Error)

### ISSUE THREAD

**Issue by bkfrye** [carbon-design-system/carbon-for-ibm-dotcom#5174]
## Brief description
There is a network error when including the `Masthead` components individually or with the DotcomShell. 

## Detailed description
When including the `Masthead` there is a network error that I cannot fix. 

You can find the error log here:
```
Unhandled Runtime Error
Error: Network Error

Call Stack

createError
node_modules/axios/lib/core/createError.js (16:0)

XMLHttpRequest.handleError
node_modules/axios/lib/adapters/xhr.js (84:0)
```

> Describe in detail the issue you're having.

If the `Masthead` is included (by itself or in DotcomShell), this issue will appear. If I remove the `Masthead` component, the issue never appears. If I turn on a CORS proxy, the issue is also bypassed. The [IBM Dotcom NextJS template](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template) is being used, this may be specific to NextJS, but I have not had the time to extensively test other frameworks or setups. 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected Masthead to work without any issues. On page load, the error appears in the console.

I did not notice this issue before when using v1.14.0, but when reverting to use that version, the same error is now present. **Could this be related to a CORS issue?**

> What browser are you working in?

Issue occurs in all modern browsers (last two versions).

Project is utilizing `@carbon/ibmdotcom-react 1.15.0`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

I'm a developer with [Centerline Digital](https://www.centerline.net/) and this project will be published in the next few weeks for Watson Health. The error shows in the production browser console, but I can not track down any consequences as a result. 

## Steps to reproduce the issue

1. Import Masthead and include component
2. See if issue appears

## Additional information
I noticed that I cannot seem to find any information about CORS proxies in the documentation anymore. Has that option been totally removed? How can I ensure that my local URL is whitelisted?

**Comment by photodow** [comment]
Thanks for bringing this to our attention @bkfrye! It looks like we might have fixed this over [here]( https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template/issues/32) coming in the next release `1.16.0`. You can start testing the latest release candidate  [1.16.0-rc.0](https://www.npmjs.com/package/@carbon/ibmdotcom-react/v/1.16.0-rc.0) and see if it works for you.  I'm going to go ahead close this. Feel free to re-open it, or reach out if you're still having an issue.
