### ISSUE TITLE
Wrong type token in Mega menu "the essentials" description text

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5181]
## Detailed description

Currently, the description text in "the essentials" column appears use `$body-short-01`, which has a line height of 22px. Intended design & spec is to use `$body-long-01` which has a line height of 24px. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/f9b3224e-418b-4ce0-8e62-8975874a80d9)

**Comment by photodow** [comment]
@shixiedesign I'm assuming this is a bug in the [component](http://ibmdotcom-web-components-experimental.mybluemix.net/?path=/story/components-masthead--with-custom-data)? I'm tagging it as dev to be triaged for now. Feel free to correct me here if I'm assuming wrong.
