### ISSUE TITLE
Masthead:  Persistent search text in Masthead searchbar after search is executed functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5187]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Masthead search` functional specs 

> so that I can:
so that I can properly code the `Masthead search` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#TBD )**
 - No visual design changes are needed
 - React Development issue (#5203 )
- Web Components dev issue (#5232 )

#### Acceptance criteria
 - [ ] Documented `Masthead search` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by RobertaJHahn** [comment]
@photodow There are no links of comments included in this issue, but it is in the Done pipeline.  Can you post the link to the func specs.  Thanks.

cc @shixiedesign

**Comment by photodow** [comment]
Must have gotten distracted, sorry about that!

https://ibm.box.com/s/89qwjyjy6kwbi69qnz4nzatwfv3mh2kc
