### ISSUE TITLE
Masthead:  Persistently visible searchfield in Masthead searchbar

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5188]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Masthead search` functional specs 

> so that I can:
so that I can properly code the `Masthead search` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5152 )**
 - No Visual design changes are needed
 - React Development issue (#5204 )
- Web Components dev issue (#5233 )
 - Visual Designs & Functional Design Specs Box folder link(TBD)

#### Acceptance criteria
 - [x] Documented `Masthead search` functional specifications
 - [x] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [x] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by RobertaJHahn** [comment]
@photodow please post a closing comment in the issue.  Thanks.

cc:  @shixiedesign

**Comment by photodow** [comment]
Ah, my bad. I got distracted while moving these over during meetings I think.

https://ibm.box.com/s/89qwjyjy6kwbi69qnz4nzatwfv3mh2kc
