### ISSUE TITLE
React & Web component: Leaving IBM - On mobile, landscape mode, user not able to access the Continue button.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5191]
## Detailed description

Issue:
 On mobile, landscape mode, user not able to access the "Continue" button. As page scrolling is not working.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/e9732bbf-2554-4a2a-b634-8f2146783fb6)

**Comment by NSDrowned** [comment]
Fixed in PR #5331
