### ISSUE TITLE
NextJS Page: CTA section - Button is not operable. [Need investigation]

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5195]
## Detailed description

Issue: 
On click, Button is not operable. [Need investigation]

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/a0264686-8d7e-400a-a24d-4110bc62014f)

**Comment by annawen1** [comment]
Does not require a fix in our CTASection React component - just need to update the nextjs test page to pass in url data to the cta section button
