### ISSUE TITLE
Carbon Styles SassError: Can't find stylesheet to import.

### ISSUE THREAD

**Issue by biapar** [carbon-design-system/carbon-for-ibm-dotcom#5199]
Failed to compile.

./src/content/CompanyChoosePage/style.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/content/CompanyChoosePage/style.scss)
SassError: Can't find stylesheet to import.
  ╷
2 │ @import '@carbon/type/scss/font-face/mono';

 
Packages:

 "@carbon/charts-react": "^0.41.32",
    "@carbon/grid": "^10.20.0",
    "@carbon/ibmdotcom-react": "^1.15.0",
    "@carbon/ibmdotcom-styles": "^1.15.0",
    "@carbon/icons-react": "^10.25.0",
    "@carbon/pictograms-react": "^11.2.0",
    "@carbon/themes": "^10.26.0",
    "@carbon/type": "^10.20.0",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.5",
    "@testing-library/user-event": "^12.7.1",
    "@types/jest": "^26.0.20",
    "@types/node": "^14.14.28",
    "@types/react": "^17.0.2",
    "@types/react-dom": "^17.0.1",
    "axios": "^0.21.1",
    "carbon-components": "^10.28.0",
    "carbon-components-react": "^7.27.0",
    "carbon-icons": "^7.0.7",
    "core-js": "^3.8.3",
    "d3": "^5.16.0",
    "dayjs": "^1.10.4",
    "formik": "^2.2.6",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.1",
    "sass": "^1.32.7",
    "typescript": "^4.1.5",
    "web-vitals": "^0.2.4",
    "yup": "^0.32.8"

**Comment by biapar** [comment]
Any news?

**Comment by biapar** [comment]
Have you made any updates? 

Because it works, now. This are the packeges:
"dependencies": {
    "@carbon/charts-react": "^0.41.41",
    "@carbon/grid": "^10.21.0",
    "@carbon/ibmdotcom-react": "^1.16.1",
    "@carbon/ibmdotcom-styles": "^1.16.1",
    "@carbon/icons-react": "^10.26.0",
    "@carbon/pictograms-react": "^11.4.0",
    "@carbon/themes": "^10.28.0",
    "@carbon/type": "^10.22.0",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.5",
    "@testing-library/user-event": "^12.8.1",
    "@types/jest": "^26.0.20",
    "@types/node": "^14.14.31",
    "@types/react": "^17.0.2",
    "@types/react-dom": "^17.0.1",
    "axios": "^0.21.1",
    "carbon-components": "^10.29.0",
    "carbon-components-react": "^7.29.0",
    "carbon-icons": "^7.0.7",
    "core-js": "^3.9.1",
    "d3": "^5.16.0",
    "dayjs": "^1.10.4",
    "formik": "^2.2.6",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",
    "sass": "^1.32.8",
    "typescript": "^4.2.2",
    "web-vitals": "^0.2.4",
    "yup": "^0.32.9"
  },

and my scss imports:

$feature-flags: (
  grid-columns-16: true,
);

@import "https://fonts.googleapis.com/css?family=IBM+Plex+Sans+Condensed|IBM+Plex+Sans:400,600&display=swap";

@import '@carbon/themes/scss/themes';

$carbon--theme: $carbon--theme--g10;
@include carbon--theme();

@import '@carbon/colors/scss/colors';
@import '@carbon/grid/scss/grid';
@import 'carbon-components/scss/globals/scss/styles.scss';
@import '@carbon/ibmdotcom-styles/scss/components/leadspace/leadspace';

**Comment by kennylam** [comment]
Hi @biapar,

Great that it's working for you now. But without seeing an example of your code it's difficult to pinpoint exactly what was causing the issue.

**Comment by biapar** [comment]
I've not changed anything. I made only again "npm update". How to? I'm plugin into a react dashboard with carbon components an carbon ibm dotcom components.

**Comment by RobertaJHahn** [comment]
Closing based on comments above.
