### ISSUE TITLE
Build full width Content block simple

### ISSUE THREAD

**Issue by sbahl1** [carbon-design-system/carbon-for-ibm-dotcom#5200]
Updated: Content section simple can be a variation of Content block simple https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-content-block-simple--default OR a use Content section and pass in content block as a child (ref. Jame's comment below)

### Acceptance criteria

- [x]  Finalize design. Needs to be fleshed out with all variations
- [x]  Visual and functional spec
- [ ]  Write out some basic usage guidance 📖

### Preliminary design below: 

![image (16)](https://user-images.githubusercontent.com/57197236/108248311-afaad500-7121-11eb-927f-e8ff47d15dc3.png)

**Comment by photodow** [comment]
> - Add heading to left column and

Probably should not be apart of this component change request. We either need to create a new component around this full thing, or y'all can leverage content section and pass in content block simple as a child.

**Comment by photodow** [comment]
> - Add media to the right, replacing link list

Might be worth having a conversation around this, but at the moment content block simple doesn't dictate anything specific goes off to the side. The author can pass in link list, video, image with caption, or anything else from a technical standpoint.

**Comment by shixiedesign** [comment]
I don't see "Content section". But yes, if I understood you right - we create a larger section component **Content section** and pass **Content block item as a child**. That sounds good to me.

**Comment by photodow** [comment]
@shixiedesign here is the box folder for [content section](https://ibm.box.com/s/oqlsa6m0vfownbn1s2y682mnugsf6cuv).

**Comment by RobertaJHahn** [comment]
Shixie will check the implementation methods with Sandeep, Ke and Shawn on Slack.  This issue may be closed based on the implementation responses.

AEM  agrees to remove the Heading 03 in order to prevent dev changes.

**Comment by shixiedesign** [comment]
AEM is able to put the components together to create this Content section simple. The only thing we need to do is: 
- video player should have a state that triggers media viewer on click, instead of playing the video in place. 
- James to update functional spec
- Roberta to help make dev issue
