### ISSUE TITLE
[Lead space]  medium variation functional specifications 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5202]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Lead space` functional specs 

> so that I can:
so that I can properly code the `Lead space` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#4753 )**
 - Design Issue (#5197) and (#5256)
 - Development issue (#5231 )
 - [Visual Designs & Functional Design Specs Box folder link](https://ibm.ent.box.com/folder/94761007991?s=d9jey3rlfxqmxu059f0x9dtcx7f5ehuh)

#### Acceptance criteria
 - [ ] Documented `Lead space` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by photodow** [comment]
Here are some updates I reviewed with design and dev yesterday, I'll be adding to functional specs, and sent over to @andysherman2121 this morning.

- Add new `size` prop to leadspace *(across all `types`)*
- New `size` options *(see [design specs](https://ibm.ent.box.com/folder/94761007991?s=d9jey3rlfxqmxu059f0x9dtcx7f5ehuh) for height definitions)*
    - `super`
    - `tall` `default`
    - `medium`
- Remove aspect ratios on `small` and `left/default` `types`. 
- Remove height for `centered` type. 


> more updates to come from #5347

**Comment by photodow** [comment]
Updated functional specs:

https://ibm.box.com/s/drihwzp3aernradc8wa3ycd2tc0t9n6k
