### ISSUE TITLE
[Card group] Change to allow guttered grid variation

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5210]
[Card group](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-card-group--default) needs a 16px guttered grid variation to accommodate AEM solution template. This will ingesting **Card in card** #5304 to create "Featured card group" section. Functional analysis for the component is done. 

**This component will be developed by HC / ref Putra,** estimated around 4 points. 

### Final Design spec
https://ibm.box.com/s/r4nt1w1fe2gnuqn6m9gac48tll7jq5pl

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/ff7ed4ba-6426-45a5-9c93-6fcccbb960f9)

- [DDS Card Group Box folder link](https://ibm.ent.box.com/folder/111654108347?s=r4nt1w1fe2gnuqn6m9gac48tll7jq5pl)

### Acceptance criteria
-[x] Finalize design. Needs to be fleshed out with all variations
-[x] Visual spec
-[ ] functional spec
-[ ] Write out some basic usage guidance 📖

### FA notes
- Only 1 **Card in card** is allowed
- [Updated Functional Specs in DDS Box folder](https://ibm.ent.box.com/file/781924336006?s=nebuvxryzaw00cknopufvskxdmyyochr)

### References
Jina's old spec
https://ibm.box.com/s/yh1r97n9qr9d6rd5jhz79c7vxqx7uhan

Reference build from HC: 
https://pages.github.ibm.com/MSC-Cloud/hc_fractal/components/detail/8b--cool-gray-10.html

"Featured card group" was tracked previously here: 
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4294

Updated [Card group spec](https://ibm.ent.box.com/folder/111654108347?s=r4nt1w1fe2gnuqn6m9gac48tll7jq5pl)

**Comment by shixiedesign** [comment]
[HC Module 8B ](https://pages.github.ibm.com/MSC-Cloud/hc_fractal/components/detail/8b--cool-gray-10.html)is very similar. Asking dev's opinion if this is easier to ingest as contribution or rebuild: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/6db833c2-a1ae-4a8c-93d6-380e12d3d745)

**Comment by shixiedesign** [comment]
According to Putra, the component can be submitted as contribution!
Would work with HC team to tweak design of Module 8B to align with spec, then contribute. FYI @RaphaelAmadeu

**Comment by RobertaJHahn** [comment]
Convert to an epic
design provided by Kirby
Func specs and naming (James in progress.)
DDS eng to support Hybrid Cloud dev.  WC dev issue  React wrapper in icebox
Visual QA
Prod QA

**Comment by proeung** [comment]
@shixiedesign The `Card in Card` component has been added to the `Card Group` layout component as part of the work outlined in this PR (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5419 ). Please let me know if there's anything else that needs to be done for this ticket.

Storybook preview: https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/5419/index.html?path=/story/components-card-group--with-card-in-card
