### ISSUE TITLE
build "Carousel with image cards"

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5211]
Carousel with image cards (or "Image card carousel"? Actual component name TBD) is a section used on AEM solution template. It can be build as a variant of https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-carousel--default

### Acceptance criteria
- [x] Finalize design. Needs to be fleshed out with all variations
- [ ] Visual and functional spec
- [ ] Write out some basic usage guidance :book:

### "Image card carousel" component has preliminary design below. Final design would show aspect ratios aligned with existing DDS standard. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/9199a5a0-f085-4d86-a313-b8db375f3cd4)

**Comment by RobertaJHahn** [comment]
This component does not need a change as the images can be added to the cards component as is.  DDS team will add a storybook story - name TBD.  Issue will be assigned to Raph.

@sbahl The DDS focals will explain on the next AEM call.
