### ISSUE TITLE
React: Footer - Short language selector - The language selector is not stretched to end of the screen

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5213]
## Detailed description

On Mobile 

Issue:
The language selector is not stretched to end of the screen

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/5d977f22-a5ae-424b-aeae-9f234ffc9bcb)

**Comment by kennylam** [comment]
@Praveen-sr This has been tested on different iPhone models and cannot be reproduced. I suspect it is a Browserstack issue.

**Comment by RobertaJHahn** [comment]
Closing based on Kenny's comments.
