### ISSUE TITLE
Promo Group:  Determine the name of the new DDS component 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5215]
#### Overview
This component was designed and code submitted behind a feature flag by AEM.  They named it `Promo Group`, but this may not be the best component name within the Carbon for ibm.com repo.  

#### Additional Information
AEM provided documentation
- Invision document is here https://ibm.invisionapp.com/share/F9O0RPZHT46#/screens/319811795
- Pull request https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5142

####  Acceptance Criteria
- [ ] Work the DDS team members to define the component name

**Comment by shixiedesign** [comment]
Having discussed with @photodow this component will use name **CTA Section** and be build as a variant of **CTA section with content content item**. Let's move it to done.
