### ISSUE TITLE
[CTA Section variant]  Create the functional specifications aka Promo Group

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5216]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `CTA section` functional specs 

> so that I can:
so that I can properly code the `CTA section` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5201 )**
 - Designs provided by AEM
- [Final design spec link](https://ibm.box.com/s/shr0pnhof0yzk2b5lh0nokwopgxxb9rr)
 - Web Component Development issue (#5218 )

**_AEM provided documentation_**
- Invision document is here https://ibm.invisionapp.com/share/F9O0RPZHT46#/screens/319811795
- Pull request https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5142
- Add new component with 4 variants (Pictogram, media, statistic and text) 

#### Acceptance criteria
 - [ ] Documented `CTA section` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by photodow** [comment]
![image](https://user-images.githubusercontent.com/3793636/108720924-067c2a00-74e7-11eb-8441-44bb8b412dcd.png)

> Break down notes
> - CTA section depends on content section as previously proposed
> - CTA section breaks out into CTA Block as previously proposed.
> - CTA section buttons enables text links option
> - Content items count upgraded to 3 at least, or enable custom count similar to link list.
> - Data, media, pictogram above content items need to be added.
> - Might need to flip the borders of content items.
Couple unknowns…
> - Video thumbnail interaction
>   - Does the video thumbnail break out of the normal CTA function?
> - Design appears to not have heading-03 in content. Something would have to give.

**Comment by photodow** [comment]
[Content section](https://ibm.box.com/s/mwz8d62bxgqlu84rwt7yfpa3lgray6sc) update
[CTA block](https://ibm.box.com/s/1mbmay093kclwwjhuhmux0kqzptvpgj3) creation
[CTA section](https://ibm.box.com/s/lwc9yt046wphh568l4qhe6pjfu23acqg) update

Content section heading optional (create issue) https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5487
