### ISSUE TITLE
[CTA Section variant] Create the design specs aka Promo group

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5217]
Please note **Kirby** is working on the spec of this one.

**Comment by RobertaJHahn** [comment]
@shixiedesign Are these design specs going to be available soon?  Can I schedule the review in Monday's, March 1, engineering meeting for sizing?

**Comment by shixiedesign** [comment]
Design spec
https://ibm.box.com/s/shr0pnhof0yzk2b5lh0nokwopgxxb9rr
