### ISSUE TITLE
Web Components:  Create the [CTA section] variant (aka Promo Group)  

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5218]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
create/change the `CTA section`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic for the Design and Functional specs information**
- Visual QA testing issue (#5220 )
- Prod QA testing issue (#5221 )
____

- Pull out "CTA block" as a component
- Remove "Promo group" & "Promo item"

#### Functional specs
[Content section](https://ibm.box.com/s/mwz8d62bxgqlu84rwt7yfpa3lgray6sc) update
[CTA block](https://ibm.box.com/s/1mbmay093kclwwjhuhmux0kqzptvpgj3) creation
[CTA section](https://ibm.box.com/s/lwc9yt046wphh568l4qhe6pjfu23acqg) update

Content section heading optional (create issue) https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5487

----

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by ljcarot** [comment]
Sandeep mentioned in satellite team slack that Raveena will take up this story from AEM side. fyi @RaphaelAmadeu

**Comment by RaphaelAmadeu** [comment]
We just had an discussion, and agreed to make `CTA Block` into a component that shall be used within `CTA Section`.

We'll have the knobs mainly set on the `CTA Block` story and have the variations on `CTA Section`.

CC: @photodow @andysherman2121

**Comment by andysherman2121** [comment]
@RobertaJHahn Adding myself back to this ticket. I started helping out Raveena with this

**Comment by RobertaJHahn** [comment]
PR (#5330 ) referenced above will not be used.  This issue was changed from a consulting issue to a DDS engineering issue as the DDS team will  build this component.
