### ISSUE TITLE
Layout spacing changes design specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5223]
These changes apply to the AEM Learn template, but will also apply to the Solution template.

#### Additional Information
Summary of changes:  
- Update spacing below section headers from 48px to 32px.
- Update 2nd-tier spacing from 96px to 64px.

AEM provided documentation:
 [Visual reference of spacing updates](https://ibm.box.com/s/mtge0azehfmshphnn12kz3iv9x7vc3vy)
 [ExperienceGuild-Learn Research.pptx (slide 3)](https://ibm.box.com/s/eku9bmzsh0e9cgr5gqw8vwnwdqiwwdgb)
 [ExperienceGuild-Learn Template User Testing (slide 6)](https://ibm.box.com/s/jvz0g15z77abfpmm2il90s82mivit11e)

#### Acceptance Criteria
- [ ] A Sketch file is created or updated with the `Layout spacing` design and specs changes
- [ ] The design specs and pdf version are added to the Box folder 
- [ ] Update the Agile Board epic with the spec link
- [ ] Add Box folder link to the website content if it exists

**Comment by shixiedesign** [comment]
I forgot this issue was created and made a new one 😬 #5376. So this can be closed as it's duplicated.
