### ISSUE TITLE
[Housekeeping] Rename master branch to main

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5230]
#### User Story

> As a `[user role below]`:
Carbon for IBM.com developer

> I need to:
pull the Carbon for IBM.com development branch from `main`

> so that I can:
work within the Carbon for IBM.com space using the newly recognized terminology for the main Github branch

#### Additional information

 - Words Matter at IBM: https://ibm.ent.box.com/s/n78wzg1e6fjbjg53f117z33wk04tbg5p
 - Repos:
   - https://github.com/carbon-design-system/carbon-for-ibm-dotcom
   - https://github.com/carbon-design-system/carbon-for-ibm-dotcom-design-kit
   - https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template
   - https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-test
   - https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-test

#### Acceptance criteria
 - [x] Update the branch name in Github to `main`
 - [x] Update all references in Github action workflows
 - [x] Update all references in all CI workflows
 - [x] Update all references in documentation (ie. comments, READMEs with urls pointing to master)

**Comment by RobertaJHahn** [comment]
There is a lot of automation impacted by this change.  As a result, the work will be scheduled during a low velocity period.  December 2021.
