### ISSUE TITLE
[AEM] Allow stand alone card component icon to change depending on link type

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#5236]
## Contribution Request 💓

Thank you for contributing to Carbon for IBM.com. Before you submit your contribution, please visit the [Contribution section](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/overview/) on our website to understand the process and requirements.

### Contribution type (please select one):

[x] Documentation
[ ] Components
[ ] Patterns
[ ] Others {{please describe}}

### Intent

There are globalization concerns around not being able to update the card icon per link type.  

### Solution

We would like the ability to have the card icons match their link type. For instance, if a card is linking to an external site outside of IBM we should be using the 'launch' icon instead of the 'arrow-right' icon to help with user expectation. We're thinking this feature should be available for all card types that currently leverage the 'arrow-right' icon.

Contribution information and required documentations

Available icon options should be similar to what's available for the [CTA component](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-cta--text).

IBM Organization or Company you are part of: 
AEM Afterburner CMS team

**Comment by photodow** [comment]
We might consider enabling CTA style cards here within the content group. I know we've talked about doing it in the past, but I don't think we've moved forward with the idea.

**Comment by RobertaJHahn** [comment]
Shixie to follow-up with Kirby.

**Comment by shixiedesign** [comment]
This issue is resolved! Following discussion happened in Slack and was later confirmed over call: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/94068374-c9d5-4387-9bcf-7ada626be6f5)
