### ISSUE TITLE
Apply for digital badge for the Carbon for IBM.com React training module

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5238]
#### User Story

> As a `[user role below]`:
developer

> I need to:
have a digital badge on completion of the Carbon for IBM.com React tutorial

> so that I can:
display my digital badge to other IBMers

#### Additional information

 - Applying for a digital badge: https://w3.ibm.com/w3publisher/badges
 - This will be in tandem with the badge submission form work: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5154

#### Acceptance criteria
 - [ ] Apply and receive badge so we can issue to developers

**Comment by RobertaJHahn** [comment]
Not stale

**Comment by RobertaJHahn** [comment]
Will be moving away from support of Pure React components.  Closing this epic and all linked issues.
