### ISSUE TITLE
[Content block cards with video] Allow 4:3 aspect ratio for Content block cards with videos component

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#5240]
## Contribution Request 💓

Thank you for contributing to Carbon for IBM.com. Before you submit your contribution, please visit the [Contribution section](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/overview/) on our website to understand the process and requirements.

### Contribution type (please select one):

[x] Documentation
[ ] Components
[ ] Patterns
[ ] Others {{please describe}}

### Intent

There is a need to mix image cards and video cards within a single content block card component. Card height is becoming uneven due to different aspect ratios used for image (4:3) and video (1:1).

### Solution

We'd like to consider allowing a 4:3 aspect ratio on video cards.

Here is the link to the Jira issue. [ADCMS 574](https://jsw.ibm.com/browse/ADCMS-574)

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/c0ca3474-ab6e-4025-b123-8f2e6d5ab4d9)

### Additional information

IBM Organization or Company you are part of: 
AEM Afterburner CMS team

**Comment by RobertaJHahn** [comment]
This request scope should include all media (video and images)

@kirbyevans  Is this request a high priority or can it wait until the April release?

**Comment by kirbyevans** [comment]
@RobertaJHahn We need to allow users the ability to mix image cards and video cards. Currently, when we do the aspect ratio is different between the two types and throws alignment off. We will need it for our release of the Learn template.

**Comment by photodow** [comment]
@kirbyevans is the aspect ratio the only piece you see missing in order to mix image and video cards?

**Comment by kirbyevans** [comment]
@photodow we'd want to allow for consistent text treatments within the content area of the card as well.

**Comment by RobertaJHahn** [comment]
Issues needed:
Design from AEM
func specs
DDS engineering - WC & React
Visual QA - Assign Shixie
Prod QA

Release Schedule needed

**Comment by shixiedesign** [comment]
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/f84a292f-a3c3-4732-9a8f-c6115107b7a5)
