### ISSUE TITLE
[Video Player]: Media viewer onClick enhancement functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5246]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Video Player` functional specs 

> so that I can:
so that I can properly code the `Video Player` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5245 )**
 - Development issue (#5247 )
 - Visual Designs & Functional Design Specs Box folder link(TBD)

#### Acceptance criteria
 - [x] Documented `Video Player` functional specifications changes
 - [x] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [x] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by photodow** [comment]
Updated: https://ibm.box.com/s/y8py6laddi9jslvxbt30kvinkvfwfalp
