### ISSUE TITLE
Web Component: [Video Player] Implement the onClick trigger - consulting support

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5247]
#### User Story

> As a `[user role below]`:
IBM.com Library developer

> I need to:
change the `Video Player`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic for the Design and Functional specs information**
 - video player should have a knob that triggers Media viewer onClick, instead of playing the video in place.
- [Video Player functional specs](https://ibm.ent.box.com/file/781903492361?s=y8py6laddi9jslvxbt30kvinkvfwfalp)
- Functional specifications issue  (#5246 )
- Prod QA testing issue (#5265 )
- Visual QA issue (#5264)

---- 

- Design is exactly the same as [default Video player](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-video-player--default), with video title and caption 
- Similar functionality as [CTA - video card](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-cta--card), trigger lightbox media viewer
- Pulling cover image from Kaltura API 
- Keep original original video's aspect ratio 
- Development by AEM, @RaphaelAmadeu consult.  Engineering 5 story points (Putra assigned) and Raph consulting 3 story points.
- @RaphaelAmadeu @andysherman2121 Link the AEM created PR to this issue and move it though the development pipelines as we normally do.  

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Design QA issue, tagging Designer, when development is finished
- [ ] The Storybook link is added to the Design QA issue for their testing
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by ljcarot** [comment]
Sandeep commented in satellite channel that Christian from AEM is assigned to this issue. FYI @RaphaelAmadeu

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu @andysherman2121 Functional specs are now available,   I have posted the link in the Additional Information section above.

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu @andysherman2121 I see that the linked PR is `Ready to merge` so I have moved this issue to the `Review` pipeline.  Has this component had the visual QA done?  Shixie is assigned to the Visual QA issue.  Was she assigned to the PR?

cc:  @shixiedesign

**Comment by asudoh** [comment]
@RobertaJHahn Those linked PRs are for setting the stage for @RaphaelAmadeu to create the feature, rather than one that closes this issue, FYI.
