### ISSUE TITLE
Anchor Link:  Final design - Target sprint 21-02

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5255]
#### User story 1  - End user
> As an [user role below]:
`ibm.com user`

> I need to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### User story 2  - DDS Designer
> As a [user role below]:
`DDS Designer`

> I need to be able to do:
`?description here?`

> so that I can:
`?description here?`

#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- [box folder]
- [reference materials]

#### Acceptance Criteria
- [ ] Final designs are available
- [ ] Design spec issue has been created on the Agile board with the documentation needed and the work scheduled.

**Comment by oliviaflory** [comment]
For now, the !Anchor link! is being considered a Table of Contents (horizontal) and is posted in the [TOC box folder](https://ibm.ent.box.com/folder/132347152466)
