### ISSUE TITLE
[Lead space] Create medium variation design specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5256]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the `Lead space` design specs

> so that I can:
correctly create / change the `Lead space` component 

#### Additional Information
- Design specs can be found here https://ibm.ent.box.com/folder/94761007991?s=d9jey3rlfxqmxu059f0x9dtcx7f5ehuh

There's an extended file named **component--lead-space--design-specs--v2.0** and also a simplified file named **component--lead-space--simplified-design-specs--v2.0**

Both files are as .sketch and .pdf.

#### Acceptance Criteria
- [x] A Sketch file is created or updated with the `Lead space` design and specs
- [x] Create a Box folder for the `Lead space` (if not already there)
- [x] The design specs and pdf version are added to the Box folder 
- [x] Update the Agile Board epic with the spec link
- [ ] Add Box folder link to the website content if it exists

**Comment by DragosRistici** [comment]
Design specs can be found here https://ibm.ent.box.com/folder/94761007991?s=d9jey3rlfxqmxu059f0x9dtcx7f5ehuh

There's an extended file named **component--lead-space--design-specs--v2.0** and also a simplified file named **component--lead-space--simplified-design-specs--v2.0**

Both files are as .sketch and .pdf.
