### ISSUE TITLE
Carbon for ibm.com Rules definition

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5258]
Digital Design Squad would like to provide a tool to Offering Managers and web site builders that will help them determine whether their Carbon for ibm.com site complies with the guidelines.  This issues is to begin researching and defining the business rules and report back to the team.

#### Additional Information
- [Carbon for ibm.com rules documentation folder](https://ibm.ent.box.com/folder/132206545552)

#### Acceptance Criteria
- [ ] Proposed Rules summarized and presented to the leads

**Comment by jeffchew** [comment]
Closing this issue in favor of https://app.zenhub.com/workspace/o/carbon-design-system/carbon-for-ibm-dotcom/issues/5625.

**Comment by jeffchew** [comment]
@RobertaJHahn not sure if you closed out sprint 6 yet, can probably close this in part of that. I have another issue to track the creation of more rules which we discussed this morning.

**Comment by RobertaJHahn** [comment]
@jeffchew I just closed out sprint 21-06.  Closed this issue as part of the current sprint.
