### ISSUE TITLE
Web component: Lead space medium variation Visual QA

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5259]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Lead space`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- [Visual Designs & Functional Design Specs Box folder link](https://ibm.ent.box.com/folder/94761007991?s=d9jey3rlfxqmxu059f0x9dtcx7f5ehuh)
- Dev Issue (#5231)

 #### Tasks
Ensure the `Lead space` component has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by andysherman2121** [comment]
@DragosRistici The deploy previews are up in the PR!
