### ISSUE TITLE
[Featured Card group]:  Determine the name of the new DDS component 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5279]
#### Overview
This component was designed and code submitted behind a feature flag by AEM.  They named it `Promo Group`, but this may not be the best component name within the Carbon for ibm.com repo.  

#### Design spec from Jina: 
https://ibm.box.com/s/yh1r97n9qr9d6rd5jhz79c7vxqx7uhan

Reference build from HC: 
https://pages.github.ibm.com/MSC-Cloud/hc_fractal/components/detail/8b--cool-gray-10.html

####  Acceptance Criteria
- [x] Work the DDS team members to define the component name

**Comment by RobertaJHahn** [comment]
@photodow @shixiedesign I noticed that the issues for this Featured Card group were not created.  I am creating them now.  James, the notes in the original issues says that you are aware of this work and started on it.  I have assigned it to this sprint, 21-04.

**Comment by photodow** [comment]
1. New card decorator: `Card in card`
2. Modify `Cards group` to take a featured `Card in card`
    - Add example page to storybook's `Cards group` story with `Cards group — with card in card`


___

**Considerations for the future**. 
*  Add grid gutter types to `Cards group`.
    - collapsed (`1px` border)
    - condensed (`2px` gutter)
    - hanging (left hangs, right `16px`)
    - default (`32px` no hang)
*   Add column count to `Cards group`. (e.g. `2`, `3`, `4` to start with)
*   Replace `Card` with `Cards group` in `Content group — with cards`.

**Comment by oliviaflory** [comment]
Added [Card in card](https://ibm.ent.box.com/folder/132489332751)
Added [Card group](https://ibm.ent.box.com/folder/111654108347?s=r4nt1w1fe2gnuqn6m9gac48tll7jq5pl) example of card group with feature card to Box folder

*might need a little clean up...
