### ISSUE TITLE
[Card group]: Create the functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5281]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Card group` functional specs 

> so that I can:
so that I can properly code the `Card group` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5210 )**
 - Designs provided by AEM
 - Development issue (#5280 )
- Only 1 **Card in card** is allowed

### References
Jina's old spec
https://ibm.box.com/s/yh1r97n9qr9d6rd5jhz79c7vxqx7uhan

Reference build from HC: 
https://pages.github.ibm.com/MSC-Cloud/hc_fractal/components/detail/8b--cool-gray-10.html

"Featured card group" was tracked previously here: 
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4294

Updated [Card group spec](https://ibm.ent.box.com/folder/111654108347?s=r4nt1w1fe2gnuqn6m9gac48tll7jq5pl)

#### Acceptance criteria
 - [x] Documented `Card group` functional specifications
 - [x] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [x] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by photodow** [comment]
Updated: https://ibm.box.com/s/nebuvxryzaw00cknopufvskxdmyyochr
