### ISSUE TITLE
v1.16.1: Limited scope testing of a Sev 1 fix included in the release - Prod QA and accessibility testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5301]
#### User Story

> As a `[user role below]`:
ibm.com Masthead user 

> I need to:
have an urgent fix for a bug involving the Masthead Search typeahead feature that has been tested for Tier 1 browsers and platforms

> so that I can:
use the Masthead without having my query term overwritten 

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1, 13.3 and 14
- Browsers to be tested:  **Desktop:** Chrome, Firefox, Safari, Edge, **Mobile:** Chrome and Safari  **Tablet:** Chrome and Safari
- [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- **Limit the scope of the testing to Masthead (Prod QA and Accessibility) on the Tier 1 browsers, operating systems and devices.  React version only**
- Dev issue (#5287 ) 
- **React (Storybook): https://ibmdotcom-react-staging.mybluemix.net and React (NextJS): https://ibmdotcom-nextjs-staging.mybluemix.net **

#### Acceptance criteria
- [ ] All Tier 1 browser versions are tested
- [ ] All Tier 1 operating systems are tested
- [ ] All Tier 1 devices are tested
- [ ] Defects are recorded

**Comment by Praveen-sr** [comment]
@RobertaJHahn I have tested Masthead on react version on tier 1 browsers, search and mega menu looks good.
 Accessibility testing is in progress, we'll have an update by EOD.

**Comment by RobertaJHahn** [comment]
Testing finished.  No issues.  release approved.
