### ISSUE TITLE
Corporate Masthead - Specify what is the currently selected element in a L1 menu

### ISSUE THREAD

**Issue by AlexandruTasca** [carbon-design-system/carbon-for-ibm-dotcom#5302]
### The problem
Corporate Masthead component does not offer an attribute inside mastheadL1Data  to specify what is the currently selected element in the L1 menu.

### The solution
For Masthead component - add an attribute inside mastheadL1Data that specifies (similar to selectedMenuItem available for L0) what is the currently selected element in a L1 menu.

### Additional information
Example:
const mastheadL1Props =
{
	title: "IBM Academy",
	titleLink: "http://ibm.biz/academy",
	titleEnglish : "IBM Academy",
	eyebrowText: string,
	eyebrowLink: string,

	selectedMenuItemL1: "My Learning",

	navigationL1: [
		{ 
			hasMenu: false,
			title: "Welcome to IBM Academy",
			titleEnglish : "Welcome to IBM Academy",
			url: "http://ibm.biz/academy/welcome"
		},
		{ 
			hasMenu: false,
			title: "My Learning",
			titleEnglish : "My Learning",
			url: "http://ibm.biz/academy/mylearning"
		},
		{ 
			hasMenu: false,
			title: "My Profile",
			titleEnglish : "My Profile",
			url: "http://ibm.biz/academy/myprofile"
		},
		{ 
			hasMenu: false,
			title: "Support",
			titleEnglish : "Support",
			url: "http://ibm.biz/academy/support"
		},
	]
}

The menu option "My Learning" should appear highlighted (selected)

**Comment by AlexandruTasca** [comment]
When a menu option (other than the first / leftmost element) is shown as selected the first / leftmost element should no longer be highlighted.
This first / leftmost option is always displayed in bold (so that user is aware about the applications it is using)
![image](https://user-images.githubusercontent.com/79101332/113139174-0dedcc00-9227-11eb-9853-7677d50ff23c.png)

**Comment by DragosRistici** [comment]
<img width="1330" alt="Screenshot 2021-03-31 at 15 23 22" src="https://user-images.githubusercontent.com/48327647/113143640-0b926e80-9235-11eb-874b-53d946069073.png">
