### ISSUE TITLE
[Content item horizontal with media]

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5303]
Previously known as "9. Horizontal item - with media " 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/16327f60-65fa-435b-aa2d-d8f39e52a92c)

#### Additional Information
- media plays inline.  Image just displays.  
- options:  media left, media right
- [Content item horizontal functional specs](https://ibm.box.com/s/64h13x3utcps7lva14abxbx5t41xx9w1)
-   Development Hybrid Cloud:  Ian

**Comment by RobertaJHahn** [comment]
Issues needed:  Func specs, wc dev issue, Visual QA, Prod QA
