### ISSUE TITLE
[Card in card] 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5304]
A stand alone component in Storybook. This is a dependency of Cards group variation requested by AEM (previously Featured card group)

**This component is being developed by HC team. Ref. Putra.**, estimated to be 3 points. 

### Final design spec

Link to design spec [Box folder](https://ibm.ent.box.com/folder/132489332751?s=jad2fd65p56odcme9aoy1lgmuo1xaifu)
Link to Functional specs [Box doc](https://ibm.box.com/s/zd6rq29aolbwr5hf574nxf4jli4z5slj)  

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/aeef7838-3cd6-4e95-8c92-db8c0e748b71)

### FA notes
- Video should open in Lightbox media viewer 
- Whole card is clickable, aka hover on image/video would trigger `hover` state of "inset" text card
- Card icon should follow current CTA functionality, allowing multiple icon based on link type (email, external link, link, etc)
- Media should be 16x9 on all breakpoints except `sm`, where it is 4x3
- Potentially repurpose CTA - feature https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-cta--feature

**Comment by oliviaflory** [comment]
Updated the spec file on box to include additional information after the review on 3/1/20:

- Interactive states
- with grid overlay to see alignment

**Comment by proeung** [comment]
@shixiedesign @oliviaflory Thanks for updating this ticket to include the FA notes and design spec file.

Here's the JIRA ticket (https://jsw.ibm.com/browse/HC-1647) of this work that the HC team is using to track this contribution work on our end. cc: @RobertaJHahn
