### ISSUE TITLE
[Tabs extended - with media] a.k.a content item horizontal with media - in tabs

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5305]
### Overview

Final design spec: https://ibm.box.com/s/ios0b4wzrkxou1aquxitacngx4nyz345

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/b02b56f1-349e-41d9-a460-4612bdf9c29b)
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/5977c976-bee3-4f78-9724-3f2772a306b9)

### Dev
Assigned to Ian, estimated to be 5.

----
#### BA additional info

**Tabs extended** `ui`
![image](https://user-images.githubusercontent.com/3793636/110023769-28e62280-7cf3-11eb-9d50-af5e4fe9c6c0.png)

**Tabs extended — with media** `block` `layout`
![image](https://user-images.githubusercontent.com/3793636/110023782-2f749a00-7cf3-11eb-9dba-08e80cb7ba5e.png)

> I'm going to suggest we don't build the `section` level equivalent of these components since it's simply putting `content section` together with these. Definitely open to hearing others' opinions on this though.
- [Tabs extended with media functional specs](https://ibm.ent.box.com/folder/133803243554?s=3sun8lo3gu2b4uaa4oxgpxrqit1m7t6i)

**Comment by RobertaJHahn** [comment]
Issues needed:  component naming for the tabs, Func specs, wc dev issue, Visual QA, Prod QA
