### ISSUE TITLE
[Card in card]: Create the functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5307]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Card in card` functional specs 

> so that I can:
so that I can properly code the `Card in card` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5304 )**
 - Designs provided by AEM
 - Development issue (#5308 )
Link to design spec [Box folder](https://ibm.ent.box.com/folder/132489332751?s=jad2fd65p56odcme9aoy1lgmuo1xaifu)

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/aeef7838-3cd6-4e95-8c92-db8c0e748b71)

- Video should open in Lightbox media viewer 
- Whole card is clickable, aka hover on image/video would trigger `hover` state of "inset" text card
- Card icon should follow current CTA functionality, allowing multiple icon based on link type (email, external link, link, etc)
- Media should be 16x9 on all breakpoints except `sm`, where it is 4x3
- Potentially repurpose CTA - feature https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-cta--feature

#### Acceptance criteria
 - [ ] Documented `Card group` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by photodow** [comment]
File created: https://ibm.box.com/s/zd6rq29aolbwr5hf574nxf4jli4z5slj
