### ISSUE TITLE
Web Components: [Card in card image variant] Visual QA

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5311]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Card in card image variant`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- [Card in card Box folder](https://ibm.ent.box.com/folder/132489332751?s=jad2fd65p56odcme9aoy1lgmuo1xaifu)
- Development of React version will be done later.  
- Web Component Dev issue (#5308 )
- Storybook link (TBD)

 #### Tasks
Ensure the `Card in card image variant` component has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by shixiedesign** [comment]
Hey Dragos I took a pass on Card in card visual QA but I should hand it back to you for next round. Putra pinged me so I took a look tonight. Lemme know if you have any questions! https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5419

**Comment by shixiedesign** [comment]
FYI @DragosRistici we are rushing to get these merged for India team to start QA so I took another look at this guy. It was good. So this is off your plate now. Thanks!
