### ISSUE TITLE
[Content item horizontal with media in tabs]: Determine the name of the new DDS component

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5313]
#### Overview

This component is mostly the tabs shell. We could potentially swap out the content within each tab to other components (eg. pictogram card group on one of the Products landing pages Gui worked on in the past). So the name might wanna be "Tabs"-forward. Maybe `Content section - Tabs`? Kinda like `Content section - Carousel`? 

Final design spec: https://ibm.box.com/s/ios0b4wzrkxou1aquxitacngx4nyz345

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/b02b56f1-349e-41d9-a460-4612bdf9c29b)

**Note:** 
On mobile the component swaps out to an accordion. Should we handle it on our component level or adopters do the swapping? Some times tabs on mobile work. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/5977c976-bee3-4f78-9724-3f2772a306b9)

####  Acceptance Criteria

- [ ] Work the DDS team members to define the component name

**Comment by photodow** [comment]
Jotting down some quick notes while it's in my head...

— We probably want to break this down...
    — Is `section` level necessary, or can we provide `block` level and let teams put it into a `content section`?
— `Block` level is necessary
— Generalize the `tabs`/`accordion` breakpoints and allow any children/content in.
— After generalizing it do we still need an option with `content item horizontal with media`?
— will this need to live within table of contents vertical, or can we safely say no?
— This is more than just `tabs`, it's a cool intersection between `tabs` and `accordion`.


Jotting some chicken scratch names down... (should ideate in mural maybe)
— Enhanced tabs `block` `ui`
— Expressive tabs `block` `ui`
— Content section — tabs `section` `layout`
— Enhanced tabs section `section` `layout`
— Tabs section `section` `layout`
— Content block with tabs `block` `layout` *(maybe if we want an option with the `heading-05` content block and paragraph)*

**Comment by photodow** [comment]
**Tabs extended** `block` `ui`
![image](https://user-images.githubusercontent.com/3793636/110023769-28e62280-7cf3-11eb-9d50-af5e4fe9c6c0.png)

**Tabs extended — with horizontal content** `block` `ui`
![image](https://user-images.githubusercontent.com/3793636/110023782-2f749a00-7cf3-11eb-9dba-08e80cb7ba5e.png)

> I'm going to suggest we don't build the `section` level equivalent of these components since it's simply putting `content section` together with these. Definitely open to hearing others' opinions on this though.

**Comment by RobertaJHahn** [comment]
@photodow does that mean I would rename the existing Content item horizontal to one of the 2 components listed above, then create a new epic for the other?

**Comment by photodow** [comment]
Yeah, that works for me. Thanks @RobertaJHahn

**Comment by shixiedesign** [comment]
Hi @RobertaJHahn yep, and enginneers may start building.
