### ISSUE TITLE
[Tabs extended - with media] functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5314]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Tabs extended - with media` functional specs 

> so that I can:
so that I can properly code the `Tabs extended - with media` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5305 )**
 - Designs provided by AEM
 - Development issue (#5422 )

#### Acceptance criteria
 - [ ] Documented `Tabs extended - with media` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by RobertaJHahn** [comment]
Scheduled to review in the March 30 Sprint Review meeting.

**Comment by photodow** [comment]
Here is the link...

https://ibm.box.com/s/3sun8lo3gu2b4uaa4oxgpxrqit1m7t6i
