### ISSUE TITLE
Component library housekeeping 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5321]
Component library clean up includes the following 3 buckets of tasks. 
Designer assignment is tracked in airtable https://airtable.com/tbllQKHjvgxJnOdfz/viwD9UDFUCPRMOfpq?blocks=hide

FYI @RobertaJHahn 

### 1. Updates component spec files 

- Names (should all say "components", not patterns)
- Check tokens 
- Connect to expressive theme as much as possible
- Check that horizontal rules are made with `rectangle` not `line` so layer style can be applied 

**Check aspect ratios:**

- CTA cards should be 2x1, Image (include video) cards
- image 4x3, card part 2x1

**Address a few sweeping changes to all components** 

- Check and add spec for `Text width: _ col - 32px padding-right, max 640px` (Reason: when text spanning 5-8 col is not lining up vertically to content on rest of the page, doesn't impact `sm`)
- Vertical spacing update from AEM #5094: spacing below section headers from 48px to 32px. Update in components. Update wiki page 
- Vertical spacing update from AEM #5094: 2nd-tier spacing from 96px to 64px. Update in components
- Media in content blocks (a few rules, depend on context) (MVP do screenshots and wiki page) 

### 2. Audit Storybook 

- QA every component against design spec 
- Storybook: https://ibmdotcom-web-components.mybluemix.net/
- Storybook (secondary): https://ibmdotcom-react.mybluemix.net/
- File bugs via ZenHub
- Change names to sentence case - write an issue for name sweep in Storybook (add to issue ###)

### 3. Create "Component overview" sketchfile 

- Goal of the file is to give adopters a place to start, and create less variations in their designs
- Abstract: https://share.goabstract.com/1982afd1-a28c-443d-ac64-4588079fafca
- Copy+paste a few examples per component into Component Overview sketchfile
- Get a representative default, not edge cases
- Keep specs of the components included 
- Get xlg, md, sm. No need for all breakpoints unless it changes unexpectedly. 
- 0-3 variants if needed
- This file is not a replacement for spec files 
- Would something like this be creating more work for us to maintain and open the door for something else to become outdated? How does this differentiate from the inventory, or design kit?

**Comment by oliviaflory** [comment]
Share the [Rename It](https://renameit.design/sketch/) plugin for Sketch, could come in handy when trying to rename all the `pattern` artboards to `component` as we go through clean up

Steps:
- Select all artboards
- Plugins / Rename it / Find and replace layers/artboard names
- Type in pattern for `Find` input
- Type in component for `Replace` input
- Enter!

https://user-images.githubusercontent.com/45692622/109723239-cf0f1c80-7b7b-11eb-835d-9b47aa55485c.mp4
