### ISSUE TITLE
Error while importing Footer

### ISSUE THREAD

**Issue by Kpal22** [carbon-design-system/carbon-for-ibm-dotcom#5322]
Hi, while using `import '@carbon/ibmdotcom-web-components/es/components/footer/footer-container'` in my angular 9 app, I'm getting this error while starting the standalone application locally
![image](https://user-images.githubusercontent.com/45649979/109643642-84d96b80-7b7a-11eb-81cc-ae8a84ba1dd7.png)

**Comment by jeffchew** [comment]
@RobertaJHahn FYI, adding this to the `v1.17.0` release, this is slated to be merged.
