### ISSUE TITLE
Table of contents navigation hidden in combination with header and/or navigation

### ISSUE THREAD

**Issue by skycryer** [carbon-design-system/carbon-for-ibm-dotcom#5323]
## Detailed description

> Describe in detail the issue you're having.
When scrolling down the page or klick on the ToC navigation points the first ToC Navigation points get hidden from the navigation. We use Navigation and Header from Carbon on our page. And the Navigation point spacing top is hardcoded and because of Web Component we can not update it. Should be a variable so we can set what we need.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Table of contents

> What did you expect to happen? What happened instead? What would you like to
> see changed?
- The First ToC Navigation should still be visible
- The padding top on bx--tableofcontents__desktop should be a variable so it can be set/overwritten on project need. So it would support versions with header/navigation, a mix, only ne or nothing.

> What browser are you working in?
Chrome, Safari, Firefox, Edge

> What version of Carbon for IBM.com are you using?
1.16

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
April, CMS Project

## Steps to reproduce the issue

1. Add a header
2. add a L1 Navigation
3. Add ToC and components
4. scroll down the page and the first ToC Navigation Point will be hidden

[Link to Slack conversation](https://cognitive-app.slack.com/archives/GTKP57FMJ/p1613413039002200)

**Comment by RobertaJHahn** [comment]
@skycryer  could you provide a screen shot and/or a link to the environment where this behavior is happening.  Thanks

**Comment by skycryer** [comment]
<img width="842" alt="Screenshot 2021-03-02 at 16 06 33" src="https://user-images.githubusercontent.com/3725699/109670876-d7fbf000-7b73-11eb-9235-0255536af037.png">
<img width="1000" alt="Screenshot 2021-03-02 at 16 06 22" src="https://user-images.githubusercontent.com/3725699/109670880-d9c5b380-7b73-11eb-87c2-c1c3a5463ed9.png">

Here are some screens, for a link to the testing environment please contact Greg Johnson from IBM CMS Team. He can share a link and give access info to the server.

**Comment by RobertaJHahn** [comment]
@skycryer Looks like this may not be an issue and can be fixed in configuration.  Andy will reach out.
