### ISSUE TITLE
[Content item horizontal with media] functional specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5333]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Content item horizontal with media` functional specs 

> so that I can:
so that I can properly code the `Content item horizontal with media` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5303 )**
 - Development issue (#5318 )
 - Visual Designs & Functional Design Specs Box folder link(TBD)

#### Acceptance criteria
 - [x] Documented `Content item horizontal with media` functional specifications changes
 - [x] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [x] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by photodow** [comment]
[Content item horizontal](https://ibm.box.com/s/64h13x3utcps7lva14abxbx5t41xx9w1) updated

Update to default https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5486
