### ISSUE TITLE
Web component: Content item horizontal with media Visual QA

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5334]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `content item horizontal with media`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- Dev Issue (#5318 )
- Storybook link provided by engineer in comments below

 #### Tasks
Ensure the `Content item horizontal with media` component has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by shixiedesign** [comment]
Reviewing PR https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5363
