### ISSUE TITLE
Content Group has extra spacing from empty item

### ISSUE THREAD

**Issue by skycryer** [carbon-design-system/carbon-for-ibm-dotcom#5344]
## Detailed description

i saw that on https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-content-group-horizontal--default behind the last child item a strange spacing from an empty bx--content-block__cta-row is there. After getting info from @asudoh that is is not a wanted behavior i create now this ticket.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
bug

> Is this issue related to a specific component?
Content Group horizontal

> What did you expect to happen? What happened instead? What would you like to
> see changed?
If no content is in this component the component should be hidden to avoid strange extra spacing coming from this empty component

> What browser are you working in?
Chrome,Firefox,Safari, Edge

> What version of Carbon for IBM.com are you using?
0.16, but it can be seen online, see link above

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
CMS, April

## Steps to reproduce the issue

1. Go to the link above
2. check inspector to see empty component adding spacing

## Additional information

<img width="1405" alt="Screenshot 2021-03-03 at 12 42 59" src="https://user-images.githubusercontent.com/3725699/109808952-09ce8e80-7c28-11eb-83a1-abcb7968456b.png">

**Comment by asudoh** [comment]
Thank you for reporting @skycryer! Seems that the problem will be fixed by #5263 and you can see it in action at https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-content-group-horizontal--default. Please let us know if you need the fix sooner than our next release and we can discuss if we should release a patch.

**Comment by RobertaJHahn** [comment]
The fix Akira mentions above is assigned to our March release.  The full release date is March 24.
