### ISSUE TITLE
Rename "Button" in WC Storybook to "Button extended"

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5345]
### Problem

Currently we have a [Button component on Web components storybook](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-button--default), also a [Button component on Expressive theme](http://carbon-expressive.mybluemix.net/?path=/story/buttons--sets-of-buttons). And no Button component in React storybook: https://ibmdotcom-react.mybluemix.net/

This is confusing because the design intent is - all Carbon core components in **expressive theme should be be provided via [Carbon expressive](http://carbon-expressive.mybluemix.net/?path=/story/buttons--sets-of-buttons).** Carbon core components should not be duplicated in Web components and React storybook for Carbon for IBM.com. 

### Proposed solution

- Triage is Button in web components storybook can be removed. 

Consolidated dependency on Carbon expressive would make sense to me, but I'm happy to hear dev perspective on if this is possible.

- If it cannot be removed:
1. it should be given a non-conflicting name
2. get design and functional spec, per regular components
3. then HIDE from storybook because it doesn't concern adopters

FYI @photodow @asudoh reference Slack conversation https://cognitive-app.slack.com/archives/GBG66T9NK/p1614737549054500

**Comment by shixiedesign** [comment]
Hey @IgnacioBecerra I imagine you might have question about this issue - because I also have a question on this: 

Looping in @photodow, maybe the correct name is `Button expressive`? I might have gotten distracted by `Tabs extended`. Button might be a different case. Just wanna double check with you what's the correct name here.

**Comment by photodow** [comment]
@shixiedesign `button expressive` sounds right to me. I would remove it from storybook since we don't want adopters using this `button`. I'm not even convinced we want to be using it...

**Comment by IgnacioBecerra** [comment]
Just to confirm, will this ticket be covering the removal of the `Button` story to ensure adopters don't use it?

**Comment by photodow** [comment]
@IgnacioBecerra removal and rename I believe.

**Comment by IgnacioBecerra** [comment]
@photodow Thinking about it, if we're getting rid of the story, is the renaming necessary? Currently the button is named `DDSBtn` in the code; we could rename the button to something like `DDSButtonExpressive`, but that's more on the coding side and adopters wouldn't know it exists, I think.

**Comment by photodow** [comment]
@IgnacioBecerra yeah, I would say so. We're building a system that works together. We may be removing it from storybook, but our developers, those contributing to the codebase, and our designers still need to be on the same page of what this component is. Everything has to be intentional. I'm personally not a fan of the DDS prefix, but if that's the coded naming convention for web components that'll work.
