### ISSUE TITLE
Create Test Component for Contribution Session

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#5349]
### The problem
Create DDSTestComponent

### The solution
Show example of how to make a PR for the contribution deep dive session

### Additional information
 - create test and must pass 80%
 - create storybook
 - add feature flag labels
 - ...

**Comment by jeffchew** [comment]
Closing this, thank you @RaphaelAmadeu @ariellalgilmore !
