### ISSUE TITLE
React: FeatureCardBlock Large - On hover the feature card, heading and the copy text is getting underlined.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5358]
## Detailed description

Issue: 
When user hover on the feature card, heading and the copy text is getting underlined.

Note: Its happening in all the places where the feature card large is used.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/8ea7d5d1-6d8d-4e70-8cdf-f8955ce87231)

**Comment by NSDrowned** [comment]
Hello @Praveen-sr, looks like it has been fixed. Can't replicate. Please retest.

**Comment by Praveen-sr** [comment]
@NSDrowned Re tested is on react, issue has been fixed.

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/7afabc34-9fe0-4ece-bc37-0ee7b61d5fea)

CC @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Closing based on Praveen's comments above.
