### ISSUE TITLE
[Content group - banner] functional specifications 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5368]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Content group - banner` functional specs 

> so that I can:
so that I can properly code the `Content group - banner` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#4753 )**
- This component is also known as Feature Promo - text
 - Development issue (#5506 )
 - [Visual Designs & Functional Design Specs Box folder link](https://ibm.ent.box.com/folder/133368674077?s=tqp7c0wm99ha0b7jrm0sqhq3whwdjv84)

#### Acceptance criteria
 - [x] Documented `Content group - banner` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by photodow** [comment]
Functional notes for `Content group — banner`...

- 1 or 2 CTAs
- Consider optional content group horizontal rule, or does Layout do that for us?
- CTA types allowed all but `jump`. (consider how emails plays out when added)
- CTA style allowed only text
- Content group, link list, maybe nested layout
- `Content group — banner` can be applied to content section to get a section level component
- Guidelines to be written around theming usage. Follows page parent/page theme. Enabled for all themes though.

**Comment by photodow** [comment]
Here is a link to the functional specs.

https://ibm.box.com/s/ay2eno7z1y5a0wkuvj4h6wqrcit3bbkn

**Comment by RobertaJHahn** [comment]
functional specs reviewed in the Mar 22 engineering meeting.  They were able to size the work, but had some questions that they will take offline with James.  Closing.
