### ISSUE TITLE
Components affected by AEM layout spacing update

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5376]
Based on Kirby's issue #5094, the design team did a component audit. We identified the following components that will be affected by this spacing change: 

## 1. Spacing below section headers from 48px to 32px
This update will affect spacing within 

### A. **Content Blocks** between heading-05 and body copy 
See green arrow for emphasis
<img width="1085" alt="Screen Shot 2021-03-04 at 3 03 32 PM" src="https://user-images.githubusercontent.com/45692622/110038584-ea119600-7d0d-11eb-9718-493416234056.png">

List of components:
- [ ] Callout with media
- [ ] Content block (hidden)
- [x] Content block cards ??? *has more spacing*
- [x] Content block cards with image???
- [x] Content block cards with videos???
- [x] Content block media + (with aside elements)
- [x] Content block mixed + (with aside elements)
- [x] Content block segmented (Default, with video, with aside elements)
- [x] Content block simple (Default, image, video, aside elements)
- [x] CTA section (default, with content items, with link list)
- [ ] Lead space block ??? (Do we want to update to be consistent?)
- [ ] Logo grid ??? 

### B. **Content Groups** between heading-04 and body copy
See green arrow for emphasis
![Screen Shot 2021-03-05 at 5 02 45 PM](https://user-images.githubusercontent.com/45692622/110179145-8eaadb00-7dd5-11eb-8209-1fb022d0695d.png)

List of components:
*I believe all content groups are already 32px?* 

---

## 2. 2nd-tier spacing from 96px to 64px
This update will affect spacing between:

### A. Spacing between Content Block Content Group
See green arrow for emphasis
<img width="1113" alt="Screen Shot 2021-03-04 at 3 09 36 PM" src="https://user-images.githubusercontent.com/45692622/110039248-f3e7c900-7d0e-11eb-93b5-2535d49d6de8.png">

List of components:
- [x] Content block media (with aside elements)
- [x] Content block mixed (with aside elements)
- [x] Content block segmented (default, with video, aside elements)
- [ ] Content group (top spacing) (hidden component)

### B. Spacing between two Content Groups
See green arrow for emphasis
<img width="834" alt="Screen Shot 2021-03-04 at 5 22 18 PM" src="https://user-images.githubusercontent.com/45692622/110039281-fcd89a80-7d0e-11eb-9f58-ba1f966c4592.png">

List of components:
- [x] Content group cards (top spacing)
- [x] Content group simple (default, with image, with video) (top spacing)
- [x] Content block media (with aside elements)
- [x] Content block mixed (with aside elements)
- [x] Content block segmented (default, with video, aside elements)

**Comment by RobertaJHahn** [comment]
@shixiedesign Is there more work to be done here or can this be reviewed in the engineering meeting next week?

**Comment by shixiedesign** [comment]
Hi @RobertaJHahn part of it is. 

### Reduce spacing below `heading-05` from 48px to `layout-03` (32px)

- Content block: spacing under header

### Reduce spacing above `heading-04` from 96px to `layout-05` (64px)

- Content group cards: top spacing
- Content group simple (default, with image, with video): top spacing
- Content block media (with aside elements)
- Content block mixed (with aside elements)
- Content block segmented (default, with video, aside elements)

**Comment by shixiedesign** [comment]
This issue is possibly done from design spec update side. Waiting on QA'ing dev work.
