### ISSUE TITLE
[Scroll animation] Storybook example is not on grid 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5380]
Scroll animation works well but the  example in storybook shows layout that's not on the grid. Please see screenshot below. The Table of Content component should be used in the left 3 column. In current [example story](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-scroll-animations--fade-once), it is showing in 4th column, nudging all things off grid.   

### Current

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/2bbea282-4fd1-4c9f-9ab2-32fc56477aed)

### Expected

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/4146c9e3-e75f-4a3c-b0f9-aec0fc1d1d95)

**Comment by RobertaJHahn** [comment]
Per Shixie, fixed.  Closing
