### ISSUE TITLE
CORS Error when creating Masthead

### ISSUE THREAD

**Issue by JacobWeinbren** [carbon-design-system/carbon-for-ibm-dotcom#5399]
## Brief Summary

Running the "Hello World" of Carbon for IBM throws a bunch of errors

`Refused to set unsafe header "origin"`
`GET https://1.www.s81c.com/common/v18/js/data/jsononly/gben.json 404`
`Access to XMLHttpRequest at 'https://login.ibm.com/v1/mgmt/idaas/user/status/' from origin 'http://localhost:8888' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
```
Failed Profile Network Call Error: Network Error
    at t.exports (main.js?ver=5.6.2:35)
    at XMLHttpRequest.h.onerror (main.js?ver=5.6.2:35)
```
`GET https://login.ibm.com/v1/mgmt/idaas/user/status/ net::ERR_FAILED`

## Detailed description

The setup is not too complicated. Carbon Design vanilla javascript is being packaged in webpack as a copy of the tutorial on the [sandbox example](https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/master/packages/web-components/examples/codesandbox/usage/webpack-basic).

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

I am not sure if it is a bug or general issue, as as running a masthead seems to load in a bunch of files from IBM. Maybe this is an intentional feature of Carbon Design for IBM as part of how chunking is done? Ideally it would not load any IBM services unless requested.

> Is this issue related to a specific component?

The masthead on the UI Shell. Or more specifically `<dds-masthead-container brand-name="Lorem Ipsum"></dds-masthead-container>`

> What browser are you working in?

Chrome

> What version of Carbon for IBM.com are you using?

1.1.1

**Comment by RobertaJHahn** [comment]
@kennylam Assigning to you as part of Fireline.

**Comment by JacobWeinbren** [comment]
@RobertaJHahn thanks for adding these tags. Sorry, I am not really sure, what does 'Airtable Done' mean?

**Comment by jeffchew** [comment]
Removing @kennylam and adding @IgnacioBecerra and @ariellalgilmore for the current fireline team.

**Comment by jeffchew** [comment]
> @RobertaJHahn thanks for adding these tags. Sorry, I am not really sure, what does 'Airtable Done' mean?

@JacobWeinbren this is a way for our team to internally track issues.

**Comment by ariellalgilmore** [comment]
Hi @jacobweinbren. We took a look at this issue and can't reproduce the error. Looks like you are using an older version though, would you try updating to our latest and see if you can still reproduce? Thank you!

**Comment by JacobWeinbren** [comment]
Thank you @jeffchew. Hi @ariellalgilmore

I made an update with the old versions and this is where the errors would come up.
https://github.com/JacobWeinbren/miliband/commit/17fc132c43ab721239bd0a1cc67e53449a397487

But when I run `npm update`, now it is broken

I just get the following error. I think I have broken something but I am not sure what.
```
main.js?ver=5.7.1:2 Uncaught ReferenceError: process is not defined
    at main.js?ver=5.7.1:2
    at main.js?ver=5.7.1:769
    at main.js?ver=5.7.1:769
```

You can see the updated version here
https://github.com/JacobWeinbren/miliband/commit/9a301d04e824f2f683c1366ed5367e1a8c75157b

Also, I did not add this originally but I am running this in a WordPress theme. I am not sure if it complicates things, but I should have included that.

Thanks,
Jacob

**Comment by ariellalgilmore** [comment]
Hi Jacob,

Thanks for the updates! The error looks like possibly a configuration error with webpack and wordpress. We were able to run your code locally without this error.

Hopefully this link can help you: https://stackoverflow.com/questions/30239060/uncaught-referenceerror-process-is-not-defined or possibly this one: https://stackoverflow.com/questions/41359504/webpack-bundle-js-uncaught-referenceerror-process-is-not-defined

**Comment by ariellalgilmore** [comment]
oh also @IgnacioBecerra mentioned after looking at your website that actually maybe Carbon's ui-shell might fit better if you wanted to take a look: https://www.carbondesignsystem.com/components/UI-shell-header/usage/

**Comment by JacobWeinbren** [comment]
Toda - this is very helpful/useful. I am going to close this thread as this has solved the problem for me and now I know more about how webpack works.
