### ISSUE TITLE
[Plex Fonts] Investigation of font-face setting

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5404]
#### User Story

> As a `[user role below]`:
Carbon for IBM.com developer

> I need to:
understand how font-face is set up in Carbon for IBM.com

> so that I can:
have a better idea of how to proceed with setting font-face based on selected language

#### Additional information

 - There is a related issue for specifically the Masthead/Footer (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5025), but there needs to be an idea if there is additional work to be done on this and what amount

#### Acceptance criteria
 - [ ] Documentation on font handling within Carbon for IBM.com
 - [ ] Create issues based on research on how to proceed with setting language specific fonts in Carbon for IBM.com

**Comment by asudoh** [comment]
Here's my finding:

* In Plex, there are two types of fonts, one is concatenated and another is split. Seems that the former one for Korean language version is [too big](https://unpkg.com/browse/@ibm/plex@5.1.3/IBM-Plex-Sans-KR/fonts/complete/woff2/unhinted/IBMPlexSansKR-Regular.woff2), OTOH the latter one has [too many files](https://unpkg.com/browse/@ibm/plex@5.1.3/IBM-Plex-Sans-KR/fonts/split/woff2/unhinted/). Both have significant performance hit (the initial download size for the former and the number of HTTP transactions for the latter) and from my such finding, I'd stay away from using web fonts version of Plex for CJKT languages.
* Usage of the the new language versions of Plex font requires additional [`@font-face` at rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face):
  1. Seems that [Carbon core maintains ones for some extra languages](https://github.com/carbon-design-system/carbon/blob/v10.30.0/packages/type/scss/font-face/_mono.scss) for limited languages. Above performance problem may make Carbon core stay away from adding CJKT languages there.
  2. [IBM/plex repo](https://github.com/IBM/plex) maintains Sass file for the `@font-face`. One for concatenated version can be found at https://unpkg.com/browse/@ibm/plex@5.1.3/scss/sans-kr/regular/_index.scss and one for split version can be found e.g. at https://unpkg.com/browse/@ibm/plex@5.1.3/scss/sans-kr/regular/_kr-00.scss.
