### ISSUE TITLE
AEM Adopter: [Card Group] use case with 4 cards

### ISSUE THREAD

**Issue by sbahl1** [carbon-design-system/carbon-for-ibm-dotcom#5406]
Type : Feature Request
Adopter: AEM
Description: In the events where there are 4 cards in a card group, the current **card grouping with card group default** and **content block cards default** is not usable for AEM purposes.  Requesting to create a variation where if there are 4 cards, they can be viewed as 2 columns with 2 rows and 2 cards per column (4 by 4 matrix)

 For all other combinations, existing designs and story book elements work for AEM Team

### Design spec 
https://ibm.box.com/s/r4nt1w1fe2gnuqn6m9gac48tll7jq5pl

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/0ef530a7-b7f5-48ac-a028-d4181d97372c)

This logic doesn't apply to: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/9bc1acb2-03d1-441e-8bba-631a4aebf859)

### Functional spec
https://ibm.box.com/s/rpki0q23o6wyrtvx22je74tbfx1xkcsn

**Comment by RobertaJHahn** [comment]
Convert to an epic and create design spec issue, func spec update, DDS engineering, Visual QA, Prod QA, website issue

**Comment by shixiedesign** [comment]
Met with team. Agreed to allow new knob/prop: 
Number per row: [ 2 | 3 | 4 ]

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/6317235d-ddf8-47ef-aec6-3b2e3f687762)
