### ISSUE TITLE
Video component within Content block simple with video should be using a max width of 640px

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#5423]
## Detailed description

> According to the design specs the video component within the Content block simple with video should have a max-width of 640px. Right now on Storybook, it doesn't appear to have a max-width applied. 

## Additional information

- Content block simple with video not using a max-width: https://ibm.box.com/s/fjt3gl9b3qkyhhshin2z74az62bz795x
- Content block simple with image appears to be using a max-width of 640px: https://ibmdotcom-react.mybluemix.net/?path=/story/components-contentblocksimple--with-image
- Design specs state that video should have a max-width of 640px: https://ibm.box.com/s/fjt3gl9b3qkyhhshin2z74az62bz795x

**Comment by RobertaJHahn** [comment]
dev - test in both react and WC to see where the problem is.

**Comment by shixiedesign** [comment]
hey @RaphaelAmadeu Web component fixed, but problem still in React https://ibmdotcom-web-components-canary.mybluemix.net/iframe.html?id=components-content-block-simple--with-video
