### ISSUE TITLE
[Quote] Hanging quote and general alignment

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5433]
#### User Story

The specs state that the starting quote should hang off the left of the column, and all other text should be aligned to the column. 
![Screen Shot 2021-03-10 at 1.17.47 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/8ed563a8-62dc-4aba-84c6-466b2566e1cb)

Currently, the Quote component does not hang the starting quotation mark on the left side of the column. The starting quote is aligned to the column, and all other text is inset within the column structure.
![Screen Shot 2021-03-10 at 1.20.03 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/fa8ba9e9-ef07-4203-b93f-be8fa878e0ed)

### Question:
Is it possible for the starting quote to hang to the left of the column? 

1. If yes, this can be a development story
2. If not, we may need to update the visual specs, or a combination of spec + dev updates to achieve the desired outcome.

#### Additional information

 - Discovered this during our clean up
 - Potentially affects Call out quote specs

#### Acceptance criteria
 - [ ] Dev & design collaboration to understand how to achieve desired design intent
 - [ ] Specs and/or story updated
 - [ ] Dev and design review

**Comment by RaphaelAmadeu** [comment]
@oliviaflory 
I've opened a PR to address this issue.

**Comment by shixiedesign** [comment]
Also noticed `Callout` component could need some update to maintain the changing quote.
