### ISSUE TITLE
[Quote] closing quote

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5438]
### The problem

**Question:** Is it possible to avoid the closing quote being an orphan in Quote and Call out quote? 

Currently the closing quote is separated from the rest of the quote and able to be an orphan (single character on its own line) and that is generally considered a bad thing in design.
![Screen Shot 2021-03-10 at 5 06 10 PM](https://user-images.githubusercontent.com/45692622/110705172-0016cf00-81c4-11eb-9d17-a29cb5249bd3.png)

Ideally the closing quote would be on the same line as the last word in the quote/text block. Example:
![Screen Shot 2021-03-10 at 5 06 10 PM copy](https://user-images.githubusercontent.com/45692622/110705163-fc834800-81c3-11eb-8019-c858bf95db8e.png)

### The solution
I know we don't usually control line breaks, but curious if there was another solution we could consider.

### Additional information
Components: Quote and Call out quote

**Comment by kennylam** [comment]
@oliviaflory Is there a specific viewport size where this happens? I'm unable to reproduce.

**Comment by oliviaflory** [comment]
@kennylam Very specific at 320px and 696–704px so between medium/large breakpoint.

I was just curious if we had control over it, if not understand it's pretty specific pixels. I thought the closing quote was on it's own, but I could definitely be wrong!

<img width="682" alt="Screen Shot 2021-03-18 at 9 37 04 AM" src="https://user-images.githubusercontent.com/45692622/111635939-63a98980-87ce-11eb-95f8-81d2b30c5b6a.png">

**Comment by RobertaJHahn** [comment]
The team will be using recent metrics to determine the devices that will be in scope for support.  The decision will be made and may exclude this scenario.  Closing.

**Comment by shixiedesign** [comment]
Olivia’s comment with breakpoint range is just to say that specific to this quote,
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus est purus, posuere at est vitae, ornare rhoncus sem. Suspendisse vitae tellus fermentum, hendrerit augue eu, placerat magna.
The closing quote drops to new line at those range viewport. But obviously that’s not a real quote, and real quote can have different number of characters.

**Comment by RobertaJHahn** [comment]
@oliviaflory @shixiedesign Based on the engineering assessment, it looks like this will be a pain to fix.  Are you OK with delaying scheduling the work on this?

**Comment by shixiedesign** [comment]
Hybrid Cloud team has a fix for their library. Adjusting the view port size of this component never orphan the `closing quote`.   https://pages.github.ibm.com/MSC-Cloud/hc_fractal/components/detail/case-studies-quote-with-bg--cool-gray-10.html 

I don't think we ever assigned any dev. I'm okay with iceboxing until our dev backlog is lighter (scared it's never!) But prefer not closing.
