### ISSUE TITLE
[Quote] text width update

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5439]
### The problem

Address sweeping text width adjustments to remove percentage and utilize fixed padding.

### The solution

1. Text width Quote text
- [x] Update quote text width to remove % calculation and apply fixed padding in specs, see page 2 and 7

2. Attribute width 
- [x] Update attribute text width on `max, xl, lg, med` breakpoints to 8 column container -32px, max width of 640px, see page 2
- [x] Remove text width constraint on Attribute section, should span full width on `small breakpoint`, see page 7
![Screen Shot 2021-03-10 at 5 19 47 PM](https://user-images.githubusercontent.com/45692622/110706586-1aea4300-81c6-11eb-9d54-84f9fb921290.png)

3. CTA link
- [x] Remove any % calculated width, apply max width from spec document, see page 2
- [x] No width constraint in small breakpoint, see page 7

### Additional information

Updated [Quote design specs](https://ibm.ent.box.com/folder/110531199928?s=0hjsr1foe5y849xs6ixc5g25uf9lgjr6)

- Changes should be seen in Quote and Call out quote component.

**Comment by jeffchew** [comment]
@RobertaJHahn this should be sized, can we add to the next refinement meeting?

**Comment by jeffchew** [comment]
Closed this PR and will come back to scheduling this in a future sprint: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7535

**Comment by ljcarot** [comment]
@jeffchew Do you want this in Sprint 1 or later sprint?

**Comment by jeffchew** [comment]
> @jeffchew Do you want this in Sprint 1 or later sprint?

Good catch, I forgot to remove the sprint when moving back to `pending scheduling`.
