### ISSUE TITLE
Language Modal: German language title not correct

### ISSUE THREAD

**Issue by fabianklonsdorf** [carbon-design-system/carbon-for-ibm-dotcom#5452]
## Detailed description

> Describe in detail the issue you're having.

German (Deutsch) would be correct. Currently it is German(Deutsche)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug in translation file

> Is this issue related to a specific component?
Language Modal --> https://ibmdotcom-react.mybluemix.net/?path=/story/components-locale-modal--default

> What did you expect to happen? What happened instead? What would you like to
> see changed?
"Deutsche" should be changed in "Deutsch"

> What browser are you working in?
Firefox

> What version of Carbon for IBM.com are you using?
N.A.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
N.A.

## Steps to reproduce the issue

1. Step one
Open ibm.com/us-en
2. Step two
Scroll down
3. Step three
Open the language Modal and search for German
4. Step four
See the error

![Screenshot 2021-03-11 at 15 25 55](https://user-images.githubusercontent.com/47037236/110804916-e7202380-8280-11eb-8b55-a4ec1ea00c73.png)

## Additional information

- Screenshots or code
- Notes

**Comment by annawen1** [comment]
I have created a ticket in the translation team's trello board: https://trello.com/c/av5sj28D/203-german-language-title-not-correct

**Comment by annawen1** [comment]
@fabianklonsdorf If you have any questions or need follow up, you can reach out to the contact I sent you on slack.
