### ISSUE TITLE
Web Components and SEO Investigation

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5459]
#### User Story

> As a `[user role below]`:
IBM.com Developer

> I need to:
understand how Web Components are indexed by search crawlers

> so that I can:
understand how to best build web components that comply with popular search bots

#### Additional information

 - Google appears to be able to crawl web components
 - Should look into other crawlers, like Bingbot, Baidu, etc
 - an older article but may still have relevance: https://medium.com/patternfly-elements/web-components-and-seo-58227413e072

#### Acceptance criteria
 - [ ] Have a full understanding of how the various popular search crawlers search pages with web components
 - [ ] Any recommendations based on research

**Comment by jeffchew** [comment]
Some notes from @asudoh : 

Note on SEO testing; For Google https://search.google.com/search-console/welcome seems the right tool, though there is a process that the submitter owns the site. We may want to try this with our test page. One good news is that we can rest assured for `<a>`; The document clearly says that the search engine looks at the shadow DOM: 
https://developers.google.com/search/docs/guides/javascript-seo-basics, which means all `<a>`s in shadow DOM (e.g. one in CTA) are crawled. Searching for Baidu SEO checker all resulted in Chinese sites and couldn’t see if there is an official tool. Good if there is, otherwise we may end up seeing how Baidu crawls the site.

Some note on heading; We rely on custom tags (e.g. `<dds-content-block-heading>` to apply the right style to the heading, most importantly, its inner content. We may consider `<h1 slot="some-slot">`, however, `::slotted([slot="some-slot"])` can style only `<h1>` itself, not the descendants.

Another idea, though it’s large, is that I’ve had a feeling that content pattern does not much value being Web Components, given they are style-only components (except the video portion, etc.). From that perspective, the only merits being Web Components is the style isolation and less `<div>` soup. That said, we may come up with vanilla markup guide, possibly with examples in Storybook.

**Comment by jeffchew** [comment]
Confirmed that Googlebot has no problems crawling pages with web components: 
<img width="1830" alt="Screen Shot 2021-03-10 at 4 05 13 PM" src="https://user-images.githubusercontent.com/1641214/110851080-93acd600-827e-11eb-9eb8-d325fac8980b.png">

**Comment by jeffchew** [comment]
Bingbot does not seem to render web components based on a quick scan. This aligns more with the findings of the article posted above, where the lightDOM may need to have semantic markup available before render:

<img width="1521" alt="Screen Shot 2021-03-11 at 3 04 36 PM" src="https://user-images.githubusercontent.com/1641214/110851707-63196c00-827f-11eb-9815-020120c84480.png">

HTML that is crawled by Bingbot:
<img width="1320" alt="Screen Shot 2021-03-11 at 3 05 20 PM" src="https://user-images.githubusercontent.com/1641214/110851727-6876b680-827f-11eb-9568-262954c19cff.png">

**Comment by asudoh** [comment]
From Bing report that says they couldn't find our headings, I'm leaning more toward documenting how to add "SEO hints" to the page. For for example, pages can render hidden `<a>` (e.g. in their Handlebars code) along with `<dds-card>`.

**Comment by jeffchew** [comment]
As discussed as a group, we have determined that creating a prerender step is the way to approach this on the application side.
