### ISSUE TITLE
Video Description from Kaltura  - displayed in a modal - contains inline markup

### ISSUE THREAD

**Issue by Georg-Hauser** [carbon-design-system/carbon-for-ibm-dotcom#5461]
## Detailed description

> the modal rendering of a video-player contains a description, which contains inline markup - see https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-content-block-cards--with-videos 

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

According to Jeff Chew comes the descriptions from the Kaltura API, which already contains HTML markup. 

> Is this issue related to a specific component?

components-content-block-cards--with-videos -- but in general a videoplayer within a modal

> What did you expect to happen? What happened instead? What would you like to
> see changed?

that the markup is stripped from the webcomponent

> What browser are you working in?

Chrome

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

yes, PROD-Release of AEM MVE with 06.04

## Steps to reproduce the issue

1. open https://prod-publish.roks.cms.cis.ibm.net/topic/supplychain#anchor-48438963 or just clicking on the tile for "Farmer Connect + IBM" in -
2. clicking on the tile for "Farmer Connect + IBM" 
3. check the modal

## Additional information

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment]
Jeff is meeting with Media Center team to remove the HTML from the source rather than by DDS.  We can make the update at a later date.

**Comment by RobertaJHahn** [comment]
This is already fixed on our end.  Kaltura will also remove from the source.  Can close
