### ISSUE TITLE
[TOC Horizontal prev Anchor link] selected state hover

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5467]
## Detailed description

> Describe in detail the issue you're having.

Looks like the selected state blue bar is grayed out on hover, can we remove that?
![Screen Shot 2021-03-11 at 5 03 11 PM](https://user-images.githubusercontent.com/45692622/110863192-4f293680-828e-11eb-8304-b250bfa5ad8c.png)

<img width="429" alt="Screen Shot 2021-03-11 at 5 24 37 PM" src="https://user-images.githubusercontent.com/45692622/110863455-b515be00-828e-11eb-92f4-5cf54b410b8b.png">

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug – selected state hover maintains a grayed out 2px selected bar, but should hide on hover

> Is this issue related to a specific component?

[TOC Horizontal](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/5446/index.html?path=/story/components-table-of-contents--horizontal)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by ariellalgilmore** [comment]
This has been fixed. Closing this with screenshot below:

![Screen Shot 2021-04-12 at 12.56.12 PM.png](https://images.zenhubusercontent.com/5ee7ae1cc40147132b286905/35966dcd-7eaa-45a2-9ff5-a2ddbc41a33d)
