### ISSUE TITLE
[Filter panel] design-build-document new component 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5469]
## Filter panel - new component

This component has shown up in various forms in many new dotcom sites: 
- Products landing (Martin) https://www.ibm.com/products
- Dotcom search results (Martin) https://www.ibm.com/search?lang=en&cc=us&q=db2&tabType[0]=Products
- Cloud learn landing (Pavol Prok, [see a slightly outdated version here](https://xd.adobe.com/view/7dc2dc38-71d2-476f-8be6-570f178b04e0-2891/screen/1ed147c6-8f82-4bc7-9e39-0e2890462f18?fullscreen&hints=off ))
- Cloud case studies landing (Niko Georgantas)
- DAM (Seth Carnes)

### Key design considerations to sort out:

- Grid usage. This bar likely sits outside the grid
- Type size. Ideally 14px to reduce text line wrapping, which complicates expressive theme
- States. This bar need several states of expansion, toggle select, and a way to reset to default state
- Search. Many use cases have this bar in conjunction to search, citing users needing both to find what they are looking far.

### Initial & incomplete audit of existing designs: 

Only for visual reference. A complete audit is still needed.

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/b6f2b5e7-2e8e-4c76-b1fc-8727ee88db0a)

### Resources
[Filter panel](https://ibm.ent.box.com/folder/136914860547?s=19a0hjn61gh3qh59kbgxba43y8uymuqy) Design specs
[Filter group](https://ibm.ent.box.com/folder/137685560033) Design specs
[Input select](https://ibm.ent.box.com/folder/137327521624) Design spec
[Filter group](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Filter-group)  functional specs
[Filter panel](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Filter-panel)  functional specs
[Filer panel input select](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Input-select)  functional specs

#### Final designs
- [DDS Design Box folder link](https://ibm.box.com/s/19a0hjn61gh3qh59kbgxba43y8uymuqy)

**Comment by RobertaJHahn** [comment]
Next step:  Shixie will schedule a meeting to talk to the teams who would use this component to understand their needs.  Teams: ibm.com Search result page,  Products Landing page, Cloud Case Studies and DAM.

Can not prioritize at this time.  More information needed.

**Comment by shixiedesign** [comment]
Found these filter bar Carbon gatsby theme is exploring. 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/1d5dfca2-c255-46f1-a241-04d1eb2d7f79)
Not in build yet. 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/3f1773fa-14d0-4e1a-9442-f91d13b34bc3)

**Comment by photodow** [comment]
IBM Security has something over there that might be somewhat relevant to the conversation.

https://ibm-security.carbondesignsystem.com/?path=/story/patterns-filterpanel--with-deprecated-filterdata

**Comment by RobertaJHahn** [comment]
Tasks: Convert to epic, Design research and investigation, design & specs, BA, dev issues (WC & React wrapper), Visual QA & Prod QA, web site

**Comment by RobertaJHahn** [comment]
All linked issues are closed.  Closing this epic.
