### ISSUE TITLE
Masthead Navigation moving on toggle

### ISSUE THREAD

**Issue by skycryer** [carbon-design-system/carbon-for-ibm-dotcom#5472]
## Detailed description

When toggle a navigation item the masthead is moving few pixel to the side on pages with a scrollbar because the scrollbar gets hidden on opening the navigation item.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
L1 Navigation

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Navigation should not move to the side on toggle

> What browser are you working in?
Firefox, Safari, Chrome, Edge

> What version of Carbon for IBM.com are you using?
0.16 styling
1.1.1 web components

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM CMS, April/May

## Steps to reproduce the issue

1. Add a header and navigation to a page
2. Add components until you see a scrollbar for the page
3. toggle the navigation item to show submenu

## Additional information

https://user-images.githubusercontent.com/3725699/110962071-d4751f80-8350-11eb-9519-2598961a4abe.mov

**Comment by sbahl1** [comment]
Would like to share the CMS launch is April 6th. vs "april/may"

**Comment by kennylam** [comment]
@skycryer What package versions (`@carbon/ibmdotcom-`) are you using? This was resolved some time ago.

http://ibmdotcom-react-canary.mybluemix.net/iframe.html?id=components-dotcom-shell--default
http://ibmdotcom-web-components-canary.mybluemix.net/iframe.html?id=components-dotcom-shell--default
