### ISSUE TITLE
Wrong login URL for KR-KO in the API

### ISSUE THREAD

**Issue by prajeethv** [carbon-design-system/carbon-for-ibm-dotcom#5475]
## Detailed description
<img width="492" alt="image" src="https://user-images.githubusercontent.com/49343229/110984007-87854f00-8338-11eb-81af-a05c80093b88.png">

This is a bug. Replicable in all browsers. Here is our dev link for your team to validate and confirm - https://pdywdcpripo01.podc.sl.edst.ibm.com/privacy/portal/kr-ko

We have a release coming up on Tuesday.

**Comment by RobertaJHahn** [comment]
This is an issue for the Translation team to resolve.  Jeff will reach out.

**Comment by jeffchew** [comment]
@prajeethv just want to confirm that you are working directly with the translation team now, before we close this issue. Thanks!

**Comment by prajeethv** [comment]
We can close this one @jeffchew. Thank you for your support on this issue.

**Comment by jeffchew** [comment]
@RobertaJHahn fyi, this one has been closed.
