### ISSUE TITLE
Masthead - Scrolling carets briefly display on component load

### ISSUE THREAD

**Issue by matoushavlena** [carbon-design-system/carbon-for-ibm-dotcom#5483]
## Detailed description

On page load, the carets used for horizontal scrolling briefly appear (and also overlay the first menu item) even though the viewport is wide enough that the caret shouldn't be displayed at all.

## Steps to reproduce the issue

1. Open the masthead component with wide viewport (e.g. 1400px)

## Additional information

Video:
https://user-images.githubusercontent.com/9358330/111152077-9e25e300-8590-11eb-8e57-f769bcbe8697.mov

Picture:
![carets-issue](https://user-images.githubusercontent.com/9358330/111152429-fe1c8980-8590-11eb-9b66-aaaec46ab4bc.png)

**Comment by shixiedesign** [comment]
Also notice is the scrolling caret makes another come back in Masthead dotcom shell story: 
https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-dotcom-shell--search-open
https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-dotcom-shell--search-open

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/6cbfeac9-5617-42dc-b739-e40b6b32ab60)

**Comment by ariellalgilmore** [comment]
This issue has been fixed. There is another bug for the masthead search default and the PR was just opened for it.
