### ISSUE TITLE
[CTA section] Design spec, storybook, & Abstract

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5489]
### QA the following component in storybook, and create issues if bugs are present

- [ ] CTA section

### Reminder of clean up fixes we are looking for across the board:

- grid should be applied
- line length
- ~spacing ~ skip spacing for now since an AEM layout token change is happening this sprint
- naming (should be correct capitalization)
- knobs

**Comment by RobertaJHahn** [comment]
@shixiedesign Should I move this issue to Sprint 21-08?
