### ISSUE TITLE
[TOC] Design spec, Storybook QA, Abstract

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5491]
### QA the following component in storybook, and create issues if bugs are present
- [ ] ToC vertical (default)
- [ ] ToC horizontal 

### Reminder of clean up fixes we are looking for across the board:

- grid should be applied
- line length
- ~spacing~ skip spacing for now since an AEM layout token change is happening this sprint
- naming (should be correct capitalization)
- knobs

**Comment by oliviaflory** [comment]
### Storybook notes / things to consider

1. Heading content example
- [ ] Remove image as an example of heading content
- [ ] Replace with link list

 | ![Screen Shot 2021-03-15 at 3.34.11 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/e016bf3b-0e8d-4d12-bfdc-8b37981aa141) | ![Screen Shot 2021-03-15 at 3.43.04 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/fdccb286-4304-4057-a44c-fb7e3c15cc55) |
| --- | --- |

2. Rename HR knob
- [ ] Rename to `Optional horizontal rule`


3. Horizontal rule color
- [ ] Should be $ui-03
