### ISSUE TITLE
[FeatureCardBlockMedium] icon does not get updated correctly

### ISSUE THREAD

**Issue by Claire-ibm-toulouse** [carbon-design-system/carbon-for-ibm-dotcom#5493]
Hello all, here is my code: : 
https://github.com/Claire-ibm-toulouse/ois

and the page in staging: 
https://wwwstage.ibm.com/strategic-partnerships/fr-fr/ois/

On the last component "ContentBlockMedia", I am using the "feature" design, and trying to call the appropriate icon called [Launch20](https://carbon-elements.netlify.app/icons/examples/preview/#Launch20), but it keeps calling the "ArrowRight20" that was initially in the template.

This is a minor bug but it gives me a compliance issue. Please help, thanks.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/74964904/111184624-6d09da80-85b1-11eb-87e3-5ddbed8393c5.png">

Also, do you happen to know why the background color of my "feature" card is dark grey when I deploy it (see above), instead of light grey when I run the code locally (see below)?
<img width="633" alt="image" src="https://user-images.githubusercontent.com/74964904/111185490-4e581380-85b2-11eb-88cc-a05bdb4452d5.png">

**Comment by RobertaJHahn** [comment]
Kenny to respond as part of fireline.  May not be a bug.  Needs investigation.

**Comment by Claire-ibm-toulouse** [comment]
Hello all, unfortunately the bug remains on my side. My code is in GitHub. Please help thanks.


Claire Lebastard

OFF on fridays
Risk & Compliance -  SE&TS (Sales Execution and Transaction Support)
IBM CIO  - Finance and Operations
+33 (0)562181617 – Toulouse - France


From: RobertaJHahn ***@***.***>
Reply to: carbon-design-system/carbon-for-ibm-dotcom ***@***.***>
Date: Tuesday 16 March 2021 at 19:08
To: carbon-design-system/carbon-for-ibm-dotcom ***@***.***>
Cc: Claire Lebastard ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [carbon-design-system/carbon-for-ibm-dotcom] [FeatureCardBlockMedium] icon does not get updated correctly (#5493)

Kenny to respond as part of fireline. May not be a bug. Needs investigation. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ 


Kenny to respond as part of fireline. May not be a bug. Needs investigation.

**Comment by Claire-ibm-toulouse** [comment]
As per Kenny Lam's recommendation I used the **FeatureCardBlockMedium** component instead and I was able to use the proper icon there, tks !
