### ISSUE TITLE
[Footer] Implement adjunct legal links to footer component

### ISSUE THREAD

**Issue by AlexandruTasca** [carbon-design-system/carbon-for-ibm-dotcom#5495]
Implement the Legal Footer component as described in previous V18 / V19a
https://www.ibm.com/standards/web/v19a-archive/components/legal-footer/

#### Additional information
- [Link to Alexandru Tasca Slack chat](https://cognitive-app.slack.com/archives/C2PLX8GQ6/p1615820883091800)
- [Link to skills academy info](http://ibm.biz/skillsacademy)
 - Adjunct legal links Design specs [Box folder](https://ibm.ent.box.com/folder/101562989787?s=nsbccv6jigfw78uwq3r0242qks1x1f87).

**Comment by oliviaflory** [comment]
[Link to slack conversation](https://cognitive-app.slack.com/archives/C2PLX8GQ6/p1615820909092500)

**Comment by RobertaJHahn** [comment]
Tasks:  Convert to epic, Design research and investigation, design & specs, BA, dev issues (WCC & stand alone react), Visual QA & Prod QA, web site

**Comment by DragosRistici** [comment]
Design specs that include Adjunct legal links can be found in this [Box folder](https://ibm.ent.box.com/folder/101562989787?s=nsbccv6jigfw78uwq3r0242qks1x1f87).
