### ISSUE TITLE
[Card, card group] Design spec, storybook, Abstract

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5499]
### QA the following component in storybook, and create issues if bugs are present
- [x] Card
- [x] Card group

### Reminder of clean up fixes we are looking for across the board:

- grid should be applied
- line length
- ~spacing~ skip spacing for now since an AEM layout token change is happening this sprint
- naming (should be correct capitalization)
- knobs

**Comment by oliviaflory** [comment]
## Notes

### Card storybook
Image [ checkbox]
Eyebrow ~(optional)~ [ text input ]
Heading [ text input ]
Copy ~(optional)~ [ text input] *blank*
Footer copy [ input ] *blank*
Footer icon [ dropdown ] ??
~Footer icon placement (footer.iconPlacement)~
Card link (href) [ input ] 
Inverse [ checkbox]

- [ ] remove tabs of Card / Pictogram card
- [ ] Default / Pictogram

### Card default


### Card group
#### Mixed media
- lightbox cannot access X
-
