### ISSUE TITLE
[Video player] Additional states:  hover, active, focus

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5514]
Our [Video](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-video-player--default) component have no hover state. This story is to add the standard interactive states to the component so that there's visual feedback when user interacts . 

## Expecting the following interactive status to be implemented: 

[Clickable figma prototype ](https://www.figma.com/file/Addj7hJnTCC9R4x66YKK9p/Component-video?node-id=36%3A0)
[Design spec](https://ibm.box.com/s/9q7rdj73m32hufcw1xwl1td6nr88rghm)
### 1. Default 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/314068da-c215-4df3-8282-b896af8a98fa)

### 2. Hover 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/789f07ed-dbeb-4ca8-a1ea-8f4704821bea)

Transition should match the rest of the cards in the library: 

```
transition: 150ms, cubic-bezier(0.2, 0, 0.38, 0.9)
```

a) the image or video poster image: to darken on light themes, and lighten on dark themes. 
` $ui-05 overlay at 8% opacity `
See clickable prototype: https://www.figma.com/proto/pVH385cIPauyJgF7o1k2CK/Card-hover?node-id=36%3A0&scaling=min-zoom

#### b) the play icon style should follow: 

| State | Spec of circle svg | Spec of triangle svg |
| --- | --- | --- | 
| Default | Gray-70, opacity: 0.8 | Gray-10 |
| Hover | Gray-100, opacity: 0.9 | White |

### ~3. Focus ~  Done!

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/9a44a514-3e98-438e-a376-5fc86041ec46)

### 4. Active (on click or on tap) 
` $ui-05 overlay at 12% opacity `
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/6379759b-8e7e-4b1d-b99f-f7f70e2ae29e)

Based on the comments below, this epic includes the work for all of the potential states for the video player.  

#### Additional Information
- A bug for the focus state has been created and scheduled in the April release.  issue (#5660 )
- The custom poster image feature is managed under epic (#5642) and the functional spec issue (#5754 )

**Comment by photodow** [comment]
All states need to be looked at here I believe.

`:hover`
`:active`
`:focus`

**Comment by RobertaJHahn** [comment]
Discussion:  The designs are out of the box Kaltura so no designs are created.  Changed to Feature request

Dev research:  1)  Investigate if the out of the box player can be customized  

Tasks: Convert to epic, Design & Dev research and investigation, design & specs, BA, dev issues (WCC & stand alone react), Visual QA & Prod QA, web site

**Comment by photodow** [comment]
> The designs are out of the box Kaltura so no designs are created.

Just to be clear I don't think this is out of the box Kaltura. We are using an thumbnail image and play icon, and then replacing those with Kaltura out of the box.

**Comment by shixiedesign** [comment]
Related issue Dragos recently looked at https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/5642 If we think this is a good feature to add, we need to consider the pros and cons listed. Personally I'm on the side of NOT allowing custom cover image.

**Comment by shixiedesign** [comment]
Collecting more info. Hover should use: 
`Lighten 8% on dark themes`
`Darken 8% on light themes` 
Is this possible? 

Based on card spec: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/fd011e5c-b903-43b0-8657-894927cb3b86)

Interactive prototype I build awhile ago in Figma: 
https://www.figma.com/proto/pVH385cIPauyJgF7o1k2CK/Card-hover?node-id=36%3A0&scaling=min-zoom
