### ISSUE TITLE
Component: Change the [Card Group] design specs to include use case with 4 cards

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5518]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the `Card Group` design specs

> so that I can:
correctly change the `Card Group` component 

#### Additional Information
- Carbon for ibm.com epic (#5406 )
- Where there are 4 cards in a card group, `Card grouping with card group default` and `content block cards default`, create a variation where if there are 4 cards, they can be viewed as 2 columns with 2 rows and 2 cards per column (4 by 4 matrix)

#### Acceptance Criteria
- [x] A Sketch file is created or updated with the `Card Group` design and specs
- [x] Create a Box folder for the `Card Group` (if not already there)
- [x] The design specs and pdf version are added to the Box folder 
- [x] Update the Carbon for ibm.com epic with the spec link
- [x] Add Box folder link to the website content if it exists

**Comment by shixiedesign** [comment]
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/e0cda4d8-1f0b-42eb-8e45-2db22ce08b6d)
