### ISSUE TITLE
[Card Group]: Change the functional specifications to include use case with 4 cards

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5519]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Card Group` functional specs 

> so that I can:
so that I can properly code the `Card Group` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5406 )**
     - Where there are 4 cards in a card group, `Card grouping with card group default` and `content block cards default`, create a variation where if there are 4 cards, they can be viewed as 2 columns with 2 rows and 2 cards per column (4 by 4 matrix)
 - Design Issue (#5518 )
 - Development issue (#5520 )
 - Visual Designs & Functional Design Specs Box folder link(TBD)

#### Acceptance criteria
 - [ ] Documented `Card Group` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by shixiedesign** [comment]
Allow new knob/prop: 
Number per row: [ 2 | 3 | 4 ]

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/6317235d-ddf8-47ef-aec6-3b2e3f687762)

**Comment by photodow** [comment]
Functional specs here: https://ibm.box.com/s/rpki0q23o6wyrtvx22je74tbfx1xkcsn
