### ISSUE TITLE
[Content block segmented] Storybooks QA

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#5536]
## General issues

Please change this: 
<img width="209" alt="Screenshot 2021-03-18 at 16 07 36" src="https://user-images.githubusercontent.com/48327647/111640569-f9600b80-8804-11eb-9bd5-7a8a5a3511bb.png">

to this:
```
Content block – segmented
    Default
    With link list

```

Rename the themes by their full name, from this: 
<img width="359" alt="Screenshot 2021-03-18 at 14 43 31" src="https://user-images.githubusercontent.com/48327647/111627967-5608f980-87f8-11eb-9bf4-c0424146bd65.png">

to this:
```
White
Gray 10
Gray 90
Gray 100
```

Add the same knobs from the Default story to the third story also, besides what it already has. Make sure you add the specific knobs at the end (link list heading, and maybe add the number of links, 2 or 3).

And also add this, but change the first one to `Container bottom border` and make the options be: `With border` and `Without border`. Make the first one, `With border`, selected by default, so the border is present from the start: 
<img width="635" alt="Screenshot 2021-03-17 at 15 30 43" src="https://user-images.githubusercontent.com/48327647/111521957-6bcbdf80-8762-11eb-8946-0c1384c4c4a1.png">

In React Storybook, for the `With link list` story, the content text CTAs are missing.
<img width="576" alt="Screenshot 2021-03-18 at 16 24 38" src="https://user-images.githubusercontent.com/48327647/111642114-79d33c00-8806-11eb-9bf7-546ec0f19048.png">
<img width="578" alt="Screenshot 2021-03-18 at 16 24 32" src="https://user-images.githubusercontent.com/48327647/111642124-7c359600-8806-11eb-8991-a995b8c5d0b3.png">

1. Again, on React Storybook, the heading is off the grid
<img width="365" alt="Screenshot 2021-03-18 at 16 25 50" src="https://user-images.githubusercontent.com/48327647/111642324-a8511700-8806-11eb-913f-2758125c29d8.png">

2. in Web Components Storybook, make sure the spacing below the heading is 32px and the H3 intro text is present, just like on the other stories. 
<img width="1047" alt="Screenshot 2021-03-18 at 16 26 50" src="https://user-images.githubusercontent.com/48327647/111642798-1269bc00-8807-11eb-97c3-6a58a3e7c927.png">

3. Please apply card max-width of 320px throughout. 
<img width="552" alt="Screenshot 2021-03-18 at 16 31 22" src="https://user-images.githubusercontent.com/48327647/111643197-6eccdb80-8807-11eb-8aea-1b92c06d1635.png">

4. On mobile, in the Web components Storybook, link list icons are not properly aligned
<img width="367" alt="Screenshot 2021-03-18 at 16 32 15" src="https://user-images.githubusercontent.com/48327647/111643366-97ed6c00-8807-11eb-9d6f-dd2beed5c1ce.png">

5. Card on sm break point, React Storybook, does not go full width at 320px.
<img width="360" alt="Screenshot 2021-03-18 at 16 33 23" src="https://user-images.githubusercontent.com/48327647/111643638-c8350a80-8807-11eb-87d0-ebe174e557a7.png">

6. Spacing above the video should be the same as above the image, 32px. 

7. Please, add a video. The video is missing.

8. The cards should maintain their 2:1 aspect ratio
<img width="471" alt="Screenshot 2021-03-18 at 16 51 29" src="https://user-images.githubusercontent.com/48327647/111646340-3c70ad80-880a-11eb-8e2b-044c452032a1.png">

Also because most of these errors are propagated to all content blocks, please check the other open issues involving `content blocks` to remain consistent: 5527, 5533, 5534.

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bugs
> Is this issue related to a specific component?
Content block – segmented
> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome
> What version of Carbon for IBM.com are you using?
Latest
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by IgnacioBecerra** [comment]
FYI: #5864 might solve some of the issues here, waiting until that gets merged to submit PR for this.
