### ISSUE TITLE
[Back to top] Design QA issues found

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#5537]
> I'd be happy to break these down, or we can do it together on one of our calls. Whatever works best for Roberta and team.

Referencing #4463 

### Web components
https://ibmdotcom-web-components-experimental.mybluemix.net/?path=/story/components-back-to-top--default

#### 1. All content used to demo is off the grid

<a href="https://user-images.githubusercontent.com/3793636/111648350-41fdd180-87d1-11eb-93c8-a990d0f4b3ba.png" target="_blank"><img  width="300px" src="https://user-images.githubusercontent.com/3793636/111648350-41fdd180-87d1-11eb-93c8-a990d0f4b3ba.png" /></a>

#### 2. Footer cut off before the end of grid, and should extend to full width of screen

<a href="https://user-images.githubusercontent.com/3793636/111648545-7a9dab00-87d1-11eb-85a3-d010a7f58eae.png" target="_blank"><img  width="300px" src="https://user-images.githubusercontent.com/3793636/111648545-7a9dab00-87d1-11eb-85a3-d010a7f58eae.png" /></a>

> 👀   &nbsp;&nbsp; See [doctom shell story](https://ibmdotcom-web-components-experimental.mybluemix.net/?path=/story/components-dotcom-shell--default) for a reference on what I mean.

#### 3. Back to top should be 16px from the right of the screen

<a href="https://user-images.githubusercontent.com/3793636/111649155-1b8c6600-87d2-11eb-829e-3d42a99c143a.png" target="_blank"><img  width="100px" src="https://user-images.githubusercontent.com/3793636/111649155-1b8c6600-87d2-11eb-829e-3d42a99c143a.png" /></a>

#### 4. is there extra space at top of page?

I think it's supposed to be `64px` here

<a href="https://user-images.githubusercontent.com/3793636/111653819-306af880-87d6-11eb-8388-3cf87d5d0022.png" target="_blank"><img  width="300px" src="https://user-images.githubusercontent.com/3793636/111653819-306af880-87d6-11eb-8388-3cf87d5d0022.png" /></a>

##### What I see
<a href="https://user-images.githubusercontent.com/3793636/111654998-44fbc080-87d7-11eb-8f19-a4b8012b20a9.png" target="_blank"><img  width="75px" src="https://user-images.githubusercontent.com/3793636/111654998-44fbc080-87d7-11eb-8f19-a4b8012b20a9.png" /></a>

##### What I expect to see
<a href="https://user-images.githubusercontent.com/3793636/111655085-58a72700-87d7-11eb-92c7-3d67d70a1e96.png" target="_blank"><img  width="75px" src="https://user-images.githubusercontent.com/3793636/111655085-58a72700-87d7-11eb-92c7-3d67d70a1e96.png" /></a>

#### 6. some bordering aliasing issue in firefox (is that just me?)

<a href="https://user-images.githubusercontent.com/3793636/111646689-de26d900-87cf-11eb-86bb-52a3f34d3512.png" target="_blank"><img  width="75px" src="https://user-images.githubusercontent.com/3793636/111646689-de26d900-87cf-11eb-86bb-52a3f34d3512.png" /></a>

### React wrapper
https://ibmdotcom-web-components-react.mybluemix.net/?path=/story/components-back-to-top--default

#### 8. different content and grid alignment.
For the most part, I didn't see any new bugs, but I couldn't fully test it since things like the footer weren't there.

> ⚠️ &nbsp;&nbsp; Note: I couldn't test whether it shows up or not depending on the content length of 3 pages/viewport heights

**Comment by kennylam** [comment]
Resolved in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6429.
