### ISSUE TITLE
[Video card] Change video card to display video title as Card headline, not card copy

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#5538]
Thoughts for consideration...

### The problem
I think one of the original requirements around the video card was that its title needed to leverage the copy section of the card. Some of the designs I'm seeing come in that need might be changing slightly.

### The solution
Should we consider looking at ways to apply the title to other places outside of the copy? Is there a need to pull in descriptions?

**Comment by RobertaJHahn** [comment]
Schedule the work.  Will convert to an epic once the design decisions are made.

**Comment by shixiedesign** [comment]
Looking through functional spec to understand the problem better. I don't see any obvious mention that video title should go into card heading. Is it documented somewhere else? 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/a1c5f2f1-60fd-4fbe-96dc-5d9710296233)

**Comment by shixiedesign** [comment]
Looks like left side is what we want. Right hand side card shows video title in copy, which doesn't make sense coz the body copy is optional in a card: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/cddc3d72-b890-4ec2-b826-383b640e47f1)

**Comment by shixiedesign** [comment]
More discussions: 
### Data from Kaltura video: 
- title 
- description
- duration
- poster image

### Current list of components that pulls a video from Kaltura:

**Card** 

| Incoming data | Field | 
| --- | --- |
| Kaltura video title | Card title (allow override) |

**Lightbox**  

| Incoming data | Field | 
| --- | --- |
| Kaltura video title | Lightbox headline (allow override) |
| Kaltura video description | Lightbox description (allow override) |

**Video**

| Incoming data | Field | 
| --- | --- |
| Kaltura video title | Caption (allow override) |
