### ISSUE TITLE
[CTA] Feature should show Feature card block - medium

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5542]
#### Overview
The CTA components inside the [React](https://ibmdotcom-react.mybluemix.net/?path=/story/components-cta--button) and [Web Components](http://ibmdotcom-web-components.mybluemix.net/?path=/story/components-cta--text) Storybooks have discrepancies around the naming and the examples between the two Storybooks (see screenshots below). 

After a [discussion](https://cognitive-app.slack.com/archives/GBG66T9NK/p1614887714098800) on the team Slack channel, the React version is wrong based on James's functional spec.

#### Additional Information
- [ ] Feature  - should show **[Feature card block - medium](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-feature-card-block-medium--default)**. (React: correct, but wrong name, should be left aligned in viewport. WC: Headline is missing).

`For the examples:`
![Storybook samples](https://user-images.githubusercontent.com/45213839/110166697-56e26a00-7dba-11eb-825e-5da90856b283.jpg)

#### Acceptance Criteria
 - [ ] Both Storybooks show the same labels and examples for `CTA - Feature card block - medium` component

**Comment by IgnacioBecerra** [comment]
This should be fixed with #5950, but there may still be a positioning issue. Will update here if a PR is needed for this.

**Comment by RobertaJHahn** [comment]
@IgnacioBecerra is a PR needed for this guy?
