### ISSUE TITLE
Carbon expressive kit (light themes): missing $inverse-link token

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5543]
Andree from KC caught that we are missing $inverse-link color style in our design kit `Carbon expressive (white theme)`: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/ca92431f-e15e-45e6-a61e-ce1983f9f635)

### Task:
Add inverse link color style 
- [ ] white theme
- [ ] gray 10 theme

**Comment by oliviaflory** [comment]
😱  also missing in gray 10 kits

**Comment by shixiedesign** [comment]
Will not fix since we are sunsetting expressive theme.
