### ISSUE TITLE
[Footer] V2 enhancements

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5544]
### Problems: 

- Language selector is left on `default` but right on `short & micro`
- `default` footer appears very long and people gravitate to the `short` instead
- Cloud footer is different. How can we anticipate their needs? 
- Global footer is also different

**US default footer** 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/70b57ddd-1f78-4177-9eec-1f3f77e4e7dd)

**Cloud footer**

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/0e0c30d5-55d2-4c88-bb4a-40ff41c2a8ee)

**UK footer** 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/7314e973-87e7-4d33-8385-3b3cdd1eb1a2)

## Tasks

1. Explore alternative way to layout the footer links & links in bottom strip 

- Local changer / language changer
- Re-layout link-groups
- Generally follow existing content from Keegan and Michael, but reach out to discuss global content difference 
- Discover & design to accommodate global footer content needs, add some guard rails 

2. Website guidance update https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/footer

### Notes
- Footer repeats some link from homepage masthead because some users enter not via homepage
- **IA Guild** is the gate keeper for what goes into footer (Current process: Geo site goes to IA guild with changes and if approved, the changes go directly to webmaster team for implementation. So the footer can grow without our knowledge)

----
#### Additional Information
- [Design Box folder link](https://ibm.ent.box.com/folder/137988555914)

**Comment by RobertaJHahn** [comment]
Convert to an epic and create research, explorations, specs and functional specs

**Comment by RobertaJHahn** [comment]
Next steps - Dev issues:  WC and React stand alone.  All QA issues
