### ISSUE TITLE
[Lead space - with search] Design - build - develop. Including type ahead

### ISSUE THREAD

**Issue by aiproulx** [carbon-design-system/carbon-for-ibm-dotcom#5551]
### The problem
Hi - we are using Leadspace with search component on IBM Docs homepage

We also have a fantastic typeahead built by Kenny, and now we would like to expose it on the dark theme leadspace.

### The solution
Implement the Shixie dark theme typeahead. 

KC Homepage Lead space with search:  https://www.ibm.com/docs/en

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/bcc6b7df-ba66-4774-959f-89f2dc5d21a7)

### Additional information
Reference: 
Shixie SHI TROFIMOV  7:01 AM
Adding typeahead to this component make sense. I have it spec'ed too back when it was designed, just didn't make it into the first round of build
If you need it, I'm open to adding that feature to this guy

https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-leadspacewithsearch--default

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/030fd90f-e129-4c11-85d1-830ce0e192ba)

**Comment by oliviaflory** [comment]
Hi @aiproulx any dates we should be aware of that your team is working towards?

**Comment by aiproulx** [comment]
Hi @oliviaflory we are implementing the homepage design this weekend and week. It is in scope for April 1st release.

My current recommendation to our dev'er is to use the search field as-is (on the glass) and link to our search engine, until we can update to the latest and greatest code from your team.

We are ready to catch it in the next release or in a canary release.

**Comment by RobertaJHahn** [comment]
This is a popular component.  DDS should have once in the Carbon for ibm.com library.  

Next steps:  Epic:  Lead space with Search (currently in experimental) - promote to Prod
design issue:  Design Investigation and exploration

**Comment by RobertaJHahn** [comment]
Example sites:  
ibm.com/products
ibm.com/mysupport

**Comment by DragosRistici** [comment]
The Lead space with search component visual specs [can be found here](https://ibm.ent.box.com/folder/137098284291).
