### ISSUE TITLE
[Feature card] Functional spec update

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5559]
With these changes in mind, the functional spec for `Feature card block large` `Feature card block medium` and `Feature card` might all be affected: 
- Feature card block large <--- Deprecate
- Feature card block medium <-- Deprecate
- Feature card: rename default to medium, fix bugs to spec
- Feature card: add large variant, fix bugs to spec

Update functional spec based on improvements described in this issue #5416

**Comment by photodow** [comment]
Functional specs link

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Feature-card
