### ISSUE TITLE
Begin thinking of names for HC library components 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5561]
## Task
Lara did this audit of HC library components, and identified possible candidates for inclusion in our library. To inform future naming decisions, we should:

1. take a look at the identified candidates for structural consistency 
2. look for opportunity for alignment with our current naming conventions

The goal is to _start formulate names_, not to finalize them. We don't yet know which of the components will have to be included yet. While it's likely we need most of these, we are not tied to them until adopters pull them into their templates.

### Lara's audit of HC library
https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1594672150192?sender=larahanlon9022&key=2a3e9826-9664-473f-9bfc-7257f1bc0ec3

**Some examples that got me thinking:** 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/e5561b33-bc13-4ab8-b8cf-9eefa2e5f73c)![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/cf18ec0c-7ae4-4391-9061-c5c2440ffbe9)

**Comment by photodow** [comment]
Have we done a full design exploration based on these? I wonder if the `2A` might work, but the `3A` feels off to me. I wonder if we could explore some variations, and maybe normalize and align to some of the components we already have. A couple quick initial thoughts I have looking at this though...

- definitely feels like we might be trying to leverage card group. although the cards themselves look off. we've talked even recently about maybe adding an offset or empty card to the card group to obtain a style like this.
- For the background layout I'm seeing a `4 of 16` and a `8 of 16` full section component. I wonder if we need both, and if they both need to differ in type size so much. Are there other layouts that might need to be able to work here? Should these layouts be used seperately without cards group? I've seen similar layouts with a  card similar to our card in card. Is that related more to this, or maybe more to card in card of even feature card.
