### ISSUE TITLE
React: Locale modal - Select geographic area link is not identified by the screen reader.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5562]
## Detailed description

In FF with JAWS, voiceover
Issue: 
Select geographic area link present before the "Location and language" search field. This link is not identified by the screen reader hence the user does not know its presence Note: working fine in web component	

Expected:
Screen reader should identify the link.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/33a9368a-b386-44c7-8740-27746d8bc615)

**Comment by kennylam** [comment]
@Praveen-sr @RobertaJHahn Confirmed with Ram that this is working and not a bug.
