### ISSUE TITLE
Lightbox Media Viewer CSS difference from Storybook

### ISSUE THREAD

**Issue by skycryer** [carbon-design-system/carbon-for-ibm-dotcom#5563]
## Detailed description
We use Lightbox Media Viewer with version 1.16.1 for Carbon Styling and 1.1.1 for Web Components and having an extra CSS for position relative on bx--modal-content. After talking with @RaphaelAmadeu i know we use the same version as on storybook so there should not be extra css.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Lightbox Media Viewer

> What did you expect to happen? What happened instead? What would you like to
> see changed?
CSS should be same on storybook and what we can get as latest version

> What browser are you working in?
Safari,Chrome,Firefox, Edge

> What version of Carbon for IBM.com are you using?
1.16.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM CMS, April 6th

## Additional information
I had a call with @RaphaelAmadeu  so he know what the issue is and how to reproduce it. He will deliver further information.

Large breakpoint
![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/ba61b668-cf61-457e-bfdd-d3bb2fb86ac7)

Tablet Breakpoint
![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/40c0b69f-edd1-4fc7-b11a-b9a6b0b4ee1c)

Mobile breakpoint
![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/e2c6f43e-4f10-4af8-9c9b-82e4289cc377)

**Comment by annawen1** [comment]
@RaphaelAmadeu can you add the details here in this ticket?

**Comment by RobertaJHahn** [comment]
Raph will ask Christian to update to the latest RC version.  Looks like that may fix this issue.

**Comment by RobertaJHahn** [comment]
@RaphaelAmadeu Do you know whether Christian made the update and we can close this issue?

**Comment by skycryer** [comment]
Seems to be solved
