### ISSUE TITLE
Can section titles and the Table of contents have the same top alignment?

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#5564]
### The problem
Right now when a user navigates via the Table of contents the main section titles do not align with the top of the ToC. It appears that the ToC is using a top padding of 32px and the main section titles are only using a top padding of 16px.

### The solution
Can we make the top padding the same for the ToC and main sections so that when a user selects a section from the ToC the top of the ToC and section are aligned?

### Additional information
 <img width="1203" alt="Pasted_Image_3_22_21__12_41_PM" src="https://user-images.githubusercontent.com/77290329/112026436-97f1b280-8b0c-11eb-8394-2eadec182e0d.png">

**Comment by oliviaflory** [comment]
> ToC is using a top padding of 32px and the main section titles are only using a top padding of 16px.

The section titles should align the Table of contents padding of 32px 👍
