### ISSUE TITLE
[AEM] Awkward spacing above TOC on md and sm breakpoints

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#5569]
## Detailed description

> I'm not sure if this space is to accommodate for the L0 header, but for AEM and I think according to the TOC design specs only the TOC should stick to the top of the page as the user scrolls. After talking with Christian Schimanski, it sounds like this is something that needs to be fixed on your guys' end. 

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
**Not sure if this is a bug or a general issue.**

> Is this issue related to a specific component?
**This is related to the TOC component.**

> What did you expect to happen? What happened instead? What would you like to
> see changed?
**I expect the TOC on md and sm breakpoints to lock to the top of the browser without any spacing between the TOC bar and the browser chrome.**

> What browser are you working in?
**Chrome**

> What version of Carbon for IBM.com are you using?
**Not sure.**

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
**We are going live next week and would be nice to have this fixed by then.**

## Additional information
![TOC_Move](https://user-images.githubusercontent.com/77290329/112157400-8d432600-8bbd-11eb-86a8-3860570fde42.JPG)

**Comment by oliviaflory** [comment]
Hey @kirbyevans, do you know if you are using the ToC - default (vertical), or are you testing using the ToC – horizontal release candidate? Will be helpful for us to know, thanks!

**Comment by kirbyevans** [comment]
@oliviaflory right now, we are seeing this issue for the ToC - default (vertical) version. We haven't started implementing the ToC – horizontal just yet.

**Comment by oliviaflory** [comment]
@kirbyevans following up: the original implementation of TOC did not have the masthead scrolling out of view, so you're seeing the space allocated for the masthead. However I'm not sure how the masthead was removed...so that is not the correct behavior either. It seems to be working in our [Dotcom shell example](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-dotcom-shell--default) 


The feature to scroll the masthead out of view and pin the TOC to the top of the browser has not been added quite yet, here's the issue tracking scroll behavior #5573

**Comment by kirbyevans** [comment]
Hey @oliviaflory, there might be some inconsistencies between the Carbon for IBM.com site, the ToC design specs, and Storybook. The [L1 example](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-dotcom-shell--with-l-1) on Storybook has the L0 and L1 sticking to the top of the page, but on Carbon for IBM.com we say that the L1 should stick and the L0 should not.

![image](https://user-images.githubusercontent.com/77290329/112368216-36b71400-8cb1-11eb-8364-5f218c39ab25.png)

But, also, according to our [design specs for TOC](https://ibm.box.com/s/25dcp4scxni2gv7odv22yof8zutvlzot) the TOC bar on md and sm breakpoints should then push the masthead (L1) out of view as well leaving only the TOC at the top of the page.

![image](https://user-images.githubusercontent.com/77290329/112368689-b93fd380-8cb1-11eb-9d09-8e933b07f8a4.png)

**Comment by RobertaJHahn** [comment]
Anna will reach out to the AEM engineering to get more implementation details.  Need to determine where the fix has to be made.

**Comment by annawen1** [comment]
After speaking with Christian, the masthead disappearing on scroll is done through AEM. Our mobile TOC doesn't have the functionality to lock to the top yet (as Olivia mentioned we have a ticket to track this #5573) which is why we have this awkward spacing.

**Comment by annawen1** [comment]
@kirbyevans following up with this, I would recommend adding back the masthead on scroll for now as we already have a ticket in place to remove masthead and lock toc to top on scroll.
