### ISSUE TITLE
Customizable footer (AKA wedding cake)

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#557]
### User story
As an IBM.com user, I need to be able to see what else is available not only in all of IBM.com, but in the section that I am looking at currently, like Cloud, Watson, Security, etc.

### Notes
- This used to be called the wedding cake footer, and is about providing customizable space in the footer to approved BUs or sections of IBM.com.
- A good article around the importance of the footer: https://www.usertesting.com/blog/4-simple-tips-that-doubled-our-conversion-rate/

**Comment by RobertaJHahn** [comment]
Closing because Reboot is reviewing the footer design / content.
