### ISSUE TITLE
Cannot import component FeatureCardBlockMedium

### ISSUE THREAD

**Issue by Claire-ibm-toulouse** [carbon-design-system/carbon-for-ibm-dotcom#5572]
Hello, here is my repo in GitHub:
https://github.com/Claire-ibm-toulouse/ois

I can successfully import and display the FeatureCardBlockLarge component, but I'm getting an error when trying to use the FeatureCardBlockMedium: TypeError: Cannot read property ‘cta’ of undefined.

**Comment by annawen1** [comment]
Hi @Claire-ibm-toulouse, can you double check the props you are passing in? Looks like you need to pass in a `card` object like so

```
<FeatureCardBlockMedium heading={heading} card={card} />
```

Example of what the `card` object looks like:
```
          card: {
            heading: 'Explore AI use cases in all industries',
            cta: {
              href: 'https://www.example.com',
              icon: {
                src: ArrowRight20,
              },
            },
            image: {
              defaultSrc: imgLg1x1,
              alt: 'Image alt text',
            },
          },
```

**Comment by annawen1** [comment]
@Claire-ibm-toulouse I'll close this as the above comment should help, if you continue to face issues rendering the FeatureCardBlockMedium component you can reopen this ticket or post on the #carbon-for-ibmdotcom slack channel

**Comment by Claire-ibm-toulouse** [comment]
Kenny Lam's opinion is that this is a bug, because the **FeatureCardBlockLarge** renders ok, but the **FeatureCardBlockMedium** with exact same content gives an error.
Besides I don't know how to add props to the NextJs components (none of them have any in the index.js) and I don't have enough skills to edit the components files if they have errors in them (and don't think I should).
Please help me thanks (my code is in GitHub https://github.com/Claire-ibm-toulouse/ois )

**Comment by Claire-ibm-toulouse** [comment]
Hello Anna,
Please re-open the ticket as I don’t know how. I added a comment.

Claire Lebastard

OFF on fridays
Risk & Compliance -  SE&TS (Sales Execution and Transaction Support)
IBM CIO  - Finance and Operations
+33 (0)562181617 – Toulouse - France


From: Anna Wen ***@***.***>
Reply to: carbon-design-system/carbon-for-ibm-dotcom ***@***.***>
Date: Tuesday 23 March 2021 at 19:55
To: carbon-design-system/carbon-for-ibm-dotcom ***@***.***>
Cc: Claire Lebastard ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [carbon-design-system/carbon-for-ibm-dotcom] Cannot import component FeatureCardBlockMedium (#5572)

@Claire-ibm-toulouse I'll close this as the above comment should help, if you continue to face issues rendering the FeatureCardBlockMedium component you can reopen this ticket or post on the #carbon-for-ibmdotcom slack channel — ‍ ‍ ‍ ‍ ‍ 


@Claire-ibm-toulouse<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Claire-2Dibm-2Dtoulouse&d=DwMCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=ilpiN5h6AAKHnYeHuT_rQ9spmCP7T1ds8GZ68OMLJyw&s=A5IoC_NFOAI61PHCEj7MkFzTW1Gubyou9Gdk4w6SG2o&e=> I'll close this as the above comment should help, if you continue to face issues rendering the FeatureCardBlockMedium component you can reopen this ticket or post on the #carbon-for-ibmdotcom slack channel

**Comment by annawen1** [comment]
Hi @Claire-ibm-toulouse, this is what I see in your github repo - specifically in the [index.js](https://github.com/Claire-ibm-toulouse/ois/blob/master/pages/index.js) file

```
<FeatureCardBlockMedium
        eyebrow="scelerisque purus"
        heading="Feature Card Block Large"
        copy="Habitant morbi tristique senectus et netus et malesuada fames. Habitant morbi tristique."
        cta={{
          href: "https://example.com",
          icon: {
            src: Launch32,
          },
        }}
        image={{
          sources: [
            {
              src: "https://dummyimage.com/320x160/ee5396/161616&text=2:1",
              breakpoint: "sm",
            },
            {
              src: "https://dummyimage.com/400x200/ee5396/161616&text=2:1",
              breakpoint: "md",
            },
            {
              src: "https://dummyimage.com/600x600/ee5396/161616&text=1:1",
              breakpoint: 991,
            },
            {
              src: "https://dummyimage.com/600x300/ee5396/161616&text=2:1",
              breakpoint: "lg",
            },
            {
              src: "https://dummyimage.com/672x672/ee5396/161616&text=1:1",
              breakpoint: "xlg",
            },
          ],
          defaultSrc: "https://dummyimage.com/600x600/ee5396/161616&text=1:1",
          alt: "Image alt text",
        }}
      />
```

The props (eyebrow, heading, copy, cta, image) that are going into the `FeatureCardBlockMedium` above do not match what it is expecting which is 

```
 <FeatureCardBlockMedium heading={heading} card={card} />
 ```
 
 You can see it is expecting 2 props (heading & card). Looks like what happened was the props for `FeatureCardBlockLarge` were pasted into `FeatureCardBlockMedium`. The two components expect different props.
 
 I am able to render `FeatureCardBlockMedium` in your code:
 
<img width="1478" alt="Screen Shot 2021-03-24 at 9 02 45 AM" src="https://user-images.githubusercontent.com/54281166/112315152-37838200-8c80-11eb-886e-c9866de61adc.png">

with this:
```
<FeatureCardBlockMedium
            heading="Feature Card Block Medium"
            card={{
              heading: "Explore AI use cases in all industries",
              cta: {
                href: "https://www.example.com",
                icon: {
                  src: ArrowRight20,
                },
              },
              image: {
                defaultSrc: "http://fpoimg.com/500x500?text=Preview",
                alt: "Image alt text",
              },
            }}
          />
```

Please try the above code and let me know if you still face issues.

**Comment by Claire-ibm-toulouse** [comment]
Tks Roberta 😉

Claire Lebastard

OFF on fridays
Risk & Compliance -  SE&TS (Sales Execution and Transaction Support)
IBM CIO  - Finance and Operations
+33 (0)562181617 – Toulouse - France


From: RobertaJHahn ***@***.***>
Reply to: carbon-design-system/carbon-for-ibm-dotcom ***@***.***>
Date: Wednesday 24 March 2021 at 12:28
To: carbon-design-system/carbon-for-ibm-dotcom ***@***.***>
Cc: Claire Lebastard ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [carbon-design-system/carbon-for-ibm-dotcom] Cannot import component FeatureCardBlockMedium (#5572)

Reopened #5572. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ 


Reopened #5572<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_carbon-2Ddesign-2Dsystem_carbon-2Dfor-2Dibm-2Ddotcom_issues_5572&d=DwMCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=ahlUjz3dCH0snuLTDJVeHbvxGvPg8w2TpNi4l6F_q20&s=QC9vOB6MOr1McEj0eXUflS0pGhmn5RJP_9UZ7uUq-TU&e=>.

**Comment by Claire-ibm-toulouse** [comment]
Thank you so much @annawen1 my issue is solved THANKS AGAIN

**Comment by Claire-ibm-toulouse** [comment]
Thnaks Anna for taking the time to look into my code, I’m afraid I don’t have enough skills to work on my own and I am also running out of tiem so THANKS AGAIN.

I have one more small question if you could help me with :
the heading in the FeatureCardBlockMedium is smaller than my other headings, would you know why and how can I fix it? I have updated my github repo.

Tks again.


Claire Lebastard

OFF on fridays
Risk & Compliance -  SE&TS (Sales Execution and Transaction Support)
IBM CIO  - Finance and Operations
+33 (0)562181617 – Toulouse - France


From: Anna Wen ***@***.***>
Reply to: carbon-design-system/carbon-for-ibm-dotcom ***@***.***>
Date: Wednesday 24 March 2021 at 14:08
To: carbon-design-system/carbon-for-ibm-dotcom ***@***.***>
Cc: Claire Lebastard ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [carbon-design-system/carbon-for-ibm-dotcom] Cannot import component FeatureCardBlockMedium (#5572)

Hi @Claire-ibm-toulouse, this is what I see in your github repo - specifically in the index.js file <FeatureCardBlockMedium eyebrow="scelerisque purus" heading="Feature Card Block Large" copy="Habitant morbi tristique senectus et netus et 


Hi @Claire-ibm-toulouse<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Claire-2Dibm-2Dtoulouse&d=DwMCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=NsgitP27J-1n40ImpGYswvBEz48VuoK-GvCSeUeJkQA&e=>, this is what I see in your github repo - specifically in the index.js<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Claire-2Dibm-2Dtoulouse_ois_blob_master_pages_index.js&d=DwMCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=Q_-Txf5fnY5plCMIbeWgNHA-1u4eoiTj9PIhCetWOMA&e=> file

<FeatureCardBlockMedium

        eyebrow="scelerisque purus"

        heading="Feature Card Block Large"

        copy="Habitant morbi tristique senectus et netus et malesuada fames. Habitant morbi tristique."

        cta={{

          href: "https://example.com<https://urldefense.proofpoint.com/v2/url?u=https-3A__example.com&d=DwQCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=R1DZJVvD2jW0YlIL6-OhiB_A-uMr9fQS6h3JULWse0M&e=>",

          icon: {

            src: Launch32,

          },

        }}

        image={{

          sources: [

            {

              src: "https://dummyimage.com/320x160/ee5396/161616&text=2:1<https://urldefense.proofpoint.com/v2/url?u=https-3A__dummyimage.com_320x160_ee5396_161616-26text-3D2-3A1&d=DwQCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=Tg_BupgTxQZmske_xinP4Wwnjr80tghEDj3yuWyuXlA&e=>",

              breakpoint: "sm",

            },

            {

              src: "https://dummyimage.com/400x200/ee5396/161616&text=2:1<https://urldefense.proofpoint.com/v2/url?u=https-3A__dummyimage.com_400x200_ee5396_161616-26text-3D2-3A1&d=DwQCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=NBPAX_tllZ6v51LiO6blqoCF-GdIh6fgUxkIhbDYXS4&e=>",

              breakpoint: "md",

            },

            {

              src: "https://dummyimage.com/600x600/ee5396/161616&text=1:1<https://urldefense.proofpoint.com/v2/url?u=https-3A__dummyimage.com_600x600_ee5396_161616-26text-3D1-3A1&d=DwQCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=d8YaJZ5Wlbycuo3wJz89f6JUXfKj4DK0Xh8O2tOOQAo&e=>",

              breakpoint: 991,

            },

            {

              src: "https://dummyimage.com/600x300/ee5396/161616&text=2:1<https://urldefense.proofpoint.com/v2/url?u=https-3A__dummyimage.com_600x300_ee5396_161616-26text-3D2-3A1&d=DwQCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=Nx_pOsuDMo1PgCvy7DHoucwiClV56gClPpuWsa0kFfM&e=>",

              breakpoint: "lg",

            },

            {

              src: "https://dummyimage.com/672x672/ee5396/161616&text=1:1<https://urldefense.proofpoint.com/v2/url?u=https-3A__dummyimage.com_672x672_ee5396_161616-26text-3D1-3A1&d=DwQCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=xVbUiKF_bwNSJOEBESi9BVwEPPuuxTWYr55AAqD9nJg&e=>",

              breakpoint: "xlg",

            },

          ],

          defaultSrc: "https://dummyimage.com/600x600/ee5396/161616&text=1:1<https://urldefense.proofpoint.com/v2/url?u=https-3A__dummyimage.com_600x600_ee5396_161616-26text-3D1-3A1&d=DwQCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=d8YaJZ5Wlbycuo3wJz89f6JUXfKj4DK0Xh8O2tOOQAo&e=>",

          alt: "Image alt text",

        }}

      />

The props (eyebrow, heading, copy, cta, image) that are going into the FeatureCardBlockMedium above do not match what it is expecting which is

 <FeatureCardBlockMedium heading={heading} card={card} />

You can see it is expecting 2 props (heading & card). Looks like what happened was the props for FeatureCardBlockLarge were pasted into FeatureCardBlockMedium. The two components expect different props.

I am able to render FeatureCardBlockMedium in your code:

[Screen Shot 2021-03-24 at 9 02 45 AM]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_54281166_112315152-2D37838200-2D8c80-2D11eb-2D886e-2Dc9866de61adc.png&d=DwMCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=pqBATFoUsqHNeclCExOhffTLVQT2yW0J-YSl38ZIuJ0&e=>

with this:

<FeatureCardBlockMedium

            heading="Feature Card Block Medium"

            card={{

              heading: "Explore AI use cases in all industries",

              cta: {

                href: "https://www.example.com<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.example.com&d=DwQCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=MQt4iQ4IuM520bqiys20qlSC5etZ84oJhS9Ygh7MpCM&e=>",

                icon: {

                  src: ArrowRight20,

                },

              },

              image: {

                defaultSrc: "http://fpoimg.com/500x500?text=Preview<https://urldefense.proofpoint.com/v2/url?u=http-3A__fpoimg.com_500x500-3Ftext-3DPreview&d=DwQCaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=-spDyz9Sfeiv3FKklPWlpxc32bxCfJqvuA2bLG0eZ5E&m=0b877mpNeHKn71WAOw0NPF22pp20Tzbfdl-tI-VveOo&s=yVKpA3iRW7mQZ_eHVDsIgnMBpt81L0ty-B1eEE-sK_g&e=>",

                alt: "Image alt text",

              },

            }}

          />

Please try the above code and let me know if you still face issues.
