### ISSUE TITLE
Dotcom shell + ToC – heading hidden under ToC

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5574]
## Detailed description

> Describe in detail the issue you're having.

Because the masthead is not scrolling out of the viewport and the Masthead and ToC are stacking, the headings are hidden behind the ToC when the user selects one of the links in the ToC

Desktop
<img width="1330" alt="Screen Shot 2021-03-23 at 11 43 50 AM" src="https://user-images.githubusercontent.com/45692622/112180199-b8377500-8bd1-11eb-89e2-b1a164bfbf61.png">

Medium & small
<img width="772" alt="Screen Shot 2021-03-23 at 12 18 14 PM" src="https://user-images.githubusercontent.com/45692622/112180399-ea48d700-8bd1-11eb-9776-41037c18add2.png">

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

Hoping this would be a non-issue if we could implement the scroll behavior of the masthead + toc #5573 

> Is this issue related to a specific component?

ToC Horizontal 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Headings cannot be hidden, impacts the readability for the user.
If #5573 is prioritized we could possibly close this one

> What browser are you working in?

Chrome

> What version of Carbon for IBM.com are you using?

[Referencing deploy preview](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/5565/iframe.html?id=components-dotcom-shell--with-horizontal-toc#2) of ToC Horizontal within dotcom shell stories

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by RobertaJHahn** [comment]
Closing as (#5573 ) is now closed.
