### ISSUE TITLE
[Dotcom shell | Table of contents] storybook demo - DDS Consulting

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5577]
## Detailed description

> Describe in detail the issue you're having.

Remove extra space between Lead space and ToC - horizontal to show how we recommend positioning ToC directly below Lead space.

**Storybook**
<img width="672" alt="Screen Shot 2021-03-23 at 11 40 20 AM" src="https://user-images.githubusercontent.com/45692622/112198213-423c0980-8be3-11eb-8f81-7393961f791e.png">

**Design intent**
![Screen Shot 2021-03-23 at 2 24 00 PM](https://user-images.githubusercontent.com/45692622/112198404-71527b00-8be3-11eb-8f60-39da6fdc6e8e.png)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

Web components [Dotcom shell with Horizontal TOC](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/5565/index.html?path=/story/components-dotcom-shell--with-horizontal-toc) story

> What did you expect to happen? What happened instead? What would you like to
> see changed?

We should demo the ToC in the position we wish adopters to use it.

> What browser are you working in?

Chrome

> What version of Carbon for IBM.com are you using?

Deploy preview of story linked above

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

----
- Hybrid Cloud developer: John Kaeser
- [HC Jira ticket](https://jsw.ibm.com/browse/HC-2152)
- Dev estimate:  
- DDS consultant:  Kenny

**Comment by RobertaJHahn** [comment]
@oliviaflory Is this still an issue or has it been fixed?

**Comment by oliviaflory** [comment]
@RobertaJHahn There is still some space, but it's less noticeable now that the lead space does not have an image. Ideally we do fix it

[Current stable Web Components](https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-dotcom-shell--with-horizontal-toc)

<img width="1241" alt="Screen Shot 2021-08-18 at 9 23 57 AM" src="https://user-images.githubusercontent.com/45692622/129906214-2d9ae931-a5e5-4111-a4ad-3adfb5418fce.png">

**Comment by proeung** [comment]
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2152
HC Engineer Assignee: @jkaeser
