### ISSUE TITLE
Carbon for ibm.com June 2021 Release Plan (v1.20.0) 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5579]
- **June 2, 2021**: PR submission date
- **June 4, 2021**: Code freeze
- **June 7 - 14, 2021**: Release Candidate(s) and testing
- **June 15, 2021**: Full Release

### Features
- **content-block-card-static**
  - created component (#6198)
- **card**
  - introducing static variant with tag-group (#6133)
- **image**
  - adding `loading="lazy"` to images in web-components (#6164)
- **imports**
  - simplification of web component imports (#6156)
- **tag-group**
  - create new component (#6107)
- **footer**
  - add specific link title to legal link data-autoids (#6137)
- **content-item**
  - restrict footer to text-cta and button-cta (#6094)
- **tag-link**
  - create new component (#6038)

### Fixes
- **card-group**
  - optional border for card group default (#6152)
- **lightbox-video-player**
  - add check for video cta specific modal to open and prevent multiple modals from opening (#6260)
  - update videoid and only open if playing mode is lightbox (#6226)
- **leadspace**
  - fixes gradient and adds new leadspace image (#6259)
  - breadcrumb style import (#6239)
  - wrap breadcrumb after full row (#6216)
  - add super variation and tag group (#6154)
- **masthead**
  - apply global styles updates based on unified cloud masthead project (#5922)
  - menu options blocking items when active (#6168)
  - remove focus search toggle and fix console error (#6108)
- **masthead-search**
  - delay position for cursor focus (#6208)
- **dotcom-shell**
  - add checks if toc exist (#6257)
- **utilities**
  - use util package for deprecate instead of relative path (#6235)
- **logo-grid**
  - styles and functionality fixes (#6097)
- **tabs-extended**
  - label wraps 2 lines then truncates with tooltip (#6155)
- **content-block**
  - heading spacing fix (#6103)
- **content-group-simple**
  - multiple storybook fixes (#6092)
- **horizontal-rule**
  - update grid layout (#6037)
- **link-list**
  - vertical focus styles (#6080)
- **content-block-simple**
  - storybook cleanup (#5943)

### Housekeeping
- **cloud-foundry**
  - updating manifest configs to force https (#6238)
- **feature-card**
  - refactored block large and medium into component (#5950)
- **upgrade**
  - upgrade to carbon 10.36.0 (#6214)
  - upgrade to carbon 10.35.0 (#6093)
- **codesandbox**
  - clean up examples (#6204)
  - update examples (#6165)
- **deps**
  - update caniuse-lite (#6189)
  - bump hosted-git-info from 2.8.4 to 2.8.9 (#6007)
- **carousel**
  - fix carousel imports in react-wrapper readme instance (#6151)
- **leadspace**
  - add documentation on using video cta within leadspace (#6113)
- **akamai**
  - switching url for artifacts to akamai domain (#6067)
- **footer**
  - remove console log (#6057)
- **deps-dev**
  - bump postcss from 7.0.17 to 8.2.10 (#6045)

### Features
- **tag-group**
  - create new component (#6107)
- **footer**
  - add specific link title to legal link data-autoids (#6137)
- **tag-link**
  - create new component (#6038)

### Fixes
- **card-group**
  - optional border for card group default (#6221)
- **leadspace**
  - added deprecation warning and sync with web-components version (#6166)
- **logo-grid**
  - styles and functionality fixes (#6097)
- **tabs-extended**
  - label wraps 2 lines then truncates with tooltip (#6155)
- **content-group-simple**
  - multiple storybook fixes (#6092)
- **content-block-simple**
  - storybook cleanup (#5943)
- **masthead**
  - prevent enter key search when search field is empty (#6082)
- **storybook**
  - remove megamenu from l1 custom data storybook (#6019)

### Housekeeping
- **cloud-foundry**
  - updating manifest configs to force https (#6238)
- **feature-card**
  - refactored block large and medium into component (#5950)
- **upgrade**
  - upgrade to carbon 10.36.0 (#6214)
  - upgrade to carbon 10.35.0 (#6093)
- **codesandbox**
  - update examples (#6165)
- **yarn**
  - removing unnecessary yarn.lock file
- **akamai**
  - switching url for artifacts to akamai domain (#6067)

### Features
- **content-block-card-static**
  - created component (#6198)
- **card**
  - introducing static variant with tag-group (#6133)
- **tag-group**
  - create new component (#6107)
- **tag-link**
  - create new component (#6038)

### Fixes
- **card-group**
  - optional border for card group default (#6221)
  - optional border for card group default (#6152)
- **leadspace**
  - fixes gradient and adds new leadspace image (#6259)
  - added deprecation warning and sync with web-components version (#6166)
  - breadcrumb style import (#6239)
  - wrap breadcrumb after full row (#6216)
  - add super variation and tag group (#6154)
- **masthead**
  - apply global styles updates based on unified cloud masthead project (#5922)
- **card-static**
  - change background color on hover (#6213)
- **linklist**
  - video heading link style is broken (#6184)
- **logo-grid**
  - styles and functionality fixes (#6097)
- **code-snippet**
  - expressive code snippet carbon 10.31.0 update adjustments (#6171)
- **tabs-extended**
  - label wraps 2 lines then truncates with tooltip (#6155)
- **content-block**
  - heading spacing fix (#6103)
- **content-group-simple**
  - multiple storybook fixes (#6092)
- **horizontal-rule**
  - update grid layout (#6037)
- **content-block-simple**
  - storybook cleanup (#5943)

### Housekeeping
- **cloud-foundry**
  - updating manifest configs to force https (#6238)
- **feature-card**
  - refactored block large and medium into component (#5950)
- **upgrade**
  - upgrade to carbon 10.36.0 (#6214)
  - upgrade to carbon 10.35.0 (#6093)
- **codesandbox**
  - update examples (#6165)

### Housekeeping
- **cloud-foundry**
  - updating manifest configs to force https (#6238)

### Housekeeping
- **settings**
  - update settings to v1.20.0
  - update settings to v1.19.1
  - update settings to v1.19.1
- **cloud-foundry**
  - updating manifest configs to force https (#6238)
- **feature-card**
  - refactored block large and medium into component (#5950)
- **upgrade**
  - upgrade to carbon 10.36.0 (#6214)
  - upgrade to carbon 10.35.0 (#6093)

**Comment by jeffchew** [comment]
@RobertaJHahn release completed: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/releases/tag/v1.20.0
