### ISSUE TITLE
[Content block mixed] - Storybooks QA

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#5585]
### 1. Rename it in as: 
```

Content block mixed
    Default
    With link list

```
from this
<img width="229" alt="Screenshot 2021-03-24 at 12 57 45" src="https://user-images.githubusercontent.com/48327647/112307248-62360080-8ca9-11eb-808e-aa471dfd4133.png">

### 3. Intro copy has the wrong size token (or no token). It should be this:  Styles Package
<img width="1629" alt="intro text" src="https://user-images.githubusercontent.com/48327647/112307559-c6f15b00-8ca9-11eb-985b-53378bf0aeab.png">

### 4. This is a subheading, please remove the full stop/period/full point.
<img width="751" alt="sub-heading" src="https://user-images.githubusercontent.com/48327647/112307688-eb4d3780-8ca9-11eb-9313-6ee0275e6046.png">

### 5. Please make sure the cards respect the content height rules.
<img width="804" alt="cards alignment" src="https://user-images.githubusercontent.com/48327647/112307842-1c2d6c80-8caa-11eb-998d-1c8a54a28016.png">

### 6. Please make sure the card link respects the specs. Also, make sure, please, that the max-width of 320px is applied regardless of the viewport.

What its expected to be 
<img width="337" alt="Screenshot 2021-03-24 at 13 49 16" src="https://user-images.githubusercontent.com/48327647/112307999-4b43de00-8caa-11eb-91dc-7da5cc0a974b.png">

What is is 
<img width="441" alt="Screenshot 2021-03-24 at 13 48 58" src="https://user-images.githubusercontent.com/48327647/112308001-4bdc7480-8caa-11eb-87ae-acc456822da3.png">

### 7. The pictograms should be 80px X 80px. 
<img width="254" alt="Screenshot 2021-03-24 at 13 43 44" src="https://user-images.githubusercontent.com/48327647/112308486-dd4be680-8caa-11eb-8fe7-c391fb172ca6.png">
<img width="176" alt="Screenshot 2021-03-24 at 13 43 30" src="https://user-images.githubusercontent.com/48327647/112308490-de7d1380-8caa-11eb-8c58-43fa63b2490f.png">

### 8. Please, make sure the pictogram item component respects the specifications.

What i see:
<img width="503" alt="Screenshot 2021-03-24 at 13 56 58" src="https://user-images.githubusercontent.com/48327647/112308686-14ba9300-8cab-11eb-96f2-c77268ba389c.png">
<img width="708" alt="med 1" src="https://user-images.githubusercontent.com/48327647/112308689-15532980-8cab-11eb-9d9b-59b1dde1caec.png">
<img width="774" alt="Screenshot 2021-03-24 at 13 58 47" src="https://user-images.githubusercontent.com/48327647/112308683-12583900-8cab-11eb-9739-45722c6d0f61.png">

What I should see: 
<img width="1440" alt="Screenshot 2021-03-24 at 13 41 11" src="https://user-images.githubusercontent.com/48327647/112308817-3b78c980-8cab-11eb-8704-637309f06a42.png">
<img width="947" alt="med 2" src="https://user-images.githubusercontent.com/48327647/112308833-403d7d80-8cab-11eb-9a04-de39a84a0a22.png">

### 9. On Gray 100, the caption is the wrong type token:
<img width="436" alt="Screenshot 2021-03-24 at 13 58 11" src="https://user-images.githubusercontent.com/48327647/112308980-6e22c200-8cab-11eb-83bd-b1c75aaf7cea.png">

### 10. Please align the link list component icons to the containers: 
What I see:
<img width="500" alt="Screenshot 2021-03-24 at 13 57 09" src="https://user-images.githubusercontent.com/48327647/112309063-8eeb1780-8cab-11eb-88f4-088505742538.png">

What I should see: 
<img width="530" alt="Screenshot 2021-03-24 at 14 17 58" src="https://user-images.githubusercontent.com/48327647/112309237-c8238780-8cab-11eb-8ab3-fee9cea7c8e6.png">

## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by guilhermelMoraes** [comment]
@DragosRistici 5. This will likely need to be addressed in another issue. The same problem can be observed in the `Content Group Cards` story.
