### ISSUE TITLE
[Footer] Adjunct Legal links research, design and specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5586]
#### Overview
Implement the Legal Footer component as described in previous V18 / V19a
https://www.ibm.com/standards/web/v19a-archive/components/legal-footer/

#### Additional information
- **See the epic for the overarching descriptions of the work.**
- [Link to Alexandru Tasca Slack chat](https://cognitive-app.slack.com/archives/C2PLX8GQ6/p1615820883091800)
- [Link to skills academy info](http://ibm.biz/skillsacademy)
- Design and functional specs can be found in this [Box folder link](https://ibm.ent.box.com/folder/101562989787?s=nsbccv6jigfw78uwq3r0242qks1x1f87)

#### Acceptance Criteria
- [x] Create a Box folder for the `Footer` (if not already there)
- [x] Research findings are available in the above Box folder
- [x] Designs are created and approved
- [x] A Sketch file is created or updated with the `Footer adjunct Legal links changes` design and specs
- [x] The design specs and pdf version are added to the Box folder 
- [x] The epic is updated with the design spec link

**Comment by DragosRistici** [comment]
Footer design specs was updated to include Adjunct legal links, and they can be found in this [Box folder](https://ibm.ent.box.com/folder/101562989787?s=nsbccv6jigfw78uwq3r0242qks1x1f87).
