### ISSUE TITLE
Nav Menu cut off when in Arabic language

### ISSUE THREAD

**Issue by yellowdragonfly** [carbon-design-system/carbon-for-ibm-dotcom#5595]
> What version of Carbon for IBM.com are you using?
1.15.0
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
It is in production. So it would be nice to get fixed whenever possible.

## Steps to reproduce the issue

1. go to web site: https://proxy1.marketplace-test.ibmcloud.com/profile/dataprivacypreferences/ae-ar
2. Shrink the window
3. Click on "persona" icon
4. you will see the menu is cut off by the screen

## Additional information
![image (2)](https://user-images.githubusercontent.com/49878979/112362065-6adb0680-8caa-11eb-9b2c-2476b77c96df.png)
![image (3)](https://user-images.githubusercontent.com/49878979/112362100-762e3200-8caa-11eb-9202-760830d44ee9.png)

- Screenshots or code
- Notes

**Comment by annawen1** [comment]
installing the `rtlcss` npm package as mentioned in our rtl docs here: https://ibmdotcom-react.mybluemix.net/?path=/docs/overview-enable-right-to-left-rtl--page might solve the issue

**Comment by RobertaJHahn** [comment]
@yellowdragonfly  Did the suggestion by Anna fix this problem?

**Comment by RobertaJHahn** [comment]
@yellowdragonfly we are closing this issue, assuming the that the issue has been resolved as a result of Anna's comments above.
