### ISSUE TITLE
[Carbon v10.31.0 Upgrade | Expressive] Alignment and size of input icon is off

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5597]
## Detailed description

> Describe in detail the issue you're having.

![image](https://user-images.githubusercontent.com/1641214/112368540-91507000-8cb1-11eb-89ff-3ad96047d1e2.png)

![image](https://user-images.githubusercontent.com/1641214/112368626-ab8a4e00-8cb1-11eb-92f2-ec4d210e9cb7.png)

> Is this issue related to a specific component?

Input

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Alignment of caret is corrected
Size of caret is corrected

> What version of Carbon for IBM.com are you using?

Current branch `chore/carbon-10.31.0-upgrade`. **Fixes should be targeted to this branch.**

## Additional information

1. Deploy Preview: https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/5566/index.html?path=/story/components-masthead--default
2. Percy Build (React): https://percy.io/538fc19a/Carbon-for-IBM.com-React/builds/9518436/changed/537649382?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=320%2C1280
3. Percy Build (Expressive): https://percy.io/538fc19a/Carbon-Expressive-Theme/builds/9518540/changed/537658459?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=320%2C1280

**Comment by NSDrowned** [comment]
Fixed in PR #5709 👍
