### ISSUE TITLE
[Carbon v10.31.0 Upgrade | Expressive] Combo box icon alignment and size

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5602]
## Detailed description

> Describe in detail the issue you're having.

![Screen Shot 2021-03-24 at 4 22 30 PM](https://user-images.githubusercontent.com/45692622/112378826-c5ca2900-8cbd-11eb-8eb6-2f62d4d0bf27.png)

- icon is not vertically centered within container
- looks like icon was reverted to 16px size, should be 20px per expressive theme

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

Combo box

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Alignment and size of caret are corrected

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

Current branch `chore/carbon-10.31.0-upgrade`. **Fixes should be targeted to this branch.**

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information
- Percy https://percy.io/538fc19a/Carbon-Expressive-Theme/builds/9518540/search/preview/537658362?browser=chrome&searchParam=combo&viewLayout=side-by-side&viewMode=new&width=1280
- Deploy preview https://carbon-expressive.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/5566/index.html?path=/story/combobox--default
- Component kitchen sink story https://carbon-expressive.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/5566/index.html?path=/story/component-icons-kitchen-sink--default

**Comment by NSDrowned** [comment]
Fixed in PR #5709 👍
