### ISSUE TITLE
[Carbon v10.31.0 Upgrade | Expressive] Multi select icon alignment and size 

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5606]
## Detailed description

> Describe in detail the issue you're having.

![Screen Shot 2021-03-24 at 5 04 45 PM](https://user-images.githubusercontent.com/45692622/112383095-11330600-8cc3-11eb-914f-36b539d8f197.png)

- icon is not vertically centered within container
- looks like icon was reverted to 16px size, should be 20px per expressive theme

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

Multi select

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Alignment and size of caret are corrected

**NOTE: Fixes should be targeted to the branch `chore/carbon-10.31.0-upgrade`.**

## Additional information
- Percy https://percy.io/538fc19a/Carbon-Expressive-Theme/builds/9518540/search/preview/537658450?browser=chrome&searchParam=multi&viewLayout=side-by-side&viewMode=new&width=1280
- Deploy preview https://carbon-expressive.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/5566/index.html?path=/story/multiselect--default
- Component kitchen sink story https://carbon-expressive.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/5566/index.html?path=/story/component-icons-kitchen-sink--default

**Comment by NSDrowned** [comment]
This was also fixed in PR #5709 👍
