### ISSUE TITLE
[Carbon Expressive] Notification inline vertical alignment is off 

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5607]
## Detailed description

> Describe in detail the issue you're having.

![Screen Shot 2021-03-24 at 5 12 01 PM](https://user-images.githubusercontent.com/45692622/112383956-2d837280-8cc4-11eb-9c31-523de382bc78.png)

![Screen Shot 2021-03-24 at 5 12 01 PM](https://user-images.githubusercontent.com/45692622/112384047-4c820480-8cc4-11eb-9a2c-1f614f12c0a1.png)

Vertical alignment is off within inline notification.

This is a tricky one because the inline variant allows for the notification to grow in height if the content grows to two lines. I'm assuming we could control the text alignment by top padding, but not sure if we want to introduce that.

Also expected the total height to be 48px, but it's 56. Not sure what's causing that.

*Looks like this is happening in the current build, so I don't think it's coming from the upgrade to 10.31.0*

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Notification inline

> What did you expect to happen? What happened instead? What would you like to
> see changed?

- height of container
- vertical alignment of content

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

**NOTE: Fixes should be targeted to the branch `chore/carbon-10.31.0-upgrade`.**

## Additional information
- Percy https://percy.io/538fc19a/Carbon-Expressive-Theme/builds/9518540/search/preview/537658455?browser=chrome&searchParam=noti&viewLayout=side-by-side&viewMode=new&width=1280
- Deploy preview https://carbon-expressive.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/5566/index.html?path=/story/notifications--inline

**Comment by shixiedesign** [comment]
Similar issue is happening with Toast notification. Julio is kind enough to include it in this fix! Here's the detail: 

![image](https://user-images.githubusercontent.com/15144993/113055705-e6402a80-9178-11eb-9ce2-a317f01d5eb9.png)
