### ISSUE TITLE
[Carbon expressive] Code snippet single line off

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5611]
## Detailed description

> Describe in detail the issue you're having.
 - [x] missing 16px padding on the left side of code snippet
**Expressive**
![Screen Shot 2021-03-24 at 6 00 04 PM](https://user-images.githubusercontent.com/45692622/112389327-f3699f00-8cca-11eb-8b81-c1f1244e7930.png)
**Carbon reference** 
![Screen Shot 2021-03-25 at 9 40 18 AM](https://user-images.githubusercontent.com/45692622/112482198-2b65f600-8d4e-11eb-8d09-06015bb9c909.png)

- [x] Hover state has odd overlay 

![Screen Shot 2021-03-24 at 6 00 10 PM](https://user-images.githubusercontent.com/45692622/112482024-01accf00-8d4e-11eb-977c-13037bb46831.png)
**Carbon reference**
![Screen Shot 2021-03-25 at 9 40 53 AM](https://user-images.githubusercontent.com/45692622/112482254-3d479900-8d4e-11eb-8b0e-917ef4c6ece1.png)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

Code snippet inline

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Fix left padding and hover state

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information
- Carbon expressive https://carbon-expressive.mybluemix.net/?path=/story/codesnippet--single-line
- Carbon reference https://react.carbondesignsystem.com/?path=/story/components-codesnippet--singleline

**Comment by RobertaJHahn** [comment]
this bug is related to the Carbon upgrade managed in epic (#5600 ).  Once the upgrade is finished, this bug should be checked for status.
