### ISSUE TITLE
[Carbon Expressive] File uploader

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5613]
## Detailed description

> Describe in detail the issue you're having.

Buttons are not the same size, seems odd and likely were the same size at some point. Can we confirm if one of the two scenarios are happening: 
- It's possible the buttons are not getting the expressive size update
- Also possible that the button size for primary is default, and clear file is small

![Screen Shot 2021-03-24 at 4 38 54 PM](https://user-images.githubusercontent.com/45692622/112485489-5e5db900-8d51-11eb-9f51-fbcae4d7d183.png)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

expected buttons to be same size

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information
https://carbon-expressive.mybluemix.net/?path=/story/fileuploader--file-uploader

**Comment by RobertaJHahn** [comment]
Should be checked after the Carbon upgrade.  Managed in epic (#5600 )

**Comment by jeffchew** [comment]
Closing this since we are sunsetting the expressive theme.
