### ISSUE TITLE
Video Player Web Component not rendering video thumbnail

### ISSUE THREAD

**Issue by stephcard** [carbon-design-system/carbon-for-ibm-dotcom#5615]
Hello! I'm super excited to be working with Carbon for IBM Web Components.

I noticed the sample video player component renders the video image by default (which is awesome) but that doesn't seem to be the case when implementing the component - the picture element and image does not render in the shadow dom. Nor does it render the picture element and image when specifying `thumbnail-url`.

Is this a bug? Any advice is much appreciated.

Screen grab attached.
![Screen Shot 2021-03-25 at 10 21 03 AM](https://user-images.githubusercontent.com/28735880/112501475-a8e63200-8d5f-11eb-97fd-316b187d7fe4.png)

Staging here: https://wwwpreview.ibm.com/repeatables/simple-scroll/

**Comment by stephcard** [comment]
Hello. I was able to resolve this by including the image component. Please consider updating the video player component's documentation to mention this dependency. Thank you!

**Comment by annawen1** [comment]
Hello @stephcard we will update the video player component so you will not have to import the image component yourself. Fix will come soon.
