### ISSUE TITLE
Fix bugs introduced from fix for issue #4174

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5618]
[Issue #4174](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4174) introduced a bunch of spacing errors and this makes Canary buggy. We have to **fix key regressions before merging to Production**.

**Comment by jeffchew** [comment]
FYI, going to rename this epic, this was not due to a Carbon upgrade but from a specific PR:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5480
