### ISSUE TITLE
[Beacon for IBM.com] Generate visual reporting pages based on Beacon data

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5630]
#### User Story

> As a `[user role below]`:
Offering Manager

> I need to:
see compliance data over time for one or many IBM.com application teams

> so that I can:
report and track the trend of compliance for all IBM.com sites

#### Additional information

 - Based on research for reporting data and tooling: #5629 
 - Determine where this application/page should live, and who has access

#### Acceptance criteria
 - [ ] Application that uses Beacon data to visualize trends over time

**Comment by RobertaJHahn** [comment]
No Longer needed.
