### ISSUE TITLE
Implement a `.nvmrc` to configure Node Version Manager for this project

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#5641]
### The problem

Most of us devs are working on multiple projects that require different versions of nodes. Depending on what version of node that you're using it might not be compatible with this project and version "12.x^" is the version of node that's expected.

### The solution

To avoid getting the following error below when starting up the project, let's look into adding a `.nvmrc` file that allows anyone with `nvm` to know the default node.js version and install the correct one.

`error carbon-for-ibm-dotcom@0.0.0: The engine "node" is incompatible with this module. Expected version "12.x". Got "14.16.0"`

**Comment by RobertaJHahn** [comment]
Jeff will include in Oct 31 Engineering Huddle agenda.

**Comment by jeffchew** [comment]
Thank you for the suggestion @proeung !

We have discussed and decided that we will not include as not all users are using nvm. There are other node version managers available as well and we would not be able to include for all.

For a quick solution, the `.nvmrc` file can be added locally and excluded via `.gitignore_global` in your home directory.
