### ISSUE TITLE
Video player - support video overlay in the middle of browser

### ISSUE THREAD

**Issue by aiproulx** [carbon-design-system/carbon-for-ibm-dotcom#5643]
Play video in the middle of the browser with overlay.

### The problem
Video plays only on the page directly. Need the video to play as overlay on the page.

### The solution
Example: https://www.ibm.com/cloud/paks

Video is overlay on the full page.

### Additional information
![image](https://user-images.githubusercontent.com/11738743/112688286-de5d4f00-8e35-11eb-9e3f-f62a955bd7a4.png)

**Comment by oliviaflory** [comment]
@aiproulx We have the `Lightbox media viewer` that plays the video in a modal that is similar.

[Carbon for IBM.com website](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/lightbox-media-viewer)
[React storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/components-lightboxmediaviewer--embedded-video-player)
[Web components storybook](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-lightbox-media-viewer--embedded-video-player)

**Comment by aiproulx** [comment]
@oliviaflory Thank you Olivia for sharing. I think the overlay used by these sites is far slicker and simpler:

https://www.ibm.com/cloud/satellite
https://www.ibm.com/cloud/paks

**Comment by shixiedesign** [comment]
Sorry @aiproulx, please use the `Lightbox media viewer` as Olivia provided for this moment in the design to align with the system.
