### ISSUE TITLE
[Table of contents] storybook updates

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5644]
## Update ToC storybook

<img width="899" alt="Screen Shot 2021-03-26 at 4 27 48 PM" src="https://user-images.githubusercontent.com/45692622/112689172-4ae54780-8e50-11eb-836d-24a77a18293e.png">

### Variations
Only two variations of Table of contents:
- Vertical (default)
- Horizontal
- Remove "With heading content" as its own story, it should be a knob under Vertical (see below)

### Vertical knobs
**1. With heading content**
- remove image example
- use link list like in the design specs
 | ![Screen Shot 2021-03-15 at 3.34.11 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/e016bf3b-0e8d-4d12-bfdc-8b37981aa141) | ![Screen Shot 2021-03-15 at 3.43.04 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/fdccb286-4304-4057-a44c-fb7e3c15cc55) |
- rule is added by default when heading content is included, see functional specs
![image (1)](https://user-images.githubusercontent.com/45692622/112689554-d8289c00-8e50-11eb-95de-8491dda58ff9.png)
- this can be a checkbox

**2. Number of items** 
- Default to 5
- Dropdown option of 4-8

**3. Content**
_It would be nice if we could allow users to include their own labels/content into the demo_

### Horizontal knobs
**1. Number of items** 
- Default to 5
- Dropdown option of 4-8

**2. Content**
_It would be nice if we could allow users to include their own labels/content into the demo_

## Additional information
React only has vertical as of now (March 26), TBD if horizontal variation is added as a React wrapper or React.
- If added as a wrapper, could React storybook link to React wrapper?

React also has options for `Dynamic items` and `Manually define menu items` 
- not sure if those options are built into Web components
- Raph was looking into if we needed to have both options and if we should show in storybook?

#### Acceptance criteria
 - [ ] Answer/confirm questions in Additional information to determine if they need to be included in the stories 
- [ ] Web components storybook is updated to reflect above changes
 - [ ] React storybook is updated to reflect above changes

**Comment by emyarod** [comment]
trying to understand the React storybook changes and I'm missing some context for the extra "Manually define menu items" and "Dynamic items" stories. They seem to be obsolete due to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/3081 so I think it's fine to just remove them
