### ISSUE TITLE
[g100] Color theme changes type size

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#5647]
For some reason, the link with icon is changing type size on a theme change... Was it doing that before? Just to be clear color themes `white`, `g10`, `g90`, and `g100` should not have any impact on type tokens.

![Mar-24-2021 15-56-15](https://user-images.githubusercontent.com/3793636/112382321-b6e17780-8cb9-11eb-82a1-095e8a07b9a4.gif)

> 👀  &nbsp;&nbsp;See https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5528#pullrequestreview-620225824 for reference

Here is the preview link since it hasn't merged as of writing this issue:
https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/5528/index.html?path=/story/components-callout-quote--default

**Comment by photodow** [comment]
@oliviaflory noticed a similar thing happening with the card eyebrow. Something definitely weird going on there.

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5552

**Comment by oliviaflory** [comment]
I think it's possible the expressive theme value overrides are broken on Gray 100 themes

Link with icon was originally built with $body-short-01, which is 14px in productive theme. Looks to me like it might be reverting to the productive size and not getting the expressive overrides from the expressive theme.



Other instances where I'm seeing this happen:
- Card eyebrow ($label-01) #5552 
- Image with caption ($caption-01)
- Leaving IBM ($label-01)
- Video player ($caption-01)

Any component using the following tokens would be affected:
- $label-01
- $caption-01
- $helper-text
- $code-01
- $code-02
- $heading-01 / expressive-heading-01
- $body-short-01
- $body-long-01
