### ISSUE TITLE
[Masthead] L0 options with dropdown is missing 8px space between label & chevron

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5650]
Masthead L0 options with dropdown is missing 8px space between label & chevron

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/694b0ee2-c4a2-41e6-b04e-b230c7b75ccc)

**Comment by annawen1** [comment]
Both WC and React carets have the 8px margin styling applied. Looks like there is a difference in the caret svg file sizing that may be causing this.

WC:
![Screen Shot 2021-03-29 at 11.22.49 AM.png](https://images.zenhubusercontent.com/5d8b7880bb171300016bf0b4/59ec99a9-2608-4bad-95df-affd1dd73fd3)

React:
![Screen Shot 2021-03-29 at 11.22.40 AM.png](https://images.zenhubusercontent.com/5d8b7880bb171300016bf0b4/dcb1830c-3917-420a-b99b-94f3dbf82eab)

**Comment by guilhermelMoraes** [comment]
@shixiedesign as Anna mentioned above, the `8px` margin is in there.

**Comment by annawen1** [comment]
Hey @guilhermelMoraes, the 8px is there but I think the issue is the svg chevron in web components is not the size we're expecting which is causing the spacing to look off. You can see in the Web components vs React screenshots I have above that the svg size is different.

**Comment by shixiedesign** [comment]
Just checked again - issues till present!
