### ISSUE TITLE
[Card] storybook updates

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#5651]
### Card - default storybook entry:

The pink box highlights the knobs that need update.

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/8c076af5-5401-4b88-825a-b5fb71231566)

### Card - pictogram storybook entry: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/b4d9565a-6f31-4542-89bc-545ac5ac9ee6)

### Card - static storybook entry: 

Content on the card should change to below to be accurate to the intended usage of this card: 

| Field | Content | 
| --- | --- |
| Eyebrow text | SPSS Statistics |
| Heading | Free trial |
| Copy | Enjoy full SPSS Statistics capabilities including all add-ons. All trial registrants are restricted to one free trial per computer per year. |

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/089d6e20-8fb3-4a64-8b9a-f4667b1a600f)

## Additional information
- https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-card--default
- https://ibmdotcom-react.mybluemix.net/?path=/story/components-card--default

**Comment by shixiedesign** [comment]
Noticed recently in canary many knobs under `Card - default` disappeared. Can we restore the knobs so I can test the cases where some optional texts are absent? Left side is Web components, right side React. Reference Olivia's issue description above for the expected list of knobs: 

![image](https://user-images.githubusercontent.com/15144993/115052518-062b5a00-9eac-11eb-87f0-c8fe4b7ba379.png)

**Comment by shixiedesign** [comment]
This is still an issue to address. Design need to look through the issue description to make sure it's still up to date? One thing I noticed we might need to add is `Outlined card`.
