### ISSUE TITLE
Support image in experimental Leadspace with search

### ISSUE THREAD

**Issue by Daynssjal** [carbon-design-system/carbon-for-ibm-dotcom#5664]
Hi. 
We would like the experimental Leadspace with search component to also support background image.

This is the Leadspace with Search component:
https://ibmdotcom-react-experimental.mybluemix.net/?path=/story/components-leadspacewithsearch--default

we would like to have a possibility of passing in background image, just like here:
https://ibmdotcom-react.mybluemix.net/?path=/story/components-leadspace--default-with-image

Thank you

**Comment by RobertaJHahn** [comment]
This work should be considered in the Lead space investigation.
