### ISSUE TITLE
[Content group horizontal] Storybooks QA

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#5668]
## General entry
0.  Rename to Content block horizontal (no one remembers why this is named Content group horizontal)

1. Storybooks entry should be: 

```

Content block horizontal
    Default

```

## General issues

1. Make sure the spacing after the section heading is 32px as according to AEM recommendations

What it should be 
<img width="753" alt="Screenshot 2021-03-30 at 15 11 32" src="https://user-images.githubusercontent.com/48327647/112986583-56937f80-916a-11eb-884e-5cc7e0270ef4.png">

What it currently is
<img width="710" alt="Screenshot 2021-03-30 at 15 11 18" src="https://user-images.githubusercontent.com/48327647/112986589-585d4300-916a-11eb-9c0e-9ab935a8fd9e.png">

2. There is an extra bottom padding for the links that makes the spacing between them and the horizontal rule 64px + an extra 16px

3. The grid alignment is off. Content starts at col 4
<img width="1367" alt="Screenshot 2021-03-30 at 15 20 16" src="https://user-images.githubusercontent.com/48327647/112987628-9e66d680-916b-11eb-8ed7-3e7aa5035019.png">

4. Horizontal rule should span 12 col and overhang

What it should be
<img width="872" alt="Screenshot 2021-03-30 at 15 22 12" src="https://user-images.githubusercontent.com/48327647/112987850-d3732900-916b-11eb-9f87-0fda2546877c.png">

What it currently is
<img width="1605" alt="Screenshot 2021-03-30 at 15 22 24" src="https://user-images.githubusercontent.com/48327647/112987860-d53cec80-916b-11eb-88f3-05ee67808416.png">

5. Adjust the content item width on md

What it should be
<img width="1072" alt="Screenshot 2021-03-30 at 15 24 51" src="https://user-images.githubusercontent.com/48327647/112988180-3a90dd80-916c-11eb-99b7-b08b5eefe25b.png">

What it currently is
<img width="744" alt="Screenshot 2021-03-30 at 15 24 59" src="https://user-images.githubusercontent.com/48327647/112988189-3c5aa100-916c-11eb-8868-dc5c024a33ee.png">

**Comment by RobertaJHahn** [comment]
Design will confirm the remaining and specs of this component, then work will be ready for dev.

**Comment by shixiedesign** [comment]
@RobertaJHahn  @DragosRistici I'm gonna break this issue down into smaller dev issues to fix. Design clean up is done.
