### ISSUE TITLE
[Video player] hover state joint design research / investigation

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5681]
#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- [box folder]
- [reference materials]

#### Acceptance Criteria
- [x] Design direction(s) has been identified, reviewed, and approved for the final design phase
- [x] The next story has been updated with the design direction

**Comment by shixiedesign** [comment]
Found my old prototype I did back on Reboot: 

https://www.figma.com/proto/pVH385cIPauyJgF7o1k2CK/Card-hover?node-id=36%3A0&scaling=min-zoom
