### ISSUE TITLE
[Filter panel] Create the functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5685]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Filter panel` functional specs 

> so that I can:
so that I can properly code the `Filter bar` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5469 )**
 - Design investigation and exploration issue  (#5683 )
 - Development issue (#TBD )
 - Visual Designs & Functional Design Specs Box folder link(TBD)

#### Acceptance criteria
 - [ ] Documented `Filter panel` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by RobertaJHahn** [comment]
Functional specs reviewed with DDS engineers in May 24 Issues refinement meeting.

**Comment by photodow** [comment]
Functional spec links

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Filter-group
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Filter-panel
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Input-select

Thanks @oliviaflory!
