### ISSUE TITLE
[Video player] Additional states functional specs - hover, active, focus

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5687]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Video player` functional specs 

> so that I can:
so that I can properly code the `Video player` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5514 )**
 - Design research / investigation Issue (#5681)
 - React dev issue (#5809 )
- Web Components dev issue (#5805 )
 - Visual Designs & Functional Design Specs Box folder link(TBD)

#### Acceptance criteria
 - [ ] Documented `Video player` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by photodow** [comment]
I'm going to let this close. I think we decided we don't need to add hover and active states like this. Design specs usually handle that. Please reach out if anyone remembers differently.
