### ISSUE TITLE
[Performance] Investigate why there are many DOM elements in locale search

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5692]
#### User Story

> As a `[user role below]`:
IBM.com application offering manager

> I need to:
have reduced load times for my IBM.com application

> so that I can:
improve SEO performance of my application

#### Additional information

 - One of the takeaways from Lighthouse performance reports are that there are too many DOM elements on the page. The locale search component in particular was reported to have many elements in there, even though the component itself is not loaded visually on the page yet

#### Acceptance criteria
 - [ ] Investigate the cause of the large  number of DOM elements
- [ ] Identify any follow-up issues based on the investigation

**Comment by jeffchew** [comment]
@RobertaJHahn need to size and set priority for this, can be a potential candidate for sprint 8.

**Comment by RobertaJHahn** [comment]
Closing, did not have impact on the performance
