### ISSUE TITLE
[Performance] Investigation of page performance issues for web components

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5693]
#### User Story

> As a `[user role below]`:
IBM.com application offering manager

> I need to:
have performant pages in my IBM.com application using web components

> so that I can:
score higher in SEO rankings

#### Additional information

- This work is a blocker for AEM to ingest the pages into Adobe 
- Some initial tests were done on the pages: https://www.ibm.com/partners, and https://www.ibm.com/testing/partners (page without `ibm-common.js`)
 - Page itself has image loading opportunities, but should focus more on other optimizations around number of DOM elements, script evaluation time, etc

#### Acceptance criteria
 - [x] Identify opportunities and tasks on how the web components package can be improved in page speed performance
 - [x] Playback to the engineering team
 - [ ] Create issues / next steps

**Comment by jeffchew** [comment]
@RobertaJHahn here is another story for dev research, and also a candidate for sprint 8. We should timebox this exercise probably, but need to estimate.

**Comment by jeffchew** [comment]
@kennylam As discussed, a couple of things we could possibly do is to lazy load the Masthead menu and Locale Modal.

**Comment by kennylam** [comment]
After investigation there are no more improvements to be made to performance at this time. The remaining issues affecting performance exist on the application side. Based on Lighthouse audits the main contributing factor to the low score are long load/paint times. There has been some improvement from https://github.ibm.com/partnerworld/partnerworld-landing/pull/64 but more optimizations will need to be made in the application before more testing can be done.
