### ISSUE TITLE
[Card group] aspect ratio concerns

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#5710]
## Detailed description
I think design should take a look at this before development fully picks it up. This is a follow-up from #5567 (PR).

##### Here is what I'm seeing

There appears to be some sort of aspect ratio being applied in particular at lower breakpoints of card group. You can see it here in `sm` when the cards are one column full width, but I'm wondering if it's happening at other breakpoints as well.

<img src="https://user-images.githubusercontent.com/3793636/113630594-bdfb7480-962d-11eb-8704-c53579f07b90.gif" width="350px" />

Notice how the cards in the above gif change height as the width changes. It appears to be a `2:1` ratio here. I'm not seeing that in the specs, but I'm wondering if it should or shouldn't and if `2:1` is the correct value for that ratio. Also if the ratio is supposed to be applied to this component, is it supposed to be applied at smaller breakpoints because it appears to be applying extra space. Another thing to consider is if the card group should have an aspect ratio at all because for example, some scenarios appear to be `1:1` while others with media are a custom ratio that has a `2:1` content and `4:3` media.

### Additional resources
- http://ibmdotcom-web-components.mybluemix.net/?path=/story/components-card-group--default
- https://ibm.box.com/s/r4nt1w1fe2gnuqn6m9gac48tll7jq5pl

**Comment by RobertaJHahn** [comment]
Reviewed in the 4/15 adopter meeting.  Shixie to discuss with the designers.

**Comment by shixiedesign** [comment]
Discussed with designers during huddle on Thursday. So in short, we do not expect additional aspect ratio expect the one applied to the **Card**, min height to preserve 2:1 aspect ratio. 

### The next step: 

**[Card group] Change to same height util application**
_(dev issue, feature request, style package)_
- Change same height util to apply to whole group, so cards in the group always the same size. 
- Same height util should turn OFF on `sm` breakpoint where cards are 1 column stacked
