### ISSUE TITLE
Setup a deploy preview for Cloud Masthead endpoint within the `webstandards/ibm-dotcom-translations` repo

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#5714]
### The problem
- The HC team is now using the `webstandards/ibm-dotcom-translations` repo to house all of our masthead and footer data. 
- As part of the content management and PR process, we need to set up a deploy build preview that allows folks to preview and verify their content changes.
- This deployed preview is similar to the ones that @jeffchew set up for `Carbon` and `v18/Northstar` (see attached).

![Screen Shot 2021-04-06 at 1 35 28 PM](https://user-images.githubusercontent.com/1815714/113754214-ff972880-96dc-11eb-86a0-fdbd96ee4888.png)

### The solution
- Create a new deploy preview pipeline similar to the one created for the `Carbon` preview.
- Set the name to `Cloud`

### Additional information
- We have a PR opened for adding the Cloud-specific container and composite components, which will be needed to assemble this preview. https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5593

**Comment by proeung** [comment]
@annawen1 When you have a moment, can you let me know if this work is still part of the `Sprint 21-11` that's due on 06/04? Just wanted to get a sense of when we have this preview available within the PRs for the `webstandards/ibm-dotcom-translations` repo, since we're going to be adding other translation files soon and it's nice to have a preview of the changes. Thanks!

**Comment by annawen1** [comment]
@proeung Yep, this has been done! You should now be able to see the deploy previews when adding the `cloud` label to your PR in the translations repo
