### ISSUE TITLE
AEM: Missing the ability to change IBM Logo color 

### ISSUE THREAD

**Issue by sbahl1** [carbon-design-system/carbon-for-ibm-dotcom#5721]
**Adopter:** AEM
**Type:** Change request/Defect
**Actual results:** 
- IBM logo and search eyeglass icon with page theme g90/100 are hard to see on the page for the .com customers
- When an L1 navigation is used, the color of the L1 navigation differs from the masthead. 

**Expected result:**  Logo color should change with the theme
**Related CMS JIRA ticket** is https://jsw.ibm.com/browse/ADCMS-876

**Screenshots**
![image-2021-04-07-15-32-32-596](https://user-images.githubusercontent.com/57197236/113877500-c1eeda00-9786-11eb-9b94-f9afde63292e.png)
![IBMLogo](https://user-images.githubusercontent.com/57197236/113877510-c4e9ca80-9786-11eb-9b57-0f1a4e17da03.jpg)
![eyeGlass](https://user-images.githubusercontent.com/57197236/113877523-c7e4bb00-9786-11eb-9260-e91738bf1f07.jpg)

**Comment by shixiedesign** [comment]
Hey Sandeep, we do not allow Masthead to be rendered in any other theme except White. So this is not a bug. [Here's the PR ](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5609) intended to lock it in white theme. Do you need the masthead in dark for some reason?

**Comment by sbahl1** [comment]
Closing this
