### ISSUE TITLE
React: [Notification - Announcement Banner] (behind a feature flag) - limited scope Prod QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5728]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `Notification - Announcement Banner`

> I need to:
have an early version of the pattern or component that has been tested for Tier 1 browsers and platforms

> so that I can:
use the pattern on an ibm.com web page or in a cms template to gather design metrics to validate or change the existing design

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1, 13.3 and 14
- Browsers to be tested:  **Desktop:** Chrome, Firefox, Safari, Edge, **Mobile:** Chrome and Safari  **Tablet:** Chrome and Safari
- [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- **See the Epic for the Design specs information.  Functional specs are not created for patterns behind a feature flag**
- Dev issue (#5512 ) 
- can test here: https://annawen1.github.io/ibm-dotcom-think-banner/

#### Acceptance criteria
- [ ] All Tier 1 browser versions are tested
- [ ] All Tier 1 operating systems are tested
- [ ] All Tier 1 devices are tested
- [ ] Defects are recorded

**Comment by RobertaJHahn** [comment]
The test environment is not set up yet.  Anna will reach out to Ryan for a status.

**Comment by annawen1** [comment]
The Think banner can be tested here: https://annawen1.github.io/ibm-dotcom-think-banner/

**Comment by RobertaJHahn** [comment]
@Praveen-sr We would like to review the results of your testing in the Prod QA meeting tomorrow morning US time.  

cc:  @annawen1 @ariellalgilmore

**Comment by RobertaJHahn** [comment]
Slack message:  ![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/13484e31-b5bd-4ee2-a5a5-c072742cf16a)

Closing
