### ISSUE TITLE
[Content group cards] Storybook - Web Comp - card focus outline incorrect

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#5732]
The Web Comp Storybook card focus outline is not correct:
![image](https://user-images.githubusercontent.com/48327647/114030655-49ba0e80-9883-11eb-93df-f17b4283fad3.png)

**Comment by IgnacioBecerra** [comment]
@DragosRistici Seems like this has been fixed already, would you be able to confirm?

**Comment by DragosRistici** [comment]
@IgnacioBecerra There's still a double outline for the cards in the content group cards. Check the others, like Card section simple:


This one is Card section simple:
![Screenshot 2021-04-20 at 19.30.59.png](https://images.zenhubusercontent.com/6024dfe2f687e36aef6881c5/326fa60c-fc97-40fd-83c8-3be442ff91bf)

This one is Content group cards:
![Screenshot 2021-04-20 at 19.30.45.png](https://images.zenhubusercontent.com/6024dfe2f687e36aef6881c5/02bdee80-186f-4df5-b703-d8008b8ed8b9)

I'm checking here: http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-content-group-cards--default

Thanks, 
Dragos
