### ISSUE TITLE
[Content section] investigate usage, spacing and implementation options  

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5734]
From Putra:

> I'm not sure if this is true. Looking at the styling of the content section component, I can see that the top padding is set to spacing-09 - 48px where it needs to be spacing-07 - 32px to align with banner variant. This looks like an issue where the spacing needs to be adjusted to work with different patterns (eg. Content Group Banner, Card section image, etc).

If there are different spacing needs, it might comes down to having such a component doesn’t make sense?

**Comment by proeung** [comment]
@shixiedesign Thanks for creating this ticket. Please see more detail about my finding here - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5697#issuecomment-815161769

![content-section-banner](https://user-images.githubusercontent.com/1815714/114048258-6260ff00-9858-11eb-9e95-3291387fba66.jpg)

**Comment by JennySanchez** [comment]
@RobertaJHahn This is the styling issue from the connected [Git comment and conversation](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5697#issuecomment-815161769), and we need to discuss if we need the section component or change something to make the spacing work.

**Next step:** Designers have a discussion and define the next step.

**Comment by RobertaJHahn** [comment]
To be included in the 4/26 Design issues refinement meeting

**Comment by shixiedesign** [comment]
Discussed with James. Here are the next steps: 
- Make a ticket for James to audit the Content section current implementations spacing https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6017
- Need design spec https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6018
