### ISSUE TITLE
Research tools that can be used to document the functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5739]
#### Overview
The functional specs are currently created in Microsoft Word.  This tool is not ideal and lacks some key features that are needed to properly support versioning and dependent components impacted by changes, as examples.  The tool options were investigated a couple of years ago.  It is time to revisit the options currently available.

#### High level requirements
- Formatting from existing documentation can be replicated easily (e.g. tables, column layouts, etc)
- Ability to link/reference other specification documents
- Automatic 2-way linking/referencing if another specification document is referenced
- Commenting/collaboration for each document
- Ability to add process flow diagrams that can be easily modified within the tool
- Version tracking
- Github integration

#### Additional information
- 

#### Acceptance Criteria
- [ ]

**Comment by photodow** [comment]
Do we have any set of requirements for this work?

**Comment by jeffchew** [comment]
> Do we have any set of requirements for this work?

@photodow I added some initial high level requirements that I think will be valuable, would like @shixiedesign @ljcarot @RobertaJHahn  to also weigh in.

**Comment by jeffchew** [comment]
@photodow sent you an invite to evaluate the Confluence space:
https://carbon-for-ibm-dotcom.atlassian.net

**Comment by jeffchew** [comment]
@photodow Carbon team appears to use Notion (https://www.notion.so/), but to what extent I'm unsure, and appears to be a competitor to Confluence. 

I'll have to find out from the licensing side of things if this is an approved IBM tool that can be expensed.

**Comment by jeffchew** [comment]
https://www.atlassian.com/software/confluence/comparison/confluence-vs-notion

**Comment by shixiedesign** [comment]
Note: Carbon uses notion for content editing / sharing, not functional spec. Carbon's components also contains less inter-dependency and it's largely undocumented... (eg. unable to confirm if Data table's search bar uses the Search component.)

**Money shot from Confluence**

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/2de1c1bb-c391-45a7-bdb7-627e19862f67)

**Comment by shixiedesign** [comment]
Website could potentially be the good place. We author the component's func spec & dependencies, and website on build time run a function that adds the `Used by` row info. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/9fb6e19b-d063-499a-bb52-d2229c17836c)

Ultimately, what we need to catch is this kind of circular dependencies: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/b4146ef3-8d51-40fc-af0b-b513614f407e)

**Comment by shixiedesign** [comment]
Had a meeting with Linda Jeff and James, decided that Wiki is the way to go. 

### The new dependency chart will live in Website repo wiki, new section: 
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/
