### ISSUE TITLE
[Masthead, megamenu] - Click anywhere with Search open will display the Next button or scrolling caret

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#5744]
## Detailed description

Masthead for Web Components has an error on Search (open): on click anywhere it shows the Next button

https://user-images.githubusercontent.com/48327647/114170011-fa371980-993a-11eb-9b61-95f12e447af0.mp4

https://user-images.githubusercontent.com/48327647/114170032-fefbcd80-993a-11eb-9c69-f988ce8be09a.mp4

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Masthead megamenu - Web Components

> What browser are you working in?

Chrome
> What version of Carbon for IBM.com are you using?

Canary

**Comment by RobertaJHahn** [comment]
Fixed in PR (#5790 ).  Closing
