### ISSUE TITLE
[Link list] Vertical variant focus/hit area is longer than link

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5746]
### Current 
Focus box shows extra padding on the right:
![Apr-09-2021 10-59-50.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/de81b31d-9684-461c-b693-e483f6b35aa3)

### Expected 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/fd631a83-22ba-486a-b780-c302cbca0416)

**Comment by JennySanchez** [comment]
@RobertaJHahn This is a dev fix for sure, and the focus box should match the length of the link and icon Shixie is showing above.
