### ISSUE TITLE
[Footer] V2 enhancements design exploration / research

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5749]
#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- [box folder]
- [reference materials]

#### Acceptance Criteria
- [x] Research findings are available in the above Box folder
- [x] Design direction(s) has been identified, reviewed, and approved for the final design phase

**Comment by RobertaJHahn** [comment]
@DragosRistici ST me when you have the links to your design research posted.  I will close both this issue and sprint 21-10.

**Comment by DragosRistici** [comment]
File [uploaded to this Box folder](https://ibm.ent.box.com/folder/137988555914).
