### ISSUE TITLE
[Footer] V2 enhancements design specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5750]
#### Additional Information
- Carbon for ibm.com epic (#5544 )

#### Acceptance Criteria
- [x] A Sketch file is created or updated with the `?component name?` design and specs
- [x] Create a Box folder for the `?component name?` (if not already there)
- [x] The design specs and pdf version are added to the Box folder 
- [x] Add Box folder link to the website content if it exists

**Comment by DragosRistici** [comment]
Updates specs [are in this Box folder](https://ibm.ent.box.com/folder/101562989787?s=nsbccv6jigfw78uwq3r0242qks1x1f87).
