### ISSUE TITLE
[Footer]: Create v2 enhancements functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5752]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `?component name?` functional specs 

> so that I can:
so that I can properly code the `Footer v2 enhancements` that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#TBD )**
 - Design exploration issue (#5749 )
- Design specs issue (#5750 )
 - Development issue (#TBD )
 - Visual Designs & Functional Design Specs Box folder link(TBD)

#### Acceptance criteria
 - [ ] Documented `Footer` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by shixiedesign** [comment]
Looks like for v2 we are not expecting a functionality change. Can this issue be closed? @DragosRistici @photodow

**Comment by photodow** [comment]
That's my understanding, thanks @shixiedesign!
