### ISSUE TITLE
[Video player] image overlay enhancement functional specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5754]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Video player` image overlay functional specs 

> so that I can:
so that I can properly code the `Video player` image overlay enhancement that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5642 )**
 - Web components dev issue (#6193 )
 - React Development issue (#5753 )

#### Acceptance criteria
 - [ ] Documented `Video Player` image overlay functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by RobertaJHahn** [comment]
Closing as the video image enhancement will be managed as a sub-task under the additional focus status epic  (#5514 )

**Comment by photodow** [comment]
Functional specs are updated: https://ibm.box.com/s/y8py6laddi9jslvxbt30kvinkvfwfalp

**Comment by RobertaJHahn** [comment]
Func specs presented in June 14 engineering meeting for sizing.  Can close.
