### ISSUE TITLE
[Masthead] Hybrid Cloud version learning and integration  

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5755]
Placeholder issue for a large project. This would include making the masthead more systematic and pieces more reusable. Current system breakers include: 

- custom logo 
- cloud masthead
- dropdown / mega menu 
- buttons (contact us, login, profile, search)
- locale switcher

More information to come.

**Comment by RobertaJHahn** [comment]
Still waiting for the Cloud designs to settle and collect testing data.  Closing
