### ISSUE TITLE
AEM production L1 navigation - 2nd level entries are abbreviated 

### ISSUE THREAD

**Issue by sbahl1** [carbon-design-system/carbon-for-ibm-dotcom#5758]
Adopter: AEM https://jsw.ibm.com/browse/ADCMS-941
Desired Behavior : the width of the pulldown-menu should be controlled by the longest entry of the L2-Item
Source: https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-masthead--with-l-1
Impacted Live URL: https://wwwpoc.ibm.com/aem-test/edi-electronic-data-interchange

## Update from Shixie May 3: 
- Dropdown width can be increased to **256px** wide. I verified with Anna that we can do a value override on our end to fix.
- Text wrap up to 2 lines for longer labels should still be added to catch future edge cases

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/4438dee7-4a60-4705-97f4-ba63988c7faf)

**Comment by shixiedesign** [comment]
I think this is what he means: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/504e609f-271c-440c-a55b-2bb09ee83d5e)
