### ISSUE TITLE
[CTA block] spacing clean up - DDS consulting

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5779]
#### Overview
Restore original design.  Reference the spec below. Specifically the spacing and grid alignment need to be fixed.

Some spacing adjustments needed: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/1bb6228e-c66c-4616-be2d-cc7e86867007)

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/107b47e6-f62c-44df-b339-8dacff853e65)

----
- Hybrid Cloud developer:   John kaeser
- HC Jira ticket:  https://jsw.ibm.com/browse/HC-2172
- DDS consultant:   Julio Marroquin

**Comment by JennySanchez** [comment]
FYI @RobertaJHahn, I reached out to Shixie as discussed to find out more detail today.

**Comment by proeung** [comment]
JIRA Ticket: https://jsw.ibm.com/browse/HC-2172

**Comment by jkaeser** [comment]
@shixiedesign @NSDrowned Hi there! I have a couple questions about this one:
1. How much space should be between the button group and the content items (https://www.ibm.com/standards/carbon/web-components/?path=/story/components-cta-block--with-content-items) or link list (https://www.ibm.com/standards/carbon/web-components/?path=/story/components-cta-block--with-link-list)?
2. Should the 160px bottom padding always be there, or should it only be applied when there are no content items or link list items beneath the button group? If it's the latter case, how much bottom padding should there be when the content items or link list items are present?

**Comment by shixiedesign** [comment]
Hi! @jkaeser sorry I didn't see this question earlier. Please reference the design specs here: https://ibm.box.com/s/ck4ludd5kj6rgt4uf19btrwor18nsrq4 So based on that PDF, 

1. spacing above Content items is 64px + horizontal rule + 32px: 

![image](https://user-images.githubusercontent.com/15144993/133774157-f09a1d33-20ed-4ad4-83a5-06e4612736ab.png)
 
2. spacing above Link list is 64px only: 

![image](https://user-images.githubusercontent.com/15144993/133774220-73d78125-f4e7-44d3-b98b-848400ffca5a.png)
