### ISSUE TITLE
NextJS page: Masthead Search bar - On hover search icon and close icon are hidden

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5789]
## Detailed description

Issue: 
On Search bar - On hover search icon and close icon are hidden.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/8d451293-1931-485a-8797-1ce6e24e9429)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/223d3ebb-c2f0-4013-9679-86866383ff0b)

**Comment by RobertaJHahn** [comment]
Slack post from Ignacio:  I took a quick look and it seems the carbon-component styles are being loaded later, so they override our previous fixes that were done for the upgrade. It may have to do with chunking, or the styles changes may possibly need to have a more specific selector overall. Not sure if it’s NextJS specific or it may affect other sites.

**Comment by RobertaJHahn** [comment]
reopened because tooltip fix is not included in the merged PR.
