### ISSUE TITLE
[Layout] not on grid

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5793]
## Layout component doesn't seem to be working as expected: 

This is our **Web component** https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-layout--default

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/435e5143-015e-4db8-a4b7-2129a4dea5a4)

And here **React** https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-layout--default

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/758d442d-995b-4a44-921c-66aa2fa877e6)

## Expecting 
- all content to be snapping to grid
- does component need design to provide placeholder content? 
- ideally discuss in huddle

**Comment by RobertaJHahn** [comment]
Design needs to provide storybook placeholder content.  To be scheduled in the design meeting.

**Comment by RobertaJHahn** [comment]
Shixie needs help from engineering to determine whether this is a storybook or a styles package issue.

**Comment by shixiedesign** [comment]
This one slipped through because we forgot to add milestone. I've caught up with Gui and we will move it to next sprint. With storybook demo class discussion done, hopefully this issue is ready to be tackled. At this time, lorem ipsum text blocks are good to use as placeholder content. 
FYI @RobertaJHahn might need airtable

**Comment by shixiedesign** [comment]
Hmm issue still exist. Was there a PR not linked? @guilhermelMoraes
