### ISSUE TITLE
Footer Component Sketch Visual Spec | Background Color Fix 

### ISSUE THREAD

**Issue by sethibm** [carbon-design-system/carbon-for-ibm-dotcom#5806]
## Detailed description

> Describe in detail the issue you're having.

The Footer Sketch component file latest has some of the backgrounds set at #252525, while others are set at #262626 (Gray90), and am pretty sure this is the correct one, looking at Storybook.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Footer 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected all the backgrounds for Gray90 and Gray100 to be Gray90 (#262626), based on at latest Storybook: 

http://ibmdotcom-web-components.mybluemix.net/?path=/story/components-footer--default

## Steps to reproduce the issue

1. Open Footer Sketch visual spec file
https://ibm.ent.box.com/folder/101562989787?s=nsbccv6jigfw78uwq3r0242qks1x1f87
2. Select background for various versions of the footer in the file. Some of them will be #252525, others will be #262626

**Comment by DragosRistici** [comment]
I've checked the file and adjusted the objects with no connection to the library. 
@oliviaflory could you help me with a quick overview? Thank you!
