### ISSUE TITLE
React & Web Components: [Video player] additional states: hover, active and focus Prod QA

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5808]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library `Video player`

> I need to:
have a version of the component that has been tested for accessibility compliance as well as on multiple browsers and platforms 

> so that I can:
be confident that my ibm.com web site users will have a good experience

#### Prototype and specs 

Prototype for hover & active states:
https://www.figma.com/proto/Addj7hJnTCC9R4x66YKK9p/Component-video?node-id=36%3A0&scaling=min-zoom&page-id=0%3A1

| Element   | Default |  Hover | Active |
|----------|-------------|------|-----|
| Play icon circle |  $gray-80 at 90% opacity | $gray-80 at 100% opacity | $gray-80 at 100% opacity | 
| Play icon triangle |  $gray-10  |  $white | $white |
| Poster image | default |  `darken(8%)` on light themes, `lighten(6%)` on dark themes | `darken(16%)` on light themes, `lighten(12%)` on dark themes |

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  Tier 2 browser defects will be created as Sev 3 defects.
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1, 13.3 and 14
- Mobile & Tablet Android versions: 9.0 Pie and 8.1 Oreo 
- Browsers to be tested:  Desktop: Chrome, Firefox, Safari, Edge, Mobile: Chrome, Safari, Samsung Internet, UC Browser, Tablet: Safari, Chrome, Android
- [Accessibility testing guidance](https://pages.github.ibm.com/IBMa/able/Test/verify/)
 - [Accessibility Checklist](https://www.ibm.com/able/guidelines/ci162/accessibility_checklist.html)
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- **See the Epic (#5514 ) for the Design and Functional specs information**
 - Web Components Dev issue (#5805 ) 
- Once development is finished the updated code is available in the [**Web Components Canary Environment**](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/overview-getting-started--page) for testing.
- [**React canary environment**](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/overview-getting-started--page)
- ** [Web Components Wrapper test env URL](https://ibmdotcom-web-components-react.mybluemix.net/?path=/story/*)**

#### Acceptance criteria
- [ ] Accessibility testing is complete.  Component is compliant.
- [ ] All browser versions are tested
- [ ] All operating systems are tested
- [ ] All devices are tested
- [ ] Defects are recorded

**Comment by emyarod** [comment]
@Praveen-sr #5805 has been addressed by #6841 and is ready for QA

**Comment by RobertaJHahn** [comment]
Prod QA testing has started.

**Comment by RobertaJHahn** [comment]
Prod QA and accessibility testing finished.  Closing.
