### ISSUE TITLE
Remove `demo` classes from Storybook to align with Carbon grid

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5813]
### Updated task description

In both Web components and React, the Storybook stories often contain `demo` classes that help with adjusting the position of components. This should be removed, and we will rely on `bx--grid` or Carbon grid to position the component in storybook canvas. 

From Kenny:

> we probably can go into the stories and remove all demo classes. we still have the carbon grid classes in the stories. once the demo classes are gone we can adjust the presentation layouts using carbon grid only

### Some history

Clean storybook's viewport grid layout in Web Components 

Update since huddle April 20: 
### Components should be positioned in Storybook canvas like described here: 
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Storybook-format-standard#3-rendering-in-viewport

From what I understand from [Ian’s comment](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5759#issuecomment-818781282), there's some grid issue within storybook and need to fixed globally: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/5c498b2a-f2ca-46ab-99bf-efacbad851ea)

**Comment by RobertaJHahn** [comment]
To be discussed in the Team Huddle on Tuesday, April 20.

**Comment by RobertaJHahn** [comment]
Comments from the April 20 Team Huddle:  

1. _Shixie will make an issue defining guidance for UI vs Layout components_

Link to the Team Huddle Box Note:  https://ibm.ent.box.com/notes/797086649110

**Comment by shixiedesign** [comment]
Confirmed with dev that we need to address grid alignment in several stories through out storybook. 

- Remove `demo` classes 
- Adjust grid alignment using `bx--grid` only

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/81470013-a452-47f8-b396-45c1948d2753)

**Comment by shixiedesign** [comment]
We have a new issue to track this work with updated info.
