### ISSUE TITLE
[Expressive theme] Contribute guidance to Carbon website

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5823]
Three areas of update needed for Carbon website: 

1. Typography (`$caption-02`, `$helper-text-02`, `$label-02`) 
2. Button (Button — expressive, field size `lg`)
3. List (List lg)

Mike's recommendation: 

> Choose the expressive Button when the environment is expressive. If the component lives on a page where body copy is 16px, or larger, such as in a banner or page lead space, pump up the button label size to match the expressive experience.

**Comment by oliviaflory** [comment]
# WIP.....

## Typography page:

Expressive tab

Supporting styles

| Description | Token |
| --- | ---|
| Missing! This is for labels in components and error messages. | label-01|
| This is for larger labels in components ~that appear within the body of an expressive page~, use as a label when paired with body-short-02 or body-long-02. | label-02 |
|This is for captions or legal content in a layout — not for body copy. | caption-01 | 
| This is for larger captions or legal content in a layout — not for body copy. Use for captions when paired with body-short-02 or body-long-02. | caption-02 |

**Comment by shixiedesign** [comment]
### Started creating PRs to the website:

Part 1/3: Button https://github.com/carbon-design-system/carbon-website/pull/2239
Part 2/3: List https://github.com/carbon-design-system/carbon-website/pull/2240

> WIP. Lots of questions here, but I added the type tokens. Lemme know if I did it right! Feel free to tear it apart or close PR. My feelings won’t be hurt if we have to redo.

Part 3/3: Typography https://github.com/carbon-design-system/carbon-website/pull/2242

**Comment by shixiedesign** [comment]
Item 1 & 2 are done. The only one still in works is "Typography" page: 

Part 3/3: Typography https://github.com/carbon-design-system/carbon-website/pull/2242

Will have to carry it to next sprint. FYI @RobertaJHahn

**Comment by shixiedesign** [comment]
Gonna split out Typography page into a new issue because it's shaping up to be a larger piece of work.
