### ISSUE TITLE
[Lead space with search ] Change the functional specifications based on Dragos' design specifications

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5837]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Lead space with search` functional specs 

> so that I can:
so that I can properly code the `Lead space with search` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5551 )**
 - Design Issues (#5833 ) and (#5679 )
 - Development issue (#TBD )

#### Acceptance criteria
 - [x] Documented `Lead space with search` functional specifications
 - [x] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [x] Additional stories are created, if needed, for any work to be done in future sprints

**Comment by DragosRistici** [comment]
Functional specifications [can be found here](https://ibm.ent.box.com/folder/137098284291).

**Comment by photodow** [comment]
Functional spec updates:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lead-space-search
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lead-space-wrapper
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Search-typeahead
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Masthead-l0
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lead-space
