### ISSUE TITLE
Web component: Dotcom shell Footer - From the second modal, when we activate "Select geographic area" link, the First modal is not displayed. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5847]
## Detailed description

On JAWS FF
Issue:
From the second modal, when we activate "Select geographic area" link, the First modal is not displayed. 
Instead the screen reader focus goes to the parent page.

Expected:
Screen reader should identify the first modal.

**Comment by kennylam** [comment]
@Praveen-sr @RobertaJHahn Issue is fixed in #5964.

**Comment by Praveen-sr** [comment]
@kennylam Re tested this, The original issue is fixed. 
But, now jaws does not identify the dialog role for both the dialogs hence the user would not know that this is a modal dialog.
