### ISSUE TITLE
[Masthead] Search - On empty search bar, clicking enter key, takes the user to results page.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5848]
## Detailed description

Issue:
Masthead: Search - On empty search bar, clicking enter key, takes the user to results page.

## Additional information

![Search_enter.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/3ad3de6e-8840-46a7-a6ef-94844fec3fb7)

**Comment by NSDrowned** [comment]
Hello, @Praveen-sr, can you please retest or provide information on how to replicate it? I tried to replicate but couldn't.

**Comment by Praveen-sr** [comment]
@NSDrowned Re tested above issue on React and web component, working as expected. Thanks!
cc @RobertaJHahn
