### ISSUE TITLE
TypeScript 3.8 breaking change

### ISSUE THREAD

**Issue by whoisbob** [carbon-design-system/carbon-for-ibm-dotcom#5852]
Similar to this issue:
 https://github.com/carbon-design-system/carbon-web-components/issues/328

And I quote (from above):
> With the launch of the TypeScript 3.8 version Microsoft introduced a breaking that affects to the carbon-custom-elements. As we can see in the next image:
<img width="1305" alt="Screen Shot 2021-04-21 at 9 32 02 AM" src="https://user-images.githubusercontent.com/71522536/115562398-70fddc00-a284-11eb-8103-3d49d5a7c46a.png"> (taken from my machine)

> It seems that after 3.8 version the index must contain a strict type and we are using in the addEventListeners and removeEventListeners (from what I could investigate) a K or K_1 type to index.

**Comment by RobertaJHahn** [comment]
Teh scope of this issue is to perform the investigation of the impact and future work.

**Comment by whoisbob** [comment]
We have a client-facing project that needs to align with carbon standards, is there any chance this could be prioritized @RobertaJHahn

**Comment by whoisbob** [comment]
F.Y.I. current version effectively breaks support for angular 10+

**Comment by RobertaJHahn** [comment]
Do you have a time frame...Date needed by?

**Comment by whoisbob** [comment]
We have a MTP next Friday, May 7th. Would it be possible to include this then?  @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Assigned to Raph as part of Fireline support.  More answers needed.

**Comment by jeffchew** [comment]
Just to capture some of the findings, this appears to be the usage of `new CustomEvent` in various components, which has been brought up as an issue here:

https://github.com/Microsoft/TypeScript/issues/28357#issuecomment-818069744

The fix may be going through and creating an interface for these CustomEvents so that Typescript won't be upset about these.

@RaphaelAmadeu @annawen1

**Comment by omkardixit** [comment]
Is there any target date for fixing this issue?
