### ISSUE TITLE
[Card Section Simple] Title section and cards don't align to the 16 column grid

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#5857]
## Detailed description

> It doesn't appear that the Section title and cards are aligning to the 16 column grid

> This appears to be a bug.

> Card section simple component

> I expected the content on the page to align to the 16 column grid. It appears that there is extra padding applied to the content that creates a misalignment with the 16 column grid.

> Seeing the issue in Chrome on a mac.

> Issue is being seen on Storybook. https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-card-section-simple--default

> AEM team.

## Steps to reproduce the issue

1. Go here: https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-card-section-simple--default
2. Initiate carbon chrome plugin to inspect grid and content

## Additional information

- ![image](https://user-images.githubusercontent.com/77290329/115594069-51c27700-a2a3-11eb-89ab-5508c292d672.png)
- For more background or context please reach out to rrastog@us.ibm.com.
**- Engineering task:  Remove the demo class from Storybook.  The Carbon grid class remains.  Adjust the presentation layout using the Carbon grid.**

**Comment by photodow** [comment]
Is this related to #5813?

**Comment by RobertaJHahn** [comment]
Add to the Team Huddle Thursday, 4/29

**Comment by RobertaJHahn** [comment]
@IgnacioBecerra Do you know whether arora-yash is going to finish this work?  Do you have to take this work on the get it finished?

**Comment by IgnacioBecerra** [comment]
Update on this issue, @NSDrowned and I will be taking over the work for this issue as Yash is currently sick and hasn't been able to work on this.

cc: @RobertaJHahn
