### ISSUE TITLE
[Content group horizontal] Web Components:  Rename to "Content block horizontal" 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5869]
The component [Content group horizontal ](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-content-group-horizontal--default) uses `$expressive-heading-05` and therefore should be a Block level component

### Additional information
In general, the levels of hierarchy in component nesting follows the logic below: 

- Section: `$heading-02`
- Block: `$heading-05` 
- Group: `$heading-04`
- Item: `$heading-02`

**- The existing `content group horizontal` component should be renamed to `dds-content-block-horizontal`, by creating a shell component `dds-content-group-horizontal` that extends the content block horizontal functionality with the addition of a deprecation notice if an adopter tries to use `content-group- horizontal`.**

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/93979733-3330-495e-9b06-dbd31055a7b8)

**Comment by RobertaJHahn** [comment]
This is not a small change.  May require a deprecation.  The existing component would be extended including a new class name that is referenced when a user tries to use the old name.

**Comment by shixiedesign** [comment]
Have to re-option because only Web component name change was done. React outstanding. Ideally this get resolved before code freeze so the name change goes out as 1 release. Website's documentation is also affected coz if we change the name there, React users who do not see the name change would get confused.

**Comment by RobertaJHahn** [comment]
Removed Raph from this issue as the work has to be looked at and he is no longer with IBM.
