### ISSUE TITLE
[Content block simple] Style bugs 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5883]
This story splits out the style bugs from the storybook bugs from issue #5527: 

6. Please apply the bottom border by default to every story, every break point and every Carbon theme.
<img width="1123" alt="Screenshot 2021-03-17 at 15 59 01" src="https://user-images.githubusercontent.com/48327647/111522210-b9e0e300-8762-11eb-80da-8388cef31980.png">

7. Apply the `max-width=640px` to the heading, paragraphs, images and videos. Upper limits of `md` and `sm` do not respect the max-width conditions for images and videos, but also the 320px max width for the card:
<img width="1047" alt="Screenshot 2021-03-17 at 20 20 07" src="https://user-images.githubusercontent.com/48327647/111522687-307de080-8763-11eb-8522-a17a0720ff3b.png">
<img width="1072" alt="Screenshot 2021-03-17 at 14 42 46" src="https://user-images.githubusercontent.com/48327647/111522700-34a9fe00-8763-11eb-94ab-678b9bd012d8.png">
<img width="504" alt="Screenshot 2021-03-17 at 15 54 55" src="https://user-images.githubusercontent.com/48327647/111522726-3a074880-8763-11eb-9a07-5e914b41fb3f.png">
<img width="456" alt="Screenshot 2021-03-17 at 14 45 32" src="https://user-images.githubusercontent.com/48327647/111522736-3c69a280-8763-11eb-8e6c-7de3995d933c.png">
<img width="1047" alt="Screenshot 2021-03-17 at 20 20 07" src="https://user-images.githubusercontent.com/48327647/111522775-45f30a80-8763-11eb-9558-f33d72f53265.png">

8. Card does not maintain its ratio on` lg break point`: 
<img width="854" alt="Screenshot 2021-03-17 at 15 12 21" src="https://user-images.githubusercontent.com/48327647/111523265-bef26200-8763-11eb-9351-8a5a6c45858b.png">

9. Link list on `sm break point` do not align correctly the icons:
<img width="505" alt="Screenshot 2021-03-17 at 15 46 45" src="https://user-images.githubusercontent.com/48327647/111523299-cade2400-8763-11eb-91e9-21b2443acfb1.png">

10. Headline in  React, `with aside item` story is bumped to the left 16px. 
![image](https://user-images.githubusercontent.com/15144993/115817176-546abc80-a3c8-11eb-9aa3-8d20ca32181d.png)

**Comment by RobertaJHahn** [comment]
@shixiedesign I assume that you checked with Julio before assigning him to this issue.  It is sitting in the New Issues pipeline, which the engineers do not pull their work from so the work was not finished in sprint 21-08.  I am moving it into sprint 21-09 and moving it into the `To do this sprint` pipeline.

**Comment by NSDrowned** [comment]
Can be closed, solved all issues in #5943 👍
