### ISSUE TITLE
Web component: Masthead - Search by default - On Mobile, search bar does not cover full screen. 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5884]
## Detailed description

Issue:
Masthead - Search by default - On Mobile, search bar does not cover full screen.  Search icon and close icon are not visible to user.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/7ba6c579-28c7-438a-823f-720aa8616cfa)

**Comment by ariellalgilmore** [comment]
This has been fixed ![Screen Shot 2021-04-27 at 10.32.07 AM.png](https://images.zenhubusercontent.com/5ee7ae1cc40147132b286905/e49b1d07-b682-4cf6-83dd-38994ec617ba)

**Comment by Praveen-sr** [comment]
@ariellalgilmore Re tested this on Web component canary, the issue has been fixed. Working as expected now.
cc @RobertaJHahn
