### ISSUE TITLE
[CTA section] Allow offset so 2x2 layout of 4 content items

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5885]
@photodow we should discuss what's the best way to achieve this layout in **CTA block/section**: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/8a4689db-1b50-4560-bbe0-659c027ed0d1)

#### Additional Information
- This is part of the Solution template

**Comment by RobertaJHahn** [comment]
@photodow Are any functional spec updates needed for this FR?

**Comment by RobertaJHahn** [comment]
This work should be scheduled at the same time as (#5406)

**Comment by photodow** [comment]
Yes, functional specs would be needed for this.

**Comment by shixiedesign** [comment]
After discussion, we decided it's best not to allow for so many instances of the CTA section content items. We will allow up to 6, and this issue is requesting for 7 content items situ. Let's push on having more succinct and categorized content within the section.
