### ISSUE TITLE
Carbon for ibm.com Release Plan (v1.30.0-v1.41.0)

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5888]
**v1.30.0**
* Jan 14, 2022: Code freeze
* Jan 17 - Jan 28, 2022: Release Candidate(s) and testing
* **Feb 1, 2022: Full Release**

**v1.31.0**
* Feb 11, 2022: Code freeze
* Feb 14 - Feb 25, 2022: Release Candidate(s) and testing
* **Mar 1, 2022: Full Release**

**v1.32.0**
* Mar 11, 2022: Code freeze
* Mar 14 - Mar 25, 2022: Release Candidate(s) and testing
*  **Mar 29, 2022: Full Release**

**v1.33.0**
* Apr 8, 2022: Code freeze
* Apr 11 - Apr 22, 2022: Release Candidate(s) and testing
*  **Apr 26, 2022: Full Release**

**v1.34.0**
* May 6, 2022: Code freeze
* May 9 - Mar 20, 2022: Release Candidate(s) and testing
*  **May 24, 2022: Full Release**

**v1.35.0**
* May 27, 2022: Code freeze
* June 6 - June 17, 2022: Release Candidate(s) and testing
*  **Jun 21, 2022: Full Release**

**v1.36.0**
* July 1, 2022: Code freeze
* July 4 - July 15, 2022: Release Candidate(s) and testing
*  **July 19, 2022: Full Release**

**v1.37.0**
* Jul 29, 2022: Code freeze
* Aug 1 - Aug 12 , 2022: Release Candidate(s) and testing
*  **Aug 16, 2022: Full Release**

**v1.38.0**
* Aug 26, 2022: Code freeze
* Aug 29 - Sep 9, 2022: Release Candidate(s) and testing
*  **Sep 13, 2022: Full Release**

**v1.39.0**
* Sep 23, 2022: Code freeze
* Sep 26 - Oct 7, 2022: Release Candidate(s) and testing
*  **Oct 11, 2022: Full Release**

**v1.40.0**
* Oct 21, 2022: Code freeze
* Oct 31 - Nov 4, 2022: Release Candidate(s) and testing
*  **Nov 8, 2022: Full Release**

**v1.41.0**
* Nov 18, 2022: Code freeze
* Nov 21 - Dec 2, 2022: Release Candidate(s) and testing
*  **Dec 6, 2022: Full Release**

**Comment by RobertaJHahn** [comment]
No stale.  This issue is used to document the schedule for all of the releases.

**Comment by proeung** [comment]
@ljcarot @jeffchew Is there a release plan for Q2 of 2022? Just wanted to have a sense of when the code freeze and testing period so that we can share the schedule with the team especially on the QA side as we're starting to do more work on that front.

**Comment by ljcarot** [comment]
@proeung I will update this pinned issue to reflect our Q2 release schedule.  We have been adjusting to the new team size here in January and so only projected out as far as end of Q1, but now feel pretty good about our cadence.  fyi: @jeffchew

**Comment by proeung** [comment]
@ljcarot Makes sense and thanks for the update!
