### ISSUE TITLE
[Lead space] Gradient over image not to spec

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5892]
This is a bit tricky, so please talk to design team if any tech limitation exist, or if svg/css gradient is defined differently. Improved gradient will help with accessibility. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/a8837248-e876-4e22-b71d-575d4ba84d8e)

Design spec file: 
https://ibm.box.com/s/mnqx7jzi3vo7ssqaf8oyd3kb8x9mv3p8

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/06cd14d1-4665-4a00-9577-96ffc9e1de73)

#### Need design review 
Please tag @DragosRistici to review lead space to-spec-ness ~

**Comment by photodow** [comment]
This might actually be a feature request apart of #5347 instead of a bug.

**Comment by DragosRistici** [comment]
The ui-background is from the opposite theme. All the other elements are from the white theme. If you need Gray 100 background, then you should go with the Gray 100 lead space.

**Comment by shixiedesign** [comment]
This issue is still present in **Lead space centered.**

**Comment by shixiedesign** [comment]
Never mind I will just open a new issue
