### ISSUE TITLE
Background image in leadspace centered 

### ISSUE THREAD

**Issue by sarovisk** [carbon-design-system/carbon-for-ibm-dotcom#5897]
## Detailed description
The Web Builder, who works with me, has reported that he is facing an issue with the centered leadspace on mobile version. The images don't change in each breakpoint.

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
> issue? It's a bug.

> Is this issue related to a specific component? yes, leadspace centered

> What did you expect to happen? What happened instead? What would you like to
> see changed? The background image should change on each breakpoint. Currently, the main background image is displayed in all breakpoints.

> What browser are you working in? Google Chrome

> What version of Carbon for IBM.com are you using? "carbon-web-components": "^1.7.1",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of? Partner Ecosystem

## Additional information

- Preview page: https://partnerworld-landing.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/45/isv-partner-program/index.html

**Comment by RobertaJHahn** [comment]
This component will be refactored to include the image component.  Support from design is needed.  Shixie and Dragos will provide the design support needed.  Dragos is primary contact

**Comment by kennylam** [comment]
@sarovisk I believe this is due to a fixed height being set on `dds-leadspace`.

![image](https://user-images.githubusercontent.com/909118/119613458-13046d00-bdcb-11eb-8a9a-44c2069e1900.png)

**Comment by gtonussi** [comment]
Hello @sarovisk @kennylam That fixed height was deleted from scss and is not present anymore. You only find it on that preview link as it is an older version. We used because the buttons of leadspace were being cut on certain resolutions, but it is not the case anymore. If that was the cause of the issue, then it should be fine by now. Thanks!
