### ISSUE TITLE
[Lead space - super] extend to include tags  design specs

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5900]
- ~Slot to accommodate a child (Ratings / Price)~ (no longer in Product page template MVE) 
- Breadcrumb / tag expressive  #5927

**Comment by DragosRistici** [comment]
Done. [The specs are in the same Box](https://ibm.ent.box.com/folder/94761007991?s=d9jey3rlfxqmxu059f0x9dtcx7f5ehuh) folder.
