### ISSUE TITLE
[Table of Contents – Horizontal]: TOC doesn't push masthead out of view when scrolling the page.

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#5902]
## Detailed description

> Describe in detail the issue you're having.
**The TOC – Horizontal page navigation should push the masthead out of view as the user scrolls down the page. It currently is not doing that.**

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
**Bug**

> Is this issue related to a specific component?
**TOC – Horizontal**

> What did you expect to happen? What happened instead? What would you like to
> see changed?
**I expected the masthead not to stick to the top of the page when the TOC – Horizontal component is being used.**

> What browser are you working in?
**Chrome**

> What version of Carbon for IBM.com are you using?
**I believe the most recent version. v1.18.1?**

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
**AEM / Afterburner**

## Steps to reproduce the issue

1. Go here to view: https://dev-author.np-roks.cms.cis.ibm.net/content/adobe-cms/us/en/qa/april-19/solutionpage.html?wcmmode=disabled#anchor-1344866353
2. Please reach out to @iwhitcomb for further details.

## Additional information
<img width="1313" alt="Pasted_Image_4_26_21__2_26_PM" src="https://user-images.githubusercontent.com/77290329/116132271-5e780e00-a69b-11eb-872b-da1281b3261a.png">

**Comment by RobertaJHahn** [comment]
Raph will reach out to Ian for more details as part of Fireline.  We think this bug was fixed.

**Comment by RobertaJHahn** [comment]
Gi reached out to Ian.  He mentioned that an AEM update is coming that will possibly fix the problem.  Gui will keep in touch to help, if needed.
