### ISSUE TITLE
[Content block card static] Naming and functional spec

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5912]
New component
## Pricing block

Using [Pricing card] (temp name) and content item to create a block with up to 2 CTAs (Button group) 

### Draft visual design reference

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/411717f2-d80c-44e5-a51c-06e9bbd03be3)

**Comment by photodow** [comment]
>
> ###### Card group `enhancement`  
> — enable static card option
> — look for tags using same height utility
> <br /><br />

 <br />

> ###### Tag expressive `new`  
> — Should this be apart of carbon's new expressive work?
> <br /><br />

 <br />

> ###### Content item `enhancement`  
> — enable button group type from CTA
> <br /><br />

 <br />
 
 > ###### Content block cards `enhancement`  
 > — Add optional content item
> 
> <br />
>
> *--- or ---*
> <br />
>
> ###### New component `new`  
> — Content block
> — Card group
> — Content item
> <br /><br />

**Comment by RobertaJHahn** [comment]
Content block - pricing name changed to Content block card static

**Comment by RobertaJHahn** [comment]
No functional specs needed.  Experimental component
