### ISSUE TITLE
Provide hook in Masthead search to make search field permanently opened

### ISSUE THREAD

**Issue by aiproulx** [carbon-design-system/carbon-for-ibm-dotcom#5925]
Defined application requirement to have the search field permanently opened in certain context / properties.
Provide hook to enabled a persistant open search field, with focus off.

### The problem
In Documentation context, a persistently open search in the masthead scope to a specific property is a HIGH priority requirement.

### The solution
Provide the hook for consumer of the masthead search component to support critical requitement.

### Additional information
I do not agree that “it would have to be the company wide strategy and carried out on the entire IBM.”
https://support.google.com/docs/answer/3300615?hl=en&ref_topic=9052528
https://docs.aws.amazon.com
https://docs.aws.amazon.com/s3/?id=docs_gateway
https://docs.microsoft.com/en-us/azure/api-management/quickstart-arm-template

The implication of adding a function in the component to be opened and not in focus is not huge.
There is a context and need for the persistent open state. Besides ibmcom/search team, who have built their own, I would like to know who else (which other teams) needs or have requested a persistent opened state.

**Comment by ljcarot** [comment]
@aiproulx We spoke to global masthead search team about this request.  Their recommendation is to conduct user testing and gather metrics that support the suggestion will be an improvement.  They are willing to work with you to explain how to establish the test and evaluate the metrics.  Reach out to Steve Atkin and Dave McDuff for more details.  We'll put this request on Icebox for now.  cc @RobertaJHahn @shixiedesign

**Comment by RobertaJHahn** [comment]
We will not implement on this request.  User testing should inform this change.  A design for the entire masthead has to be considered. Masthead is a shared property and all parties have to be considered.

Dave McDuff's recommendation was 1)  to add another search to their page.  2)  Masthead search should search all of IBM on the page.  

KC has analysis of competitor sites.  Those sites do not have the same user strategy as IBM.  

KC would like the same local search in the MH that they had in their previous KC experience.  The new version of the KC site with the Carbon implementation is Docs.

**Comment by RobertaJHahn** [comment]
No longer needed.
