### ISSUE TITLE
[Lead space - super] Add super, add tags, fix tall - AEM Product template

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5928]
This epic contains functional and design links that define the scope of the deliverable. This epic also includes links to all of the work required to deliver the component.

This component is designed by DDS, supporting the AEM use cases.  Once complete, the available Lead space sizes will be:  super, tall (default), medium, short, 

----
#### Additional Info
- Design and func specs box folder:  https://ibm.ent.box.com/folder/94761007991?s=d9jey3rlfxqmxu059f0x9dtcx7f5ehuh

**Comment by photodow** [comment]
Do we have a functional spec issue for this yet?
