### ISSUE TITLE
[Tabs extended] AEM requested enhancement to allow 2 line text wrap - Product template

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5931]
This epic contains functional and design links that define the scope of the deliverable. This epic also includes links to all of the work required to deliver the component.

----
Designer:  Stephanie Homan

**Design specs Box link:  (https://ibm.box.com/s/biz4gdl54v7lv5bpz5tbflfw19hd8go7)**

**Comment by photodow** [comment]
Here are the PDF design specs from Stephanie. We still need the sketch file and archive the older specs. I gave it an alpha tag so to distinguish between the others for now.

https://ibm.box.com/s/biz4gdl54v7lv5bpz5tbflfw19hd8go7
