### ISSUE TITLE
[Tabs extended] Change the functional specifications to include the enhancement to allow 2 line text wrap

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5933]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Tabs extended` functional specs 

> so that I can:
so that I can properly code the `Tabs extended` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5931 )**
 - These designs are created by Stephanie Homan from AEM
 - Development issue (#TBD )

#### Acceptance criteria
 - [ ] Documented `?component name?` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by photodow** [comment]
Designers mentioned tooltip is added when an overflow happens. Need to determine if this is going to be possible or not.

**Comment by photodow** [comment]
No tooltip. `title` should ~default~ be enabled if the adopter chooses with the tabs today.

**Comment by photodow** [comment]
Functional specs updated here to allow 2 line overflow. Just a not to double check and make sure `title=""` is allowed to be passed in as-is allowed with the Carbon tabs component.

https://ibm.box.com/s/isxvoxtzczxgrjbrhw7cbiej4zisq585
