### ISSUE TITLE
[CTA section] Update the functional specs to allow offset so 2x2 layout of 4 content items

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5937]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `CTA section` updated functional specs 

> so that I can:
so that I can properly code the `CTA section` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5885 )**
 - Development issue (#TBD )

#### Acceptance criteria
 - [ ] Documented `CTA section` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by RobertaJHahn** [comment]
@photodow You moved this issue to the Done pipeline, but I don't see updates / links to the functional specs.

**Comment by photodow** [comment]
Sorry, @RobertaJHahn you caught me in the middle of moving things over. As of right now, I don't think we should update any functional specs for this. Here is what I shared with the designers last week.

> Looking over some of this L shaped card group, offsetting card group, and 2x2 layout of four content items orphan logic issues. In particular that last item right now. Card group, and the content items we’re talking about includes multiple column layouts like 2, 3, 4 as an example. Each column increases the complexity of adding this orphan card or orphan content item logic. With the addition of the L-shape we need to bring in the offsetting in card group. With that comes different logic for not only each column, but for each placement of that offset and how many are offset. With that said I still have some major reservations by adding this type of logic to our components. If we add the offset ability the adopter can implement this type of logic themselves as needed given a specific context. But anyway that’s some of my concerns and thoughts.
> 
![image](https://user-images.githubusercontent.com/3793636/121051411-0b57a780-c77f-11eb-921a-986fc228c202.png)

**Comment by shixiedesign** [comment]
After discussion, we decided it's best not to allow for so many instances of the CTA section content items. We will allow up to 6, and this issue is requesting for 7 content items situ. Let's push on having more succinct and categorized content within the section.
