### ISSUE TITLE
[Web Components | Integration Tests] Fixes to the Integration Build tests

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5941]
## Detailed description

> Describe in detail the issue you're having.

The Web Components integration build tests were disabled as they abruptly stopped working:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5936

This bug is to track the reason why it stopped working, and if there is a way to adjust the tests to work.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Web Components integration build tests with the footer

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Tests to pass

## Steps to reproduce the issue

1. Run `yarn test:integration:build` in the `web-components` package folder
2. Note, it may help to disable the server breakdown so that the local browser can be viewed after the temporary instance is deployed at http://localhost:9000

## Additional information

- The component itself does not seem to be rendering when viewed locally:

![image](https://user-images.githubusercontent.com/1641214/116752807-1840e880-a9d4-11eb-98be-bd2d4d614d1e.png)

- Puppeteer version is severely out of date. I tried updating to latest version (v9 at the time) but ran into the same issues.

**Comment by jeffchew** [comment]
Removed designers from this issue. @RobertaJHahn we can look through this perhaps in the next refinement meeting.

**Comment by RobertaJHahn** [comment]
These tests have been turned off.  Low severity.  Jeff will add to the engineering huddle when there is time.

**Comment by RobertaJHahn** [comment]
Closing.  Work in progress under another story.
