### ISSUE TITLE
[NextJS test] Reduce scroll animation

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5946]
Design is putting together a direction on how to use scroll animation. Once done, we need to update NextJS templates to be less scroll woozy.

**Comment by RobertaJHahn** [comment]
Potentially schedule in Sprint 11.  Animation is assigned to sprint 10.  This issue can be taken up after the animation work is finished.

**Comment by RobertaJHahn** [comment]
Closing dup of (#
