### ISSUE TITLE
Web component: Design - Masthead, menu option blocking IBM logo.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5949]
## Detailed description

Issue:
Web components Masthead with custom-navigation, one of the menu option blocking IBM logo.

## Additional information

![Masthead_menu.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/5b84fb1a-9df7-4eb6-8c78-ce53743546a7)

## Solution

Design team reviewed on May 6 in Design Huddle, decided to follow the Design specs and [React](https://ibmdotcom-react.mybluemix.net/?path=/story/components-masthead--with-custom-navigation) example where menu can open when partially hidden and will remain behind the IBM logo (or overflow buttons, Search, login).
**This will apply to all variations of the masthead, not _only_ With custom-navigation**

<img width="895" alt="Screen Shot 2021-05-10 at 9 16 41 AM" src="https://user-images.githubusercontent.com/45692622/117665108-7f972f00-b170-11eb-9889-8bf3f8ff80ea.png">

**Comment by RobertaJHahn** [comment]
will be added to the May 6 design huddle.

**Comment by oliviaflory** [comment]
@RobertaJHahn I updated the issue to show the desired solution from the review with design.
