### ISSUE TITLE
[Content block mixed] padding issues between intro paragraph and content groups

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#5953]
## Detailed description

> Describe in detail the issue you're having.

There are inconsistencies in spacing between the design spec and Storybook implementation of the Content block mixed component. The design spec says that spacing between the intro paragraph and the content groups should be 64px, but on Storybook it is 96px.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

This is a bug.

> Is this issue related to a specific component?

Content block mixed

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected the spacing between the intro paragraph and content groups to be 64px.

> What browser are you working in?

Chrome

> What version of Carbon for IBM.com are you using?

This is on [Storybook web components](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-content-block-mixed--default).

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

AEM

## Additional information

- [Jira 1167](https://jsw.ibm.com/browse/ADCMS-1167)

**Current result**
![image-2021-05-04-10-52-47-520](https://user-images.githubusercontent.com/77290329/117025364-da400f00-acc8-11eb-914e-dae2c7b83e31.png)

**Expected Result**
![ADCMS-1167](https://user-images.githubusercontent.com/77290329/117025387-dd3aff80-acc8-11eb-9883-9491fc8f3a89.jpg)

**Comment by RobertaJHahn** [comment]
@kirbyevans It looks like this was fixed in the latest release.  Code freeze was Friday, May 7.  Can you check here:  https://ibmdotcom-web-components-staging.mybluemix.net/?path=/story/components-content-block-mixed--default

**Comment by shixiedesign** [comment]
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/5fb0f9db-625d-49f0-a43e-a292ba66bb9c)
