### ISSUE TITLE
[Masthead L1]: L1 Megamenu position is off when user first scrolls page and then opens L1 megamenu

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#5954]
## Detailed description

> Describe in detail the issue you're having.

When scrolling the page and then opening the L1 megamenu, the megamenu top position is off, creating a gap between the menu item and megamenu

## Steps to reproduce the issue

1. go react storybook, DotcomShell component with L1
2. scroll page
3. open menu item with megamenu on the L1

## Additional information

<img width="1461" alt="Screen Shot 2021-05-04 at 12 27 00 PM" src="https://user-images.githubusercontent.com/54281166/117039517-dca96580-acd6-11eb-8889-0ba90866b68a.png">

**Comment by RobertaJHahn** [comment]
@annawen1 We shouldn't be using the mega menu data for the L1.  This isn't a bug, engineering should stop pointing to the L0 data file.  Reach out to @oliviaflory for more details, if needed.
