### ISSUE TITLE
[Site Feedback] needs new design specs.

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/carbon-for-ibm-dotcom#5955]
Site Feedback team informed us that with the Think banner pushing the content on the page down, it is causing a problem with Site Feedback display.

### The problem
When we display the Think banner and a page has L1 navigation, it obscures the button label.

### The solution
[Site Feedback] need new designs that show lower placement of the button (272 px from top) and smaller font size (12px).  The team can implement the design in their codebase.

### Additional information
Contact: Jo Welsh

**Comment by ljcarot** [comment]
@oliviaflory @DragosRistici @JennySanchez FYI opened this per our slack discussion on May 4.

**Comment by shixiedesign** [comment]
### Design spec 
https://ibm.box.com/s/8ao2ohehntsitp95qkv8ey889nk71a9n

The style of the button appears to be tertiary button but current implementation is not showing the correct hover state. I spec'ed it as Tertiary button to avoid creating misalignment on the theoretical level. If Jo's team is interested in updating, it could be a good thing to align better with Carbon. FYI @ljcarot 


![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/dc506614-1ac2-461b-b9b7-92d1c039b390)
