### ISSUE TITLE
[Content block card static]: Development of new AEM Product template component behind a feature flag

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5961]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `Content block card static`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic for the Design and Functional specs information**
- Feature flag documentation: https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/packages/react/docs/feature-flags.md
- Card - static, dev issue (#5962 ) must be finished before this component development can begin.  
 - Web Components limited Prod QA testing issue (#6056 )
- DDS sizing 5 story points

----
Hybrid Cloud developer:  Dennis Dolliver
DDS Dev consulting:  Ignacio

#### Acceptance criteria
- [ ] Build behind a feature flag
- [ ] Include README for the web component and corresponding styles
- [ ] Add any necessary stable selectors
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] A comment is posted in the Prod QA issue, tagging Praveen, when development is finished

**Comment by proeung** [comment]
@RobertaJHahn @kirbyevans Can you provide a link to the design and technical specs of this new "Content Block Card Static" layout component? Thanks!

**Comment by RobertaJHahn** [comment]
@proeung There are no functional specs on this component as it will be developed behind a feature flag.  Here is the design info:

Designer:  Kerby Evans

**Design specs Box link:** https://ibm.box.com/s/bu6ksttoozynfkvpm3mogzov0t8hdzsy

**Comment by proeung** [comment]
@RobertaJHahn Thanks!

Here's a direct link to the JIRA ticket (https://jsw.ibm.com/browse/HC-1936) that we're using on our side to track the work. This particular ticket is currently assigned to Dennis Dolliver.
