### ISSUE TITLE
[Card group - default] Research whether - light variant - no URL

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5975]
#### User Story

> As a `[user role below]`:
DDS engineer

> I need to:
investigate whether the current Web Components and React [Card group - default] components support a light variant and passing of no URL to create a static version of the Cards

> so that I can:
help determine whether additional work is needed to support the AEM Product template

#### Additional information

 - _{{user research}}_
 - _{{user insights}}_
 - _{{user metrics}}_

#### Acceptance criteria
 - [ ] Investigation summary by the EOD Friday, May 7 posted to Slack and this issue.

**Comment by photodow** [comment]
Functional specs don't really have anything that should block this from happening.

Light and "static or default" context can be found on Carbon's tile page. 

![May-06-2021 08-10-32](https://user-images.githubusercontent.com/3793636/117303817-be607880-ae42-11eb-9002-76c23761486d.gif)

We might need to enable some sort of optional border, so functional specs will be needed at the very least for that.

**Comment by ariellalgilmore** [comment]
**React**
- allows for no URL (CTA arrow icon will always appear though)
- light variant not possible, but should be easy fix
- no border option

**Web component**
- does not allow URL (if remove URL it looks completely broken)
- light variant not possible
- no border option
