### ISSUE TITLE
[404 page] Create new design

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5976]
### Compulsory fun design task: redesign IBM 404 page
Current: https://www.ibm.com/404

## Design brief 

- A friendly message could be written that includes these words: `404`, `Page not found`
- Provide pathways forward, eg. Search & Popular links
- Demonstrate IBM brand philosophy https://www.ibm.com/design/language/philosophy/principles
- Consider this error page an opportunity to show IBM's best side 

## Additional info 

Past issues description from Wonil: 

#### User story
As a user of IBM.com, I need to be informed of an HTTP error and understand what the next steps are.  The error pages were implemented on v18.  This work is needed for Carbon.  

#### Next Steps
- Research
- Design exploration
- Design
- Review & approval
- Development
 
#### Examples:
https://www.ibm.com/common/errorpages/300.html
https://www.ibm.com/common/errorpages/303.html
https://www.ibm.com/common/errorpages/305.html
https://www.ibm.com/common/errorpages/307.html
https://www.ibm.com/common/errorpages/400.html
https://www.ibm.com/common/errorpages/401.html
https://www.ibm.com/common/errorpages/402.html
https://www.ibm.com/common/errorpages/403.html
https://www.ibm.com/common/errorpages/404.html
https://www.ibm.com/common/errorpages/405.html
https://www.ibm.com/common/errorpages/406.html
https://www.ibm.com/common/errorpages/407.html
https://www.ibm.com/common/errorpages/408.html
https://www.ibm.com/common/errorpages/409.html
https://www.ibm.com/common/errorpages/410.html
https://www.ibm.com/common/errorpages/411.html
https://www.ibm.com/common/errorpages/412.html
https://www.ibm.com/common/errorpages/413.html
https://www.ibm.com/common/errorpages/414.html
https://www.ibm.com/common/errorpages/415.html
https://www.ibm.com/common/errorpages/416.html
https://www.ibm.com/common/errorpages/417.html
https://www.ibm.com/common/errorpages/500.html
https://www.ibm.com/common/errorpages/501.html
https://www.ibm.com/common/errorpages/502.html
https://www.ibm.com/common/errorpages/503.html
https://www.ibm.com/common/errorpages/504.html
https://www.ibm.com/common/errorpages/505.html

**Comment by DragosRistici** [comment]
The wip file is here in [this Box folder](https://ibm.box.com/s/47cq4r0p0idbli5ojk1usgrtjh41kbpz). Will add another 2 story points issue to finish the work.

**Comment by DragosRistici** [comment]
Continuation is here: #7709
