### ISSUE TITLE
[Filter panel] Design support of the a/b testing by the ibm.com search team

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5977]
#### User Story

> As a `[user role below]`:
DDS designer

> I need to:
provide a/b testing consulting support to the ibm.com Search team

> so that I can:
have the metrics to refine / improve the filter panel designs

#### Additional information

 - ibm.com Search Offering Manager:  Dave McDuff
 

#### Acceptance criteria
 - [x] Meet with the ibm.com Search squad, as needed
 - [ ] _{{State another}}_
 - [ ] _{{And another}}_

**Comment by oliviaflory** [comment]
Kickoff meeting scheduled for Wednesday 5/12 with the Search team.

**Comment by oliviaflory** [comment]
### Update from Search team:
- JC should be working on a code or javascript that will load on the B version the filters you designed.  He should deliver that by the end of this month.
- Jeannie from our squad to write a user-story. Can you please write me a description for this AB test - A vs. B version, plus a hypothesis we want to test?
- Proposed keeping A/B test simple, with the least amount of changes
   - Removing the gray background container
   - Keeping the Products & Solutions home button (we would allow this in the custom header area)
   - Could you please send me updated Sketch file, with the white background color and chevrons?
- Have two KPIs:
   - Overall page engagement A vs. B
   - Clicks on the subcategories A vs. B


### Example of filter panel accordion interaction: 
- https://w3.ibm.com/design/spark-design-festival/schedule
- https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/21.0.x?topic=overview-what-is-cloud-pak-business-automation
- https://ibm-security.carbondesignsystem.com/?path=/story/patterns-filterpanel--default

### Hypothesis:


### Olivia needs to follow up with:
- [ ] Send Martin a version of the file with no gray background & accordions
- [ ] Send martin the hypothesis for the A/B test

**Comment by oliviaflory** [comment]
### Hypothesis:
Collapsing the filters into accordions will 
- help users with screen readers to get into to the main content and/or search results faster
- help users focus on the main content if categories are collapse
- allowing IBMers the flexibility to configure which categories are collapsed, expanded by default, and how many filters are shown will allow for a better user experience, tailored to user needs.

**Comment by RobertaJHahn** [comment]
Designs reviewed with DDS engineers in May 24 Issues refinement meeting.
