### ISSUE TITLE
[Account page] Create new design 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5978]
Current URL: https://www.ibm.com/account/us-en/

### What's the Account page for? 

> from Linda:

- when someone logs out, this page is where they land.  It was a solution a few years ago due to issues where logging out in context, didn't reliably bring people to the page they were on before logging in. Could think of something perhaps more elegant for what happens with log out.
- its not a high traffic page but there's one per locale

## Design brief

In need a minimal lift & shift for now so that we can began the build in Carbon.

**Comment by RobertaJHahn** [comment]
Shixie will track down:
1)  the translated pages
2) Google Analytics for other entry points to the us-en page.

**Comment by shixiedesign** [comment]
1) Only designing the us-en page for now
2) Found some more data: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/75cdab14-78ca-476b-a80c-d1a63876bce6)

A few interesting callouts. Generally we wanna decrease bounce rate, because that means people didn't engage with the page. Though given the intention of the page (a catch all for logouts), bounce rate is probably always gonna be on the higher side. We can potentially improve content on page to provide more helpful links to increase engagement. **Definition of bounce rate**

**Comment by DragosRistici** [comment]
Slight IA and visual update. Page is viewed by logged-in, logged-out but also by users with no IBM account.
Page uplift proposal [can be found here](https://ibm.ent.box.com/folder/140167960332).
