### ISSUE TITLE
[Card in card] Card heading wrong type size, is it not using Card component? - DDS Consulting

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5984]
Card heading should be `$expressive-heading-03` which is 24px on max breakpoint, and 20px on lg. This highlights an issue - is Card in card not using Card component as a dependency? 

**Currently,** heading in Card in card is too small 
http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-card-group--with-card-in-card

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/29a7bac1-6331-40fc-bc95-1fa02de3c2a1)

**Expecting Card in card to use Card component** 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/a0d19683-0a21-4157-b2f6-c49aa1a3c938)

----
HC Developer:  Putra Bonaccorsi
[HC Jira Ticket](https://jsw.ibm.com/browse/HC-2131)
Dev sizing:  1
DDS Engineer:

**Comment by ariellalgilmore** [comment]
@shixiedesign is this still an issue? [Uploading... Screen Shot 2021-06-28 at 2.54.33 PM.png]

**Comment by shixiedesign** [comment]
@ariellalgilmore yes it is. The issue is only visible when screen width is >= 1584px. 
This issue is brought up by Sandeep [here](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/6817). @RobertaJHahn @jeffchew can we swap this ticket out for a lower priority bug for a sooner sprint?

**Comment by proeung** [comment]
@RobertaJHahn Here's the link to the JIRA ticket (https://jsw.ibm.com/browse/HC-2131) that we're tracking on our board.

HC Engineer Assignee: @proeung
