### ISSUE TITLE
Continue [Masthead] Clean up design spec, add Cloud menu designs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5985]
### Clean up 

- Clean up design specs to represent the latest decisions
- Archive the old... 

### Cloud alignment

- Leaving the 16px & 14px untouched 
- Identify any new component needed by Cloud masthead

I hope at the end of this cleanup, we will have an understanding on the number & type of components masthead has today, and would potentially need for future. We'd like to target the future components that already exist in Cloud masthead to be absorbed eventually, so Cloud masthead can be taken out of experimental and live harmoniously with dotcom masthead. 

----
This work is a continuation of the work managed under issue (#5708)

#### Acceptance criteria
- [ ] Once analysis is finished, create the issues needed for future alignment

**Comment by oliviaflory** [comment]
@shixiedesign maybe we could review together early next week, or if you have time to look alone and lmk if you see anything glaring.

**Comment by oliviaflory** [comment]
Reviewed questions about L1 behavior with Shixie, Lila and James 5/25

Decisions: 
- L1 ecosystem name / topic should be visible on medium & small breakpoints
- Keep options for selected state of ecosystem name on medium & small breakpoints
- within the hamburger menu, the ecosystem name will only be visible on the first level of navigation.
