### ISSUE TITLE
[Card group - default] Create designs for how the outline will be shown on the cards within a card group

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5989]
#### User story
> As a `[user role below]`:
DDS Designer

> I need to:
change the `Card group - default` design specs

> so that I can:
provide the DDS engineers with the correct designs for the AEM Product template use cases

#### Additional Information
- Carbon for ibm.com epic (#5988 )
- Include a 1 px border around the cards within a card group, including between the cards.
- These designs will be presented in the Monday, May 10, DDS engineering issues refinement meeting

#### Acceptance Criteria
- [x] A Sketch file is created or updated with the `Card group - default` design and specs
- [x] Create a Box folder for the `Card group - default` (if not already there)
- [x] The design specs and pdf version are added to the Box folder 
- [x] Add Box folder link to the website content if it exists

**Comment by DragosRistici** [comment]
Updated the card group files. [Find the specs and the pdf file](https://ibm.ent.box.com/folder/111654108347?s=r4nt1w1fe2gnuqn6m9gac48tll7jq5pl) in the Box folder.
