### ISSUE TITLE
[Card group - default] Change the functional specs to include an optional card border when in a group

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5991]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Card group - default` functional specs 

> so that I can:
so that I can properly code the `Card group - default` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5988 )**
 - Design Issue (#5989 )
- A 1 px border is added to the card

#### Acceptance criteria
 - [x] Documented `Card group - default` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by photodow** [comment]
Functional specs are done for this. https://ibm.box.com/s/rpki0q23o6wyrtvx22je74tbfx1xkcsn
