### ISSUE TITLE
[Tag group] Create the Tag group design specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5994]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the `Tag group` design specs

> so that I can:
correctly create the `Tag group` component 

#### Additional Information
- Carbon for ibm.com epic (#5987 )

#### Acceptance Criteria
- [ ] A Sketch file is created or updated with the `Tag group` design and specs
- [ ] Create a Box folder for the `?component name?` (if not already there)
- [ ] The design specs and pdf version are added to the Box folder 
- [ ] Add Box folder link to the website content if it exists

**Comment by shixiedesign** [comment]
Done! :tada: 
https://ibm.box.com/s/t2njzzny00mgy67cxj0r420nacvpvc83

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/7fdcc604-64d2-45dc-8353-422a7cccfff8)
