### ISSUE TITLE
[Tag group] Create the Tag group functional specs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5995]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Tag group` functional specs 

> so that I can:
so that I can properly code the `Tag group` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5987 )**
 - Design Issue (#5994 )
- [Tag group design specs](https://ibm.box.com/s/t2njzzny00mgy67cxj0r420nacvpvc83)

#### Acceptance criteria
 - [x] Documented `Tag group` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by shixiedesign** [comment]
Done! :tada: https://ibm.box.com/s/t2njzzny00mgy67cxj0r420nacvpvc83

**Comment by RobertaJHahn** [comment]
Designs and func specs reviewed in May 10 engineering refinement meeting. Sized.
