### ISSUE TITLE
[Content item] Change functional specs to allow button group as a CTA style

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5998]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Content item` functional specs 

> so that I can:
so that I can properly code the `Content item` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#5968 )**

#### Acceptance criteria
 - [ ] Documented `Content item` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by shixiedesign** [comment]
The prophetic Photodow has done the task already! Moved to done. 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/7c1204ae-7aba-4398-bee8-d76dec2545db)

**Comment by photodow** [comment]
Thanks @shixiedesign, just going to add the link here: https://ibm.box.com/s/xfm17x7dwbe4z7kjk482b8hbpjasft7o
