### ISSUE TITLE
Automated roadmap

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#6003]
### The problem
Release communications issue isn't automated

### The solution

New automation pipeline that will auto generate our communications issues with changelog since the latest stable tag.
Add a comment block to the issue that the pipeline will look for, maybe search by specific label in github.  The purpose is to provide headlights to the adopters of what may be coming down the road.

The content should be based on Zenhub data.  Filtering by the release and labels (TBD).  Presentation and Location (TBD)

**Comment by RobertaJHahn** [comment]
Add to the 5/24 Engineering issues refinement.
