### ISSUE TITLE
[Windows machine]: unable to install and test locally 

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#6009]
## Detailed description

> Describe in detail the issue you're having.

Currently running `yarn install` at the root folder in windows gives an error installing the `telemetry` package. A workaround is commenting out this line https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/406837b96bdb749d4b3a50ea59fd1b07da1abd20/packages/react/package.json#L34 

When then trying to run `yarn storybook` this error now appears: 
![image](https://user-images.githubusercontent.com/20210594/117676272-3dff8780-b162-11eb-8cf8-eae73a921f81.png)

This is blocking window users from being able to contribute to our library.

**Comment by RobertaJHahn** [comment]
Raph will reach out to Ari.  Can run WSL on Windows to address this.
