### ISSUE TITLE
[Expressive theme page] Write notification about deprecation 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6014]
We need to write a short warning message for adopters before the actual deprecation start. This warning message would be delivered vi: 
- added to various pages on the Website
- posted in Slack #carbon-for-ibm-dotcom

Suggestion from James
> could say it's transitioning to carbon core instead of deprecating

**Comment by shixiedesign** [comment]
Draft: https://ibm.box.com/s/n0hm7big5ema7ng4ok2m63cl1efyu94j

**Comment by JennySanchez** [comment]
@shixiedesign If this task is for the website, let's move it over to the website repo.
