### ISSUE TITLE
[card, cardgroup] enable border to allow gradient and offset items

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#6016]
Follow onto #5962 and #5993 

### The problem
Need the ability to add border gradient applied to card group cards in between cards, beginning in one corner to the other corner without breaking or starting over. Also needs to skip over blank/empty/offset columns.

- border images don't work great because we need them in the grid gutter between cards.
- things like box shadows don't allow you to add gradients properly.
- needs to be applied to the card group as a whole so it has a consistent beginning to end flow.
- needs to also be applied to a single card for certain situations.

### Possible solution
- See the prototype for how I approached it. There maybe a better way, but at least this will kind of demonstrate what we're looking for.
- Empty cards for offsetting
- Border using padding on card
- linear background applied to the card, and card group depending on the effect we're going for.
- Gutters in-between two offsets shouldn't exist both horizontally, and vertically
- Empty items don't have borders

![image](https://user-images.githubusercontent.com/3793636/117724295-2ac3da80-b1a9-11eb-8239-6098b20c5b4b.png)

### Additional information
 - See a prototype exploring some of the different approaches. https://codepen.io/photodow/full/MWpYKmL

**Comment by RobertaJHahn** [comment]
@ariellalgilmore Can you take a look at this work and decide what the sizing would be.  Would like to know if this work can be done by the code freeze June 25.
