### ISSUE TITLE
React: Footer - inconsistent country list and display

### ISSUE THREAD

**Issue by flatcoding** [carbon-design-system/carbon-for-ibm-dotcom#6021]
## Detailed description

> Using the react footer (with the next.js template), the country list display is not consistent between different locales. I.e., if I am on de-de, the list shows Belgium / Luxemburg for English and French, on at-de it only shows Belgium / Luxemburg English.
Also, on DE, the German language is displayed as 'Deutsche' (which I think is wrong), while on AT all county names are in English and it's displayed as 'German (Deutsch)'. I 

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Footer

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The list of locales should be consistent across locales. Within countries of the same language, the way how the country names are displayed should be consistent (always English, or always local language).
Ideally, be-fr should be supported in all lists.

> What browser are you working in?
FF / Chrome (latest version)

> What version of Carbon for IBM.com are you using?
1.13 (but confirmed with a local build of 1.18.1)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Storage Digital Platform

## Steps to reproduce the issue

1. https://www.ibm.com/it-infrastructure/storage/flash/offers/de-de & https://www.ibm.com/it-infrastructure/storage/flash/offers/at-de
2. Scroll down to footer, click country selector, EMEA
3. Notice difference in country list display.

## Additional information
![be_fr_AT_20210511](https://user-images.githubusercontent.com/47025385/117792559-ac6c4480-b24b-11eb-957c-93156906e6e0.png)
![be_fr_DE_20210511](https://user-images.githubusercontent.com/47025385/117792560-ad04db00-b24b-11eb-9513-c35e36df4b5f.png)

**Comment by flatcoding** [comment]
You can also contact me via erik.reder@de.ibm.com if any question.

**Comment by kennylam** [comment]
Hi @flatcoding! Yes we're aware of the inconsistencies and all supported locale translation files are currently being updated.

**Comment by flatcoding** [comment]
Thx for the quick reply, @kennylam 
An additional question - do you have a list of all supported locales? Do you think that be-fr will be supported in the updated version?

**Comment by RobertaJHahn** [comment]
Linda meeting with the translation team May 18 to discuss
