### ISSUE TITLE
[Nextjs & HTML templates] Need a designed comp 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6028]
Our templates could use some tidying up. Currently these are the demo pages, and serves to test our components put together. Need design comps & animation recommendation for: 

https://ibmdotcom-nextjs-staging.mybluemix.net/
https://ibmdotcom-web-components-html-staging.mybluemix.net/

### Acceptance criteria

- [x] Need 2 pages comp in Sketch + PDF (both frameworks will demo the same pages) 
- [x] 1 page should demo horizontal ToC; 1 page should demo vertical ToC
- [x] Using components in the library to construct a cohesive page
- [x] Critical components to include: Masthead, footer, lead space, card group, carousel, CTA section
- [x] Try to demo as many components as possible, but doesn't have to be all

**Comment by shixiedesign** [comment]
A few references: 

Dotcom shell 
https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-dotcom-shell--default

Past designs from Dotcom Reboot:

**Comment by RichKummer** [comment]
Recommending _Slide up_ as the animation for the demo pages. This one is one of the most common scroll animations on the web and would fit most designs for IBM.com.

**Comment by RichKummer** [comment]
**Invision prototype:** https://ibm.invisionapp.com/share/3BO1BITMC64#/320020357_NextJS-Light-Max

**Box link to current PDFs:** https://ibm.box.com/s/zi99u74f5ugwn6mok1zr4sojretuui8o
