### ISSUE TITLE
IBM url image without s in https link

### ISSUE THREAD

**Issue by MatiasDifabioIBM** [carbon-design-system/carbon-for-ibm-dotcom#6031]
The url in IBM logo in masthead don't have the s of the https://
is this something you can fix?

thanks a lot!

**Comment by MatiasDifabioIBM** [comment]
Hi, I am sorry but I am still seeing the URL without the "s".
Maybe is a cache issue, do you know when is going to reflect?
please see the image attached,
thanks
![Screen Shot 2021-05-12 at 09 58 45](https://user-images.githubusercontent.com/84032789/117979043-e18a9c80-b308-11eb-8eea-f0c2b0c4fc9b.png)

**Comment by ljcarot** [comment]
Our next release is May 19 when this fix will be live.
