### ISSUE TITLE
[Filter panel] New component Visual QA of web component version

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6035]
#### User Story

> As a `[user role below]`:
DDS Designer and Developer

> I need to:
test the `Filter panel`

> so that I can:
be sure the developer's code correctly works as designed

#### Additional Information
- **See the Epic for the Design and Functional specs information**
- Designer will be added as a reviewer to the Pull Request.  Visual QA reviewer will be notified by Github when review is needed.
- [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- This issue includes visual QA for both the Web Components and React Wrapper component versions
- Web Components Dev Issue (#6034 )
- Storybook link provided by engineer in comments below

 #### Tasks
Ensure the `Filter panel` component has been tested and reviewed by design + dev.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] Comments are posted to the Pull Request.  Review is iterative until final approval to merge the code is provided in the PR.
- [ ] New issues are opened to log individual defects for any bugs that can not be addressed in the PR
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed

**Comment by oliviaflory** [comment]
@RobertaJHahn FYI we only covered Web Components, React wrapper version has not been completed by engineering yet.

**Comment by RobertaJHahn** [comment]
@oliviaflory I have created separate issues for all of the React Wrapper work.  This work will be scheduled in a future sprint.  The React Wrapper visual QA issue (#6645 ).  Moving this Web Components visual QA to Done.

**Comment by oliviaflory** [comment]
Thank you @RobertaJHahn 👍
