### ISSUE TITLE
[Logo grid] Storybook cleanup 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6040]
## Logo grid storybook example can be improved. 
- Should be on grid! 
- Remove CTA from example. It is an optional CTA but should not be in default
- Ideally, instead of images we use logos. [Here's a folder of logos ](https://ibm.box.com/s/c51wajohvdl92q0ywhhy2t5yuglj18ne)

### Current screenshot with expected position of logo images in pink:
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/efe6b570-af11-4585-b190-3efebb9bb2d3)

**Comment by DragosRistici** [comment]
@shixiedesign what do you think, should we update the spacing below the heading here, too, or not? From 64 to 32?

**Comment by shixiedesign** [comment]
Good point @DragosRistici ... spec is not up to date, lemme update to 32px for now.
