### ISSUE TITLE
[Lead space] Video & play-pause controls

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6054]
Many pages on IBM.com includes short video or animation in the lead space. We have been asked to add this as a feature to our current lead space. We need to access priority and design to stay compliant with accessibility requirements. 

- Video / animation: any guardrails? subtle animation only, no audio. 
- Add play / pause button 

Please note, this should be an enhancement to **Background media** https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-background-media--default

Current IBM US homepage https://www.ibm.com/us-en?ar=1  

![May-12-2021 12-54-27.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/2cd2b1b1-09ff-4f4a-898a-4f2aabc4d3f5)

#### Additional Information
- [Lead space left aligned visual specs](https://ibm.ent.box.com/folder/94761007991?s=d9jey3rlfxqmxu059f0x9dtcx7f5ehuh). 
- [Lead space functional specs](https://ibm.ent.box.com/folder/94761007991?s=d9jey3rlfxqmxu059f0x9dtcx7f5ehuh). 
- [Background media visual specs](https://ibm.ent.box.com/folder/137924469929?s=t2y4gne6754xuf3popy9vfhr9rhupm0v). 
- [Background media functional specs](https://ibm.ent.box.com/folder/137924469929?s=t2y4gne6754xuf3popy9vfhr9rhupm0v).

**Comment by RobertaJHahn** [comment]
issues needed:  func specs, dev and QA issues

**Comment by shixiedesign** [comment]
Lead space video

### Video duration limit, allow to pause on desired end frame

Irina
Can we have a range? Stopping the video within a range. Like 10 seconds would be enough. 

Michael Baryla 
Pause button is a bit weird. The video is gonna stop after 5 seconds, then the pause button renders? 

Irena 
We actually have a person on the team very sensitive to flashing. Using some post control is good for someone like that. 

Rafael 
If you have auto play and looping, we need pause button

Sometimes when working on videos, we sometimes encounter sometimes the sound will play even if you set HTML to mute. 

I like the circled icon better than the squared one, will check if we can implement that on ours, looks so much better


### A more visible play/pause button

Irina / Rafael 
Add outline? 

### Require / recommend a back up still

A safe measure is to always make sure to have placeholder image in case something is wrong with the video. 

### Mobile

Michael Baryla: sometimes in advertising we use an image slide show / some motion helps to attract interaction with the lead space.

# Types of video behavior  

1. Autoplay, loop, pause button. Required file has to have no audio. Any interaction with the page will pause video.

2. Autoplay, stop after 5 seconds, no pause button. Required file has to have no audio. Any interaction with the page will pause video.

3. No autoplay, big play button. Play in Lightbox.

**Comment by DragosRistici** [comment]
Options for the play button to be tested.
