### ISSUE TITLE
[Content block card static] Web Components:  New AEM Product template component limited scope Prod QA testing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6056]
#### User Story

> As a `[user role below]`:
developer using the ibm.com Library ?component name?

> I need to:
have an early version of the pattern or component that has been tested for Tier 1 browsers and platforms

> so that I can:
use the pattern on an ibm.com web page or in a cms template to gather design metrics to validate or change the existing design

#### Additional information

- [Browser Stack link](https://ibm.ent.box.com/notes/578734426612)
- [Browser Standard](https://w3.ibm.com/standards/web/browser/) 
- Browser versions to be tested:  Tier 1 browsers will be tested with defects created as Sev 1 or Sev 2.  
- Platforms to be tested, by priority:  1)  Desktop  2)  Mobile  3)  Tablet
- Mobile & Tablet iOS versions: 13.1, 13.3 and 14
- Browsers to be tested:  **Desktop:** Chrome, Firefox, Safari, Edge, **Mobile:** Chrome and Safari  **Tablet:** Chrome and Safari
- [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- **See the Epic for the Design specs information.  Functional specs are not created for patterns behind a feature flag**
- DDS Dev consulting issue (#5961 ) 
- A react version of this component will not be created at this time.
- ** If Web Components, once development is finished, the updated code is available in the [Experimental environment](https://ibmdotcom-web-components-experimental.mybluemix.net/?path=/story/overview-getting-started--page) for testing.**

#### Acceptance criteria
- [ ] All Tier 1 browser versions are tested
- [ ] All Tier 1 operating systems are tested
- [ ] All Tier 1 devices are tested
- [ ] Defects are recorded

**Comment by IgnacioBecerra** [comment]
@Praveen-sr Component is ready for review! 

https://ibmdotcom-web-components-experimental.mybluemix.net/?path=/story/components-content-block-card-static--default

**Comment by RobertaJHahn** [comment]
Prod QA testing finished.  No issues found.
