### ISSUE TITLE
Web component: Dotcom shell - Locale modal- After giving the search input and activation of clear search input button the dialog is getting closed

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6078]
## Detailed description

On JAWS FF
Issue:
After giving the search input and activation of clear search input button
the dialog is getting closed, and the focus comes back to to the Select geographic button in the parent page.
Note: in react staging it is working fine

Expected behavior :  is after activation of clear search input button, the focus should set back to the search edit field.

**Comment by annawen1** [comment]
PR was opened in carbon-web-components repository.
