### ISSUE TITLE
Carbon for ibm.com Patch Release Plan (v1.19.1)

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6084]
- **May 11, 2021**: Release Branch Created
- **May 12 - 21, 2021**: Release Candidate(s) and testing
- **May 24**: Full Patch Release

### Fixes
- **custom-events**
  - onloadend type defined (#6158)

### Housekeeping
- **settings**
  - update settings to v1.19.1

**Comment by jeffchew** [comment]
Release created: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/releases/tag/v1.19.1
