### ISSUE TITLE
[Link list] CTA type - Video is broken

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6086]
When Link list's CTA type is set to `Video`, the styling is wrong. Currently showing heading-03, or card title style, but it should be still the link style: 

### Current 
Web components: https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-link-list--default
![May-13-2021 14-29-16.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/5c17fb09-dfc4-4cf9-99b6-b9ad620602a4)

React: https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-link-list--default
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/1c4ccdf4-03c1-43a6-85ed-8b507cef6d40)

### Expecting

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/1ffac59b-a98a-4052-b4fb-81dff2246ae4)

**Comment by RobertaJHahn** [comment]
The linked PR is for React only.  Another PR is needed for the Web Components fix.
