### ISSUE TITLE
[Expressive theme | model button label] Alignment off when button label wraps to 2 lines

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6098]
When model button's label are long and wraps to 2 lines, the button set should grow taller to maintain internal padding: 

Current:
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/9325f571-8ea1-4f0a-b7ea-bf3bf0686b5e)

Expecting: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/d01edcd3-9b9a-41b6-b910-6191ae794c39)

**Comment by jeffchew** [comment]
Closing this, since we are sunsetting the expressive theme.
