### ISSUE TITLE
[Expressive theme | Pagination] Disabled button styling wrong

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6099]
Original is correct on the left side. Disabled button should show svg color as `$disabled-03` 

![May-14-2021 15-26-48.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/f9ef63b8-58ea-4f34-9053-824ee750003a)

**Comment by jeffchew** [comment]
Closing this since we are sunsetting the expressive theme.
