### ISSUE TITLE
[Web Components | Masthead] Have menus be lazy loaded for performance reasons

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#6100]
#### User Story

> As a `[user role below]`:
IBM.com application developer

> I need to:
only load the necessary Masthead elements on page load

> so that I can:
improve page speed performance in my IBM.com application

#### Additional information

 - One of the items mentioned from Google Lighthouse / Pagespeed insights is that there are too many dom elements loaded on the page, which can impact performance.
 - This issue should determine if this will improve page performance

#### Acceptance criteria
 - [ ] Determine if lazy loading the menu elements will improve the page performance
 - [ ] Implement if this will improve performance

**Comment by RobertaJHahn** [comment]
Closing, did not have impact on the performance
