### ISSUE TITLE
[Content item horizontal - with thumbnail] New variation for the the Content item horizontal

### ISSUE THREAD

**Issue by pavolprok** [carbon-design-system/carbon-for-ibm-dotcom#6110]
### The problem
We are currently missing a Content item horizontal component variation with small thumbnail images. We only have the variation with media where the image is too dominant. 

### The solution
I have prepared (together with Lila Title and also with guidance from Shixie) design specs for this new variation with a 4:3 thumbnail image that aligns to the right and takes up 100% of the last 3 columns with max. width of 256px.
https://ibm.box.com/s/bvpjhnwwpsi8uo51s1993v5ywbpakxcf

This variation is currently being used on the Learn ecosystem prototype. 

![image](https://user-images.githubusercontent.com/70329414/118513102-a8509300-b733-11eb-97cc-4ccf8b7b5880.png)

### Additional information

Design specs:

https://ibm.ent.box.com/s/bvpjhnwwpsi8uo51s1993v5ywbpakxcf

Functional specs:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-item-horizontal

![content-item-horizontal--thumbnail](https://user-images.githubusercontent.com/3793636/121090652-85535500-c7ae-11eb-8bb8-4b329b9897cb.gif)

----
This component will be developed by a Hybrid Cloud engineer.  

- Corresponding Jira issue:  https://jsw.ibm.com/browse/HC-1969

**Comment by RobertaJHahn** [comment]
AEM will develop this component behind a feature flag and contribute it.  Design specs are finished.  

The topic of maintaining the DDS experimental components to the May 18 Team Huddle.

**Comment by RobertaJHahn** [comment]
Met with Lily, Lila and Sandeep.  They asked whether James can create the functional specs for this component.  AEM will still develop it.

**Comment by RobertaJHahn** [comment]
Will be developed as a component in the Carbon for ibm.com Library:  Needs epic, func specs, DDS dev consulting, (AEM developer), Visual QA (AEM designer), Prod QA

**Comment by proeung** [comment]
@RobertaJHahn Here's the JIRA ticket for this component that we're (HC) tracking on our end - https://jsw.ibm.com/browse/HC-1969.

**Comment by RobertaJHahn** [comment]
Epics do not belong in the Review pipeline.  Moved back to the Prioritized epics pipeline.
