### ISSUE TITLE
[Leadspace] type='left' is not working properly

### ISSUE THREAD

**Issue by sarovisk** [carbon-design-system/carbon-for-ibm-dotcom#6112]
## Detailed description
- Adopter:  Partnerworld

> The leadspaces on ibm.com/partners, ibm.com/partners/build and ibm.com/partners/start aren't rendering. The problem seems to be only happening with leadspace type=‘left’ and type='right'. When the ‘centered’ is used, for example, it works normally.

> Is this a feature request (new component, new icon), a bug, or a general
> issue? It's a bug.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/24360999/118540244-cb287a80-b726-11eb-9706-3acc564a76a8.png)

![image](https://user-images.githubusercontent.com/24360999/118540284-d54a7900-b726-11eb-8746-39b40fcf1e5f.png)

![image](https://user-images.githubusercontent.com/24360999/118540330-e0050e00-b726-11eb-9845-6c39534d0115.png)

- Notes

**Comment by annawen1** [comment]
Hi @sarovisk, can I know what version of @carbon/ibmdotcom-web-components you guys are using? We are starting to phase out the `left` and `small` type attributes. We do have the `size` attribute if that is something that would help. You can go here and checkout the `Docs` tab up top for code implementation examples: https://ibmdotcom-web-components-staging.mybluemix.net/?path=/docs/components-lead-space--tall-with-no-image


CC: @andysherman2121 @DragosRistici

**Comment by annawen1** [comment]
Could you also share more of the code? The screenshot doesn't show the entire implementation of the leadspace

**Comment by sarovisk** [comment]
Hi @annawen1! I'm asking @amanda-ibm for help. She is the developer and she may have much more information than me. 😃

**Comment by annawen1** [comment]
oh great! I actually got the link to the partners pages github repo and dug around. It looks like the change in the leadspace height in the custom scss file caused the leadspace to not show up.

<img width="1169" alt="Screen Shot 2021-05-17 at 5 07 52 PM" src="https://user-images.githubusercontent.com/54281166/118557271-f31ddb00-b732-11eb-8eca-63b63366644f.png">

Upgrading to our latest @carbon/ibmdotcom-web-components version (currently the latest is v1.3.1) also solves the issue. We've had some fixes to the leadspace recently so I would highly recommend to upgrade. You may run into issues with imports when upgrading but I believe adding this should resolve that issue. Please let me know if this helps!

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-test/blob/master/config/webpack.config-helper.js#L163-L166

**Comment by sarovisk** [comment]
Good, thanks, Anna! :)

**Comment by RobertaJHahn** [comment]
@sarovisk  @amanda-ibm  Please follow Anna's advise.  We are closing this issue.
