### ISSUE TITLE
[Expressive theme] Support Carbon designers to add expressive type styles to Carbon sketch kits

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6114]
We have **agreement on May 17 from Anna Lauren and Jeannie** that it's no problem to add Expressive type set to Carbon sketch kit. There might be some support work. The plan is to try simply copy+pasting from Carbon Expressive first. If doesn't work, rebuild might be needed.

**Comment by oliviaflory** [comment]
Created the issue to [add expressive type styles](https://github.com/carbon-design-system/carbon-design-kit/issues/437) to the Carbon kits on the design kit repo. Anna said over slack they would review in their next sprint planning meeting.

**Comment by oliviaflory** [comment]
Carbon team has finished adding all the type styles to the Carbon design kits, in all the themes. 

Now we just wait for the release of the design kit before we can tell our adopters to transition.
