### ISSUE TITLE
[Content group horizontal]: Rename to Content block horizontal, reduce spacing between header and Content item to 32px

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#6119]
### Info added during Triage meeting: 
Original issue for renaming: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5869
Header spacing change was probably missed because this is not named Content Block blah. So should loop in. 

## Detailed description

> Describe in detail the issue you're having.
**Spacing between the Section header and the first Content item within the Content block horizontal component isn't the same. Storybook is using 96px padding and the Design specs have the spacing documented as 32px.**
 
> Is this a feature request (new component, new icon), a bug, or a general
> issue?
**Maybe a general issue?**

> Is this issue related to a specific component?
**Yes, the Content block horizontal component.**

> What did you expect to happen? What happened instead? What would you like to
> see changed?
**I expect the spacing to be consistent between Storybook and the Design specs.**

> What browser are you working in?
**Chrome**

> What version of Carbon for IBM.com are you using?
**N/A**

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
**AEM**

## Steps to reproduce the issue

1. Screenshots and links to the spec file and Storybook are below.

## Additional information

**[Storybook](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-content-group-horizontal--default)**

![image](https://user-images.githubusercontent.com/77290329/118657093-299e3900-b7b9-11eb-9f69-203351bfc173.png)

**[Design specs](https://ibm.box.com/s/m9p9xfb8m33h6lhglwhccbnwph9npjzq)**

<img width="1446" alt="Pasted_Image_5_18_21__9_14_AM" src="https://user-images.githubusercontent.com/77290329/118657438-7b46c380-b7b9-11eb-89d7-61cc6c35a5dc.png">

**Comment by NSDrowned** [comment]
This one can be closed now. All issues fixed in PRs #6494 and #6666 👍 

@RobertaJHahn
