### ISSUE TITLE
Issue with leadspace component [all types]

### ISSUE THREAD

**Issue by amanda-mendes-1998** [carbon-design-system/carbon-for-ibm-dotcom#6120]
# Detailed description
> This [issue](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6112) was opened and marked as resolved but another issue is happening.
 ## As recommended, I’ve removed all the custom css related to the leadspace and updated but then this happened:
![image](https://user-images.githubusercontent.com/80002122/118694615-a1348e00-b7e2-11eb-8304-f709de4b36c4.png)
## If the custom CSS is active, the layout renders normally but the copy font gets like this:
![image](https://user-images.githubusercontent.com/80002122/118694844-e658c000-b7e2-11eb-9c43-01522da27c46.png)

> I've noticed that actually the "gradient" layer z-index is higher that the copy so it renders over the text.

## Also, once updated, the leadspace centered type that was working properly before updating is now completely bugged
![image](https://user-images.githubusercontent.com/80002122/118694910-fcff1700-b7e2-11eb-9756-2c4a921e3175.png)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
bug
> Is this issue related to a specific component?
Yes, the leadspace - with image
> What browser are you working in?
Chrome and firefox
> What version of Carbon for IBM.com are you using?
1.19.0
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
The leadspaces are not rendering live, we need this fix complete with urgency

## Steps to reproduce the issue

1. Open the page and you'll se the leadspace isn't rendering
2. Update library
3. add the leadspace component (enable/disable custom CSS on leadspace to test)

**Comment by annawen1** [comment]
Hi @amanda-mendes-1998, could you possibly open a draft PR with what you're reporting in the partnerworld repo? We can then us that PR to investigate why the styles are off.

**Comment by RobertaJHahn** [comment]
Andy will follow-up for more details.

**Comment by annawen1** [comment]
This issue was resolved with the upgrade to the latest version. Closing this ticket
