### ISSUE TITLE
[card section offset] used on the Learn ecosystem a.k.a. Content block with L-shaped card group

### ISSUE THREAD

**Issue by pavolprok** [carbon-design-system/carbon-for-ibm-dotcom#6129]
### The problem
We are currently missing a component where the card group in L-shape can be used on top of a background image as part of the main topic that is represented by the Content Block component on the left side.

### The solution

I have prepared design specs for this new component that we are using on the Learn ecosystem prototype.
There are 4 dependencies:
1. Card
2. Card group
3. Content block simple
4. Image component

![image](https://user-images.githubusercontent.com/70329414/118792490-fda5b500-b897-11eb-9ccf-2fefe420c617.png)

### Additional information

Learn ecosystem:

https://xd.adobe.com/view/f260b7b3-e460-4e78-ab17-75237a7968c4-a733/screen/9aad39f9-bf0d-4752-afa4-8bd72ae5ae38?fullscreen&hints=off

Design specs:
To find under: Content block cards
https://ibm.box.com/s/9pweudf9ptucx8jxzgo3e2m5jpyke5qi

Functional specs:
`enhancement` Offset cards in card group:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-group

![card-section-offset--card-group](https://user-images.githubusercontent.com/3793636/121088163-f133be80-c7aa-11eb-8d42-d16dde542bf7.gif)

`new` Background media component:  
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Background-media

![card-section-offset--background-media](https://user-images.githubusercontent.com/3793636/121088143-e8db8380-c7aa-11eb-8779-b14e69866af8.gif)

`new` Card section offset:  
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-section-offset

![card-section-offset--card-section-offset](https://user-images.githubusercontent.com/3793636/121088198-fc86ea00-c7aa-11eb-9916-3ef2daad7ef9.gif)

----
This component will be developed by a Hybrid Cloud engineer.

- Corresponding Jira issue:  https://jsw.ibm.com/browse/HC-1970

**Comment by RobertaJHahn** [comment]
AEM will develop this component behind feature flag and contribute it.  

Met with Lily, Lila and Sandeep today.  They asked whether James can create the functional specs.

**Comment by RobertaJHahn** [comment]
Will be developed as a component in the Carbon for ibm.com Library:  Needs epic, naming & func specs, DDS dev consulting, (AEM developer), Visual QA (AEM designer), Prod QA

**Comment by proeung** [comment]
@RobertaJHahn Here's the JIRA ticket for this component that we're (HC) tracking on our end - https://jsw.ibm.com/browse/HC-1970.

**Comment by RobertaJHahn** [comment]
Closing, All linked issues are closed.
