### ISSUE TITLE
[Research] Create a demo of KeystoneJS

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#6134]
#### User Story

> As a `[user role below]`:
Carbon for IBM.com team member

> I need to:
understand how a headless CMS solution would work

> so that I can:
determine if using a light CMS solution would be a better path for the Carbon for IBM.com website

#### Additional information

- Scope of this work is to create a demo.  Does not have to hooked up to anything Carbon.  Purpose is to explain how Keystone works to the rest of the team members.
 - Keystone website: https://www.keystonejs.com/
 - Ideally can spin up a quick demo that can tie into the web components app or NextJS template, but a "hello world" demo may also work
 - Sign up for team huddle to demo once ready

#### Acceptance criteria
 - [ ] Create keystone test application
 - [ ] Hook up keystone APIs to a test application
 - [ ] Create demo to highlight how authoring and publishing would work
 - [ ] Sign up for team huddle

**Comment by RobertaJHahn** [comment]
discussing whether we decide to move to AEM.
