### ISSUE TITLE
[Content block with L-shaped card group] Assign name & create functional specs - AEM Learn ecosystem

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6147]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Content block with L-shaped card group` functional specs 

> so that I can:
so that I can properly code the `Content block with L-shaped card group` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#6129 )**
 - This component is designed by AEM.  Pavol Prok is the designer

#### Acceptance criteria
- [ ] New component name is selected, documented and communicated 
- [ ] Documented `Content block with L-shaped card group` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by photodow** [comment]
`enhancement` Offset cards in card group:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-group

`new` Background media component:  
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Background-media

`new` Card section offset:  
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-section-offset
