### ISSUE TITLE
[Content item horizontal - with thumbnail] Create the functional specs for this new variant

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6148]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Content item horizontal - with thumbnail` functional specs 

> so that I can:
so that I can properly code the `Content item horizontal - with thumbnail` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#6110 )**
 - This component is designed by AEM.  Pavol Prok is the designer.

#### Acceptance criteria
 - [ ] Documented `Content item horizontal - with thumbnail` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by photodow** [comment]
Here is the link for the functional specs: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-item-horizontal
