### ISSUE TITLE
[Feature section] Create functional specs for new AEM component used in the Services landing page

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6149]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Feature section` functional specs 

> so that I can:
so that I can properly code the `Feature section` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#6118 )**
 - This components is designed by AEM.  The designer is Saijan Kuruvila

#### Acceptance criteria
 - [ ] Documented `Feature section` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by RobertaJHahn** [comment]
Reviewed in the June 7 meeting with AEM engineers and DDS engineers.

**Comment by photodow** [comment]
`new` Feature section:  
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Feature-section

`enhanchement` Feature card added option to flip content and image:  
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Feature-card


`enhanchement` Added card link option to differenciate from Card style. See #5740:  
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/CTA
