### ISSUE TITLE
[Leadspace - Medium]: Leadspace is rendering extra padding

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#6153]
## Detailed description

> Describe in detail the issue you're having.

The leadspace in particular the medium variation with the image is rendering with extra padding below the image. This is evident when the leadspace is in the g100 dark theme.

> What version of Carbon for IBM.com are you using?

web-components v1.4.0

## Additional information
```
<dds-leadspace size='medium' alt="Image text" default-src="../assets/images/leadspace-sample-2.jpg">
      <dds-leadspace-heading>Lead space title</dds-leadspace-heading>
      <dds-image slot="image" class="bx--image" alt="Alt image text" default-src="../assets/images/leadspace-sample-2.jpg">
      </dds-image>
</dds-leadspace>
```

<img width="1626" alt="Screen Shot 2021-05-21 at 2 47 31 PM" src="https://user-images.githubusercontent.com/54281166/119184883-f3281e80-ba43-11eb-8fc9-6c18e5ea7815.png">

**Comment by annawen1** [comment]
Removing the `padding-top` in the leadspace-section class could help, but need to check out leadspace variations
<img width="1470" alt="Screen Shot 2021-05-21 at 2 54 36 PM" src="https://user-images.githubusercontent.com/54281166/119185257-91b47f80-ba44-11eb-8e90-e7815fb6819e.png">

**Comment by shixiedesign** [comment]
Is this why we are getting a big gap under Horizontal ToC? https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-dotcom-shell--with-horizontal-toc
