### ISSUE TITLE
Include Breadcrumbs component in Lead space component as new variation

### ISSUE THREAD

**Issue by pavolprok** [carbon-design-system/carbon-for-ibm-dotcom#6160]
### The problem
Right now the Carbon for IBM.com doesn't have Breadcrumb component available, but we would need it for the Learn ecosystem. 

https://xd.adobe.com/view/f260b7b3-e460-4e78-ab17-75237a7968c4-a733/?fullscreen&hints=off

### The solution
Using the existing Breadcrumb component from the Productive theme: https://www.carbondesignsystem.com/components/breadcrumb/usage/

### Additional information
 Dragos Ristici did already explorations of this component while working on the updates to the LS component.
- Learn ecosystem

**Comment by RobertaJHahn** [comment]
Next steps:  Convert to an epic, Designs complete, func specs needed, then engineering issues needed with sizing, Visual QA, Prod QA and Website update

**Comment by shixiedesign** [comment]
Design spec already exist: https://ibm.box.com/s/mnqx7jzi3vo7ssqaf8oyd3kb8x9mv3p8

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/0e03c071-c213-4fb0-82b3-e306de2306bb)

**Comment by shixiedesign** [comment]
Catching a fast train to development! We will only need an additional issue for functional spec. I think this doesn't have to be an epic any more.

**Comment by shixiedesign** [comment]
I gave a rough estimate of 2 @ariellalgilmore feel free to change

**Comment by RobertaJHahn** [comment]
@shixiedesign I have linked this issue to the Lead space - super epic as this feature will be included in the June release with that component.
