### ISSUE TITLE
Web component: Dotcom shell - On Mobile, Table of contents scrolls down with the page

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6172]
## Detailed description

Issue:
On Mobile, When the user scrolls the page down and up, Table of contents also scrolls down with the page.

## Additional information

![TOC_dotcom.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/88911685-613d-4c2b-8670-99a02834b0ee)

----
HC Developer: John Kaeser
[HC Jira Ticket](https://jsw.ibm.com/browse/HC-2129)
Sizing:  3
DDS Consultant:  Gui

**Comment by guilhermelMoraes** [comment]
@Praveen-sr would you please test it again? I'm trying to reproduce it but it's not happening. Tested locally, on staging and canary.

**Comment by Praveen-sr** [comment]
@guilhermelMoraes Re tested this on Web component canary, i was able to reproduce the issue on iPhone 11 with iOS 14.

https://images.zenhubusercontent.com/193129061/80910348-4b92-4e65-a50d-f3b06b766367/image_from_ios.mp4

Note: Scrolls the page down and up multiple times,  we can see the issue.

**Comment by proeung** [comment]
@RobertaJHahn Here's the link to the JIRA ticket (https://jsw.ibm.com/browse/HC-2129) that we're tracking on our board.

HC Engineer Assignee: @jkaeser
