### ISSUE TITLE
Web component: Masthead - focus on the search bar should be removed when open by default

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6173]
## Detailed description

Issue:
Masthead - On opening search edit bar, Default Focus on the search edit bar should be removed.

## Additional information

https://images.zenhubusercontent.com/193129061/ad3285be-99cc-44e4-85d4-c83f4a32561d/rpreplay_final1621852603.mp4

**Comment by ariellalgilmore** [comment]
This has been fixed and should be working in canary: http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-masthead--default

**Comment by RobertaJHahn** [comment]
Closing based on Ari's comments above.

**Comment by Praveen-sr** [comment]
@ariellalgilmore Another issues related to focus position on search edit bar :- 
On Mobile, when bar is opened initially there is a delay in focus position set to left of search edit field.
