### ISSUE TITLE
[Closed]: incorrect/accidental issue creation

### ISSUE THREAD

**Issue by kariukiandy** [carbon-design-system/carbon-for-ibm-dotcom#6175]
### The problem
_{{A clear and concise description of what the problem this new feature is trying to solve. (ex. I'm always frustrated when...)}}_

### The solution
_{{A clear and concise description of what you want to happen}}_

### Additional information
 _{{Please provide any additional information or resources for reference}}_
 - _{{user research}}_
 - _{{user insights}}_
 - _{{user metrics}}_

**Comment by kennylam** [comment]
Closing due to insufficient information, as well as potentially sensitive information in the issue.

@kariukiandy Please re-open this issue if you still need assistance and make sure to follow the template in listing out your problems. Thanks!
