### ISSUE TITLE
[Lead space] Expand background to full screen width

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6177]
### Need to allow Lead space's background to be covering screen width based on section's theme, not page theme. 

Current lead space in inverse theme still render white background left-and-right of the image. This area should be in inverse theme as well. See current experience on [AEM learn template](https://www.ibm.com/topics/edi-electronic-data-interchange). 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/9a67a03e-ec4b-4084-ac1b-0ca0f9dc5a95)

Design specs: https://ibm.box.com/s/d9jey3rlfxqmxu059f0x9dtcx7f5ehuh

### Details

Additional details. Previous strategy is "Global" components get the full screen width background, which are so far Masthead and Footer. I've had several sources complaining about the result. Lead space without theme'ed background extending full width looks incomplete. **This bad visual experience gets worse when Horizontal table of content is below.** 

Some users of DDS lead space with modified background: 
- US home page https://www.ibm.com/us-en?ar=1
- PartnerWorld https://www.ibm.com/partners/ & Build https://www.ibm.com/partners/build/
- Event THINK https://www.ibm.com/events/think/
- Hybrid Cloud https://www.ibm.com/cloud/hybrid

Some users of DDS lead space without modified background: 
- PartnerWorld https://www.ibm.com/partners/ & Build https://www.ibm.com/partners/build/ (also on white theme, no visual changes if we fix this)
- IBM Docs https://www.ibm.com/docs/en (unsure about this one. Could be completely custom) 

----
Design spec: https://ibm.box.com/s/d9jey3rlfxqmxu059f0x9dtcx7f5ehuh

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/1f9d7efb-6b13-481d-8ccd-3758642c819b)

**Comment by RobertaJHahn** [comment]
@photodow Does this enhancement need functional specs?

**Comment by photodow** [comment]
> @photodow Does this enhancement need functional specs?

Possibly, I think I need more information.

**Comment by jeffchew** [comment]
Discussing this, we would like to introduce a utility class for this to be applied to whichever components that needs this and would be applied via prop/attribute.

Utility class and applying to Lead space (web components) would be the scope of this issue.

**Comment by jeffchew** [comment]
@RobertaJHahn we will need functional specs before we can size this work.
