### ISSUE TITLE
[Masthead]: Provide local/globalization support to Platform Name and URL

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#6178]
### The problem
- The current attributes for passing a platform name and URL to the `dds-masthead-container` and `dds-cloud-masthead-container` works great, however, it doesn't scale well on localized pages.
- Here's an example of the current Drupal Cloud masthead that has the string "cloud" translated into `arabic` (https://cms.ibm.com/ar/cloud/paks) as well as its homepage URL (https://cms.ibm.com/ar/cloud).
- This feature is needed within the production use of the Unified Cloud Masthead + Mega Menu as well as in AEM.

![Screen_Shot_2021-05-25_at_11_12_26_AM](https://user-images.githubusercontent.com/1815714/119522753-3a672580-bd4a-11eb-8ebc-724018b88d96.jpg)

```
<dds-cloud-masthead-container
  platform="Cloud"
  data-endpoint="/common/carbon-for-ibm-dotcom/translations/cloud-masthead/jsononly"
  platform-url="https://www.ibm.com/cloud"
></dds-cloud-masthead-container>
```

### The solution
- Alter the data fetching method to pull from the endpoint if the data exists.
- We might need to add a new field within the `mastheadNav` array for `mastheadNav[platform]` that manages its translated name and URL. https://github.ibm.com/webstandards/ibm-dotcom-translations/tree/master/translations

**Comment by jeffchew** [comment]
Does the platform name need to be translated if it's an IBM product name?

**Comment by proeung** [comment]
@jeffchew From what I've seen so far, the platform name looks to be translated for non-English speaking countries, please see below for the list of pages that are translating the word "Cloud". 

- https://cms.ibm.com/ar/cloud
- https://cms.ibm.com/jp-ja/cloud
- https://cms.ibm.com/cn-zh/cloud
- https://cms.ibm.com/ar-es/cloud

I'm not sure if this is the standard, however, I think it's still important to expose the `platform-url` string in the API endpoint so that each local can put in their proper homepage link.

![Screen_Shot_2021-05-27_at_10_54_47_AM](https://user-images.githubusercontent.com/1815714/119848696-07539c00-beda-11eb-8efd-f282dfac1d44.jpg)

**Comment by RobertaJHahn** [comment]
Will be added to the 6/7 engineering refinement meeting agenda.

**Comment by RobertaJHahn** [comment]
HC has a work around until this is ready.  Moving to the July 27 release.

**Comment by proeung** [comment]
@RobertaJHahn Thanks! Looking forward to seeing the long term solution for this issue in the July 27 release.
