### ISSUE TITLE
[Button group] without expressive, switch to Carbon core

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6180]
## Detailed description

> Describe in detail the issue you're having.

Without the expressive theme and with the introduction of the expressive button in Carbon, we should switch button group to depend on Carbon core expressive variant of button. It should look the same (48px container, 16px font and 20px icon).

Assuming updating `button group` will cascade to `Lead space` and `CTA` based on the [used by](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Button-group) list in the func specs

## NOTE TO DEVELOPER

**Branch should be off of the `feat/expressive-sunset` branch and targeted back to this branch when opening a PR!**

## Additional information

[Percy](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/10505563/search/preview/590974595?browser=chrome&searchParam=button&viewLayout=overlay&viewMode=new&width=1280)
[PR removing expressive](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6127)
[Web components](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/6127/index.html?path=/story/components-button-group--default)
[React](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/6127/index.html?path=/story/components-button-group--default)

**Comment by RobertaJHahn** [comment]
Waiting for Olivia's feedback

**Comment by oliviaflory** [comment]
@guilhermelMoraes cc @RobertaJHahn is there something you're waiting on me for? I thought this was where we left off last week:
>Just to make sure I'll add the isExpressive  prop to the buttons (although they don't need it since they already matches the expressive style with no flag for it).

I haven't seen a PR yet, but can review when it's ready!
