### ISSUE TITLE
[Content section, block, group, item] Create design specs

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6190]
We need to expose these components in Storybook (previously called sub-components). Reason being: 
- encourage adopters to assemble their own Content blocks
- allows for easier QA 
- allows for component documentation to be written against more logically 

To do the above, we need to prep these materials for dev: 
- [x] Design spec
- [x] Placeholder content 
- [x] Check functional spec
- [ ] Write out ideal storybook presentation (component name, knobs, variants if any)

**Comment by shixiedesign** [comment]
For **Content section's current spacing**, pls reference James's very thorough audit https://ibm.ent.box.com/file/817125554824?s=otaivja5mvh5jn5niwzcobbacauy2x1y

**Comment by DragosRistici** [comment]
Items [are added here](https://ibm.ent.box.com/folder/140116941081) for the team review.

**Comment by DragosRistici** [comment]
Content section [is here](https://ibm.box.com/s/oqlsa6m0vfownbn1s2y682mnugsf6cuv). 
Content block [is here](https://ibm.box.com/s/uaq0ovswviefwbv7gd4jn13llvqb23f8). 
Content group [is here](https://ibm.box.com/s/5n0sj6b3kkicnwimxmgnwb5owm46g8wz).
Content item [is here](https://ibm.box.com/s/xfm17x7dwbe4z7kjk482b8hbpjasft7o).

**Comment by DragosRistici** [comment]
### Storybook stories:

**Content item**
Heading (textarea)
Add media (select)
	– Image
	– Video
Description (textarea)
CTA copy (textarea)
CTA type (select)

**Content group**
Heading (textarea)
Paragraph (textarea)
Add children
	– Content item simple (checkbox)
	– Content item with image (checkbox)
	– Content item with video (checkbox)	
Card link heading (textarea)

**Content block**
Heading (textarea)
Paragraph (textarea)
Add children
	– Content group (checkbox)
	– Card group (checkbox)
CTA type (select)
– CTA link – Card link
Container bottom border (checkbox)

**Content section**
Heading (textarea)
Description (textarea)
Add children
	– Content group (checkbox)
	– Card group (checkbox)
CTA link

Note: No blocks were included in the Content section knobs.
