### ISSUE TITLE
[back to top] without expressive theme, update to use Carbon expressive button

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6191]
## Detailed description

> Describe in detail the issue you're having.

Removing expressive theme seems to have broken back to top visuals somehow.

**Current**
- missing icon
- not a circle
![Screen Shot 2021-05-26 at 9.24.51 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/238714c9-c8ed-47b2-a7bf-539ae541047b)

**Expected**
- needs icon
- should be a circle
![Screen Shot 2021-05-26 at 9.29.22 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/7fce21ff-1949-44a0-b1d1-525b4946eb8d)

- [ ] update to use Carbon expressive button

[Design spec](https://ibm.ent.box.com/folder/127553793291?s=1ol1qe0tdplhet6mh9z2sx5ncqmikd4r)
[Func spec](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Back-to-top)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

back to top

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## NOTE TO DEVELOPER

**Branch should be off of the `feat/expressive-sunset` branch and targeted back to this branch when opening a PR!**

## Additional information

[PR removing expressive](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6127)
[Percy](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/10505563/search/preview/590974600?browser=chrome&searchParam=back&viewLayout=overlay&viewMode=new&width=1280)
[Web components](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/6127/index.html?path=/story/components-back-to-top--default)
[React wrapper](https://ibmdotcom-web-components-react.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/6127/index.html?path=/story/components-back-to-top--default)

**Comment by jeffchew** [comment]
@kennylam going to unassign this from you since you're on vacation for the rest of the sprint, and I want you to focus on Beacon next sprint.
