### ISSUE TITLE
[video player] without expressive theme, use $caption-02 token

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6199]
## Detailed description

> Describe in detail the issue you're having.

Removing expressive theme caused the type token to shrink, need to update to utilize the new type token Carbon added to accommodate expressive styles.

- [ ] Update `video player` to use `$caption-02` token for the caption type style.

Assuming updating video will cascade to all [components that use it](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Video):

- CTA block
- Content block segmented
- Content block simple
- Content group simple
- Content item
- Lead space block

<img width="763" alt="Screen Shot 2021-05-26 at 11 59 13 AM" src="https://user-images.githubusercontent.com/45692622/119692933-d57b0080-be19-11eb-971c-6bbb1b8b7e37.png">

## NOTE TO DEVELOPER

**Branch should be off of the `feat/expressive-sunset` branch and targeted back to this branch when opening a PR!**

## Additional information

[PR removing expressive](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6127)
[Web components](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/6127/index.html?path=/story/components-video-player--default)
[React](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/6127/index.html?path=/story/components-video-player--default)

**Comment by ariellalgilmore** [comment]
Assigning to myself as @lathaMaramganti will be working on this.
