### ISSUE TITLE
[Link list] without expressive theme, update type token

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6201]
## Detailed description

> Describe in detail the issue you're having.

*Note: this may be taken care of when `link with icon` #6179 and `CTA` #6141 are updated, but want to make sure to document this change since Link list has so many variations and is used a lot*

Type size decreased in `Link list – horizontal` `Link list – vertical` and `Link list – end of section` variants.

Should use `$body-long-02` token, possibly will be updated through `CTA`.

Assume we will also see the changes in [`Link list section`](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/6127/index.html?path=/story/components-link-list-section--default)

**Horizontal**
![Screen Shot 2021-05-26 at 1.48.09 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/b3f7d123-90a5-4360-a07e-47d19a01ab9d)

**Vertical**
![Screen Shot 2021-05-26 at 1.48.21 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/4f821676-e420-453d-ba84-708a59d9e21f)

**End of section**
![Screen Shot 2021-05-26 at 1.48.33 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/60d1abaa-0671-4a76-9a0a-bf7853f5961d)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## NOTE TO DEVELOPER

**Branch should be off of the `feat/expressive-sunset` branch and targeted back to this branch when opening a PR!**

## Additional information

[PR removing expressive](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6127)
[Web components](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/6127/index.html?path=/story/components-link-list--horizontal)
[React](https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/6127/index.html?path=/story/components-link-list--horizontal)

**Comment by NSDrowned** [comment]
Hello @oliviaflory, both #6179 and #6141 are done now. Can you please confirm they the size issue in this `link list`? They show up at 16px to me 👍

**Comment by NSDrowned** [comment]
Hello @oliviaflory, both #6179 and #6141 are done now. Can you please confirm they fixed the size issue in this link list? They show up at 16px to me 👍

**Comment by oliviaflory** [comment]
@NSDrowned yes, it looks good in the feature branch! We can probably close this issue?

**Comment by NSDrowned** [comment]
Sounds good! 

Cc @RobertaJHahn
