### ISSUE TITLE
[Expressive modal] update to use Carbon expressive button

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6202]
## Detailed description

> Describe in detail the issue you're having.

Without the expressive theme, the modal launch button and button within the modal text size decreased in the example of the expressive modal.

- [ ] update the example to use Carbon expressive button variant from Carbon core

![Screen Shot 2021-05-26 at 1.58.19 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/fe296b1c-9039-4f63-a303-d1b52f40b870)

**Note: React looks fine, the removal of expressive theme is only present in Web components**
> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## NOTE TO DEVELOPER

**Branch should be off of the `feat/expressive-sunset` branch and targeted back to this branch when opening a PR!**

## Additional information

[PR removing expressive](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6127)
[Percy](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/10505563/search/preview/590974670?browser=chrome&searchParam=expressive&viewLayout=overlay&viewMode=new&width=1280)
[Web components](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/6127/index.html?path=/story/components-expressive-modal--default)
~React~

**Comment by emyarod** [comment]
it looks like the Carbon Expressive button is already in use, but there are a few upstream bugs which should be resolved in https://github.com/carbon-design-system/carbon-web-components/pull/697
