### ISSUE TITLE
[Video player] Web Components: Lightbox mode for video player only supports a single video on a page

### ISSUE THREAD

**Issue by ccwilson-us-ibm-com** [carbon-design-system/carbon-for-ibm-dotcom#6217]
## Detailed description

> Describe in detail the issue you're having.

Bug occurs when rendering two instances of the video player container web component in lightbox playing mode with different video ids.  Clicking on one video will open the lightbox modal and play the correct video as expected.  Clicking on the second video will open the lightbox model, but only the first video clicked will play in the modal.  The second video id (or any video id beyond the first one clicked) will not play.

The issue revolves around this line: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player-composite.ts#L77

This if conditional will prevent a different video id from being loaded in the lightbox video player.  And I haven't found another line of code that clears the original video id.  So only the first video loaded will play in the lightbox and no other after that.

Should there be more than one `dds-lightbox-video-player-container` to handle more than one `dds-video-player-container` in lightbox mode?

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

A bug. (maybe)

> Is this issue related to a specific component?

Video player and lightbox video player components.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected: Multiple video players in lightbox mode can be used on a page.  Each video player will load the video associated with the video id attribute.

Currently: Only the first video clicked will play the correct video.  Clicking any other video player will only play that same first video regardless of the video id attribute.

> What browser are you working in?

Chrome, Firefox

> What version of Carbon for IBM.com are you using?

Latest master branch.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

AEM

## Steps to reproduce the issue

The following markup in storybook should replicate the behavior:
```
<dds-video-player-container video-id="1_9h94wo6b" aspect-ratio=${aspectRatio} playing-mode="lightbox">
</dds-video-player-container>
<dds-video-player-container video-id=1_w5drm2rz aspect-ratio=${aspectRatio} playing-mode="lightbox">
</dds-video-player-container>
<dds-lightbox-video-player-container></dds-lightbox-video-player-container>
```

**Comment by RobertaJHahn** [comment]
@ccwilson-us-ibm-com  Can you provide a link to the page where you have implemented so that we can reproduce the issue.  Thanks.

**Comment by virtuakazib** [comment]
There isn't a published page with this issue.  It can be replicated in this fork/branch: https://github.com/ccwilson-us-ibm-com/ibm-dotcom-library/tree/issue-6217

This branch contains the same code change quoted above.

Build and run storybook locally.  And browse to http://localhost:9000/?path=/story/components-video-player--with-lightbox-media-viewer

**Comment by ariellalgilmore** [comment]
Hi! a temporary fix should be adding the video-id to the `<dds-lightbox-video-player-container>`

` <dds-video-player-container video-id="1_9h94wo6b" aspect-ratio=${aspectRatio} playing-mode="lightbox">
    </dds-video-player-container>
    <dds-video-player-container video-id="1_w5drm2rz" aspect-ratio=${aspectRatio} playing-mode="lightbox">
    </dds-video-player-container>
    <dds-lightbox-video-player-container video-id="1_9h94wo6b"></dds-lightbox-video-player-container>
    <dds-lightbox-video-player-container video-id="1_w5drm2rz"></dds-lightbox-video-player-container>`

**Comment by ariellalgilmore** [comment]
Maybe we can change this bug to instead be updating our `<dds-lightbox-video-player-container>` to handle the switch between different video-id's, so we don't have to duplicate the variable in the components.

**Comment by ccwilson-us-ibm-com** [comment]
Hmmm.... That solution works for me when running it in storybook.  But not when I try this in an AEM page, I still can't play more than one video.

When I checkout the AEM page with a debugger, the videoId property within the DDSLightboxVideoPlayerComposite isn't being given an initial value.  Even though we're assigning a value with the `video-id` attribute.  Any ideas?
