### ISSUE TITLE
Uncaught Type Error in dotcom-shell-composite.js:183

### ISSUE THREAD

**Issue by Kpal22** [carbon-design-system/carbon-for-ibm-dotcom#6220]
## Uncaught Type Error in dotcom-shell-composite.js:183

# Detail

In a new angular project, just implemented `dotcom-shell` but getting type error in browser console on scrolling
**_app.component.html_** has
```
<dds-dotcom-shell-container>
  <main>
    Hello World!
  </main>
</dds-dotcom-shell-container>
```
**_package.json_** has
```
"dependencies": {
    "@angular/animations": "~9.1.13",
    "@angular/common": "~9.1.13",
    "@angular/compiler": "~9.1.13",
    "@angular/core": "~9.1.13",
    "@angular/forms": "~9.1.13",
    "@angular/platform-browser": "~9.1.13",
    "@angular/platform-browser-dynamic": "~9.1.13",
    "@angular/router": "~9.1.13",
    "@carbon/ibmdotcom-web-components": "^1.4.0",
    "@carbon/icons-angular": "^11.2.2",
    "carbon-components": "^10.36.0",
    "carbon-components-angular": "^4.52.0",
    "lit-element": "^2.5.1",
    "lit-html": "^1.4.1",
    "process": "^0.11.10",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "typescript": "^3.7.7",
    "zone.js": "~0.10.2"
  },
```
# Error
In Chrome the error in console is
`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined`
![chrome_error](https://user-images.githubusercontent.com/45649979/119953569-c3d15e80-bfbb-11eb-91a4-b09eec137a5e.png)

In Firefox the error in console is
`Uncaught TypeError: this._tableOfContentsInnerBar is undefined`
![firefox_error](https://user-images.githubusercontent.com/45649979/119953951-232f6e80-bfbc-11eb-8109-ada8061a8c16.png)

**Comment by DragosRistici** [comment]
@Kpal22 Hi Kaustav, 

We'll look into it. 
Could you put it in a sandbox and give us the link to it to further investigate?

Thank you!

**Comment by Kpal22** [comment]
@DragosRistici  Hi,
I tried my repo https://github.com/Kpal22/carbon-design-test  in codesandbox but its not working there
https://codesandbox.io/s/keen-zhukovsky-p5r4q
