### ISSUE TITLE
Update the 🐛 Bug issue template

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6224]
### The problem
Many adopters do not provide enough information with the current 🐛 bug issue template, which makes it difficult for the Fire line team to lend support and triage issues.

### The solution
Update the Bug template to encourage adopters to fill it out and add any additional questions that might be missing in the current version.

### Additional information

**Current template**
[See issue templates](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/new/choose)

```
<!-- Feel free to remove sections that aren't relevant.

## Title line template: [Title]: Brief description

-->

## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes
```

**Ideas from Team Huddle 6/1**

- Add codesandbox question to the template
- Link to an environment if exists, but be mindful not to share if has sensitive information, reach out over slack
- React vs web components
- Promote screenshot to higher in the questions
- Try to fix the formatting to be easier to read/scan
   - Use categories to break up questions?
   - Use caps for H2's?
- Better messaging at the top of the bug template (benefits of providing more details)
- If not enough info provided, can close the issue sooner

### Acceptance criteria
- [ ] New Bug template is shared with the wider team
- [ ] Bug template is updated

**Comment by RobertaJHahn** [comment]
Jonathan will be assigned to this issue.

**Comment by JBrandwine** [comment]
[https://app.zenhub.com/files/193129061/ffcadeb4-a6a9-4cef-a0ce-0530b35dcdc1/download](https://app.zenhub.com/files/193129061/ffcadeb4-a6a9-4cef-a0ce-0530b35dcdc1/download)

**Comment by JBrandwine** [comment]
Added WIP template update for review. Thanks!

**Comment by jeffchew** [comment]
Bring up as a huddle topic to review as a team.

**Comment by JBrandwine** [comment]
[https://app.zenhub.com/files/193129061/3ca3f920-2b71-4934-b3a8-776e29a4062b/download](https://app.zenhub.com/files/193129061/3ca3f920-2b71-4934-b3a8-776e29a4062b/download)

Updated per feedback during DDS team huddle.

Please let me know of any additional feedback.

Thanks!
