### ISSUE TITLE
[Masthead L1] Nav on page load, active item not necessarily visible depending on where it is in nav menu

### ISSUE THREAD

**Issue by QuirkWebDevelopment** [carbon-design-system/carbon-for-ibm-dotcom#6225]
## Detailed description

> Describe in detail the issue you're having.

Using Carbon for IBM Next JS template
Configured L1 navigation through Dotcom Shell
Load page
Click on arrow at top right of L1 to load next nav items
Click on any nav item
reload page
Active menu item not visible on page load

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Dotcom shell that then pulls in Masthead Component that then renders L1 navigation. 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected the active menu item to be visible on page load always no matter where it is in the menu

> What browser are you working in?

Chrome

> What version of Carbon for IBM.com are you using?

@carbon/ibmdotcom-react": "^1.18.1"

https://user-images.githubusercontent.com/66688772/120378915-0d3be980-c2ed-11eb-929c-6e11a8a315fe.mov

**Comment by RobertaJHahn** [comment]
Will be added to the 6/3 design huddle meeting agenda.

**Comment by shixiedesign** [comment]
This will be treated as a feature request with a functional spec issue and a dev issue. @RobertaJHahn Thanks!
