### ISSUE TITLE
Web component: Leadspace Super - On Mobile, Bread crumb must be aligned same line.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6227]
## Detailed description

Issue: 
Leadspace Super - On Mobile, Bread crumb must be aligned same line. Here the bread crumb text is small but still wrapped to next line.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/010a6ba5-ffaa-4f5a-9e95-99e7e6c82a17)

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr I've couldn't find this issue happening on the latest version.
Can you please share the link you used along with the resolution you found the bug on?

Thank you!

**Comment by Praveen-sr** [comment]
@RaphaelAmadeu Re tested this on web component, above issue is fixed now.

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/29fcd3c4-76da-4933-8bfe-7c35114b6ebf)

**Comment by RobertaJHahn** [comment]
Closing based on Praveen's comments above.
