### ISSUE TITLE
web component: Card Static - On Mobile, CTA link is not operable.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6228]
## Detailed description

Issue:
On Mobile, CTA link is not operable. On click does not re direct to page.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/eba75529-9841-465d-84c4-21ec6d109847)

**Comment by NSDrowned** [comment]
Hello @Praveen-sr, this issue seems to be the same as https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6490 which was fixed in this PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6506 

Can you please recheck?

**Comment by Praveen-sr** [comment]
@NSDrowned Re tested this on staging,  CTA link is operable now. Working fine.
cc @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Closing based on Praveen's comment above.
