### ISSUE TITLE
Web component: Leadspace breadcrumbs - The current/selected bread crumb is clickable and it re direct.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6230]
## Detailed description

Issue:
Leadspace breadcrumbs - The current/selected bread crumb is clickable and it re direct.

## Additional information

![LS_Breadcrumb.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/8b8bb994-37c9-4dbb-9d51-d95e59b1169c)

**Comment by RaphaelAmadeu** [comment]
@Praveen-sr 
This is working as intended, as the breadcrumbs are demostration only they are using blank links, so it redirects.

Thanks!
