### ISSUE TITLE
Web component: Leadspace - Tag group/ breadcrumb are mis aligned on mobile landscape mode

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6231]
## Detailed description

Issue:
Leadspace - Tag group/ breadcrumb are misaligned on mobile landscape mode

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/dcf6eea4-7ede-4a32-8ea0-7718560f754d)

**Comment by shixiedesign** [comment]
Just checked canary, no longer an issue.
