### ISSUE TITLE
[Card group] Style bugs in Web components

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#6234]
1. Web Components – With Card in card story – grid mode narrow (16px):
<img width="569" alt="Screenshot 2021-06-01 at 12 38 39" src="https://user-images.githubusercontent.com/48327647/120302191-516fbf80-c2d6-11eb-8901-2094f4eb683b.png">
<img width="89" alt="Screenshot 2021-06-01 at 12 38 32" src="https://user-images.githubusercontent.com/48327647/120302197-52a0ec80-c2d6-11eb-9d3c-90cc85a4080d.png">
There is a right border for the first 2 cards that is applied to the dds-card-group-item which has padding instead of margin so the border is applied to the padding spacing also. 

2. Web Components – With Card in card story – the collapsed grid has some spacing errors
<img width="244" alt="Screenshot 2021-06-01 at 12 43 34" src="https://user-images.githubusercontent.com/48327647/120302888-fdb1a600-c2d6-11eb-9c48-32cf4c392048.png">

3. The same errors from 2 and 3 are visible for the `With Card in card and Image cards` story
<img width="681" alt="Screenshot 2021-06-01 at 12 44 22" src="https://user-images.githubusercontent.com/48327647/120303001-191cb100-c2d7-11eb-86c1-c8cab0773ade.png">

**Comment by RobertaJHahn** [comment]
Shixie and Dragos will break out the style issues (Sev 3) and the storybook issues (Sev 4).

**Comment by photodow** [comment]
2 additional items. Card in card is missing border when grid mode is set to border, and card in card is seperated from card group in storybook causing issues where one can have narrow, and the other broder grid modes for example. I think it might also be creating some of the spacing issues we see above.

**Comment by shixiedesign** [comment]
Looking through this issue trying to break it down, and I think some of here might be not bugs. 

React version of this component is behind web components. Some issues are tracked but not all: 

- with Card in card variant https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/5339
- with mixed media variant

I made an edit to the description above to focus the issue on **Card group web components style bugs**

New issue for Web components storybook knob changes: #6338

**Comment by DragosRistici** [comment]
Hi @BrunnoM7 

I re-QAed it again, and I just see this one now for `Card group – With card in card and image cards` story. When I switch to the collapsed grid, there is no top border for the cards – its image touching image. Also, when I switch back to a narrow grid, the 16px top spacing is not there. I don't know if this second one is a Storybook bug, or a component bug, because the default story has a narrow grid. Here's what I see: 
https://images.zenhubusercontent.com/193129061/dff6be3e-fae5-4bb1-bb22-bbdbcb6d8df3/card_group_with_card_in_card_and_image_cards.mov

**Comment by kennylam** [comment]
Having reviewed the [production version](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-card-group--with-card-in-card) of this component's `With card in card` and `With card in card and image cards` variants, it appears these layout issues have been resolved. If these issues resurface, potential fixes can be found in #7409.

cc: @emyarod @jeffchew
