### ISSUE TITLE
[card section offset] web components

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6241]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
provide consulting support to a non-DDS engineer who is creating/changing the `card section offset`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic for the Design and Functional specs information**
- Visual QA will be done by the AEM designer, Pavol Prok
- DDS consulting designer assigned for questions and process:  Shixie
- Visual QA consulting issue issue (#6243 )
- Prod QA testing issue (#6291 )

----
- Dev by Hybrid Cloud team
- HC Engineer assigned:  Dennis Doliver will shadow for learning experince.
- HC story point estimate:  8

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by proeung** [comment]
**Dennis Dolliver** is the FE Engineer assigned on the HC side for this component.
