### ISSUE TITLE
Lead space height

### ISSUE THREAD

**Issue by nrmv** [carbon-design-system/carbon-for-ibm-dotcom#6248]
Hello! How can I change the height of the lead space?
http://carbon-for-ibm-dotcom.mybluemix.net/components/leadspace/#lead-space-left-aligned

**Comment by ariellalgilmore** [comment]
Hi! are you using react or web components? We have documentation for both in our storybook docs on which props to change for the height: [react](http://ibmdotcom-react.mybluemix.net/?path=/docs/components-lead-space--default-with-no-image#props) and [web components ](http://ibmdotcom-web-components.mybluemix.net/?path=/docs/components-lead-space--medium#props).

**Comment by nrmv** [comment]
> Hi! are you using react or web components? We have documentation for both in our storybook docs on which props to change for the height: [react](http://ibmdotcom-react.mybluemix.net/?path=/docs/components-lead-space--default-with-no-image#props) and [web components ](http://ibmdotcom-web-components.mybluemix.net/?path=/docs/components-lead-space--medium#props).

For any type parameter, the leadspace does not resize and remains large

**Comment by nrmv** [comment]
Template https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template
has the same problem.
![image](https://user-images.githubusercontent.com/13987951/120634420-e6f48600-c473-11eb-9f22-3d482478c2f9.png)

**Comment by nrmv** [comment]
I am trying to make such a leadspace:
![image](https://user-images.githubusercontent.com/13987951/120637706-e6f68500-c477-11eb-996a-d6b03e458cf9.png)

**Comment by RobertaJHahn** [comment]
Here is the link to the June release schedule:  https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5579
