### ISSUE TITLE
Contribute expressive type styles usage on "Typography" page

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6252]
### Details 
- With new the expressive type styles added to Carbon, we still need to provide guidance on when they should be used. 
- New guidance should resolve "**When to use expressive vs productive?**" question. 
- Content could live between Carbon "Typography" page & Dotcom `Type pairing`

Draft PR: https://github.com/carbon-design-system/carbon-website/pull/2410

Issue in Carbon repo for dev work to create type set table: https://github.com/carbon-design-system/carbon/issues/8934

**Comment by shixiedesign** [comment]
Here are the content so far and have gone through a rough review already: 

PR: 
https://github.com/carbon-design-system/carbon-website/pull/2410
Invision link: 
https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/21476859

**Comment by janchild** [comment]
- [ ] Examples of expressive within productive experience
- [ ] Images
- [ ] Do's and Don'ts
- [ ] Review table behavior and update Carbon issue

**Comment by janchild** [comment]
June 22: 
- Met with @oliviaflory to discuss content and behavior of prototype for new type set page. 
- Confirmation from Alison Joseph that Carbon dev will be working on table next sprint (week beginning June 28)
- Meeting with Jean Servaas June 24 to discuss behavior of prototype

**Comment by janchild** [comment]
- @oliviaflory and @janchild met with Jeannie, Lauren, and Tracey to discuss expressive moments in product and draft some content
- Handing Sketch file over to @oliviaflory to create images. Will add another issue to cover this work.

**Comment by oliviaflory** [comment]
Uploading the examples I mocked up here for initial look 👀 

I used the 3:2 928 (12 column) browser template size from Jeannie's spec template, but also have the 3:2 608px (8 column) created as well. These use a 1px solid border to outline the productive moment areas.

**1. Mega menu**
![3:2_928_ui_full productive-moment-3](https://user-images.githubusercontent.com/45692622/123694186-fe325380-d826-11eb-88a3-959bff9f22f1.png)

**2. Products page**
![3:2_928_ui_full productive-moment-1](https://user-images.githubusercontent.com/45692622/123694164-f5418200-d826-11eb-9520-b165a0c270ff.png)

**3. Search results**
![3:2_928_ui_full productive-moment-2](https://user-images.githubusercontent.com/45692622/123694177-fa9ecc80-d826-11eb-9abb-f413d6a9cba8.png)

**4. URX**
![3:2_928_ui_full productive-moment-4](https://user-images.githubusercontent.com/45692622/123694196-012d4400-d827-11eb-8fd4-c166803e5065.png)

**Comment by janchild** [comment]
@oliviaflory Thank you for these. I can start putting them up in the PR. 

For the mega menu, I'm wondering if there's another way to show it because the outline is decoupling the mega menu content from the tab. I'm also wondering if we should scroll down the page a little bit because I'm distracted by the color images at the bottom of the page there. 🤓 

![image](https://user-images.githubusercontent.com/44503588/123700428-13f34900-d826-11eb-921d-697734f12d64.png)

**Comment by oliviaflory** [comment]
Update to all images on G20 background, and adjustments to mega menu & filter panel outline

*Also just remembered the live Products page is still using Expressive type styles for the filter panel* 🙈   *I will update with a mock UI I have*

![3:2_928_ui_full productive-moment-2](https://user-images.githubusercontent.com/45692622/123705316-cc27ee00-d834-11eb-8c3f-ede3c8d32c73.png)
![3:2_928_ui_full productive-moment-3](https://user-images.githubusercontent.com/45692622/123705551-1f9a3c00-d835-11eb-9dd0-ba04f49661e3.png)
![3:2_928_ui_full productive-moment-4](https://user-images.githubusercontent.com/45692622/123705322-ccc08480-d834-11eb-8f17-e740d56ad727.png)

**Comment by oliviaflory** [comment]
Product page updated... let me know if you'd like to adjust the outline for the filter panel, I stuck to just the filter panel container

![3:2_928_ui_full productive-moment-1](https://user-images.githubusercontent.com/45692622/123708044-bcaaa400-d838-11eb-9741-a3a374637361.png)

**Comment by oliviaflory** [comment]
### All final images can be found in the [Carbon typography page folder](https://ibm.ent.box.com/folder/140118821311)

**Comment by janchild** [comment]
The guidance has been completed and the tables updated by the Carbon dev, Scott Strubberg. 
Guidance is ready for publishing and can be previewed here: https://github.com/carbon-design-system/carbon-website/pull/2410

The project is moving into the implementation phase now, covered by #6696.
