### ISSUE TITLE
[Masthead]: Masthead missing top padding to prevent overlay with content components - DPO Consulting

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#6270]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2366
- DPO consulting engineer: @annawen1 

----

## Detailed description

> Describe in detail the issue you're having.

There is `padding-top: 3rem` applied to the DotcomShell component to prevent the overlap of the masthead and another component on the page (ie. Leadspace). However if adopters use the masthead independently of the DotcomShell, we see the overlap issue occurring. 

Solution would be to apply the `padding-top` to the masthead component instead of DotcomShell.

## Additional information

<img width="1572" alt="Screen Shot 2021-06-01 at 5 24 36 PM" src="https://user-images.githubusercontent.com/54281166/120825711-a7877180-c527-11eb-87bb-3e4fad7e7e3a.png">

Issue seen on zStore application:
![image (9)](https://user-images.githubusercontent.com/54281166/120825750-b1a97000-c527-11eb-83fa-bfa690d5c002.png)

**Comment by proeung** [comment]
@annawen1 Thanks for opening this ticket!

@huntermacd FYI.

**Comment by shixiedesign** [comment]
I believe we still need this - adding `adopter support` as this is a recurring issue.

**Comment by jeffchew** [comment]
Might be related to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7643
