### ISSUE TITLE
[Call out with media] update type token

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6272]
As a designer I need to update the visual specs, and check the functional spec dependencies, so the specs match the upcoming changes to the component.

- [ ] update caption under video in callout with media to use $caption-02 token

## Acceptance criteria
- [x] visual spec are updated and saved to Box
- [x] functional spec dependencies have been cross checked and updated

**Comment by RichKummer** [comment]
Boxnotes folder for review: https://ibm.box.com/s/p7l9hs3hht4zlcu3ipaqbwqngqtdcdhi
