### ISSUE TITLE
[Content block with card static] Add link with icon below button group - behind a feature flag

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#6274]
### The problem
_{{We need to add the **link with icon** to the Content block with card static component.)}}_

### Additional information
 - Design specs (PDF): https://ibm.box.com/s/plhuxjxl2sv9fxt54eg66mk9qst4iqri
 - Design specs (Sketch): https://ibm.box.com/s/2o4y3cfpofhwrhnc9qpbmfn5z9clylju
 
<img width="858" alt="Pasted_Image_6_4_21__3_35_PM" src="https://user-images.githubusercontent.com/77290329/120854179-cc411080-c54a-11eb-872d-fc539b51b409.png">

**Comment by RobertaJHahn** [comment]
Next issues:  Convert to epic Update func specs, WC dev, limited Prod QA

**Comment by RobertaJHahn** [comment]
@kirbyevans  This change can be done without making a change to this component.  The requested link can be added below the current CTA's.  When ready to built this template, we should have an engineering huddle between DDS and AEM to talk about implementation.

**Comment by RobertaJHahn** [comment]
iceboxing this issue until AEM is ready to implement.

**Comment by RobertaJHahn** [comment]
Linked issues closed.  Closing
