### ISSUE TITLE
[Lead space] gradient issues on Gray 100 and Gray 90 themes

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#6275]
1. Apparently gradient doesn't change for Gray 100 and Gray 90 themes anymore on React 
<img width="1754" alt="Screenshot 2021-06-04 at 22 44 27" src="https://user-images.githubusercontent.com/48327647/120854883-6d998800-c586-11eb-9bc0-ff3abc39f18f.png">
2. On Web Components, all stories with no images for Gray 90 and Gray 100 have inverted gradients present. 

<img width="2087" alt="Screenshot 2021-06-04 at 20 00 05" src="https://user-images.githubusercontent.com/48327647/120854506-f237d680-c585-11eb-99cb-9439b4f5f740.png">

**Comment by RobertaJHahn** [comment]
This review was done against unmerged code.  This code was not merged because of this bug.  This should be retested on Canary.
