### ISSUE TITLE
[Card section carousel] update specs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6278]
#### User Story

Card section carousel specs don't follow the content section design specs. 

As a designer, I need to update the Card section carousel specs, so they follow the Content section specs. 

![Screen Shot 2021-06-04 at 4.41.44 PM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/e340f8ab-0fac-42db-a29a-f4b524668ace)

#### Additional information

- There should be no space between the headline and body copy
- Content section specs will be updated in #6190
- Check space between body copy and link/CTA for accuracy (see content section specs)
- Card section carousel should reference `Content section` rather than calling out all type tokens / components again.

#### Acceptance criteria
 - [x] Design specs have been updated and saved to Box
 - [x] Follow on development issue created to fix error

**Comment by shixiedesign** [comment]
Done. Should get fixed via ticket #6712 to all `Content section`
