### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by adrmnv** [carbon-design-system/carbon-for-ibm-dotcom#6279]
How do I fix this error?

`
./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[2].oneOf[7].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[2].oneOf[7].use[2]!./node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[7].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[2].oneOf[7].use[4]!./styles/globals.scss
SassError: Undefined variable.
   ╷
13 │   :host(#{$dds-prefix}-footer),
   │           ^^^^^^^^^^^
   ╵
  node_modules\@carbon\ibmdotcom-styles\scss\components\footer\_footer.scss 13:11                                  footer()
  node_modules\@carbon\ibmdotcom-styles\scss\components\footer\_footer.scss 124:3                                  @content
  node_modules\carbon-components\scss\globals\scss\vendor\@carbon\elements\scss\import-once\import-once.scss 23:5  exports()
  node_modules\@carbon\ibmdotcom-styles\scss\components\footer\_footer.scss 123:1                                  @import
  styles\globals.scss 19:9                                                                                         root stylesheet
`

**Comment by ljcarot** [comment]
Hard to know with just the little info you've shared.  We have office hours on Wed at 9am ET.  It might be easier if you sign up to join that.  If that is how you want to proceed, let us know via comment and we'll provide the sign up link.

**Comment by nrmv** [comment]
> Hard to know with just the little info you've shared. We have office hours on Wed at 9am ET. It might be easier if you sign up to join that. If that is how you want to proceed, let us know via comment and we'll provide the sign up link.

I am trying to use components from carbon-components-react with carbon-for-ibm-dotcom, I tried many different ways, different configurations of next and webpack, nothing helps

**Comment by jeffchew** [comment]
If you're using NextJS, you might want to check out the NextJS template. It comes configured with Carbon for IBM.com and `carbon-components-react`:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template

**Comment by nrmv** [comment]
> If you're using NextJS, you might want to check out the NextJS template. It comes configured with Carbon for IBM.com and `carbon-components-react`:
> 
> https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template

Unfortunately, the template does not contain carbon-components-react. And the error occurs due to the sharing of two libraries.

![image](https://user-images.githubusercontent.com/13987951/120923128-89f80a80-c6d5-11eb-8201-ad968a838ca1.png)

**Comment by RobertaJHahn** [comment]
@adrmnv Did Jeff's suggestion fix your issue?  Can we close it?

**Comment by RobertaJHahn** [comment]
Closing
