### ISSUE TITLE
[Masthead] Add functional spec of caret scrolling behavior

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6311]
Currently missing information on caret scrolling behavior: 
- Would need to document existing behavior
- Add that selected menu item in masthead should scroll into view on page load as requested by https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6225

**Comment by photodow** [comment]
Added an update to the functional specs. Let me know if I didn't capture it correctly. Didn't migrate this work over such a small change this time around.

![image](https://user-images.githubusercontent.com/3793636/127400935-fbc2de1e-e2d4-49fa-954d-cfc2f2018494.png)


https://ibm.box.com/s/89qwjyjy6kwbi69qnz4nzatwfv3mh2kc

**Comment by shixiedesign** [comment]
@photodow did you also add the documentation of existing caret scrolling behavior between breakpoint 800px - 961px ?

**Comment by RobertaJHahn** [comment]
Needs engineering sizing.  Schedule in the Aug 16 engineering issues refinement for sizing.
