### ISSUE TITLE
[Image] Add optional border to image

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#6315]
### The problem
There are times when an image's background color and the page's background color are the same. When this happens it creates an unintentional illusion of white space that feels awkward and unbalanced within the page layout.

### The solution
We think having the ability to add an optional 1px border of #E0E0E0 ($decorative-01) would help frame the images better when the page background and image background colors are the same.

### Additional information
- Image's optional border is documented in website already (branch to be merged): https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1112/components/image#border

Visual reference:
<img width="991" alt="Pasted_Image_6_8_21__2_02_PM" src="https://user-images.githubusercontent.com/77290329/121234941-48e13100-c862-11eb-96ef-002ea34e03ab.png">

 - [Functional specs](https://ibm.ent.box.com/folder/94834513317?s=zaofzs8ssrfbkgker2lqxyvdnbpxvsly)

**Comment by RobertaJHahn** [comment]
Convert to epic:  func specs, dev issues, QA and no website
