### ISSUE TITLE
[Lightbox media viewer] Layout updates

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#6328]
### The problem
There are inconsistencies between the current implementation of the Lightbox media viewer and its design specs. There are issues with the margin/padding and the image scrolling with the supporting image copy.

### The solution
We hope by simplifying the layout within the Lightbox media viewer that these issues will be resolved. Attached are the updated design specs for the Lightbox media viewer. These specs should address alignment of the image and supporting copy, as well as, how to accommodate supporting copy when it isn't able to fit within the Lightbox media viewer's visible area.

### Additional information
Design specs for the proposed solution can be found here:

[PDF](https://ibm.box.com/s/1gmz28s04qf17y0fvpky4csukumcomfw)
[Sketch file](https://ibm.box.com/s/1bv9s86wxo63exuend5ts9y1bdmvbsgs)

Preview of specs for Lightbox media viewer

![image](https://user-images.githubusercontent.com/77290329/121388709-b3a17380-c919-11eb-80fc-5ea117f21440.png)
![image](https://user-images.githubusercontent.com/77290329/121388791-c5831680-c919-11eb-8eee-f63dc998589f.png)

- Functional specs:  https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lightbox-media-viewer#2-viewer

**Comment by shixiedesign** [comment]
To be turned into Epic: design spec done. Need func spec, dev issue, QA issues. We need 1 website issue for all the lightbox changes coming from AEM (6328, 6329, 6314)
