### ISSUE TITLE
[Lightbox media viewer] Allow for isolated image view on mobile

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#6329]
### The problem
We suspect that a user will need to view an image larger than how it is currently displayed within the lightbox media viewer on mobile (sm breakpoint).

### The solution
We think by providing functionality to allow a user to isolate and zoom in on an image within the Lightbox media viewer that this new functionality could accomplish the user's desire to view an image larger.

### Additional information
Design specs for the proposed solution can be found here:

[PDF](https://ibm.box.com/s/1gmz28s04qf17y0fvpky4csukumcomfw)
[Sketch file](https://ibm.box.com/s/1bv9s86wxo63exuend5ts9y1bdmvbsgs)
 
Preview of specs for isolated image within the Lightbox media viewer 
![image](https://user-images.githubusercontent.com/77290329/121400492-a7bbae80-c925-11eb-974b-074f620b8c77.png)
![image](https://user-images.githubusercontent.com/77290329/121400502-ab4f3580-c925-11eb-8488-3f6c46fd8ef2.png)

**Comment by shixiedesign** [comment]
To be turned into Epic: design spec done. Need func spec, dev issue, QA issues. We need 1 website issue for all the lightbox changes coming from AEM (6328, 6329, 6314)

**Comment by ljcarot** [comment]
@shixiedesign  Do you think we can get some testing of this feature request before building it out.  I'm concerned that we are building a heavy duty lightbox viewer before MVP of the new product page has even launched. If I'm on mobile, I should be able to pinch the image on the page even if I can't pinch the image in the lightbox.  It feels like an extreme edge case to build for so early in our creation of the pp in Carbon.

**Comment by shixiedesign** [comment]
@ljcarot Yes I agree. I'm thinking we icebox this issue until the other 2 Lightbox enhancements are merged first? Meanwhile we can build out an inVision test to verify the UX.

**Comment by RobertaJHahn** [comment]
Icebox'd this epic and all linked issues based on comments above.
