### ISSUE TITLE
Identify the one GA report for tracking traffic

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6333]
To enable us to successful deliver against the OKRs, we'd like to identify the one Google Analytics report that we will all reference as the source of metric of our KPI.

**Comment by RobertaJHahn** [comment]
@ljcarot I think we said this issue can have the documentation added and then closed.  Thanks.

**Comment by ljcarot** [comment]
This is report from GA for tracking our pageviews in Carbon: https://analytics.google.com/analytics/web/?authuser=0#/dashboard/rWGJRg8ESuaNdNpdOdPXyg/a143580012w207210660p200215585/
