### ISSUE TITLE
[Masthead, login] Need new design

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6335]
### The problem

Login/Profile section of Masthead currently is a bit of a mess. [More details soon]

![image](https://user-images.githubusercontent.com/15144993/121599729-7ae4c580-ca11-11eb-94de-09f3f1642dfd.png)

Cloud masthead 
https://ibmdotcom-web-components-experimental.mybluemix.net/?path=/story/components-cloud-masthead--default
![image](https://user-images.githubusercontent.com/15144993/121600114-02cacf80-ca12-11eb-9cb7-042b225376db.png)

### Stakeholders & people in the field

- Login button currently takes people to **MyIBM**, which is owned **Jeff Mitchell** and designers involved are **Brandon Appe** and **Douglas Henry**. 

- **Cloud / Hybrid cloud** created their own masthead with primary button etc. Designer is **Lila Tittle** and IA comes from **Keegan Whitla**.

### To be figured out

1. this login / profile has to be for MyIBM, correct? was there a reason the current button gives 2 options: MyIBM and Login, instead of just 1 for login?
2. once logged in, we allow users to modify the dropdown from profile button, but is the default list of options all required? 3. Currently there are 4 options after logging in: MyIBM, Profile, Billing, Log out. In another words, would we need to consider grouping the options here.
4. Can we create new features here? Eg. showing user’s notifications such as product updates available, subscription expiring soon, etc
5. Does IBM has a rule against letting users creating avatars? I have vague memories of such things when Sheina was working on URX.

### Additional Information
- Completed design & functional spec in box: 
https://ibm.ent.box.com/folder/59063660753?s=mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1

**Comment by shixiedesign** [comment]
### Notes while taking to Jeff Mitchell 

**Pre login**
MyIBM - after authentication users are directed to MyIBM dashboard
Login - after authentication users are directed back to current page 

Question - users might not understand the difference  

**After login**
MyIBM = 
Dashboard (internally called Products & Services) 
Profile (is owned by IBM ID team, only hosted here)
Billing (owned by myIBM, considering future consolidation with other services InVoices at IBM) 

Dashboard
- in IBM multiple "dashboards" exist
- Lots of people arrive at myIBM dashboard without proper context. Bounce rate is high, bad NPS score. People go through creating an IBM ID, and then get dumped in myIBM and it's completely empty, and users are unable to complete the task they set out to do. 
- Aim to be a better landing spot. 


1. Should "MyIBM" be relabeled to be something more clear. Eg. MyIBM products & services
2. Profile - do customers understand that's where we update IBM ID? We have so many different kind of accounts at IBM, and cannot do it all in Profile page. People could be mislead and then disappointed. 
3. Do we need Profile, Billing here? 
4. "Billing" tab doesn't show info for hardware and services, which is again a big, visible promise, that could potentially mislead. Maybe Invoice at IBM system is a better place? 


> Does IBM has a rule against letting users creating avatars? I have vague memories of such things when Sheina was working on URX.
A IBM ID question. 

> showing user’s notifications such as product updates available, subscription expiring soon, etc
A couple of things could be interesting. Knowing a trial is about to expire. Inform people of annual renewals. New versions of product available, new fix pack available. Today users can [sign up](https://www.ibm.com/systems/support/myview/subscription/css.wss/?code=aceEqB1gHRheX3lYM7xoZcaRIXfVHP&grant_id=c82934e4-63a9-40dd-bb25-30690cd9dcab&state=Klqz58JfSkt2ijrahWoME2R-tYs3NiTzIZGFTIgL6V8) to get update with Support team on products, but that info is not visible else where.

**Comment by RobertaJHahn** [comment]
Issues needed:  func spec, WC & React, QA issues, website
