### ISSUE TITLE
[Table of contents][Web components test] Service page - Hamburger menu open, while user scrolls menu options, close icon not seen for the user

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6345]
## Detailed description

Issue:
Hamburger menu open, while user scrolls menu options, close icon not seen for the user.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/1ead73cb-ebe7-4af5-9cc9-72bb0d906cd8)

**Comment by IgnacioBecerra** [comment]
@Praveen-sr seems like this one has been fixed already, could you re-test? Thanks!

cc: @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Closing this issue based on Praveen's testing.  Here is his status:  
![image](https://user-images.githubusercontent.com/52469167/139853589-1a71a9fe-5ad5-44a6-b14a-a5c094f8067f.png)
