### ISSUE TITLE
[Footer][Web components test] Service page - On Mobile - Footer - Language selection modal - user clicks focus comes back to the parent page

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6346]
## Detailed description

On iPhone
Issue:
Footer - Language selection modal - user clicks focus comes back to the parent page

## Additional information

https://images.zenhubusercontent.com/193129061/06608853-db24-4546-8d76-6fb0d0539488/rpreplay_final1621854380.mp4

**Comment by Praveen-sr** [comment]
@IgnacioBecerra Retested this on iPhone and android, above issue has been fixed. 
 Language selection works as expected.

cc @RobertaJHahn

**Comment by RobertaJHahn** [comment]
Closing based on Praveen's comments above.
