### ISSUE TITLE
[feature card] theming is off

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#6350]
## Detailed description

The feature card components both medium and large aren't changing themes. Looks like we're hard setting it `g90` theme. The design specs appear to be using inverse tokens.

![Jun-11-2021 09-24-56](https://user-images.githubusercontent.com/3793636/121701860-f6d52100-ca96-11eb-86e8-4f615d91108b.gif)

## Steps to reproduce the issue

1. [Go here](http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-feature-card--medium) (link is to web components, but same issue is in react)
2. Change theme

## Additional information

- https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/styles/scss/components/feature-card/_feature-card.scss#L151

**Comment by shixiedesign** [comment]
Still an issue :scream:
