### ISSUE TITLE
[Web Components | Lit] Investigate upgrade to Lit 2.x

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#6361]
### The problem

Blocked by https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9767

Carbon Web Components is currently running on v1.x of `lit-element` / `lit-html`. This is one of the fundamental libraries used for rendering web components within this repository.

### The solution

Investigate the level of effort for upgrading `carbon-web-components` to Lit 2.x. 

### Additional information

- Investigation should consider users that are currently on lit-html/lit-element, and if there is any messaging necessary to have users upgrade to lit 2. 
- Corresponding upgrade issue for `carbon-web-components`: https://github.com/carbon-design-system/carbon-web-components/issues/657
- Upgrade documentation: https://lit.dev/docs/releases/upgrade/
- Additional information regarding the update is captured in [this](https://github.com/carbon-design-system/carbon-web-components/issues/657) issue.

**Comment by jeffchew** [comment]
Will hold on this for now, investigation began with `carbon-web-components` and found that there is a directive that we are waiting on, more details at https://github.com/carbon-design-system/carbon-web-components/issues/657.

**Comment by abdonrd** [comment]
There are any ETA to migrate `carbon-web-components` to Lit v2? Thanks!

**Comment by abdonrd** [comment]
Any news here?
It's been almost a year since Lit v2 came out.
Thanks!

**Comment by korgan00** [comment]
There is a new version 2.3 that prevents errors with windows not defined while using it with SSR in Node.
We are working with that versión, and it will be very useful to have it updated.

**Comment by javabster** [comment]
Has there been any progress one this? my team ran into an issue today where we are trying to access a web component built with carbon via a CDN but the import failed because the CDN requires v2

**Comment by 1ucian0** [comment]
This is blocking some things in qiskit.org. It would be great to have bump soon :)

**Comment by abdonrd** [comment]
@jeffchew more good news!

`@open-wc/lit-helpers@0.5.0` just released with `spread`, `spreadEvents`, and `spreadProps` directives!
https://github.com/open-wc/open-wc/releases/tag/%40open-wc/lit-helpers%400.5.0

**Comment by abdonrd** [comment]
To update this issue a bit, it is being worked on!

- https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9905
- https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9958

**Comment by abdonrd** [comment]
Another related issue:
- https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9750

**Comment by kr05** [comment]
Just want to say I appreciate so much the constant check-ins from @abdonrd, and much love to everyone on the team for all the work that has gone into building out Carbon. I'm currently using the [lit alpha release](https://www.npmjs.com/package/@carbon/web-components/v/2.0.0-lit-v2-alpha) and for my limited use case it's working perfectly. I haven't tried using the more complex components like data table, but it's probably better to wait a bit in case another alpha version is released.

**Comment by jeffchew** [comment]
> Just want to say I appreciate so much the constant check-ins from @abdonrd, and much love to everyone on the team for all the work that has gone into building out Carbon. I'm currently using the [lit alpha release](https://www.npmjs.com/package/@carbon/web-components/v/2.0.0-lit-v2-alpha) and for my limited use case it's working perfectly. I haven't tried using the more complex components like data table, but it's probably better to wait a bit in case another alpha version is released.

I concur and thank you @abdonrd for staying on top of this (us!). Work is currently in flight to also upgrade Carbon Web Components to Carbon v11, which in of itself will also bring some pretty great upgrades there. From there, we should be seeing an initial v2.0.0 beta (and release candidates).

Apologies for the radio silence on this and the changing of dates, @kennylam and team will provide an updated timeline hopefully soon, but we also plan on including a sync of features between Carbon Web Components and Carbon React shortly after, so the team definitely has its work cut out for it!

cc: @annawen1 @emyarod @IgnacioBecerra @ariellalgilmore @ljcarot @jeanservaas

**Comment by abdonrd** [comment]
Thanks @jeffchew! I hope it will be soon! 🤞

**Comment by abdonrd** [comment]
Related PR about the update to Carbon v11:

- https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10196

**Comment by abdonrd** [comment]
@jeffchew closed with the new release?

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/releases/tag/%40carbon/web-components%402.0.0
