### ISSUE TITLE
[Lightbox media viewer]: Change the functional specifications to include carousel functionality

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6371]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Lightbox media viewer` functional specs 

> so that I can:
so that I can properly code the `Lightbox media viewer` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#6314 )**
 - The designs were done by Kirby Evans.  
 - Design specs for the proposed solution can be found here:

[PDF](https://ibm.box.com/s/1gmz28s04qf17y0fvpky4csukumcomfw)
[Sketch file](https://ibm.box.com/s/1bv9s86wxo63exuend5ts9y1bdmvbsgs)

#### Acceptance criteria
 - [ ] Documented `Lightbox media viewer` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by photodow** [comment]
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lightbox-media-viewer

**Comment by shixiedesign** [comment]
I know we usually present the FS to devs during a Epic refinement but I think we have a few more changes to Lightbox coming up. Suggest we present all the changes to lightbox together when those are done too. So closing this for now so the Milestone can be closed. I will make a note for the next Engineering refinement meeting.
