### ISSUE TITLE
[Cloud Masthead Container]: Expose a new authentication checking method for the docs/console team - DDS Consulting

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#6374]
### The problem
- The current `<dds-cloud-masthead-container>` is using the cookies to check whether the login status of `could.ibm.com` returns `true` or `false`.
- This method works great for marketing pages, however, for the integration of the new Cloud WC in the docs/console header, we'll need to expose an authentication fetching method that's in alignment with the doc header.

### The solution
- Expose a new prop/attribute within the `<dds-cloud-masthead-container>` that allows adopter (eg. docs/console) to define the authentication fetching method that's coming from this API (see [link](https://cloud.ibm.com/api/v6/selected-account?profile=true)).
- This checking method should be managed within the `utilities` package and imported within `cloud-masthead-composite`. We want to abstract this authentication class so that it can be leveraged on the global masthead level when it's ready to be implemented.

### Additional information
- API - (see [link](https://cloud.ibm.com/api/v6/selected-account?profile=true))
- Docs/Console authentication fetching method - see [link](https://github.ibm.com/Bluemix/docs-components-react/blob/master/src/components/DocsHeader/DocsHeader.js#L97)

### HC Ticket Tracking
- **Ticket:** https://jsw.ibm.com/browse/HC-1993
- **Assignee:** @huntermacd

**Comment by proeung** [comment]
This work has been assigned to @huntermacd and slated for our 06/15 to 06/22 sprint schedule.

**Comment by RobertaJHahn** [comment]
@proeung Is there are target date for this update to go live.  We need to know which release to put this PR in.

**Comment by proeung** [comment]
@RobertaJHahn This feature is something that's needed for the Docs/Console team for testing purposes and we're not looking to have this in for the 07/07 full release. We're shooting for getting a PR ready by next week and hopefully have the changes merged to master and available to pull down via `canary` for testing.
