### ISSUE TITLE
[Lightbox media viewer with Carousel] web components: DDS Visual QA consulting support for the carousel enhancement

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6376]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com designer

> I need to:
provide Visual QA consulting support to a non-DDS designer of the `component name`

> so that I can:
ensure the component is developed to the design specs for adopters to use when building ibm.com web pages

#### Additional information

- **See the Epic for the Design and Functional specs information**
- Designer will be added as a reviewer to the Pull Request.  Visual QA reviewer will be notified by Github when review is needed.
 - [Creating a QA bug](https://ibm.ent.box.com/notes/603242247385)
- Web Components Dev Issue (#6372 )
- Storybook link provided by engineer in comments below

 #### Tasks
Ensure the `Lightbox media viewer` component has been tested and reviewed by design + dev.

----
- Developed by DDS team
- Designer:  Kirby Evans
- Visual QA will be done by Kirby.

#### Acceptance criteria
- [ ] Pattern is reviewed by designer and design defects are identified
- [ ] New issues are opened to log individual defects
- [ ] Screenshots of as-is and to-be design should be added to the issue when needed
- [ ] Developer associated with building the pattern is assigned to the new issues
- [ ] Appropriate labels are added to the issue  eg.  bug, dev

**Comment by proeung** [comment]
Accessibility concern from @oliviaflory as part of this PR discussion thread - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8757#issuecomment-1126394063

> Keyboard navigation
> I'd love to get some accessibility representation to look at the keyboard navigation for screen readers. I was able to access everything in the first page, but switching between the other carousel pages and accessing that content was more challenging. I'm probably not the best person to be testing/making recommendations for that behavior though!

Whoever picks up this issue, please conduct full accessibility testing and open follow-up tickets if any issue arises.

cc: @kennylam
