### ISSUE TITLE
[Lightbox media viewer]: change the functional specifications to include the layout updates

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6382]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Lightbox media viewer` functional specs 

> so that I can:
so that I can properly code the `Lighthouse media viewer` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#6328 )**
 - Design was done by Kirby Evans
Design specs for the proposed solution can be found here:

[PDF](https://ibm.box.com/s/1gmz28s04qf17y0fvpky4csukumcomfw)
[Sketch file](https://ibm.box.com/s/1bv9s86wxo63exuend5ts9y1bdmvbsgs)

Preview of specs for Lightbox media viewer

![image](https://user-images.githubusercontent.com/77290329/121388709-b3a17380-c919-11eb-80fc-5ea117f21440.png)
![image](https://user-images.githubusercontent.com/77290329/121388791-c5831680-c919-11eb-8eee-f63dc998589f.png)

#### Acceptance criteria
 - [ ] Documented `Lightbox media viewer` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by photodow** [comment]
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lightbox-media-viewer
