### ISSUE TITLE
[Lightbox media viewer] Web Component & React: Include the layout updates  

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6386]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `Lightbox media viewer`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic for the Design and Functional specs information**
- Design specs done by Kirby Evans
- Functional specs:  https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lightbox-media-viewer#2-viewer
- Web Components Visual QA testing issue (#6388 )
- Web Components Prod QA testing issue (#6401 )

----
Design specs for the proposed solution can be found here:

[PDF](https://ibm.box.com/s/1gmz28s04qf17y0fvpky4csukumcomfw)
[Sketch file](https://ibm.box.com/s/1bv9s86wxo63exuend5ts9y1bdmvbsgs)

Preview of specs for Lightbox media viewer

![image](https://user-images.githubusercontent.com/77290329/121388709-b3a17380-c919-11eb-80fc-5ea117f21440.png)
![image](https://user-images.githubusercontent.com/77290329/121388791-c5831680-c919-11eb-8eee-f63dc998589f.png)

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] Include the DDS design consultant in the Pull Request for the Visual QA
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by jeffchew** [comment]
Team has discussed and will do both Web Components and React at the same time. Will close the React story.

**Comment by shixiedesign** [comment]
Func spec done. 
@RobertaJHahn this is ready for Monday's engineering refinement. Looks like James is not feeling well the past few days, so I can present the specs.
