### ISSUE TITLE
[Background media] New component - DDS consulting

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6394]
## Overview
The `Background media` is used behind content to display image or video, standardizing the **gradient overlay** and **mobile stacking behavior**. MVP is image for now, and later should be enhanced to support video.

This component is used in **Card section offset**.

## Functional spec: 
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Background-media

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/1d83c702-85e4-4ae5-8664-43d2c02f3e75)

----
- Dev by DDS
- HC Engineer assigned:  Putra Bonaccorsi

**Comment by RobertaJHahn** [comment]
@ariellalgilmore I have not set this issue up for poker planning since you have been assigned and should probably be in the best position to provide the estimate.  This component has been assigned to the July 7 sprint because the content block with L-shaped card group (#6241 ) needs it.

cc:  @jeffchew @shixiedesign

**Comment by proeung** [comment]
@RobertaJHahn Here's the JIRA ticket (https://jsw.ibm.com/browse/HC-2014) that we're using to track the contribution work on our end.

**Comment by proeung** [comment]
@RobertaJHahn @ariellalgilmore We have new work coming in from the HC business that requires @ddollive's time. I'm going to take on the work in this ticket so that we can still try to get this component in for the late July release.

**Comment by RobertaJHahn** [comment]
@proeung Thanks for letting us know.  

cc:  @ariellalgilmore
