### ISSUE TITLE
[Locale selector] Design clean up to address inconsistencies 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6395]
Locale selector is one of the "first borns" and contains some inconsistencies compared to the standard the team later established. Example of inconsistency: 

- Not using card group
- Search bar using expressive 
- Label text size 

The clean up design should be followed by 
1. react & web component dev issues 
2. QA issues
3 Website image update (avoiding content update right now until content template) 

Link to Box folder [locale selector v2.0](https://ibm.ent.box.com/folder/82255256134?s=nwy0fyiw6mu3qwd3p882pnqmit93rfa5)

**Comment by RobertaJHahn** [comment]
convert to an epic:  Check with Shixie on any design issue, WC & React, all QA issues & website
