### ISSUE TITLE
Allow declarative overriding of the default event handlers for the masthead search input

### ISSUE THREAD

**Issue by ncheaz** [carbon-design-system/carbon-for-ibm-dotcom#640]
### The problem
The ibm.com search page needs the masthead search components to be customizable so that it can integrate into the workflow of the search app

### The solution
Start with allowing declarative overriding of all event handlers on the mastehead state change, and probably the some events on the masthead search input.  Plus allow overriding values for endpoints, and other fixed properties.

### Additional information
This is needed only for the ibm.com search page https://www.ibm.com/search?lang=en&cc=us

**Comment by jeffchew** [comment]
@ncheaz please provide more details regarding what events need to be exposed in the Masthead.

**Comment by RobertaJHahn** [comment]
@ncheaz Can you arrange a call so that we can get to the details.

**Comment by RobertaJHahn** [comment]
This issue has been placed in the Icebox pipeline, due to the Web Simplification priorities.

**Comment by RobertaJHahn** [comment]
Already handled.  Closing
