### ISSUE TITLE
[Masthead] Web components storybook demo clean up

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6407]
## Detailed description

> Describe in detail the issue you're having.

Masthead storybook clean up, React issue #6409 

### Default
Knobs:
- [x] no platform knob, default global nav should not enable a platform name

Storybook example is good as-is, update knobs per above
![masthead-global](https://user-images.githubusercontent.com/45692622/124154336-666d7900-da63-11eb-8ac0-4bf4ac7190a7.jpg)

### ~With custom navigation~ hide/remove story
- [x] We are proposing to hide this story, in most cases, IA guild does not recommend teams have custom navigation within the L0. But we do not want to deprecate yet as it would be a breaking change.
- [ ] ~no platform knob, default global nav should not enable a platform name~
- [ ] ~Label should be sentence case: `With custom navigation` (not initial caps)~
- [ ] ~Custom navigation should **not** have mega menu styling, remove all mega menu styling and use dropdown. May have to change data sets?~

![Screen Shot 2021-06-17 at 3 50 31 PM](https://user-images.githubusercontent.com/45692622/122464757-3a42fa00-cf85-11eb-8ef7-452c471f37c1.png)
![Screen Shot 2021-06-17 at 3 51 02 PM](https://user-images.githubusercontent.com/45692622/122464759-3adb9080-cf85-11eb-9e5d-e4776009036f.png)

### Search Open Onload
- [x] label should be in sentence case, not initial caps `Search open onload`
- [x] hide platform knob

Storybook demo proposal:
![masthead-Search-open-onload](https://user-images.githubusercontent.com/45692622/124154819-dbd94980-da63-11eb-8411-21efd8cc2e2c.jpg)

### With Platform
- [x] label should be in sentence case, not initial caps `With platform`
- [ ] ~All nav items within the With platform story should **not** have mega menu styling, remove all mega menu styling and use dropdown. May have to swap data sets?~
- [x] Remove all links from With platform story other than the Platform
- [x] Update "Cloud" to "Platform"
![Screen Shot 2021-06-17 at 4 01 35 PM](https://user-images.githubusercontent.com/45692622/122464901-5fd00380-cf85-11eb-80b3-5924dca29c80.png)

Story book demo proposal: 
![masthead-with-platform](https://user-images.githubusercontent.com/45692622/124155222-425e6780-da64-11eb-9dd4-48e089eb8b1a.jpg)

### With L1
- [x] update L1 nav content to the example shown in the image below, red italic indicates dropdown items. Reference [Analytics page](https://www.ibm.com/analytics?lnk=hpmps_buda) for content. Note: ignore "Services" dropdown on the live page.

Storybook demo proposal:
![masthead-with-L1](https://user-images.githubusercontent.com/45692622/124155648-b6990b00-da64-11eb-991f-39f248eee3ab.jpg)

### With Alternate Logo And Tool Tip
- [x] Label should be sentence case: `With alternate logo and tool tip` (not initial caps)

Storybook demo good as-is

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

storybook clean up

> Is this issue related to a specific component?

Masthead demo & variants

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

Chrome

> What version of Carbon for IBM.com are you using?

[WC](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-masthead--default)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Additional information

Reasoning for not using mega menu in anything other than Default global nav: the IA team has not come to a conclusion on whether teams can customize their own mega menus. We should not show mixing customized labels with the global nav labels & data or show the global nav with a platform. 

Cloud is the only other team that has a customized nav & mega menu approval.

**Comment by RobertaJHahn** [comment]
engineering needs the content from design before they can make the changes.  Olivia will talk to Shixie about when to schedule the design work.  She may be able to work on it this sprint.

**Comment by oliviaflory** [comment]
@shixiedesign I updated the tasks above and included the images of the storybook demo for masthead that we reviewed in Design review today so you can take another look.

**Comment by oliviaflory** [comment]
Content updates added to the task description above, reviewed and approved by @shixiedesign. 

@RobertaJHahn this is ready for scheduling

**Comment by shixiedesign** [comment]
Hi @RobertaJHahn @oliviaflory! Sorry for not seeing this one earlier - yes the issue description looks good!
