### ISSUE TITLE
[Masthead] React storybook demo clean up

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6409]
## Detailed description

Masthead storybook clean up, Web components issue: #6407 
**_Content updates are documented in the web components issue #6407_** 

> Describe in detail the issue you're having.

### Default
Knobs:
- [x] no platform knob, default global nav should not enable a platform name
- [x] remove "Other" tab

### With custom navigation
- [x] no platform knob, default global nav should not enable a platform name
- [x] Label should be sentence case: `With custom navigation` (not initial caps)

### Search Open Onload
- [x] label should be in sentence case, not initial caps `Search open onload`

### With Platform
- [x] label should be in sentence case, not initial caps `With platform`

### With Alternate Logo And Tool Tip
- [x] Label should be sentence case: `With alternate logo and tool tip` (not initial caps)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

storybook clean up

> Is this issue related to a specific component?

Masthead demo & variants

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

Chrome

> What version of Carbon for IBM.com are you using?

[React](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--default)

**Comment by RobertaJHahn** [comment]
engineering needs the content from design before they can make the changes.  Olivia will talk to Shixie about when to schedule the design work.  She may be able to work on it this sprint.

**Comment by oliviaflory** [comment]
@RobertaJHahn content updates are documented in the web components issue #6407. @shixiedesign signed off on the updates in that issue so this is ready for scheduling.
