### ISSUE TITLE
[Masthead with L1] dropdown color React

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6410]
## Detailed description

> Describe in detail the issue you're having.

The dropdown color in the Masthead with L1 in the React package isn't the right color, I think this may be a carry over from the old gray L1. 

Wasn't sure if this was a styles package since the two storybooks are showing different styling?

- [ ] Update L1 dropdown color to match Web Components package. Assuming it should be `$ui-background` token, unless it's hard coded to only be in white theme. Would appreciate whoever picks this up to let me know so I can make sure our specs are aligned.

**React**
![Screen Shot 2021-06-17 at 4 37 12 PM](https://user-images.githubusercontent.com/45692622/122471090-d15f8000-cf8c-11eb-8919-9ab6684a8f1d.png)

**Web components**
![Screen Shot 2021-06-17 at 4 37 38 PM](https://user-images.githubusercontent.com/45692622/122471101-d6243400-cf8c-11eb-980a-9a2cffa6f8d7.png)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

Masthead with L1 in React

> What did you expect to happen? What happened instead? What would you like to
> see changed?

background color of dropdown should not be gray, should be white 

> What browser are you working in?

Chrome

> What version of Carbon for IBM.com are you using?

[React](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--with-l-1)

**Comment by kennylam** [comment]
@oliviaflory Web components was using `$ui-02`, which is the same as `$ui-background` (both are `#fff`). All `L1` menu items have been changed to use `$ui-background` for consistency.
