### ISSUE TITLE
Content Item horizontal with media whitespace to right of video

### ISSUE THREAD

**Issue by gregj0** [carbon-design-system/carbon-for-ibm-dotcom#6415]
## Detailed description

> Describe in detail the issue you're having.
When using Content Item Horizontal with media in AEM the video image is not expanding to fill the width of the grid.  An image is better but I think a width:100% is not getting carried forward and will fix the issue.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Content item horizontal with media

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Here is the an example of the issue.  Note the purple area to the right of the image when I highlight the div with bx--content-item-horizontal__row.
    
![image](https://user-images.githubusercontent.com/23464162/122580789-53e74e80-d024-11eb-9d69-87a310c8d3f1.png)

If I add width: 100% directly in the browser here, it fills in that space with the image

`.bx--content-item-horizontal__row {
    display: grid;
    column-gap: 2rem;
}`

If I got to storybook https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-content-item-horizontal--with-media it behaves better but still does not have that width: 100%

There is a width: 100% here for the content item horizontal  without media but I do not think it is getting carried forward with the media.  https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/ed414d195c1f91065e375845716557d7db4173d1/packages/styles/scss/components/content-item-horizontal/_content-item-horizontal.scss#L112

> What browser are you working in?
Chrome

> What version of Carbon for IBM.com are you using?

`    "@carbon/ibmdotcom-styles": "1.20.0-rc.1",
    "@carbon/ibmdotcom-web-components": "1.5.0-rc.1",
    "@carbon/type": "^10.18.0",
`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

This is part of the solutions template for AEM

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by oliviaflory** [comment]
Hi @gregj0 I believe the Content item horizontal with media is behaving as expected according to the design specs. 

Within the [design spec file](https://ibm.ent.box.com/folder/112262788897?s=911wx1w694l21iazjcw9powshyxmk0du) you can see at the max breakpoint there is a `max width` of 640px for any media and the last column is left blank. This might be why you are seeing extra space to the right of the media. 

**Max breakpoint design spec**
<img width="1035" alt="Screen Shot 2021-06-21 at 9 42 57 AM" src="https://user-images.githubusercontent.com/45692622/122772457-660bfb80-d275-11eb-8979-57dc2bb30e94.png">

**Max breakpoint in storybook**
![Screen Shot 2021-06-21 at 9 47 33 AM](https://user-images.githubusercontent.com/45692622/122772818-c00cc100-d275-11eb-98f8-b52a6007ac76.png)


At the xl breakpoint, the media is spanning 8 columns and goes to the edge of the browser

**Xl breakpoint design spec**
<img width="610" alt="Screen Shot 2021-06-21 at 9 49 54 AM" src="https://user-images.githubusercontent.com/45692622/122773185-1da10d80-d276-11eb-9ae8-40c721bca38f.png">


**Xl breakpoint in storybook**
![Screen Shot 2021-06-21 at 9 47 18 AM](https://user-images.githubusercontent.com/45692622/122772906-d6b31800-d275-11eb-8433-5478da614e52.png)

---
From the screen shot you provided I couldn't tell which breakpoint you were viewing, let us know if the gap is happening below the `max breakpoint of 1584px` and if this answers your question, thanks!

**Comment by gregj0** [comment]
Here is two pages, you should be able to access using it.
Using the image it does match what you have https://dev-publish.np-roks.cms.cis.ibm.net/gjtest/solution-item-horiz1

![image](https://user-images.githubusercontent.com/23464162/122816121-535ceb00-d2a4-11eb-8358-41a2d4369dcd.png)

But with a video is it does not https://dev-publish.np-roks.cms.cis.ibm.net/gjtest/solution-item-horiz2 
![image](https://user-images.githubusercontent.com/23464162/122816259-7be4e500-d2a4-11eb-9579-315e17f3e440.png)

Christian had looked at it and suggested that it needed the width 100% and maybe that is not right.  But it does seem to fix the video and have no impact on the image

**Comment by annawen1** [comment]
In the example page links shared above, the `content-item-horizontal-media` component is used within `content-group-horizontal` which could be causing the layout for the video variation to look weird

**Comment by gregj0** [comment]
That's how our design team wants to use it on the solutions page.  And while I cannot create a page on the server, with a content-item-horizontal-media component outside content-group-horizontal, I can locally and it behaves the same.  This page might demonstrate it better as it has one with an image and another with video. https://dev-publish.np-roks.cms.cis.ibm.net/gjtest/solution-item-horiz-both  They match in size on large breakpoint but medium is not close.  Here is a similar local page without the content-group-horizontal on medium breakpoint 
![image](https://user-images.githubusercontent.com/23464162/122834560-ceca9680-d2bc-11eb-9572-8228b1089e11.png)

**Comment by annawen1** [comment]
Hey @gregj0, a fix has been merged yesterday and will be part of the web-components 1.6.0 release. You'll be able to text out the fix when we release a release candidate (`1.6.0-rc.0`) some time tomorrow
