### ISSUE TITLE
[Feature card] Web Components:  Feature card large & medium wrong stable selector

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#6417]
## Detailed description

In Web Components our large & medium size feature card has the wrong stable selector. It is supposed to be:
`dds--feature-card` (medium) and `dds--feature-card-large` (large)

Correctly in react:  https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/react/src/components/FeatureCard/FeatureCard.js#L41-L43

**Comment by emyarod** [comment]
maybe relevant: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/web-components/docs/stable-selectors.md#data-autoid-support-for-partial-backward-compatibility

I can update the feature card stable selector to be `dds--feature-card` but it won't be dynamic based on the card size. I believe if a stable selector for the web component is required, checking the tag name and the value of the `size` attribute should help determine whether or not it is a medium or large feature card

**Comment by RobertaJHahn** [comment]
@jeffchew I am not sure who should determine the correct implementation strategy for this bug.  Can you take a look and let me know if we have to include in one of the engineering meetings?

cc:  @emyarod

**Comment by jeffchew** [comment]
Speaking with @emyarod , the feature card appears to be the only component with dynamic auto-id. In React, the `feature-card-large` selector isn't even documented in Storybook docs, though is unknown whether if teams are actively using that stable selector.

This might be a huddle topic to discuss first, to see if we should stick with static stable selectors and do something about this particular case.
