### ISSUE TITLE
[Masthead with L1] expose the L1 platform name on small and medium breakpoints

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6418]
### The problem

The L1 is hidden on medium and small breakpoints, hiding the platform/ecosystem name and the user may not have a sense of where they are within IBM.com.

![L1-WC-Jun-18-2021 09-31-13.gif](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/7b596feb-ec20-46b4-be53-88c7528b8982)

### The solution
Expose the L1 on medium and small breakpoints and only display the platform/ecosystem name. The Northstar L1 does this today. 
Visual specs have been updated, [link to Box folder](https://ibm.ent.box.com/folder/118448193520?s=o0v38tot6t0s9tnr3y3estp4cnxar6vo)

![L1-analytics-Jun-18-2021 09-29-55.gif](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/13e9cdfd-482d-437d-a364-17747452e56b)

![Screen Shot 2021-06-18 at 9.34.45 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/9cdb0abb-5cc0-409f-9142-b6375d37876f)

### Additional information
Notes from #5985 masthead clean up:
_Reviewed questions about L1 behavior with Shixie, Lila and James 5/25_
_**Decisions:**_
- _L1 ecosystem name / topic should be visible on medium & small breakpoints_
- _Keep options for selected state of ecosystem name on medium & small breakpoints_
- _Within the hamburger menu, the ecosystem name will only be visible on the first level of navigation._

##

**Comment by RobertaJHahn** [comment]
To be sized and implementation discussion in the engineering issues refinement.
