### ISSUE TITLE
[Feature card] Storybook alignment is wrong

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#6422]
Storybook has feature card stories that are currently centered, they need to be left-aligned.

###### as-is
![image](https://user-images.githubusercontent.com/3793636/122619162-6cbc2800-d055-11eb-96da-09384d5c9cab.png)

###### should be
![image](https://user-images.githubusercontent.com/3793636/122619255-a3923e00-d055-11eb-936e-e6ea5fde57a7.png)

**Comment by RobertaJHahn** [comment]
Closing.  Shixie will create an issue for all of the storybook alignment issues.
