### ISSUE TITLE
[Back to top] storybook example has a background in dark theme 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6423]
Noticed some odd styling in the Back to top storybook story. My guess is these are storybook example issues and not related to the component. 

### Web components
When switched to theme Gray 100 and Gray 90, the page's content area is showing a lighter background, and a little box above & under ToC. 

Gray 90 theme, showing gray70 background

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/331119f3-7a1e-4f70-ba59-e100adf19ec9)

Gray 100 theme, showing gray 80 background 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/a36ca398-bdde-489f-a294-46706e003190)

### React wrapper 

1. Gray 90 and Gray 100 theme showing background in page content area
2. CTA section bg appears locked to Gray 10. Background not changing when theme switches. Expecting `$ui-01` background
3. `Content block(group) horizontal` bottom rule is not changing color when theme switches. Expecting `$ui-04` rule color

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/0808aafc-b77b-48ee-ba1b-331cc49eead9)

**Comment by RobertaJHahn** [comment]
The styles were updated in the Back to Top.  This problem is fixed in PR (#6383)
