### ISSUE TITLE
Sketch File

### ISSUE THREAD

**Issue by designnatix** [carbon-design-system/carbon-for-ibm-dotcom#6430]
Is the Sketch file for Carbon for IBM.com available to non-IBMers?

If so that would be great. 

Thank you

**Comment by oliviaflory** [comment]
Hi @designnatix,

We do not have a Sketch file for non-IBMers at this time, but we are currently working on improving our tooling and hope to have something to share soon.

For now, you can create all the Carbon for IBM.com components with the Carbon and IBM Design Language [Sketch kits](https://carbondesignsystem.com/designing/kits/sketch/) as they have all the type and component symbols we use in the Carbon for IBM.com package.

**Comment by ljcarot** [comment]
@designnatix - Can you explain your role in working with Carbon for ibmdotcom?  Might help to determine other options for you. Thx

**Comment by designnatix** [comment]
Hello, @ljcarot I'm with CloudNatix. We are a startup in the infrastructure space that is using Carbon for our application and now we would like to build our company website with Carbon for IBM.com. We are big fans of Carbon! Thanks for your message.

**Comment by ljcarot** [comment]
@designnatix At this time, the carbon for ibm.com sketch files are not available outside of IBM.  As Olivia mentioned above, you can get from carbondesignsystem.com almost everything you need for website development too.  Good luck in your startup!
