### ISSUE TITLE
Design explorations for IBM.com cookie preferences - Intern exercise

### ISSUE THREAD

**Issue by maryjiang-ibm** [carbon-design-system/carbon-for-ibm-dotcom#6431]
### Objective
Create additional design explorations for IBM.com cookie preferences, building upon the ongoing redesign by the Commons team. This is a learning exercise to familiarize DGC interns with the dotcom design system. 

### Tasks
- Analyze (i.e. collect screenshots) how popular websites handle cookies 
- Create design explorations and share for review

### Acceptance criteria
- [ ] Sketch file of additional explorations (optional visual spec)

### Additional Information
Design spec:
[cookie_notes_from_shixie.txt](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/6687956/cookie_notes_from_shixie.txt)

Existing designs:
[component--cookies--visual-spec.sketch.zip](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/6687904/component--cookies--visual-spec.sketch.zip)

[Current experience on IBM.com] Screen 1 - Personalize preferences
![image](https://user-images.githubusercontent.com/84742894/122790387-44674000-d286-11eb-9a4e-6a056513dd70.png)

[Current experience on IBM.com] Screen 2 - Personalize preferences (ft. advanced settings)
![image](https://user-images.githubusercontent.com/84742894/122789965-d7ec4100-d285-11eb-8cea-2111edb28a97.png)

**Comment by shixiedesign** [comment]
Feel free to join design reviews and huddles if you d like some eyes on any WIP!

**Comment by maryjiang-ibm** [comment]
## Questions on the existing redesign

Playing devils advocate 😈

### 1. Initial banner

1. **Why did legal request 3 buttons** (accept all, proceed with required, manage settings)? Could we replace the "Proceed with required" secondary action with "Manage settings"? To visitors, the distinction between accepting _all_ vs. _required_ cookies is likely fuzzy. 

![image](https://user-images.githubusercontent.com/84742894/123298110-2dbf2400-d4e6-11eb-8169-452859220bf6.png)

### "View and manage cookies" modal screens
1. **Could the info fit in 1 screen?** 2 screens for this seems redundant.
2. **How appropriate is a modal?** The tables to display the cookie details take up a lot of space (possible scroll issues). Perhaps a fullscreen page is appropriate for exploring the advanced details. 

![image](https://user-images.githubusercontent.com/84742894/123299035-1cc2e280-d4e7-11eb-9957-9a02c24c619e.png)

**Comment by shixiedesign** [comment]
Great questions! 

> Why did legal request 3 buttons (accept all, proceed with required, manage settings)? Could we replace the "Proceed with required" secondary action with "Manage settings"? To visitors, the distinction between accepting all vs. required cookies is likely fuzzy.

IBM is trying to be ethical here. By having "Accept required" or "proceed with required", we expose the option of NOT tracking the visitor. Usually sites more concerned with selling you things will hide this button so people will just push "Accept all" and consent to being tracked, and become target for ads. 

>

**Comment by maryjiang-ibm** [comment]
## 🔭 Exploration 1: two-panel modal
### Considerations

- **Relationship between Screen 1 and Screen 2**: If a user checks "Functional" and also goes to "Advanced settings", should the toggles for the functional cookies be on? What if they go back to Screen 1?
- [WIP]

![image](https://user-images.githubusercontent.com/84742894/123863127-2f7a5480-d8f7-11eb-9442-8c5e66de19fe.png)

**Comment by maryjiang-ibm** [comment]
## 🔭 Exploration 2: Full-pager

![image](https://user-images.githubusercontent.com/84742894/124183804-bb6eb680-da86-11eb-84a7-051255dee39e.png)

**Comment by maryjiang-ibm** [comment]
[
[cookies-explorations-june2020.zip](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/6756546/cookies-explorations-june2020.zip)
](url)

Sketch file of first two explorations and screenshots of cookie consent experiences on other sites.

**Comment by maryjiang-ibm** [comment]
## 🔭 Exploration 3: Single-panel modal
![image](https://user-images.githubusercontent.com/84742894/124939699-57dd0f80-dfd7-11eb-8509-be86953acb0a.png)
