### ISSUE TITLE
[Universal banner] design, dev & usage documentation 

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#6436]
## Task

A universal is **the only component allowed to show up above Dotcom masthead**, and should be used for exclusively global and critical announcements. 

A prototype universal banner has been built for THINK 2021 in Carbon. And previously v18's universal banner has been used for to communicate other global events / announcements such as  COVID and THINK. As a design system, we need to add it to the library as a reusable component, complete with:

1. a cleaned up design
2. updated implementation
3. usage documentation on our website

### Content 

A universal banner could need the following content. Some fields might be optional. 

 - heading
 - optional subheading
 - media (image, video, loop)
 - CTA text (button or link)

### Examples

**THINK 2021**
NPM package: 
![image](https://user-images.githubusercontent.com/15144993/122942124-f57fe000-d343-11eb-9a1a-713ed87f8493.png)

**THINK 2020**
![image](https://user-images.githubusercontent.com/30183447/82491057-21ca8c80-9ab2-11ea-854f-51f981de5c3b.png)

**COVID-19 Response**
![image](https://user-images.githubusercontent.com/30183447/82491216-5b9b9300-9ab2-11ea-900d-b65253ec706d.png)

#### Additional Information
- [Final design and design specs](https://ibm.ent.box.com/folder/142303458357?s=fas5qv5zrscudr63y85g28v0k657p83u)
- [Functional specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Universal-banner)

**Comment by RobertaJHahn** [comment]
Colsing, no longer relevant

**Comment by RobertaJHahn** [comment]
![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/57c253fe-7968-4f79-b61b-4e97935e52f5)

Reopening the issue based on Shixie's comments.

**Comment by RobertaJHahn** [comment]
Convert to an epic, design research, design exploration, func specs, website and the dev & QA issues.
