### ISSUE TITLE
Locale change banner design studies

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#6437]
### User story
As a user of IBM.com, I would like to know when I am forwarded to a page that has a different locale setting than my preferences or the previous pages.

### Notes
- This story is based on SEO's recommendation to not use the popup for locale change.
- The existing banner design seems to be problematic in that users either miss it or are not helped by it.
- The original epic from the Agile board: https://github.com/carbon-design-system/ibm-dotcom-library/issues/859

**Comment by shixiedesign** [comment]
Moved over from Ideation repo for record tracking. 
Here are the issues attached previously to this epic: 
- https://app.zenhub.com/workspace/o/carbon-design-system/digital-design-ideation/issues/22
- https://app.zenhub.com/workspace/o/carbon-design-system/digital-design-ideation/issues/24
- https://app.zenhub.com/workspace/o/carbon-design-system/digital-design-ideation/issues/29
- https://app.zenhub.com/workspace/o/carbon-design-system/digital-design-ideation/issues/27
- https://app.zenhub.com/workspace/o/carbon-design-system/digital-design-ideation/issues/23
- https://app.zenhub.com/workspace/o/carbon-design-system/digital-design-ideation/issues/25
- https://app.zenhub.com/workspace/o/carbon-design-system/digital-design-ideation/issues/28

**Comment by shixiedesign** [comment]
Deprecating locale change banner after google analytics reveal most people simply stay on current locale page. So the hypothesis of the banner that people need to change locale is negative. This banner is not needed.
