### ISSUE TITLE
Website: "Designing" page needs to be broken out with more detailed getting started instructions

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6445]
Add information to [Designing](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/designing), potentially turning it into a section containing several pages. The goal is to clearly present these information below that are currently disorganized or missing: 

- Workflow instructions "how to design for IBM.com?"
- **Link to Boxfolder for component sketchfiles** & folder structure 
- Brief explanation of our relationship with Carbon and IDL
- Upstream sketch kits
- Declare the accessibility standards we follow

**Comment by janchild** [comment]
![image](https://user-images.githubusercontent.com/44503588/124025481-1a182f80-d9b6-11eb-8db0-7a4db7fcb0b7.png)

**Comment by shixiedesign** [comment]
Moved above comment to the other "designing" page ticket. Closing this one for now.
