### ISSUE TITLE
[Lead space]: Create video & play-pause button design specs 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6452]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the `[Lead space]` design specs

> so that I can:
correctly create / change the `[Lead space]` component 

#### Additional Information
- Carbon for ibm.com epic (#6054 )

#### Acceptance Criteria
- [x] A Sketch file is created or updated with the `[Lead space]` design and specs
- [x] Create a Box folder for the `[Lead space]` (if not already there)
- [ ] The design specs and pdf version are added to the Box folder 
- [ ] Add Box folder link to the website content if it exists

**Comment by DragosRistici** [comment]
Added the visual specs [in this folder](https://ibm.box.com/s/9xlrnmzph7jcxddygfybavq43hdzljt1).
