### ISSUE TITLE
[CTA Block - with Link list] Web Components: grid misaligned on all breakpoints

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#6466]
#### Component is out of grid for all breakpoints
<img width="505" alt="Screenshot 2021-06-24 at 16 51 47" src="https://user-images.githubusercontent.com/48327647/123275114-bd77c900-d50c-11eb-884a-662558bd3e6f.png">
<img width="756" alt="Screenshot 2021-06-24 at 16 51 38" src="https://user-images.githubusercontent.com/48327647/123275123-bf418c80-d50c-11eb-84f3-fb63862014a4.png">
<img width="1368" alt="Screenshot 2021-06-24 at 16 54 18" src="https://user-images.githubusercontent.com/48327647/123275263-d84a3d80-d50c-11eb-9e55-9accca08182f.png">

**Comment by shixiedesign** [comment]
Actually this issue is a duplicate and is currently in PR under review: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6330
