### ISSUE TITLE
[Masthead, mega menu] `md` breakpoint clicking outside the menu should close menu

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6483]
In both web comp & react, `md` breakpoint.

**Expecting:** clicking outside the menu on page with an overlay should close the menu. 

**Currently:** clicking outside the menu on the overlaid page doesn't do anything.

![Jun-25-2021 22-09-47.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/f9e7b0d3-6907-4b16-868b-ae14c7272a81)

**Comment by RobertaJHahn** [comment]
Closing.  Consolidated this information into issue (#6676)
