### ISSUE TITLE
Dotcom shell styles issue with UI shell

### ISSUE THREAD

**Issue by KunalSolanke** [carbon-design-system/carbon-for-ibm-dotcom#6492]
Hello,
this is a styles issue  with one of the packages mentioned below .
I am using two components from following libraries:
carbon-components-react : UI Shell
ibmdotm-com:Dotcom Shell

when I import styles from the dotcom shell,styles of ui shell component gets overwritten and its doesn't look like a shell at all.
Given these are third party styles I can't  import them with module.css/scss or I am not aware such a way except  configuring webpack

here is my styles files
```css
$feature-flags: (
  grid-columns-16: true,
);
@import "@carbon/ibm-cloud-cognitive/css/index.min.css";
@import "@carbon/ibmdotcom-styles/scss/components/dotcom-shell/dotcom-shell";
@import "carbon-components/scss/globals/scss/styles.scss";


@import "@carbon/type/scss/font-face/mono";
@import "@carbon/type/scss/font-face/sans";
@include carbon--font-face-mono();
@include carbon--font-face-sans();

@import "@carbon/ibmdotcom-styles/scss/components/card-group/card-group";
```
Here is how the UI shell looks after importing dotcom shell styles
[
![Screenshot from 2021-06-29 01-13-19](https://user-images.githubusercontent.com/58597818/123694677-3feaea80-d877-11eb-887b-3f1288ffdb11.png)
](url)

**Comment by kennylam** [comment]
@KunalSolanke The `DotcomShell` is a themed/modified version of Carbon's UI Shell – you will get conflicts. We suggest you do not use them on the same page.

**Comment by KunalSolanke** [comment]
Oh, I guess then I won't be able to use one of them in a react app,that's too bad.Thanks for your help .

**Comment by kennylam** [comment]
> Is cdn available for ibm dot com

@KunalSolanke Yep! However, currently they are only available for our web components package. You can read more about using them [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/master/packages/web-components#cdn-bundles).
