### ISSUE TITLE
[Masthead megamenu] – React – Profile menu provokes an issue for the top nav menu items

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#6495]
## Steps to reproduce the issue

1. Click on `dds-masthead-profile`
2. Click any other `dds-megamenu-top-nav-menu` item
3. Switch between `dds-megamenu-top-nav-menu` items

You will see the expanded sub-menus for the top nav menu items on top of each other. 

## Additional information

https://user-images.githubusercontent.com/48327647/123789957-6d22b180-d8e6-11eb-9cd6-7cef62288ab0.mov

**Comment by kennylam** [comment]
@DragosRistici This issue seems to be coming from Carbon core.

https://codesandbox.io/s/angry-davinci-4mw5x

@jeffchew @RobertaJHahn @ljcarot Since this is affecting production, do we want to try and bandaid this fix until Carbon provides a solution?

**Comment by RobertaJHahn** [comment]
Decision was made in the July 15 stand-up not to fix this issue in our code, but wait for the fix in Carbon.

**Comment by RobertaJHahn** [comment]
Not stale. Waiting for Carbon fix.
