### ISSUE TITLE
[Card link] and [Tabs extended] changes to support AEM Geo home pages 

### ISSUE THREAD

**Issue by skuruvil** [carbon-design-system/carbon-for-ibm-dotcom#6501]
### The problem
One of the templates that have been prioritized is the IBM geo home page. Using https://www.ibm.com/us-en?ar=1  as a reference, one of the components on the page is essentially a list of links that allow users to access different portions of the site. What we want to use going forward is basically a full-width link list with tabs

### The solution
Created this new layout component design using variants of existing components Tabs extended vertical, Card link, and Content-group (for heading) as a baseline. This component is going to be used in IBM geo home page design.

https://ibm.ent.box.com/folder/140172923780

### Additional information

Content model: https://ibm.box.com/s/2d9wyvho8ue2kgx3sszvjq7103jcf7ln

 - Adding vertical tabs and a modified card link
 - Hybric Cloud Jira ticket link:  https://jsw.ibm.com/browse/HC-2066
 - [Card link functional specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-link)
 - [Tabs extended functional specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Tabs-extended)

**Examples from design spec:**

<img width="1193" alt="Screenshot 2021-06-29 at 7 17 46 PM" src="https://user-images.githubusercontent.com/71765369/123809037-e33b0e80-d90e-11eb-8ea6-bf3be765b14d.png">
<img width="702" alt="Screenshot 2021-06-29 at 7 18 12 PM" src="https://user-images.githubusercontent.com/71765369/123809364-2bf2c780-d90f-11eb-8cfd-59cf6fde59f5.png">
<img width="200" alt="Screenshot 2021-06-29 at 7 18 30 PM" src="https://user-images.githubusercontent.com/71765369/123809424-38772000-d90f-11eb-9d35-809ddfd4190e.png">

**Comment by RobertaJHahn** [comment]
Convert to epic, func specs, dev issues (WC & React Wrapper), all QA & website

**Comment by RobertaJHahn** [comment]
Per 7/12/2021 Slack with Sandeep.  This request is a high priority.  They would like the feature to be included in the Aug 17 release.

**Comment by RobertaJHahn** [comment]
Card link and Tabs extended dev will be  done by HC.

Card LInk WC sizing:  3
Card link React sizing:  set up planning poker

**Comment by proeung** [comment]
@RobertaJHahn Here are the direct links to the JIRA ticket for this work that we're tracking.

[DDS Contribution] Add an optional "Copy" slot to the "Card link" UI Component

- https://jsw.ibm.com/browse/HC-2115

[DDS Contribution] Add a vertical orientation prop to the "Tabs extended" Layout component

- https://jsw.ibm.com/browse/HC-2066

**Comment by RobertaJHahn** [comment]
@mwanberg @shixiedesign PR's are not linked to epics.  They are linked to the design and dev issues.  The Web Components dev issue is (#6614 ).  I have moved this epic from the Review pipeline back into the Prioritized Epics pipeline.

**Comment by RobertaJHahn** [comment]
Closing.  All linked issues are closed.
