### ISSUE TITLE
[Lightbox media viewer] On mobile, video and content is smaller compared to React version

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6509]
## Detailed description

Issue:
On mobile, video and content is smaller compared to React version.

## Additional information

Actual :
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/64553e15-7358-4624-a456-1e6321cc87a9)

Expected:
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/894da79d-a797-4032-97b6-528fbc15112c)

**Comment by emyarod** [comment]
@Praveen-sr I'm not able to replicate this issue on Android, is it iOS specific?

**Comment by Praveen-sr** [comment]
@emyarod Re tested this on both android and iOS, its working as expected now.
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/b1621a58-2d74-484c-9542-989bfb62e729)

**Comment by RobertaJHahn** [comment]
Closing based on Praveen's comments above.
