### ISSUE TITLE
[Video Card] Web Component: Change video card to display video title as Card headline, not card copy

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6518]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `video card`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic for the Design and Functional specs information**
- Web Components Visual QA testing issue (#6521 )
- Web Components Prod QA testing issue (#6524 )

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by jeffchew** [comment]
Going to increase the scope to video player, and the headline in the lightbox with embedded video player.

**Comment by emyarod** [comment]
it looks like this issue may have already been resolved in a previous PR https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5717

**Comment by RobertaJHahn** [comment]
Closing based on Andrew's comments above.
