### ISSUE TITLE
[Image]: Change the functional specifications to include an optional border

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6526]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `image` functional specs 

> so that I can:
so that I can properly code the `image` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#6315 )**
- Designs provided by Kirby Evans.  See epic for details

#### Acceptance criteria
 - [x] Documented `image` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [x] Comment is added with link to functional specs

**Comment by DragosRistici** [comment]
Due to the fact that there are no Annotations yet in the wiki and the border is not a dependency, I've [updated the functional specs](https://ibm.ent.box.com/folder/94834513317?s=zaofzs8ssrfbkgker2lqxyvdnbpxvsly) in the Box folder.
