### ISSUE TITLE
[image] Web Component: Include optional border - DDS Consulting

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6528]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
change the `image`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic for the Design and Functional specs information**
- Web Components Visual QA testing issue (#6531 )
- Web Components Prod QA testing issue (#6533 )

----
- Image's optional border is documented in website already (branch to be merged): https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1112/components/image#border

Visual reference:
<img width="991" alt="Pasted_Image_6_8_21__2_02_PM" src="https://user-images.githubusercontent.com/77290329/121234941-48e13100-c862-11eb-96ef-002ea34e03ab.png">

 - [Functional specs](https://ibm.ent.box.com/folder/94834513317?s=zaofzs8ssrfbkgker2lqxyvdnbpxvsly)

----
- Hybrid Cloud developer:  John Kaeser
- [HC Jira ticket](https://jsw.ibm.com/browse/HC-2154)
- Dev estimate:  
- DDS consultant:  Gui

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by proeung** [comment]
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2154
HC Engineer Assignee: @jkaeser
