### ISSUE TITLE
[Lightbox media viewer]: change the functional specifications to allow for isolated image view on mobile

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6534]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Lightbox media viewer` functional specs 

> so that I can:
so that I can properly code the `lightbox media viewer` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#6329  )**

#### Acceptance criteria
 - [x] Documented `lightbox media viewer` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [x] Comment is added with link to functional specs

**Comment by shixiedesign** [comment]
Moving to next sprint. James pointed out that the feature could be more complicated than expected.

**Comment by RobertaJHahn** [comment]
Moving to icebox.  See comments in the epic (#6329 )
