### ISSUE TITLE
[Universal banner] Functional spec

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6547]
#### Additional information
- There is a known issue related to the MH positioning and scrolling behavior.  This was seen when the Cloud MH was introduced on the [v19a page and the yellow translation banner appears](https://www.ibm.com/sg-en/cloud/application-modernization).  This information is also captured in the linked FR (#7216)
- This behavior should be resolved in the Universal banner designs and func specs.

**Comment by photodow** [comment]
[Here are the designs](https://ibm.box.com/s/fas5qv5zrscudr63y85g28v0k657p83u)

Might reach out to Sorin, or Shixie if any questions come up. This looks pretty straightforward for the most part though?

**Comment by photodow** [comment]
Once https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1345 is merged the link to the functional specs will be at...

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Universal-banner
