### ISSUE TITLE
ibmdoctcom-styles - Error in minified css version 1.19.0 and above - we are unable to upgrade dotcom

### ISSUE THREAD

**Issue by Daynssjal** [carbon-design-system/carbon-for-ibm-dotcom#6554]
React:

As per the documentation https://www.npmjs.com/package/@carbon/ibmdotcom-styles -> Usage, we are using this import to apply styles from ibm dotcom in our project:

`import '@carbon/ibmdotcom-styles';`

After upgrading to version 1.19.0 and above (we tried 1.20.0 as well as the current rc - 1.21.0-rc.0), we receive an error in the console, due to which our whole build fails:

![image (35)](https://user-images.githubusercontent.com/33804471/124249062-cc213a00-db23-11eb-933c-e61afc9b57f6.png)

We checked the ibmdotcom-styles minified css file, where the error occurs and localized the error:

<img width="704" alt="dotcom-styles-bug" src="https://user-images.githubusercontent.com/33804471/124249331-10143f00-db24-11eb-963b-9b41f9fd4b0c.PNG">

For easier localiziation, we unminified css and found out there are 2 errors like that:

![image (33) (1)](https://user-images.githubusercontent.com/33804471/124249588-5073bd00-db24-11eb-964b-9cebb60c507b.png)
![image (34) (1)](https://user-images.githubusercontent.com/33804471/124249593-51a4ea00-db24-11eb-99b8-8b7cdaf3802d.png)

I had a chat with Anna Wen from your team, who checked this issue and said, that the line which produces this code in the minified css is this one: ` @include carbon--breakpoint-between('md', $TEMP--breakpoint-down--lg)` and that it hasn't been changed since last  year. 

So there might be a deeper underlying issue.

What we tried:
- upgraded not only dotcom react and dotcom styles but also carbon-components and carbon-components-react to the latest version at that time (carbon-components: "10.37.0", carbon-components-react: "7.37.0")
- later we downgraded carbon-components to "10.36.0" and carbon-components-react to "7.36.0" as suggested by Ari in this slack post  https://ibm-content-coe.slack.com/archives/C2PLX8GQ6/p1623682361279700
- with each new release or release candidate of ibmdotcom-react and ibmdotcom-styles, we upgraded to that version just to check if the error is still there - it was

We tried a different strategy too:  **(plan B)**
- we removed the `import '@carbon/ibmdotcom-styles';` - the page loaded okay, as the error was not present anymore, however, of course, there were no dotcom styles in our project anymore
- so we went step by step based on the documentation: https://www.npmjs.com/package/@carbon/ibmdotcom-styles
and added the imports for each component separately as well as for the expressive theme, just like in the documentation.
However, we run into problems - some styles were not applied, e.g. for the Card component, which resulted in the inability to click on the card.
Summarized in this slack post:  https://ibm-content-coe.slack.com/archives/C2PLX8GQ6/p1623764471290100
This is our package.json for this strategy:
![image](https://user-images.githubusercontent.com/33804471/124252047-e0b30180-db26-11eb-863b-a1df5ed3c52e.png)
And imports in our main scss file called layout.scss:
![image](https://user-images.githubusercontent.com/33804471/124252286-1657ea80-db27-11eb-9843-af10953f1c52.png)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Knowledge Center team - IBM Docs project

## Additional information
We gave access to our repo to two developers in your team to see if there is something wrong, they were unable to run our app. We are of course willing to help with resolving the issues to make the app run on their machines so that they can have a look.

Unfortunately, due to this error, we are unable to test and use further versions of dotcom, but we need to.
We are willing to go with the second strategy - plan B, however there are issues with styles of the components as if some of the classes were simply not assigned to the components.

This is a pressing item and we would appreciate your help. Thank you

**Comment by jeffchew** [comment]
@Daynssjal to give you an update on this, we have dug into this and discovered that it is an upstream issue in Carbon, which we have went ahead and opened a PR to fix in core Carbon. In the meantime, we are patching with hardcoded breakpoint values to unblock in the meantime. We are scheduling another release candidate today.

cc: @annawen1 @kennylam @ljcarot @RobertaJHahn @shixiedesign
