### ISSUE TITLE
React: Card component, v 1.19.0 and above: missing .bx--card css class and pseudoselectors

### ISSUE THREAD

**Issue by Daynssjal** [carbon-design-system/carbon-for-ibm-dotcom#6563]
Hello, after upgrading to v 1.21.0-rc.3, we are facing the following issue with the Card component:
(This issue started to occur from version 1.19.0 and above)

The css class  .bx--card is not applied, neither are the pseudo selectors.

Please, compare the html of the Card component from the dotcom storybook:
<img width="315" alt="dotcom-card" src="https://user-images.githubusercontent.com/33804471/124507322-dc5c4200-ddcd-11eb-875c-920bae8d584e.PNG">

and the html of the Card component in our project:
<img width="314" alt="docs-card" src="https://user-images.githubusercontent.com/33804471/124507341-e5e5aa00-ddcd-11eb-89f1-640ae1b4c409.PNG">

It seems, that due to the missing .bx--card class, the user won't be able to click on the card. They can only click on the link in the card, but that is not right. The whole card should be clickable.

We tried this with dotcom-react and dotcom-styles v 1.19.0, 1.20.0 and also the latest rc v 1.21.0-rc.3.
We also tried this in combination with carbon-components 10.35.0, 10.36.0, 10.37.0 and carbon-components-react 7.35.0, 7.36.0, 7.37.0. None of these helped.

Can you please investigate? Thank you

What offering/product do you work on? Any pressing ship or release dates we
should be aware of?
Knowledge Center team - IBM Docs project

**Comment by RobertaJHahn** [comment]
This is not a high priority for KC.  They have a work around.  Kenny can not reproduce the bug and has to recreate their environment to reproduce.

**Comment by kennylam** [comment]
@Daynssjal Now that I'm able to reproduce this error, I see there are a few things causing this issue. I tested using `v1.22.0` for both `@carbon/ibmdotcom-react` and `@carbon/ibmdotcom-styles`.

1. `.bx--card` CSS class is missing because it is being overridden. This prop should be changed to `customClassName`.
```diff
--- a/src/Frontend/components/LayoutContainer/FamilyPicker/VersionCard.js
+++ b/src/Frontend/components/LayoutContainer/FamilyPicker/VersionCard.js
@@ -7,11 +7,13 @@
 const VersionCard = ({ label, href, icon, type, copy, ctaIcon, copyTextLimit }) => {
   return (
     <Card
-      className={`ibmdocs-versioncard ${type !== '' ? `ibmdocs-versioncard-${type}` : ``}`}
+      customClassName={`ibmdocs-versioncard ${type !== '' ? `ibmdocs-versioncard-${type}` : ``}`}
       key={`version-${href}`}
       cta={{
         href: href,
-        icon: ctaIcon ? { ctaIcon } : undefined,
+        icon: {
+          src: ctaIcon ? { ctaIcon } : undefined
+        },
         copy: copy
           ? copyTextLimit
             ? trimTextToLength(copy, copyTextLimit, true)
@@ -20,7 +22,6 @@
       }}
       heading={label}
       eyebrow={icon}
-      type="link"
     ></Card>
   );
 };
```
2. the styles for `VersionCard` can be adjusted like this
```diff
--- a/src/Frontend/components/LayoutContainer/FamilyPicker/versionCard.scss
+++ b/src/Frontend/components/LayoutContainer/FamilyPicker/versionCard.scss
@@ -120,19 +120,12 @@
   background-color: $ibm-color__gray-80;
   color: $ibm-color__white-0;
   min-height: 14rem;
-  .bx--card__wrapper {
-    bottom: 0px;
-    top: 0px;
-    left: 0px;
-    right: 0px;
-    position: absolute;
-    height: 100%;
-  }
   .bx--card__footer {
     fill: $ibm-color__white-0;
     color: $ibm-color__white-0;
-    position: absolute;
-    bottom: 1rem;
+    .bx--card__cta__copy {
+      color: $ibm-color__white-0;
+    }
   }
   .bx--card__eyebrow {
     color: $ibm-color__white-0;
@@ -140,5 +133,8 @@
   }
   &:hover {
     background-color: #4c4c4c;
+    .bx--card__wrapper {
+      background-color: inherit;
+    }
   }
 }
```
3. the styles for `landing.scss` can be adjusted like this
```diff
--- a/src/Frontend/components/LayoutContainer/Views/Topic/LandingPages/landing.scss
+++ b/src/Frontend/components/LayoutContainer/Views/Topic/LandingPages/landing.scss
@@ -38,8 +38,7 @@
     color: #0f62fe !important;
     font-size: $layout-01 !important;
   }
-  .bx--card__copy,
-  .bx--card__footer {
+  .bx--card__copy {
     display: none !important;
   }
 }
```

**Comment by Daynssjal** [comment]
Adjusted the code based on Kenny's suggestions, the cards now work as designed. Thank you very much Kenny for looking into this!
