### ISSUE TITLE
Components pare down exercise 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6565]
### Problem
Looking into the existing list of components, not all component need a page on the website. Currently every component has a page which results in 

- Left nav is too long, hard to find anything
- Duplicated information
- Confusion around which component to use

### Task

We need to look at the relationships between components, the complexity, and the function/usage, and 

1. **derive a list of components that doesn't need a page**
2. where to include the useful info of those components if it doesn't have a page

Please use **Component naming standard** for reference: https://ibm.box.com/s/xlq4romcyp50lnvwuaagyzzbmmesuxen

**Comment by RichKummer** [comment]
**Airtable exploration:** https://airtable.com/invite/l?inviteId=invU1ggwLpB6YMFGp&inviteToken=60a4db3ea0b860ac27606ae56cba553a8c80367f71412f733d0fcdcb4f18ecae&utm_source=email

**Figjam exploration:** https://www.figma.com/file/lr7Xv8AojBVH5mJNXADCXV/Simplified-Component-Library?node-id=0%3A1

**Comment by RichKummer** [comment]
Attaching the simplified component library concept reviewed earlier today:

![071521-Simplified-Components-Concept.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/20e900cc-d250-4956-9f1a-0bcc4e66cde8)
