### ISSUE TITLE
Component content model audit & ramp up

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6567]
## The problem

**Content model** describes the content of a component. For example, a simple Card, the content might include: 

- heading
- eyebrow (optional) 
- copy (optional) 
- CTA text (optional) 
- image (optional) 

Beside the list, optional vs required, a content model should also describe what's the recommended character count before the design intent of the component breaks. 

These are so far thinking that happens during the component design process and not thoroughly documented. Partly because we lacked a standard way to do so. 

## The task 

We need a clear and complete content model definition: what are the attributes, what are the types, what are the recommended character counts? 

#### Additional info 

Here's an example of documentation started by Michael Fearer https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/callout-quote/#content-guidance

Here's our character count sizes & translation size: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Character-count-standards

**Similar terminologies**

1. Content model == Content guidance on the Carbon for IBM.com website. The website documentation is not as complete and thorough as the spreadsheets you guys have been seeing, but the intention is to document those exact spreadsheets.
2. Content model =/= Style model . Style model is more a visual treatment & layout thing that I’m trying to move forward.
3. Content model =/= Content types. So far Content type tends to refer to names like “Case studies” “Benefits”, so description of purpose or nature of a part of a page.
4. Content model =/= Data model . Data model is what we’ve been using previously to describe “data” of a component. They are kinda similar. Both data & content model can be shared between many components. But data model is more generic. Eg. a string in Data model might be a long copy or short copy or headline etc in Content model.

**Comment by RobertaJHahn** [comment]
To be assigned to Jonathan
