### ISSUE TITLE
[Nextjs & HTML templates] final design refinement + spec 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6569]
Continuation of #6028

There are a few outstanding checkboxes:

**Comment by RichKummer** [comment]
**InVision:** [https://ibm.invisionapp.com/share/3BO1BITMC64](https://ibm.invisionapp.com/share/3BO1BITMC64)

**BoxNotes Content (including content, functional notes, and assets):** 

- Dark theme: [https://ibm.box.com/s/91bzc8uj2e3fezc7gpp3lywkvyl1n50o](https://ibm.box.com/s/3h5ij3aks02j7w80l8y7wls9lktn73cm)
- Light theme: [https://ibm.box.com/s/u29docb85ejmareqmv7cnb7jdbc384hs](https://ibm.box.com/s/7foqlazlucgo941wtyse5n5pktm7eqkj)
