### ISSUE TITLE
[Feature section] background color using wrong token - DDS consulting support of HC development

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6571]
Background color of the section is wrong.

**Currently** using `$hover-ui` token
**Expecting** `$ui-01` 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/54681be1-b1cf-4c56-92f9-e84fb6e0ed98)

----
- Dev will be done by the Hybrid Cloud team
- Engineer assigned:  Putra Bonaccorsi

**Comment by RobertaJHahn** [comment]
@proeung Do you want to assign someone to fix this bug?

**Comment by RobertaJHahn** [comment]
Sent Slack message to Putra.  Waiting for response.

**Comment by proeung** [comment]
@RobertaJHahn I just assigned this bug to myself. It's a straightforward fix and I should have a PR up for this bug shortly.
