### ISSUE TITLE
Web component: Card Pictogram - On hover, tags and content are not visible for user.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6576]
## Detailed description

Issue: 
Pictogram placement: Top
On hover, tags and content are not visible for user.

Note:
Pictogram placement: Bottom
On hover, tags and content are visible.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/5e263fd7-5175-4710-9152-d5ee81a99fb8)

**Comment by IgnacioBecerra** [comment]
@Praveen-sr After talking to the designers, this feature works as intended -- hover functionality should only work on bottom pictogram placement.

cc: @RobertaJHahn

**Comment by shixiedesign** [comment]
Yep that's correct. I'm adding a mention of this behavior (top aligned pico doesn't have this feature) to the website right now via https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom-website/766. Sorry for the confusion.
