### ISSUE TITLE
[Content item horizontal] CTA icon is not aligned, when link text is 2 lines

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6577]
## Detailed description

Issue:
Content item horizontal with-thumbnail and Media 
CTA icon is not aligned, when link text is 2 lines.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/feef2b26-1efb-4e00-9947-23b881437f6e)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/d036e886-5ba1-4df2-a4e6-f2e9e6582cda)

**Comment by shixiedesign** [comment]
I believe this issue is resolved now. There's a new bug coz the wrap puts the icon in new line with a spacer. Will log later though. 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/323fa9b0-b36a-474a-92f4-dbe41bb0f540)
