### ISSUE TITLE
[Card - pictogram] Design improvement needed for mobile text display

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6578]
### Problem

[**Card - pictogram** component ](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-card--pictogram) has a few issues: 
- When pictogram is bottom, a hover interaction reveals additional body copy. On mobile (no hover state), these additional body copy is never readable. We should have a new mobile design so the body copy is always revealed
- When the body copy and card headline are long, hover interaction makes the card grow taller. This is probably because the card size is not calculated with those elements present at first. Might need a refactor? 

### Task 
1. Look into additional of the designs for mobile design 
2. Create logic for how the content edge cases should be handled

**Comment by shixiedesign** [comment]
To be assigned to Saijan when he onboards to Github

**Comment by shixiedesign** [comment]
When uploaded, the specs will be found here https://ibm.ent.box.com/folder/95514001950

**Comment by skuruvil** [comment]
The specs have been uploaded to the Box folder https://ibm.ent.box.com/folder/95514001950
