### ISSUE TITLE
[Card - logo] Card variation dedicated to logo / app icons

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6592]
### Problem

We might need a Card variation dedicated to logo / ~pictogram /~ app icons. We have pictogram cards at the moment, but they are not most suited for logo. 

### Task

- Audit, collect, and create designs for cards with logo / pictogram / app icons 

##### Additional information

For reference, here is a designs from Jen Witkowski from Hybrid Cloud team referencing our default card. **It drops the card heading**, but creates a lighter design.

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/f4c2617a-ef51-4c1e-bd4a-116e9bcbfac2)

- [Design and functional spec Box folder](https://ibm.ent.box.com/folder/95514001950?s=hgvu48r1fv2ga2h0yn3qshrtxjc71vch)

**Comment by RobertaJHahn** [comment]
Convert to an epic, design exploration

**Comment by RobertaJHahn** [comment]
issues needed:  consulting dev for WC, React wrapper, QA issues, website

**Comment by oliviaflory** [comment]
Work completed!
