### ISSUE TITLE
[Expressive modal] without expressive theme

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6599]
## Detailed description

> Describe in detail the issue you're having.

Without the expressive theme, the expressive modal launch button and button within the modal are using productive type

Swap both buttons to use the `expressive-button` variant from Carbon

![Screen Shot 2021-07-08 at 5 40 15 PM](https://user-images.githubusercontent.com/45692622/124994462-e5d6eb80-e013-11eb-8fca-5525bf4e8d6b.png)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

> Is this issue related to a specific component?

Expressive modal

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Caught this in a percy review from another PR, expect button to use 16px font via the expressive variant from Carbon

> What browser are you working in?

> What version of Carbon for IBM.com are you using?

Web components

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## NOTE TO DEVELOPER

**Branch should be off of the `feat/expressive-sunset` branch and targeted back to this branch when opening a PR!**

**Comment by RobertaJHahn** [comment]
Closing, dup of (#6202 )
