### ISSUE TITLE
[Callout data] without expressive theme update text token

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6600]
## Detailed description

> Describe in detail the issue you're having.

Callout data needs to use $caption-02 token for the caption text. I didn't catch this earlier because it's hidden? I only saw within the [Code sandbox example](https://webcomponents-codesandbox.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/6573/callout-data/index.html) in the e2e test

![Screen Shot 2021-07-08 at 5 47 20 PM](https://user-images.githubusercontent.com/45692622/124995030-bb396280-e014-11eb-97ee-2e7d5fafd321.png)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug 

> Is this issue related to a specific component?

Callout data

### NOTE TO DEVELOPER
Branch should be off of the `feat/expressive-sunset branch` and targeted back to this branch when opening a PR!

**Comment by RobertaJHahn** [comment]
@oliviaflory Call out data is being deprecated.  Should dev's work on this issue?

**Comment by oliviaflory** [comment]
@RobertaJHahn if Callout data is deprecated should we remove it from the Code sandbox demo? It appeared in the Percy review from the e2e test and came up as a change so that is why I logged it.

**Comment by RobertaJHahn** [comment]
Closing as this component is being deprecated.  See issue (#6183 )
