### ISSUE TITLE
[Card-in-card] card and hover overlaps masthead/navigation

### ISSUE THREAD

**Issue by pscheufens** [carbon-design-system/carbon-for-ibm-dotcom#6602]
## Detailed description

> When a Card in Card component is created in our AEM environment, the Card of Card in Card component is overlapping the toc when scrolling up. Upon hovering on Card in Card, when it's behind the toc, hover effect is also applied to that part of the toc.

> Is this issue related to a specific component?
Card in Card

> What browser are you working in?
Chrome

> What version of Carbon for IBM.com are you using?
v1.20.0-rc.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
AEM

## Steps to reproduce the issue
I have published a page on our system with a Card in Card component
https://dev-publish.np-roks.cms.cis.ibm.net/pascal-testpage-solution

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/29569154/125065011-947d3980-e0b1-11eb-95f6-fe21e2df1d91.png)

- Notes

**Comment by DragosRistici** [comment]
#### 1. The card in `Card in card` puts the card over the horiz ToC at scroll
#### 2. The hover on `Card in card` is also over the Toc: 

https://user-images.githubusercontent.com/48327647/125069214-1fb0fc00-e0bf-11eb-98ff-16b34b981675.mov
