### ISSUE TITLE
Create print-friendly web components so that users can print a web page with the relevant content easily visible

### ISSUE THREAD

**Issue by lily-kenney** [carbon-design-system/carbon-for-ibm-dotcom#6607]
**OVERVIEW**
This request originally stemmed from discussions with the case study team and the Afterburner experience guild team as we collaborated on the new case study article template. We wanted the Carbon for ibm.com components to be able to be assembled together in a way that when the user chooses to print the web page, it is visually aligned with what the components should look like. Specifically for case study team, this will allow the team to create custom PDFs for the more important case studies and rely on the print-friendly view for all other case studies. This use case seems applicable not just for the case study team, but for all other pages that uses the Carbon components (e.g. Learn, Solution).

Attached is an example of what the Learn page (that is a Carbon page) currently  looks like when users try to print to PDF via the print command. 
[What is EDI: Electronic Data Interchange? | IBM.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/6802339/What.is.EDI.Electronic.Data.Interchange.IBM.pdf)

Box note with print style specs: https://ibm.box.com/s/fdi0xrphqsqpa4dg64ts7zo9x8y1cin1
NOTE: The design of the Card section offset has been updated so the cards align below the headline and CTA.

**REQUIREMENTS**
1. The print-view of a page that uses Carbon components should be visually aligned with what the components should look like
2. Supporting the print friendly view should not compromise the integrity of the components on the web

NOTE: I discussed this via Slack with Shixie and she recommended that I submit a feature request to pursue this endeavor.

## Additional Information
- This would be tested in the Web Components and the HTML deploy previews
- The scope of this work includes updating the test applications to include the components being tested
- Design specs box folder:  https://ibm.ent.box.com/folder/148230038041
- Design for questions:  Rich Kumer

**Comment by RobertaJHahn** [comment]
Shixie will ask Sandeep about the minimum scope to size this work.

**Comment by ljcarot** [comment]
Could we get some metrics on how often things are printed?  I'd like to understand the volume of printing that is happening. cc @shixiedesign

**Comment by oliviaflory** [comment]
Office hours notes Aug 4
AEM: Sandeep 
DDS: Shixie, Rich, Jan, Jonathan, Olivia

Ideal state:
Shouldn't be lost by the borders or shouldn't be cut. 
Example:
- Cards being split between pages / arrows splitting between pages

Possible solutions / ideas
- Test printing medium breakpoint
- Remove images 

Components to look into:
- Masthead shows up in the middle of the page
- Leadspace is quite large
- TOC vertical is an issue with lg–max breakpoints
- TOC horizontal has issues with horizontal scrolling
- Tabs extended needs to open all tabs to reveal content
- back to top should hide
- carousel current print hides most content, needs to reveal all content
- card section offset current print preview is very bad
- dotcom shell
- footer

Q: Is there a universal way of printing that is not specific to components?
- AWS: the bulk is readable, but the top section is not great
- Google Cloud: everything is printed without cutting things out. 
  - Note: Google seems to remove some formatting on cards, and 

Q: If we come up with a service that can be applied per component for a print state, are you making...

Design team can help define the minimum and maximum solution
Minimum: lets not cut out any content

### Let us know when you have a timeline or plan in mind, when is what going to be available. 
DDS needs to follow up.

**Comment by RobertaJHahn** [comment]
All liked issues are closed.  Closing.
