### ISSUE TITLE
[Card link and tabs extended]: Create the functional specifications for this new component to be used on the Geo Home Page a.k.a Link list card section with tabs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6612]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Card link` and `Tabs extended` functional specs 

> so that I can:
so that I can properly code the `Card link` and `Tabs extended` component that meets the Design functions and intent

#### Additional information
- The original name for this component was `Link list cards section with tabs`.  Upon review, the work was broken into 2 pieces, changing 2 existing components:  Card link and Tabs extended.
     -  [PR for functional specs updates](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1117)
     - [Card link functional specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-link)
     - [Tabs extended functional specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Tabs-extended)

#### Acceptance criteria
 - [ ] Documented `Card link` and `Tabs extended` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by jeffchew** [comment]
This will be ready for review Aug 2nd refinement for engineers to size and build for Sprint 16. This would realistically be delivered for `v1.24.0`.

**Comment by photodow** [comment]
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Tabs-extended
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-link
