### ISSUE TITLE
[Masthead] Tabbing menu options, last option opens and user is directed to level 2 menus

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6623]
## Detailed description

Issue:
When keyboard focus is on Explore more option, pressing tab key Explore more section get expanded (on focus) automatically.

Expected:
No action should take place on focus. Pressing tab key from Explore more, keyboard focus should go to the Close icon present at the top.

## Additional information

![2MenuOpt.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/7d1bb90d-448f-46ec-8abf-ebb712345941)

**Comment by annawen1** [comment]
This issue seems to be resolved already. @Praveen-sr please confirm if we can close this ticket.

![Sep-27-2021 12-25-02](https://user-images.githubusercontent.com/54281166/134947968-4fab5269-6c0f-4a8e-9da4-bd93bde51b64.gif)

CC: @RobertaJHahn

**Comment by Praveen-sr** [comment]
@annawen1 Retested this on web component canary, its working as expected.

Note: We observed new issue now, On tab key from close icon focus is going to the non available (disabled) element.

**Comment by RobertaJHahn** [comment]
Closing this bug based on @Praveen-sr comments above.  Increased the scope of issue #6624 to include both react and web components to address Praveen's observation above.  

cc:  @annawen1
