### ISSUE TITLE
[Masthead] Mobile - On tab key from close icon focus is skipping platform ('IBM cloud') and jumping to the 'Product and Solution' - DDS consulting

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6625]
## Detailed description

Issue:
Hitting tab key from close icon focus is skipping platform 'IBM cloud' and jumping to the 'Product and Solution'

Expected:
Tab focus should go the the IBM cloud first then to the product and solution.

## Additional information
-  Engineering info:  
     - HC engineer: @andy-blum 
     - JC Jira Ticket: https://jsw.ibm.com/browse/HC-2188
     - DDS consulting engineer:   Anna Wen

**Comment by RobertaJHahn** [comment]
@Praveen-sr Could you provide a video of this behavior?

**Comment by proeung** [comment]
This bug is reproducible within the canary version of the library - https://ibmdotcom-web-components-canary.mybluemix.net/iframe.html?id=components-masthead--with-platform
