### ISSUE TITLE
[Card - logo] Design exploration for a card variation dedicated to logo / pictogram / app icons

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6633]
#### User story
> As a [user role below]:
`DDS Designer`

> I need to be able to do:
`Audit, collect, and create designs for cards with logo / pictogram / app icons`

> so that I can:
`recommend the design direction and next steps for this new component`

#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- Designs from Jen Witkowski from Hybrid Cloud team referencing our default card. **It drops the card heading**, but creates a lighter design.

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/f4c2617a-ef51-4c1e-bd4a-116e9bcbfac2)

#### Acceptance Criteria
- [ ] Design direction(s) has been identified, reviewed, and approved for the final design phase
- [ ] The next story has been updated with the design direction

**Comment by shixiedesign** [comment]
### Update
Let's treat this component as a new one separate from Card - pictogram. Just need to acquire the spec and add to box.

**Comment by skuruvil** [comment]
Visual specs available here https://ibm.ent.box.com/folder/95514001950?s=hgvu48r1fv2ga2h0yn3qshrtxjc71vch
