### ISSUE TITLE
dds-card-footer overlays the whole page if there is no href

### ISSUE THREAD

**Issue by dratzenboeck-ibm** [carbon-design-system/carbon-for-ibm-dotcom#6634]
## Detailed description

If a card does not have a href, a css style on dds-card-footer is overlaying the whole page, which causes the page not to be interactive anymore (e.g. can't click other links). 

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Cards with `dds-card-footer`

> What did you expect to happen? What happened instead? What would you like to
> see changed?
If the card is missing an href I want just a card which is not clickable instead of an transparent overlay over the whole page. 

> What browser are you working in?
Google Chrome Version 91.0.4472.124

> What version of Carbon for IBM.com are you using?
    "@carbon/ibmdotcom-styles": "1.20.0-rc.1",
    "@carbon/ibmdotcom-web-components": "1.5.0-rc.1",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
AEM CMS - No pressing dates, minor issue, which can be handled via authoring. 

## Steps to reproduce the issue

1. Use a card component e.g. `dds-link-list-item-card` with a `dds-card-footer`
2. Make sure the `dds-link-list-item-card` has no href attribute
3. The `::after` style on the dds-card-footer will overlay the whole page

## Additional information

![image](https://user-images.githubusercontent.com/85555103/125595015-68687d2f-333b-4404-9516-c73763715fdd.png)

https://codesandbox.io/s/nervous-sinoussi-92vv5?file=/index.html 

Some background information:
This might not be a valid use case looking at web components alone, but in a CMS it can be. As editors are providing the links it could be that they have a typo. AEM would automatically check all links and if they have a typo like "https://www.google,com" the href would be removed, because of security reasons. If that happens I don't want to have a broken page, because of that one missing href.

**Comment by ariellalgilmore** [comment]
Share with @dratzenboeck-ibm this codesandbox https://codesandbox.io/s/dreamy-gates-cq6hr?file=/index.html

He confirmed that the codesandbox looked good, but AEM is still experiencing the issue since they are still using version 1.21. He will check again after the update.

**Comment by dratzenboeck-ibm** [comment]
@ariellalgilmore Works as expected after updating to
    "@carbon/ibmdotcom-styles": "1.23.0",
    "@carbon/ibmdotcom-web-components": "1.8.0",

Thanks
