### ISSUE TITLE
Update Google Analytics reporting for Website so it's tracking the new URL

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6639]
Old URL: https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/
New URL: https://www.ibm.com/standards/carbon/

Redirect has just turned on, so we can update the tracking to avoid disruption later when the old URL stops working.

**Comment by photodow** [comment]
Looks like the storybook URLs got updated as well, so those need to be updated in GA as well.

**Comment by photodow** [comment]
Updated reports:
[Website: Carbon for IBM.com / Referral Traffic](https://analytics.google.com/analytics/web/template?uid=8PHF7dhrRKumvfGrZhIsuA)
[Website: Carbon for IBM.com](https://analytics.google.com/analytics/web/template?uid=s9jBmmQpTBulpNDUoOFhtw)
[Storybook: Referral Traffic](https://analytics.google.com/analytics/web/template?uid=NjahMORSS6GuVAOkIC0jiA)
[Storybook: Carbon for IBM.com](https://analytics.google.com/analytics/web/template?uid=_grQKN8YRRqwf88IuyrbpA)
[Storybook: Carbon for IBM.com / Content Drilldown](https://analytics.google.com/analytics/web/template?uid=6OXgjMYGSw6eqWn7pqgLtg)

> heads up that because we moved to react and web-components storybooks under the `/carbon` directory our website reports will now begin to see those.  
> 
> I would recommend we maybe move it under a directory or subdomain that we can easily filter out if that's unexpected. Otherwise, our filtering options could become almost unmanageable.

**Comment by shixiedesign** [comment]
Awesome!
