### ISSUE TITLE
[Tabs extended] Padding issues

### ISSUE THREAD

**Issue by iwhitcomb** [carbon-design-system/carbon-for-ibm-dotcom#6669]
## Incorrect padding on mobile breakpoint

https://jsw.ibm.com/browse/ADCMS-1473
https://jsw.ibm.com/browse/ADCMS-1515
https://jsw.ibm.com/browse/ADCMS-1513

### Description

Tabs Extended should have the breaker lines, between the tabs, extended end to end
The tab title and other text should have 16px padding on each sides

Each tab title should not be in a box

https://dev-author.np-roks.cms.cis.ibm.net/editor.html/content/adobe-cms/ca/pt/qa/qa/june30soln.html

### Actual result

- The text on each side having 48px
- The tab title is inside a box
- the breaker line are having 16px on each side

### Expected Result
- The text should have 16px on each side
- the tab title should not be inside box and
- the tab title should maintain 16px on each side
- the breaking line should extend end to end

## Steps to reproduce the issue

1. Place a content item horizontal media inside a tabs extended component.

## Additional information

![ADCMS-1473](https://user-images.githubusercontent.com/887528/125958177-903f0b20-56e7-404c-b8a7-297ab05d52cd.jpg)
![ADCMS-1513](https://user-images.githubusercontent.com/887528/125959566-1f105cf2-c9f9-411e-a66b-f269c6959ec8.png)
![ADCMS-1514](https://user-images.githubusercontent.com/887528/125959601-b4de7994-a395-4515-a356-03f00944d316.jpg)

**Comment by jeffchew** [comment]
@iwhitcomb thank you for reporting! You could also contribute since you're familiar with the component!

@shixiedesign could you weigh in?
