### ISSUE TITLE
[Tabs extended] Tabs overlapping TOC on scroll

### ISSUE THREAD

**Issue by iwhitcomb** [carbon-design-system/carbon-for-ibm-dotcom#6670]
## Tabs overlapping TOC on scroll

https://jsw.ibm.com/browse/ADCMS-1514

## Detailed description

The tabs are overlapping with TOC when page is scrolled. This appears to be a z-index issue with the tabs.

## Additional information

![ADCMS-1514](https://user-images.githubusercontent.com/887528/125959234-4aa57e35-2536-4923-aea1-783b6bab4f70.jpg)

**Comment by jeffchew** [comment]
@iwhitcomb thank you for reporting! You could also contribute a fix since you're familiar with tabs extended!

**Comment by RobertaJHahn** [comment]
This fix will be done by DDS.  Work is included in sprint 16.
