### ISSUE TITLE
Website: Rename component Content Group Horizontal to Content Block Horizontal

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-for-ibm-dotcom#6671]
### Related Ticket(s)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6653 and #6666 

### Description

Rename `Content Group Horizontal` to `Content Block Horizontal` as the old component is deprecated per #6666.  

- [x] Update the left nav
- [x] Update component description json file
- [x] Update component page names
- [x] Update the footer name

**Comment by shixiedesign** [comment]
:tada:
