### ISSUE TITLE
[Masthead (dotcom & Cloud)]: Overflow logic is behaving weirdly on RTL

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#6672]
## Detailed description
- While testing the new `<dds-cloud-masthead-container>` within the Drupal pages in RTL, I noticed that the overflow container is constantly adding and removing the `.dds--ce--header__nav-caret-container--hidden` class resulting in flickering behavior where the masthead is unusable on RTL direction.
- This behavior looks to be the same on the dotcom version as well.

## Steps to reproduce the issue

1. Visit this page - _VPN requires_ (https://feat-hc-2021-gwktmubqkviyou8ytu4emiozocilov2b.w3-origin-007522.intranet.ibm.com/ar/cloud/watson-assistant)
2. Or test the bug locally.
3. set `STORYBOOK_IBMDOTCOM_WEB_COMPONENTS_USE_RTL=true` in your `packages/web-components/.env` file

## Additional information

![Screen Recording 2021-07-16 at 3 41 33 PM](https://user-images.githubusercontent.com/1815714/126000705-25842f7e-fba9-4004-8850-70dcc4a7ea4f.gif)

![Jul-16-2021 15-49-28](https://user-images.githubusercontent.com/54281166/126001374-40f65a8d-2f6f-48e1-8a9a-cbeee9168cec.gif)

**Comment by jeffchew** [comment]
This will need to be included in the next release candidate for `v1.22.0`.
