### ISSUE TITLE
[Lead space] Deprecation of React Lead Space

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#6675]
### The problem
The Lead Space is a complex component that has multiple variations. It is a tax on the team to keep up changes for both React and Web Components.

### The solution
Stop any new development of the React Lead Space and move users to the Web Component React wrapper version.

### Additional information
- Creation of the React wrapper for Lead Space 
 - Add a deprecation notice to the current React lead space that development has stopped for it, and any new updates will be seen in the Web Components (and React Wrapper) versions. 
 - As we're not fully removing the React version, perhaps should think of a way to snapshot the existing styles and continue any new development in separate styles files

**Comment by jeffchew** [comment]
Probably should also have messaging on the website.

**Comment by RobertaJHahn** [comment]
Issues:  Dev, website (pointing users to the React Wrapper), Visual QA of React Wrapper and Prod QA of React Wrapper
