### ISSUE TITLE
[Masthead, mega menu] Web Components:  In the `md` breakpoint, Mega menu options do not close when clicked outside the menu options.. - DDS consulting

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6676]
HC engineer: @andy-blum 
HC Jira Ticket: https://jsw.ibm.com/browse/HC-2187
DDS consulting engineer: Anna Wen

----
## Detailed description

Issue:
Mega menu options do not close when clicked outside the menu options. Anywhere on the page.

**Expecting:** clicking outside the menu on page with an overlay should close the menu. 

**Currently:** clicking outside the menu on the overlaid page doesn't do anything.

## Additional information

- Example 1
![MM.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/ef6e8822-b90e-4804-80ca-40aa34fd0635)

----

- Example 2
![Jun-25-2021 22-09-47.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/f9e7b0d3-6907-4b16-868b-ae14c7272a81)

**Comment by proeung** [comment]
This issue looks to be similar to the regression bug mentioned here - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6483.

**Comment by RobertaJHahn** [comment]
Consolidated the content from issue (#6483) into this issue and closed issue (#6483)

**Comment by andy-blum** [comment]
@RobertaJHahn who is the consulting engineer on this ticket?

**Comment by proeung** [comment]
@RobertaJHahn @jeffchew I'm removing the "Package: react" label from this issue based on the finding noted in the comment of this PR - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7161#issuecomment-922052141. Please feel free to break out a new issue for the Core React package.

**Comment by RobertaJHahn** [comment]
React issue #7190 created for the fix.
