### ISSUE TITLE
[Lightbox media viewer] Scroll is showing, but it is not needed

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6692]
## Detailed description

Issue:
 Scroll is showing, but its not needed.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/4e575921-37ee-4dc1-b1c3-75973949732d)

**Comment by annawen1** [comment]
Am not able to recreate this issue, I believe this has been resolved.

@Praveen-sr can you double check?
https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-lightbox-media-viewer--embedded-video-player

**Comment by annawen1** [comment]
Closing this as I believe it's bee resolved
