### ISSUE TITLE
[Housekeeping] Implement the updated 🐛 Bug issue template

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6695]
Jonathan wrote a new bug issue template last sprint. Looking for some dev help to get it implemented. 

Details here: 

https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/6224

**Comment by jeffchew** [comment]
@RobertaJHahn this should be sized in the next refinement.
