### ISSUE TITLE
yarn Install fails on Apple Silicon (M1) and other ARM architecture [Solution Inside] - DDS Consulting

### ISSUE THREAD

**Issue by andy-blum** [carbon-design-system/carbon-for-ibm-dotcom#6726]
## Detailed description

> Describe in detail the issue you're having.

Following the instructions in the [developer guide](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/docs/developing.md) on an ARM machine, the command `yarn install` fails with:

```
error .../node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/andy/Sites/IBM/carbon-for-ibm-dotcom/node_modules/puppeteer
Output:
The chromium binary is not available for arm64.
```

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

It's a bug, but well outside Carbon's package

### Getting the packages installed

Puppeteer's issue queue has a lot of discussion around this, but the most informative issue is [Installation fails on Apple Silicon / M1 #6622](https://github.com/puppeteer/puppeteer/issues/6622).

I just got up and running with the following steps
1. Install chromium on your machine. I used `brew install chromium` but if you don't have homebrew you can get it from [chromium's download page](https://www.chromium.org/getting-involved/download-chromium)
2. My machine told me the copy of chromium I got was broken and should be moved to the trash. Instructions to remedy that can be found within [chromium's documentation](https://chromium.googlesource.com/chromium/src.git/+/main/docs/mac_arm64.md#building-for-arm-macs)
3. Following the directions of [this comment](https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-787912758), you can direct puppeteer to use the copy of chromium you just downloaded by adding the below lines to your `~/.zshrc` (or equivalent):
```
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`
```
4. Restart your terminal, or run `source ~/.zshrc` (or equivalent) to get those variables in your current shell.

### Getting the packages built

Running `yarn build` was failing and I thought I'd have another rabbit hole to dive into, but moving from node v12 to node v14 seems to have gotten me past the point I was previously failing and things seem to complete successfully now.

----
- Hybrid Cloud developer: 
- [HC Jira ticket]
- Dev estimate:  
- DDS consultant:

**Comment by RobertaJHahn** [comment]
Kenny tested on his machine and could not recreate the problem.  Needs more review.

**Comment by andy-blum** [comment]
Tried testing this morning by removing the customizations I outlined in the original issue and was able to get everything working. I'm going to test this on my wife's laptop which has never installed node or yarn to ensure a fresh M1 mac can get up and running.

**Comment by andy-blum** [comment]
Installed the following on my wife's machine:
- node v14.17.6
- npm 6.14.15
- yarn 1.19.0

`yarn install` and `yarn build` both working fine - whatever dependency was causing this issue must have been updated. Closing this issue out
