### ISSUE TITLE
Inconsistent spacing between content group banner link list items

### ISSUE THREAD

**Issue by rastogir** [carbon-design-system/carbon-for-ibm-dotcom#6728]
Spacing between content group banner links when both link text don't break into new line and when the second link text breaks into a new line is different. Expected behavior is to have consistent spacing.

<img width="1103" alt="Screen Shot 2021-07-26 at 2 55 59 PM" src="https://user-images.githubusercontent.com/11525031/127051535-695905e3-670e-42bb-aa13-2fab7bc0e244.png">

**Comment by proeung** [comment]
@rastogir I just adjusted the preview to include a long string and the spacing looks to be rendering correctly within the `<dds-link-list-item>` component. Can you give me an example of the rendering that you're seeing on AEM? I just wanted to make sure the WC markup/template is set correctly.

![Screen Shot 2021-08-11 at 12 26 27 PM](https://user-images.githubusercontent.com/1815714/129067210-4ef47495-ce4e-4433-9d0f-9de2919585b9.png)
![Screen Shot 2021-08-11 at 12 26 22 PM](https://user-images.githubusercontent.com/1815714/129067223-ca54c933-42bc-4ed6-9579-d368bd3d75dd.png)

**Comment by rastogir** [comment]
@proeung There is a difference of few pixels between the link list items when link text is longer. Below screenshot is from storybook running locally with latest from `master`.

<img width="1471" alt="Screen Shot 2021-08-11 at 4 22 28 PM" src="https://user-images.githubusercontent.com/11525031/129105736-b86fcc21-ccad-4bc8-ba92-c7b3e3589884.png">
<img width="1503" alt="Screen Shot 2021-08-11 at 4 23 37 PM" src="https://user-images.githubusercontent.com/11525031/129105750-0a042dd7-840d-4579-9175-72ec5bc3189e.png">

**Comment by shixiedesign** [comment]
Hey @proeung @rastogir this is a recent fix just pushed to Canary this sprint. So I believe Putra's screenshots represent the latest: https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-content-group-banner--default

**Comment by proeung** [comment]
@shixiedesign That's correct. My screenshots are from the `master` branch/Canary build.

@rastogir Can you test on the Carnary preview and let us know if you're still seeing the spacing issue? Thanks!

**Comment by proeung** [comment]
@RobertaJHahn @jeffchew Please review this ticket and let me know if this is something that we should take a look deeper or close out.

**Comment by shixiedesign** [comment]
Hmm in Canary i cannot reproduce inconsistent spacing: 

Single line text link
![image](https://user-images.githubusercontent.com/15144993/130095032-aee92ec6-45ae-45c9-b3b7-d6c30da19dd4.png)

Multiline text link
![image](https://user-images.githubusercontent.com/15144993/130094958-b1bc6c40-e3c7-49af-9756-a358df009378.png)

**Comment by rastogir** [comment]
@shixiedesign @proeung Retested the issue and spacing is consistent. Thanks for working on this issue.

**Comment by shixiedesign** [comment]
Awesome! Thank you!
