### ISSUE TITLE
[Card - logo] Functional spec 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6740]
Based on the designs from Jen's team. We don't need to make further tweaks and the goal is to absorb the component.

**Comment by photodow** [comment]
[Here are the designs](https://ibm.box.com/s/ifgrr5yfjl9z76rqyllwf30mxlk6mmmr)

Might reach out to Saijan if I have any questions. I am curious how this plays with some things like pictograms, and other things we provide.

**Comment by photodow** [comment]
Added a new section under "Optional logo"

https://ibm.box.com/s/hgvu48r1fv2ga2h0yn3qshrtxjc71vch
