### ISSUE TITLE
Website "Patterns" section new concept exploration

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6753]
### The problem

Currently, the Patterns section contains quite a few pages named after Components, but not all. The content of these pages are similar to component guidance, but leaning towards design guidance and design decision documentation. To better understand how this section became this way, please check with Olivia and James who have the history. 

The current pages and page names under Patterns feels too similar to Components, and even internal team member struggle to remember where to find a specific piece of content. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/1945b448-fcb5-4df1-9046-8606f815f0f6)

### The task

Investigate the possibility of using Patterns section **for something completely different from Components in concrete ways.** Effectively use this precious real estate we have for findable information.

I have explored the idea of using Patterns for "Content type" (name TBD) documentation. An example of Content type is **Use cases**. Use cases can be expressed in many different components, such as `Card section` `Card section carousel`, `CTA section - with content items` etc. So the entry point is for content writers / OMs of pages looking for available designs for their materials. That's just 1 idea. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/90494822-1c42-4497-8f50-82fe23422d6f)
Screenshot from sitemap concept here https://www.figma.com/file/Nkn8gqjyKVEbIiWcBRUsMm/Carbon-for-Dotcom-Sitemap?node-id=0%3A1

**Comment by JBrandwine** [comment]
Initial thoughts:

- Move content that fits the new web component page template
- Delete any redundant information
-Consider a tabbed experience for content heavy pages to reduce scroll and improve findability
- Focus section on design tips
- Demonstrate how to combine multiple components to build a well-designed page
        - Provide sample pages for page-types, e.g., marketing
- Provide examples of rare/outlier use cases..."exceptions to the rules"
