### ISSUE TITLE
[Masthead] Change functional specs to include logic that highlights the current and parent menu items within the Masthead dropdown + Mega Menu based on the URL

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6762]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Masthead` functional specs 

> so that I can:
so that I can properly code the `Masthead` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#6638 )**

#### Acceptance criteria
 - [ ] Documented `Masthead` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by shixiedesign** [comment]
Incremented func spec number to 1.2.5 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/cce31ef4-400f-405d-827e-43dc0de1b99f)
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/f9f80458-d8f1-4120-842b-bceccf39ccbe)
