### ISSUE TITLE
[Masthead] Web Component: Change component to include logic that highlights the current and parent menu items within the Masthead dropdown + Mega Menu based on the URL 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6763]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `Masthead`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic for the Design and Functional specs information**
- No visual changes and visual QA testing required.
- The manual option stays in place.  The automatic mapping is added.
- Web Components Prod QA testing issue (#6765)

----
Hybrid Cloud developer:  Hunter MacDermut
- [HC Jira ticket](https://jsw.ibm.com/browse/HC-2132)
- Dev estimate:  5
- DDS consultant:  Anna

----

Incremented func spec number to **1.2.5** https://ibm.ent.box.com/file/781809973704?s=89qwjyjy6kwbi69qnz4nzatwfv3mh2kc

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/c62cd242-5ea8-452d-a04d-ec49cc8a21b0)
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/99737657-691f-43c2-9da3-5546e18185e4)

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by proeung** [comment]
Link to the issue request - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6638

**Comment by proeung** [comment]
@RobertaJHahn Here's the link to the JIRA ticket (https://jsw.ibm.com/browse/HC-2132) that we're tracking on our board.

HC Engineer Assignee: TBD

**Comment by proeung** [comment]
@huntermacd Please reach out to @annawen1 if you have any questions about the solution that came out of this ticket (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6638).

**Comment by RobertaJHahn** [comment]
Moving Hunter's comments in the epic #6638 to this dev issue.  @proeung  @annawen1 

----
Making good progress on this work. A couple issues came up I'd like to bring attention to.

1. Certain links in the Cloud version of the masthead, like https://www.ibm.com/cloud/ai are present both under Products and Solutions. Unlike links in the non-Cloud version of the masthead, which have identifiers, like `?lnk=hpmps_buai`, Cloud masthead links have no identifier that can be used to distinguish under which heading they should be highlighted. How should we distinguish between the two?

![Screen Shot 2021-08-19 at 1 03 35 PM](https://user-images.githubusercontent.com/4371669/130112221-c552e4a0-a30c-4132-af67-4e85f66a5371.png)

2. Certain links in the non-Cloud version of the masthead, like https://www.ibm.com/docs/en?lnk=hpmls_budc, are used both for the link with icon that heads the section as well as an underlying link. How might we decide which to highlight?

![Screen Shot 2021-08-19 at 1 00 40 PM](https://user-images.githubusercontent.com/4371669/130111810-34c60dc9-7525-4760-b04b-843bb8808d5f.png)

**Comment by RobertaJHahn** [comment]
Design comments in engineering meeting:  Options:  1)  Refer to the IA guild.  2)  Provide a way to manually update the links.  3)  Documentation could be a heading and not have a link.  Solves the problem of dup links within the same menu item.  

Solution for both issues 1 & 2:  Add logic to select the first parent menu item.
