### ISSUE TITLE
Component content model continued 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6772]
Last sprint the focus was on Cards & related. 

#### Moving forward, let's continue to pick components from the Top priority list, and clean up the content model for them  

Top priority component list based on page visits: https://cognitive-app.slack.com/archives/G01CFF8ETPU/p1624048170003600

- Masthead
- Dotcom shell
- Lead space
- Footer
- CTA section
- Card group
- Card 
- Card section
- Carousel
- Content item / group / block / section

Other related components to consider: 
- Feature card
- Feature section

### Acceptance criteria 

**Aim to finish 2-4 component content models**. Recommend more complex components so we can prepare for any additional complexity that the tables need to accommodate.

**Comment by JBrandwine** [comment]
[Content Model Master.xlsx](https://app.zenhub.com/files/193129061/6ea705bb-f715-4c35-a497-d37f940352a6/download)

Models drafted this sprint:Dotcom Shell
L0 Masthead
L1 Masthead
Footer
Carousel
CTA
CTA section
Content Item
Lightbox media viewer
Video
Expressive modal
Image
Image w/ caption
