### ISSUE TITLE
TypeScript V4.2.3 or more needs to be supported

### ISSUE THREAD

**Issue by SR1947** [carbon-design-system/carbon-for-ibm-dotcom#6792]
Brief description

We need to upgrade to latest Angular version and the minimum TS version supported by Angular 12 is 4.2.3. But Carbon for ibm dotcom supports < TS 3.8.x. 

Please check the angular documentation link below for details.
https://angular.io/guide/updating-to-version-12#breaking-changes-in-angular-version-12
"Add support for TypeScript 4.2. TypeScript <4.2.3 is no longer supported. The supported range of TypeScript versions is 4.2.3 to 4.2.x"

Adopter:  SDMA - Passport Advantage

**Comment by RobertaJHahn** [comment]
Setting up the issues as a dev research.  The results of the research will be presented in the engineering huddle meeting to talk about the next steps and the potential issues.

**Comment by jeffchew** [comment]
@SR1947 I did an upgrade to `typescript v4.3.5` in the following PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6943, and there didn't seem to be any issues with upgrading. Once this is merged in, could we have you test out a canary version to see if this works for you?

Can you reach out to me in IBM slack at @jeffchew?

**Comment by igaldino** [comment]
Hi team, I tried Angular 12 and this didn't work.
I attached the `ng serve` output. It only has the following:
```
<dds-dotcom-shell-container>
  <main>The main content</main>
</dds-dotcom-shell-container>
```
[serve.log](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/8703782/serve.log)

Did you get anything special to get it working?
