### ISSUE TITLE
Content Group Banner | Not showing the Divider line between title and CTA for content group banner in safari - DDS Consulting

### ISSUE THREAD

**Issue by druckerk** [carbon-design-system/carbon-for-ibm-dotcom#6794]
Brief Description: The Divider line between title and cta for the content group banner is not showing up in safari. 

## Detailed description

> Describe in detail the issue you're having.

The divider line between the title and cta for the content group banner will appear in chrome and firefox browsers. However, when opening the links in safari the divider line does not appear. 

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

This is a general issue when open the component in Safari

> Is this issue related to a specific component?

This issue is related to the Content Group Banner component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Actual result: 
- Not showing the Divider line between title and CTA for content group banner in safari
- https://dev-publish.np-roks.cms.cis.ibm.net/qa/abhinav-testpage/learn-landing-page-20-july
- https://www.ibm.com/standards/carbon/web-components/?path=/story/components-content-group-banner--default

Expected Result:
- Show show the Divider line between title and CTA for content group banner in safari as it is showing in Chrome

> What browser are you working in?
- Chrome (works as expected)
- FireFox (works as expected)
- Safari (Does not work)

> What version of Carbon for IBM.com are you using?
- ibmdotcom-styles: 1.21.0
- ibmdotcom-we-compnents: 1.6.0

## Steps to reproduce the issue

1. Copy the links provided above
2. Paste the links into Safari
3. Then paste the links to chrome or firefox
4. Then review Safari and chrome/firefox side by side and you will notice the divider is missing in firefox.

## Additional information

Safari Screenshot: 
![Screen Shot 2021-08-03 at 3 10 46 PM](https://user-images.githubusercontent.com/88403358/128079577-31a9a3d1-e5a1-412d-9216-ac691411a465.png)
![Screen Shot 2021-08-03 at 3 10 39 PM](https://user-images.githubusercontent.com/88403358/128079579-8fd3e6a5-3cd2-450e-955a-2600d641f0e5.png)

Chrome Screenshot: 
![Screen Shot 2021-08-03 at 3 10 17 PM](https://user-images.githubusercontent.com/88403358/128079630-17221bdd-7a85-4356-93ef-8c31aa8269eb.png)
![Screen Shot 2021-08-03 at 3 10 07 PM](https://user-images.githubusercontent.com/88403358/128079633-7aedc2a9-3669-4251-af42-c246acf68f81.png)

----
Dev will be done by HC
- HC dev assigned:  Marlene Wanberg
- [HC Jira ticket](https://jsw.ibm.com/browse/HC-2130)

**Comment by sbahl1** [comment]
Corresponding AEM ticket is https://jsw.ibm.com/browse/ADCMS-1598 and this impacts the Geo Home page Rollout, planned for Aug 31st

**Comment by RobertaJHahn** [comment]
8/4/2021 Slack:  **Sandeep Bahl**:  11:21 AM --we can live without it, just need a new date

**Comment by RobertaJHahn** [comment]
Safari usage globally is 18.64%.  Tier 1 support level.

**Comment by proeung** [comment]
@RobertaJHahn Here's the link to the JIRA ticket (https://jsw.ibm.com/browse/HC-2130) that we're tracking on our board.

HC Engineer Assignee: @mwanberg
