### ISSUE TITLE
Transposition of data attributes to support target analytics in web components

### ISSUE THREAD

**Issue by leetsao** [carbon-design-system/carbon-for-ibm-dotcom#6813]
### The problem
In order for Adobe Target Experiments to transmit information to Google Analytics, a series of html attributes have been created for the DBDM analytics code to identify elements modified by Adobe Target.

Example:
data-experimentid="12345"
 data-dynamic-content="true" 
 data-driverintent="interactive" 
 data-driverformat="CF603" 
 data-driversource="target" 
 data-driverlocation="dds-leadspace__cta-0" 
 data-drivertype="TY702" 

### The solution
When placing these attributes on elements with href, need for these attributes to be transposed to the create html elements with the anchor

<dds-some-item href="https://www.google.com"
data-experimentid="12345"
 data-dynamic-content="true" 
 data-driverintent="interactive" 
 data-driverformat="CF603" 
 data-driversource="target" 
 data-driverlocation="dds-leadspace__cta-0" 
 data-drivertype="TY702" 
><dds-some-item>

Should be transposed to:
<a href="https://www.google.com"
data-experimentid="12345"
 data-dynamic-content="true" 
 data-driverintent="interactive" 
 data-driverformat="CF603" 
 data-driversource="target" 
 data-driverlocation="dds-leadspace__cta-0" 
 data-drivertype="TY702" 
>
#### Additional Information
- DDS will implement as a generic solution that will transpose all data attributes except autoid.
 - Tracking the data attributes is difficult for this team without this feature in place.
- When authoring, the data attributes should be added to the web components to be transposed into the shadow dom

**Comment by RobertaJHahn** [comment]
@leetsao Recommend attending the Engineering Office Hours.  The meeting takes place every Wednesday morning at 9 ET.  Here is a link to the meeting information:  https://ibm.ent.box.com/notes/799374147228

**Comment by leetsao** [comment]
This was previously discussed in an office hours and I was asked to create this feature request.
I have time on the next office hours and we can continue to discuss there.
 
 
Lee TsaoSenior Solutions Architect, IBM IXe: ***@***.***: 248-470-6725
 
 
----- Original message -----From: "RobertaJHahn" ***@***.***>To: "carbon-design-system/carbon-for-ibm-dotcom" ***@***.***>Cc: "Lee Tsao" ***@***.***>, "Mention" ***@***.***>Subject: [EXTERNAL] Re: [carbon-design-system/carbon-for-ibm-dotcom] Transposition of data attributes to support target analytics in web components (#6813)Date: Tue, Aug 10, 2021 9:41 AM      @leetsao Recommend attending the Engineering Office Hours. The meeting takes place every Wednesday morning at 9 ET. Here is a link to the meeting information: https://ibm.ent.box.com/notes/799374147228 — You are receiving this because    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
@leetsao Recommend attending the Engineering Office Hours. The meeting takes place every Wednesday morning at 9 ET. Here is a link to the meeting information: https://ibm.ent.box.com/notes/799374147228

**Comment by leetsao** [comment]
QA URL that is modified by Target: https://www.ibm.com/topics/edi-electronic-data-interchange?at_preview_token=lIs_-apTKomYU1rYN9Q8BQ&at_preview_index=1_1&at_preview_listed_activities_only=true

**Comment by jeffchew** [comment]
Will need to transpose for any anchors and cards. Example above would need to include this for `dds-link-list-item-card`, for example.
