### ISSUE TITLE
[Universal banner] Web Component: Develop the Universal banner component

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6814]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `Universal banner`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic for the Design and Functional specs information**
- [Final design and design specs](https://ibm.ent.box.com/folder/142303458357?s=fas5qv5zrscudr63y85g28v0k657p83u)
- [Functional specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Universal-banner)
- The background color should be able to change.
- Include MH change for the behavior when Banner is present.  Func spec (#7620)
- Include a Knob in the dotcom shell storybook to allow for the Universal Banner.  
- Web Components Visual QA testing issue (#6816 )
- Web Components Prod QA testing issue (#6821 )

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] Update the e2e test scripts, if needed. 
- [ ] Confirm e2e test results have no major errors.
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by IgnacioBecerra** [comment]
@jeffchew Moving this one back to Sprint 3 since it got approved on Friday to merge
