### ISSUE TITLE
theme.background is undefined

### ISSUE THREAD

**Issue by chris-aeviator** [carbon-design-system/carbon-for-ibm-dotcom#6827]
When building via `yarn build` and running `yarn start` inside `packages/react` to build the storybook, the storybook does not render any code and shows an error popup

## Detailed description

```
theme.background is undefined

../../node_modules/@storybook/components/dist/blocks/DocsPage.js/DocsWrapper<@http://localhost:9000/vendors~main.4e37b7293aa15b6ed4fe.bundle.js:182534:5
handleInterpolation@http://localhost:9000/vendors~main.4e37b7293aa15b6ed4fe.bundle.js:168277:37
serializeStyles@http://localhost:9000/vendors~main.4e37b7293aa15b6ed4fe.bundle.js:168397:15
createStyled/</Styled</<@http://localhost:9000
```

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
bug

> Is this issue related to a specific component?
no
> What did you expect to happen? What happened instead? What would you like to
> see changed?
the storybook should render perfectly fine after a successful build
> What browser are you working in?
firefox
> What version of Carbon for IBM.com are you using?
master as of today

## Steps to reproduce the issue

1. download master
2. run `yarn && yarn build && cd packages/react && yarn start`
3. goto localhost:9000

**Comment by annawen1** [comment]
Hi @chris-aeviator have you done a `yarn install` as well in the `packages/react` folder? Are you using a windows machine or Mac?

**Comment by chris-aeviator** [comment]
yes I've done that. I'm running on arch linux. 

```
❯ node --version
v12.21.0
```

**Comment by chris-aeviator** [comment]
My initial issue description was slightly misleading - after a reload of the page I'm able to see the storybook contents but this error appears on every doc-page (doc page is the first thing to load). I have since disabled the doc pages via storybook config file to not have anyone using the system confused.

I'm off the workstation until early September and will try to join the proposed E.O. Hours

**Comment by RobertaJHahn** [comment]
Closing this issue based on comments above.  Will address in the engineering office hours.  Can reopen this issue later, if needed.
