### ISSUE TITLE
Extended Tab inside content section simple has width problem with several tabs on small screens

### ISSUE THREAD

**Issue by skycryer** [carbon-design-system/carbon-for-ibm-dotcom#6829]
## Title line template: [Title]: Brief description
When adding the extended tab inside a content section simple and adding several tabs they have a problem on small screen where no more space is available for the content section area.

-->

## Detailed description

> Describe in detail the issue you're having.
When adding tabs every tabs has a set width. But when adding to many tabs on smaller screens the width of all tabs together is to much for the screen.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Extended Tabs 

> What did you expect to happen? What happened instead? What would you like to
> see changed?
On smaller screens the tabs should scale down or show a slide or something so the tabs also fit on smaller screens

> What browser are you working in?
Safari, Chrome ,Firefox

> What version of Carbon for IBM.com are you using?
1.21

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM CMS

## Steps to reproduce the issue

1. Add content section simple
2. Add extended Tabs into body area
3. Add 6 Tabs
4. scale Browser to 672px width

## Additional information

<img width="1066" alt="Screenshot 2021-08-06 at 12 24 56" src="https://user-images.githubusercontent.com/3725699/128497484-f3fabe35-f80a-4309-96fa-02043c672512.png">

**Comment by RobertaJHahn** [comment]
This component changes to an accordion format at this breakpoint.  However it appears that this component is being put inside the Content section simple component which is causing this issue.  This component already has a content section in it so it should not be used inside another content section.  Recommend attending the Engineering Office Hours to discuss.

**Comment by RobertaJHahn** [comment]
Closing based on comments above.
