### ISSUE TITLE
Link List item not using same height

### ISSUE THREAD

**Issue by skycryer** [carbon-design-system/carbon-for-ibm-dotcom#6830]
## Detailed description

> Describe in detail the issue you're having.
We use a different web component for the link (dds-link-list-item-cta) but same problem is with dds-link-list-item. I found that if i chnge the a-tag inside the linklist item to flex !important it works. But on storybook it works without. No idea why the flex is not working for us no matter if we use the same link list item as storybook or our.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bug

> Is this issue related to a specific component?
Link List

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Items should use same height and center text

> What browser are you working in?
Chrome, Safari, Firefox

> What version of Carbon for IBM.com are you using?
1.21

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM CMS

## Steps to reproduce the issue

1. add link list
2. In one item add as much text as needed to create a second line

## Additional information
As said this works in storybook but not for us even with the web component version used in sotrybook

<img width="1617" alt="Screenshot 2021-08-06 at 13 40 07" src="https://user-images.githubusercontent.com/3725699/128505776-1b2cf3bf-826b-4017-b965-6da0fb5c7f06.png">

Because this bug are visible for everyone i can not post a link to the page with the problem. But please contact me over Slack (Christian Schimanski) if you have questions or need the link to the sample page

----
HC Jira issue:  (https://jsw.ibm.com/browse/HC-2139) 
HC Dev:   Andy Blum
Story Points:  3
DDS consultant:  Ignacio Becerra

**Comment by RobertaJHahn** [comment]
@skycryer Anna will reach out to you for more information.

**Comment by annawen1** [comment]
Confirmed by Sandeep in the aem support slack channel that the issue is on hover/focus, user can see the link does not take the full height when other links in the link-list have more than one line of copy

<img width="833" alt="Screen Shot 2021-08-10 at 10 26 29" src="https://user-images.githubusercontent.com/54281166/129205264-56d713f6-a5b3-4628-9288-ec75119019a8.png">

**Comment by shixiedesign** [comment]
Ooof! I see. Yes 🐛 I vote sev 3 @jeffchew @RobertaJHahn

**Comment by proeung** [comment]
@RobertaJHahn Here's the link to the JIRA ticket (https://jsw.ibm.com/browse/HC-2139) that we're tracking on our board.

HC Engineer Assignee: @andy-blum

**Comment by RobertaJHahn** [comment]
@proeung Ignacio is the DDS consulting engineer on this one.

cc:  @IgnacioBecerra
