### ISSUE TITLE
[Link with icon] React: icon position when text wraps to 2 lines 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6837]
Currently link with icon is not showing the correct behavior when link text wraps to 2 lines. Icon snaps to right-aligned to the container, and creates a weird gap between text and icon. This could happen when text is too long, or when screen size is narrow, and is influencing several dependent components such as `Link list`, `Link list section`, and `Content group banner`

This is similar problem to (#5740 )

**This bug was fixed in Web Components under issue (#5705 ) and PR (#6812 )**
See this issues for more details, if needed.  Fix done by Andrew Wang

#### Current

![Apr-02-2021 16-52-42.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/daeba0c3-fb50-4005-8468-6913d6923c9d)

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/7d7a419e-8c4d-42e1-9050-d6f371b4cf06)

**Comment by emyarod** [comment]
may have been resolved in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6812

**Comment by shixiedesign** [comment]
Yes this can be closed. There's still a bug in alignment in React `Link List - end of section` but we can consider it out of scope of this ticket. Thanks!

React: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/b85b81fa-ffcf-41b8-9864-31ff673eca6c)
