### ISSUE TITLE
Website: Continue work on the component guidance template - second sprint

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6846]
### Task
Need a new **Component page** template so usage guidance and specs are surfaced to adopters better, and information better connected. 

### Problem 

Currently most component page guidance is created using below template:

```
- Default
- (Variations) 
- Behaviors
- Design and functional specifications
- Development documentation
- Feedback

```

A few complains about the current template include 
- Design & functional specs are too buried, reducing discoverability and making it hard for returning users to access. 
- "Default" etc are not informative section names
- Need to allow more flexibility depending on the component's complexity and needs

### Ideas

From the top of my head, some potential candidates for what goes into the template. 

**Always show:** 

- Design intent (usage)
- Function & behaviors
- Content guidance (required vs optional content, recommended char count and cardinality) 

**Potentially good to show:** 

- Explain build in logic
- Anatomy
- Use case examples
- Live demo? 
- Do’s and Don’ts
- Accessibility

**Comment by janchild** [comment]
Here are the latest versions of the template:

[Single component template v2.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/6984415/Single.component.template.v2.pdf)

[Multicomponent template v2.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/6984416/Multicomponent.template.v2.pdf)

**Comment by janchild** [comment]
Increasing estimate because I'm spending time refining, reviewing PRs, and reviewing content guidance tables.

**Comment by janchild** [comment]
I'm attaching the latest drafts of the component templates. The changes include:

- removing the `Related components` section in both `Single` and `Multi`. Feedback was that it was too complicated. 👋 
- including the option for real-life images in the `Multi` Overview, alongside the abstract mini-components, and I've explained when to use one over the other, hopefully capturing our discoveries! 

- [Single component template_v2.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/7145557/Single.component.template_v2.pdf)

- [Multicomponent template_v2.pdf](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/7145558/Multicomponent.template_v2.pdf)

I have not yet included a note about referring to the IBM Web Standards when using media, but will be exploring ways to include that info on the page in another ticket. It would be something along these lines. 

> Note: When using media on a page, refer to [Use of images](https://w3.ibm.com/w3publisher/ibm-web-standards-external/standards-mandatory/page-layout-design) in the IBM Web Standards for all type, format, size, and other requirements.
