### ISSUE TITLE
Component content model continued - second sprint

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6847]
This work is ongoing across multiple sprints.  Related issues:  
Sprint 21-16:  (#6772 )

#### Moving forward, let's continue to pick components from the Top priority list, and clean up the content model for them  

Top priority component list based on page visits: https://cognitive-app.slack.com/archives/G01CFF8ETPU/p1624048170003600

- Masthead
- Dotcom shell
- Lead space
- Footer
- CTA section
- Card group
- Card 
- Card section
- Carousel
- Content item / group / block / section

Other related components to consider: 
- Feature card
- Feature section

### Acceptance criteria 

**Aim to finish 2-4 component content models**. Recommend more complex components so we can prepare for any additional complexity that the tables need to accommodate.

**Comment by JBrandwine** [comment]
Component content models drafted:
Content block
Content block cards
Content block horizontal
Content block media
Content block segmented
Content block simple
Content group banner
Content group cards
Content group pictograms
Content group simple
Content group
Feature card
Feature section
Back to top
