### ISSUE TITLE
Website [Images] page refinement 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6872]
A few bug fixes for the new Images page: 

1. Page title should be `Images`
2. New Overview paragraph that's more detailed than Page description
3. Image with caption doesn't' support video
4. Gif on page has dark corners, ideally make them Gray 10
5. Gif on page, when Lightbox is open, there shouldn't be carousel buttons
6. Update the content table based on @JBrandwine 's comment below

**Comment by JBrandwine** [comment]
![image.png](https://images.zenhubusercontent.com/60e469d5eddded36d94e2c43/65b9ecad-6dd0-4cda-8d85-7b31bf59fad1)

**Comment by JBrandwine** [comment]
@RichKummer attached excel sheet so you can copy/paste

[Image with caption content model](https://app.zenhub.com/files/193129061/de5d0fa7-3006-406f-9348-4d98ed72f7d1/download)
