### ISSUE TITLE
[React & WC] Video Player: Allow for caption override

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#6879]
### The problem
The caption rendered with the VideoPlayer is generated from the API. Adopters may want to adjust to fit their needs.

<img width="1432" alt="Screen Shot 2021-08-12 at 3 59 13 PM" src="https://user-images.githubusercontent.com/54281166/129261580-9b18f2b3-daed-41b7-aba8-4a58d2d97910.png">

### The solution
Allow for override of the caption

### Additional information
- Image Overlay Functional Specs: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Video#1-caption

**Comment by RobertaJHahn** [comment]
Convert to epic, dev issues & QA issues
