### ISSUE TITLE
[Card section offset] Background image is not positioned right - DDS Consulting

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6883]
Background media is not covering the full width background in Card section offset: https://www.ibm.com/standards/carbon/web-components/?path=/story/components-card-section-offset--default

**Screenshot with annotation**

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/d9155a1c-bd3b-49e3-96ed-9ffbd0b9087c)

**Design specs**

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/0bda77ff-fbbb-403b-90e8-2fd666179421)

----
- Hybrid Cloud developer: 
- [HC Jira ticket]
- Dev estimate:  
- DDS consultant:

**Comment by proeung** [comment]
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2153
HC Engineer Assignee: @mwanberg

**Comment by ariellalgilmore** [comment]
confirmed with @shixiedesign that this has been fixed and can be closed. This was the PR that fixed it https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6809

cc: @RobertaJHahn
