### ISSUE TITLE
[Button group] Web components: icon should top align to button label when label wraps

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6886]
### Details

React version should get an upstream update from [Carbon when their bug](https://github.com/carbon-design-system/carbon/issues/9478) is fixed. But for Web components, I think we are still unclear how to fix the bug: 

Currently, when button label wraps, icon becomes middle aligned: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/950b0071-939f-444f-863e-7cc667868be1)

Expecting: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/a2620a84-400d-4f24-ae88-c7e5cc7706dd)

### Additional information

1. There is a **Button expressive** in Web components of Carbon for IBM.com library. We are not sure if it's still being used: 
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/master/packages/web-components/src/components/button

2. [Carbon react button](https://react.carbondesignsystem.com/?path=/story/components-button--playground) has been evolving and recently gained the `isExpressive` prop. I'm not sure if this is carried over to [Carbon web component button](https://web-components.carbondesignsystem.com/?path=/story/components-button--default)

3. Ideally, Carbon for IBM.com should not have any buttons. We should take buttons from upstream Carbon react & Carbon web components.

**Comment by RobertaJHahn** [comment]
Steps: 1) Change to be made in core Carbon  2)  Make the change in Carbon Web Components  3)  Make the change in Carbon for ibm.com.  

@shixiedesign Could you work with Mike to define the details.  A request would have to be submitted to Carbon, if needed.

**Comment by shixiedesign** [comment]
A bug issue for Carbon is already made. So this issue would just need to take care of the last 2 steps: 
> 2) Make the change in Carbon Web Components 3) Make the change in Carbon for ibm.com.

**Comment by RobertaJHahn** [comment]
@shixiedesign This issue will go into Pending scheduling until the work is done in Carbon.  Could you post a link to the Carbon issue?  Thanks.

**Comment by shixiedesign** [comment]
Here it is: https://github.com/carbon-design-system/carbon/issues/9478
