### ISSUE TITLE
[Masthead/Footer] Accessibility - The WAI-ARIA attribute 'aria-selected' is not valid for the element <a> with WAI-ARIA role 'menuitem' - DDS Consulting

### ISSUE THREAD

**Issue by abhin07** [carbon-design-system/carbon-for-ibm-dotcom#6888]
----
- Hybrid Cloud developer: 
- HC Jira ticket:
- DDS consultant: 

----
IBM Equal Access Accessibility Checker
The WAI-ARIA attribute 'aria-selected' is not valid for the element <a> with WAI-ARIA role 'menuitem'

Element that is showing this error :- 
```
<a aria-selected="false" aria-expanded="false" class="bx--header__menu-item bx--header__menu-title" aria-haspopup="menu" href="javascript:void 0" tabindex="0" part="trigger" role="menuitem">
```

**Comment by RobertaJHahn** [comment]
@Praveen-sr Could you work with Ram to find out whether this bug found by the IBM Equal Access Accessibility checker is valid?  If it is. could you provide us with the priority.  Thanks.

**Comment by Praveen-sr** [comment]
Expected fix: Remove aria-selected attribute from the menu item.

**Comment by andy-blum** [comment]
🔖 [aria-selected logic](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/web-components/src/components/masthead/top-nav-menu.ts#L40-L42)

🔖 [aria-selected-based styles](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/styles/scss/components/masthead/_masthead.scss#L336-L347)

@annawen1 (cc: @huntermacd)

Currently, the `dds-megamenu-top-nav-menu`'s trigger element is targeted in the styles based on `aria-selected=true` to apply the blue underline in the masthead. How do you recommend maintaining the styling here?

**Comment by annawen1** [comment]
I believe we initially added the `aria-selected` attribute because we needed to indicate to screenreaders that the menu item had selected styling. So I would hesitate to remove it without checking with our accessibility QA team. I will bring this up to them.

**Comment by annawen1** [comment]
Ah I just noticed the above comment from Praveen

> Expected fix: Remove aria-selected attribute from the menu item.

In that case @andy-blum can we instead use `selected` attribute instead of `aria-selected`? We can then change the style to use the `selected` attribute.
