### ISSUE TITLE
[Masthead/Footer] Accessibility - Form control element <select> has no associated label

### ISSUE THREAD

**Issue by abhin07** [carbon-design-system/carbon-for-ibm-dotcom#6889]
IBM Equal Access Accessibility Checker
Form control element <select> has no associated label

Elements showing this error
```
<select ng-reflect-is-disabled="false" ng-reflect-model="10" id="pagination-select-items-per-page-0" class="bx--select-input ng-untouched ng-pristine ng-valid">
<select ng-reflect-model="1" ng-reflect-is-disabled="false" id="pagination-select-current-page-0" class="bx--select-input ng-untouched ng-pristine ng-valid">
```

**Comment by RobertaJHahn** [comment]
@Praveen-sr Could you work with Ram to see whether this bug identified by the IBM Equal Access Accessibility Checker is valid?  If it is, could you let us know what the priority would be.  Thanks.

**Comment by kennylam** [comment]
@abhin07 The masthead/footer components do not contain any pagination elements. Can you provide the page where you see these warnings, please?

**Comment by abhin07** [comment]
@kennylam Apologies, this looks like an error on IBM carbon components. I guess I opened this one by mistake.

**Comment by RobertaJHahn** [comment]
Closing based on comments above.
