### ISSUE TITLE
[CTA - Card, type Video] functional specs - should allow poster image to be turned off 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6933]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the [CTA - Card, type Video] functional specs 

> so that I can:
so that I can properly code the [CTA - Card, type Video] components that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#6413)**

#### Acceptance criteria
 - [ ] Documented [CTA - Card, type Video] functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by photodow** [comment]
Updates can be found [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/CTA) once https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1173 gets merged.
