### ISSUE TITLE
[Card] CTA text doesn't wrap

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6935]
**Current in Canary**

When CTA text is long, the text doesn't wrap, instead goes outside the card: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/f1f4c868-5b0d-40b8-a950-fed05e2a8af9)

**Expecting**

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/480362e2-0b4b-48b6-8ecc-5569da55747a)

**Comment by MeerHamza1421** [comment]
Hey👋,  can I give it a try?
