### ISSUE TITLE
[Beacon] Clean up the NextJS and Web Components test applications to validate that the reporting is helpful

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6941]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
clean up the NextJS and Web Components test applications 

> so that I can:
validate the effectiveness of the Beacon audits and reporting

#### Additional information

- **See the Epic (#6940) for the project overview**
-  A copy of this issue was created in the Beacon for ibm.com repo. [issue 34](https://github.com/IBM/beacon-for-ibm-dotcom/issues/34)

#### Acceptance criteria
- [ ] NextJS and Web Components test applications clean up is finished
- [ ] Review the results with Design and DDS Leads
- [ ] Scoring algorithm adjustments are made
- [ ] Identify any missing audits
- [ ] Necessary audit adjustments are made

**Comment by RobertaJHahn** [comment]
Roberta will schedule a meeting to review the audit results and define changes in sprint 20.

**Comment by RobertaJHahn** [comment]
Kenny will make changes uncovered in the adotper meetings  Beacon changes from the adopter meetings:  
1)  US Home page team is not loading v18, but are getting penalized for using Northstar class names
2)  Identify where in the page invalid tokens are used.
3)  Ensure that the token values pulled in are the latest
4)  Loading of the cookie preferences link throws an error.  Need to fix the timing
5)  Create better descriptions if adopter uses an older Carbon version

**Comment by kennylam** [comment]
@RobertaJHahn issues have been created in the [Beacon](https://github.com/IBM/beacon-for-ibm-dotcom/issues) repository.

**Comment by RobertaJHahn** [comment]
Closing this issue as a copy has been created in the Beacon for ibm.com repo.  [issue 24](https://github.com/IBM/beacon-for-ibm-dotcom/issues/34)

**Comment by RobertaJHahn** [comment]
Closing as a copy of this issue has been created in the Beacon repo.  [issue 34](https://github.com/IBM/beacon-for-ibm-dotcom/issues/34)
