### ISSUE TITLE
[Beacon] Run Beacon against the ibm.com/account web page

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6942]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
run Beacon against the ibm.cm web page

> so that I can:
continue to refine the effectiveness of the Beacon audits and reporting

#### Additional information

- **See the Epic (#6940) for the project overview**
- 

#### Acceptance criteria
- [ ] Review the results with Design and DDS Leads
- [ ] Scoring algorithm adjustments are made
- [ ] Necessary audit adjustments are made

**Comment by kennylam** [comment]
@jeffchew @ljcarot See audit results below. Old package version usage is a relatively simple fix. Not sure why cookie prefs aren't showing though?

![image](https://user-images.githubusercontent.com/909118/132872685-e081d043-c918-45df-acc6-c99ba448cf8c.png)

**Comment by IgnacioBecerra** [comment]
@kennylam fyi, I pushed a fix for the version bug yesterday 👍
