### ISSUE TITLE
[Video player] With Tab key we are able to reach to the video player but there is no visual focus indicator - DDS Consulting

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6944]
## Detailed description

Issue:
With Tab key we are able to reach to the video player but there is no visual focus indicator.

Expected:
Provide thick and strong visual focus covering the element from all sides border.

Note: working fine in react canary.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/4275a259-9d44-425b-89dd-0a200dcfb934)

----
- Hybrid Cloud developer:   Putra Bonaccorsi
- HC Jira ticket:  https://jsw.ibm.com/browse/HC-2168
- DDS consultant:   Andrew Wang

**Comment by proeung** [comment]
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2168

**Comment by emyarod** [comment]
related https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5805

**Comment by proeung** [comment]
@Praveen-sr I just checked the Web Components canary and the focus styling is showing up just fine (see - [link](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-video-player--default) and attached).

![Screen Shot 2021-08-31 at 5 23 03 PM](https://user-images.githubusercontent.com/1815714/131577999-34198580-754e-43ac-9369-f517247017c2.png)

Looks like the fixes might be coming from @emyarod's PR (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6841). Can you take a look? Happy to close out this issue if the bug has already been fixed.

**Comment by proeung** [comment]
@Praveen-sr @emyarod Any thoughts on what I mentioned above?

**Comment by emyarod** [comment]
@proeung I believe it is a Firefox-only issue
