### ISSUE TITLE
[Video player] With Lightbox Media - Audio plays on the background

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6953]
## Detailed description

Issue: 
Video player With Lightbox Media - When the user does not open the video/ lightbox modal, Audio plays on the background. 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/60b62f46-4520-4f70-8f0f-e25e3913eaa5)

**Comment by emyarod** [comment]
this issue is no longer present when viewing the story by itself, but in storybook if another video player story is viewed in advance, the autoplay issue appears
