### ISSUE TITLE
Component content model continued - third sprint

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6954]
This work is ongoing across multiple sprints.  Related issues:  
Sprint 21-16:  #6772
Sprint 21-17:  #6847

#### Moving forward, let's continue to pick components from the Top priority list, and clean up the content model for them  

[List of components TBD]

### Acceptance criteria 

**Aim to finish 2-4 component content models**. Recommend more complex components so we can prepare for any additional complexity that the tables need to accommodate.

**Comment by JBrandwine** [comment]
Content models drafted: https://ibm.box.com/s/ye8a12p66jrdocx8wyfob5yd74yd1a75


Button group
Callout quote
Callout w/media
Content item horizontal
Filter panel
Horizontal rules
Language Selector
Layout
Lead space
Lead space block
Lead space search
Leaving IBM
Link list
Link list section
Link with icon
Locale modal - region
Locale modal - language
Logo grid
Pictogram item
Quote
