### ISSUE TITLE
Component content model continued - fourth sprint

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#6955]
This work is ongoing across multiple sprints.  Related issues:  
Sprint 21-16:  #6772
Sprint 21-17:  #6847
Sprint 21-18:  #6954

#### Moving forward, let's continue to pick components from the Top priority list, and clean up the content model for them  

Top priority component list based on page visits: https://cognitive-app.slack.com/archives/G01CFF8ETPU/p1624048170003600

- Masthead
- Dotcom shell
- Lead space
- Footer
- CTA section
- Card group
- Card 
- Card section
- Carousel
- Content item / group / block / section

Other related components to consider: 
- Feature card
- Feature section

### Acceptance criteria 

**Aim to finish 2-4 component content models**. Recommend more complex components so we can prepare for any additional complexity that the tables need to accommodate.

**Comment by JBrandwine** [comment]
https://ibm.box.com/s/2drh0lhqrd8eo5tfc8ru46kdp8ckuu1c

Models drafted this sprint:Lead space
Lead space block
Lead space search
Link with icon
Locale modal
Logo grid
Pictogram item
Table of contents
Tabs extended
Tag link
