### ISSUE TITLE
Reuse foundation of expressive kit to create Dotcom kit

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6961]
### Goal 
Goal is to deliver an MVP sketch kit that contains all of the Expressive type styles. 

With expressive theme kit going away, and Carbon v11 not arriving soon, we have a gap where adopters will not have access to the new expressive type styles. This issue (and the related issue on [Figma kit](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/6960)) looks into solving this temporary gap, and also set us up for delivering a future Dotcom Design kit for adopters. 

### Full list of Expressive type tokens are:

https://carbondesignsystem.com/guidelines/typography/expressive

#### and the additional expressive type tokens
- Letter spacing unchanged: `Letter-spacing: .16px`

| Token name | Value |
| --- | --- | 
| `caption-02` | 14px type size, 18px line height | 
| `label-02` | 14px type size, 18px line height | 
| `helper-text-02` | 14px type size, 18px line height | 

An more complete list of type style, but harder to read: https://carbon-elements.netlify.app/type/examples/preview/

**Comment by oliviaflory** [comment]
Label
- [ ] disabled-02
- [ ] inverse-01
- [ ] text-01
- [ ] text-02

Helper text
- [ ] disabled-02
- [ ] text-01
- [ ] text-05

Caption
- [ ] disabled-02
- [ ] inverse-01
- [ ] text-01
- [ ] text-02

**Comment by shixiedesign** [comment]
White kit form Olivia: https://ibm.box.com/s/217nrmwxmufxe14eczdqbq4zf0n83rmd
