### ISSUE TITLE
[Tabs extended] Disabled item borders wrong color on md and sm

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#6986]
## Detailed description

When an item in the accordion version of `Tabs extended` is disabled, and the accordion item appears in `md` and `sm` breakpoints, the disabled item's top and bottom borders appear as the wrong color. The color of the disabled borders should be the same as the actionable item borders, only the text color and icon color are changed visually (see design specs).

Seen in Chrome in Canary Web Components v1.8.1 (http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-tabs-extended--default_ and the new version of the React wrapper for Tabs extended.

**Tabs extended in Canary Web Components v1.8.1**
<img width="780" alt="Tabs-extended-current" src="https://user-images.githubusercontent.com/15643582/130859978-53ed0625-50a8-4b87-a6c5-e9e98d560cb9.png">

**Tabs extended md breakpoint in design specs**
<img width="1190" alt="Tabs-extended-md" src="https://user-images.githubusercontent.com/15643582/130860183-df0f8b5c-e1ef-4d82-ae2e-bd8af7d75db5.png">

**Tabs extended sm breakpoint in design specs**
<img width="1181" alt="Tabs-extended-sm" src="https://user-images.githubusercontent.com/15643582/130860174-466f7fd4-bb73-48b2-a920-bda91391e6e0.png">

**It looks like the issue may be these lines of code effecting the disabled item (through Inspect)**
<img width="1047" alt="Tabs-extended-inspect" src="https://user-images.githubusercontent.com/15643582/130860205-5864da5d-1022-408d-aa6b-2da4289cf2ba.png">

## Steps to reproduce the issue

1. Configure a disabled item in Tabs extended
2. View in breakpoint `md` or `sm`
3. Compare top and bottom border color for disabled item with enabled item

**Comment by emyarod** [comment]
this should be resolved when the `carbon-components` version is upgraded to `v10.43.0` to include the upstream fix https://github.com/carbon-design-system/carbon/issues/9542
