### ISSUE TITLE
[Sticky behavior] Create new component(s) to manage sticky headers

### ISSUE THREAD

**Issue by andy-blum** [carbon-design-system/carbon-for-ibm-dotcom#6994]
### The problem
carbon-for-ibm-dotcom has several elements that have a stick-to-top behavior - the masthead, L1 navigation, and the table of contents immediately come to mind. Right now, managing the elements that stick to the top of the viewport requires managing styles & scripts across three separate components. This feels like an opportunity to abstract that behavior out into a new component

### The solution
I propose a new pair of components, the `<dds-sticky-anchor>` and `<dds-sticky-content>` elements.

The sticky content element would be a wrapper that goes around the content we intend to stick to the top of the page. By moving all the positioning logic to this element we can eliminate the complex web of if-this-then-that that exists now like in PR #6838 

The sticky anchor would be a relatively-positioned block element. It's job is to scroll along with static page content and maintain the height of the content that will stick to the top of the viewport and to act as a "home base" of sorts for elements that might not be at the top of the site on page load.

By initializing these components and watching them with a `ResizeObserver` and an `IntersectionObserver` we can toggle elements from static/relative positioning to fixed/absolute positioning and let the sticky-anchor element set an explicit height  and width to prevent the page content from jumping when we move elements out of the document flow.

Once this is abstracted out, adding additional components with the ability to stick to the top of the page should be trivial

**Comment by proeung** [comment]
@jeffchew Let us know what you think about this enhancement request. We can bring this up to the next DDS Engineering Huddle meeting if that works better for you and your team.
