### ISSUE TITLE
[react-wrapper]: component does not always update with knob changes

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#6995]
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
bug

> Is this issue related to a specific component?

multiple react-wrapper components specifically though CTA Section heading and changing the content items

> What did you expect to happen? What happened instead? What would you like to
> see changed?

When changing the heading the knob the text does not update and when changing to the statistics content item the alignment is off. It works correctly though when opening the story in a new window. 

## Additional information

- could be caused by react usually taking in the text data as an attribute instead of having it be “inline” like in web components

**Comment by andysherman2121** [comment]
Knobs aren't updating due to https://github.com/storybookjs/storybook/issues/16682 
This is being blocked until the storybook team fixes the issue

**Comment by jeffchew** [comment]
@ariellalgilmore saw that this was flagged by stalebot, will upgrading to storybook 6 / controls fix this issue?
