### ISSUE TITLE
[Lead space]: Design work for the skeleton implementation

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7002]
#### User Story

> As a `[user role below]`:
DDS designer

> I need to:
design a solution for AEM

> so that I can:
improve on the flicker behavior users are currently experiencing 

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#6723 )**
- Lee Tsao will attend the Sept 1 Engineering Office Hours: https://ibm.ent.box.com/notes/799374147228

#### Acceptance criteria
- [ ] Meetings with AEM and DDS engineering are conducted 
- [ ] Documented `Lead space` designs

**Comment by shixiedesign** [comment]
### Here's the prototype & spec: 

https://images.zenhubusercontent.com/193129061/43b9ea4c-c773-4bb1-8327-dbd73c88abf8/loading_proto.mp4

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/b2090da8-56b4-4e4d-ae5b-0d1d79f4271d)

For cycling gradient (used https://www.gradient-animator.com/), make sure to use 2 sec
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/f49d36b0-2654-43ce-8e13-79485b11d1f0)
