### ISSUE TITLE
[Dotcom shell] Enable a version of the Dotcom Shell that renders Cloud Masthead and fetches Footer data from the Cloud endpoint

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#7009]
### The problem
- Now that we have a Cloud Masthead component defined within the library, I think it'll be helpful for adopters to have a wrapper component like the `Dotcom shell` that wraps the Masthead and Footer components in a UI shell using Carbon's grid.
- @shixiedesign, let me know if this request makes sense and whether we need to review this with the larger design team as well.

### The Solution
- This version of the `Dotcom shell` component renders the Cloud Masthead + Megamenu with the correct attributes/props and fetches the Footer data from the Cloud endpoint.

```
<dds-dotcom-shell-container>
  platform="Cloud"
  data-endpoint="/common/carbon-for-ibm-dotcom/translations/cloud-masthead"
></dds-dotcom-shell-container>
```

**Comment by RobertaJHahn** [comment]
Investigate whether the Cloud Masthead and the global Masthead will converge.  If so, timeframe?
This includes discussions with Keegan.

**Comment by proeung** [comment]
@RobertaJHahn Yeah, this is something that I'd like to touch base with Keegan, once the new Cloud Masthead launches. This is just a post-launch follow-up ticket for us to track once we're at a place where the Cloud Masthead is no longer a feature flag and that we can converge the two variations into one component or keep them separate.

I'm going to mark this issue as a low priority and move it to a later milestone.

**Comment by jeffchew** [comment]
Need to set up a call to discuss this work, also may need to include some form of education on using this rather than using the Masthead/Footer adhoc on the page.

**Comment by jeffchew** [comment]
this issue can be closed out, superceded by https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8240.
