### ISSUE TITLE
Difference in Storybook navigation

### ISSUE THREAD

**Issue by IgnacioBecerra** [carbon-design-system/carbon-for-ibm-dotcom#7013]
The component list seems to be ordered in a different order in each library. For example, in React, the CTA component is listed before “Callout quote”, whereas Web Components follows proper alphabetical order. 

We should aim for the same alphabetical order in both environments.

#### Additional Infomration
- The Storybook configuration file needs to resort the stories before outputting
- The general documentation should not be included in the resort.  It should still remain on top

**Comment by jeffchew** [comment]
Bringing back to triage, we don't have a severity/priority for this.
