### ISSUE TITLE
Difference in Story media content

### ISSUE THREAD

**Issue by IgnacioBecerra** [carbon-design-system/carbon-for-ibm-dotcom#7014]
Once we got rid of the pink example images, it seems that certain images started being used in React, while a different set of images were used in Web Components. We now have differences in images between the libraries.

Components affected:
* Callout with media
* Card Group w/Images
* Card section images
* Content Block Cards
* Content Block Segmented
* Content Group Simple
* Feature Card 
* Leadspace
* Leadspace Block

**Comment by jeffchew** [comment]
Bringing back to triage, we don't have a severity/priority for this.
