### ISSUE TITLE
[React] Move internal components under components folder

### ISSUE THREAD

**Issue by IgnacioBecerra** [carbon-design-system/carbon-for-ibm-dotcom#7016]
One thing that caught my eye is that internal components such as 
* ContentBlock
* ContentGroup
* ContentItem
* ContentSection

Are still within the `internal` folder in React. In Web Components, there is no internal directory and all the aforementioned components are located alongside the rest of the components. We could maybe use a small cleanup to have a similar directory structure between our libraries, similar to how there was one for `scss/internal` some time ago.

**Comment by RobertaJHahn** [comment]
Closing.  Dup of #6698
