### ISSUE TITLE
Investigate a way to inject markdown templates into other markdown files

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#702]
#### User Story

> As a `[user role below]`:
IBM.com Developer

> I need to:
find a way to inject repeating content into multiple markdown files

> so that I can:
manage repeating content in a single place and reduce any future maintenance of this content

#### Acceptance criteria
 - [ ] Determine if there is a mechanism to inject markdown into other markdown
 - [ ] Assess work involved, and create any additional issues if necessary

**Comment by kennylam** [comment]
This seems to be a long-standing request of the GH team, and at the moment they still have no plans to offer this feature.
https://github.com/github/markup/issues/172#issuecomment-33241601
https://github.com/github/markup/issues/1159

There are packages that provide this functionality. They would need to be added locally so the markdown can be compiled before pushing to the repo
https://github.com/BurdetteLamar/markdown_helper#markdownhelper

**Comment by jeffchew** [comment]
Do we want to try one of these? Or maybe icebox this for now? I'm leaning towards the latter...

**Comment by kennylam** [comment]
@jeffchew I agree with icebox for now. Not crazy about the available solutions. If we find that we really need to avoid duplication and want to consolidate, we could always have a markdown file just for that content and link to it.

**Comment by RobertaJHahn** [comment]
This issue was put in icebox to keep until the resources are available to do the work.

**Comment by RobertaJHahn** [comment]
Closing based on Carbon's experience with this approach.
