### ISSUE TITLE
[Feature CTA - video] Component doesn't play video.

### ISSUE THREAD

**Issue by guilhermelMoraes** [carbon-design-system/carbon-for-ibm-dotcom#7033]
> What did you expect to happen? What happened instead? 

`dds-feature-cta` should play a video when the type is set to `video`.  Instead, it doesn't play the video. When clicked, it redirects to the storybook iframe view.  

> Component(s) impacted? Please include screenshots, or code and relevant URLs.

This issue is web components only. It can be reproduced on the canary. 
`dds-feature-cta`, affecting only the `video` variation.

http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-cta--feature

Steps to reproduce the issue (if applicable):

1. Open this [URL](http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-cta--feature);
2. In the knobs panel, set the `type` to `video`;
3. Click on the feature CTA.

**Comment by RobertaJHahn** [comment]
@guilhermelMoraes There should be a PR linked to this issue if it is in Review.
