### ISSUE TITLE
[Masthead]: Default to the correct translation endpoint for application calling just lc/language code in the URL parameter

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#7060]
### The problem
- The `cloud.ibm.com/docs` application is currently loading just the language code within its `?locale= parameter` (eg. https://cloud.ibm.com/docs?locale=es) where other content ecosystems like Drupal is using both `lc` and `cc`.
- This is a feature that has not yet been accounted for in the Masthead component data fetching script.
- Docs mentioned that altering their parameter to accept both `lc` and `cc` will requires some changes in their current translation files which they're not in the position to adjust.

### The solution
- Figure out a checking mechanism that fetches the correct translation without having the country code/cc in the URL parameter.

![Screen Shot 2021-09-02 at 4 58 15 PM](https://user-images.githubusercontent.com/1815714/131915200-83c7008b-5008-4981-b558-0566a6dd671a.png)

**Comment by RobertaJHahn** [comment]
Included in the Sept 13 Engineering Issues Review meeting agenda.

**Comment by RobertaJHahn** [comment]
1)  Convert to an epic.  2)  Circle back with Linda to get an estimate from the translation team regarding the availability of the needed files

**Comment by proeung** [comment]
@jeffchew @RobertaJHahn  Looks like this workaround (https://github.ibm.com/webstandards/ibm-dotcom-translations/pull/427) doesn't work for the Cloud Docs application (see [slack thread](https://ibm-marketing-comms.slack.com/archives/G01LKRP5RB6/p1631645600041000?thread_ts=1630614053.029600&cid=G01LKRP5RB6)). We might need to adjust the priority of this issue. Let me know what you both think.

**Comment by RobertaJHahn** [comment]
@proeung We will talk about this topic in our Adopter Issues review meeting tomorrow morning, 9/16.  We have a dependency on translation files from another team, I'll update this issue when there is more information.

**Comment by RobertaJHahn** [comment]
1)  The Locale service change:  The locale API needs to add flixibility to only fetch the LC code  2)  The Translation service api needs to pull the corresponding translation file if only lc is provided.

**Comment by RobertaJHahn** [comment]
Issues needed:  1 dev issue to update the services, Prod QA testing of both React & WC.

**Comment by proeung** [comment]
Once, the PR for this work is ready for review, please reach out to the Docs/KC team (Mark Kulube and Jenifer Schlotfeldt) to review and test the work within their application.

**Comment by annawen1** [comment]
> @RobertaJHahn @annawen1 Looks like the two issues that are associated with this EPIC have been closed. Is there anything else that we need to follow up on for this request? If not, I think we can close this issue out.

Yeah looks like we're good to go in closing this one. @RobertaJHahn?

**Comment by RobertaJHahn** [comment]
@proeung @annawen1 I assigned to the release, updated the Roadmap dates and closed.  Thanks for the head-up.
