### ISSUE TITLE
Feature Section link does not open in new tab

### ISSUE THREAD

**Issue by EAVilleda** [carbon-design-system/carbon-for-ibm-dotcom#7072]
![image (2)](https://user-images.githubusercontent.com/47429622/132357820-8c21a6ad-56d0-4172-8754-450a53ea1e5c.png)
Describe the issue: 

We’re running into an issue where the smaller card in the bottom right of Feature Section has a target of _blank but it’s not opening the link in a new tab. I tried adding target=“_blank” in the Storybook example to see if it works there, and it didn’t work there either. https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-feature-section--default

Steps to reproduce the issue (if applicable):

1. Create Feature Section
2. Add target="_blank" to smaller card
3. Click on card, link opens in same tab

## Additional information
-  Engineering info:  
     - HC engineer: @proeung 
     - JC Jira Ticket: https://jsw.ibm.com/browse/HC-2217
     - DDS consulting engineer:

**Comment by RobertaJHahn** [comment]
DDS dev:  Need to replace card with the card link CTA.
