### ISSUE TITLE
[Figma kit] Add Grid & Color to design kit 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7077]
Other foundational elements to Carbon for Dotcom: 

- [Color](https://carbondesignsystem.com/guidelines/color/usage) 
- Grid 
- Icon (potentially a big lift)
- Spacing (less essential) 

### Task 

Starting with adding **Grid & Colors tokens** as shareable styles to design kit.

**Comment by RichKummer** [comment]
Updated Figma kit can be found here: https://www.figma.com/file/O6R9yl3wXFyBry4l2tz6h4/Carbon-Expressive-Type-and-Color?node-id=0%3A1
