### ISSUE TITLE
[v18] adding banner content for 'Think Summit Japan 2021' 

### ISSUE THREAD

**Issue by tanglili123** [carbon-design-system/carbon-for-ibm-dotcom#7091]
Japan team wants to launch the 'Think Summit Japan 2021' banner in accordance with the 'Think 2021 Universal Promo Banner'. Could you please help confirm that the following information provided can be carried out?

'Think 2021 Universal Promo Banner' Sample>> (Template image attached)
https://ibm-translations-v18.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/299/index.html?locale=jp-ja
background video>>
https://1.dam.s81c.com/public/content/dam/worldwide-content/homepage/ul/g/c0/f7/think2021-registration-masthead-banner-bg-new.webm

【'Think Summit Japan 2021' banner info】
1.left text of the banner>>
「テクノロジーと共創で切り拓く新時代」
日本IBM最大のデジタル・イベント 10月5日(火)-8日(金)開催

2.right text of the banner>>(Click anywhere on this banner can go to the link)
Button text>>
詳細・お申し込み（無料）→
Button link>>
https://www.ibm.com/ibm/jp/ja/events/think-summit/
(※message from Sponsor>> We are currently checking the data measurement method with WW team, so we may add tags to the URL future.)

3.period: ASAP ~ Oct. 8, 2021
※Please delete the banner in the morning of 10/8.
4.including the following domains>>
/jp-ja/cloud
/jp-ja/watson
/jp-ja/services
/jp-ja/it-infrastructure
/jp-ja/security
/jp-ja/analytics
/jp-ja/about
/jp-ja/products
/blogs/think/jp-ja/
/think/jp-ja/business/
/blogs/security/jp-ja/
/blogs/systems/jp-ja/

![sample image](https://user-images.githubusercontent.com/90363684/132608909-c09b017f-39f0-4196-b53a-b51a9c646f27.png)

**Comment by jeffchew** [comment]
Created follow-on issue for disabling the banner: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7104

**Comment by jeffchew** [comment]
PR created with deploy preview: https://github.ibm.com/webstandards/ibm-dotcom-translations/pull/432
