### ISSUE TITLE
Website Standards: Gatsby update needed 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7092]
Mike Abbink's update request: 
> Hi Shix, Who can update the Web Standards site to the latest Gatsby theme which should bring in the latest switcher too. The current one is months old.

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/b12be701-7643-4851-bfe2-9976b61f9458)

**Comment by jeffchew** [comment]
@shixiedesign created an upgrade bot to auto create PRs with gatsby upgrades when available. First successful PR generated by the bot: https://github.ibm.com/webstandards/standards-website/pull/18
