### ISSUE TITLE
[Video player] Parameters for Thumbnails (resolution, aspect ratio)

### ISSUE THREAD

**Issue by dratzenboeck-ibm** [carbon-design-system/carbon-for-ibm-dotcom#7093]
### The problem
On some web components where a video is used, it is fetching a thumbnail with a too low resolution from Kaltura. That results in an image being pixelated. Sometimes it is also using the wrong aspect ratio for the thumbnail. 
Example:
https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-card-in-card--default&knob-video=true&knob-Image%20alt%20text%20(alt):=Image%20alt%20text&knob-Image%20src%20(defaultSrc):=f9bc0ff2cb7e5cbd748ea2f65ddf1962.jpg&knob-Card%20Heading%20(heading):=Standard%20Bank%20Group%20prepares%20to%20embrace%20Africa%E2%80%99s%20AI%20opportunity&knob-Card%20Href%20(href):=https://example.com&knob-Card%20Eyebrow%20(eyebrow):=Label

### The solution
**Best Case:**
All web components that use video thumbnails (Video, Card Ctas, etc.) provide parameters that map 1:1 to parameters of the kaltura thumbnail API **("width", "height", "type"  and "nearest_aspect_ratio" should be enough).** So that I can set the resolution and aspect ratio of the thumbnail depending on the context. 
Optional: Maybe it could be useful to set these parameters per breakpoint to also optimize the thumbnail, but I think that is not necessarily needed. 
**Easy Solution:**
The defaults for web components with big video thumbnails are updated. 
I found the issue regarding bad image quality in

- Card in Card: https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-card-in-card--default&knob-video=true&knob-Image%20alt%20text%20(alt):=Image%20alt%20text&knob-Image%20src%20(defaultSrc):=f9bc0ff2cb7e5cbd748ea2f65ddf1962.jpg&knob-Card%20Heading%20(heading):=Standard%20Bank%20Group%20prepares%20to%20embrace%20Africa%E2%80%99s%20AI%20opportunity&knob-Card%20Href%20(href):=https://example.com&knob-Card%20Eyebrow%20(eyebrow):=Label
- Feature Card: https://www.ibm.com/standards/carbon/web-components/?path=/story/components-feature-card--large (no option for video in story book)

### Additional information
Kaltura Video Thumbnail API: https://developer.kaltura.com/api-docs/Engage_and_Publish/kaltura-thumbnail-api.html

**Comment by RobertaJHahn** [comment]
There is an enhancement included in the v1.25.0 release (Sept 28 release date) to override the video image.  This will provide a work around until this enhancement is available.

**Comment by RobertaJHahn** [comment]
Issues needed:  Func specs, WC & React Services update, QA issues, website update
