### ISSUE TITLE
[Masthead] Web component and React version discrepancies

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon-for-ibm-dotcom#7116]
original discussion https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7100#issuecomment-916496424 

while taking a look at the masthead I found some discrepancies between `web-components` and `react`:

* the category heading arrow doesn't appear in the web components masthead
* the horizontal rule under the category headings have different lengths

web components:
![image](https://user-images.githubusercontent.com/8265238/132773216-fba8acb8-8cde-44db-8bdc-57001164f16d.png)

react
![image](https://user-images.githubusercontent.com/8265238/132773233-145bc0c3-f39c-4a50-9e14-e6148c14d462.png)

the spec file seems closer to web components but it may also require an update

----

Another instance found for **Services & consulting > Talent management services**
Web components: it's not a link, and no arrow:
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/72cc265e-5622-4ae6-a6be-26da3939c599)
React: it's a link, and arrow is a bit cropped: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/13c0f4a6-b2aa-4894-b7b5-084ec64b2ce6)

**Comment by RobertaJHahn** [comment]
Updating the labels and letting Shixie know that some design work is needed for this issue.  @shixiedesign how / when do you want to move this work forward?  For background, here is a copy of my Slack with Andrew.

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/13b8ab4d-5187-438b-a9e0-8a16ddffb845)

**Comment by shixiedesign** [comment]
Link or not link, React is correct. This is strange to me. Shouldn't they both be pulling the same json file? 

Styling wise, Web components is correct! And once the heading is a link, there should be an arrow to indicate it. Here's the design: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/9e23397b-05e1-4d46-bfdf-801b25ad5320)
