### ISSUE TITLE
[Card Section Offset] Main Card Link Target Issues - DDS Consultant

### ISSUE THREAD

**Issue by druckerk** [carbon-design-system/carbon-for-ibm-dotcom#7119]
Describe the issue: 

> What did you expect to happen? What happened instead? 
When setting the link target type to open in a "new tab" for the link on the main card, the HTML code will appear correctly (target="_blank"). But, when clicking on the link it will open the link as if the target is set to "_self" vs opening in a new tab. 

> Component(s) impacted? Please include screenshots, or code and relevant URLs.
The component impacted by this issue is the Card Section Offset and Feature Card Section component.

![Screen Shot 2021-09-08 at 4 16 44 PM](https://user-images.githubusercontent.com/88403358/132900621-f7e297de-0dc5-4207-aee0-44108078836a.png)

> What browser(s)are you working in?
Chrome

> What version of Carbon for IBM.com are you using?
Carbon version 1.8.0

> What application/website do you work on? 
AEM

> Release date (if applicable):

Steps to reproduce the issue (if applicable):

1. created a new page using the Learn Landing page template
2. Add the Card Section Offset or Feature Card Section component to the body section.
3. In the component properties, go to the Link Properties or Main Card Content tab and enter the href link field and set the Target to New Tab. 
4. Once the Feilds are set, view the page as Published and click on the link you set to open in a new tab. 

## Additional information
-  Engineering info:  
     - HC engineer: @jkaeser 
     - JC Jira Ticket: https://jsw.ibm.com/browse/HC-2203
     - DDS consulting engineer:  @emyarod

**Comment by proeung** [comment]
This issue looks to be similar to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7072, where the link target attribute is not being rendered in the shadow DOM.

**Comment by proeung** [comment]
@druckerk Similar to the solution in this PR (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7250/files#diff-7647fb7aae8ef874b2eec930a5a72ff6dbcedcccc17d4947fbd07d2941e4e70eR23), I think we need to adjust the `DDSLinkList` component to extend from `DDSTextCTA`. @ariellalgilmore let me know if you agree.

**Comment by ariellalgilmore** [comment]
Hi @proeung! I'm trying to follow this issue, but it would be helpful to get some clarification on what the actual issue is becuase there is no DDSLinkList in DDSCardSectionOffset. When needing to change a link to open in an external link you can add the attribute `cta-type="external"`. For example you can see the use case in this storybook http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-content-item-horizontal--default
<img width="1246" alt="Screen Shot 2021-09-29 at 11 40 15 AM" src="https://user-images.githubusercontent.com/20210594/135302450-294fc792-871f-4682-8fba-85bc62e2d6b9.png">

**Comment by jkaeser** [comment]
@emyarod @ariellalgilmore It seems to me the request is to allow CTAs that are not `cta-type="external"` to open in a new tab/window. Currently, https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/web-components/src/component-mixins/cta/cta.ts#L137 stops this from happening by overriding any attempt to manually set the target. Is that the desired behavior?

**Comment by emyarod** [comment]
@jkaeser from my understanding if the link will open in a new tab/window then the `cta-type` should be `external` https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/CTA#user-content-13-external. not sure if the design intent is to allow `local` type CTAs to also open a new tab/window but I will defer to design
