### ISSUE TITLE
Can't find Accordian CDN/Vanilla JS

### ISSUE THREAD

**Issue by SeanDKendle** [carbon-design-system/carbon-for-ibm-dotcom#7121]
Why is there no Accordian component available for Carbon for IBM dotcom/Web Components? I need a CDN version of this for Vanilla JS, please!

**Comment by jeffchew** [comment]
The accordion is available under `Carbon Web Components`:

https://web-components.carbondesignsystem.com/?path=/docs/components-accordion--default

The CDN version is available here:

https://github.com/carbon-design-system/carbon-web-components#using-cdn
