### ISSUE TITLE
Continued Sketch kit for Gray 10, Gray 90, and Gray 100 themes

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7138]
Follow on of #6961 

Olivia has delivered a White theme kit here 
https://ibm.ent.box.com/folder/144108011596?s=q5wc5ivh0h2wl0o4aqosqmxt2exrjn5e

Task for this issue is to continue design kit for 
- [x] Gray 10 theme kit
- [x] Gray 90 theme kit
- [x] Gray 100 theme kit

Containing the following symbols:
- all IBM type styles, productive + expressive 
- all Carbon color tokens

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/8728fb9e-0d0a-4af6-a97d-ce9bc2643de7)

**Comment by DragosRistici** [comment]
Added the Gray 10 and Gray 100 themes in [this Box folder](https://ibm.ent.box.com/folder/144108011596?s=q5wc5ivh0h2wl0o4aqosqmxt2exrjn5e).

**Comment by shixiedesign** [comment]
@RichKummer will be taking Gray 100 theme kit.

**Comment by RichKummer** [comment]
Added the Gray 100 theme to the Box folder
