### ISSUE TITLE
[Card - logo] Web Component: Develop a card variation dedicated to logo / app icons - DDS consulting

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7139]
**Engineering info:**  
- HC engineer: @proeung 
- HC JIRA Ticket:  https://jsw.ibm.com/browse/HC-2312
- DDS consulting engineer: @IgnacioBecerra 

----

#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `Card - logo`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic (#6592 ) for the Design and Functional specs information**
- [Design and functional spec Box folder](https://ibm.ent.box.com/folder/95514001950s=hgvu48r1fv2ga2h0yn3qshrtxjc71vch)
- Web Components Visual QA testing issue (#7142)
- Web Components Prod QA testing issue (#7144)

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by proeung** [comment]
@RobertaJHahn Is this feature on the agenda for the 09/27 "Engineering Epic and Story refinement" meeting? If so, I'd like to attend to review the design and functional specs of this logo/app icon variation within the Card component.

**Comment by RobertaJHahn** [comment]
@proeung The designs were just finished in the current sprint.  The functional specs are scheduled in the next sprint, 9/27 - 10/8 so the review will not be scheduled until the func specs are done.

**Comment by proeung** [comment]
I see. Thanks for the update!
