### ISSUE TITLE
Masthead: dds-left-nav-menu-sections don't align properly if some have scrollbars and others dont

### ISSUE THREAD

**Issue by andy-blum** [carbon-design-system/carbon-for-ibm-dotcom#7159]
Describe the issue: 

> What did you expect to happen? What happened instead?

Discovered this during work on #6676.

When moving between left-nav-menu-sections, I expect the 'pages' of menu items to properly align within the left-nav wrapper element regardless of if the menu-section has y-axis overflow. Currently, moving to a menu-section with a vertical scrollbar causes all menu-sections to lose their proper alignments, and breaks the overall usability of the left-nav menu system

> Component(s) impacted? Please include screenshots, or code and relevant URLs.

dds-left-nav, dds-left-nav-menu-section

![Screen Recording 2021-09-15 at 3 11 05 PM](https://user-images.githubusercontent.com/25532785/133495901-01aef21b-fe61-4bac-9077-05d41c201ab1.gif)

> What browser(s)are you working in?

Encountered in Chrome and Firefox

> What version of Carbon for IBM.com are you using?

Latest/Dev

> What application/website do you work on?

IBM Cloud

Steps to reproduce the issue (if applicable):

1. Open dotcom shell
2. Shrink browser window to get hamburger menu
3. Open hamburger menu and navigate to any item with vertical overflow
4. Navigate back or close menu

**Comment by RobertaJHahn** [comment]
@andy-blum Does this behave this way on mobile or just tablet?

**Comment by andy-blum** [comment]
@RobertaJHahn In my testing it's been in the left-nav component at all widths

**Comment by andy-blum** [comment]
@RobertaJHahn I'm about to push a change to #7161  that should fix this for good.

**Comment by annawen1** [comment]
@andy-blum looks like your PR fixed it, can we go ahead and close this issue?

**Comment by andy-blum** [comment]
Works for me!

**Comment by annawen1** [comment]
Thanks @andy-blum!
