### ISSUE TITLE
ToC Anchor jump destination wrong if Leadspace is added - DDS consulting

### ISSUE THREAD

**Issue by skycryer** [carbon-design-system/carbon-for-ibm-dotcom#7191]
### Description

On a page with ToC with Leadspace component added the jump destination is wrong, page does not scroll enough.

### Component(s) impacted

ToC, Leadspace

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v1.23.0

### Business priority

High Priority = pressing release

### Application/website

IBM CMS

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

Not available

### Steps to reproduce the issue (if applicable)

Add ToC with several components for anchor positions, add Leadspace, click on the Anchor and check for page scroll position

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues
<img width="1680" alt="Screenshot 2021-09-13 at 14 04 59" src="https://user-images.githubusercontent.com/3725699/134016512-0af862d7-3210-4809-8d2e-c1b63197ba29.png">

## Additional information
-  Engineering info:  
     - HC engineer: TBD
     - JC Jira Ticket: https://jsw.ibm.com/browse/HC-2201
     - DDS consulting engineer:  @guilhermelMoraes

**Comment by RobertaJHahn** [comment]
Slack message from Christian:
![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/302af13b-810e-44bb-8c34-d8f4822c693f)
