### ISSUE TITLE
[Tabs extended] Remove content area padding

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7206]
Tabs extended component should not come with padding within the content area. However, if this is just how our storybook example is authored, that's okay. Just need to double check the padding around content area is not part of the component: 

**Current:** 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/3796b5f6-a6a8-47ca-994a-6cc37a75963d)

**Expecting:**
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/1ef86513-b64a-4562-91a7-eac35fdec4d7)

**Engineering info:**  
     - HC engineer: @proeung 
     - JC Jira Ticket: https://jsw.ibm.com/browse/HC-2247
     - DDS consulting engineer: N/A

**Comment by proeung** [comment]
@shixiedesign Looks like these paddings are coming from the carbon `.bx--tab-content` class (see attached) and not something that's being shown for the Storybook preview. Is this something that you'd like to be removed and add spacing around the placeholder text area?

![Screen Shot 2021-10-06 at 1 21 47 PM](https://user-images.githubusercontent.com/1815714/136253197-f3478d3d-77af-453e-8b58-e35a66ba17b7.png)
