### ISSUE TITLE
[Masthead, login] Design exploration

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7210]
### The problem

Login/Profile section of Masthead currently is a bit of a mess. [More details soon]

![image](https://user-images.githubusercontent.com/15144993/121599729-7ae4c580-ca11-11eb-94de-09f3f1642dfd.png)

Cloud masthead 
https://ibmdotcom-web-components-experimental.mybluemix.net/?path=/story/components-cloud-masthead--default
![image](https://user-images.githubusercontent.com/15144993/121600114-02cacf80-ca12-11eb-9cb7-042b225376db.png)

### Stakeholders & people in the field

- Login button currently takes people to **MyIBM**, which is owned **Jeff Mitchell** and designers involved are **Brandon Appe** and **Douglas Henry**. 

- **Cloud / Hybrid cloud** created their own masthead with primary button etc. Designer is **Lila Tittle** and IA comes from **Keegan Whitla**.

### To be figured out

1. this login / profile has to be for MyIBM, correct? was there a reason the current button gives 2 options: MyIBM and Login, instead of just 1 for login?
2. once logged in, we allow users to modify the dropdown from profile button, but is the default list of options all required? 3. Currently there are 4 options after logging in: MyIBM, Profile, Billing, Log out. In another words, would we need to consider grouping the options here.
4. Can we create new features here? Eg. showing user’s notifications such as product updates available, subscription expiring soon, etc
5. Does IBM has a rule against letting users creating avatars? I have vague memories of such things when Sheina was working on URX.

**Comment by skuruvil** [comment]
Sketch file (WIP) is here https://ibm.ent.box.com/folder/146390948927
