### ISSUE TITLE
[Universal banner]: Spec for how Masthead may appear below banner (desktop, mobile)

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#7216]
### Overview
This problem was seen when the Cloud MH was introduced on the [v19a page and the yellow translation banner appears](https://www.ibm.com/sg-en/cloud/application-modernization).

- This behavior should be resolved in the Universal banner designs and func specs.  This FR has been linked to the Universal Banner epic (#6547) and included in sprint 21-10 for the designer working on the functional specs in that sprint to revisit the designs to be sure that this problem is addressed.  

### The problem

The current masthead doesn't seem to account for banners above and overlaps them. An issue was brought up with when the cloud-masthead is used with the locale banner: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7211

Currently the Cloud pages override the `position: fixed` style of the masthead by setting to `position: static` when banner is seen, and setting it back to `position: fixed` when banner is scrolled out of view. The Carbon THINK banner Ryan had created uses similar logic to override our masthead positioning.

<img width="1677" alt="Screen Shot 2021-09-21 at 4 04 31 PM" src="https://user-images.githubusercontent.com/54281166/134240123-e122633b-9e1c-4159-8299-9f4c2f610608.png">

### The solution

Detect when there is a banner above the masthead and correct the position to static. When banner is scrolled out of view, the masthead can be set to `fixed`. Not sure if this needs to be separated into a wrapper component or can be part of the masthead?

Ensure that the scrolling behavior of the masthead maintains the expected behavior when there is an L1 / TOC / L1 & TOC.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@annawen1 Thanks for opening this feature request issue! Once, these changes are implemented in the WC package, we (HC) can clean up the extra styling/logic that is added on the Drupal side.

**Comment by shixiedesign** [comment]
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/ae50610c-0e32-4c23-9563-620928c71a06)

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/314c4979-2aac-4cb4-8a77-fcd80169baf3)

**Comment by shixiedesign** [comment]
QQ for @RobertaJHahn this issue is not done, but is there dev task following? The change is made to Universal banner component's design spec. Maybe there's no dev task until we start [developing Universal banner](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/6814)?

**Comment by RobertaJHahn** [comment]
@shixiedesign There is a dev issue for Web Components, #6814 and React Wrapper #6815 .  I have also included review of the designs and func specs in the Nov 8 Engineering Issues Refinement meeting agenda.  https://ibm.ent.box.com/notes/825037557515

**Comment by photodow** [comment]
Do any functional specs need to be updated on this? It doesn't appear to be any particular function on the banner itself. The masthead really isn't changing either, except calling out that things might could live above it? Very similar to horizontal tabs. It's static until it hits the top of the page?

**Comment by shixiedesign** [comment]
TY @RobertaJHahn 
Re @photodow I don't think it's a functional change to the banner. I'm unsure *where* the calculation / logic has to be added for the masthead and mega menu to be aware of the banner's existence. Let's check with devs on Nov 8. If this is a function to add to Masthead, we can make a func spec update to Masthead.
