### ISSUE TITLE
Different ipcInfo cookie value set dotco footer component & legacy ibm.com script (v18)

### ISSUE THREAD

**Issue by sanjitbauli** [carbon-design-system/carbon-for-ibm-dotcom#7226]
### Description

When i use language switcher on the IBM home page (https://www.ibm.com/us-en/) (Non-carbon version) to change the language to for example Russian federation - Russian
The ipcInfo cookie value set to 
`cc%3Dru%3Blc%3Dru%3Bac%3Dall`
when I parse the value using `queryString.parse(ipcInfo.replace(/;/g, '&'))` it became this object 
`{ ac: 'all', cc: 'ru', lc: 'ru' }`

Now using dotcom footer component, when do the same thing the cookie value is
`cc%253Dru%253Blc%253Dru`
and after parsing it the object looks like
`{ 'cc=ru;lc=ru': null }`

### Component(s) impacted

This is causing the issue, the cookie value set by non-carbon is not compatible with the carbon dotcom version and vice versa.
Impacting the globalization part for the whole app.

### Browser

Chrome

### Carbon for IBM.com version

v1.25.0-rc.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

httpw://www.ibm.com

### Package

@carbon/ibmdotcom-utilities

### CodeSandbox example

NA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
Closing this issue based on the Sept 23, 2021 Slack conversation with Jeff.  ![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/b8a4cba9-e81b-4aea-994e-5fad9fe5bee4)
