### ISSUE TITLE
[DevTools] Selected enhancements 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7227]
Continuation of DevTools upkeep: 

Column opacity https://github.com/carbon-design-system/devtools/issues/#52
Web components support https://github.com/carbon-design-system/devtools/issues/#14

**Comment by photodow** [comment]
Might add updating the listing pages to next sprint? It's a little over due for a refresh.

https://github.com/carbon-design-system/devtools/issues/18
