### ISSUE TITLE
[Cloud masthead] Fading gradient is scrolling with content and covering links

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7232]
When screen height is short, the gradient covering the bottom of mega menu is not locked to the bottom. Instead it's scrolling up with content, and covering links: 

![Sep-23-2021 11-11-50.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/47e45a17-30d4-4fe2-bf7b-3136a563e41c)

**Comment by proeung** [comment]
@annawen1 FYI. I'm not seeing this issue within the latest v.1.24 release (see - https://www.ibm.com/cloud/paks). I suspect that this is a regression that got recently merged into the master branch.
