### ISSUE TITLE
[Masthead, login]: Change the Masthead, login functional specifications to include the new designs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7237]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Masthead, login` functional specs 

> so that I can:
so that I can properly code the `Masthead, login` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#6335)**

#### Acceptance criteria
 - [ ] Documented `Masthead, login` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by shixiedesign** [comment]
In review [updated func spec](https://app.zenhub.com/files/193129061/0861aecd-2af3-4368-9fb8-edf986a4e5a5/download)

**Comment by RobertaJHahn** [comment]
@shixiedesign Can this issue be closed?  It is the last open issue in sprint 21-22

cc:  @skuruvil

**Comment by shixiedesign** [comment]
Yes! We will upload to box shortly.

**Comment by skuruvil** [comment]
Completed functional spec in Box:
https://ibm.ent.box.com/folder/59063660753?s=mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1
