### ISSUE TITLE
[CONTENT ITEM HORIZONTAL]: Update styles and layout of Content item horizontal with media to better align with Content item horizontal and New Featured media variant

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#7256]
### The problem

We are trying to unify the set of Content item horizontal components so that elements used across the multiple variations feel more consistent. 

### The solution

Updates to font styles, column structure, and padding need to be made in order to unify the family of components.

**Requested updates to Content item horizontal with media**
![Content item horizontal with media@2x](https://user-images.githubusercontent.com/77290329/134951781-cd76ae75-dc88-4068-bdad-ebf287ef2eeb.png)
![Content item horizontal with media (320px_sm)@2x](https://user-images.githubusercontent.com/77290329/134951859-ab8e753d-2611-4ede-b6d4-2dab19b6604f.png)

**Requested updates to Content item horizontal**
![Content item horizontal@2x](https://user-images.githubusercontent.com/77290329/134952037-eb596da7-1975-4475-8007-3a7cc6abb37b.png)

**Content item horizontal with media specs**
[PDF](https://ibm.ent.box.com/file/869427591424?s=2h7ultdzzh4vbn9g31w8kijhexufvvut)
[Sketch](https://ibm.ent.box.com/file/869453525289?s=ruwgj206fa3uhb7pgyyu0dmeugdgtlw0)

----

**Requested new component for "Featured media"**
![Content item horizontal with featured media@2x](https://user-images.githubusercontent.com/77290329/134953367-36429182-2e2a-4a14-bcc0-33ae59e8d786.png)
![Content item horizontal with featured media (320px_sm)@2x](https://user-images.githubusercontent.com/77290329/134953486-bfd7ec86-421c-43ba-acd3-9ec68beef301.png)

**Content item horizontal with featured media specs**
[PDF](https://ibm.ent.box.com/file/869480191103?s=gqsiqmkfc80bhpxibrbsf0x8liaz5ci8)
[SKETCH](https://ibm.ent.box.com/file/869457280581?s=w8eljmph81wv2dy1knallt6s4etff34d)

----

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
Convert to an epic, func spec, WC dev, React Wrapper, Vis QA & Prod, website update
