### ISSUE TITLE
[Masthead, search] Scoped search

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7267]
As part of the continuous improvement of Masthead, we've been requested to add scoped search by: 
- Search & discovery team
- Support
- IBM Docs (Knowledge Center)

### Brief 

~By default, a visitor of IBM.com can search in all of IBM.~
Scoped search, when turned on, allows a visitor to choose to search within specific categories within IBM, such as searching within Docs for documentation, or within Products catalogue for products.

_Updated Nov 12_: Spoke with Dave McDuff from Search and Dallas Hudgens from Docs, we are refining the problem scope to below: 

**Two situations:**

1. IBM Masthead search should be able to accept variable from the page, which will define default search scope. Search All IBM will be the secondary scope available via manual selection (like dropdown) 
2. When no matching variable value is detected, default to search All IBM 

#### Tips

1. [Nielsen Norman Group's recommendations ](https://www.nngroup.com/articles/scoped-search/)

2. Never forget, search result page. How is the "scoped-ness" communicated on the Search result page? Need design explorations (based on the 3 adopters above) and gather usage guidance.

3. Competitor examples

![ss-amazon.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/00dca845-6608-4186-b161-aa1baa8b52f7)

![ss-imdb.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/a478a65c-e006-45a0-9789-5d0dee45b60b)

**Comment by RobertaJHahn** [comment]
Convert to epic:  design issues (2 = Design exploration & spec), func specs, dev WC & pure react, QA issues and website

**Comment by skuruvil** [comment]
You can find the design spec and functional spec here https://ibm.ent.box.com/folder/137924368899?s=csvl5h1qnekbvhg2m33a6od0kmhjn73z
