### ISSUE TITLE
[Card component]: Add tags to the bottom of card components

### ISSUE THREAD

**Issue by justinlam2** [carbon-design-system/carbon-for-ibm-dotcom#7281]
### The problem

We are trying to add tags to the bottom portion of card components. This should also be allowed to use in other components that use the Card component, such as Card in card and Card with images

### The solution

<img width="533" alt="Screen Shot 2021-09-29 at 1 17 23 PM" src="https://user-images.githubusercontent.com/91626425/135317599-125fc4f0-ff85-4786-ab85-6dbc43675414.png">

- **Final Designs Box folder link:  https://ibm.ent.box.com/folder/95514001950?s=hgvu48r1fv2ga2h0yn3qshrtxjc71vch**

### Application/website

AEM Events & Learn landing page

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
Convert to epic, design specs update, dev (WC & React Wrapper), QA, website

**Comment by RobertaJHahn** [comment]
All linked issues are closed.   Closing
