### ISSUE TITLE
Web Components Tutorial design 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7321]
### Task

Design a simple page for the Web components tutorial, so the adopters can learn the basics of how to use Carbon for IBM.com library. The page should contain: 

- Dotcom shell
- 2-3 Out of the box components (choose from some top used ones, eg. Table of Contents, Card group, Carousel, maybe showing a Video ) 
- A custom Content block component assembled with our subcomponents
- Lead space search, to provide a chance to use API of IBM Docs

**Comment by shixiedesign** [comment]
Adding a low res screenshot from Slack as an update. 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/51553b93-053d-4f24-b241-45c6c1e9d042)

@DragosRistici when the design is ready, please add it to a boxfolder, please remember to include exported image assets used: https://ibm.box.com/s/3tudp91p69ot0y63phmxkfthjsy5krkk

**Comment by DragosRistici** [comment]
<img width="817" alt="Screenshot 2021-11-05 at 12 55 54" src="https://user-images.githubusercontent.com/48327647/140500096-76c5c582-c11a-4a0f-bfcf-3c49f5f4116a.png">

Two related options [got uploaded in the Box folder here](https://ibm.ent.box.com/folder/149397039365?s=3tudp91p69ot0y63phmxkfthjsy5krkk). One has the horizontal ToC and no Lead space search sticky behavior (they are mutually exclusive), and the other option has no ToC and the sticky behavior for the lead space. Images can be found in the images folder. Custom 4x3 images for sm for Card in card video thumbnail (custom cover) and for the Card section offset Background media image.
