### ISSUE TITLE
[Masthead, search] Scoped search design study / exploration

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7332]
### Brief 

By default, a visitor of IBM.com can search in all of IBM. 
 
Scoped search, when turned on, allows a visitor to choose to search within specific categories within IBM, such as searching within Docs for documentation, or within Products catalogue for products.

#### Additional Information
- **See the epic (#7267) for the overarching descriptions of the work.**
- [Nielsen Norman Group's recommendations ](https://www.nngroup.com/articles/scoped-search/)
- Never forget, search result page. How is the "scoped-ness" communicated on the Search result page? Need design explorations (based on the 3 adopters above) and gather usage guidance.
-  Competitor examples
- Should work with the following other teams:  IBM Docs (Dallas Hudgens), ibm.com Masthead Search (Dave McDuff)

![ss-amazon.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/00dca845-6608-4186-b161-aa1baa8b52f7)

![ss-imdb.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/a478a65c-e006-45a0-9789-5d0dee45b60b)

#### Acceptance Criteria
- [ ] Design direction(s) has been identified, reviewed, and approved for the final design phase
- [ ] The next story has been updated with the design direction

**Comment by shixiedesign** [comment]
Reducing points to 2 and adding the rest to Spec ticket
