### ISSUE TITLE
[Masthead, search]: Create scoped search designs, & specs 

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7333]
#### User story
> As a `[user role below]`:
developer on the DDS Squad 

> I need to:
have the `Masthead, search` design specs

> so that I can:
correctly create / change the `Masthead, search` component 

#### Additional Information
- **See the epic (#7267) for the overarching descriptions of the work.**

#### Acceptance Criteria
- [ ] A Sketch file is created or updated with the `Masthead, search` design and specs
- [ ] The design specs and pdf version are added to the Box folder 
- [ ] Add Box folder link to the website content if it exists

**Comment by shixiedesign** [comment]
Let's continue this in a new ticket #7720
