### ISSUE TITLE
[Masthead, search]: Change the functional specifications to include scoped search

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7334]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Masthead, search` functional specs 

> so that I can:
so that I can properly code the `Masthead, search` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#7267)**
- One thing to keep in mind, in Func spec, the change should be made to **Search with typeahead**, which is used in masthead: https://ibm.box.com/s/csvl5h1qnekbvhg2m33a6od0kmhjn73z

#### Acceptance criteria
 - [ ] Documented `Scoped search` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by skuruvil** [comment]
You can find the design spec and functional spec here https://ibm.ent.box.com/folder/137924368899?s=csvl5h1qnekbvhg2m33a6od0kmhjn73z
