### ISSUE TITLE
[Card]  allow `target` attribute to card links

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#7345]
### The problem

Currently there is no way to open links into new tabs/windows.

### The solution

Provide access to the `target` attribute, either via component properties or add directly by authors (`target="_blank").

### Application/website

Carbon for IBM.com

### Business priority

Medium Priority = upcoming release but is not pressing

### Examples

For example:

`Card - with pictogram` here has no way to open links in a new tab or window.

![image](https://user-images.githubusercontent.com/909118/136397680-726fbb55-ccbf-4eb3-a2f0-d3a21c374548.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

### Additional Information
- [existing web standards documentation](https://w3.ibm.com/w3publisher/ibm-web-standards-external/standards-mandatory/page-layout-design)

**Comment by shixiedesign** [comment]
Currently, there is a way to get a Card link & default Card to open a new link by using `CTA - Card` and `CTA - Card link`. This ticket is asking for the function to be added to Card component. If we do this, we are duplicating functionalities, and if there are many situations where we wanna add CTA functions to Card (and buttons, Feature card, etc), maybe there's no reason for CTA component to exist. 

Unfortunately Card pictogram and other variants of default card would not be able to perform this function. But the work around for this function using default Card and Card link exist. We will icebox this issue for now.
