### ISSUE TITLE
[Styles package]: refactor component styles for V2

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#7348]
### The problem

Various component styles in the `styles` package have become very bloated and unwieldy. This is further exacerbated by components that have styles in both the `styles` and `web-component` packages.

### The solution

A refactor of some component styles is overdue. It would also be a great opportunity to merge components which have styles in `styles` and `web-components`.

### Application/website

Carbon for IBM.com

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

~Q1 2022

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
discussed in the Engineering Huddle.  Kenny to create additional issues.

**Comment by jeffchew** [comment]
Components to consider:
- Card
- Link with Icon
- Link List

This will be in tandem with migrating to sass modules.

**Comment by kennylam** [comment]
Tracked in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10373
