### ISSUE TITLE
[Tabs extended vertical]: Focus state

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#7372]
### User story

Designs are needed for the `focus` state within Tabs extended vertical component. This came up on the QA call on Oct 12, as an unexpected visual treatment in comparison to the Tabs extended horizontal.

Current implementation:
![Screen Shot 2021-10-12 at 9 17 31 AM](https://user-images.githubusercontent.com/45692622/136987110-9fdd2862-1930-4e15-b331-fccbcd22c585.png)

Things to consider:
- No overlap of focus outline on the text, might be good to reference how [Link](https://react.carbondesignsystem.com/?path=/story/components-link--default) or [Link with icon](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-link-with-icon--default) focus state is handled.
<img width="96" alt="Screen Shot 2021-10-12 at 11 48 40 AM" src="https://user-images.githubusercontent.com/45692622/136988476-cce2d83f-7c2c-4ec0-a7ae-4bb088ad6c92.png">

- Saijan pointed out mirroring the Tabs extended horizontal focus state might not look quite right when the tab is also selected
![Screen Shot 2021-10-12 at 11 44 29 AM](https://user-images.githubusercontent.com/45692622/136988327-26b29107-f620-4f26-9b23-41c7a3e6eb31.png)

### Additional information

- [Box folder with specs](https://ibm.ent.box.com/folder/133802998765?s=26zrugvym00408zhpp23gqwnudzmgdd1)
- [Tabs extended storybook](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-tabs-extended--default)

**Comment by RobertaJHahn** [comment]
Convert to an epic, design review & specs, WC dev, QA, Jan will check on whether website updates are needed.
