### ISSUE TITLE
[Filter panel]: add `View all` link for filter groups

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#7376]
### The problem

The design/functional specs have a `View all` button for filter groups, suggested to be used when items in a group exceed 7. This functionality has not been implemented.

![image](https://user-images.githubusercontent.com/909118/137136008-982af468-47fe-4c3e-b0df-168d9f3c7c51.png)

### The solution

Add `View all` and ~`View less`~ (edit: view less is not needed. See comment below. - Shixie) buttons to filter groups. Should default to `us-en`, with an option to change via component attributes for localization.

### Application/website

Carbon for IBM.com

### Business priority

Medium Priority = upcoming release but is not pressing

### Examples

See usage recommendations [here](https://www.ibm.com/standards/carbon/components/filter-panel/#number-of-items-per-category).

### Design & functional spec: 

Functional spec link: https://ibm.ent.box.com/file/877078938624
Design spec: https://ibm.ent.box.com/file/812504212849?s=gu6zn73y1gpeggi9v5gauyhan7u9ndc4

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by shixiedesign** [comment]
Clarification: decided not to include "view less" link because collapsing the accordion should restore original state. Restoring to only 5 item in accordion is not a useful scenario.
