### ISSUE TITLE
[Card-in-Card Copy Text]: With adding the copy field to the card in card component, the card stretches beyond the image between the window size of 1041 px to 1204 px

### ISSUE THREAD

**Issue by druckerk** [carbon-design-system/carbon-for-ibm-dotcom#7383]
### Description

Expected: 

When the window screen sinks the card within the component should not stretch beyond the image. 

<img width="774" alt="Screen Shot 2021-10-13 at 1 57 50 PM" src="https://user-images.githubusercontent.com/88403358/137196727-310a7b56-872a-4130-976e-e849b6176175.png">

Actual:

When adding the copy field to the card within this component the behavior of how it stretches over the image changes. For example,  If the author adds a long string to the field the card will stretch beyond the image. This issue only occurs when the window screen size is between 1041 px and 1204 px.

<img width="816" alt="Screen Shot 2021-10-13 at 1 33 22 PM" src="https://user-images.githubusercontent.com/88403358/137197703-42bf9c33-883b-4b36-83a4-4cbc7e05189d.png">

### Component(s) impacted

Card in Card Component

### Browser

Chrome

### Carbon for IBM.com version

ibmdotcom-web-components: 1.8.0 / ibmdotcom-styles: 1.23.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

AEM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/busy-platform-rt7ek?file=/dist/index.html

### Steps to reproduce the issue (if applicable)

1. Create a new page or use an existing page.
2. Click on the drag component here within the body section. 
3. Click on the Content Section component. 
4. In the content section component, click on the drag component. 
5. Add the card in card component.
6. click on the configuration button to open the dialog. 
7. In the dialog, drag an image to drop an asset here under the asset tab. 
8. Then click on Card Content tab and fill out the fields: 
<img width="526" alt="Screen Shot 2021-10-13 at 2 20 17 PM" src="https://user-images.githubusercontent.com/88403358/137199215-b553aab7-4b9c-4798-9225-98258dab20d2.png">
9. Then click on the Link Properties:
<img width="546" alt="Screen Shot 2021-10-13 at 2 20 27 PM" src="https://user-images.githubusercontent.com/88403358/137199282-db698273-67be-4953-9cf5-91a41a98d218.png">
10. Click on the checkmark icon in the upper right corner to complete the setup. 
11. Lastly, open the page in publish view and shrink the browser window size to view the behavior o the card stretch beyond the image. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@druckerk Is something like [this](https://www.ibm.com/standards/carbon/components/feature-section) more appropriate? 

cc: @oliviaflory

**Comment by druckerk** [comment]
@kennylam -  I don't think how the card in the feature section addresses the issue occurring when we have the copy field in the card in card. I added gif of how the card in card is working with the copy text and without copy text. Let me know if you have any other questions or need additional information. 

Card in Card with Copy Text:
![card_in_card_screen_caption](https://user-images.githubusercontent.com/88403358/137391786-7f70b1d3-4baa-43bb-8a35-b1c60c5645b9.gif)

Card in Card without Copy Text: 
![card_in_card_without_copy_text](https://user-images.githubusercontent.com/88403358/137392296-6098e7c0-ddbe-47cc-9d04-8f08f4695b1e.gif)
