### ISSUE TITLE
[Mega menu & dropdowns]: overlay vs no overlay

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#7394]
### User story

The Cloud team reached out to ask: **why there's no overlay being shown for regular dropdown and only for mega-menu?**

Answer from Olivia in slack:
- The mega menu takes up so much of the screen that we wanted to ensure it was really differentiated from the page.
- Where as the dropdown is a more condensed experience it doesn’t need the overlay. I’m not sure if I’ve seen an example of another site/experience that uses an overlay for a dropdown
- When I first designed the mega menu we only anticipated it being used for the global masthead, and that all of the links would have a mega menu.

--- 

Now that the Cloud masthead has a mix of mega menus and dropdowns we might want to look at if we think having an overlay for mega menu and no overlay for dropdown is the best solution. 

**Initial ideas to explore**
- Turn off overlay for when there are both mega menu and dropdown
- Inset mega menu and turn off overlay
- Add overlay when there are both mega menu and dropdowns 
- Leave as is (note: Olivia doesn't think this is a huge deal because the user has to click on each dropdown/mega menu to open it, so the experience isn't as noticeable) But we should check against an example that might like a mega menu, but it would have less content aka the mega menu wouldn't take up the entire screen.

### Additional information

Cloud example: https://www.ibm.com/cloud/watson-assistant
![Screen Shot 2021-10-13 at 5 07 43 PM](https://user-images.githubusercontent.com/45692622/137213988-27e883a7-afe9-49fb-b816-53c29281afed.png)
![Screen Shot 2021-10-13 at 5 07 48 PM](https://user-images.githubusercontent.com/45692622/137213989-38a8b659-f450-4a81-8a68-055376c36949.png)

### Acceptance criteria

- [ ] _{{State acceptance criteria}}_
- [ ] _{{State another}}_
- [ ] _{{And another}}_

**Comment by proeung** [comment]
@oliviaflory Thanks for creating this issue. Please keep me posted on the decision that will be coming out from the design research.

**Comment by RobertaJHahn** [comment]
We will be OK with mixing the mega menu and dropdown and allowing for the mix of overlay treatment.  Closing.
