### ISSUE TITLE
ToC is not navigating to correct section of the page 

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/carbon-for-ibm-dotcom#7395]
### Description

https://www.ibm.com/topics/hyperledger

Go to URL above and click on any item in ToC.  

It doesn't bring you to that section.  It's a little above or below.

This might be AEM implementation but wondering if Fireline could take a look and assist AEM team.

### Component(s) impacted

Vertical ToC on AEM page

### Browser

Chrome

### Carbon for IBM.com version

not sure

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

not avail

### Steps to reproduce the issue (if applicable)

see above.

There was a duplicate issue but it was closed.  

### Release date (if applicable)

This is happening in production now.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
Removing @kennylam from this.

**Comment by ljcarot** [comment]
This is no longer a bug.
