### ISSUE TITLE
[Filter panel]: Change the functional specifications to include `View all` link for filter group

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7404]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Filter panel` functional specs 

> so that I can:
so that I can properly code the `Filer panel` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#7376 )**
- See usage recommendations [here](https://www.ibm.com/standards/carbon/components/filter-panel/#number-of-items-per-category).

#### Acceptance criteria
 - [ ] Documented `Filter panel` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by shixiedesign** [comment]
This functionality is already in functional spec. Dev may proceed with sizing and development @RobertaJHahn
