### ISSUE TITLE
[Filter panel] Web Component: add View all link for filter groups - DDS Consulting

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7405]
**Engineering info:**  
- Innovation Team engineer: @jkaeser 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2365
- DPO consulting engineer: @IgnacioBecerra 
- Original Carbon for IBM.com engineering estimate: 5

----

#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `Filter panel`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic (#7376 ) for the Design and Functional specs information**
- Add `View all` button to filter groups. Should default to `us-en`, with an option to change via component attributes for localization.
- See usage recommendations [here](https://www.ibm.com/standards/carbon/components/filter-panel/#number-of-items-per-category).
- Web Components Visual QA testing issue (#7406 )
- Web Components Prod QA testing issue (#7407 )

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by shixiedesign** [comment]
This feature already exist in design and func spec. Just need dev issues.

**Comment by jeffchew** [comment]
@emyarod going to put this back in pending scheduling until we re-jigger the sprints for January. Unassigning from you for now.
