### ISSUE TITLE
[Carbon 10.46 upgrade expressive modal]: content width reduced

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#7420]
### Description

With the upgrade to Carbon 10.46, the width of the expressive modal content was reduced and the type size decreased.

**Percy – Expressive modal default**
![Screen Shot 2021-10-18 at 4 17 20 PM](https://user-images.githubusercontent.com/45692622/137800793-231ef31c-ddbd-45fe-b875-55d1dd6c4df9.png)

**Expecting**

**Fix**
- [ ] body type token set to $body-long-02 for both default and expanded variants
- [ ] Default: return internal content width to 32px padding (keep 32px padding around edge of modal)

<img width="707" alt="Screen Shot 2021-10-18 at 4 21 06 PM" src="https://user-images.githubusercontent.com/45692622/137801410-cbf2e6d7-25c0-4bf5-9134-392eef9c6584.png">

- [ ] Expanded: return internal padding to 0px (keep 32px padding around edge of modal)
![Screen Shot 2021-10-18 at 4 22 01 PM](https://user-images.githubusercontent.com/45692622/137801444-75777c6e-c785-4bcb-9444-8f3d615ce536.png)

### Component(s) impacted

Expressive modal
- Default
- Expanded
https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/7400/index.html?path=/story/components-expressive-modal--default

### Browser

Chrome

### Carbon for IBM.com version

https://ibmdotcom-react.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/7400/index.html?path=/story/components-expressive-modal--default

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

Carbon for IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://react-codesandbox.s3-web.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/7399/index.html

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
@oliviaflory Oh sorry, forgot to include the link! It's inbound with this PR:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7437
