### ISSUE TITLE
[Filter panel] Heading knob not updating

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon-for-ibm-dotcom#7441]
**Engineering info:**  
- Innovation Team engineer: @jkaeser 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2394
- DPO consulting engineer: N/A

-----

### Description

When changing the filter panel `heading` knob in Storybook, the filter panel heading value does not update

### Component(s) impacted

Filter panel

### Carbon for IBM.com version

canary

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

-

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-filter-panel--default

### Steps to reproduce the issue (if applicable)

- visit https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-filter-panel--default
- change `heading` knob

https://user-images.githubusercontent.com/8265238/137959698-d29b889f-cd06-4bfa-80bf-9df63ab392e9.mov

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@jkaeser I'm going to assign this issue to you since you've been working on the Filter Panel component. 👍

**Comment by proeung** [comment]
I'm going to move this issue up to Sprint: 04 as I don't think we'll be able to get a PR up and reviewed/approved in time for today's code freeze period.

cc: @ljcarot @jeffchew

**Comment by jkaeser** [comment]
This isn't a bug with the Storybook configuration; the light DOM heading element _does_ update when the knob value changes. However, this doesn't trigger anything in the composite to re-render the heading in the other places it is used. Ideally we can emit an event from the `<dds-filter-panel-heading>` when it changes that triggers the composite to fire its `_renderStatus()` method.
