### ISSUE TITLE
[Test Scenario]: Table of contents - horizontal - DDS Consulting

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#7446]
**Engineering info:**  
- HC engineer: @andy-blum 
- HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2323
- DDS consulting engineer: Pending DDS resourcing review

----

### Component and test scenario title

Table of contents - horizontal

### Test scenario steps

a. Check Table of contents horizontal bar and content is loaded
b. Verify On click of horizontal menus, it must redirect to actual content below the TOC horizontal
c. Check the Table of contents horizontal menu Select State
d. Verify on scrolling page, Table of contents horizontal bar must remain at top of the page whereas the horizontal menu Select state changes.
e. Customize theme from Carbon theme and verify gray 10, gray 90 and gray 100 theme.

**Comment by andy-blum** [comment]
Is this different from #7444 ? I'd been anticipating writing tests for the horizontal variation of the TOC.
