### ISSUE TITLE
[HTML & NextJS page examples - White theme] Update components to align to grid

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#7457]
Follow on to: carbon-design-system/carbon-for-ibm-dotcom#6732

The components displayed in the NextJS and HTML template pages do not align with the grid.

https://ibmdotcom-web-components-html-staging.mybluemix.net/
https://ibmdotcom-nextjs-staging.mybluemix.net/

### Lead space
The description and the edge of the button group should be aligned with the grid. Right now, they overhang the edge of the column.

![Screen Shot 2021-10-20 at 9.51.32 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/c4bb348a-dbb3-4551-ae5c-b7d6a2c7cd3b)

Compare to specs:
![Screen Shot 2021-10-20 at 10.55.22 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/cc72d177-4bf3-4844-bef2-a94f1c0afb39)

### Vertical Table of Contents
The ToC should overhang the edge of the left-most column, with the text aligned to the edge of the grid and the line selector element hanging outside the column.

![Screen Shot 2021-10-20 at 9.51.24 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/8d8dc948-9618-4d22-898d-06673aa71e94)

Compare with spec:
![Screen Shot 2021-10-20 at 9.48.53 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/9c677b4c-5470-4c6f-bbce-b5b5c83d7072)

### Content block media
Header, body copy, and image should align with the column edge, currently they are floating inside the column. The text elements for the aside link list should align with the edge of the column, with the horizontal rule hanging over the edge of the column.

![Screen Shot 2021-10-20 at 9.52.03 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/b25e7783-c8f2-46c0-a98e-02405597d5fb)

Compare to WC Storybook preview:
![Screen Shot 2021-10-20 at 11.14.35 AM 1.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/64519c77-8140-46ee-afa6-c91ce8c59240)

### Callout quote
The Paragraph, Source, Copy 1, and Copy 2, and CTA text should align with the edge of the column. The beginning quotation mark and the horizontal rule should overhang the column.

![Screen Shot 2021-10-20 at 9.52.18 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/c6c6a870-1f4e-4b8e-8f4a-2a272a214334)

Compare with specs:
![Screen Shot 2021-10-20 at 11.22.33 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/f245df3c-4b50-4a14-b0e7-71e72b35ed15)

### Content group pictogram
The header, body, and pictograms should align to the edge of the column, but are currently floating in the middle of the column. The description header, description copy, and CTA should also align to the edge of the column.

![Screen Shot 2021-10-20 at 9.52.37 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/d8df4fe1-e02f-4d77-b5c7-58b7f2500fba)

Compare to spec:
![Screen Shot 2021-10-20 at 11.28.46 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/5259053e-8542-4974-9ed3-e292e6d8331b)

### Card section
The section title should align with the edge of the left-most column in the grid. For the cards, the card header, body copy, and CTA should align with the left-most column that the card sits in, with the card body overhanging the grid. This should be true for each of the cards in the section.

![Screen Shot 2021-10-20 at 9.53.48 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/85ab58c0-dc60-4f82-9a7e-4d1703b8e38c)

Compare to specs:
![Screen Shot 2021-10-20 at 11.39.22 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/9a1c76fd-a480-4da5-b8b4-8b5d4b26c731)

### Content group banner
The group title should align with the edge of the grid - right now it is floating to the right within the column. The aside element should also have the text aligned to the column, with the vertical rule overhanging to the left.

![Screen Shot 2021-10-20 at 9.53.36 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/999060b5-a8bc-4872-9ef4-95d2200cd221)

See spec:
![Screen Shot 2021-10-20 at 12.09.23 PM 1.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/aaa6f475-9955-4a86-9074-b7d434790293)

### Card section carousel
The section title should align with the edge of the left-most column in the grid. For the cards, the card header, body copy, and CTA should align with the left-most column that the card sits in, with the card body overhanging the grid. This should be true for each of the cards in the section.

![Screen Shot 2021-10-20 at 9.53.58 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/0adcbab6-800b-448f-bd9d-35362ece928d)

Compare to specs:
![Screen Shot 2021-10-20 at 11.47.13 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/6f973db4-bd3d-4083-a643-ad18c03abd21)

### CTA Section
The section header, body, button, and secondary subsection should align with the edge of the column. The second subsection should also align with the edge of the column.

![Screen Shot 2021-10-20 at 9.54.06 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/ece6d4c9-6792-4236-a9e0-970d74124d11)

See spec:
![Screen Shot 2021-10-20 at 12.05.09 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/4c43bdbe-d551-4fbc-a2ed-3fc3c0b68b1d)

**Comment by ariellalgilmore** [comment]
seperated out issues being seen in storybook here: #8933, #8932, #8931, #8930, #8929
