### ISSUE TITLE
[HTML & NextJS page examples - Gray 100 theme] Update components to align to grid

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#7460]
Follow on to: carbon-design-system/carbon-for-ibm-dotcom#6732

The components displayed in the NextJS and HTML example pages do not align with the grid.

https://ibmdotcom-web-components-html-staging.mybluemix.net/
https://ibmdotcom-nextjs-staging.mybluemix.net/

### Card section images
The section title should align with the edge of the left-most column. For the cards, the eyebrow, card header, and CTA should align with the edge of the column, with the left-hand section of the card overhanging the column.

![Screen Shot 2021-10-20 at 10.06.57 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/74f4d02f-81be-4316-8cf6-4644b2bf9267)

See specs:
![Screen Shot 2021-10-20 at 1.09.17 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/31607734-a96e-4bdd-b864-7ea120001128)

### Content block segmented
The Content block segmented header, description, image, follow-up text content should align with the edge of the grid. The card's text should also align with the edge of the grid, with the card background overhanging to the left of the column.

The intro text to Link list, the CTA text, and the CTA icon should also align to the edge of the grid, with the horizontal rule overhanging the column to the left.

![Screen Shot 2021-10-20 at 10.07.31 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/b210b544-81cf-40ab-89bd-d1e99dc38b45)

![Screen Shot 2021-10-20 at 10.07.49 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/30871186-9d83-49e7-adef-97d777ab5331)

See the specs:
![Screen Shot 2021-10-20 at 1.15.53 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/97150331-3a1d-4e69-a684-89174b00bf07)

### Content block horizontal
The block title should align with the edge of the column, and same for the eyebrow and headline within each section. The body copy and the CTA links should align with the column that they sit in (right now, they are floating to the left of the column.

![Screen Shot 2021-10-20 at 10.07.59 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/35e7a637-b3aa-477d-8e87-8ae739aef9e4)

See specs:
![Screen Shot 2021-10-20 at 1.28.52 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/97c1fb78-3900-4ea4-9d52-2d9ad04cea42)

### Card in card
The card background element should overhang the grid on the left-hand side and right-hand side - right now, the card background on the left-hand side is to the right of where it should overhang. The right-hand side of the card is overhanging on the wrong side as well. The card element background should overhang the column on the left and right-hand sides. The card eyebrow, body copy, and CTA icon should align with the edge of the column.

![Screen Shot 2021-10-20 at 10.08.30 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/300814e3-babf-4c7c-8e2d-f88ba7a35287)

See WC Storybook:
![Screen Shot 2021-10-20 at 1.38.03 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/e2c63afa-a141-49a4-bba4-80568bc19319)

### Link list section
The section title should align with the edge of the left-hand column. The list link text CTAs should align with the edge of the column that they appear. The second column on the right appears right, but the first column has added spacing pushing the text off the column.

See WC Storybook:
![Screen Shot 2021-10-20 at 1.46.44 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/9b4fe6e7-a46f-4f49-8bf5-c370a823adaa)

### Card section carousel
The section title should align with the edge of the left-most column in the grid. For the cards, the card header, body copy, and CTA should align with the left-most column that the card sits in, with the card body overhanging the grid. This should be true for each of the cards in the section.

The carousel control also looks like it does not align to the grid.

![Screen Shot 2021-10-20 at 10.08.49 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/74ba67cf-0b25-4990-a125-90f222ca28c3)

See specs:
![Screen Shot 2021-10-20 at 11.47.13 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/d106fa10-c500-4440-bfb6-8adbc1a55c0d)

### CTA Section
The section header, body, button, and secondary subsection should align with the edge of the column. The subsection intro text, and the subsection CTA links should align with the edge of the column. The second subsection on the right should also align with the edge of the column.

![Screen Shot 2021-10-20 at 10.08.58 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/bf124024-91c9-4297-a326-7c15d233a245)

See specs:
![Screen Shot 2021-10-20 at 12.05.09 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/25fd2369-ca62-42fb-af7d-ce052d84b5d5)

**Comment by IgnacioBecerra** [comment]
Closing this in favor of the Content block/group refactoring.
