### ISSUE TITLE
[Masthead Search] XSS scripting vulnerability in search

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon-for-ibm-dotcom#7471]
### Description

attacker can run js through the search component in masthead

### Component(s) impacted

masthead

### Carbon for IBM.com version

1.23.1

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

1.23.1

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

SANDBOX DOES NOT WORK FOR THIS

### Steps to reproduce the issue (if applicable)

Steps To Reproduce:
1.Go to https://www.ibm.com/docs/de/search
2. Now put this payload on the search icon `"><img src=x onerror=alert(document.cookie)>` and hit enter.
3. It will execute the XSS payload in the URL.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
We should remove special characters in search for both React and Web Components.
