### ISSUE TITLE
[Tabs extended vertical] Web Component: update focus state - DPO Consulting

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7483]
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2396
- DPO consulting engineer: @emyarod 

-----

#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `Tabs extended vertical`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

### Specific update needed

When Tooltip is visible (on hover & on focus), the tooltip's little triangle should be on the top, and aligned left.

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/1e2f3a75-8c36-499f-957c-08a56f1f6097)

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic (#7372 ) for the Design and Functional specs information**
- No E2E testing update is needed.
- Web Components Visual QA testing issue (#7485)
- Web Components Prod QA testing issue (#7486)

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] Update the e2e test scripts, if needed. 
- [ ] Confirm e2e test results have no major errors.
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by andy-blum** [comment]
Just wanted to double check the design on this. The carbon tooltip component we're using here doesn't allow for changing the placement of the caret, just the text bubble. The caret is _always_ center-aligned to the element that triggers it
<img width="268" alt="Screen Shot 2022-02-09 at 1 53 54 PM" src="https://user-images.githubusercontent.com/25532785/153270588-c27c99b0-493f-427f-92d8-45cc4197903c.png">
<img width="266" alt="Screen Shot 2022-02-09 at 1 54 02 PM" src="https://user-images.githubusercontent.com/25532785/153270589-77ebedef-61b0-405d-b00d-4e0265f4e7d8.png">
<img width="266" alt="Screen Shot 2022-02-09 at 1 54 09 PM" src="https://user-images.githubusercontent.com/25532785/153270591-92393cd2-ab26-49ac-8946-aaf28a81beb4.png">
.

**Comment by andy-blum** [comment]
cc: @oliviaflory and/or @RichKummer

**Comment by andy-blum** [comment]
@oliviaflory The implementation of the tooltip with the tabs is already matching this, then. Currently the tooltip is left-aligned with the trigger element (the tab in this case), and takes the width of its text content up to 13 rems.

<img width="701" alt="Screen Shot 2022-02-10 at 4 48 27 PM" src="https://user-images.githubusercontent.com/25532785/153502927-5c034e0c-f1f8-4f14-bd28-cab1981d12f0.png">

The tooltip is left aligned to it's parent
<img width="428" alt="Screen Shot 2022-02-10 at 4 47 56 PM" src="https://user-images.githubusercontent.com/25532785/153502965-36ed3c6d-8be9-4eb6-aa98-2924a5781419.png">

The tooltip is set to takes up the width of `max-content`, so long as that value falls between 1.5 & 13 rems.
<img width="426" alt="Screen Shot 2022-02-10 at 4 47 40 PM" src="https://user-images.githubusercontent.com/25532785/153502971-62511e80-a2e5-4194-b1ab-1d415f045c63.png">

The only thing that this issue would change is the placement of the caret in relation to the parent item. Is that something we actually want to change away from carbon core?

**Comment by oliviaflory** [comment]
@andy-blum  cc: @jeffchew 

> The only thing that this issue would change is the placement of the caret in relation to the parent item. Is that something we actually want to change away from carbon core?

No, we don't want to change away from how the Carbon tooltip is done. I _think_ in an earlier version of the Carbon tool tips the caret was more like the "expected" example above, but it seems like design didn't catch the update to always be center aligned to the parent. 

**If this is already implemented there is no further action needed and we can close out this issue.**

**Comment by proeung** [comment]
@oliviaflory Thanks for getting back to us! Feels like there's no action that's needed for this particular issue. I'll go ahead and close this out for now. Feel free to re-open if there is more action needed. cc: @ljcarot @jeffchew
