### ISSUE TITLE
[v18 banner] adding a new banner request

### ISSUE THREAD

**Issue by lbailing** [carbon-design-system/carbon-for-ibm-dotcom#7489]
### Contribution type

Documentation

### Contribution type (other)

we plan to add a new banner since 10/27 instead of the banner between10/12-10/26 at the same place and the same layout.

text：
Think Summit Japan 2021
IBM X-Onlineでオンデマンド配信中
CTA：
オンデマンドを視聴する
[url]
https://www.ibm.com/jp-ja/events/x-online?ondomainbanner=tsj2021_xonlinebanner

we hope the new banner can be show in below domain:
https://www.ibm.com/jp-ja/about
https://www.ibm.com/jp-ja/analytics
https://www.ibm.com/jp-ja/cloud
https://www.ibm.com/jp-ja/it-infrastructure
https://www.ibm.com/jp-ja/products
https://www.ibm.com/jp-ja/security
https://www.ibm.com/jp-ja/watson
https://www.ibm.com/think/jp-ja/business/
https://www.ibm.com/blogs/security/jp-ja/
https://www.ibm.com/blogs/systems/jp-ja/
https://www.ibm.com/blogs/think/jp-ja/
we hope the new banner will not been show in below page:
https://www.ibm.com/jp-ja/services

### Intent

we plan to add a new banner since 10/27 instead of the banner between10/12-10/26 at the same place and the same layout.

### Solution

we hope the new banner can be show in below domain:
https://www.ibm.com/jp-ja/about
https://www.ibm.com/jp-ja/analytics
https://www.ibm.com/jp-ja/cloud
https://www.ibm.com/jp-ja/it-infrastructure
https://www.ibm.com/jp-ja/products
https://www.ibm.com/jp-ja/security
https://www.ibm.com/jp-ja/watson
https://www.ibm.com/think/jp-ja/business/
https://www.ibm.com/blogs/security/jp-ja/
https://www.ibm.com/blogs/systems/jp-ja/
https://www.ibm.com/blogs/think/jp-ja/
we hope the new banner will not been show in below page:
https://www.ibm.com/jp-ja/services

### IBM Organization or Company you are part of

I'm from MSC - Digital Specialist_Japan

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
The follow-on issue in sprint 21-23 is #7612 .  Closing this issue.
