### ISSUE TITLE
[DIGITAL STRATEGIST]: Applied Digital, AIOps/Turbonomic

### ISSUE THREAD

**Issue by kendallcarpenter** [carbon-design-system/carbon-for-ibm-dotcom#7529]
### Description

I work as a digital strategist on the Applied Digital team for AIOps. All of the heat maps that I have been trying to create have not been coming out right. I had started a ticket with Chris Albrecht/ServiceNow and got directed to this team instead.

The guidance that I have received is that something was blocking the CSS. 

I have attached an image of how the heat maps are generating. 

![heatmap-8317866-click-desktop](https://user-images.githubusercontent.com/93283113/139155829-c4cf5307-4418-455c-8c59-f4562de22007.png)

### Component(s) impacted

Hotjar heat maps

![heatmap-8317866-click-desktop](https://user-images.githubusercontent.com/93283113/139155877-2bcaa69c-97bf-41b2-8d55-efdf4c3552ec.png)

### Browser

Firefox

### Carbon for IBM.com version

Not sure

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

/cloud/aiops, /cloud/turbonomic

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

Not sure how to answer

### Steps to reproduce the issue (if applicable)

Generate a heatmap for /cloud pages

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kendallcarpenter** [comment]
Hey Jeff, do you have any new updates about Hotjar?

**Comment by jeffchew** [comment]
Their team is looking into adding support for adopted stylesheets, which they rolled into their mid November roadmap to start development.

**Comment by kendallcarpenter** [comment]
Awesome, thank you!

**Comment by jeffchew** [comment]
Moving to sprint 24. Will followup with the hotjar dev team on Monday.

**Comment by kendallcarpenter** [comment]
Hey Jeff, has there been any progress on adding support for adopted stylesheets?

**Comment by jeffchew** [comment]
Hi @kendallcarpenter ,

I received notice that the hotjar team will be activating first load support in the coming days!

They are still working on an incremental update that will allow for dynamic updates of adoptedStylesheets which will be going into Q1 (tentatively of the new year).

**Comment by kendallcarpenter** [comment]
@jeffchew Awesome, thanks for the update! What exactly is first load support?

**Comment by jeffchew** [comment]
@kendallcarpenter it pretty much means whatever loads when the page first loads will be captured by hotjar.

**Comment by kendallcarpenter** [comment]
@jeffchew Gotcha, thank you!

**Comment by jeffchew** [comment]
@kendallcarpenter just a heads up, the initial fix should be deployed now for Hotjar! Can you verify if you're seeing the changes?

**Comment by kendallcarpenter** [comment]
@jeffchew For sure. Let me set up a new manual heatmap and I will respond with the results!

**Comment by kendallcarpenter** [comment]
@jeffchew Looks like I am still having issues with the manual heat maps. I tried it out on /cloud/aiops and /cloud/turbonomic

**Comment by kendallcarpenter** [comment]
@jeffchew Hey Jeff, were other people who were testing out the changes still having issues or was it only me?

**Comment by jeffchew** [comment]
Hi @kendallcarpenter !

I heard back from the Hotjar team, they actually said that they will be retiring manual heatmaps in the near future, and that it should be working for Recordings and Continuous Heatmaps. Can you check if it works fine in there?

**Comment by kendallcarpenter** [comment]
Hey @jeffchew! Thank you for the update on manual heatmaps. I just checked on the continuous heat maps. It looks like they are having some issues, too. I'm attaching the one for www.ibm.com/cloud/aiops for reference!
![heatmap-42920-click-desktop-1](https://user-images.githubusercontent.com/93283113/148259826-c2a5ba71-4d33-40a5-80c8-9b61f539fc9c.png)

**Comment by kendallcarpenter** [comment]
Nothing shows up for the tablet version and this is what I got for the mobile version


![heatmap-42920-click-phone](https://user-images.githubusercontent.com/93283113/148259981-59570b44-5927-46ad-9738-2753422a6ce1.png)

**Comment by jeffchew** [comment]
@kendallcarpenter I was informed that the hotjar team made some improvements to continuous heatmaps in the past few weeks. Can you check to see if things look better now?

**Comment by kendallcarpenter** [comment]
Just checked on continuous. Here is what I see for /cloud/turbonomic! 

I also recently got an email from the Hotjar support team that said the following - 

_Hey Kendall,
 
Thanks for reaching out and sorry to hear about the issue with your Recordings.
 
I took a look into this, and I could see that when I'm trying to re-take your Screenshot, I'm seeing "Error 413: Request Entity Too Large" in my Console view.
 
The 413 error is occurring when we're trying to open a connection between the user/client session, and our Hotjar servers. The problem is that the content we're trying to retrieve from that page is larger than our current limit 🙁 
 
For some additional context, the way Hotjar works is that we pass data from the user's session through our WebSocket. We are collecting the DOM elements and any mutations, plus any events related to click and scroll—these are used to rebuild the session as a web page. 
 
For performance (both on our end, and for the user) we request larger data payloads (so images, CSS, etc.) separately and we cap what can be sent through the WebSocket. If assets are added right into the DOM, the page may bloat up a little and cause 413 errors. 
 
The hard limit we have right now is 10MB. We've reviewed this in the past, but currently, we're not comfortable with raising the limit any higher.

I wouldn't assume to ask you to refactor the page to support Hotjar, however, it might be worth having a look at the code and see if there's any room for optimization, and if there are styles added to the page itself that could be loaded as separate assets. The page itself is 11MB in size, for reference.
 
Of course, I do appreciate that this approach has been chosen for good reasons during production and I'd be happy to learn more about the approach taken if you feel that our limits are not appropriate for contemporary development. 
 
I hope this helps. Please let me know if I can clarify anything, or if you have any other questions 😊. 
 
Cheers,

Alex Bakke | Technical Support_

![ContHeatmap-01 31 22](https://user-images.githubusercontent.com/93283113/151875767-272c6482-d5dd-4514-840c-164eb86b1fcf.png)

**Comment by jeffchew** [comment]
@kendallcarpenter just checking in! Has the use of dynamic heatmaps been helpful to get around this?
