### ISSUE TITLE
Component:  Scroll animation / fade MVP

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#753]
### User story
As a user of IBM.com, I would like the experiences to be more dynamic and responsive to scrolling so that I can stay longer without losing attention and know that the experience is actively responding to my actions.

### Notes
- This is to add the ability to add scroll-fade to any elements on a page.
- As user scrolls, elements on a page should fade in and slide up slightly.

#### Additional Information
- [Ideation Scroll animation epic #144 ](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/144)
- [Functional specs box folder](https://ibm.ent.box.com/folder/125890741222)

### Acceptance criteria
- [ ] Component is available

**Comment by RobertaJHahn** [comment]
Sept 30, 2020 comment posted by James to the closed Ideation [epic 144](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/digital-design-ideation/144)

Here is my first pass at the scrolling design research. I'll add it to our critique on Friday to review if you'd like.

https://ibm.box.com/s/9izcfoxb04wkxoa5ycewn9bfrdtup7fb
