### ISSUE TITLE
[BUG: Card group]: Grey border in Safari

### ISSUE THREAD

**Issue by KarMartin** [carbon-design-system/carbon-for-ibm-dotcom#7541]
**Engineering info:**  
- Innovation Team engineer: @jkaeser 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2403
- DPO consulting engineer: 

-----

### Description

**Problem description**
The component "Card Group" does not displayer properly in Safari. 
It can be seen in variants "With card in card", "With card in card and image cards" and "With card Links".

CURRENT: (View in Safari (15))
![image](https://user-images.githubusercontent.com/93377090/139412228-e52a5cc7-41a1-4d12-90fd-e787e5b16a44.png)

EXPECTED: (View in Chrome (94) & Firefox (93))
![image](https://user-images.githubusercontent.com/93377090/139412397-d58c1b87-55ac-4526-96fc-98dba80c7a63.png)

**System used to reproduce**
- Macbook pro
- MacOS 11.6
- Safari 15
- Carbon for IBM.com Web Components v1.11.0: https://www.ibm.com/standards/carbon/web-components/?path=/story/components-card-group--with-card-in-card-and-image-cards

### Component(s) impacted

**Affected components:**
card-group--with-card-in-card
https://www.ibm.com/standards/carbon/web-components/?path=/story/components-card-group--with-card-in-card

card-group--with-card-in-card-and-image-cards
https://www.ibm.com/standards/carbon/web-components/?path=/story/components-card-group--with-card-in-card-and-image-cards

card-group--with-card-links
https://www.ibm.com/standards/carbon/web-components/?path=/story/components-card-group--with-card-links

Inspection:
![image](https://user-images.githubusercontent.com/93377090/139413503-9bd8fb8d-1473-412a-b81a-223c2a91be1b.png)

`<dds-card-group-card-link-item href="https://example.com" pattern-background="" data-autoid="dds--card-group-card-link-item" size="" color-scheme="" pictogram-placement="top" cta-type="">
    <dds-card-link-heading role="heading" aria-level="3" data-autoid="dds--card-link-heading" slot="heading">IBM Developer</dds-card-link-heading>
    <p>Learn, code and connect with your community</p>
    <dds-card-cta-footer slot="footer" data-autoid="dds--card-cta-footer" icon-placement="right" color-scheme="" cta-type="" parent-href="https://example.com" href="https://example.com">
      <svg focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" fill="currentColor" aria-hidden="true" width="20" height="20" viewBox="0 0 20 20" slot="icon"><path d="M11.8 2.8L10.8 3.8 16.2 9.3 1 9.3 1 10.7 16.2 10.7 10.8 16.2 11.8 17.2 19 10z"></path></svg>
    </dds-card-cta-footer>
  </dds-card-group-card-link-item>`

### Browser

Safari

### Carbon for IBM.com version

1.11.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

webpage

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/?path=/story/components-card-group--with-card-links

### Steps to reproduce the issue (if applicable)

**Reproduction**
1. Open reference in Safari https://www.ibm.com/standards/carbon/web-components/?path=/story/components-card-group--with-card-links
Result: There are additional grey borders on top of each card when Safari is used.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
The PR attached to this issue should address the border regression bug that's currently being seen on various release tags (eg. `Next` and `Latest`). See the attachment for an example of the bug.

**Card Group with Card Link (Type)**
![Screen Shot 2022-02-16 at 3 45 10 PM](https://user-images.githubusercontent.com/1815714/154366919-1ba966b2-7fbf-4b9b-982d-620a6f5a1d03.png)
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8320#pullrequestreview-885133433
