### ISSUE TITLE
Scroll fade design

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#755]
### User story
As a user of IBM.com, I would like the experiences to be more dynamic and responsive to scrolling so that I can stay longer without losing attention and know that the experience is actively responding to my actions.

### Notes
- This is to add the ability to add scroll-fade to any elements on a page.
- As user scrolls, elements on a page should fade in and slide up slightly. A demo will be added.

### Acceptance criteria
- [ ] Motion prototype has been reviewed and accepted

**Comment by RobertaJHahn** [comment]
This work is managed on the Ideation board under [epic #144](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/144)  Closing
