### ISSUE TITLE
[Link list, end of section] Web components: style regression

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7550]
### Details

Component: **Link list**
Variant: **End of section**
Framework: **Web components**
Breakpoints: **Desktop and mobile**
Environment: **Canary, production**

#### A few style regressions

1. Based on [functional spec](https://ibm.ent.box.com/file/701341004019?s=9z0w7wb5lphykujnq3pxz6iuvmwy9glm), types knobs should never contain `none` as an option. Default should be `local`
2. All types except `none` is showing the wrong icon alignment. Icon should align to right of columns
3. Expecting `type = video` to change link list heading to **video title**, and append **duration** to  in a parentheses

![Oct-29-2021 12-35-53.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/44ff2159-f2b4-4983-98b5-550326e9b31c)

#### Expected design
Spec: https://ibm.box.com/s/hgrc62y10kopxdk5z75fcxq48m6ad3vc
And currently React is showing the proper style on **Link list - end of section**: https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-link-list--end-of-section

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/52f8ec02-cc31-48ac-9e3f-65aecf9928d8)

**Comment by tuanthanh2067** [comment]
Hello there, do you mind if I wan to try this one?

**Comment by jeffchew** [comment]
Hi @tuanthanh2067 , sure! Would be happy to receive your contribution! Let us know if you have any questions!

When the time comes to opening a PR, we will need to get you to [sign a CLA](https://www.ibm.com/standards/carbon/contributing/overview#contributor-license-agreement) before it can be merged in.

cc: @ariellalgilmore @IgnacioBecerra
