### ISSUE TITLE
Scroll animation / fade Functional specs

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#756]
### User story
As a user of IBM.com, I would like the experiences to be more dynamic and responsive to scrolling so that I can stay longer without losing attention and know that the experience is actively responding to my actions.

### Notes
- This is to add the ability to add scroll-fade to any elements on a page.
- As user scrolls, elements on a page should fade in and slide up slightly.

#### Additional Information
- [Scroll animation Ideation epic #144 link](https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/144)
- [Functional specs box folder](https://ibm.ent.box.com/folder/125890741222)

#### Acceptance Criteria
- [ ] Create a Box folder for the `Scroll animation` (if not already there)
- [ ] Update the Ideation Board epic with the specs link
- [ ] Update the Agile Board epic with the spec link
- [ ] Add Box folder link to the website content if it exists

**Comment by photodow** [comment]
[Functional specs](https://ibm.ent.box.com/file/739961020599)
[Coded prototype](https://codepen.io/photodow/full/vYKaaxK)
