### ISSUE TITLE
[Safari browser] Analyze and fix visual differences found by Percy

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7566]
####  Overview
Throughout the component development Percy has been used to QA the engineering work for the Chrome browser.  Percy has been turned on for the Safari browser.  The differences found will be reviewed by the designers.  Bugs will be created for the engineers to fix.  All related work will be linked to this epic.

To review, go to: [Percy build link](https://percy.io/538fc19a/Carbon-for-IBM.com-Web-Components/builds/13642748/changed/771932768?browser=safari&browser_ids=18%2C20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=320%2C1280)

**Comment by shixiedesign** [comment]
Update: 
I've went through 1 - 56 out of 125 snapshots. Will pick up again tomorrow.

**Comment by shixiedesign** [comment]
Complete!
