### ISSUE TITLE
Safari baseline: list of components missing snapshots

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7567]
Missing snapshots on these components: 

**1280px**

- Quote 
- Link list - end of section
- Lead space - tall 
- Dotcom shell - With L1 
- Content block simple: With video 
- Card group: Default

**320px**
- Content block media: With link list
- Card group: With images

**Comment by jeffchew** [comment]
Iceboxing for now. Disabled safari diffs in order to conserve on snapshot monthly quota.
