### ISSUE TITLE
Safari baseline: [Lead space centered] Gradient direction and padding diff

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7573]
A few issues noticed: 

1. Desktop, gradient direction & values appear different 

Safari:
![image](https://user-images.githubusercontent.com/1641214/140796194-0aa8bbec-5526-4f44-b9e9-7852575e5dba.png)

Chrome: 
![image](https://user-images.githubusercontent.com/1641214/140796252-233c1764-a5f3-4433-8886-8b3c1dd632cf.png)

2. Mobile, extra padding in Safari on Center aligned lead space

![lead space centered 1](https://user-images.githubusercontent.com/15144993/144238306-c59341c4-1341-4288-8328-f39760fc7bcd.gif)

**Comment by proeung** [comment]
There are a couple of issues to consider before starting on this issue. See https://github.com/carbon-design-system/carbon/issues/9142 and https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7148.
