### ISSUE TITLE
Web component: Masthead - Search edit field close icon is not working

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#7587]
### Description

Issue: 
On Mobile:
Masthead search edit field close icon does not clear the keyword and does not close edit field.
Once the user enters keyword and clicks on close icon, user again opens the search field then close icon is missing.

Note: Working fine on react version.

### Component(s) impacted

![Mast3](https://user-images.githubusercontent.com/60002341/140065306-c6682f29-8b99-4934-9d2b-eef52bfb712d.gif)

### Browser

Chrome, Safari, Firefox

### Carbon for IBM.com version

1.27

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

Web component

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

NA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
@Praveen-sr was monitoring e2e tests after the hotfix was merged, it looks like it might have introduced another bug where clocking away from the search box will close it out, even when there are results showing. Can you verify as part of your testing?

![Kapture 2021-11-03 at 20 19 44](https://user-images.githubusercontent.com/1641214/140236931-d22b2ac9-74d9-459b-927e-cc93f079d039.gif)

cc: @IgnacioBecerra

**Comment by Praveen-sr** [comment]
@jeffchew I verified on web component:
Yes, clicking away from the search box will close it out, even when there are results showing.

![Search_close](https://user-images.githubusercontent.com/60002341/140280804-9c8433cc-53b5-4b24-965d-291a4376f7d2.gif)
cc @RobertaJHahn 


Expected: 

![Search_close_expected](https://user-images.githubusercontent.com/60002341/140280979-3754f5d4-0075-4bb1-a4ec-7712b3932bb5.gif)
