### ISSUE TITLE
[IBM Accessibility]: Investigate automated tests not running in React

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#7598]
### Description

Currently the tests are not running properly in the workflow:

![image](https://user-images.githubusercontent.com/1641214/140334560-d007618f-aeae-4fb7-9ca4-65e5d412e80b.png)

### Component(s) impacted

React is currently encountering this. It appears it's not set up for Web components, which we will need to do in a separate issue.

### Browser

Chrome

### Carbon for IBM.com version

v1.26.0

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

Carbon for IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/runs/4105364428?check_suite_focus=true

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by tombrunet** [comment]
Looks like this is trying to process the image files rather than just the HTML files. May need a guard there somewhere to skip images.

**Comment by RobertaJHahn** [comment]
No longer needed.
