### ISSUE TITLE
[ibm.com/standards/web page]  Review Linda's recommended solution and propose a solution reviewed by Design

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7601]
### The problem

Users who are not working within IBM VPN will get an error page when they try to click on most of the links on this page -> ibm.com/standards/web

### Suggested solution

So for all links on this page that send the user to w3 page, need to add to the card an indicator that it is for internal use.

An example is on this page:   

https://www.ibm.com/design/language/ibm-logos/8-bar

under the Resources section.  It show message after title  (IBM id required)

### Application/website

www.ibm.com/standards/web

### Additional Information
- Dev issue (#7565 )
- Link to repo for changes:  https://github.ibm.com/webstandards/standards-website
- Page where the edits will be needed: https://github.ibm.com/webstandards/standards-website/blob/master/src/gatsby-theme-carbon/templates/Homepage.js.

### Acceptance Criteria
- [ ] Linda's recommended solution and additional options are reviewed
- [ ] Design solution is reviewed with the DDS designers for input
- [ ] Dev issue is updated with the final design

**Comment by ljcarot** [comment]
Don't need this design story.
