### ISSUE TITLE
Masthead functional spec clean up and migrate to wiki 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7613]
Currently, masthead functional spec is here https://ibm.ent.box.com/folder/126271959517 and it doesn't follow the latest functional spec template. 

The word document is due for a big clean up, and we should migrate to the expected wiki location: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Masthead

**Comment by photodow** [comment]
@RobertaJHahn @shixiedesign any chance we can prioritize this for next sprint?
