### ISSUE TITLE
Beacon [Universal banner]: add usage rules

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7619]
The following usage rules should pass:
1. Universal banner must always be above the masthead 
2. Test for any content overflow. If there are content overflow, because the universal banner has a max height, the overflown content will not be accessible.

**Comment by RobertaJHahn** [comment]
Closing.  This issue is replaced by [issue 57](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/ibm/beacon-for-ibm-dotcom/57) in the Beacon repo.
