### ISSUE TITLE
[Masthead] func spec: add behavior when universal banner is present

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7620]
This feature was discussed/designed during Universal banner work, but still needs to be updated on the masthead side: 

https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/7216

**Masthead need a logic to calculate its position when Universal banner is present. This should also influence the position of mega menu & left nav when on mobile.**

**Comment by photodow** [comment]
Here is the update I made. I think there are a couple different directions we could take on this. I figured I would start with what seems to be the simplest, and we can discuss with development if another approach needs to be taken.

I reworded some of the sticky behavior for this component, but in general what I added was the masthead is static (meaning it scrolls on the page like everything else) until it reaches the top of the page where it then becomes sticky depending on lower level navigation items. It's the static aspect that's new here for the L0. That has been present in the table of contents and even L1 up to this point.

###### masthead container
![image](https://user-images.githubusercontent.com/3793636/141653263-012de265-a01c-4c8d-8afc-ac6866278a85.png)

###### Mobile masthead container
![image](https://user-images.githubusercontent.com/3793636/141653214-26601f43-faac-4663-95fb-323e80eca432.png)


###### mobile menu container
![image](https://user-images.githubusercontent.com/3793636/141593731-e6f74fff-7e7d-4372-b3df-cbb44aa3e82a.png)

Here is the [box folder](https://ibm.box.com/s/xul87svjz92a6c1zzo0nhqkyvljrfkhi)

**Comment by RobertaJHahn** [comment]
@photodow Could you post a link to the func specs in this issue.  I'll schedule for review and sizing on Monday, Nov 22, engineering meeting.  Thanks.
