### ISSUE TITLE
[Content item horizontal with media]: Padding issues

### ISSUE THREAD

**Issue by yosefwpp** [carbon-design-system/carbon-for-ibm-dotcom#7621]
## Incorrect padding on mobile breakpoint

* https://jsw.ibm.com/browse/ADCMS-1513

### Description
`Item Horizontal with Media` content should have 16px padding for 672px and 320px breakpoints on each sides

https://dev-author.np-roks.cms.cis.ibm.net/content/adobe-cms/language-masters/en/yosef-test-page/solution-test-page0.html?wcmmode=disabled

### Actual result
* The padding for the component is not being applied correctly, the padding is there, but is not being used correctly by the component

### Expected result
* The padding should be applied correctly to the whole component

### Steps to reproduce the issue 
1. Place an `Item Horizontal Group` component
2. Inside the `Item Horizontal Group` add an `Item Horizontal with Media` component

### Additional information

![Screen Shot 2021-11-08 at 12 58 10](https://user-images.githubusercontent.com/93942987/140809290-c53defd9-fb07-4fc1-96fc-44b2f253db46.png)

<img width="727" alt="Screen Shot 2021-11-08 at 13 32 21" src="https://user-images.githubusercontent.com/93942987/140809315-855399d8-3a92-408c-8600-a937ea6d177a.png">

-----

![Screen Shot 2021-11-08 at 12 59 19](https://user-images.githubusercontent.com/93942987/140809335-902d6db0-abd0-4278-8c5b-65644262a271.png)

<img width="515" alt="Screen Shot 2021-11-08 at 13 31 11" src="https://user-images.githubusercontent.com/93942987/140809350-950c2883-12bc-4240-9bea-a4efa2c69100.png">

### Carbon for IBM.com version
1.26.0

### Package
@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

**Comment by proeung** [comment]
@yosefwpp @EAVilleda Looks like some of these padding issues that are noted above have already been addressed in past dev issues (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7765 and https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7269).

Can you take a look at the canary deploy preview and let us know if you're seeing the missing paddings on the tablet and mobile breakpoints? https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/?path=/story/components-content-item-horizontal--default

**Comment by yosefwpp** [comment]
@proeung Thank you for the support, this has been fixed, adding css styling to the component, and no longer an issue.

**Comment by proeung** [comment]
@yosefwpp Thanks for getting back to me. I'm going to close out this issue as no further action is needed.

cc: @ljcarot @jeffchew
