### ISSUE TITLE
[Masthead, search] Web Component: Change the component to include the scoped search feature

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7627]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `Masthead, search`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic (#7267 ) for the Design and Functional specs information**
- This issue is blocked by the issue (#TBD) to include the Grouped results (included in the React version)
- The widget will allow self service style scoping of search results by taking in explicit and implicit parameters in order of priority
- Scoping can be done via different types of parameters, so we need a param for scoping "type" and one for "value"
- Explicit scoping parameters overrule the implicit ones, so a user can set the type and value explicitly and that will be what is used
- For explicit scoping types/values, the masthead search widget will not keep an allow list on the allowed scoping values for each type, and maybe even which explicit types will be allowed.  The widget should be agnostic and the explicit scoping type/value communication is between the page owner and the search app
- Web Components Visual QA testing issue (#7628)
- Web Components Prod QA testing issue (#7629)

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] Update the e2e test scripts, if needed. 
- [ ] Confirm e2e test results have no major errors.
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Prod QA issue, tagging Praveen when development is finished

**Comment by oliviaflory** [comment]
There is a [search with dropdown](https://github.com/carbon-design-system/carbon-web-components/issues/300) issue open for Web components package that is very similar to this as well, it may not cover the change from desktop to small breakpoint though.
