### ISSUE TITLE
Web component NextJS page: Issues on g100 theme example page

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#7632]
### Description

Issue: 
On Web component NextJS page:
1. Table of contents - horizontal bar is not sticking to top of the page. When user scrolls the page its getting hidden.
2. On Card section images, all content on the cards are not visible for the user
3. Content Block Horizontal, Content Block Segmented heading are not visible for user.
4. On Content Block Segmented, paragraph text is not visible for the user.

 

### Component(s) impacted

![WebCom_Nextjs](https://user-images.githubusercontent.com/60002341/140943416-4ea37e7e-6481-42ab-8797-5603aab6889b.gif)

### Browser

Chrome, Firefox

### Carbon for IBM.com version

1.27.0-rc.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

Web component NextJS

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

NA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
A bug ticket has been opened for the TOC not sticking to the top of the page on scroll here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7641
