### ISSUE TITLE
[Content block horizontal] Add ability to hide horizontal rule in dds-content-group-horizontal element  - DDS Consulting 

### ISSUE THREAD

**Issue by EAVilleda** [carbon-design-system/carbon-for-ibm-dotcom#7640]
**Engineering info:**  
- HC engineer: @andy-blum 
- HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2340
- DDS consulting engineer:

----

### The problem

![image](https://user-images.githubusercontent.com/47429622/141153349-9015f50e-377e-44d9-a050-d39216f4f1cb.png)

We need to be able hide horizontal rule in the ~dds-content-group-horizontal~ [Content block horizontal](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-content-block-horizontal--default) element. 

### The solution

The solution would be an attribute we can pass in the element to hide the horizontal rule. Similar to how no-border is used in the dds-cta-block element.

### Application/website

AEM (Marketing)

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by photodow** [comment]
@EAVilleda can you please provide a use case or scenario of where you're hoping to use this in context?

**Comment by EAVilleda** [comment]
@photodow Item Horizontal Group is one of many components that should support hiding the Horizontal Rule on any page in AEM. https://jsw.ibm.com/browse/ADCMS-1748

**Comment by photodow** [comment]
Ah, ok I think I see now. There are a few horizontal rules in this component, but if I understand correctly you're asking for the horizontal rule at the bottom of the component that's apart of the content block. correct? It appears we are incorrectly hard coding it [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/react/src/components/ContentBlockHorizontal/ContentBlockHorizontal.js#L25) to `true`.

[Here are the functional specs for the border](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Layout#4-border) used in [Content block horizontal](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-block-horizontal), and [Content block](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-block).

@EAVilleda let me know if I misunderstood. I'm going to reclassify this as a bug for now, and make sure the description is clear with the correct component.

**Comment by EAVilleda** [comment]
That's correct, I am asking about the last horizontal rule, at the bottom of the component.
