### ISSUE TITLE
[Masthead]: Accessing User profile button first makes the L0 menu items to open on top of each other

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#7644]
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2399
- DPO consulting engineer: @annawen1 

-----

### Description

Present on IBM homepage. The bug was found and resolved a while ago. It reappeared somehow. 

1. Click User profile
2. Start clicking on L0 menu items
3. They are opening on top of each other
<img width="1666" alt="Screenshot 2021-11-11 at 14 49 18" src="https://user-images.githubusercontent.com/48327647/141301451-1e37caef-3b08-489a-83dc-1cbec8db3fe7.png">

### Component(s) impacted

Masthead

### Browser

Chrome

### Carbon for IBM.com version

IBM homepage

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://www.ibm.com/us-en/

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/us-en/

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
This problem originates from Carbon core.  The UI shell has been created in carbon for ibm.com and can be fixed in our code.

**Comment by jeffchew** [comment]
Was able to replicate in both React and Web Components. We might want to create a separate issue for React.

**Comment by andy-blum** [comment]
I'm not able to replicate this in the web components package - working on the react package instead.

**Comment by proeung** [comment]
@andy-blum Thanks for taking a look! I'm going to move this issue up to Sprint: 04 as I don't think we'll be able to get a PR up and reviewed/approved in time for today's code freeze period.

cc: @ljcarot @jeffchew

**Comment by andy-blum** [comment]
ATTN: @proeung @jeffchew

This is an upstream issue that will need to be fixed in carbon core.

The [MastheadProfile component](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/react/src/components/Masthead/MastheadProfile.js#L47-L53) returns the following:
```js
  return (
    <OverflowMenu
      className={`${prefix}--header__action`}
      {...overflowMenuProps}>
      {profileNav}
    </OverflowMenu>
  );
```

The [OverflowMenu](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/OverflowMenu/OverflowMenu.js#L523-L538) in turn renders a [FloatingMenu](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/internal/FloatingMenu.js#L443-L464):
```js
    const wrappedMenuBody = (
      <FloatingMenu
        focusTrap
        triggerRef={this._triggerRef}
        menuDirection={direction}
        menuOffset={flipped ? menuOffsetFlip : menuOffset}
        menuRef={this._bindMenuBody}
        flipped={this.props.flipped}
        target={this._getTarget}
        onPlace={this._handlePlace}
        selectorPrimaryFocus={this.props.selectorPrimaryFocus}>
        {React.cloneElement(menuBody, {
          'data-floating-menu-direction': direction,
        })}
      </FloatingMenu>
    );
```

If we edit the imported files to set `focusTrap={false}` that fixes the error here, but also breaks the ability to enter the overflow menu via keyboard navigation.

I attempted to clone the repo and make some changes, but I'm running into the following issue:

```
ModuleBuildError: Module build failed: Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Node.js 14.x
```

**Comment by proeung** [comment]
@andy-blum Thanks for taking a look at this issue. I'll go ahead and move this issue to "Blocked from scheduling" as this bug needs to be resolved within the Core Carbon side.

@annawen1 Please include the link to the Carbon Core issue here. Thanks!

cc: @kennylam

**Comment by kennylam** [comment]
> I attempted to clone the repo and make some changes, but I'm running into the following issue:

@andy-blum you can try `npm rebuild node-sass` and see if that fixes it.

**Comment by andy-blum** [comment]
@kennylam it's an issue with the new mac M1's ARM architecture. This will need some dependency updates to make compatible

**Comment by kennylam** [comment]
Ah gotcha. I somehow dodged that bullet. Haven't had any issues on M1 so far.

**Comment by andy-blum** [comment]
That's odd - I'm curious how you got the carbon package up and running then while I cannot 🤔

**Comment by annawen1** [comment]
@proeung @andy-blum Here's the link to the Carbon core bug issue: https://github.com/carbon-design-system/carbon/issues/10828

**Comment by tw15egan** [comment]
Just pushed up a [PR](https://github.com/carbon-design-system/carbon/pull/10829) to core that will allow the `focusTrap` prop to be configured by the end-user, but as @andy-blum said, this will break keyboard navigation. Open to suggestions in that regard.

Also, I believe the repo requires Node 16 to build properly, but it could also be an M1 issue (I'm running an old, non-M1 Macbook so I'm not sure)

**Comment by andy-blum** [comment]
@tw15egan Thanks for the suggestion to Node 16.

I was using v14 (which FYI, is [specified in the contribution readme](https://github.com/carbon-design-system/carbon/blob/main/.github/CONTRIBUTING.md?plain=1#L23)). I've switched versions and am re-building now, hopefully I can find a solution to the keyboard nav issue.

**Comment by tw15egan** [comment]
@andy-blum thanks for pointing that out, let me get that updated

**Comment by proeung** [comment]
Moving this issue out of our queue. cc: @kennylam
