### ISSUE TITLE
[Table of Contents]: Heading content does not display after screen resize

### ISSUE THREAD

**Issue by andy-blum** [carbon-design-system/carbon-for-ibm-dotcom#7663]
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2360
- DPO consulting engineer: N/A
----

### Description

The WC Table of Contents component's "with heading content" variation shows a picture above the ToC on desktop sizes, and above the indexed content on mobile sizes. Crossing the breakpoint from mobile to desktop layout, however, causes the image to no longer display.

https://user-images.githubusercontent.com/25532785/141854695-f8e8e38f-a23b-41d2-881f-fe03b76a402a.mov

### Component(s) impacted

Table of Contents (with heading content)

### Browser

Chrome

### Carbon for IBM.com version

1.27.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

carbon-for-ibmdotcom

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-table-of-contents--with-heading-content

### Steps to reproduce the issue (if applicable)

Shrink window to mobile size, then expand to desktop size again

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@andy-blum Thanks for opening this issue! 

I find it odd that in the SB preview example that we have the `<dds-image>` component placed below the `<dds-table-of-contents>` instead of returning it in the inner content area (see attached). Feel like an issue in the way we're assembling the components in the SB example.

![Screen Shot 2021-12-08 at 12 23 47 PM](https://user-images.githubusercontent.com/1815714/145255482-d3535729-d125-4226-a88d-e7f5cc37cd4d.png)

@shixiedesign or @jeffchew Love to get your thoughts on this.

**Comment by RobertaJHahn** [comment]
@oliviaflory @RichKummer This decsign decision will be needed next year to move the dev work forward.  Dev has been tentatively assigned to the first sprint of 2022.

**Comment by proeung** [comment]
@oliviaflory @RichKummer When you have a moment, can you let me know what's the design preference is for the placement of the image within the SB preview? Thanks! https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7663#issuecomment-989022781

**Comment by oliviaflory** [comment]
> @oliviaflory @RichKummer When you have a moment, can you let me know what's the design preference is for the placement of the image within the SB preview? Thanks! #7663 (comment)

@proeung The example of `Table of contents with heading content` allows for an image, or other items like links, to be placed above the TOC. This was originally designed by a team that intended to use the space for back links to different pages. It's a bit unusual, and not commonly used right now.

**Desktop**
![Screen Shot 2022-01-12 at 4 28 52 PM](https://user-images.githubusercontent.com/45692622/149224812-4d4aeaad-48bb-4973-bdba-e6438b57c677.png)


At the smaller breakpoints (medium and small) the "heading content" does move into the inner area of the page, the TOC is sticky and scrolls with the user, indicating what section the user is in.

**Medium breakpoint**
![Screen Shot 2022-01-12 at 4 29 03 PM](https://user-images.githubusercontent.com/45692622/149224624-5c553516-2b03-49a7-9f2a-a86ef2146c8f.png)

**On scroll**
TOC is sticky, heading content is static.
![Screen Shot 2022-01-12 at 4 34 12 PM](https://user-images.githubusercontent.com/45692622/149224796-b9c8d84b-cf9b-4bad-bbe0-e944308c3876.png)

----

What Andy is pointing out does seem to be a bug, the image disappears when changing the browser size from `desktop` to `mobile` back to `desktop`.

I would expect the image to return to the space above the TOC when moving from mobile to desktop.

**Comment by proeung** [comment]
@oliviaflory Thanks for clarifying this! Glad to see that the `Table of contents with heading content` allows for an image and other components like links to be placed above the TOC listing and not just in the TOC content area.

We'll move forward with this issue and fix the image disappearing bug.
