### ISSUE TITLE
[Masthead (Global)]: z-index/overlapping issue within Drupal page integration 

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#7675]
**Engineering info:**  
- HC engineer: @proeung 
- HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2325
- DDS consulting engineer: @emyarod 

----

### Description

- The Hybrid Cloud team is in the process of adopting the <dds-masthead-container> component to launch two navigational L0’s supporting the QRadar & Storage content ecosystems that are managed in Drupal and AEM (see attached).
- We're able to successfully pull in the `<dds-masthead-container>` in a page builder template within Drupal (see - https://pr1558-vw04dbfv1j8wrjmghdgeaqqaxk6ur6dt.w3-origin-007522.intranet.ibm.com/security/security-intelligence/qradar), however, there's an overlapping issue seen due to the z-index stacking issue.

https://user-images.githubusercontent.com/1815714/142066793-1a99fcb9-bf8d-48e8-a246-528c429beee8.mov

### Solution
- Looks like we can adjust the z-index of `<dds-masthead-container>`, similar to what we've implemented on the `<dds-cloud-masthead-container>` component. https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7037

### Component(s) impacted

Global Masthead - `<dds-masthead-container>`

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v.1.27

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Drupal

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

N/A

### Steps to reproduce the issue (if applicable)

- Visit this demo page - https://pr1558-vw04dbfv1j8wrjmghdgeaqqaxk6ur6dt.w3-origin-007522.intranet.ibm.com/security/security-intelligence/qradar (_requires VPN_)
- Click on one of the dropdown menu items.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
@proeung This fix should be quickly regression tested by Praveen.  Could you tag him in either the PR or this issue with testing instructions  when the PR is merged.  

cc:  @Praveen-sr @jeffchew @ljcarot
