### ISSUE TITLE
[Card]: Change the functional specifications to allow text link in all situations

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7677]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Card` functional specs 

> so that I can:
so that I can properly code the `Card` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#7631 )**

#### Acceptance criteria
 - [ ] Documented `Card` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by shixiedesign** [comment]
Checked functional spec, the text link is not forbidden as we thought. So no change is needed. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/c36edcd2-67d6-4e43-b12a-e1ee99dab085)

**Comment by photodow** [comment]
I think clarification here is needed @shixiedesign. The add here is add text even when the whole card is already interactive. The way this is written now is it's either or.

**Comment by shixiedesign** [comment]
@photodow I agree. Looks almost like this is inclusive of static card. But it didn't seem to impact the feature request. Lemme know if you agree. 

Card's func spec could use a clean up like Masthead's one later.

**Comment by photodow** [comment]
> Card's func spec could use a clean up like Masthead's one later.

Definitely agree.

> But it didn't seem to impact the feature request.

Not sure how it doesn't impacts the work. Do you mean that development has enough information to go on so that this doesn't block them? It definitely needs to be done I think, but I can see how this wouldn't have to block development moving forward. It's a small change for both parties, and I think we're all aligned on it at this point.
