### ISSUE TITLE
[Footnotes section]: Create functional specifications for the new design

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7698]
#### User Story

> As a `[user role below]`:
DDS developer

> I need to:
have the `Footnotes section` functional specs 

> so that I can:
so that I can properly code the `Footnotes section` component that meets the Design functions and intent

#### Additional information

- **Overview and scope of the engineering work should be included in the linked epic (#4434 )**
- 

#### Acceptance criteria
 - [ ] Documented `Footnotes section` functional specifications
 - [ ] Sent and/or presented the specs to Design and Engineering for their review and comments
 - [ ] Comment is added with link to functional specs

**Comment by RichKummer** [comment]
Carbon's v11 update contains changes to the tooltip, splitting it into a default tooltip (which does not display interactive links) and a toggle tooltip (which can). 

More info on the toggle tooltip: https://carbondesignsystem-git-fork-kingtra-17c6a2-carbon-design-system.vercel.app/components/toggletip/usage/
