### ISSUE TITLE
[Footnotes section] Web Component & React Wrapper: Develop component based on the new designs

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7699]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `Footnote section`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- The React version is created as a wrapper to the Web Components version
- **See the Epic (#4434 ) for the Design and Functional specs information**
- Visual QA testing issue (#7700 )

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] add the trigger to create the React Wrapper
 - [ ] create the React storybook stories and related documentation
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Design QA issue, tagging Designer, when development is finished.

**Comment by jeffchew** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Carbon-for-IBMcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/7699?planning-poker) with ZenHub @annawen1

**Comment by proeung** [comment]
Adding the "follow-up: innovation team" label to see if this is something that our Innovation team can help pick up in the next issue sharing meeting. cc: @jeffchew @ljcarot

**Comment by jeffchew** [comment]
We will schedule a walk through with innovation team and @RichKummer to get a sense of the work.

**Comment by kennylam** [comment]
From @oliviaflory: This is on hold until we upgrade to v11 so we can utilize the new and improved toggle tip for accessibility reasons. More info [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7698#issuecomment-1009357293).
