### ISSUE TITLE
Knowledge transfer: James

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7703]
#### Special area of expertise: 

- [ ] Func'l specs
   - [x] [Functional spec workshop](https://cognitive-app.slack.com/archives/G01CFF8ETPU/p1631122032029700?thread_ts=1631118884.024700&cid=G01CFF8ETPU)
   - [x] [Functional specs wiki](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki)
   - [x] [Functional specs Box](https://ibm.ent.box.com/folder/94084789008)
   - [x] [Writing functional specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Writing-functional-specs)
   - [x] [Functional specs template](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Functional-spec-template)
   - [x] [original pattern research and breakdown](https://ibm.box.com/s/193e0pmmzuez8qxrfgwssfha3fn2sf7s)
   - [x] [original ontology & hierarchy](https://app.mural.co/t/digitaldesignsystemsquadwork2176/m/digitaldesignsystemsquadwork2176/1579536578502/f6889e09b56bc7aec34cd62954ec78766ae3c5c7?sender=jamesdow)
   - [x] [Knowledge transfer session with both Design and Engineering team members](https://cognitive-app.slack.com/archives/G01CFF8ETPU/p1639509646001900?thread_ts=1631118884.024700&cid=G01CFF8ETPU)
   - [ ] Finish migration from Box to Wiki (stretch goal)
- [x] Carbon devtools
   - [x] [High level walkthrough design and dev](https://cognitive-app.slack.com/archives/GBG66T9NK/p1638300999312900?thread_ts=1638215661.294700&cid=GBG66T9NK)
   - [x] Transfer google analytics `cc Matt Rosno`
   - [x] Update permissions under repo `cc Matt Rosno`
   - [x] Transfer URLs in [snip](https://snip.innovate.ibm.com/) `cc Matt Rosno`
   - [x] Remove publishing tokens from account APIs `cc Matt Rosno`
   - [x] Remove Video demo on markteplace from account [`cc Carbon design system Youtube`](https://youtu.be/jxrymjzuHHY)
   - [x] Remove Google analytics API key from account
   - [x] Walkthrough deep dive with design
       - [x] [Shixie's design explorations](https://cognitive-app.slack.com/archives/GBG66T9NK/p1638809602392700?thread_ts=1638215661.294700&cid=GBG66T9NK)
       - [x] [Google analytics walk through](https://cognitive-app.slack.com/archives/GBG66T9NK/p1639581023026800?thread_ts=1638215661.294700&cid=GBG66T9NK)
- [x] [Google Analytics reports](https://cognitive-app.slack.com/archives/GBG66T9NK/p1637588232243400)
  - [x] Turn off email reports `cc Linda Carotenuto`

#### Common things to prep access:
- upload any relevant computer **local files** 
- clean up box folder organization 
- Boxfolder / Boxnote
- InVision 
- Murally
- Figma
- Airtable

<details>
  <summary><strong>Functional specs migration list</strong> (54)</summary>

- [ ] [Masthead (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Masthead)
- [ ] [Mega menu (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Mega-menu)
- [ ] [Card (3)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card)
- [ ] [Card group (4)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-group)
- [ ] [Link list (6)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Link-list)
- [ ] [Table of contents (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Table-of-contents)
- [ ] [Carousel (2)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Carousel)
- [ ] [Search typeahead (2)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Search-typeahead)
- [ ] [Locale modal (2)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Locale-modal)
- [ ] [Leaving ibm (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Leaving-ibm)
- [ ] [Background media (2)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Background-media)
- [ ] [Footer (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Footer)
- [ ] [Back to top (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Back-to-top)
- [ ] [Locale service (3)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Locale)
- [ ] [Translation service (3)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Translation)
- [ ] [Scroll into view utility (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Scroll-into-view)
- [ ] [Scroll animations (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Scroll-animations)
- [ ] [Same height utility (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Same-height-utility)
- [ ] [CTA block (2)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/CTA-block)
- [ ] [CTA section (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/CTA-section)
- [ ] [Card section carousel (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-section-carousel)
- [ ] [Card section images (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-section-images)
- [ ] [Card section offset (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-section-offset)
- [ ] [Card section simple (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-section-simple)
- [ ] [Card section (2)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-section)
- [ ] [Content block cards (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-block-cards)
- [ ] [Content block media (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-block-media)
- [ ] [Content block mixed groups (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-block-mixed-groups)
- [ ] [Content block segmented (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-block-segmented)
- [ ] [Content block simple (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-block-simple)
- [ ] [Content group banner (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-group-banner)
- [ ] [Content group cards (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-group-cards)
- [ ] [Content group pictograms (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-group-pictograms)
- [ ] [Content group simple (2)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Content-group-simple)
- [ ] [Feature section (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Feature-section)
- [ ] [Lead space block (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lead-space-block)
- [ ] [Lead space search (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lead-space-search)
- [ ] [Lead space (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lead-space)
- [ ] [Link list section (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Link-list-section)
- [ ] [Logo grid (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Logo-grid)
- [ ] [Tabs extended media (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Tabs-extended-media)
- [ ] [Button group (2)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Button-group)
- [ ] [Card in card (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Card-in-card)
- [ ] [Expressive modal (3)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Expressive-modal)
- [ ] [Feature card (2)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Feature-card)
- [ ] [Filter group (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Filter-group)
- [ ] [Filter panel (0)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Filter-panel)
- [ ] [Input select (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Input-select)
- [ ] [Link with icon (3)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Link-with-icon)
- [ ] [Pictogram item (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Pictogram-item)
- [ ] [Quote (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Quote)
- [ ] [Tag group (3)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Tag-group)
- [ ] [Tag link (1)](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Tag-link)

</details>

**Comment by photodow** [comment]
Who am I transferring to?
