### ISSUE TITLE
Knowledge transfer: Jan

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7704]
#### Special area of expertise: 

- content/website stories
- any drafts / planned future work 
- contacts to conversation scientist for Slack bot work

#### Common things to prep access:
- upload any relevant computer **local files** 
- clean up box folder organization 
- Boxfolder / Boxnote
- InVision 
- Murally
- Figma
- Airtable

**Comment by janchild** [comment]
I've created a folder in Box called [Content review tools](https://ibm.ent.box.com/folder/152805575255). It includes:

- [Carbon for IBM.com style guide](https://ibm.ent.box.com/notes/899180253007) that provides the basics for what you need to develop content that follows the IBM style.
- [Checklist for PR reviews](https://ibm.ent.box.com/notes/899208246216) that is a short checklist to use when reviewing other PRs, highlighting the items to watch out for. 

@oliviaflory and @RichKummer, these are works in progress and let me know if there are any topics that you'd like to add!
