### ISSUE TITLE
[404 page] Create new design - continuation from 5976

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#7709]
#### Issue description update from Shixie, Dec 13, 2021
Existing exploration from @DragosRistici https://ibm.ent.box.com/folder/150147427973?s=cazz3zid4uq7f635sw2od6hpgyo20kpd
The exploration has received the following feedback: 
- exciting concept of past-vs-future
- content requirement of this design is potentially too much work to maintain
- need something that requires less maintenance, more timeless
- need to expand the design to be able to work as other error pages as well eg. 300, 303, 500, 505 etc.. see full list below

___

## Design brief 

- A friendly message could be written that includes these words: `404`, `Page not found`
- Provide pathways forward, eg. Search & Popular links
- Demonstrate IBM brand philosophy https://www.ibm.com/design/language/philosophy/principles
- Consider this error page an opportunity to show IBM's best side 

## Additional info 

- [Design Box folder](https://ibm.ent.box.com/folder/150147427973)

#### User story
As a user of IBM.com, I need to be informed of an HTTP error and understand what the next steps are.  The error pages were implemented on v18.  This work is needed for Carbon.  

#### Next Steps
- Research
- Design exploration
- Design
- Review & approval
- Development
 
#### Examples:
https://www.ibm.com/common/errorpages/300.html
https://www.ibm.com/common/errorpages/303.html
https://www.ibm.com/common/errorpages/305.html
https://www.ibm.com/common/errorpages/307.html
https://www.ibm.com/common/errorpages/400.html
https://www.ibm.com/common/errorpages/401.html
https://www.ibm.com/common/errorpages/402.html
https://www.ibm.com/common/errorpages/403.html
https://www.ibm.com/common/errorpages/404.html
https://www.ibm.com/common/errorpages/405.html
https://www.ibm.com/common/errorpages/406.html
https://www.ibm.com/common/errorpages/407.html
https://www.ibm.com/common/errorpages/408.html
https://www.ibm.com/common/errorpages/409.html
https://www.ibm.com/common/errorpages/410.html
https://www.ibm.com/common/errorpages/411.html
https://www.ibm.com/common/errorpages/412.html
https://www.ibm.com/common/errorpages/413.html
https://www.ibm.com/common/errorpages/414.html
https://www.ibm.com/common/errorpages/415.html
https://www.ibm.com/common/errorpages/416.html
https://www.ibm.com/common/errorpages/417.html
https://www.ibm.com/common/errorpages/500.html
https://www.ibm.com/common/errorpages/501.html
https://www.ibm.com/common/errorpages/502.html
https://www.ibm.com/common/errorpages/503.html
https://www.ibm.com/common/errorpages/504.html
https://www.ibm.com/common/errorpages/505.html

**Comment by DragosRistici** [comment]
Continuation from [404 page] Create new design #5976

**Comment by shixiedesign** [comment]
@DragosRistici completed a round of explorations and files can be found here: https://ibm.ent.box.com/folder/150147427973?s=cazz3zid4uq7f635sw2od6hpgyo20kpd

Next year, this issue needs to be picked up again and I've updated the issue description with this detail.

**Comment by oliviaflory** [comment]
Feedback from Mike on the options presented on Dec 13
> I like the options on pages 10, 14—16 which offer useful/valuable statistics or insights.
I also like the abstract illustrations like pg. 23 and 26—27. I think these should be light theme given the new brand promise work. I think the light colors work well in the statistics concept as well.
Those ISO illustrations can incorporate the animations you mentioned as well.

Still need to consider the feedback stated within the main issue
