### ISSUE TITLE
[Card group] Issue on video overlay

### ISSUE THREAD

**Issue by KIQsco** [carbon-design-system/carbon-for-ibm-dotcom#7712]
### Description

on the video overlay, the text next to the video do not have a padding between them.
<img width="868" alt="Captura de Tela 2021-11-19 às 15 23 19" src="https://user-images.githubusercontent.com/88741436/142672767-62cb192b-035e-4e72-8926-ae05b5100822.png">

### Component(s) impacted

<img width="868" alt="Captura de Tela 2021-11-19 às 15 23 19" src="https://user-images.githubusercontent.com/88741436/142672809-da96b8c1-3a4b-4c57-855c-ce270fb55eb0.png">

### Browser

Chrome

### Carbon for IBM.com version

ˆ1.26.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://wwwpreview.ibm.com/ae-en/events/think-summit/videos/#intro

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://www.ibm.com/standards/carbon/react/?path=/story/components-video-player--with-lightbox-media-viewer

### Steps to reproduce the issue (if applicable)

I just added it on my page, and it did not work as should, the issues was already on the overlay.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
Note: This issue with the lightboxmedia viewer text overlap appears to only affect the `CardGroup` component with video
