### ISSUE TITLE
[CTA Section with Content Items]: Bottom Padding is not 160px - No DDS consulting

### ISSUE THREAD

**Issue by EAVilleda** [carbon-design-system/carbon-for-ibm-dotcom#7713]
###  Engineering info:
- HC engineer: @jkaeser 
- HC Jira Ticket: https://jsw.ibm.com/browse/HC-2327
- DDS Designer: @DragosRistici 

----

### Description

The bottom spacing of the content sections that contain the CTA section component have a bottom spacing of 136px. The bottom spacing should be 160px. However, this spacing does match what is on Storybook. Can the bottom spacing be updated to have 160px? 

### Component(s) impacted

CTA Section with content items

### Browser

Chrome

### Carbon for IBM.com version

v1.26.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM (Marketing)

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/master/packages/web-components/examples/codesandbox/components/cta-section

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
There are spacing bugs related to the CTA Section layout component that was mentioned within this ticket (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7482). The engineer that's picking up this issue should account for the discrepancies mentioned in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7482 as well.
