### ISSUE TITLE
[Feature Card]: Failed e2e test | Firefox | should check that the footer's pseudo class takes up entire card to be clickable

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#7716]
**Engineering info:**  
- HC engineer: @andy-blum 
- HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2329
- DDS consulting engineer: N/A

----

### Description

This test is failing only in Firefox (React and Web Components):

![image](https://user-images.githubusercontent.com/1641214/142699289-19100e09-5516-4854-b140-acef0ede75db.png)

### Component(s) impacted

Feature Card

### Browser

Firefox

### Carbon for IBM.com version

Latest Canary

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

React and Web components Storybooks

### Package
@carbon/ibmdotcom-react, @carbon/ibmdotcom-web-components

### CodeSandbox example

https://automate.browserstack.com/dashboard/v2/builds/e5548e5f6afde78c67b3880804018e0ea2aa7c3d/cypress-tests/tests/0fbbb596772c85ba596490e639550d7005d2067aY3lwcmVzcy9pbnRlZ3JhdGlvbi9GZWF0dXJlQ2FyZC9GZWF0dXJlQ2FyZC5lMmUuanM=

### Steps to reproduce the issue (if applicable)

As far as I can tell, the Feature Card in Firefox is clickable. Might be something going on with the test in Firefox only.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
Technically this is a sev 4, but we will have failing e2e tests on browserstack until this is fixed.

**Comment by andy-blum** [comment]
Looks like firefox needs the pseudoelement string to include the colon

<img width="602" alt="Screen Shot 2021-11-23 at 9 40 47 AM" src="https://user-images.githubusercontent.com/25532785/143045135-d8334ec6-1ec4-4911-afea-bb95e622eaa8.png">
