### ISSUE TITLE
[404 page] Web Component: Develop the new 404 page

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7731]
#### User Story

> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create the `404 page` 

> so that I can:
provide the ibm.com adopters with a Carbon version of the 404 v18 user experience.

#### Additional information

- Utilize Carbon
- **See the Epic (#7674 ) for the Design and Functional specs information**
- [Design Box folder](https://ibm.ent.box.com/folder/150147427973)
- Web Components Visual QA testing issue (#7732 )

#### Acceptance criteria
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description

**Comment by kennylam** [comment]
From @oliviaflory: not top priority right now, maybe Q3. Follow up with @ljcarot on any feedback/thoughts of existing design exploration.
