### ISSUE TITLE
[Tree view] Dev of the new component absorbed from Carbon

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7734]
#### Background

Carbon's tree view component currently exist in Carbon react experimental: [Tree view](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-treeview--default) and is a very accessibility friendly navigational component. We have many use cases that could benefit from this component include IBM Docs and SDMA. We would like to build this component in Carbon for IBM.com web components, and later contribute any enhancement to Carbon react. 

Design does not have time to schedule the work to design the enhancements to the Carbon version.  We will absorb the component and make enhancements based on user feedback later.  

#### Additional information

- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic (#7196 ) for the Background information**
- This dev work is to build with only one change to the Carbon version.  The design work will be done in the future, based on feedback.
     - One change is to wrap the title to 2 lines.
- Web Components Visual QA testing issue (#7735 )

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] Update the e2e test scripts, if needed. 
- [ ] Confirm e2e test results have no major errors.
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description

**Comment by RobertaJHahn** [comment]
@emyarod I have scheduled this work for the next sprint.  Add the story points when ever you get a chance before the end of sprint 21-25.

**Comment by jeffchew** [comment]
@emyarod pulling this into pending schedule for now but noticed there isn't an estimate for this, have an idea of the effort?

**Comment by emyarod** [comment]
@jeffchew I think I would go with a 5 or maybe an 8 on this

**Comment by ljcarot** [comment]
Stilling working on it.
