### ISSUE TITLE
[Content block card static]: Card group items, not showing correctly

### ISSUE THREAD

**Issue by yosefwpp** [carbon-design-system/carbon-for-ibm-dotcom#7744]
**Engineering info:**  
- HC engineer: @proeung 
- HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2353
- DDS consulting engineer: N/A

----

### Description

Inside the `Content Block Card Static` component, the `Card group`  and the `card group item` components are being shown with some inconsistencies in the design, the borders are missing on certain sides and sometimes a background color is shown in an empty cell space. 

The problems, seems to be appearing in the `lg`, 'md' and `max` breakpoints (Trying with carbon DevTools) .

![Screen Shot 2021-11-22 at 17 58 33](https://user-images.githubusercontent.com/93942987/143070224-8e2aa83f-e05e-4d19-b264-f05b787ef4a8.png)
<img width="645" alt="Screen Shot 2021-11-22 at 18 02 21" src="https://user-images.githubusercontent.com/93942987/143070225-bd91072d-1615-4c95-ba31-ca6301e5dc2f.png">
<img width="1669" alt="Screen Shot 2021-11-22 at 18 04 27" src="https://user-images.githubusercontent.com/93942987/143070227-4e06da62-e213-4ee5-9491-ab14bc1564f5.png">

### Component(s) impacted

- Content Block Card Static (`dds-content-block-card-static`)
  - Card Group (`dds-card-group`)
     - Card Group Item (`dds-card-group-item`)

### Carbon for IBM.com version

10.45.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Adobe CMS

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

https://codesandbox.io/s/content-block-card-static-os9xn?file=/cdn.html

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
@yosefwpp This is an experitmental component which is not a high priority to fix.  Feel free to contribute a fix if you need the fix within a timeframe for the work you are doing.

**Comment by yosefwpp** [comment]
@RobertaJHahn Ok, thank you!

**Comment by proeung** [comment]
@yosefwpp I'm not about to replicate the styling issues that you've noted above in the latest release or the codeSandbox example. Can you take a look and let us know if you're still experiencing this issue?
