### ISSUE TITLE
[Masthead-Translations]: Add a JSON file data source to populate the list that Drupal Editorial Admins will choose from when assigning a WC masthead to a page

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#7760]
### The problem

- The Hybrid Cloud team is in the process of adopting the `<dds-masthead-container>` component to launch two navigational L0’s supporting the QRadar & Storage content ecosystems that are managed in Drupal and AEM (see attached).
- We're currently leveraging the existing [ibm-dotcom-translations](https://github.ibm.com/webstandards/ibm-dotcom-translations) repo as a place that houses all of the menu translations and exposes them via the JSON API endpoints, similar to the process that we've set up for the Cloud Masthead.
- While AEM eventually needs to integrate a masthead data management, we can lay the groundwork using the [ibm-dotcom-translations](https://github.ibm.com/webstandards/ibm-dotcom-translations) repo as a place to manage the data until AEM is ready.
- However, to reduce the dependency on Drupal deployment for every time a new WC Masthead is enabled per product, we'd like to create a simple JSON file data source to populate the list that Drupal Editorial Admins will choose from when assigning a WC masthead to a page.

### The solution

- Set up translation build folders for managing the single JSON file data source (see example below).
```
{
  "storage": {
    "id": "storage",
    "platform_name": "Storage",
    "url": "/storage",
    "endpoint": "/common/carbon-for-ibm-dotcom/translations/storage-masthead"
  },
  "qradar": {
    "id": "qradar",
    "platform_name": "QRadar",
    "url": "/qradar",
    "endpoint": "/common/carbon-for-ibm-dotcom/translations/qradar-masthead"
  }
}
```
- Create new Jenkins jobs to deploy this file to an endpoint hosted via the `https://1.www.s81c.com` environment.

### Application/website

Drupal

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### What time frame would this ideally be needed by (if applicable)

The timeframe of this work has not been determined yet. We just like to put this request on the board and figure out whether this work is feasible from a translation and management perspective. 

We understand that AEM is developing a data storage/store for the Masthead and Footer content and this configuration might not be needed there, however, this is a good workaround if the business would like to continue to roll out WC Masthead within Drupal.

cc. @kjwhitla

### Examples

Screenshot of the Masthead settings within Drupal Editorial control.

![Screen Shot 2021-11-23 at 5 25 05 PM](https://user-images.githubusercontent.com/1815714/143271589-db64a4d6-9f9d-4e8c-9d67-f5b993ee98e4.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
This is a short term solution, bicycle.  The team has to spend time working on the Long Term solution (car).  The Long Term solution is to have AEM to be the source of managing the MH data.  In the meantime the team will move forward with creating the single JSON file that lists out all of the available MH's that Drupal can fetch and make available in the Editorial settings.

**Comment by proeung** [comment]
@jeffchew Any preference to where you would like this JSON file to live within the [ibm-dotcom-translations](https://github.ibm.com/webstandards/ibm-dotcom-translations) repo? Should I create a new folder within the `/translations` directory and call it `/configs` (eg. `/translations/configs/configs.json`) or just add this file in the root directory of `/translations` (eg. `translations/configs.json`)? Let me know what you think.

**Comment by proeung** [comment]
I just spoke to our team and it looks like we don’t need to set up this endpoint anymore. We have a solution on the Drupal management side that addresses our performance concerns. @hawkeyetwolf will leave a comment regarding our findings in this issue. In the meantime, we can go ahead and close out this request.

cc: @kjwhitla

**Comment by hawkeyetwolf** [comment]
We realized that the blocking PHP request to retrieve this JSON file would happen on each uncached page, so it's better we keep the data stored in Drupal for now.
