### ISSUE TITLE
[Website] Add "Contributing" section to Figma page

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#7793]
The Figma page needs instructions on how a designer can contribute a component to the libraries. Need to detail:

* Creating a branch from a library page
* Adding or creating a new component
* Submitting the component for review/handoff

Also, add instructions on accessing documentation links from Figma components.

**Comment by oliviaflory** [comment]
Still want to do this, will wait until after the first library is out
