### ISSUE TITLE
[Masthead]: Only one item should be underlined - DDS Consulting 

### ISSUE THREAD

**Issue by EAVilleda** [carbon-design-system/carbon-for-ibm-dotcom#7794]
**Engineering info:**  
- HC engineer: @jkaeser 
- HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2339
- DDS consulting engineer: @annawen1 - @huntermacd 

----

### Description

On the live site, we have issues where two items are underlined in the masthead. Example: https://www.ibm.com/topics/supply-chain-management
![image](https://user-images.githubusercontent.com/47429622/144280069-4c52cb71-f765-4066-8c05-f6b81d54bb7a.png)

Anna Wen explained that a new feature was implemented to detect the selected/active menu item based on the url. This is why "Learn" is underlined, but “Supply Chain” should not be underlined in this case.

### Component(s) impacted

Masthead https://www.ibm.com/standards/carbon/web-components/?path=/story/components-masthead--default

### Carbon for IBM.com version

v1.26.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM (Marketing)

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

No codesandbox avaiable

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
This bug issue is related to the work that went into this EPIC (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6638) & https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6763.

**Comment by proeung** [comment]
The highlighting style on the platform name (eg. `Supply Chain`) within the L1 nav component is set by default. We'll need to adjust the logic for selecting the current nav item so that the platform name doesn’t get highlighted as well.

**Comment by proeung** [comment]
@RobertaJHahn @jeffchew I'm adding Anna as the consulting engineer for this issue as she worked on #6763.
