### ISSUE TITLE
[CTA section] Link list for video should display video time

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#7797]
There's a discrepancy between the Web components and React versions of the `link-list`. The Web Components version should be following the React version where the time on a video link item would display in the link copy (even if it appears at the end of a section), but it looks like the time is not displaying properly.

**React version:**
![Screen Shot 2021-12-01 at 3.31.35 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/adee166e-aada-4d19-8248-a5e6c6f8c6e1)

**Web components version:**
![Screen Shot 2021-12-01 at 3.31.15 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/1fed329b-9abd-4003-bace-0c0bc7e55700)

**Comment by proeung** [comment]
AEM JIRA ticket - https://jsw.ibm.com/browse/ADCMS-1953

**Comment by proeung** [comment]
@RichKummer Looking at the current `canary` deploy preview for the Web Component package, the video duration seems to be rendering just fine now (see attached and https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/?path=/story/components-link-list--default).

![Screen Shot 2022-02-08 at 11 21 11 AM](https://user-images.githubusercontent.com/1815714/153030892-cfcf6c3b-4b85-4cb0-a50b-054e9773b981.png)

Can you confirm that you're seeing the same thing? If so, I think we can safely close out this issue.
