### ISSUE TITLE
[Content section]: aligning children to content-section heading

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#7804]
### Description

Expected children items to align correctly with the `content-section-heading`
<img width="1140" alt="Screen Shot 2021-12-02 at 9 11 42 AM" src="https://user-images.githubusercontent.com/20210594/144470306-8a1cbda5-4dc8-40f4-aa1d-a4f494318960.png">

### Component(s) impacted

Content Section with children (content block, content item, content group) need all to align to top properly when using `content-section`

### Browser

Chrome

### Carbon for IBM.com version

v1.12.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Carbon for IBM.com WC Tutorial and broken in storybook

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-tutorial/tree/web-components-step-3

### Steps to reproduce the issue (if applicable)

go to https://carbon-design-system.github.io/carbon-for-ibm-dotcom-tutorial/step-3/ to see issue. Code can be found here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-tutorial/tree/web-components-step-3. Also in storybook here: http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-content-section--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@ariellalgilmore Can this not be achieved with CSS?
