### ISSUE TITLE
[CTA]: allow for custom video thumbnail in cta

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#7805]
### The problem

Currently `card-cta` only has the option to customize title, description, and remove poster image. I would like to customize the thumbnail image as well. 

### The solution

optional customize thumbnail for card-cta. this then should be usable for card-in-card with video

### Application/website

carbon-for-ibm-dotcom-tutorial

### Business priority

Medium Priority = upcoming release but is not pressing

### Examples

Working on the the tutorial and this is necessary for the design spec for Card-in-card with video. 
https://ibm.ent.box.com/file/881441415343

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
Convert to an epic,  design decision needed.  If yes, func specs changes needed, WC dev, React Wrapper, Vis QA & Prod QA.

Does design want to open the API to provide this capability and include in the tutorial?  This issue may not be needed if the work in issue #7660 covers it.  @DragosRistici Do you want to discuss in a post-scrum topic.

**Comment by photodow** [comment]
This appears to be a bug according to the functional specs. `false` should allow for no image, but it should also allow for a user to define this prop.

![image](https://user-images.githubusercontent.com/3793636/145855345-680eaba3-5f45-4646-bfe2-02a45c646f3e.png)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/CTA#23-card

**Comment by jeffchew** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Carbon-for-IBMcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/7805?planning-poker) with ZenHub @annawen1
