### ISSUE TITLE
[cta | feature]: Card is not fully-clickable in mobile 

### ISSUE THREAD

**Issue by andy-blum** [carbon-design-system/carbon-for-ibm-dotcom#7806]
###  Engineering info:
- HC engineer: @andy-blum 
- HC Jira Ticket: https://jsw.ibm.com/browse/HC-2347
- DDS consulting engineer: N/A

----

### Description

The feature variant of the CTA component is not fully-clickable across all browser sizes. In the web components package, the vertical layout (<672px wide) does not extend the clickable area over the image. In the react package, below the 400px breakpoint the image isn't part of the interactive space.

<img width="554" alt="Screen Shot 2021-12-02 at 2 13 40 PM" src="https://user-images.githubusercontent.com/25532785/144489357-a5916e1f-e6c9-407d-9574-0a046df3fe5c.png">

<img width="462" alt="Screen Shot 2021-12-02 at 2 13 51 PM" src="https://user-images.githubusercontent.com/25532785/144489379-cd94b822-85e2-48a8-b979-8b2a5a62f8e4.png">

<img width="394" alt="screen_shot_2021-12-02_at_2 20 39_pm" src="https://user-images.githubusercontent.com/25532785/144489390-14d96a66-00ea-49b3-be90-682423f70064.png">

### Component(s) impacted

[React](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-cta--feature)
[Web Components](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-cta--feature)

### Browser

Chrome

### Carbon for IBM.com version

latest

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

carbon-for-ibmdotcom

### Package

@carbon/ibmdotcom-react, @carbon/ibmdotcom-web-components

### CodeSandbox example

see canary links above

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@jeffchew I'm going to move this issue to our HC dev queue as it's currently causing the mobile test errors that @andy-blum mentioned here (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7827#issuecomment-988972343).
