### ISSUE TITLE
[CTA block/section with content items] resolve discrepancy on horizontal rule 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7814]
The light $ui-03 horizontal rule is present above the first set of content items in this design (item number 5 in the spec):

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/cef37cd0-8d9d-4a12-82b6-f3aa45707c8c)

But absent in 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/5fd44a1b-5eae-4937-820f-3830637953d2)

This design here, when no Block level body copy, might be the reason why the rule is removed: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/0d5d165c-83b3-4d59-a406-19f1608a910c)

### Task

1. Decide if this horizontal rule is needed. If needed, is it optional? 
2. Update design & func spec according to decision

**Comment by shixiedesign** [comment]
@DragosRistici conducted a thorough exploration and here's the conclusion: 

> So, designers, looking at this from more angles, it seems to me that we can drop the horizontal rule above the first row of Content items if we keep a bigger spacing - 64px. Mobile goes similar, with one exception (in my opinion): when there’s only a heading + Content items, you keep the 32px spacing before the first Content item (content items are only stacked one by one, so no  white space variations between the near items). If there’s more than the heading (at least the subheading or the short copy is present), the 64px should apply. You can see the other explorations and the comparison with the rule present in the sketch file attached in the first comment (i got a limit of 10 files here). Let me know what you think. 

Here's the exploration file: 
[https://app.zenhub.com/files/193129061/79fe30dd-6c0f-4d1a-ad88-feb85c8e1b63/download](https://app.zenhub.com/files/193129061/79fe30dd-6c0f-4d1a-ad88-feb85c8e1b63/download)

Only need to update the design spec of CTA block or section then we can close this @DragosRistici Thank you!

**Comment by DragosRistici** [comment]
Visual specs are [uploaded in the Box folder here](https://ibm.box.com/s/96hzuj9ippwe5ly2ypmsdcytwqbck7q0).
