### ISSUE TITLE
[Tabs & Tabs extended with media]: Not on grid

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7815]
**Engineering info:**  
- Innovation Team engineer: @mwanberg 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2387
- DPO consulting engineer: N/A

-----

### Description

1. Tabs extended media: Contents of the component are not aligned to Carbon grid. 

**Current Canary web components**
![image](https://user-images.githubusercontent.com/15144993/144798385-d6124585-b78e-41e9-bffd-59e5fb3c9ca7.png)

**Expecting**
![image](https://user-images.githubusercontent.com/15144993/144798590-8d961cc2-1831-4fbf-a085-4e13a63182d4.png)

2. For Tabs extended, the individual tabs should be 2 columns wide. 

**Current:** 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/52368160-9d5e-49cf-bd6d-0c490eb83840)

**Expecting:**
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/6d77531e-9c89-455f-a572-634aaf66ed0b)

### Component(s) impacted

Tabs extended
Tabs extended with media

### Browser

Chrome

### Carbon for IBM.com version

canary

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

NA

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

NA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
Design specs - https://ibm.ent.box.com/folder/133803243554?s=3sun8lo3gu2b4uaa4oxgpxrqit1m7t6i
