### ISSUE TITLE
[Tabs extended] Add animation to make "Tabs expressive"

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7816]
### Description

Original intent of Tabs extended is that it should actually _extend_ Carbon tabs. However during development, it turned out to be tricky and Ian had to rebuild tabs from scratch. 

So given now the tabs are detached from Carbon tabs, we should lean into the "expressive" direction, and make these proper "expressive tabs" by adding animation, and rename to `Tabs expressive`. 

**Horizontal tabs animation**
![Dec-06-2021 02-48-34.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/02b1e401-8d1b-4f1a-a91c-f2c52925992e)

**Vertical tabs animation**
![Dec-06-2021 02-47-50.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/3e428030-33c2-4865-bdbc-8c8f87e5870e)

**Comment by RobertaJHahn** [comment]
Convert to an epic, Design exploration, design spic, func spec, WC dev, React Wrapper, Vis & Prod QA, website
