### ISSUE TITLE
Continue Masthead functional spec clean up and migrate to wiki:  follow-on to issue 7613

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#7829]
#### Overview
Currently, masthead functional spec is here https://ibm.ent.box.com/folder/126271959517 and it doesn't follow the latest functional spec template. 

The word document is due for a big clean up, and we should migrate to the expected wiki location: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Masthead

#### Additional Information
- follow-on to issue #7613

**Comment by ljcarot** [comment]
@photodow Checking in on status of this work.  Thanks!
