### ISSUE TITLE
Update Image Caption to be Optional

### ISSUE THREAD

**Issue by ted-steinkamp-ibm** [carbon-design-system/carbon-for-ibm-dotcom#7836]
### Description

**Request:**
As an author, I want the ability to enter or leave a caption blank without promoting a default caption so that site visitors do not see the defaults caption.

**Additional context:**
Site visitors are currently seeing a default caption on pages that have been published. These pages that are in production need to be updated without requiring a republish or re-authoring.

**Examples**
- Updated caption: https://www.ibm.com/topics/healthcare-technology
- Default caption: https://www.ibm.com/topics/smart-contracts 

### Component(s) impacted

Images

### Browser

Chrome

### Carbon for IBM.com version

unclear

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

unsure

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by shixiedesign** [comment]
Follow through work: 
- [x] Functional spec update: not needed. Current spec is correct https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Image-with-caption
- [x] Website update https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1390
