### ISSUE TITLE
ContentSection not exported from @carbon/ibmdotcom-react

### ISSUE THREAD

**Issue by JOwens818** [carbon-design-system/carbon-for-ibm-dotcom#7838]
### Description

Importing ContentSection is giving the following error message:

Attempted import error: 'ContentSection' is not exported from '@carbon/ibmdotcom-react'.

Currently using @carbon/ibmdotcom-react": "^1.27.0"

Possible cause: The export may be missing from https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/a80379a0d39cafa3c0376952151cab0bd9c7e276/packages/react/src/components/index.js

### Component(s) impacted

ContentSection

### Browser

Firefox

### Carbon for IBM.com version

v1.27.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

TMF

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://www.ibm.com/standards/carbon/react/?path=/story/components-content-section--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
Hi @JOwens818 !

As noted in slack, a workaround would be to import the es module directly:

```import ContentSection from '@carbon/ibmdotcom-react/es/components/ContentSection/ContentSection';```

This would also be better for your bundler so it won't do as much guess work in the tree shaking side.
