### ISSUE TITLE
[Test Scenario]: Content item - DDS Consulting

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#7842]
**Engineering info:**  
- HC engineer: @jkaeser 
- HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2350
- DDS consulting engineer: @ariellalgilmore 

----

### Component and test scenario title

Content item

### Test scenario steps

a. Verify Heading, copy and CTA link is loaded 
b. Verify CTA link must be clickable 
c. Change 'Media type' on knobs, verify image and video types
d. Change 'copy' checkbox on knobs, verify the text gets hidden.
e. Change 'CTA style' to button, verify the button is operable.

**Comment by ariellalgilmore** [comment]
Bringing this back to sprint 1 since we will be able to get this merged in
