### ISSUE TITLE
[Masthead-Translation-Services]: Enable a locale fetching method that falls back to its master language translations

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#7850]
### The problem

- We're currently using the [ibm-dotcom-translations](https://github.ibm.com/webstandards/ibm-dotcom-translations) repo as a place that houses all of the menu content translations for Cloud, QRadar, and Storage masthead.
- Currently, we're defining `.json` files for all of the supported locales using the `cc-lg.json` format and it's been working great, however, it can be a bit cumbersome when we're managing 50+ locales, and often times those translations are the same as the master with the exception of the locales URL pattern.
- We'd like to enable a fetching method that grabs the master language file in the event where the locale doesn't exist within the [ibm-dotcom-translations](https://github.ibm.com/webstandards/ibm-dotcom-translations) repo as a fallback.
- This continues to be an issue in the JSON management workflow until we have the Masthead + Footer data store setup in AEM. This issue acts as a place for us to track the locale fallback logic discussion that will serve the AEM adoption as well.
- @kjwhitla Can you add the business requirements for this request?

### The solution

- No solution at the moment, but would like to get a sense of what the team thinks.
- Each menu URL might be a factor and one that we'll need to discuss further.

### Application/website

Drupal, AEM

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### What time frame would this ideally be needed by (if applicable)

The timeframe of this work has not been determined yet. We just like to put this request on the board and figure out the solution and resourcing at a later time.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
Convert to an epic.  Requires strategic planning and discussion between Putra's team and DDS engineers.  The work will be done next year. 

ACTIONS;  1)  Issue needed for Dev research.  2)  A meeting scheduled in 1Q 2022 is needed.

**Comment by andy-blum** [comment]
This issue is no longer needed as translation sources are being moved to AEM experience fragments.
