### ISSUE TITLE
[PR Reviews]: Ari - 25

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#7926]
### Pull request(s) reviewed

- fix(masthead): align react and wc mobile menu styles #7925
- test(link-with-icon): add e2e tests #7915
- docs(card): update card-group, card-in-card, and image readmes #7912
- fix(a11y-checker): fix file-loader for karma a11y checker in React #7868
- chore(react): export missing Content* components #7839
- fix(image-with-caption): revert caption requirement #7834
- chore(card): update wrapper story and docs with card logo #7786
- fix(cta-card): add knob and docs to allow poster to be turned off #7784

**Comment by jeffchew** [comment]
Hey @ariellalgilmore can you provide an estimate?
