### ISSUE TITLE
[Card in Card]: Clicking smaller card with a new tab link opens twice within Firefox

### ISSUE THREAD

**Issue by EAVilleda** [carbon-design-system/carbon-for-ibm-dotcom#7941]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2369
- DPO consulting engineer: N/A

----

### Description

When the link is set with target="_blank", clicking on the small card within the bigger card will open the new tab twice.

![image](https://user-images.githubusercontent.com/47429622/148430921-d6356a28-8872-4752-b5b4-c76f56574ed9.png)

### Component(s) impacted

Card Group with Card in Card
Card in Card

### Browser

Chrome

### Carbon for IBM.com version

v1.29.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM (Marketing)

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

No codesandbox avaiable

### Steps to reproduce the issue (if applicable)

https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-card-in-card--default
Set the target="_blank" on dds-card-in-card tag.
Click on the smaller card within the bigger card.
Two new tabs open. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
Hi @EAVilleda , we followed the steps and couldn't reproduce the issue. Are there additional details you can provide to reproduce the issue?

**Comment by proeung** [comment]
@EAVilleda The Card in Card component extends the `DDSCardCTA` component (see - https://www.ibm.com/standards/carbon/web-components/?path=/story/components-cta--card), therefore the external/new tab behavior should be the same as what you're seeing within the CTA Card preview.

Are you manually adding the `target="_blank"` within the shadow DOM, if so I wonder if that causes the link to open twice? Let us know if there's something that we're missing here.

**Comment by proeung** [comment]
@EAVilleda Thanks for getting back to me! Both @ariellalgilmore and I looked into the snippet that you've provided and we noticed that you have the `target` attribute added in both the `<dds-card-in-card>` and `<dds-card-cta-footer>` components. We recommend that you remove this attribute as setting `cta-type="external"` will add the `target="_blank"` attribute to the shadow DOM of the card CTA.

Removing the `target` attribute from your HTL template should prevent the new tab from opening twice. This is the same method that we have on card components outside of `Card in Card`.

**Comment by EAVilleda** [comment]
@proeung I removed the target attribute, but it did not resolve the issue. The external page opened twice if I click on the smaller card. Also, without the target attribute, I am unable to make an internal page open in a new tab. 

I copied the markup from the code sandbox to my page for testing, but it still opens two new tabs.

**Comment by proeung** [comment]
@EAVilleda Can you share the link to the test page you're seeing this issue on so that we can better debug this issue?

**Comment by proeung** [comment]
Actually, I just tested this on Firefox and I'm able to replicate the bug that you're describing. Looks like an odd issue limited to FF.

**Comment by EAVilleda** [comment]
@proeung Just in case you still want to check, I have a page published in Dev with the component: https://dev-publish.np-roks.cms.cis.ibm.net/article-page-test
And I've been testing in Chrome browser.
