### ISSUE TITLE
[Tabs Extended - Default] Accordion icons are not loading for the Mobile view.

### ISSUE THREAD

**Issue by Monika-Jayanna** [carbon-design-system/carbon-for-ibm-dotcom#7944]
### Description

I am using the following design in our application
https://www.ibm.com/standards/carbon/web-components/react/?path=/docs/components-tabs-extended--default
and its working fine in local but when we move the code to development server the accordions icons are missing only for mobile version it says like [object object]

<img width="596" alt="image" src="https://user-images.githubusercontent.com/97293722/148548776-8e24028e-3ed1-406a-ae68-d9ddd4c1ee33.png">

and I am using same packages which is there in sandbox link, still its not working so please check this issue

### Component(s) impacted

`DDSTabsExtended`

These are the dependencies which I am using
```
"dependencies": {
    "@carbon/colors": "^10.30.0",
    "@carbon/ibmdotcom-react": "^1.21.0",
    "@carbon/ibmdotcom-styles": "^1.21.0",
    "@carbon/ibmdotcom-web-components": "latest",
    "@carbon/icons-react": "~10.22.0",
    "@carbon/layout": "^10.29.0",
    "@carbon/pictograms-react": "^11.15.0",
    "@carbon/type": "^10.33.0",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "carbon-components": "^10.23.0",
    "carbon-components-react": "7.32.1",
    "carbon-icons": "^7.0.7",
    "downshift": "^6.1.7",
    "node-sass": "^6.0.1",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.2.1",
    "react-scripts": "4.0.3",
    "redux": "^4.1.2",
    "web-vitals": "^1.1.2"
  },
```

### Browser

Chrome

### Carbon for IBM.com version

1.21.0

### Severity

Severity 1 = The design is broken in a critical way for the mobile view, So this is blocking us from going live, we wanted to release this feature ASAP.

### Application/website

https://www.ibm.com/privacy/portal/us-en

### Package

@carbon/ibmdotcom-react, @carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/master/packages/web-components/examples/codesandbox/components-react/tabs-extended

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
Adding a comment here for reference; this issue is in reference to the React Wrapper of the `tabs-extended` component. The Privacy team is using a Create React App which I've tried implementing the component in a basic CRA, building and deploying but am not able to replicate the bug.

We've suggested a change in the dependencies and also running `yarn-deduplicate` to update the `yarn.lock` file.

**Comment by annawen1** [comment]
I ran the `build:development` script on the project and served the files on a static server but still not able to see the issue
<img width="1248" alt="Screen Shot 2022-01-07 at 11 09 23 AM" src="https://user-images.githubusercontent.com/54281166/148572112-83f08a3c-c633-4b05-9595-84cdbaf8fb6d.png">

**Comment by jeffchew** [comment]
Hi @Monika-Jayanna ,

We couldn't reproduce this locally so might be an application level configuration. If you can, would you be able to join our next office hours so we can live troubleshoot with you?

**Comment by Monika-Jayanna** [comment]
@jeffchew Sure, I will recheck with deployment team once.
