### ISSUE TITLE
[a11y]: "listitem" is not contained in or owned by an element with one of the following roles: "directory, list"

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#8010]
**Engineering info:**  
- Innovation Team engineer: @jkaeser 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2384
- DPO consulting engineer: N/A

-----

### Description

When running `yarn test:a11y` multiple stories are recieving an example of the following "listitem" error: 

<img width="899" alt="Screen Shot 2022-01-12 at 12 16 48 PM" src="https://user-images.githubusercontent.com/20210594/149215151-0e107ae4-a667-47eb-91bd-888f29f8606b.png">

Example output of all accessibility errors:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/runs/4779749308?check_suite_focus=true#step:7:2065

### Component(s) impacted

-  Card section images
     -  `<dds-card-section-images>`
- Card section simple, | with CTA
     -  `<dds-card-section-simple>`
- Content section
     -  `<dds-content-section>`
- CTA block | withContentItems
     -  `<dds-cta-block-item-row>`
- CTA section | simple,  | withLinkList
     -  `<dds-cta-section>`
- Dotcom shell (all)
     -  `<dds-cta-block-item-row>`
- Link list section 
     -  `<dds-link-list-section>`

### Carbon for IBM.com version

canary

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Carbon for IBM.com web components

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/runs/4779749308?check_suite_focus=true#step:7:2065

### Steps to reproduce the issue (if applicable)

View the actions tab and look under `Run a11y compliance tests` for web components

To run locally go to `packages/web-components` and `yarn test:a11y`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by hongyuxgt** [comment]
I also found the same issue in dds-masthead-container component. would you please help to check?
![image](https://user-images.githubusercontent.com/23979517/150465125-c368f175-c2b8-4820-b0ef-bd5a6edf3d46.png)
# Component(s) impacted
<dds-top-nav-item>
<dds-legal-nav-item>
