### ISSUE TITLE
[Figma kit] Update interactive elements for prototypes

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8024]
The Figma kit currently has the hover styles for components baked into the component as variants, but these are not connected to the Prototyping portion of Figma. 

We need to link these styles so that adopters can more easily show interactive prototypes. Need updates to these components as of 01/13/22 (there may be more depending on when this is picked up):

- [x] Button
- [x] Text link
- [x] Card link
- [ ] CTA Text
- [x] Feature card
- [ ] Link list
- [ ] Masthead (?)

Should be added across all four libraries. Should at least be for `hover`, potentially for `active`

![Screen Shot 2022-01-13 at 1.31.52 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/171007a8-a3c5-4187-9978-46759d10524b)

**Comment by oliviaflory** [comment]
Pausing work until we meet with Juan to learn about bases and how the Carbon kit was built

**Comment by oliviaflory** [comment]
Iceboxing for now due to change in kit creation strategy / best practices. Will revisit after refactor is completed. 

Interactive states may be addressed in re-build issues
