### ISSUE TITLE
[Figma kit] Working area clean-up

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8029]
We've been able to get components out to adopters, but now we need to clean up some of the mess in the Figma library files. Currently, a lot of components and variants are floating on the design kit working area. 

We should consider more backgrounds and labels to better organize the components that are already built. Should be done across all libraries.

- [x] white
- [ ] g10
- [ ] g90
- [ ] g100

**Carbon kit for reference:**
![Screen Shot 2022-01-13 at 1.38.38 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/fd900010-c29d-4728-8a09-9deea661c269)

**Comment by oliviaflory** [comment]
Clean up completed for white theme. Closing w/o completing other themes due to change in kit creation strategy
