### ISSUE TITLE
[Cloud-Masthead]: add services endpoint to determine auth status for Cloud Console - DPO Consulting

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#8033]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2377
- DPO consulting engineer: @annawen1 

-----

### The problem

- It was brought to our attention that the Cloud console team has completed a feature to detect and personalize based on if a person was authenticated/logged-on on via the `cloud.ibm.com` console.
- This detection method was based on a request to personalize `/cloud` pages with users' live login state, which can now be accomplished.
- @kjwhitla Can you let me know if this is correct from a business requirement perspective?

### The solution

Steps to verify the personalization functionality:

- Goto an IBM.com marketing page, like https://ibm.com/cloud
- Open the developer console
- type `_dl.ddo.user.segment.isCloudLoggedOn` (previously made a typo and omitted the _ in this command)
- The console output should read `true` or `false`
- Either log in or log out of `cloud.ibm.com` (change your state)
- Reload the https://ibm.com/cloud page
- Repeat step 3 and see the status updated

We’ll need to adjust our `CloudAccountAuth` script within the Services package of the Carbon for ibm.com.

### Application/website

AEM, Drupal

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

The timeframe of this work has not been determined yet.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
Reopening this ticket as the solution added to this PR doesn't seem to be working on PROD. https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8149

PR to revert the changes - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8792

**Comment by proeung** [comment]
@annawen1 Just wanted to revisit this issue. Do you have any recommendations on how to best test this change (see above).

**Comment by annawen1** [comment]
@proeung Yeah, it seems so far the only way to test if it really works or not is to test in a Drupal environment. We might have to try pushing changes to canary for Drupal test pages to consume.

**Comment by proeung** [comment]
@annawen1 We can certainly try that, however, ideally, I'd like to get these changes tested before the PR is merged down so that we don't have to create follow-up PRs to address any issues that might pop up. I wonder if there's a way to generate a CDN reference per PR with some sort of GH label. This obviously will be a new Jenkins job I would assume.
