### ISSUE TITLE
[Cloud Masthead]: Mobile menu items are not rendering

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#8082]
### Description

The Cloud masthead mobile menu is not rendering.

<img width="685" alt="Screen Shot 2022-01-19 at 4 28 32 PM" src="https://user-images.githubusercontent.com/54281166/150216706-31b90a75-bf9a-4c0d-a303-1467ec023b7c.png">

### Component(s) impacted

Cloud masthead

### Browser

Safari

### Carbon for IBM.com version

1.30.0-rc.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

https://www.ibm.com/cloud

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@annawen1 Thanks for opening this issue!

@jeffchew @ljcarot This is a serv 1 bug that's affecting all production pages that are currently referencing the `next` CDN build URL. Is it possible to patch up to the `1.30.0-rc.0` or roll the release back? Please let me know as this is affecting users from accessing the Cloud mobile menu.

I'm not sure why this is happening on the Cloud Masthead, but not the Global version.

**Comment by jeffchew** [comment]
Hey @proeung ,

We decided to publish `latest` version on the `next` tag to remedy this for now, but I highly suggest that Drupal changes target to use the `latest` tag instead.

We are currently in the middle of publishing and it may take a few moments (or more) for akamai to pick up all the changes globally.

We will announce in the slack support channel that the `next` tag for this regression cycle will be unavailable, but the specific versions should still be available for testing.

cc: @ljcarot

**Comment by proeung** [comment]
@jeffchew Wonderful! Thank you for addressing this so promptly! 

I believe the usage of the `next` tag was during the launch time period for quickly verifying fixes, but I don't think we made the steps to switch back to `latest`. With that being said, I'll make sure that we're using the `latest` tag in our next Drupal deployment.

**Comment by proeung** [comment]
@jeffchew @annawen1 FYI. We changed the CDN reference from `next` to the `latest` tag in the recent Drupal deployment 01/25. https://jsw.ibm.com/browse/HC-2370
