### ISSUE TITLE
[Locale Modal]: Focus isn't trapped within modal

### ISSUE THREAD

**Issue by IgnacioBecerra** [carbon-design-system/carbon-for-ibm-dotcom#8086]
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2371
- DPO consulting engineer:

----

### Description

Using tab navigation and VoiceOver, once the focus moves out of the last card going forward, the next focused item is the browser tabs themselves. Going backward results in the focus moving out of the close button for the modal will result it focusing on any background elements (such the links in the footer).

https://user-images.githubusercontent.com/24970122/150236949-80eceb74-1eff-4f98-8293-b811a261270e.mov

 

### Component(s) impacted

Footer
Locale Modal

### Browser

Chrome

### Carbon for IBM.com version

1.30.0-rc.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

N/A

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
Tested this in mobile (iPhone 12 device), safari with VoiceOver in the latest release candidate (1.30.0-rc.1) and the focus isn't trapped in mobile.

https://user-images.githubusercontent.com/54281166/150870389-0e73f33a-66dc-4045-9021-2c20f3c6b98e.mov

**Comment by andy-blum** [comment]
See my last 2 comments on #8074

**Comment by annawen1** [comment]
Closing this ticket as a fix has been applied to desktop. Another ticket has been opened for focus trapping in mobile: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8146
