### ISSUE TITLE
[Content block media]: React single paragraph is read out as separate text items

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#8091]
### Description

In Content block media the intro paragraph is read out as separate paragraphs, even splitting one sentence in two, which may be confusing for users. Torn between a Sev 2 and 3

![content-block-media--Jan-20-2022 14-03-39](https://user-images.githubusercontent.com/45692622/150405072-d396fa2a-4f65-41c5-b113-b3b26e8c18b1.gif)

~This is specific to if a user to using the arrow keys to navigate content, it does not happen when you allow the screen reader to navigate/read out on its own.~

_This does not occur in Production_

### Component(s) impacted

Content block media

Also saw this in Call out media

### Browser

Chrome

### Carbon for IBM.com version

1.30.0 rc 0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Carbon for iBM.COM

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-content-block-media--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
@jeffchew and @ljcarot I think we could close this issue. It might be an odd fluke in line breaks with italicized content that I could reproduce at a very specific breakpoint, but does not happen at every breakpoint. I uploaded two new recordings (were you can hear the VO) as an example:


I tested this again a few times in the Content block media story and the NextJS template. I think there is only a specific breakpoint (~1280px), where the italicized word is the last word on the line and somehow causes an odd reading in the VO. 

https://user-images.githubusercontent.com/45692622/151056420-c1d2b5fd-1e1b-4f13-95bf-9dc9166b3f56.mov


It reads out consecutively, in a single paragraph at a wider breakpoint.

https://user-images.githubusercontent.com/45692622/151056445-5dc58029-2894-4fca-a6da-6948a315608c.mov

**Comment by ljcarot** [comment]
Okay, we can close.  Thanks for double checking.
