### ISSUE TITLE
[DotcomShell]: Web Components - Language Only footer doesn't change page locale in storybook

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#8092]
### Description

The DotcomShell stories using the language only footer doesn't change the page locale when a locale is selected. When selecting a locale with the default footer, the page's locale does get updated. We should have the same for language only as well.

This is happening on Safari, iPhone 12.

![Jan-20-2022 14-12-42](https://user-images.githubusercontent.com/54281166/150406428-b08d7aeb-df8d-4910-8cdf-9ead59ab26cf.gif)

### Component(s) impacted

DotcomShell

### Browser

Safari

### Carbon for IBM.com version

1.30.0-rc.0

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

https://www.ibm.com/standards/carbon/react/?path=/story/components-dotcom-shell--default-language-only

### Package

@carbon/ibmdotcom-react

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
There is no way to map the custom language only configuration to the standardized language/locale selection. Closing this.
