### ISSUE TITLE
[Locale modal]: React – Europe disabled, missing European country alt links

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#8094]
### Description

The Locale modal and locale modal within the Footer stories have disabled Europe button.

<img width="1325" alt="Screen Shot 2022-01-20 at 4 47 37 PM" src="https://user-images.githubusercontent.com/45692622/150427901-355c931f-6f2f-465e-b904-28437f34d43d.png">

From Anna:
the locale modal generates the locales based on the alternate links provided in the page `head`
not seeing the european locale alternate links in the staging storybook page

<img width="1066" alt="Screen Shot 2022-01-20 at 4 44 50 PM" src="https://user-images.githubusercontent.com/45692622/150427872-04baf872-e0eb-4280-93b1-44c24f6f6428.png">

_This does not exist in Production_

### Component(s) impacted

Footer 
Locale modal

### Browser

Chrome

### Carbon for IBM.com version

1.30.0

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

Carbon for IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-locale-modal--default and  https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-footer--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
@oliviaflory This actually isn't a bug, we disabled it on purpose so we can visually and functionally test a disabled state for a region.
