### ISSUE TITLE
[card-pictogram]: screen reader output

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#8101]
### Summary

On desktop when reading card-pictogram with VO. Tabbing will read just the heading text and then using down arrow key will read the copy, but when using left and right arrow keys it still will not read the copy.

On mobile with VO the heading and copy are all read at once. 

Also, not seeing it read the pictogram label at all.

Browserstack screenreader only reads both heading and copy.

Wondering what info a user using VO should recieve from card-pictogram since it's slightly different from our other cards? 

### Relevant information

Previously, Ram has complained about cards being over verbose when reading heading and copy all at once

### Name and organization

Carbon for IBM.com

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment]
Ask Michael Gower from A11y team for help with this one.

**Comment by oliviaflory** [comment]
Met with a11y guild on May 5, 2022:

notes from guild:
- Pictogram card shows a title, and then when hovered will expose more text/content
- VO on mobile reads the title and the extra copy/content - Test has complained that is overly verbose
- Reads as expected on desktop (heading - then arrow for more content
VO itself behaves differently (with "containers") on mobile vs desktop - so this is not a surprising interaction/response

Things to consider: 
- what is the pictogram providing?
- how do we convey that they card should be hovered
- and then if there is no pictogram at all then we wouldn’t have the hover interaction
- also mobile completely remove the hover interaction and shows all info
