### ISSUE TITLE
[Table of Contents]: Web Components & React - VO - focus doesn't stay with selected section, user has to swiped through all content - DPO Consulting

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#8107]
**Engineering info:**  
- Innovation Team engineer: @mwanberg 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2380
- DPO consulting engineer: @kennylam 

-----

### Description

When utilizing the Table of Contents with VoiceOver in Safari and Chrome (Mobile & Desktop), user selects a section to jump to from the TOC selector. 

**Mobile**
Expected behavior: User jumps to selected section and can interact with the selected section's content
Current behavior: User jumps to selected section visually, but the focus goes to the top of the page and user has to navigate from the top of the page.

Mobile: Safari - iPhone 12 - Web Components Test App 
https://user-images.githubusercontent.com/54281166/150600903-1f063f5a-dc5b-4fe2-a87f-3040431dad3f.mov

**Desktop**
Expected behavior: User jumps to selected section and can interact with the selected section's content
Current behavior: VO tells user to press Control+Option+Space to access "group" when on TOC selector, doing so user is not able to access any content.

Desktop: Chrome - DotcomShell default React story
https://user-images.githubusercontent.com/54281166/150601086-82ad9bcc-ad2d-41af-a21c-0cba64d0a175.mov

### Component(s) impacted

Table of Contents

### Browser

Safari & Chrome

### Carbon for IBM.com version

1.30.0-rc.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/
https://ibmdotcom-nextjs-staging.mybluemix.net/

### Package

@carbon/ibmdotcom-web-components
@carbon/ibmdotcom-react

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@ljcarot I'm moving this issue up to `Sprint: 04` as I don't think we'll be able to get a PR up and reviewed/approved in time for the 2/11 code freeze.
