### ISSUE TITLE
[Locale Modal]: In mobile, screen zooms in when clicking a region - DPO Consulting

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#8127]
**Engineering info:**  
- Innovation Team engineer: Pending the Innovation Team's 02/01 sprint planning
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2388
- DPO consulting engineer: N/A

-----

### Description

When clicking a region in mobile Safari, the screen zooms in a little bit:

![Kapture 2022-01-24 at 09 09 00](https://user-images.githubusercontent.com/1641214/150801336-81c191bf-c53a-463a-97a0-88dd56fdcd10.gif)

### Component(s) impacted

Locale Modal

### Browser

Safari

### Carbon for IBM.com version

1.30.0-rc.0 and 1.29.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Storybook and WC test

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/?path=/story/components-dotcom-shell--default

### Steps to reproduce the issue (if applicable)

1. Go to Dotcom Shell story in mobile: https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/?path=/story/components-dotcom-shell--default
2. Open the locale modal
3. Click a region

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by IgnacioBecerra** [comment]
#6582 Should fix this bug when changing the font size to a bigger one.

**Comment by proeung** [comment]
@IgnacioBecerra Thanks and good to know! In the meantime, I'll close this issue out and note that the solution will be accounted for in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6582.
