### ISSUE TITLE
[npm vulnerabilities]: dependency marked needs to be update

### ISSUE THREAD

**Issue by markkulube** [carbon-design-system/carbon-for-ibm-dotcom#8130]
### Description

There is a high npm vulnerability associated with the package `marked: ^2.0.0`.

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/0026aa45d9033f049902fbc790bdb33797a90bb7/packages/utilities/package.json#L56

npm requires `marked` version 4.0.10 or greater where in the vulnerability is patched.
![image](https://user-images.githubusercontent.com/34955942/150820176-3482688b-b927-4a73-a190-b07563412b1b.png)

### Component(s) impacted

N/A

### Carbon for IBM.com version

1.11.0

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

cloud.ibm.com/docs

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ariellalgilmore** [comment]
Hi @markkulube! We have a PR open for this https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8037

**Comment by markkulube** [comment]
@ariellalgilmore thanks.

So closing this issue as resolution is in PR #8037
