### ISSUE TITLE
[Test Scenario]: Cloud Masthead - DDS Consulting

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#8133]
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2379
- DPO consulting engineer: @annawen1 

-----

### Component and test scenario title

Masthead - Cloud
- This component is marked behind a feature flag and it's available to preview via the experimental deploy preview.
- Enable this component locally
  - Edit your `.env` file and add this line `DDS_CLOUD_MASTHEAD=true`.

### Test scenario steps

**Menu Testing**

1. Check the "IBM" logo is loading and clickable
2. Check the "Cloud" platform name and ensure that it links out to `ibm.com/cloud` and it's clickable. 
2. Check 5 Mega menu options (eg. Products, Solutions, Pricing, Support, and Explore More) are loading with one active(selected) state, and all options are clickable.
3. Click through one of the menu items from the left tabbing list and ensure that it returns the tab panel content.
4. Check Mega menu drop down links and options are clickable/operable
4. Click on the Mobile hamburger menu and ensure that the Mobile Menu (Left Nav) opens and the menu listing is visible
5. Click through the mobile left nav and ensure that the top links are functioning as expected.
6. Add a test case for ensuring that the nav next/previous carets are rendering on the table breakpoints. This is important as we need to ensure that the users are still available to navigate through the masthead once the menu items are longer than the set container.

**Search** - Should be the same as the Default/Global Masthead

1. Check Search edit field is open by default
2. Check Search edit field opens and the user can enter keywords
3. Check Search field auto-suggest results (10 results should be displayed)
4. Verify Menu options must be hidden while the search edit field is open.

**CTAs**

1. Check the "Contact us" CTA and ensure that the `data-ibm-contact="contact-link"` attribute is present. This attribute is needed for the activation of the IBM Cloud Chatbot.
2. Check and ensure that the "Contact us" button is hidden on the Mobile breakpoints.
3. Click on the blue CTA button "Create IBM Cloud account" and ensure that it's clickable.

**Authentication**

1. Click on the "Log in" CTA and ensure that this button is clickable and directs the user to `https://cloud.ibm.com/login`.

**Comment by andy-blum** [comment]
@proeung 

> **Authentication**
>
> Click on the "Log in" CTA and ensure that this button is clickable and directs the user to https://cloud.ibm.com/login.
If authenticated via the https://cloud.ibm.com, the browser cookie should return com.ibm.cloud.iam.LoggedIn.manual. (I'm not sure how we're tackling this within the automatic testing script, but this line item is part of the manual regression testing.

The cypress framework does not allow running tests across multiple origins. The browser will follow a clicked link, but the tests will stop. We're also not able to manually navigate to that location.

<img width="482" alt="Screen Shot 2022-01-31 at 1 48 23 PM" src="https://user-images.githubusercontent.com/25532785/151854270-2a90c53f-9398-4d4c-9ef5-4f55aba41a82.png">

**Comment by proeung** [comment]
@andy-blum I figured that might be the case. I'll adjust the test scenario to check and verify that the "Login" button links out to the Cloud counsel (`https://cloud.ibm.com/login`).
