### ISSUE TITLE
[Cloud Masthead]: Add an environment variable to enable the Cloud Masthead for the Storybook build side

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#8138]
### The problem

- For this sprint, we're diving into creating e2e testing scripts for the Cloud Masthead (see - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8133), which is currently marked behind a feature flag.

### The solution

- In order to run to enable this component as part of the e2e testing process, we need to add an environment variable so that the 2e2 tests coming out of (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8133) will not fail when we try to run it.

### Application/website

Drupal / AEM

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
This is being added to @andy-blum's Cloud Masthead e2e testing PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8174
