### ISSUE TITLE
[Test Scenario]: False positives occurring with CTA Feature test

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#8159]
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2389
- DPO consulting engineer: N/A

-----

### Component and test scenario title

Feature CTA - Should load image on left and content on right

### Test scenario steps

The following test is being skipped for now:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/react/tests/e2e-storybook/cypress/integration/CTA/Feature.e2e.js#L175-L178

This is generating a number of false positives in tests. This should be addressed, possibly with adding a `cy.waitUntil` or some way of waiting for layout to complete rendering before running the test.

**Comment by proeung** [comment]
@andy-blum Can you take a look at this issue since you worked on https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7827?
