### ISSUE TITLE
[Sandbox]: Setup a sandbox repo (aka C4AEM) for creating experimental components  

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#8196]
### The problem

- Looking at the needs from the team that's in charge of the new branding expression, there's a desire to experiment with new components that they can hit the glass quickly.
- Carbon for IBM.com offers feature flag/canary release, however, deploying in this tag is too much of a risk for the other stable components that the library is support. Also, the release schedule is a bit too spread out to create experiments.
- One thought that @jeffchew and I have been bouncing is to introduce a sandbox package. This would be based on the latest stable version of C4IBM using the current Web Components package but would include a small storybook of new, experimental components that can be built quickly and published, and iterated adhoc and in a nimble way.
- We envision this as a place where folks can flex some creative juices and we can work on getting these experiments out for AEM and Adobe Target to take advantage of right away. 
- The goal is to graduate these components from the sandbox and put it into the main C4IBM library. 

### The solution

**Solution outlines from the 02/02/2022 Engineering Huddle:**

- Extend from carbon for ibm.com web components
- Something that will be easy for the Adobe team to pull down
- Separated from the Carbon for IBM.com release schedule
- Able to iterate quickly and not shackled down by the Carbon for IBM.com release schedule
- Should be a flat package (not a mirror of Carbon for IBM.com)
- Carbon for IBM.com is possibly an upstream dependency
- Implement a different prefix for custom elements (easily identify that there are experimental components on the page)
- Ultimately, will create a Zenhub board on the repo itself in IBM Github for issue tracking

**Governance** - The governance aspect to this sandbox project will need to be figured out, however, this issue is intended for the work to get the sandbox spin up from the ground up.

### Application/website

Drupal/AEM

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment]
@kennylam Can this Epic be closed?

**Comment by jeffchew** [comment]
Moved the governance issue into its own standalone issue, closing this epic.
