### ISSUE TITLE
[Table of Contents]: Manual trigger for anchor harvesting - DPO Consulting

### ISSUE THREAD

**Issue by dratzenboeck-ibm** [carbon-design-system/carbon-for-ibm-dotcom#8216]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2400
- AEM JIRA ticket: https://jsw.ibm.com/browse/ADCMS-2095
- DPO consulting engineer: @IgnacioBecerra 

-----

### The problem

CMS authors are changing titles / anchors within the TOC, but the TOC links do not update automatically. After the author changes a title, I want to be able to trigger an update on the TOC to harvest the anchors again. 

### The solution

Provide a method on the TOC element (or add logic to https://lit.dev/docs/v1/components/lifecycle/#requestupdate ), which will trigger harvesting of anchor tags within the TOC. 

### Application/website

Afterburner Adobe CMS / https://www.ibm.com

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
Based on my conversation with @IgnacioBecerra, for this request, we'll need to check for the event that AEM provides for when the element is edited and trigger the rescan.

**Comment by dratzenboeck-ibm** [comment]
@proeung Can't you provide a method on the table of contents element to make it more reusable? So that I would just call that method on the AEM event. Because there would be multiple AEM events to trigger that method.

**Comment by proeung** [comment]
@dratzenboeck-ibm Yep! I should have a PR up for you to review shortly.

**Comment by proeung** [comment]
@dratzenboeck-ibm Here's the PR for this feature request (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8329). Please take a look and let me know what you think.

Also, is there a corresponding ADCMS JIRA ticket for this request on your side? If so, can you give me the number so that I can update the status so that your team will know which release these changes will be available in? cc: @EAVilleda

**Comment by dratzenboeck-ibm** [comment]
@proeung Created one https://jsw.ibm.com/browse/ADCMS-2095
