### ISSUE TITLE
[Sandbox]: Basic integration tests

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#8222]
### User story

> As a `[user role below]`:

> I need to:

> so that I can:

### Additional information

- Create isolated sandbox builds for each component
- Run Cypress e2e tests on each
- will check if any exceptions are thrown
- Run on main and possibly on PRs

### Acceptance criteria

- [ ] Jenkins job that will build the sandbox components individually then run basic cypress e2e tests on it
- [ ] Should run on `main` and PRs

**Comment by jeffchew** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Carbon-for-IBMcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/8222?planning-poker) with ZenHub @annawen1 @ariellalgilmore @emyarod @IgnacioBecerra @kennylam @proeung

**Comment by proeung** [comment]
@kennylam Can we prioritize this issue for this sprint 5? Thanks!
