### ISSUE TITLE
[C4AEM/Sandbox]: Create documentation for the sandbox

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#8224]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2424
- DPO consulting engineer: N/A

-----

### User story

> As a `[user role below]`:

> I need to:

> so that I can:

### Additional information

- [x] Main repo README (how to build/use the repo, its purpose, etc)
- [x] Add a README to the storybook (pinned to the top of the storybook)
  - Should be pretty similar to the main repo README
- [x] Add doc to each component
- [x] Github templates (PRs)
- [ ] Git issue templates (Pending decision from folks on whether to use JIRA or GH issues)
- [x] Release process (canary vs latest), CDN only
- [ ] Governance process (TBD documentation)
- [x] dependabot yml file

### Acceptance criteria

- [ ] All documentation and Github templates added to the repo

**Comment by jeffchew** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Carbon-for-IBMcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/8224?planning-poker) with ZenHub @annawen1 @ariellalgilmore @emyarod @IgnacioBecerra @kennylam @proeung

**Comment by jeffchew** [comment]
Some documentation will need to be added/revised over time (especially governance)

**Comment by annawen1** [comment]
@proeung tagging you to this ticket for info on the governance process and maybe the Main repo README?
