### ISSUE TITLE
[Sandbox]: New leadspace component from the Brand Expression project

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#8227]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2420
- DPO consulting engineer: N/A

-----

### User story

> As a `[user role below]`:

> I need to:

> so that I can:

### Additional information

- Add new leadspace component to storybook
- Light documentation
- Include motion to showcase
- Include design specs
- How to showcase this on a page (web components test template)

### Acceptance criteria

- [ ] Lead space added to storybook
- [ ] published on CDN

**Comment by jeffchew** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Carbon-for-IBMcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/8227?planning-poker) with ZenHub @annawen1 @ariellalgilmore @emyarod @IgnacioBecerra @kennylam @proeung

**Comment by proeung** [comment]
PR: https://github.ibm.com/webstandards/carbon-for-ibm-dotcom-innovation-sandbox/pull/11

**Comment by proeung** [comment]
Follow up PR - https://github.ibm.com/webstandards/carbon-for-ibm-dotcom-innovation-sandbox/pull/19
