### ISSUE TITLE
[Figma kit] Lead space centered component

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8235]
Follow on to #8136

We have the left-aligned variants of the `Lead space` component, now we need to add the centered lead space. Needs to include:
- [ ] Default
- [ ] with breadcrumb
- [ ] with tag group
- [ ] image variants of the above
- [ ] video variants of the above

![Screen Shot 2022-06-11 at 11.47.38 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/f6daec4e-32a9-4176-a66d-38bf4f7422e0)

**Comment by oliviaflory** [comment]
Duplicate, see Figma board for details
