### ISSUE TITLE
[Carousel]: mixture of dds-card and dds-card-cta causing heading alignment issue - DPO Consulting

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#8247]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2406
- AEM JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-1338
- DPO consulting engineer: @IgnacioBecerra 

-----

### Description

- The AEM team is noticing an alignment issue when there's a mixture of `<dds-card>` and `<dds-card-cta>` within the `<dds-carousel>` component.
- If one of the first two cards has a heading with three lines, then the copy text of all cards align again, however, if a video card has the longest heading, then they do not align.
- This might be an issue related to the sameHeight function is not calculating the video heading compared to the regular headings.

<img width="1624" alt="image-2022-02-09-17-15-11-703" src="https://user-images.githubusercontent.com/1815714/153505293-b13e3282-ed6a-471b-9527-dc2348df12ce.png">

### Component(s) impacted

dds-carousel

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v1.30, Canary

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/gifted-blackburn-uk21f?file=/index.html

### Steps to reproduce the issue (if applicable)

See CodeSandbox link to view the issue.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
Should create a test scenario issue for this.

**Comment by proeung** [comment]
@jeffchew Yep! I'll create a new issue for adding a new SB variant that includes a mixture of `dds-card` and `dds-card-cta` so that we can use it in the e2e testing of this component. We'll account for this work in a separate ticket.

**Comment by proeung** [comment]
@jeffchew @kennylam Here's an issue for the Carousel e2e testing (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8330), which should include a test for this variant so that we won't run into this alignment issue again.
