### ISSUE TITLE
[CTACard]: video heading is blue

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#8273]
### Description

Heading should not be blue

<img width="364" alt="Screen Shot 2022-02-14 at 3 19 25 PM" src="https://user-images.githubusercontent.com/20210594/153956054-e1c1d148-9abb-4c16-ac56-d15140559f86.png">
 

### Component(s) impacted

CTACard

### Browser

Chrome

### Carbon for IBM.com version

1.31.0-rc.1

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

carbon for ibm.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-cta--card

### Steps to reproduce the issue (if applicable)

1. go to https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-cta--card
2. select video knob

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RichKummer** [comment]
Seeing this in Firefox as well
