### ISSUE TITLE
[image]: border knob doesn't add border

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#8276]
### Description

No border shown in Image component

<img width="381" alt="Screen Shot 2022-02-14 at 3 54 59 PM" src="https://user-images.githubusercontent.com/20210594/153960508-00085ec4-a774-433b-8bb3-2bb06124d58f.png">

### Component(s) impacted

Image

### Browser

Chrome

### Carbon for IBM.com version

1.31.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

carbon for ibm.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-image--default

### Steps to reproduce the issue (if applicable)

1. go to storybook:https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-image--default
2. check border knob

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment]
retest in other theme

**Comment by ariellalgilmore** [comment]
works fine!
