### ISSUE TITLE
[Content block media]: Opening canvas in new tab error

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8281]
### Description

`Content block media` appears as normal in Storybook, but when I open the canvas in a new tab I get an error. This only happens in Firefox, not in Chrome.

<img width="1646" alt="Screen Shot 2022-02-15 at 10 48 47 AM" src="https://user-images.githubusercontent.com/15643582/154098132-db819a72-a8a6-4823-b8db-41acdec091c8.png">

### Component(s) impacted

Content block media

### Browser

Firefox

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/react/examples/codesandbox/components/ContentBlockMedia

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
Looks like this has been fixed.
