### ISSUE TITLE
[cardlink]: (react wrapper) disabled does not change heading/copy color

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#8284]
### Description

When CardLink is disabled heading/copy color do not change

<img width="407" alt="Screen Shot 2022-02-15 at 9 23 50 AM" src="https://user-images.githubusercontent.com/20210594/154105260-3eea1077-99cf-4ce6-aa45-55c3610c33fb.png">

### Component(s) impacted

cardLink

### Browser

Chrome

### Carbon for IBM.com version

1.31.0-rc.1

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

carbon for ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components-react/?path=/story/components-card-link--default

### Steps to reproduce the issue (if applicable)

1. go to this story: https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components-react/?path=/story/components-card-link--default
2. disable card link and view heading/copy

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RichKummer** [comment]
Also seeing in Firefox:
<img width="556" alt="Screen Shot 2022-02-16 at 11 45 47 AM" src="https://user-images.githubusercontent.com/15643582/154314227-33dfc055-bd1c-4ee4-a236-cd88c50b3f09.png">

**Comment by ariellalgilmore** [comment]
Seems to be fixed
![Screen Shot 2022-04-27 at 10.55.35 AM.png](https://images.zenhubusercontent.com/5ee7ae1cc40147132b286905/8490e670-e3c3-42d2-88b4-08dcbca44102)
