### ISSUE TITLE
[card-in-card]: (react wrapper) image not coming through

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#8285]
### Description

Expected there to be an image where there is a large white space

<img width="371" alt="Screen Shot 2022-02-15 at 9 33 48 AM" src="https://user-images.githubusercontent.com/20210594/154106836-7e88b741-1753-4b32-b38d-02e7d4cf54be.png">

### Component(s) impacted

card-in-card

### Browser

Chrome

### Carbon for IBM.com version

1.31.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

carbon for ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components-react/?path=/story/components-card-section-offset--default

### Steps to reproduce the issue (if applicable)

1. go to react wrapper story: https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components-react/?path=/story/components-card-section-offset--default
2. should see image in the background

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
Fixed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8673.
