### ISSUE TITLE
[Dotcom Shell]: CTA - Card link has blue text in header

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8293]
### Description

In Dotcom Shell Storybook, the CTA - Card link that appears on the page has a blue heading. Could be related to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8273

<img width="1433" alt="Screen Shot 2022-02-15 at 3 07 48 PM" src="https://user-images.githubusercontent.com/15643582/154140936-abe0f018-5cb5-4a37-b904-d32fb13dc3bd.png">

### Component(s) impacted

Dotcom shell

### Browser

Firefox

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/react/examples/codesandbox/components/DotcomShell

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment]
Will be fixed with CTA card link bug.  Closing
