### ISSUE TITLE
[Footer - default language only]: Keyboard navigation for language selector

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8295]
### Description

When using the `footer` variation with the language selector, it's unclear how I should update the language using the keyboard - the instructions from VoiceOver tell me to enter another name, but typing any letter reverts the selection to English. 

https://user-images.githubusercontent.com/15643582/154153666-1bc2bec1-a700-440b-a965-dab1dc423eac.mov

### Component(s) impacted

Footer - default language only

### Browser

Firefox

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/react/examples/codesandbox/components/Footer

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ariellalgilmore** [comment]
Tested this on firefox and see the issue. The same issue is happening with [Carbon core ](https://react.carbondesignsystem.com/?path=/story/components-combobox--combobox-story) on firefox with VO.

if you don't have VO on though and just tab into the footer and type the language it works fine.

Seems like an issue with VO on firefox.
![Mar-21-2022 13-14-32.gif](https://images.zenhubusercontent.com/5ee7ae1cc40147132b286905/4ddac4ca-2e33-4e28-9a9e-46f1a2db67eb)

**Comment by ariellalgilmore** [comment]
Tested this on JAWS as well and it works. Closing this issue

https://user-images.githubusercontent.com/20210594/159373036-0bc9b20a-34b3-4018-a344-30dc45e30e70.mov
