### ISSUE TITLE
[Card group - default]: Extra border on Gray90 & Gray100

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8299]
### Description

In React wrapper: On the darker themes, a light border appears on the edge of the 3rd card in the row. This also shows up for `Card group - with card in card` in Gray90 & Gray100.

<img width="1571" alt="Screen Shot 2022-02-16 at 8 38 00 AM" src="https://user-images.githubusercontent.com/15643582/154276439-cd18881f-ecd4-47c5-b0fa-6ec7b8c0dbc3.png">

### Component(s) impacted

Card group

### Browser

Firefox

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/examples/codesandbox/components-react/card-group

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
This issue looks to be similar to the one outlined in this one (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8335).

**Comment by proeung** [comment]
Closing this issue in favor of this one (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8335), which will address some of the border regression bugs seen within the Card Group component.
