### ISSUE TITLE
[Card - Pictogram]: React wrapper - pictogram position top does not reveal body text on hover

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8302]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2411
- DPO consulting engineer:

-----

### Description

In Firefox and when `Card - Pictogram` is set to the top position, hovering on the card does not reveal any body text. The title animates out of view but nothing comes in to replace it. This works fine when the pictogram is in the bottom position.

https://user-images.githubusercontent.com/15643582/154316116-9b37b8c1-8055-4a23-8c84-bb0b1aab6a00.mov

On Mobile Safari, the Card in top position appears with no body copy, but appears with body copy in bottom position
![IMG_2033](https://user-images.githubusercontent.com/15643582/154345502-7fae73ac-43a4-4f6f-8d76-899fa8f5c7cf.PNG)

### Component(s) impacted

Card - Pictogram

### Browser

Firefox

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/examples/codesandbox/components-react/card

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@kennylam Just checked the WC storybook preview (see [link](https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/?path=/story/components-card--pictogram)) and the re-rendering of the `Card with Pictogram` when the knob is adjusted seems to be working fine, however, the WC (with React wrapper) (see [link](https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components-react/?path=/story/components-card--pictogram)) is not behaving in the same manner. Do you know the difference between these two previews and is there a way to have a consistent rendering when the attribute has been updated in the SB preview?

**Comment by kennylam** [comment]
Oh, interesting. Looks like the react wrapper version is missing the slotted content for some reason (wrapper on the left).

![image](https://user-images.githubusercontent.com/909118/155230258-65157914-e5d2-49ca-a969-dcb4c9cede76.png)
