### ISSUE TITLE
[Content block simple]: Spacing between content and CTA text

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8304]
### Description

In Firefox for React wrapper, there is too much spacing between the content of `Content block simple` and the CTA text (if there is one selected). Currently, it looks like the spacing is set to 64px, while the specs say it should be 32px

**Firefox**
<img width="1793" alt="Screen Shot 2022-02-16 at 12 33 09 PM" src="https://user-images.githubusercontent.com/15643582/154322828-df8cc253-8585-441b-b0ee-99562714e915.png">

**Design specs**
<img width="779" alt="Screen Shot 2022-02-16 at 12 35 42 PM" src="https://user-images.githubusercontent.com/15643582/154323138-e43d2cf3-b7b6-45d6-9919-c20ec94030b9.png">

### Component(s) impacted

Content block simple

### Browser

Firefox

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/examples/codesandbox/components/content-block-simple

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment]
@RichKummer
