### ISSUE TITLE
[Lead space search - with image]: Image background not appearing

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8308]
**Engineering info:**  
- Innovation Team engineer: @mwanberg 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2414
- DPO consulting engineer: @IgnacioBecerra 

-----

### Description

In Firefox using React wrapper - an image should appear inside the `Lead space search - with image`, but no image appears in the background.

<img width="1478" alt="Screen Shot 2022-02-16 at 1 03 12 PM" src="https://user-images.githubusercontent.com/15643582/154327687-20e6f359-14c8-42a7-aa31-d86e9c6e0ac3.png">

### Component(s) impacted

Lead space search - with image

### Browser

Firefox

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components-react/?path=/story/components-lead-space-search--with-image

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
I'm not sure this is a bug so much as it's a feature that's not available in the react wrapper.

The leadspace-with-search component is utilizing the `<dds-background-media>` component which is not a part of the react-wrapper stories, and the only other react-wrapper story to use background-media is the card-section-offset where the image also fails to load.

The leadspace component variations within react-wrapper are still utilizing the old setup of dds-leadspace-image.

Are we expecting `<dds-background-media>` to work in this environment at this time or not?

**Comment by proeung** [comment]
@kennylam Please take a look at @andy-blum's comment. I'd like to get your input on what direction we should take for the react wrapper version of this leadspace component as well.

**Comment by kennylam** [comment]
@proeung This definitely is a bug and should be fixed. Agree on removing the severity since this is more of a 3 to me.
