### ISSUE TITLE
[ToC - Horizontal]: anchor link half covering headings

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8309]
### Description

When clicking an option in `Table of contents - horizontal` in Firefox, the anchor link will navigate me to the right section, but about half the header is covered by the fixed ToC element.

Uploading Screen Recording 2022-02-16 at 1.08.57 PM.mov…

### Component(s) impacted

Table of contents - horizontal

### Browser

Firefox

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/examples/codesandbox/components-react/table-of-contents

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
This work is being completed in #8240, and should resolve this issue.
