### ISSUE TITLE
[NextJS]: Gray100 theme 'See components in action' CTA does not scroll

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8313]
### Description

The second button from the left that appears in the Gray100 theme page for NextJS should scroll the user to the first section of the page (just like the White theme).
<img width="1820" alt="Screen Shot 2022-02-16 at 1 40 51 PM" src="https://user-images.githubusercontent.com/15643582/154333993-837ed4c7-4599-4c91-94c5-ff6518a5c302.png">

### Component(s) impacted

NextJS Gray100 theme

### Browser

Firefox

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom-nextjs-test/next/g100-theme-example.html#content

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment]
Duplicate @RichKummer
