### ISSUE TITLE
[NextJS]: Cannot tab into Carousel card content

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8315]
### Description

When tabbing through the White theme page content using VoiceOver in Firefox, tabbing in the card carousel moves me from the CTA in the section content directly to the carousel controls, without tabbing through any card content. I should move from CTA into the card content before tabbing to the carousel controls.

This also happens in the Card carousel in the Gray100 theme.
https://user-images.githubusercontent.com/15643582/154335303-f57abe0a-e420-459e-8338-72a704c1c148.mov

### Component(s) impacted

Card carousel

### Browser

Firefox

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom-nextjs-test/next/white-theme-example.html

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment]
Duplicate
