### ISSUE TITLE
[Tabs extended media]: Mobile has content too close to tabs

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8318]
### Description

When in the `@sm` breakpoint and a tab is expanded, the area of the tab is overlapping the Tab's heading inside the content. On `@sms`, there should be `16px` between the bottom of the tab and the top of the heading.

<img width="241" alt="Screen Shot 2022-10-12 at 2 12 07 PM" src="https://user-images.githubusercontent.com/15643582/195417881-7443b087-0c5c-4293-8b45-23b0371a43c8.png">

**Design specs for mobile**
<img width="809" alt="Screen Shot 2022-02-16 at 2 28 04 PM" src="https://user-images.githubusercontent.com/15643582/154341054-b355a3e9-63d5-4acc-aa6e-d0d2e1760fe4.png">

### Component(s) impacted

Tabs extended media

### Browser

Safari

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components-react/iframe.html?id=components-tabs-extended-media--default&knob-Heading=Title%20heading&knob-Alignment=left&knob-Media%20type=video&knob-Image%20alt%20text=Lorem%20ipsum&knob-Heading%20(heading):=Aliquam%20condimentum&knob-CTA%201%20type%20(cta-type):=local&knob-CTA%201%20copy%20(cta-copy):=Learn%20more&knob-CTA%201%20href%20(cta-href):=https://www.ibm.com&knob-CTA%202%20type%20(cta-type):=external&knob-CTA%202%20copy%20(cta-copy):=Microservices%20and%20containers&knob-CTA%202%20href%20(cta-href):=https://www.ibm.com&knob-Tag%20Type:_TagGroup=Tag%20Link

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment]
@RichKummer replace with correct screenshot
