### ISSUE TITLE
[Table of contents]: Mobile highlight for anchor link

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8321]
### Description

On Mobile Safari, when clicking a selection from the ToC dropdown, the user is sent to the selected header. However, the area covered by the highlight is awkward, and covers the preceding content.
![IMG_2034](https://user-images.githubusercontent.com/15643582/154347120-23b72a04-449b-4e4c-b4b6-b3871af7b7ee.PNG)

### Component(s) impacted

Table of contents

### Browser

Safari

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/examples/codesandbox/components-react/table-of-contents

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Duplicate! Fixed in #8659
