### ISSUE TITLE
[Link with icon]: Visited link in mobile Safari

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8332]
### Description

On mobile Safari, the visited link toggle in Storybook only changes the color of the text - the icon remains blue when it should also turn the same color as the visited text in the CTA.

![IMG_2039](https://user-images.githubusercontent.com/15643582/154545829-93f6db37-f0c8-4302-843c-2f7dfc08ce30.PNG)

### Component(s) impacted

Link with icon

### Browser

Safari

### Carbon for IBM.com version

v1.31.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-link-with-icon--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
This has already been resolved in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8367.
