### ISSUE TITLE
[Content Block Horizontal border attribute]: The content block horizontal web component is always setting border attribute as true by default.

### ISSUE THREAD

**Issue by druckerk** [carbon-design-system/carbon-for-ibm-dotcom#8348]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2419
- DPO consulting engineer:

-----

### Description

**Expected Results:**
When a user uses the <dds-content-block-horizontal> component, the default for this component should be showing in the inspect html as <dds-content-block-horizontal data-autoid="dds--content-block-horizontal"></dds-content-block-horizontal>. Then when a user adds the attribute "border" to the <dds-content-block-horizontal border> component, then the component should be appearing as <dds-content-block-horizontal border data-autoid="dds--content-block-horizontal"></dds-content-block-horizontal> in the inspect html. 

**Actual Results:** 
When a user uses the <dds-content-block-horizontal> component, the current default is showing in the inspect html as <dds-content-block-horizontal data-autoid="dds--content-block-horizontal" border></dds-content-block-horizontal>. Then when the user adds the attribute "border" to the <dds-content-block-horizontal border> component, the component will appear as <dds-content-block-horizontal border data-autoid="dds--content-block-horizontal"></dds-content-block-horizontal> in the inspect html. 

### Component(s) impacted

Content Block Horizontal

Storybook:
https://www.ibm.com/standards/carbon/web-components/?path=/docs/components-content-block-horizontal--default

### Browser

Chrome

### Carbon for IBM.com version

ibmdotcom-web-components: 1.15.0 / ibmdotcom-styles: 1.30.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/red-cookies-5v9qnw?file=/dist/index.html

### Steps to reproduce the issue (if applicable)

In the code sandbox:

1. Test the <dds-content-block-horizontal> element without the "border" attribute.
2. Once the build completes, then inspect the HTML from the browser and you will see the "border" attribute appear to the right of the data-autoid attribute in the element. 
3.  Then go back to the code add the "border" attribute to the element. 
4. Once the rebuild is completed, then inspect the HTML from the browser and you will see the "border" attribute has moved to the left of data-autoid attribute in the element. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@druckerk Thanks for opening this issue! I just put together a sandbox code example of the `Content Block Horizontal` layout component as well and I do notice that the `border` attribute is not working as expected. Ideally, when the `border` attribute is not defined within the `<dds-content-block-horizontal>` element, the component should not render the border-bottom line. We might need to look at the `border` prop and see what's causing this issue.

Sandbox code example: https://codesandbox.io/s/gracious-torvalds-e0yipl?file=/index.html

@kennylam I'm going to assign our Innovation team to this issue.
