### ISSUE TITLE
Internet Explorer sunset: Details on policy

### ISSUE THREAD

**Issue by CarlosCastro12** [carbon-design-system/carbon-for-ibm-dotcom#8360]
### Summary

Hello IBM Governance board. 

We have 4 applications (4 separate instances per region of 1 product). I navigated IBM web standards page (https://w3.ibm.com/w3publisher/ibm-web-standards-external/standards-mandatory/browser-standards) and IBM.com Web standards page (https://www.ibm.com/standards/web/) without success on finding an answer. I was referred to open this ticket.

These applications are from a 3rd party vendor and run in Internet Explorer. As you might be aware already, Microsoft announce IE is being sunset in June. This set of applications are the strategic CAS systems worldwide, and are currently using IE compatibility mode to run,

1.- Is there a browser policy that would prevent or automatically disable IE compatibility mode after June?
2.- Is there any kind of extension as the vendor won't be able to adjust their product prior to June?
3.- Is there maybe a person we can talk to go in detail and review the case and help us define the best course of action as this application can't be down or stop working?

You help is needed and appreciated. Thank you

### Name and organization

Carlos Castro
IBM CIO Architect & Iteration Manager for Security Services portfolio
carlos.castro.cabrera@ibm.com

Organization: IBM CIO
Domain: Digital Enablement & Supply Chain
Sub-Domain: CIO Real Estate, Research, & Security Systems

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
@CarlosCastro12 We have not supported IE since Q1 of 2020 due to low usage across IBM.com. We did note that on the w3 page for [Browser standards](https://w3.ibm.com/w3publisher/ibm-web-standards-external/standards-mandatory/browser-standards) under the Change history section:
> March 2020 – Updated to call out Mobile as well as Desktop. Created separate tables for Desktop and for Mobile. Updated with current browsers for Desktop based on usage, including QQ Browser due to China usage. Moved mobile browsers in old Desktop table across to Mobile table: Samsung Internet and UC Browser. Removed IE11 from Desktop Tier 2 due to low usage, and because it does not ship as the default browser for Microsoft's latest operating system. Also Brave removed from Desktop Tier 2.
