### ISSUE TITLE
[CI]: CDN builds failing

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#8383]
### Description

Current CDN builds are failing for the `build:components` job.

### Component(s) impacted

`@ibmdotcom/utilities`

![image](https://user-images.githubusercontent.com/909118/155619138-9fdc6ded-c397-4b33-be16-7e1b8d6f04ce.png)

### Carbon for IBM.com version

latest

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

Carbon for IBM.com

### Package

@carbon/ibmdotcom-utilities

### CodeSandbox example

N/A

### Steps to reproduce the issue (if applicable)

```
yarn
yarn build
cd packages/web-components
yarn build:components
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
@kennylam moved this into `to do this sprint` and added to `sprint 4`.
