### ISSUE TITLE
Update the banner on the standards/web page to indicate 2022 instead of 2021

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/carbon-for-ibm-dotcom#8439]
### The problem

Currently it references the sunset of v18 at the end of 2021.  

### The solution

The message should read "Please be aware that the v18/v19 is targeted to be sunset at the end of 2022 and Carbon for IBM.com based on the Carbon Design System is its official replacement."

### Application/website

www.ibm.com/standards/web

### Business priority

High Priority = pressing release

### What time frame would this ideally be needed by (if applicable)

ASAP

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Mike requested to update the banner color to an IDL color, if we can update to Blue 90 `#001d6c` that would be awesome!
