### ISSUE TITLE
Cannot read properties of null (DDSBackgroundMedia and DDSVideoPlayerContainer) - WebComponents

### ISSUE THREAD

**Issue by Quentin-Macquart** [carbon-design-system/carbon-for-ibm-dotcom#8454]
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2496
- DPO consulting engineer: N/A

-----

### Description

Hello Everyone,
I met some issues with the ibm-dotcom-web-components and i'm asking for help.
After import my dds-video-player-container from the good file, i put the Kaltura Id of my video, and it didn't work and i got this error (image joined)
Is anyone got this problem ? It cannot read the dataset because the value just before is considered as "null"
FI : This web-component is in the DDSBackgroundMedia component.
Thanks in advance for your help guys !
<img width="942" alt="Capture d’écran 2022-03-03 à 17 32 15" src="https://user-images.githubusercontent.com/77687596/156726619-a14f33e4-f1d5-4cc0-93e9-c68c0bfe8e32.png">

### Component(s) impacted

There is no render at all of the video container of the background media web-components.

### Browser

Chrome

### Carbon for IBM.com version

v1.16.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

IBM intern website

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/?path=/docs/components-video-player--default

### Steps to reproduce the issue (if applicable)

import dds-background-media and dds-video-player-container in react app after downloading the good package.
Rename these tags like : DDSBackgroundMedia, in your imports. 

It shouldn't work on the render.

### Release date (if applicable)

This was released 2 days ago.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by IgnacioBecerra** [comment]
Hey @Quentin-Macquart! Would you be able to provide a CodeSandbox example of the issue you're facing? It would be helpful so we can start narrowing down this issue, thanks!

**Comment by IgnacioBecerra** [comment]
@Quentin-Macquart, just wondering if you were able to get this fixed?

**Comment by Quentin-Macquart** [comment]
Hello @IgnacioBecerra, unfortunately i didn't have the time to review this since i made this post. I found another way of getting this by adding the component video-player with the kaltura ID. 

I'll try to reproduce this error and i let you know, 
Have a great day,

**Comment by andy-blum** [comment]
@Quentin-Macquart any chance you can reproduce in a codesandbox? Looking at the error in your screenshot, I can see _where_ the code was failing, but I'm struggling to see why.

```ts
async _embedVideoImpl(videoId: string, backgroundMode = false) {
  const { ownerDocument: doc } = this;
  
  // Here we're creating a div with a specific ID
  const playerId = Math.random()
    .toString(36)
    .slice(2);
  const div = doc!.createElement('div');
  div.id = playerId;
  div.className = `${prefix}--video-player__video`;
  
  // Here we get the video player component and append that div
  const { _videoPlayer: videoPlayer } = this;
  if (!videoPlayer) {
    throw new TypeError('Cannot find the video player component to put the video content into.');
  }
  videoPlayer.appendChild(div);
  
  ...  

  // Here we're getting that same div
  doc!.getElementById(playerId)!.dataset.videoId = videoId;
  const videoEmbed = doc!.getElementById(playerId)?.firstElementChild;
  if (videoEmbed) {
    (videoEmbed as HTMLElement).focus();
  }
  return embedVideoHandle.kWidget();
}
```

My best guess at this time is that the DDSVideoPlayer component either wasn't imported, or wasn't on the page, but if that was the case I'd have expected the type error we throw in that code block: "Cannot find the video player component to put the video content into."

**Comment by Quentin-Macquart** [comment]
I found another solution to add a video in leadspace. I tried to reproduced the error when you published your answer last time but it did not sucessed.
