### ISSUE TITLE
[UX Designer & Researcher]: Filter Panel UX (expanded)

### ISSUE THREAD

**Issue by martin-stefanik** [carbon-design-system/carbon-for-ibm-dotcom#8464]
### The problem

We, the Unified Search and Product Discovery squad, launched the usability study of the Filter Panel UX. It was a balanced comparison usability study comparing two different UX:
1. (Version A) Expanding/Collapsing filter panel experienced defined by the Carbon for ibm.com standards
https://www.ibm.com/standards/carbon/components/filter-panel

2. (Version B) Expanded version of the filter panel experience with having some additional enhancements (in comparison to what we have now on ibm.com/products Products Catalog page):
a. Filter by typing
b. Scrollable list of filter sub-categories (when there is a very long list of subcategories, e.g. in Industries and Brands category)
Prototype: https://4nyeuv.axshare.com/b_version.html

The results of the study may be found here:
https://ibm.box.com/s/fznrraiknaw0qp44cllt251b6dstwyjk

We want to go live with the Version B experience and our development team will start working on that soon.

We would love the Carbon for ibm.com standards team to add this kind of filter panel experience to our design system so we have more filter panel experiences in our design system that the stakeholders can leverage.

Thank you and I appreciate it. 

Let me know if you have any questions, I'm happy to help,
Martin

### The solution

see above

### Application/website

ibm.com/products

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
@martin-stefanik Thank you for opening this Feature Request!

Outlining a few things we discussed in our previous meeting regarding the above request:

### 1. Update website guidelines
We will open an issue to update the guidelines on the Carbon for IBM.com site to inform adopters that expanding the categories performed better in this context. Right now we suggest only expanding 1–3.
   - I did notice that a lot of the testers comments on the label “Brands” not being informative of what would be under that label, so I wonder if that had any influence.
   - If I remember correctly, Keegan and Colleen did some testing of labels for the navigation and mega menu and that’s why that category is “top products and platforms” and not “brands” any longer.
   - Alphabetical ordering is already a part of the guidance.

### 2. Search page next steps
I’m ok with your team moving forward with the expanded filters + the view all link (we just got that released), but I’d like to see more visual explorations on the filter by typing and scrolling before the search team developers code that into the experience.

### 3. Additional explorations
We need additional explorations for the filter by typing and the scrolling within a category that the Version B prototype shows.
I would love for us to coordinate with Shawn and Joseph about the business priority of these items.

**Comment by martin-stefanik** [comment]
Thanks, @oliviaflory for your comments. Really great points!

I will get back to this "hill" once I complete some of my top priorities right now. Here are some of my comments:

A. I agree that informing adopters that expanding the categories performs better on the Product Catalog page. It doesn't mean that it will perform on any other website. In my point of view, it's the adopters' responsibility to conduct research that will convince them which is the better way to go for their offerings.
B. One of my findings that I communicated to broader stakeholders (including Shawn and the PM of the Search and Product Discovery squad) is that the naming conventions are confusing (Cloud, Cloud Computing, Topics, Solutions, Brands, Platforms, etc.). I believe that they added this into their backlogs.
C. We will definitely work with you and your team in order to have an alignment of the "filter by typing" experience (+ visual concepts) plus the scrolling within the category. We will for sure continue user research of these "new" features.
D. I will also talk to Shawn and Joseph about the business priority of these items. I will work more and more for them in the future.

Thanks again, Martin
