### ISSUE TITLE
[Universal banner]: Image stretching

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8474]
### Description

At the desktop breakpoints, the image in the Universal banner is being too condensed as the screen is resized. We should figure out a solution to keep the image clear as the window is resized.

![univ-banner--Mar-11-2022 16-23-44](https://user-images.githubusercontent.com/15643582/157974022-d846c0a9-7e55-4d52-b255-4cdbb3fb6240.gif)

@RichKummer and @oliviaflory to check the CTA alignment to the grid: https://ibm.ent.box.com/folder/142303458357?s=fas5qv5zrscudr63y85g28v0k657p83u

### Component(s) impacted

Universal banner

### Browser

Chrome

### Carbon for IBM.com version

v1.16.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/examples/codesandbox/components/universal-banner

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
Design to do additional testing and update functional specs. Consider keeping fixed width until next breakpoint where image will become hidden. See [example](https://annawen1.github.io/ibm-dotcom-think-banner/).

**Comment by oliviaflory** [comment]
**Feedback:**
- simplify type
   - Semi bold
   - Semi bold + regular ?
   - Try 14px
- left align type
- Try primary and tertiary buttons. Don't think secondary is the right choice
- Should we allow for colors other than the default themes
- option for video or image ? 
- Review in context (masthead) @ each breakpoint

Asset needs more space around it so it doesn't get cropped
Or adaptively change space around it so it doesn't get cropped.

Need detailed guidance on how to position and crop image. Has enough room to scale without being cropped.
