### ISSUE TITLE
[Structured list] React Wrapper: enhancement and new variant

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#8494]
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2497
- DPO consulting engineer: N/A

-----

#### User Story
> As a `[user role below]`:
Carbon for ibm.com developer

> I need to:
create/change the `Structured list`

> so that I can:
provide the ibm.com adopter developers components they can use to build ibm.com web pages

#### Additional information
- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- The React version is created as a wrapper to the Web Components version
- **See the Epic (#8385) for the Design and Functional specs information**
- Visual QA testing issue (#8386)
- Prod QA testing issue (#8387)

### 1. Structured list enhancement
- Ability to include paragraph breaks
- Ability to add checkmark icon in row items
- Ability to add tooltip
![Screen Shot 2022-02-25 at 11 44 45 AM](https://user-images.githubusercontent.com/45692622/155753753-6a47fbd0-4735-42a5-9172-49e8b1f9654e.png)

### 2. Structured list with row headers (vertical)
New variant of current structured list
- Ability for Rows to have heading style (no column headers) 
![Screen Shot 2022-02-25 at 11 47 15 AM](https://user-images.githubusercontent.com/45692622/155754122-8f0f02cb-4c01-46d3-83d4-587c959a31f9.png)

### 3. 8 columns
Not sure if this is an enhancement or new, I think structured list can already span 8 columns?
![Screen Shot 2022-02-25 at 11 48 46 AM](https://user-images.githubusercontent.com/45692622/155754495-af426c45-ce0e-4031-82d3-79abe94672ba.png)

#### Additional Information
- [Design specs](https://ibm.ent.box.com/folder/157071416507)
- [Carbon web components structures list](https://web-components.carbondesignsystem.com/?path=/story/components-structured-list--default)
- [Carbon React structured list](https://react.carbondesignsystem.com/?path=/story/components-structuredlist--simple)

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Create React wrapper
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] add the trigger to create the React Wrapper
 - [ ] create the React storybook stories and related documentation
- [ ] Update the Carbon for ibm.com website component [data file](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/blob/master/src/data/components.json) to be sure the web site Component Status and Storybook links are correct
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] Update the e2e test scripts, if needed. 
- [ ] Confirm e2e test results have no major errors.
- [ ] A comment is posted in the Prod QA issue (#8387) when development is finished.  
- [ ] The `dev complete` label is added to the Prod QA issue (#8387).

**Comment by proeung** [comment]
@kennylam @jeffchew I defer to you both on when you'd like to schedule the work for implementing the React Wrapper version of this component. In the meantime, our Innovation team is focused on contributing the work needed on the Web Component package side (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8388) for AEM consumption.

**Comment by jeffchew** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Carbon-for-IBMcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/8494?planning-poker) with ZenHub @annawen1 @ariellalgilmore @emyarod @IgnacioBecerra @kennylam
