### ISSUE TITLE
Can I import Plex glyphs with Carbon?

### ISSUE THREAD

**Issue by mstudio** [carbon-design-system/carbon-for-ibm-dotcom#8498]
### Summary

We recently ran into an issue on the "Let's Create" rebrand on IBM.com: https://www.ibm.com/lets-create/

On Safari, the design team noticed that the curly arrow glyph ↷, which appears on many new pages, does not render correctly in Safari.

We were able to fix this by adding the following to the `<head>`:

```
<link
      rel="stylesheet"
      href="//1.www.s81c.com/common/carbon/plex/plex-full.css"
/>
```

The only downside to this approach is that the font is loaded again. We are also using the following in the SCSS like so:

```
@import "~@carbon/type/scss/font-face/mono";
@import "~@carbon/type/scss/font-face/sans";
@include carbon--font-face-mono();
@include carbon--font-face-sans();
```

What is the best-practice approach to including glyphs on IBM.com?

### Relevant information

<img src="https://i.ibb.co/BL4BmGD/incorrect-safari.png" />

![image](https://user-images.githubusercontent.com/229130/158462700-88fbecc3-f9d7-47b0-b494-883f343c232b.png)

### Name and organization

Alex Motzenbecker
alex.motzenbecker@ogilvy.com
IBM/Ogilvy

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@mstudio What version of Safari is being used in that screenshot? I'm on `15.3 (17612.4.9.1.8)` and it renders correctly for me.

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/909118/159017670-d309c0bf-ff84-40c2-a1c1-974754598104.png">

**Comment by proeung** [comment]
@kennylam The glyph rendering issue is seen on the latest version of Safari `Version 15.4`, when the normal `plex.css` CDN is being used, however, when the reference is changed to `//1.www.s81c.com/common/carbon/plex/plex-full.css`, the glyph is rendering fine on Safari as seen on the current https://www.ibm.com/lets-create/ and this CodeSandbox (https://codesandbox.io/s/goofy-snyder-ds0d0u?file=/index.html).

Looks to me like the `plex-full.css` is pulling from `@ibm/plex` package, which has all of the font families and including glyphs where the normal `plex.css` doesn't have? https://github.ibm.com/webstandards/plex-cdn/blob/main/scss/plex-full.scss#L9

**Comment by kennylam** [comment]
@mstudio So after a little testing I can confirm these two imports should solve the problem – no need for `plex-full`

```css
<link rel="stylesheet" href="https://1.www.s81c.com/common/carbon-for-ibm-dotcom/tag/v1/latest/plex.css"/>
<link rel="stylesheet" href="https://1.www.s81c.com/common/carbon/plex/sans.css"/>
```
It looks like certain fonts may be left out in `plex.css` when the CDN file is built. I'll need to do a little more digging and create a new issue for this. But in the meantime this should resolve your issue so you don't need to import the entire font family.

cc: @proeung

**Comment by proeung** [comment]
@kennylam Yay! Looks like the two imports that you've suggested are working correctly on Safari. See CodeSandbox example - https://codesandbox.io/s/xenodochial-chandrasekhar-75cn7m

I'll update the documentation of this component so that adopters like AEM can use the proper plex imports to show the correct glyphs! Thanks, @kennylam!

**Comment by kennylam** [comment]
@mstudio @proeung New issue #8661 created to track this bug.
