### ISSUE TITLE
[Figma] Card section

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8527]
Add the Card section component to Figma kit. Remember we are only building variants for `xlg`, `md`, and `sm`. 

[Design spec](https://ibm.ent.box.com/folder/99476973715?s=6prfrgt7dftdg47ejy3q3m4x7h47kbmo)
[Website](https://www.ibm.com/standards/carbon/components/card-section)

**Must haves:**
- [ ] Use `Card - basic` in the component, if able. If we can't, we should create a new card component for `Card section`.
- [ ] Either give designers option to scale from 2-9 card (max 8 cards + 1 CTA Card) or deliver the largest version and let designers delete unnecessary ones. 

- [ ] There are two main variants: Default or With CTA

- [ ] Use or create a `Card CTA` that uses an inverse color scheme. Ideally should use a Card CTA version that's the same as `Card group`
- [ ] Card section can include cards with images (does this include video?)

![Screen Shot 2022-06-11 at 12.00.38 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/63b50d67-2b82-4761-91ce-fc93f7163050)

![Screen Shot 2022-06-11 at 12.00.44 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/2f768865-44a9-4127-b076-26fd62f0f209
)

**Resources**
- C4IBM.com Component checklist is available in the Read Me 👀 page of the Figma library
- [Bases demo](https://secure.video.ibm.com/channel/23570833/playlist/641336/video/131117161) from the Figma Fridays (Episode 23)
- Reference the [best practices](https://www.figma.com/file/8n9IJtHnICSydODoYl4ueW/Figma-Best-Practices?node-id=52%3A6706) from Figma guild
- Info on [auto layout](https://www.figma.com/proto/RQhu2NWQVr1JDaU4mpRuZh/Figma-Exercises?node-id=422%3A2366&scaling=min-zoom&page-id=52%3A6706&starting-point-node-id=422%3A2366)

**Comment by oliviaflory** [comment]
Card section deprecated in v2, no longer need a Figma component
