### ISSUE TITLE
[Innovation Sandbox]: Component registry import conflict

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#8530]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2437
- DPO consulting engineer: N/A

-----

### Description

- This bug issue is related to the overall SOW outlined in this EPIC (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8196).
- When importing components from the Carbon for IBM.com WC package in the [Carbon Innovation Sandbox](https://github.ibm.com/webstandards/carbon-for-ibm-dotcom-innovation-sandbox) project, I noticed that we encountered a component registry issue when the compiled CDN artifact of the new component is used in an application that already has that custom element set in the registry (see attached).

![Screen Shot 2022-03-08 at 3 29 01 PM](https://user-images.githubusercontent.com/1815714/158686781-4f755bde-a443-4ae1-9756-0f989cdaff52.png)

### Current workaround solution
- Right now, I'm just extending components so that the custom element has a different name, however, I'd love to see if there's any way to check and see if certain components have already been registered in the application so that we can avoid this type of conflict.

### Component(s) impacted

N/A

### Carbon for IBM.com version

v1.31.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

Carbon Innovation Sandbox and AEM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/goofy-snyder-ds0d0u?file=/index.html:327-581

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
Despite changing the custom element to `cis-brand-leadspace-image`, which is an extension of `import DDSImage from '@carbon/ibmdotcom-web-components/es/components/image/image';`, I'm still seeing the registry issue within the current WC test app (see attached).

@kennylam @jeffchew Any suggestion on how we can resolve this import/registry issue?

![Screen Shot 2022-03-22 at 11 37 04 AM](https://user-images.githubusercontent.com/1815714/159521161-023fadc7-f088-44b6-94a0-403f62a1ad58.png)

**Comment by jeffchew** [comment]
@proeung was just chatting with @ariellalgilmore , she spotted a tool used in Carbon for IBM.com where it prevents these declarations to happen from Carbon Web Components where we can possibly do the same for the sandbox: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/tools/babel-plugin-undef-custom-elements.js

**Comment by jeffchew** [comment]
@proeung see this configuration, which probably needs to include the `carbon-for-ibm-dotcom` repo in the configuration in rollup:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/tools/get-rollup-config.js#L202-L207

**Comment by proeung** [comment]
@jeffchew Thanks! Will take a look.

**Comment by proeung** [comment]
PR: https://github.ibm.com/webstandards/carbon-for-ibm-dotcom-innovation-sandbox/pull/28

**Comment by proeung** [comment]
Fixed using the existing babel plugin that Akira Sudoh has written to prevent `customElements.define()` in `@carbon/ibm-dotcom-web-components` and `carbon-web-components` modules from running.
