### ISSUE TITLE
Back to Top icon is not functioning on iOS 15.4

### ISSUE THREAD

**Issue by raximkoron** [carbon-design-system/carbon-for-ibm-dotcom#8533]
### Description

When selecting the Back to Top icon, the user should be taken to the top of the page.

When on an iPhone 13 Pro Max on iOS 15.4, selecting the Back to Top icon does not function.

> It should be noted, this works as expected on an iPhone XS Pro on iOS 15.3.1, as well as Android & Desktop browsers

### Component(s) impacted

Back to Top
https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/?path=/story/components-back-to-top--default

https://user-images.githubusercontent.com/2856797/158690427-08d50bfb-9c69-4d1c-a345-b677b44fe518.mov

### Browser

Safari

### Carbon for IBM.com version

1.32.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Cloud

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/?path=/story/components-back-to-top--default

### Steps to reproduce the issue (if applicable)

1. Open Safari on an iPhone running iOS 15.4
2. Navigate to https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/?path=/story/components-back-to-top--default
3. Select canvas tab if necessary
4. Scroll down page
5. Select the Back to Top icon
6. Observe no action takes place

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Re-tested outside of storybook and is working fine 🎉  Closing issue
