### ISSUE TITLE
[Video player]: does not restore focus to video player after playing – React Safari Mobile

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#8535]
### Description

I played the video in content block segmented, it opened in the native player, I navigated to close the video and the focus was brought to the top of the Content block, now I have to navigate down the whole page again 👎 

Expect Focus to be restored to the video player on close

Recording
https://user-images.githubusercontent.com/45692622/158698510-37ceb512-31d0-4113-aab9-07686b8863c3.mov

### Component(s) impacted

tested on Content block segmented

Could impact any component / template that utilizes video player
Confirmed this is the case
- Content block simple
- Content group simple
- Lead space block with video
- etc

### Browser

Safari

### Carbon for IBM.com version

v1.32.0 rc0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

c4IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-content-block-segmented--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
Looking at this, it might not be something we can adjust since the focus is captured within the Kaltura player itself. We wouldn't be able to manipulate the focus from the player
