### ISSUE TITLE
Table of Contents does not scroll through the page on iOS 15.4

### ISSUE THREAD

**Issue by raximkoron** [carbon-design-system/carbon-for-ibm-dotcom#8537]
### Description

When viewing the Table of Contents web component on an iPhone 13 Pro Max on iOS 15.4, selecting any listing does not scroll the browser to the appropriate section. No action takes place.

> Important to note: This functionality appears to work correctly on an iPhone 8+ on iOS 15.0.1, Android & Desktop browser

https://user-images.githubusercontent.com/2856797/158703699-5aa8d5f3-3650-4dd4-af91-eddc88190cec.mov

### Component(s) impacted

Table of Contents - Default
Table of Contents - Horizontal

### Browser

Safari

### Carbon for IBM.com version

1.32.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Cloud

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/?path=/story/components-table-of-contents--default

### Steps to reproduce the issue (if applicable)

1. Open Safari on an iPhone running iOS 15.4
2. Navigate to https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/?path=/story/components-table-of-contents--default
3. Select canvas tab if necessary
4. Tap the menu icon and select "Client success stories"
5. Observe menu is dismissed, but user is not scrolled to the "Client success stories" section of the page

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Re-tested and works fine when opened in a new tab (outside of storybook canvas)
