### ISSUE TITLE
[Figma] CTA Section/Block

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#8548]
**Should this be split into two with a dependency on one?**

Add the CTA section component to Figma kit. Remember we are only building variants for `xlg`, `md`, and `sm`. 

[Design spec](https://ibm.ent.box.com/folder/109648616047)
[Website](https://www.ibm.com/standards/carbon/components/cta-block-and-section/)

**Pre-work:** Do we need a separate `CTA block` story for Figma? Plan was to combine these in code.

**Must haves:**
- [ ] Content should be flexible - the designer should be able to condense or stretch the component and the content should respond. Removing text for example should maintain the right padding automatically through auto layout.
- [ ] This component uses a fluid type token for the heading. If this is not created already, create a base to help swap the header type based on breakpoint size. See `Content group` in the library. This should be tested with for `Cards`.
- [ ] Variant for single button and button group. Use the `Expressive button` and `Button group` existing Figma components.
- [ ] Variant toggle for border at the bottom
- [ ] Variants for Default, with Content item, and with Link list
- [ ] Variants to toggle Heading on and off, Copy on and off, and Expressive button on and off.

![Screen Shot 2022-06-11 at 11.49.45 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/442afb1a-edfa-42cd-a8e4-5f89cde44487)

![Screen Shot 2022-06-11 at 11.48.48 AM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/d495aa9c-7c93-4f6f-9502-0bbfe8ce67ae
)

**Resources**
- C4IBM.com Component checklist is available in the Read Me 👀 page of the Figma library
- [Bases demo](https://secure.video.ibm.com/channel/23570833/playlist/641336/video/131117161) from the Figma Fridays (Episode 23)
- Reference the [best practices](https://www.figma.com/file/8n9IJtHnICSydODoYl4ueW/Figma-Best-Practices?node-id=52%3A6706) from Figma guild
- Info on [auto layout](https://www.figma.com/proto/RQhu2NWQVr1JDaU4mpRuZh/Figma-Exercises?node-id=422%3A2366&scaling=min-zoom&page-id=52%3A6706&starting-point-node-id=422%3A2366)

**Comment by oliviaflory** [comment]
See Figma board for details
