### ISSUE TITLE
(Web Components) Images not rendering for Content Block Cards and Card Link on Example Page C

### ISSUE THREAD

**Issue by QALosey** [carbon-design-system/carbon-for-ibm-dotcom#8569]
### Description

Expected: 
Images for Content Block Cards and Card Link will render in Example Page C.

Actual:
Images not rendering for Content Block Cards and Card Link on Example Page C.

### Component(s) impacted

Content Block Cards and Card Link
https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/example-page-c/index.html
![Example Page C - Cards   Card Link](https://user-images.githubusercontent.com/57540897/159036188-70ca8a3c-d579-4c08-beac-b182b014548a.jpg)

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v1.32.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/

### Steps to reproduce the issue (if applicable)

1. Navigate to https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/ on any platform
2. Use the Table of Contents to navigate down to the Content Block Cards and Card Link section
3. Observe that images are not rendering

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Consolidating in favor of #8570
