### ISSUE TITLE
(Web Components) Image not rendering for Content Block - Segmented on the Cloud example page

### ISSUE THREAD

**Issue by QALosey** [carbon-design-system/carbon-for-ibm-dotcom#8571]
### Description

Expected:
Images will render for Content Block - Segmented on the Cloud example page.

Actual:
Images not rendering for the Content Block - Segmented section in the Cloud example page.

### Component(s) impacted

Content Block - Segmented
https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/cloud/index.html
![Example Cloud - Segmented](https://user-images.githubusercontent.com/57540897/159038971-2f33dbe5-ee35-449a-b8d3-3390e6a2502b.png)

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v1.32.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/

### Steps to reproduce the issue (if applicable)

1. Navigate to https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/cloud/index.html
2. Use the Table of Contents to navigate to the Content Block - Segmented section
3. Observe that images are not rendering

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Carbon-for-IBMcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/8571?planning-poker) with ZenHub @annawen1 @ariellalgilmore @emyarod @IgnacioBecerra @kennylam

**Comment by oliviaflory** [comment]
Consolidating Cloud example page to #8572
