### ISSUE TITLE
(Web Components) Images not rendering for the Card Section with Images on the Cloud example page

### ISSUE THREAD

**Issue by QALosey** [carbon-design-system/carbon-for-ibm-dotcom#8573]
### Description

Expected:
Images will render for the Card Section with Images on the Cloud example page.

Actual:
Images not rendering for the Card Section with Images section in the Cloud example page.

### Component(s) impacted

Card Section with Images
https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/cloud/index.html
![Example Cloud - Feature Card    Card Section](https://user-images.githubusercontent.com/57540897/159040528-09f80806-a61e-4c1b-9b71-a387138ada3c.png)

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v1.32.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/

### Steps to reproduce the issue (if applicable)

1. Navigate to https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/next/cloud/index.html
2. Scroll to the bottom of the page
3. Observe that images are not rendering

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Closing in favor of consolidating in #8572
