### ISSUE TITLE
[Locale modal]: VO stuck on close button

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#8574]
### Description

User gets stuck on the `close modal button` when closing the locale selector (not selecting a different country/language). 

I couldn't figure out a work around, but does anyone else know if there might be one in a gesture I am not familiar with ?

Workaround = "tap" anywhere else on the screen. Issue being that a user with no, or poor vision may not know where on the screen to tap and then needs to reorient themselves after they tap.

**Update**
Happened on Locale modal and expressive modal
Did not happen in image with caption using lightbox media viewer in storybook 

https://user-images.githubusercontent.com/45692622/159060673-6a3752d1-2b8d-489c-ac44-772e049ffbb4.mov

*Tested on dotcom shell*

### Component(s) impacted

Locale modal 
Lightbox media viewer
Video w lightbox media viewer
Expressive modal?

### Browser

Safari

### Carbon for IBM.com version

v1.32.0 rc 1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

carb4ibm.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-dotcom-shell--micro-footer

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Check Carbon upgrade to see if upgrade introduced focus trapping in modal in v10.55 @annawen1

**Comment by oliviaflory** [comment]
@oliviaflory is checking if present in all modals (expressive, etc)

**Comment by annawen1** [comment]
Update from Olivia: this bug happening in locale modal, expressive modal, but _not_ present in lightbox media viewer image with caption story.

This issue will require an upstream fix from Carbon Core, the `onBlur` event in `ComposedModal` is causing issues when I try to set the focus back to the trigger button on modal close.

I've opened an issue with Carbon team here: https://github.com/carbon-design-system/carbon/issues/11059

**Comment by annawen1** [comment]
PR to merge fix into carbon `v10` branch here: https://github.com/carbon-design-system/carbon/pull/11418
