### ISSUE TITLE
[Masthead]: VO stuck inside Login menu

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#8575]
### Description

If the user opens the Login menu, they cannot close the menu. I was able to get out of the menu but am brought to the bottom of the page into the footer and the menu is open on top. Or you are trapped within the menu and need to tap anywhere else on the screen to get out.

Additionally in JAWS, when the login menu is closed, menu items are still announced by screen reader.

.

https://user-images.githubusercontent.com/45692622/160433243-b47f21ba-c822-42e4-80c9-13bfaecd4638.MP4

### Component(s) impacted

Masthead

### Browser

Safari

### Carbon for IBM.com version

v1.32.0 rc1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

carb4IBM.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/react/?path=/story/components-dotcom-shell--with-l-1

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Need to bring up with Carbon about overflow menu @annawen1

**Comment by annawen1** [comment]
Opened a A11y bug ticket with Carbon here: https://github.com/carbon-design-system/carbon/issues/11083

**Comment by oliviaflory** [comment]
@kennylam will talk with Taylor about this issue and how Carbon is moving forward with bugs in v10
