### ISSUE TITLE
Locale change banner update

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#859]
### User story
As a user of IBM.com, I would like to know when I am forwarded to a page that has a different locale setting than my preferences or the previous pages.

### Notes
- This story is based on SEO's recommendation to not use the popup for locale change.
- The existing banner design seems to be problematic in that users either miss it or are not helped by it.

**Comment by kathysaraf** [comment]
Draft of functional spec ready for review: https://ibm.ent.box.com/folder/113158587587 Please note there may be changes pending results of user testing.

**Comment by RobertaJHahn** [comment]
@kathysaraf You have created the functional specs. Do the specs include the Locale banner version that was developed?

**Comment by RobertaJHahn** [comment]
Design work is being managed on the Ideation Board in this epic:  https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/26

**Comment by RobertaJHahn** [comment]
Closing as all linked issues are closed.
