### ISSUE TITLE
[Sandbox]: Adjust Brand Leadspace action slot to align with usage on the AEM side 

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#8607]
### User story

> As a `[user role below]`:

> I need to:

> so that I can:

### Additional information

- This is a follow-up ticket to the Brand Leadspace component - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8227
- AEM folks are in the midst of integrating the Brand Leadspace component (see [link](https://pages.github.ibm.com/webstandards/carbon-for-ibm-dotcom-innovation-sandbox/canary/index.html?path=/story/components-brand-leadspace--default)), however, they're experiencing an issue using a single `<dds-video-cta-container>` as a mean to house multiple video CTAs.
- Therefore, they're having to mange the markup of the leadspace CTA using a combination of `cis-brand-leadspace-cta` and `dds-video-cta-container`

```
<cis-brand-leadspace-cta slot="action" cta-type="external" href="https://www.example.com/">What is cloud next leap?</cis-brand-leadspace-cta>
<dds-video-cta-container slot="action">
   <cis-brand-leadspace-cta cta-type="video" href="1_9h94wo6b">Why Cloud without Compromise (7:24)</cis-brand-leadspace-cta>
</dds-video-cta-container>
```

### Acceptance criteria

- [ ] Ensure that each CTA item still gets the proper animation delays.
- [ ] If there are more than one CTAs ensure that there are proper spacing.

**Comment by IgnacioBecerra** [comment]
PR: https://github.ibm.com/webstandards/carbon-for-aem/pull/34
