### ISSUE TITLE
[Plex CDN]: not all font families included in some CDN builds

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#8661]
### Description

Certain font-families are excluded in CDN builds, specifically, the most commonly used
```
https://1.www.s81c.com/common/carbon-for-ibm-dotcom/tag/v1/latest/plex.css
```

This results in glyphs rendering incorrectly in certain browsers (looking at you, Safari). A temporary workaround is to import additional font families that aren't present in `plex.css`. See #8498.

### Component(s) impacted

Any component that uses text.

### Browser

Safari

### Carbon for IBM.com version

v1.32.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

Carbon for IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/xenodochial-chandrasekhar-75cn7m

### Steps to reproduce the issue (if applicable)

On any page using only `https://1.www.s81c.com/common/carbon-for-ibm-dotcom/tag/v1/latest/plex.css` for font styling, the `↷` character will render incorrectly since the glyph is missing in the stylesheet.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
This is the file used to generate the plex CDN artifact:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/globals/scss/plex.scss

**Comment by kennylam** [comment]
Can compare with generated scss files from https://github.com/ibm/plex build process.

**Comment by oliviaflory** [comment]
Update documentation to instruct user to use direct font sources and not rely on Carbon.
