### ISSUE TITLE
Masthead search is intermittently unusable on the US home page in Android + Chrome

### ISSUE THREAD

**Issue by ncheaz** [carbon-design-system/carbon-for-ibm-dotcom#8663]
### Description

I am seeing an intermittent problem with the masthead search in Chrome + Android.  Not sure if it's a known issue.  It happens on the US [ibm.com](http://ibm.com/) home page, and some others.

The symptom is that when I put the cursor on the search field, the keyboard popup up, but then hides immediately, and does it repeatedly.  For some it is intermittent, for me it happens very consistently

### Component(s) impacted

Masthead search field component

### Browser

Chrome

### Carbon for IBM.com version

latest

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

US Home page: https://www.ibm.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

N/A

### Steps to reproduce the issue (if applicable)

Have an Android phone/tablet/Browserstack
Open https://www.ibm.com in Chrome
Go to the masthead search and put the cursor in the search field

You will see the keyboard popup, the masthead widget seems to a quick refresh which hides the keyboard, and the immediately the keyboard pops up again <== This cycle repeats a number of times, and some users see a lot more cycles than others (I get 30 keyboard popup cycles before it stops and I can use the search)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ariellalgilmore** [comment]
![Screen Shot 2022-04-01 at 8.15.48 AM.png](https://images.zenhubusercontent.com/5ee7ae1cc40147132b286905/f3fcbc00-a8a2-4751-bb5f-a98a171f1591)
