### ISSUE TITLE
No API for retrieving user coutry code per IP

### ISSUE THREAD

**Issue by jcgonzal** [carbon-design-system/carbon-for-ibm-dotcom#8678]
### The problem

Hello tea,

Could you please help me to create an API for javascript and html only to retrieve the user country code base on the IP which is detected when user opens a form, for example, something like this option that only works for v18 IBMCore.common.util.user.getInfo()country, but it uses this(IBMCore.common.util.user.getInfo().country) script which when I implement, it breaks the dropdown.

### The solution

I would like to have an api or function to retrieve the user country code base on the IP detected in the users machine.

### Application/website

IBM Systems Primary Web

### Business priority

High Priority = pressing release

### What time frame would this ideally be needed by (if applicable)

One or two days 

### Examples

This function retrieves the country user base on IP: IBMCore.common.util.user.getInfo().country;, and here there is a form that when is loaded the country code is automatically loaded:
https://www.ibm.com/it-infrastructure/us-en/resources/campaignmail/mail/ibmhr/

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment]
@jcgonzal I wonder if you could please check in with the URX team.  They do country lookup for setting the country field on the form.  Their slack channel is #urx-questions

**Comment by kennylam** [comment]
Issue resolved by manually including utility on client-side.
