### ISSUE TITLE
Tabs Extended media containing a Title heading section

### ISSUE THREAD

**Issue by pscheufens** [carbon-design-system/carbon-for-ibm-dotcom#8691]
### The problem

We are using Tabs Extended Media now instead of Tabs Extended and noticed that in the Media version there is another div for a title element causing spacing issues. But this is not the case for Tabs Extended. 
Codebox shows the behaviour where the bx--heading resides inside the dds-tabs-extended-media. And we only have this tag in our markup. Changing it to dds-tabs-extended removes the heading area in the shadow root but we lose media support for all viewports.

### The solution

Would it possible to get rid of this bx--heading div? Since it resides inside the shadow root we cannot access it with css or markup. 

### Application/website

AEM

### Business priority

Medium Priority = upcoming release but is not pressing

### Examples

![screenshot_spacing](https://user-images.githubusercontent.com/29569154/162508110-b727e5e2-c7c1-4457-8754-6eff543b4cfc.png)
![screenshot_spacing2](https://user-images.githubusercontent.com/29569154/162508128-5fb1d97c-34ef-4c21-97ed-da67275de79c.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@RichKummer Once you have determined the solution from the design side, please go ahead and assign this issue to my queue so that we can plan for this work in the next sprint.

**Comment by oliviaflory** [comment]
@pscheufens Could you share the design you are working from?

I'd be happy to make the heading optional and keep the existing grid alignment. This would allow the use of the Horizontal table of contents in that first four columns, and ensure the tabs extended is aligned to any other Carbon for iBM.com components used on the page.

However I would not advise the Tabs extended to span the full 16 columns of the grid and would like to review the overall design if that is the case.

**Comment by EAVilleda** [comment]
@oliviaflory We don't need the Tabs extended with media to extend the full 16 columns. We want it to be the same as Tabs extended.
https://www.ibm.com/standards/carbon/web-components/?path=/story/components-tabs-extended--default
https://www.ibm.com/standards/carbon/web-components/?path=/story/components-tabs-extended-with-media--default

It doesn't make sense for us that Tabs extended with media has its own header on the left, since we are adding the component to a container that already has a header.

**Comment by proeung** [comment]
AEM JIRA Ticket - https://jsw.ibm.com/browse/ADCMS-2137

**Comment by EAVilleda** [comment]
Hello! This ticket has not been assigned to anyone, and we have had this issue opened since March. Is there another ticket I should be looking at? @kennylam @proeung

**Comment by proeung** [comment]
@EAVilleda The last I've heard of this ticket is that the DPO design team would like to have to follow-up discussion from the design side of why this heading area needed to be optionally hidden. @jwitkowski79 This feels like another follow-up ticket to visit in your next office hour call alongside (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8826).

**Comment by kennylam** [comment]
@EAVilleda @proeung We actually plan on merging the two `tabs-extended-` components into one, with an optional title heading section. Design has done a review of the component and it'll be added to next sprint's pipeline.

cc: @oliviaflory

**Comment by EAVilleda** [comment]
> @EAVilleda @proeung We actually plan on merging the two `tabs-extended-` components into one, with an optional title heading section. Design has done a review of the component and it'll be added to next sprint's pipeline.
> 
> cc: @oliviaflory

My only concern with this is that we would never use the heading section because we are adding the component inside of a content section that already has its own title heading section. Does it have to include the heading section?

**Comment by oliviaflory** [comment]
> My only concern with this is that we would never use the heading section because we are adding the component inside of a content section that already has its own title heading section. Does it have to include the heading section?

@EAVilleda our strategy for combining the `tabs-extended` and `tabs-extended with media` is to allow more flexibility for all teams adopting Carbon for IBM.com.

Including the section title as optional will allow all of our adopter teams to decide how to apply headings, turning it off should allow AEM to place it within a content section that has another heading, such as a Content block.

Rough example of what we are thinking:
- Top (teal) is tabs extended with media with the section title turned off.
- Bottom (pink + teal) is the tabs extended with media and 
![Screen Shot 2022-07-25 at 10 33 29 AM](https://user-images.githubusercontent.com/45692622/180803355-cf8c4e9c-21dc-4e9c-83c9-4097477baa5c.png)

**Comment by oliviaflory** [comment]
Link to [Figma specs](https://www.figma.com/file/lytaUn8Jn9OckMolZmdXRQ/Audit-Content-Block-%26-Section?node-id=112%3A157)
