### ISSUE TITLE
[MASTHEAD]: New hover icon sliding for the Search (outside and inside)

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#8696]
### Description

https://user-images.githubusercontent.com/48327647/162763937-dbc51e48-1a68-42f0-a0a7-c4e4403a2924.mov

https://user-images.githubusercontent.com/48327647/162763945-780a59ae-4d56-4edf-aa0c-ab353ffd2b4f.mov

### Hey team,

I see you introduced an icon slide to the right on search (hover). I was wondering if the fact that you got another visual cue of the hover state (besides the background color change) that will only be visible on the desktop, won't make the audience think that one of the 2 is a bug: either the search or the user icon, which doesn't slide. And also when the search is open, the sliding seems opposite – for the search icon and the close icon – because there is no neutral space between the two (although visually it looks like there is). 

I understand that the icon sliding follows the button with icon animation, but maybe the masthead icon buttons should be treated as a different case: here the hover background-color change is very visible, so maybe you don't need another visual cue of the hover state. Or maybe you shouldn't apply it on the search button when the search is closed.

### Component(s) impacted

Masthead

### Browser

Chrome

### Carbon for IBM.com version

latest

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

https://www.ibm.com/us-en/

### Package

@carbon/ibmdotcom-react, @carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

https://www.ibm.com/us-en/

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@DragosRistici Looks like this is an issue on that specific page, i.e. an authoring issue.
