### ISSUE TITLE
CDN Includes don't provide the proper styles for the dds-footer-container language selector

### ISSUE THREAD

**Issue by SeanDKendle** [carbon-design-system/carbon-for-ibm-dotcom#8706]
### Description

Footer language selector should be properly styled when importing from CDN.

The language choices aren't styled properly

### Component(s) impacted

dds-footer-container

### Browser

Chrome, Firefox

### Carbon for IBM.com version

latest

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

www.ibm.com/community/z-and-cloud

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/amazing-morning-98rj0u?file=/index.html:173-940

### Steps to reproduce the issue (if applicable)

```
<!--
@license

Copyright IBM Corp. 2020

This source code is licensed under the Apache-2.0 license found in the
LICENSE file in the root directory of this source tree.
-->

<html>
  <head>
    <title>@carbon/ibmdotcom-web-components example</title>
    <meta charset="UTF-8" />
    <link
      rel="stylesheet"
      href="https://1.www.s81c.com/common/carbon-for-ibm-dotcom/tag/v1/latest/plex.css"
    />

    <script
      type="module"
      src="https://1.www.s81c.com/common/carbon-for-ibm-dotcom/version/v1.17.1/footer.min.js"
    ></script>
  </head>
  <body>
    <div style="padding-top: 100px;"></div>
    <dds-footer-container> </dds-footer-container>
    <script>
      const languageList = ["English", "Japanese / 日本語"];
      document.querySelector("dds-footer-container").langList = languageList;
      document.querySelector("dds-footer-container").selectedLanguage =
        languageList[1];
    </script>
  </body>
</html>

```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by SeanDKendle** [comment]
(you have to make the example larger to see the desktop version)

**Comment by SeanDKendle** [comment]
Workaround from Ariella Gilmore is to also include combo-box.min.js:

`<script type="module" src="https://1.www.s81c.com/common/carbon/web-components/tag/latest/combo-box.min.js"></script>`

**Comment by oliviaflory** [comment]
Double check the footer web component to ensure all the imports are included
