### ISSUE TITLE
Option to open dropdown items in masthead in a new tab

### ISSUE THREAD

**Issue by chrsfshr** [carbon-design-system/carbon-for-ibm-dotcom#8712]
### The problem

In our nav under "Docs" all those are external links from the site. So we would like to have those open in a new tab which fits how we are handling all external links throughout the site.

https://www.ibm.com/quantum-computing

### The solution

Ability to add external or target "blank" to Nav links.

### Application/website

https://www.ibm.com/quantum-computing

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

As soon as possible. So that we are consistent with our link patterns across the site. But it is not a blocker or pressing.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
@chrsfshr thanks for the feature request. 

This is a bit unusual, generally we have external sites as part of the IBM navigation. And navigation shouldn't open in a new tab. In a similar scenario, the IBM Cloud navigation opens the Cloud console in the same tab. I'm going to ask someone from the IA guild to weigh in on this as well!
