### ISSUE TITLE
Brand expression test page spec

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#8740]
Follow on issue from #8586

Create a spec for the test page we want to create to demo the Brand changes to the Carbon for IBM.com components

**Additional information**
- use one of the lever pages 
- note spacing changes and type changes

**Acceptance criteria**
- Spec created
- Spec available for dev

**Comment by ljcarot** [comment]
@oliviaflory can we close this?
