### ISSUE TITLE
[ui-shell]: standalone links A11y - Hyperlink has no link text, label or image with a text alternative

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#8759]
### Description

Web components `header-nav-item` links that do not have child menus require an `aria-label`.

![image](https://user-images.githubusercontent.com/909118/165784883-9cc5edec-d70e-425a-bffc-e992c1b8262b.png)

### Component(s) impacted

`ui-shell`

### Browser

Chrome

### Carbon for IBM.com version

v1.21.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Carbon for IBM.com

### Package

@carbon/carbon-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-masthead--default

### Steps to reproduce the issue (if applicable)

Go to site provided. Run IBM Equal Access checker

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
This issue appears to no longer exist.

<img width="1440" alt="Screenshot 2022-12-22 at 12 53 47 PM" src="https://user-images.githubusercontent.com/25532785/209196423-890023d8-e5bb-4c3f-aa66-91c0bacad640.png">
