### ISSUE TITLE
[Dependencies]: Potential vulnerability detected in `axios`

### ISSUE THREAD

**Issue by ajohar1** [carbon-design-system/carbon-for-ibm-dotcom#8786]
Hello, I'm an IBM employee and we use Carbon for ibm.com for one of our internal applications. 

We have Whitesouce set up on our GitHub repo and it found a reported vulnerability with axios 0.21.4. This appears to be a dependency of one of the Carbon for ibm.com packages. Is this a known issue and if so, is there an update planned?

**Comment by kennylam** [comment]
Hi @ajohar1, yes, expect `axios` to be updated soon, probably in the next release. We are slowly upgrading all our dependencies and that one is on the list.
