### ISSUE TITLE
[Storybook]: Proposal for Storybook Controls

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#8791]
### User story

> As a `[user role below]`:

Designer

> I need to:

propose storybook control labels, inputs, toggles

> so that I can:

help devs with new controls in storybook 6 that make sense for all users (designers & developers).

### Additional information

- Rich has done some explorations already, review with Olivia & Jeannie
- Add any additional explorations / naming / labels 
- _{{user metrics}}_

### Acceptance criteria

- [ ] Review with stakeholders (devs, designers)
- [ ] All scenarios accounted for and documented
- [ ] Figma file shared with devs for follow on issues

**Comment by RichKummer** [comment]
https://www.figma.com/file/SwulGh25Jlqefxz2e3Fzdb/Storybook-Controls?node-id=0%3A1
