### ISSUE TITLE
[leadspace-block]: allow `expressive-heading-06` to be optional

### ISSUE THREAD

**Issue by heyhilary** [carbon-design-system/carbon-for-ibm-dotcom#8802]
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2495
- DPO consulting engineer: N/A

-----

### The problem

For the AEM version of this component, we will be allowing the expressive heading 05 as the only headline and not requiring the expressive heading 06 as well. This aligns more closely with the new branding. NOTE: I submitted a bug ticket to add the Paragraph text edit knob in Storybook. (It's currently missing)

![Leadspace-search-mod](https://user-images.githubusercontent.com/87664492/166973230-206251a5-a7ab-4763-91e0-4b5cba71ddc7.png)

### The solution

See above. 

### Application/website

Interfaces Team - AEM Templates

### Business priority

High Priority = pressing release

### What time frame would this ideally be needed by (if applicable)

This Integrations Catalog template will be launching with the Watson Orchestrate pages in June. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jkaeser** [comment]
Hi there, @heyhilary! It looks like this feature has already been implemented. You can remove the value from the **Heading** field in the Knobs section on https://www.ibm.com/standards/carbon/web-components/?path=/story/components-lead-space-search--default to see this in action.

<img width="1280" alt="Screen Shot 2022-06-27 at 2 07 30 PM" src="https://user-images.githubusercontent.com/12532727/176007470-d07e66a4-dd27-4b33-a48d-2ef04d6425d7.png">

Am I misunderstanding your request? If not, are you okay with me closing this ticket?

**Comment by proeung** [comment]
Closing this issue out as no further action is needed. @heyhilary Feel free to reach out to us if any of your AEM devs have questions about the ingestion work for this component within the AEM CMS.
