### ISSUE TITLE
[Tabs-Extended with CTA Section]: Text display issue in CTA Section nested in Tabs

### ISSUE THREAD

**Issue by EAVilleda** [carbon-design-system/carbon-for-ibm-dotcom#8820]
**Engineering info:**  
- Innovation Team engineer: @jkaeser 
- Innovation Team JIRA Tickets: https://jsw.ibm.com/browse/ADCMS-2305 & https://jsw.ibm.com/browse/HC-2474
- DPO consulting engineer: @annawen1 

-----

### Description

Authors have reported a strange issue occurring in CTA Section when it’s in Tabs. When switching between the tabs, the text in cta section sometimes overlays on a single line. This can be seen here, in the “Databases for any use case” section: https://prod-publish.roks.cms.cis.ibm.net/analytics/database-management
It tends to happen on the Document tab more often, when switching between tabs.

### Component(s) impacted

CTA Section Row in Tabs

### Browser

Chrome

### Carbon for IBM.com version

v1.30.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM (Marketing)

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

No codesandbox avaiable

### Steps to reproduce the issue (if applicable)

- Visit - https://prod-publish.roks.cms.cis.ibm.net/analytics/database-management
- Scroll down to the "Databases for any use case" section.

![Screen Shot 2022-05-12 at 10 46 40 AM](https://user-images.githubusercontent.com/1815714/168103082-480479f1-9c83-4e0a-9f71-761e2c2bd1fe.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
It looks like the `height` is being dynamically set on the `content-item`s, and is set every time the tab content comes into view. I would check to see if `sameHeight` utility is being used in this instance.

**Comment by jkaeser** [comment]
The relevant DOM tree on this page looks like this:
`DDSTabsExtended` > `DDSTab` > `DDSTabsExtended` > `DDSTab` > `DDSCTABlockItemRow`

Two more relevant things to note:
1. `DDSCTABlockItemRow`, the last element noted, uses the `sameHeight` utility on its child elements when it is first mounted.
2. Elements with the `hidden` attribute and their children have heights of `0` as far as the browser is concerned.

In this case, the block item row is mounted within an unselected tab, which has the `hidden` attribute, so the `sameHeight` utility is giving each of the observed elements height of `0px`.
