### ISSUE TITLE
[masthead]: profile menu not working in `with platform` variant

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#8845]
### Description

The profile menu does not expand when clicking in the `masthead - with platform` version.

![May-16-2022 08-53-45](https://user-images.githubusercontent.com/909118/168597212-b46478e5-412c-4696-ac9e-bc6ec8ffcf18.gif)

### Component(s) impacted

[`masthead - with platform`](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-masthead--with-platform)

### Browser

Chrome

### Carbon for IBM.com version

v1.34.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

Carbon for IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/?path=/story/components-masthead--with-platform

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment]
@kennylam is this something we need to patch?
