### ISSUE TITLE
[CTA Section with Content Items]: Expose new image ratios

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#8849]
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2475
- DPO consulting engineer:

-----

### The problem

- This "Layout Component" is part of the Product Use Cases v1 Template (see EPIC - [AEMSITES-94](https://jsw.ibm.com/browse/AEMSITES-94))
- These changes from coming from the Interfaces Team (cc: @jwitkowski79)
- Design Specs
   - PDF: https://ibm.ent.box.com/file/958328867245?s=296kh5b2y5pe3mlbad7y2kdiny46k713
   - Figma: https://www.figma.com/file/0qjKUHD652dqE9BdjId9YY/Templates?node-id=1130%3A29863

![Screen Shot 2022-05-16 at 11 24 21 AM](https://user-images.githubusercontent.com/1815714/168628175-ee8387bd-d116-4383-b606-fb3933727187.png)

### The solution

- Add an attribute/prop (eg. `logo-ratio`) for the different image ratios that we're supporting. The container of the logo item should be adjusted based on the defined ratio (see specs).
- Add "logo" to the SB content type knob

@oliviaflory @kennylam Feel free to add/adjust this solution area.

### Application/website

AEM

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

We'd like to get these modifications in for the v.1.35.0 release.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Thanks @proeung! For the content item type will it say "Logo" ?  Thinking "Logo" fits in well with the other type descriptions we have. 

![Screen Shot 2022-05-16 at 12 57 00 PM](https://user-images.githubusercontent.com/45692622/168644834-42ffe49b-be7d-4789-a155-199f3a113d45.png)

**Comment by proeung** [comment]
@oliviaflory Sounds good! I just added "Logo" to the Solution area as one of the content types dropdown knob.

**Comment by IgnacioBecerra** [comment]
@Gopi916 Staging storybook was slightly outdated -- the Logo option should now be testable on staging.
