### ISSUE TITLE
[Footer]: QA: By default gray theme is getting applied to the component

### ISSUE THREAD

**Issue by Gopi916** [carbon-design-system/carbon-for-ibm-dotcom#8872]
### Summary

Issue:
By default gray theme is getting applied to the component and not able to change the theme in knob section.

Is this the expected?

![image](https://user-images.githubusercontent.com/61313055/169010902-43f0050a-f93a-4cb1-9d12-74721abd97f1.png)

### Name and organization

Name: Gopinathan
Organization: IBM

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@Gopi916 The `footer` is only available in the theme shown. We'll remove the `theme` tab in Storybook to avoid confusion.
