### ISSUE TITLE
[Add a 10 column image to content block media]: Add an option to expand the image to 10 columns in content blocks that support imagery

### ISSUE THREAD

**Issue by jwitkowski79** [carbon-design-system/carbon-for-ibm-dotcom#8892]
### Contribution type

Components

### Intent

While working through template design options in AEM, we've identified a need to have an option to expand the size of the image that displays within a content block from 8 column to 10 columns. The reasoning is that we often follow a content block with a content block horizontal with media and the image alignment is off. We also want the option to present detailed screenshots of products within the content block and would like the imagery to be displayed larger to show more detail. We know that we could utilize a lightbox to increase the sizing, but this does not solve the issue with the misalignment when stacking a content block horizontal with media. Below is a screenshot of the misalignment issue that we're running into. 

![MVE1 - Use cases - individual](https://user-images.githubusercontent.com/2040791/169574089-1850a736-3812-4cdf-b314-36f311574746.png)

### Solution

Our solution is to include an option to increase the size of the image that displays within a content block to 10 columns. We've  been working with @oliviaflory AND @jeanservaas on this request. There's some concern that introducing a 10 column image could introduce some misalignment with other types of component stacks, and that the brand team generally discourages a 10 column layout because of alignment issues that can take place. This approach is still in review and discussion. 

Below is a screenshot of the solution
![MVE1 - Use cases - individual- WO](https://user-images.githubusercontent.com/2040791/169574488-28d9da90-e2aa-4152-8190-7f14eb84e143.png)

### IBM Organization or Company you are part of

Interfaces Team: Our design teams main goal is to design, support and to create processes for templates in AEM for ibm.com

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
Marking this design contribution issue as cancelled since the team has decided not to move forward with this work.

cc: @jwitkowski79 @oliviaflory
