### ISSUE TITLE
[Test Scenario]: CTA Block Item Rows within Tabs Extended

### ISSUE THREAD

**Issue by jkaeser** [carbon-design-system/carbon-for-ibm-dotcom#8901]
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2479
- DPO consulting engineer: N/A

-----

### Background
#8820 revealed an issue where elements that leverage the `sameHeight` utility but are initially rendered in an element that has the `hidden` attribute are given a `0px` height. The specific scenario under which this occurred was with markup like the following:
```
<dds-tabs-extended>
  <dds-tab label="First tab">
    <dds-cta-block>
      <dds-cta-block-item-row>
        <dds-cta-block-item>
          ...
        </dds-cta-block-item>
      </dds-cta-block-item-row>
    </dds-cta-block>
  </dds-tab>
  ...
</dds-tabs-extended>
```

#8881 fixes the issue, but there is not currently a place to write tests for the scenario. However, this seems like the type of thing that warrants automated test coverage.

### Component and test scenario title

CTA Block – When rendered inside Tabs Extended, CTA Block Items within CTA Block Item Rows should have equal heights.

### Test scenario steps

1. Given a `DDSCTABlock` is placed within a `DDSTabsExtended` element
2. And a `DDSCTABlockItemRow` is placed within it,
3. And that row has one or multiple `DDSCTABlockItem` children
4. Then those children should have equal heights
5. And their heights should not equal `0px`.

**Comment by jkaeser** [comment]
As alluded to in the issue description, I'm not sure where such a test might live. Does anyone have any thoughts? Is this something we want to have test coverage for?

**Comment by proeung** [comment]
@jkaeser Thanks for opening this issue!

> As alluded to in the issue description, I'm not sure where such a test might live. Does anyone have any thoughts? Is this something we want to have test coverage for?

This is a tricky one because the test could live in either the `CTA Block` or `Tab Extended`. @kennylam I'll defer to you on this. Let us know where you would like the test to live.

**Comment by proeung** [comment]
@kennylam @annawen1 or @oliviaflory Any thought regarding my comment above? ^

**Comment by annawen1** [comment]
hmm I'm thinking we can put the test case in `CTA Block`? That seems to be the most relevant to me

**Comment by jkaeser** [comment]
@proeung I believe that's all I needed. I'll create another Story in `CTA Block` as the testable surface for this scenario. Thanks, all!
