### ISSUE TITLE
[lightbox-media-viewer - with carousel]: QA: Keyboard navigation in the Slides of the page

### ISSUE THREAD

**Issue by Gopi916** [carbon-design-system/carbon-for-ibm-dotcom#8909]
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2518
- DPO consulting engineer: N/A

-----

### Description

Page Element:
Slides in the page.

Issue Description:
When user navigates in the page, all the interactive elements are receiving keyboard focus. For eg., after the video content in the first slide, on pressing tab slide gets changed automatically and scrollable content in the second slide is receiving keyboard focus.

Expected:
Navigation should happen only in the interactive elements in the currently visible slide.
 For eg., focus should navigate in the below order in first slide.
1. Close button
2. Video
3. Next button
4. Again it should loop back to 'Close' button.
Reverse order should happen with shift + tab.

User Impact:
When the slides gets automatically changed and all the contents in different slides are navigated in the same flow, user who are motor impairments and user who uses screen reader will face difficulty in understanding the flow of the application.

### Component(s) impacted

lightbox-media-viewer - with carousel

### Browser

Firefox

### Carbon for IBM.com version

canary

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Carbon for IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/8757/iframe.html?id=components-lightbox-media-viewer--with-carousel

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
@proeung 
I'm able to replicate the issue on the link provided, but not on the canary version. This will also impact #8916 and #8910

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/iframe.html?id=components-lightbox-media-viewer--with-carousel

**Comment by oliviaflory** [comment]
Not stale, issue in review process

**Comment by proeung** [comment]
Closing out this issue as it has been addressed in this PR (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9004). Feel free to reopen if the issue still persists.
