### ISSUE TITLE
[Masthead customProfileLogin]: after log in icon does not change to logout

### ISSUE THREAD

**Issue by Stefan8412** [carbon-design-system/carbon-for-ibm-dotcom#8944]
### Description

we are trying to use customProfileLogin in our app but after log in icon should change to log out, similiar like before . Should we do something on our side or you you can do it  on your side to react on our "custom login". i have attached our MastheadProfile
![Screenshot 2022-06-01 at 16 29 04](https://user-images.githubusercontent.com/57751227/171661611-f685fa1b-756b-4835-be72-f1a0f72c1c16.png)

our dev enviroment where you can check that icon is not changed : https://ibmdocs-dev.mybluemix.net/docs/en

### Component(s) impacted

we want to get something like before ...

![Screenshot 2022-06-01 at 16 21 13](https://user-images.githubusercontent.com/57751227/171661826-4f8ebdd9-f757-422c-8cda-a517d899a020.png)

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

 "@carbon/ibmdotcom-react": "1.32.1",

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://www.ibm.com/docs/en

### Package

@carbon/ibmdotcom-react, @carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

https://ibmdocs-dev.mybluemix.net/docs/en

### Steps to reproduce the issue (if applicable)

please try to log in here https://ibmdocs-dev.mybluemix.net/docs/en and you can see that icon is not changed, its showing us still log in ...

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by IgnacioBecerra** [comment]
@Stefan8412 Haven't been able to reproduce this bug, can you verify if it still happens with our latest version?

**Comment by IgnacioBecerra** [comment]
Contacted @Stefan8412 and it seems Issue has been resolved, closing issue.
