### ISSUE TITLE
[Structured List & Pricing Table]: AEM currently returns `<p>` tag in the list cell causing style rendering issue

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#8962]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2487
- DPO consulting engineer: N/A

-----

### The problem

- The AEM team is in the midst of adopting the Structure List and Pricing Table components and has recently noticed some discrepancies related to the rendering of the text within the structured list and pricing table cells.
- Currently, the team is using AEM's OOTB WYSIWYG to populate data within the text cell area as this content can be a regular paragraph or includes `<ul>`, which results in `<p>` tag that gets wrapped around the text.
- The text in the cell should be using `productive-body-long-01` and color `$text-02` instead of the `<p>` style from the Carbon reset helper stylesheet.

![Screen Shot 2022-06-08 at 09 06 00](https://user-images.githubusercontent.com/1815714/172673429-2d1c2239-4bf9-4a32-bd68-b508263aad25.png)

### The solution

- Figure out a way to import styling needed for the WYSIWYG area that includes proper formatting for `<p>`, `<ul>`, etc as there's no great way to target/force style within the shadow root (eg. `:host(dds-structured-list-cell) ::slotted(p)`).
- This is the same issue that we're currently running into the Accordion version that's managed in Carbon for AEM (https://github.ibm.com/webstandards/carbon-for-aem/pull/40/files#r6224256). @kennylam @annawen1 Feels like this can be something we can bring to the dev office hour call.

### Application/website

AEM

### Business priority

Medium Priority = upcoming release but is not pressing

### Examples

- https://codesandbox.io/s/jovial-hugle-vpqkqg?file=/index.html

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@kennylam During our last issue-sharing meeting, I believe you mentioned that you have a solution to follow up on regarding this issue. Can you let me know how we can approach this aside from the rejected solution in this PR (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8993)? Thanks!

**Comment by sirkitree** [comment]
Hi @kennylam - have you had a chance to think about this one? Can you offer some guidance on how we can solution this issue?

**Comment by sirkitree** [comment]
Hi @kennylam - have you had a chance to look at this issue?
