### ISSUE TITLE
[Logo grid]: @sm should be two columns for logos

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#9005]
**Engineering info:**  
- Innovation Team engineer: [Prachaya Sinsuwan](https://app.slack.com/team/W4BSY8N2H)
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2505
- DPO consulting engineer: @emyarod 

-----

### Description

Discovered in #8973.

The Web Components version of Logo grid is currently displaying a single column of logos and should be updated to match the newly created React wrapper version. At the `@sm` breakpoint, the logos should be in two columns to match the spec:

**Current WC version**
<img width="224" alt="Screen Shot 2022-06-15 at 4 50 56 PM" src="https://user-images.githubusercontent.com/15643582/173925450-014b5fb5-e9e1-428a-a351-548d3d5bf8f5.png">

**Specs**
<img width="469" alt="Screen Shot 2022-06-14 at 10 36 31 AM" src="https://user-images.githubusercontent.com/15643582/173924764-34632558-0634-46e6-aa58-249c716483c7.png">

### Component(s) impacted

Logo grid

### Browser

Chrome

### Carbon for IBM.com version

v1.19.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/examples/codesandbox/components/logo-grid

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@emyarod FYI, this issue is assigned to our Innovation team group. I'm going to leave you as a consultant for this issue. Let me know if you have any questions.
