### ISSUE TITLE
[Search with Typeahead]: Display data with customer API

### ISSUE THREAD

**Issue by cedricpelle** [carbon-design-system/carbon-for-ibm-dotcom#9043]
### Description

Result is not displaying correctly  with customer API

### Component(s) impacted

Search with Typeahead

### Carbon for IBM.com version

v1.35

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

https://www.ibm.com/support/customer/csol/terms/

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://localhost.ibm.com/support/customer/csol/terms/

### Steps to reproduce the issue (if applicable)

- when using the IBM search the out put is well rendering

![image](https://user-images.githubusercontent.com/38075847/176039716-6ede5cad-d9c0-48cf-ba7f-49887c9cb2b3.png)

- when using Custom API seems not render correctly 
![image](https://user-images.githubusercontent.com/38075847/176039851-3401ce8c-57f8-498d-a7f3-e2191d158695.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
@cedricpelle I'm having difficulty replicating your issue. If it's still a problem can you provide steps to duplicate?
