### ISSUE TITLE
Why TypeScript as peer dependency?

### ISSUE THREAD

**Issue by abdonrd** [carbon-design-system/carbon-for-ibm-dotcom#9044]
### Summary

Why TypeScript as peer dependency?

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/c2e99ca87ef13274577df9ae7b861a0e47f6f82d/packages/web-components/package.json#L265-L267

We have an issue with that:
<img width="609" alt="Screen Shot 2022-06-28 at 18 17 47" src="https://user-images.githubusercontent.com/1007051/176239762-e18f29c2-516d-4270-96a0-24051a1fc494.png">

### Name and organization

IBM

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by abdonrd** [comment]
Maybe there is something I don't know, but just in case I send the PR:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9045

**Comment by kennylam** [comment]
Hi @abdonrd, it would be for the exact reason you are showing in your terminal output – to alert users that a specific version of Typescript is needed to use this package at runtime. It looks like you are using a different version in your project?

**Comment by abdonrd** [comment]
> Hi @abdonrd, it would be for the exact reason you are showing in your terminal output – to alert users that a specific version of Typescript is needed to use this package at runtime. It looks like you are using a different version in your project?

Mmm but why? TypeScript it's only used for build the package before publishing to npm.
When you download the npm package, you only use the JavaScript files.

**Comment by abdonrd** [comment]
From another conversation:

To import a component such as:
[@carbon/ibmdotcom-web-components/es/components/button/index.js](https://unpkg.com/browse/@carbon/ibmdotcom-web-components@1.21.0/es/components/button/index.js)
[@carbon/ibmdotcom-web-components/es/components/button/button.js](https://unpkg.com/browse/@carbon/ibmdotcom-web-components@1.21.0/es/components/button/button.js)

You don’t need TypeScript... it’s a simple JavaScript file.
