### ISSUE TITLE
[Footer]: Update placeholder adjunct link labels

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#9053]
### The problem

Mike has requested that we update the sample adjunct legal links in the Storybooks with new language.

### The solution

In the `Footer` Storybook entries, the copy should be updated. Remove the period in each:

- “See the updated terms of Use. Learn more.” → “Updated Terms of Use”
- “Read Learning Technologies Privacy.” → “Learning Technologies Privacy”

Should update in each of the `Footer` Storybooks in which adjunct legal links appear:

- [ ]  Default with adjunct legal links
- [ ]  Short with adjunct legal links

Should be updated in Web components, React, and React wrapper if applicable.

### Application/website

C4IBM.com

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@jeffchew @ljcarot This sounds like something for the translation team? Wondering if other languages would also need their link copy updated to reflect the change in `us-en`.
