### ISSUE TITLE
[masthead]: megamenu items not displaying correctly

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#9065]
### Description

Web components `masthead` megamenu items are all stacking in one large column.

![image](https://user-images.githubusercontent.com/909118/177762279-0332c82e-f8fe-41b0-9480-6093adadef1f.png)

### Component(s) impacted

`masthead`

### Browser

Chrome

### Carbon for IBM.com version

v1.35.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

Carbon for IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/react/?path=/story/components-masthead--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
Fix has been merged in previous release
