### ISSUE TITLE
[web-components]: Add file extensions on esm import

### ISSUE THREAD

**Issue by y4izus** [carbon-design-system/carbon-for-ibm-dotcom#9069]
### The problem

This is a library to be used in the browser and the browser isn't able to resolve ECMAScript modules if they haven't file extensions. That makes that anyone that wants to use the library have to resolve those paths or they couldn't use this components

### The solution

Add file extensions to allow users use the library without extra work. It could be interesting to add a linter like [this one](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md) to be sure all the imports have their extension

### Application/website

We are building a [web components library for IBM Quantum](https://github.com/Qiskit/web-components)

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by abdonrd** [comment]
@kennylam done in this PR:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9089
