### ISSUE TITLE
[External link] W3 page links to older website

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#9084]
When someone uses the `Carbon for IBM.com` link on **[this w3 page](https://w3.ibm.com/w3publisher/ibm-web-standards-external/standards-mandatory/page-layout-design)**, they are brought to an older version of our website. The Storybook links come up as 404 errors.

Per this **[Slack conversation](https://ibm-studios.slack.com/archives/C2PLX8GQ6/p1657558837102439)**.

https://images.zenhubusercontent.com/193129061/d12a0947-31d9-4bd6-8cc9-2473ddf20ff6/screen_recording_2022_07_11_at_1_28_28_pm.mov

**Comment by oliviaflory** [comment]
Redirects are in place and w3 site is updated!
