### ISSUE TITLE
[Masthead (Storage)]: dds-masthead using data endpoint from "Storage" translation renders EN version on soft refresh in FF

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#9085]
**Innovation Team JIRA ticket:** https://jsw.ibm.com/browse/HC-2504

-----

### Description

When a translated version of the Storage page, which uses the Global Masthead "Storage", the links of the masthead appear in English instead of the desired language, but only on Firefox. Chrome and Safari work as expected.

**Examples:**
https://www.ibm.com/es-es/storage
https://www.ibm.com/fr-fr/storage
https://www.ibm.com/jp-ja/storage

Occasionally, on first load, they render correctly on Firefox, but a soft refresh or navigate away and back renders them in English.

![エンタープライズ・データ・ストレージ・ソリューション_-_日本___IBM](https://user-images.githubusercontent.com/1815714/178331624-0826fe74-264e-4365-9e12-f781d7ccd7a7.png)

### Proposed Workaround solution
- For (https://www.ibm.com/jp-ja/storage), currently, the API call for the translation file is trying to query for `usja.json` which doesn’t exist within the Storage translation repo (https://github.ibm.com/webstandards/ibm-dotcom-translations/tree/master/translations/storage-masthead).
- A workaround for this issue that we can look into is to duplicate [jpja.json](https://github.ibm.com/webstandards/ibm-dotcom-translations/blob/master/translations/storage-masthead/jpja.json) for [usja.json](https://github.ibm.com/webstandards/ibm-dotcom-translations/blob/master/translations/storage-masthead/jpja.json).

<img width="1496" alt="Screen Shot 2022-06-30 at 12 51 51 PM" src="https://user-images.githubusercontent.com/1815714/178332569-c5b920ae-d76f-4d7b-ad2c-539e71d3480a.png">

### Component(s) impacted

- dds-masthead
- Masthead translation API

### Browser

Firefox

### Carbon for IBM.com version

v.1.35.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Drupal

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-services

### CodeSandbox example

https://www.ibm.com/es-es/storage

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@proeung Does [this](https://github.ibm.com/webstandards/ibm-dotcom-translations/pull/756) address this issue (bullet #2)?
