### ISSUE TITLE
Masthead and Footer making api calls and resulting in errors

### ISSUE THREAD

**Issue by jhossain1** [carbon-design-system/carbon-for-ibm-dotcom#9091]
### Description

The masthead and footer components make api calls and which encounter errors. Just simply open the code sandbox links from the documentation to view it on the console.
<img width="791" alt="Screen Shot 2022-07-12 at 1 05 31 PM" src="https://user-images.githubusercontent.com/91224996/178574729-0daf46c9-1950-4d2f-8dfc-57d9f8e3e24a.png">

Masthead: https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/react/examples/codesandbox/components/Masthead

Footer: https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/react/examples/codesandbox/components/Footer

### Component(s) impacted

Masthead: https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/react/examples/codesandbox/components/Masthead

Footer: https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/react/examples/codesandbox/components/Footer
<img width="791" alt="Screen Shot 2022-07-12 at 1 05 31 PM" src="https://user-images.githubusercontent.com/91224996/178574847-c15972a4-fa14-4dfd-982b-14749f30a5be.png">

### Browser

Chrome, Safari, Firefox

### Carbon for IBM.com version

1.35.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://www-40.ibm.com/ibm/cas/canada/

### Package

@carbon/ibmdotcom-react, @carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

Masthead: https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/react/examples/codesandbox/components/Masthead  Footer: https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/react/examples/codesandbox/components/Footer

### Steps to reproduce the issue (if applicable)

Visit code sandbox links from official documentaion and open up console to view the errors.

Masthead: https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/react/examples/codesandbox/components/Masthead

Footer: https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/react/examples/codesandbox/components/Footer

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Not stale

**Comment by annawen1** [comment]
Most of the errors coming through in that screenshot are CORS errors (namely the login API) which fails because the page requesting is not under the allowed host list set by the server. These are valid errors. 

The other API error (translation one) I do not see in the current stackbiltz (try running in FireFox - Chrome will run out of memory). 

Closing this ticket, feel free to reopen if there are any questions or additional information that needs to be addressed.
