### ISSUE TITLE
[Footer] Explore Adjunct link location

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#9133]
[Original Slack conversation](https://ibm-studios.slack.com/archives/G019HG7R2LQ/p1656606070448919)

Mike has asked us to revisit the location of the adjunct links in the `Footer`. We should explore out each option to see what change might entail and whether it would be technically feasible.

**Option A - w/o adjunct links**
![Screen Shot 2022-07-06 at 5.59.26 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/8029b9d9-a899-4372-aa38-c6be3702ab21)

**Option A - with adjunct links**
![Screen Shot 2022-07-06 at 5.59.37 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/25859ce0-8d3f-449a-abdf-01f4b1427859)

**Option B - clustering**
![Screen Shot 2022-07-06 at 6.01.59 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/62fa7d99-fdb0-4c9f-861a-7e15861281eb)

**Option C - add second rule to current version**
![Screen Shot 2022-07-06 at 6.21.05 PM.png](https://images.zenhubusercontent.com/60b63c5c740eb13b3d18acb6/16cbdb42-afe4-473f-8eb1-06fcc8538237)

**Comment by mjabbink** [comment]
Still leaning into option A
