### ISSUE TITLE
[card-group]: empty card styles fail to apply when extending component

### ISSUE THREAD

**Issue by jkaeser** [carbon-design-system/carbon-for-ibm-dotcom#9147]
**Engineering info:**  
- Innovation Team engineer: @jkaeser 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2522
- DPO consulting engineer: N/A

-----

### Contribution type

Components

### Intent

We've extended `dds-card-group` in C4AEM as `caem-card-group`, and the automatically added empty cards are visible.

![Screen_Shot_2022-07-18_at_12_25_37](https://user-images.githubusercontent.com/12532727/180222659-5700122a-91e1-4dcf-aee5-2f2eb346c12d.png)

The styles that make these "invisible" are failing to apply since the selector is more specific than it needs to be: 

`dds-card-group dds-card-group-item[empty] { ... }`

### Solution

Make the selector less specific. Simply removing `dds-card-group` from this selector fixes the problem whilst not negatively impacting `dds-card-group`. This might also be an opportunity to move the styles from the `web-components` package to the `styles` package so they can be extended if need be.

### IBM Organization or Company you are part of

Innovation Team, working on Carbon for AEM.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@jkaeser Thanks for opening this issue!

@kennylam I'd like to get your thought on the solution to this issue before we open a PR for your team to review.

**Comment by kennylam** [comment]
@jkaeser Sounds like a great solution!
