### ISSUE TITLE
[CTA Section]: Horizontal line is shown as visible when there are 3 cards in a row 

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#9166]
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2431
- DPO consulting engineer: N/A

-----

### Description

- The CTA Section row shows a horizontal rule between rows even with only 3 content items before the row break.
- The border issue looks to be happening on AEM because of additional padding top and bottom properties that were added, however, I think there's some improvement on the C4IBM side that we can do to eliminate this issue so that the addition and removal of the horizontal line depending on the number of items per row is managed better.
- See - https://prod-author.roks.cms.cis.ibm.net/content/adobe-cms/language-masters/en/products/watson-orchestrate.html?wcmmode=disabled

![box-image](https://user-images.githubusercontent.com/1815714/180872593-d921bc09-469c-48cf-8003-dc1fca25a770.png)

### Component(s) impacted

CTA Section

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v.1.35

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

https://prod-author.roks.cms.cis.ibm.net/content/adobe-cms/language-masters/en/products/watson-orchestrate.html?wcmmode=disabled

### Steps to reproduce the issue (if applicable)

- Scroll to the bottom of this page (https://prod-author.roks.cms.cis.ibm.net/content/adobe-cms/language-masters/en/products/watson-orchestrate.html?wcmmode=disabled)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@oliviaflory Can you help take a look at this issue and let me know what you think? Thanks!

cc: @jwitkowski79

**Comment by oliviaflory** [comment]
> - The CTA Section row shows a horizontal rule between rows even with only 3 content items before the row break.
> - The border issue looks to be happening on AEM because of additional padding top and bottom properties that were added, however, I think there's some improvement on the C4IBM side that we can do to eliminate this issue so that the addition and removal of the horizontal line depending on the number of items per row is managed better.

@proeung 
1. Yes, there should not be a horizontal rule below the 3 content items before a row break
2. CTA section is performing correctly in our C4IBM [storybook](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-cta-section--with-content-items)
3. Can you clarify what improvements could be made? I would need to understand the changes and have our dev team weight in.
4. The current CTA section has 160px of padding on the bottom. Does the problem go away with the added padding removed? From a first look the additional top and bottom padding seem like they're throwing the content off from the rest of the page spacing.
