### ISSUE TITLE
[Figma] Review current components

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#9179]
Took a look at the components you reviewed and the ones that are a little newer.

### High Priority

- [x]  Pictogram item
- [x]  Content item
- [x]  Card - default – Lots of questions / comments should discuss!
- [x]  Card - logo – Lots of questions / comments should discuss!

### Medium

- [x]  Feature section
- [ ]  Universal banner
- [x]  Logo grid
- [x]  Content group banner
- [x]  Link list
- [x]  Feature card - large
- [x]  Feature card - medium
- [x]  Carousel control

### Low

- [ ]  Back-to-top
- [ ]  Horizontal rule
- [ ]  Expressive modal
- [ ]  Language selector
- [ ]  Leaving IBM Modal
- [ ]  Locale selector

### Reviewed

- [x]  Expressive button
- [x]  Link with icon
- [x]  Logo grid
- [x]  Content group pictogram
- [x]  Expressive button
- [x]  Card link
- [x]  Footer
- [x]  List large
- [x]  Tabs extended
- [x]  Tag link
- [x]  Video player

**Comment by oliviaflory** [comment]
**Pictogram**
- Boolean hides text
- Breakpoints, I was thinking they'd be set to the length the text is allowed to span (8 columns, or slightly less for max). Thoughts?
