### ISSUE TITLE
[Tabs Extended-component]: Onclick function with href tag is not working in mobile responsiveness.

### ISSUE THREAD

**Issue by Monika-Jayanna** [carbon-design-system/carbon-for-ibm-dotcom#9199]
### Description

we are using this below component in our privacy portal project
https://www.ibm.com/standards/carbon/web-components/react/?path=/story/components-tabs-extended--default
inside the tabs we have some contents with few links so links are working when we have only href links inside the tag
but its not working when we have onclick function inside the href tag.

### Component(s) impacted

Please refer the below image 

![image](https://user-images.githubusercontent.com/97293722/182205916-4afbc00f-de4d-4ac0-89b0-4ae4c601e3bb.png)

### Carbon for IBM.com version

1.35.1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

https://www.ibm.com/privacy/portal/us-en

### Package

@carbon/ibmdotcom-react, @carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components/examples/codesandbox/components-react/tabs-extended

### Steps to reproduce the issue (if applicable)

Please add some href tag with sample onclick function inside the content of the tab then check that onclick function in mobile responsive view.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by Monika-Jayanna** [comment]
@kennylam Any ETA on this issue because external users also facing this issue.

**Comment by ariellalgilmore** [comment]
Hi @Monika-Jayanna, I found a current work around you can use to solve the issue. You can see it here in the [codesandbox example](https://codesandbox.io/s/elegant-lalande-s2161c?file=/index.html). If you are having trouble getting it to load you can download the zip in the top left hand corner. 

The work around includes specifically targetting the mobile rendered elements and adding an event handler. 

I plan to bring up this issue this week to see if we can rework the component later on with the fellow Carbon for IBM.com engineers.

**Comment by ariellalgilmore** [comment]
Hi @Monika-Jayanna could you give us more details on what your team is using the `onclick` funciton for? Is it for analytics?

**Comment by Monika-Jayanna** [comment]
@ariellalgilmore  Yes we are using it for analytics also and we need that as per the requirements.

**Comment by ariellalgilmore** [comment]
Resolved via slack
