### ISSUE TITLE
[Masthead v2]: Create a job that auto merges changes from `main` to `feat/masthead-2`

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#9209]
### Description
- Add an `automerge` GitHub action to the [feat/masthead-v2](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/feat/masthead-v2) that auto updates from the `main` branch.

### Additional information
- **Overview and scope of the engineering work should be included in the linked epic (#9208)**

### Acceptance criteria
 - [ ] Changes from the `main` branch automatically merge down to `feat/masthead-v2`

**Comment by kennylam** [comment]
@proeung Already completed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9207
