### ISSUE TITLE
[Audio player] update design spec

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#9278]
> As a `[user role below]`:

developer 

> I need to:

have the `audio player` design specs

> so that I can:

correctly change the `audio player` component to meet accessibility requirements

#### Additional Information
- **See the epic Audio player #9256 for the overarching descriptions of the work.**

#### Acceptance Criteria
- [x] A Figma file is created or updated with the `Audio ` design and specs
- [x] Create a Box folder for the `?component name?` (if not already there)
- [x] The design specs and pdf version are added to the Box folder 
- [ ] Add Box folder link to the website content if it exists

**Comment by RichKummer** [comment]
[https://app.zenhub.com/files/193129061/8fc4e33b-b56b-4b24-b330-d1a8624cd1f9/download](Sample Component page with callouts)

**Comment by tweenn** [comment]
Hi!

I just thought it would be nice to add some context and background on this task about the specs that were used to create the current audio-player.

In #4083 - specifically [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4083#issuecomment-708374058) - there is a link to a [box folder called "References and inspirations"](https://ibm.ent.box.com/s/gkxfo5axnbtri0gq2ef4392pmixal0sf/folder/124345981083) and under it there is [this sketch file](https://ibm.ent.box.com/s/gkxfo5axnbtri0gq2ef4392pmixal0sf/file/730045788763) that contains studies for a podcast-page or micro-site page containing an audio-player.

After some calls with Shi Xie and our stakeholders around those ideas - everyone agreed with the "Desktop Version" without the download transcript button - being the best experience.

I'm not sure if it may help around upgrading / migrating from sketch to figma, but again, thought it would be nice to at least have some backstory around this 😃

**Comment by oliviaflory** [comment]
Hi @tweenn!

In order to upgrade the Audio player from experimental to production, we had our accessibility team review and test the component. They found a few accessibility issues and have logged them on our github board, you can see them all under the Epic Audio player upgrade to production #9256 

This design task is specifically addressing the accessibility issues and creating/updating the specs for things that were not documented in the original spec sheet. 

I hope that context helps! @kennylam and I will be scheduling some time to review the requirements with you and your team as soon as I wrap up the spec updates

**Comment by oliviaflory** [comment]
@tweenn Here is a link to the specs in [Figma](https://www.figma.com/file/M8HFBvFGoanLvNnq7VfEwk/Audio-player?node-id=3816%3A9315) you should be able to view them there! 

I will also add a PDF of the specs to the [Box folder](https://ibm.box.com/s/05ndo5nsg3sonc3wyskcbkoi93lhdoor)
