### ISSUE TITLE
Upgrading react-scripts to 5.0.1 gives a ReferenceError: process is not defined

### ISSUE THREAD

**Issue by ThomasMatthewFletcher** [carbon-design-system/carbon-for-ibm-dotcom#9285]
### Summary

I am trying to upgrade react-scripts from 4.0.3 to 5.0.1

```
Uncaught ReferenceError: process is not defined
    at ./node_modules/@carbon/ibmdotcom-react/es/internal/vendor/@carbon/ibmdotcom-services/services/Analytics/Analytics.js (Analytics.js:16:1)
```

This references the line:
```
var _scrollTracker = process && process.env.SCROLL_TRACKING === 'true' || false;
```

It looks like react-scripts 5 upgrades webpack to v5. I see this in the webpack docs under "process is not defined" which might be relevant:
```
webpack 5 does no longer include a polyfill for this Node.js variable. Avoid using it in the frontend code.
```

### Name and organization

Tom Fletcher - IBM
TomFletcher@uk.ibm.com

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ThomasMatthewFletcher** [comment]
I found this workaround for now. Adding this to index.html:
```
<script>if (!('process' in window)) { window.process = {}; }</script>
```

**Comment by kennylam** [comment]
@ThomasMatthewFletcher thanks for following up!

**Comment by ThomasMatthewFletcher** [comment]
Hi, I don't believe this should be closed as completed
My workaround is to define manually `window.process` before the carbon script is included. It seems very hacky and like a bug that I should have to do this?
