### ISSUE TITLE
[Masthead v2.0.0]: Consolidate Global + Cloud authentication methods

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#9291]
**Engineering info:**  
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2555
- DPO consulting engineer: @annawen1 

-----

### Description
- This is a follow-up ticket to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9211
- Now that the Masthead L0 V2 will be supporting the Global and Cloud Masthead usage, we'll need to work on consolidating the authentication methods and ensure that we deliver the right utility menu items based on the value defined in the `auth-method` prop/attribute.
- Currently, the `auth-method` prop accepts two values, 1 (cookie) checking against the cookie value coming from (https://cloud.ibm.com) and `api` checking against the API return coming from Docs/Console authentication fetching method. For the default Masthead Profile API, perhaps we can expose a new value called `profile-api` to create the distinction.

### Consulting
- Direct questions to @annawen1 for questions related to Global Masthead Profile API authentication fetching method

### Additional information
- **Overview and scope of the engineering work should be included in the linked epic (#9208)**

### Design Specs
- Desktop - https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=1970%3A110816
- Mobile - https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=1970%3A111059

**New Design**
![Screen Shot 2022-08-09 at 3 03 22 PM](https://user-images.githubusercontent.com/1815714/183740535-061274a0-bb44-49dd-8830-1ee2d25df528.png)

### Acceptance criteria
 - [ ] Masthead v2 is able to authenticate using the different auth methods.

**Comment by proeung** [comment]
@kennylam FYI, I'm adding @annawen1 as a consultant on this ticket for our upcoming sprint that's starting tomorrow.

**Comment by andy-blum** [comment]
From @jkaeser's feed back on https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9275#discussion_r953769802:

`'cookie'` is the only of these options that is checked in the Redux actions currently. We should store magic strings like this somewhere reference-able, such as an enum.
```ts
enum MASTHEAD_AUTH_METHOD {
  PROFILE = 'profile-api',
  COOKIE = 'cookie',
}
```

Then we can make this property typed:

```ts
authMethod: MASTHEAD_AUTH_METHOD = MASTHEAD_AUTH_METHOD.PROFILE;
```

What do you think? Perhaps this change makes more sense in the follow-up ticket, https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9291.
