### ISSUE TITLE
[Masthead v2.0.0]: Conduct design QA for the L0/Masthead v2.0.0 (Phase 1)

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#9307]
**Engineering info:**  
- JIRA Ticket: https://jsw.ibm.com/browse/INTF-241
- DPO consulting: @oliviaflory 

-----

### Description
- This issue aims to capture the design QA task needed for the L0/Masthead v2.0.0 (Phase 1).

### Storybook Environment
- Visit the default Masthead preview - https://carbon-design-system.github.io/carbon-for-ibm-dotcom/masthead-v2/web-components/?path=/story/components-masthead--default
- Adust the `Masthead data (data-endpoint)` knob to `masthead v2`
- If nothing changes, visit the direct [preview link](https://carbon-design-system.github.io/carbon-for-ibm-dotcom/masthead-v2/web-components/iframe.html?id=components-masthead--default&knob-Masthead%20data%20(data-endpoint)_MastheadComposite=/common/carbon-for-ibm-dotcom/translations/masthead-footer/v2&knob-show%20the%20profile%20functionality%20(has-profile)_MastheadComposite=true&knob-show%20the%20search%20functionality%20(has-search)_MastheadComposite=true&knob-search%20placeholder%20(searchPlaceholder)_MastheadComposite=Search%20all%20of%20IBM&knob-selected%20menu%20item%20(selected-menu-item)_MastheadComposite=Consulting%20&%20Services&knob-The%20user%20authenticated%20status%20(user-status)_MastheadComposite=Unauthenticated)
- NOTE: We might look at moving the endpoint updating out of the knobs as this feature is inconsistent.

### Additional information
- **Overview and scope of the engineering work should be included in the linked epic (#9208)**

### Design Specs
- Desktop - https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=1970%3A110816
- Mobile - https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=1970%3A111059

### Acceptance criteria
 - [ ] Masthead v2 is able to authenticate using the different auth methods.

**Comment by oliviaflory** [comment]
### Breakpoints

- [ ] 1. Mega menu should change to the hamburger menu at 956px browser width, see [3.4 in the Functional spec](https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=2325%3A136631)

Currently the mega menu is maintaining past 960px and appears broken with content falling below the tabbed section

<img width="968" alt="Screen Shot 2022-08-29 at 4 56 59 PM" src="https://user-images.githubusercontent.com/45692622/187298583-4525d5de-0ab6-46d1-87b0-566db1ae8753.png">
