### ISSUE TITLE
Svelte support?

### ISSUE THREAD

**Issue by AZProductions** [carbon-design-system/carbon-for-ibm-dotcom#9353]
### Summary

Has anyone tried the web-components package with svelte? Thanks in advance!

### Name and organization

AZ

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
Hi @AZProductions, you should try asking in https://github.com/carbon-design-system/carbon-components-svelte.

**Comment by AZProductions** [comment]
> Hi @AZProductions, you should try asking in https://github.com/carbon-design-system/carbon-components-svelte.

Thank you, but I'm talking about `carbon-for-ibm-dotcom` with its pre-built layouts

**Comment by kennylam** [comment]
Right, what I meant was that you should try asking if anyone in the `carbon-components-svelte` community has tried using the `@carbon/ibmdotcom-web-components` package with the components you mentioned. I can tell you with certainty that Carbon for IBM.com does not use Svelte.
