### ISSUE TITLE
[Masthead v2.1.0]: Phase 2 - Add improvements to Contact us CTA button

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#9369]
**Engineering info:**  
- JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2602
- JIRA Epic: https://jsw.ibm.com/browse/AEMSITES-177

-----

### Description
- A follow-up phase 2 task from https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9359
- From @oliviaflory 
  - I like that when you have a mega menu open and then select the contact us button, the mega menu collapses/closed. I think the reverse should also be true. When I select the Contact us button first, the contact module opens, and if I then select a mega menu the chat module stays open and obstructs part of the mega menu content

![contact module mega menu Sep-13-2022 17-49-10](https://user-images.githubusercontent.com/45692622/190015621-0a609752-f9ba-4f1e-98e5-533937a2e78a.gif)

**Questions that we should run by the accessibility team:**

- Should clicking the chat button again (after the chat module is opened) trigger the chat module to close? Asking because otherwise the user has to move their mouse to the contact module to close, and all other navigation items (mega menus and profile menu) close the menus on a second click.
- Should the focus state move to the Chat module once the user clicks it for keyboard users?
- When testing with the screen reader, there is no announcement that the chat module has opened
- After you select the Contact us button, a keyboard user has to tab through the entire page before getting to the contact module. This doesn't seem like a great experience (hence the suggestion to move the focus state). Shift tab would go back to the contact us button.

### Design Specs
- Figma mockup - https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=2325%3A136628

**Comment by andy-blum** [comment]
I've been looking into this, and it appears these changes will need to be made within the cm-app script, not in Carbon. As far as I can tell, the event listeners that handle this interaction are on the document and/or body element and are placed by the cm-app.min.js file. 

<img width="730" alt="Screenshot 2022-11-08 at 2 14 50 PM" src="https://user-images.githubusercontent.com/25532785/200655354-68350a47-f75b-4a45-957f-fecf2b92dfdb.png">

**Comment by sirkitree** [comment]
Do we know where cm-app.min.js comes from, or who owns that?

**Comment by andy-blum** [comment]
Per @jeffchew:

> The repo for that script is here: https://github.ibm.com/live-advisor/cm-app
