### ISSUE TITLE
[Masthead v2.1.0]: Rethink menu closing on focus

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#9376]
**Engineering info:**  
- JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2591
- JIRA Epic: https://jsw.ibm.com/browse/AEMSITES-177

-----

### Description
- A follow-up phase 2 task from https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9341#issuecomment-1239780252
- Why [sic] trying to design QA this, we noticed that the entire menu closes on focus. We noticed that the original masthead does this too. Is there a better way to handle this? It's more of an annoyance, functionality quirk but understand if it needs to be this way for accessibility purposes.

### Design Specs
- Figma mockup - https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=2325%3A136628

**Comment by andy-blum** [comment]
We've elected to not do this.
