### ISSUE TITLE
[Pricing table]: CTA wrong size

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#9394]
### The CTA within the Pricing table header is a large type and container size than what is defined in the specs.
This throws off the hierarchy of the content.

**Current**
Expressive button: 16px type; 48px container

![Screen Shot 2022-09-19 at 8 49 50 AM](https://user-images.githubusercontent.com/45692622/191024056-6c75243c-f1f8-4efe-b824-21752edd0209.png)

**Expecting**
Productive button: 14px type; 40px container
- This will have the button text match the text size throughout the pricing table

![Screen Shot 2022-09-19 at 8 51 48 AM](https://user-images.githubusercontent.com/45692622/191024413-b9d93497-fb3a-4e1f-b2c2-443cd3ee971f.png)

### Component(s) impacted

[Pricing table](https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components-experimental/?path=/story/components-pricing-table--default)

### Browser

Chrome

### Carbon for IBM.com version

v1.23.0

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

AEM / C4IBM 

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components-experimental/?path=/story/components-pricing-table--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
cc: @jwitkowski79 @andy-blum

**Comment by andy-blum** [comment]
@oliviaflory is this still a problem?
