### ISSUE TITLE
[Filter Panel]: QA: When the user reaches filter Catagories like 'technologies and Business options', screen reader announces the entire list

### ISSUE THREAD

**Issue by gopinathan-n** [carbon-design-system/carbon-for-ibm-dotcom#9396]
### Summary

Page Element:
Filter Catagories like, technologies and Business options

Issue Description:
When we reach the last option in the mentioned catagories using shift tab key, screen reader announces the entire list of options within that catagory. This makes the screen reader oververbose.

Expected:
Screen reader is expected to announce only the focused element

Impact:
Any redundant, excessively wordy and extraneous announcement can be distracting for the screen reader users. 

Component(s) impacted
Filter Panel

Browser
Firefox

Carbon for IBM.com version
v1.38.0-rc.0

Application/website
Carbon for IBM.com

Package
@carbon/ibmdotcom-web-components

CodeSandbox example
Web component Canary- https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components Web component Staging- https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components

### Name and organization

Gopinathan 
IBM

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
Closing in favor of #10589
