### ISSUE TITLE
[Filter Panel]: QA: Screen reader is announcing the hidden content in Filter overlay

### ISSUE THREAD

**Issue by gopinathan-n** [carbon-design-system/carbon-for-ibm-dotcom#9397]
### Description

Page Element:
Filter overlay

Issue Description:
In Voiceover iPhone, When the filter overlay is displayed, the parent content is visually hidden. But screen reader identifies them. e.g. the button which triggered the modal overlay

Expected:
Hide the content from  the screen reader as well.

Impact:
If the screen reader identifies the visually hidden content, it tends to mislead users who are blind. 

### Component(s) impacted

Filter Panel

### Browser

Safari

### Carbon for IBM.com version

v1.38.0-rc.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Carbon for IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

Web component Canary- https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components Web component Staging- https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
Closing in favor of https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10589
