### ISSUE TITLE
[Page links broken]: A few links are broken.

### ISSUE THREAD

**Issue by adsingh14** [carbon-design-system/carbon-for-ibm-dotcom#9463]
### Description

1. Open [this](https://www.ibm.com/standards/web/) link.
2. Click on any box under `Mandatory Standards` and `Quality Guidelines`.

### Component(s) impacted

![image](https://user-images.githubusercontent.com/35252877/194343562-e041c664-7549-4aeb-b340-6e5102bba37a.png)

### Browser

Microsoft Edge

### Carbon for IBM.com version

Version 106.0.1370.34

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

-

### Package

@carbon/ibmdotcom-styles

### CodeSandbox example

-

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Hi @adsingh14, thanks for your issue!

I am able to access all of the links on this page, if you are an IBMer you will need to make sure your VPN is on. This site is for internal use only and outlines the requirements for IBM's domain governance.
