### ISSUE TITLE
[Video]: Video shows first frame on Pause.

### ISSUE THREAD

**Issue by adsingh14** [carbon-design-system/carbon-for-ibm-dotcom#9466]
### Description

1. Open [this](https://www.ibm.com/design/language/whats-new/#people-illustration) link.
2. Pause/Play video or check the attached video.

### Component(s) impacted

https://user-images.githubusercontent.com/35252877/194358432-6d7c2e5e-c5d6-4573-8bb5-a7a59b4fac0d.mp4

### Browser

Firefox

### Carbon for IBM.com version

-

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

-

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

-

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by adsingh14** [comment]
Hi! I just received the notification. This issue hasn't been resolved.

**Comment by kennylam** [comment]
@adsingh14 This doesn't seem to be using any components from this package.
