### ISSUE TITLE
[Video Player]: Not working properly on safary

### ISSUE THREAD

**Issue by tweenn** [carbon-design-system/carbon-for-ibm-dotcom#9587]
### Quick Description
The way that the video player works is failing on safari@macOS - as of now, a user has to double click a video to watch it.
Aka - click on an inline player poster and click again on the player to play it - or click in a cta/poster to open a overlay and then click again in the player to watch it.

#### Player inner workings:
Northstar & Carbon create a "poster" with a thumbnail & other media-information and upon user interaction (either mouse or keyboard click) the poster goes away and the kaltura player is added to the DOM through a javascript controlled iFrame.
The player is instantiated with auto-play and muted (per browser rules) and a code-generated click is emitted through javascript to unmute the player.
This "fake" click works on other browsers 'cause the page has already been interacted with - in the form of the user clicking in the fake poster.

#### The problem:
In safari, the .play() action of the video element failed as it should for videos that auto-play with sound.
This mean that the fake click is working and unmuting the player but it's not considered a valid user click - triggering the browser to stop the video as like we were trying to bypass the rule.

After some study on the matter, I've found out that if the player element exists in the page in the time that the poster is clicked (aka the user interaction is generated) - this "failing behavior" won't happen, making me believe that Safari changed the rules around this first interaction of the user AND newer elements in the DOM tree.

#### When:
I'm not sure in which [Safari release](https://developer.apple.com/documentation/safari-release-notes/) this happened (my best guess is somewhere in v15) - but it updated something around media autoplay rules and broke the video player experience.

#### Possible solution
Instead of instantiating the player after the user click the poster, the player has to be added on page-load - which may hinder the page speed and performance (need a more detailed study on impact)
There is a stub-not-optimised example in the "steps to reproduce" section (last link)

### Component(s) impacted

Video Player
Canary Audio Player

### Browser

Safari

### Carbon for IBM.com version

latest

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

mediacenter.ibm.com

### Package

@carbon/ibmdotcom-react, @carbon/ibmdotcom-web-components

### CodeSandbox example

https://tweenn.github.io/carbon-for-ibm-dot-com-media-player-safari-examples/?path=/story/introduction--page

### Steps to reproduce the issue (if applicable)

In safari, macOs, enter in any of the following pages and click on the player without clicking anywhere else in the page.

* Carbon Video Component - Web Components:
    * [My example](https://tweenn.github.io/carbon-for-ibm-dot-com-media-player-safari-examples/?path=/story/failing--carbon)
    * [Carbon for IBM dot Com storybook](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-video-player--default)

* Carbon Video Component - React:
    * [Carbon for IBM dot Com storybook](https://www.ibm.com/standards/carbon/react/?path=/story/components-video-player--default)

* Northstar Video Widget - Kaltura
    * [My example](https://tweenn.github.io/carbon-for-ibm-dot-com-media-player-safari-examples/?path=/story/failing--northstar)
    * [Northstar official doc for Kaltura's Video Widget](http://northstarexamples.mybluemix.net/v18/elements/videoplayer-kaltura/)
    * [Drupal live page](https://www.ibm.com/optimization-modeling)

This behavior can also be observed in Northstar's youtube widget
* [Northstar official doc for Youtube's Video Widget](http://northstarexamples.mybluemix.net/v18/elements/videoplayer-youtube/)

This behavior is not happening in my (not-optimised) proposal
* [Not Optimised Working Example](https://tweenn.github.io/carbon-for-ibm-dot-com-media-player-safari-examples/?path=/story/working--web-component)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by tweenn** [comment]
Hey everyone!

After the Office Hours that happened today, I've agreed with @ariellalgilmore to add some extra information here, like a more detailed diagram on how the players (carbon and northstar) currently works and the changes for the proposed solution - and also how this change would affect (benefit) the audio-player that is currently in react-canary.

I'll do so in two new comments (one for each topic) - for better view in github.

**Comment by tweenn** [comment]
# Disclaimer

- The northstar/v18 flow for both YouTube and IBM Video [former uStream] is here to illustrate how it was done in other players versus how we're doing with Kaltura's.
- The proposed solution is only for the kaltura player in both frameworks and should not touch the legacy players for both YouTube and IBM Video [former uStream]

# Diagrams

### Current State

* Framework: Northstar
* Player vendors: Youtube & IBM Video [uStream]

![northstar-youtube-ibmvideo](https://user-images.githubusercontent.com/1704162/199516868-87d50e30-6c2b-4faa-8432-f7b8a85c112c.jpg)


----------
* Framework: Northstar & Carbon
* Player vendors: Kaltura

![carbon-and-northstar-kaltura-player](https://user-images.githubusercontent.com/1704162/199517071-4b88a1df-03ae-49b5-b990-682e099c974a.jpg)


----------

### Proposed Solution

* Framework: Northstar & Carbon
* Player vendors: Kaltura

![proposed-solution](https://user-images.githubusercontent.com/1704162/199517679-e52f3ccf-9ed8-47cd-b9f6-a55f1af1fd70.jpg)

**Comment by tweenn** [comment]
# Audio Player

### Disclaimer

The audio player ALSO suffers from double clicking in safari, but since you have "less visual clues" about it not working, the user experience is way more degraded than the video-player.

----------
### Description

As we create a poster for the video to force the user to interact with the player before invoking it in the dom, the audio player don't have such elegant solution and thus it get all interaction buttons disabled (there was a discussion around this behavior in the first PR of the audio player, [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6102#issuecomment-849917206))

Here's how it look like:

![audio-player-poster-mode](https://user-images.githubusercontent.com/1704162/199522212-4abb23fd-9f65-48ba-9395-1cb5cf43fda4.jpg)


----------

Now, if the player get invoked in the page before the user click, those disabled buttons can be set to enabled as soon as the player emits the "ready to play" notification through the kaltura-api, just like as if a user had clicked, making not only the user experience better but also solving the double-click-clueless issue.

![audio-player-after-user-interaction](https://user-images.githubusercontent.com/1704162/199524316-a1ab3493-0d08-44a3-864e-565b13c057b4.jpg)

**Comment by andy-blum** [comment]
I'm not seeing this in action on safari today.

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/iframe.html?args=&id=components-video-player--default&viewMode=story

@tweenn are you able to replicate this issue still?

**Comment by andy-blum** [comment]
bump @tweenn

**Comment by tweenn** [comment]
Hey @andy-blum 
Sorry for the humongous delay on this response.
I had lost my Mac and changed orgs, things were crazy by that time.

ANYWAY, problem still persists.

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1704162/080a2dce-dc84-4fb7-bd85-e6aef4ca3a5c

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1704162/67ef2a58-f2b5-4323-9de6-a41658284792

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1704162/d30a3d5e-03da-4eba-8595-e5d5c14ff3cc

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1704162/c9766721-a413-49f4-bf5c-b5f9b897031e
