### ISSUE TITLE
DDSCarousel doesn't set hidden slides as "inert" until after a navigation event

### ISSUE THREAD

**Issue by mo-alaa** [carbon-design-system/carbon-for-ibm-dotcom#9589]
### Description

Hi Team, we found a strange behavior in the DDSCarousel component here:
https://www.ibm.com/standards/carbon/web-components/react/?path=/story/components-carousel--default

_**The first behavior is:**_

When navigating with the 'Tab' button, the carousel makes only 1 slide!
This should affect the accessibility of the Carousel component.
Please follow the steps along with the images to reproduce the issue.

**_The second behavior is:_**

Once I reach the navigation buttons I can't slide back all the cards with (Shift + Tab), I also think it's from the 'inert' attribute.
Thanks and sorry for this long description :slightly_smiling_face:

**See slack conversation**: https://ibm-studios.slack.com/archives/C2PLX8GQ6/p1666708985092449

### Component(s) impacted

[DDSCarousel](https://www.ibm.com/standards/carbon/web-components/react/?path=/story/components-carousel--default)

### Browser

Chrome

### Carbon for IBM.com version

v1.24.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

ibm.com/impact

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/react/?path=/story/components-carousel--default

### Steps to reproduce the issue (if applicable)

1. Go to this link https://www.ibm.com/standards/carbon/web-components/react/?path=/story/components-carousel--default and refresh the page, make sure to resize the browser so that you see only one card in the carousel 'just to reproduce the issue' (image 1)
![dds1](https://user-images.githubusercontent.com/41386480/197810630-c22e1359-fc95-4201-bd63-9b479ac99de3.png)

2. Press 'Tab' button until you reach the card (image 2)
![dds2](https://user-images.githubusercontent.com/41386480/197810727-b3bbd447-006d-4c17-b99f-dbf002c4c5c4.png)

3. Click 'Tab' again, and the carousel will make a slide 'that's normal' (image 3)
![dds3](https://user-images.githubusercontent.com/41386480/197810762-c5a42d2f-5c32-460d-ad37-c8ae673ee253.png)

4. Hit 'Tab' one more time, instead of sliding to the next card, it moved focus to the navigation button as shown in (image 4)
![dds4](https://user-images.githubusercontent.com/41386480/197810793-3df7e2f4-cab1-4c4c-9095-5f46bcc98c03.png)

5. I tried to inspect the html code, actually there's an inert attribute that 'I think' prevents sliding to the next and previous cards (image 5).
![dds5](https://user-images.githubusercontent.com/41386480/197810822-493dc188-e619-4b11-a210-58deabffdad0.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
This behavior is, in fact, incorrect, but not in the way you describe. The carousel should not move _at all_ when tabbing. To maintain an accessible carousel, we want to make the experience as identical as possible for mouse and keyboard users, and keyboard users don't have to navigate the contents of the carousel to move past it.

The actual issue here is that the carousel doesn't properly set the inert attributes until after a navigation has occured.
