### ISSUE TITLE
Table of content auto-select issue

### ISSUE THREAD

**Issue by bhumicaIbm** [carbon-design-system/carbon-for-ibm-dotcom#9603]
### Description

Hi team,
We have implemented table-of-content  component in our project but we are facing some functionality related issue where if we Navigate to url in mobile mode and  say select "Section 4" from table of content. Now just click on table of content bar and notice that a option at mouse pointer  gets auto-select and if you click outside you'll also notice the Title of the table of content is also changed even though the section underneath remains the same!
Attached is the screen share in the default component which we have added in our project with the issue mentioned above ! has anyone any idea on the fix or has faced something similar ? link :https://www.ibm.com/standards/carbon/react/?path=/docs/components-table-of-contents--default (edited) 
[Screen Recording 2022-10-27 at 6.23.16 PM.zip](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/files/9885701/Screen.Recording.2022-10-27.at.6.23.16.PM.zip)

### Component(s) impacted

 "@carbon/ibmdotcom-react/es/components/TableOfContents/TableOfContents"

https://user-images.githubusercontent.com/116866964/198517278-4f7300cc-dbda-4b83-aeed-98292711d6c2.mov

### Browser

Chrome

### Carbon for IBM.com version

1.38.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

developer.ibm.com

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://www.ibm.com/standards/carbon/react/?path=/docs/components-table-of-contents--default 

### Steps to reproduce the issue (if applicable)

N/A

### Release date (if applicable)

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Hi @clu-7, yes there will be a fix for this issue, it is in our backlog to address in a future sprint.
