### ISSUE TITLE
Reveal the HTML elements and move them outside the "shadow-root" while constructing the web components.

### ISSUE THREAD

**Issue by mseth24** [carbon-design-system/carbon-for-ibm-dotcom#9630]
### Problem Statement-

1. Adobe Target can edit/modify Standard HTML Components
2. Adobe Target cannot edit any component within the Shadow DOM

Adobe Target works using CSS Selectors. Elements within the "Shadow-root" node are not accessible using CSS selector and hence, not editable in Adobe Target. However, if an  HTML element is revealed using a slot, it becomes accessible using a CSS selector and can be edited in Adobe Target.

### Example Component-
**dds-link-list-item-card**
In the dds-link-list-item-card component, "p" tag  is revealed using a slot, and is editable in Adobe Target using a selector.

**dds-card-cta-footer**
"a" Tag is placed inside the "shadow-root", and hence not accessible/editable in Adobe Target.

Adobe Target cannot directly edit custom web-component (Any DDS component) and it can not see elements inside the "Shadow-root". Hence, updating the first standard parent HTML element is the only way to modify an element that is placed inside the "Shadow-root". 

In certain scenarios, we have to update almost the entire page (for example, to change any menu item in the Table of Content) to make minor edits on the page.

### The solution

Reveal the HTML elements and move them outside the "shadow-root" while constructing the web components. This change will enable Adobe Target to edit the element using a selector easily.

**dds-link-list-item-card**
This element uses both dev style. Few HTML elements are revealed  using slots, whereas a few others are  hidden inside shadow-root.

**Frequently Used Components-**
dds-table-of-contents
dds-link-list-item-card

### Application/website

www.ibm.com

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
@mseth24 Looking at the possibility of moving elements out of the shadow DOM and into slots, I think the approach is not feasible. Two main reasons:

1. For complex components like`link-list-item-card` for example, there are many dependencies within and outside of our library. Changes would need to be made to our own `card` component and any other components that uses it (which is a majority) as well as carbon-web-components package’s `link` component. These are massive breaking changes to our adopters and makes it difficult to maintain our components as adopters themselves will have to pass and maintain elements/styles that were once encapsulated.

2. The shadow DOM is a fundamental aspect to web components. Without it, we lose out the ability to encapsulate elements/styles/behaviors of our components that we don’t want our adopters to manipulate. We want our adopters to do through our design process before making changes not aligned with Carbon standards. The shadow DOM is a fundamental aspect to web components. Without it, we lose the ability to encapsulate elements/styles/behaviors of our components, one of the main benefits of web components.

One possible solution is to have Adobe Target listen in to custom events. Here’s a stackoverflow post going through this possible solution: https://stackoverflow.com/questions/55139670/analytics-script-is-not-sending-data-from-shadow-dom. We already have existing custom events (ie. This [example](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/video-player/video-player.ts#L60-#L72) where we dispatch a custom event for video player overlay click). We can work together to include any events the team needs to capture.

CC @kennylam

**Comment by annawen1** [comment]
Closing this ticket - see comment above for conclusion.
