### ISSUE TITLE
Leadspace gradient-style-scheme attribute string option request 

### ISSUE THREAD

**Issue by druckerk** [carbon-design-system/carbon-for-ibm-dotcom#9631]
### The problem

The leadspace web component has the attribute default for ```gradient-style-scheme``` sets to "with-gradient". 

In AEM, we have a dialog option to "Remove Image Gradient" and I'm not able to apply an empty string to the ```gradient-style-scheme```; the string will always default to "with-gradient".  I tried to use another string like "no-gradient" to the attribute, but this did not remove the gradient from the image.  

### The solution

Is there a way we can have a string option like "no-gradient" or "none" that could be applied to the ```gradient-style-scheme``` attribute that removes the gradient from the image? 

### Application/website

AEM

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

If this update can be part of the next release, that would be greatly appreciated so we can update the leadspace to use carbon tags. Thanks.

### Examples

Example Page from Dev Environment: https://dev-author.np-roks.cms.cis.ibm.net/content/adobe-cms/language-masters/en/kayle-s-test-page/learn-landing-page-test.html?wcmmode=disabled

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
@druckerk This should already be possible by setting `<dds-leadspace gradient-style-scheme="">` or `<dds-leadspace gradient-style-scheme>`

I've created #9872 to add a storybook knob for that control, you should be able to verify on that PR's deploy previews.
