### ISSUE TITLE
[Jenkins]: update Jenkins jobs to upload to COS instances

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#9649]
Update all Jenkins jobs to upload to new COS instances. See `Carbon for IBM.com - CDN - Web Components - Canary` job for an example. Once new transfers are verified to be working, the deprecated `rsync` commands can be removed (or commented out).

Jenkins buckets:

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9649#tasklist-block-bfae2d0d-6d12-4050-b1b6-cfe354173936

**Comment by annawen1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Carbon-for-IBMcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/9649?planning-poker) with Zenhub @ariellalgilmore @kennylam @IgnacioBecerra @emyarod
