### ISSUE TITLE
Carbon for ibm.com Release Plan 2023 (v1.42.0-v1.54.0)

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/carbon-for-ibm-dotcom#9698]
**v1.42.0**
Jan 5, 2022: Code freeze
Jan 5 - Jan 13, 2023: Release Candidate(s) and testing
**Jan 17, 2023: Full Release**

**v1.43.0**
Jan 17, 2023: Code freeze
Jan 17 - Jan 27, 2023: Release Candidate(s) and testing
**Jan 31, 2023: Full Release**

**v1.44.0**
Feb 10, 2023: Code freeze
Feb 13 - Feb 24, 2023: Release Candidate(s) and testing
**Feb 28, 2023: Full Release**

**v1.45.0**
Mar 10, 2023: Code freeze
Mar 13 - Mar 24, 2023: Release Candidate(s) and testing
**Mar 28, 2023: Full Release**

**v1.46.0**
Apr 7, 2023: Code freeze
Apr 10 - Apr 21, 2023: Release Candidate(s) and testing
**Apr 25, 2023: Full Release**

**v1.47.0**
May 5, 2023: Code freeze
May 8 - May 19, 2023: Release Candidate(s) and testing
**May 23, 2023: Full Release**

**v1.48.0**
Jun 9, 2023: Code freeze
Jun 12 - Jun 23, 2023: Release Candidate(s) and testing
**Jun 27, 2023: Full Release**

**v1.49.0**
Jul 7, 2023: Code freeze
Jul 10 - Jul 21, 2023: Release Candidate(s) and testing
**Jul 25, 2023: Full Release**

**v1.50.0**
Aug 4, 2023: Code freeze
Aug 7 - Aug 18, 2023: Release Candidate(s) and testing
**Aug 22, 2023: Full Release**

**v1.51.0**
Sep 1, 2023: Code freeze
Sep 4 - Sep 15, 2023: Release Candidate(s) and testing
**Sep 19, 2023: Full Release**

**v1.52.0**
Sep 29, 2023: Code freeze
Oct 2 - Oct 13, 2023: Release Candidate(s) and testing
**Oct 17, 2023: Full Release**

**v1.53.0**
Oct 27, 2023: Code freeze
Oct 30 - Nov 10, 2023: Release Candidate(s) and testing
**Nov 14, 2023: Full Release**

**v1.54.0**
Dec 1, 2023: Code freeze
Dec 4 - Dec 15: Release Candidate(s) and testing
**Dec 19, 2023: Full Release**

**Comment by Rurucode** [comment]
Is react 18 compatible???

**Comment by kennylam** [comment]
Update release schedule for 2024 [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Carbon-for-IBM.com-Releases).
