### ISSUE TITLE
add type="submit" to bx-btn

### ISSUE THREAD

**Issue by fedorzajac** [carbon-design-system/carbon-for-ibm-dotcom#9700]
### The problem

to be able to use bx-btn as native form element (preferably other elements as well) with carbon style and features. and not be dependent on any external js apart from js provided by carbon-web-components for easier incorporation into rails framework.

### The solution

to be able to pass type="submit" into inner shadowed button element. like 
```
<bx-btn type="submit"> 
or
<bx-btn submit>

### Application/website

internal

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### What time frame would this ideally be needed by (if applicable)

_No response_

### Examples

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
Should match [types](https://github.com/carbon-design-system/carbon/blob/b2cc2982e6d9bcbc0bb7298c4c956027bd575a41/packages/react/src/components/Button/Button.tsx#L417C7-L417C7) available in React component.

```js
/**
  * Optional prop to specify the type of the Button
  */
  type: PropTypes.oneOf(['button', 'reset', 'submit']),
```
