### ISSUE TITLE
Filterable doesn't work in multi-select

### ISSUE THREAD

**Issue by UXsree** [carbon-design-system/carbon-for-ibm-dotcom#9729]
### Description

By adding filterable to <bx-multi-select>, it should ideally list out the items similar to what we type in the input field and hide the remaining items.
This behavior is not happening as expected and all items are listed instead.

### Component(s) impacted

https://web-components.carbondesignsystem.com/?path=/story/components-multi-select--filterable

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon Web Components version

1.21.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://web-components.carbondesignsystem.com/?path=/story/components-multi-select--filterable

### CodeSandbox example

https://codesandbox.io/s/falling-sound-i343jh?file=/index.html

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by rccc** [comment]
Hello,

This bug is still here ! ("carbon-components": "10.58.4"). Adding "filterable" attribute does not let us filter the option list.

**Comment by annawen1** [comment]
@rccc I see this working in our latest Carbon Web Components version (1.28.0) in our storybook [here](https://web-components.carbondesignsystem.com/?path=/story/components-multi-select--filterable)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/54281166/ad368c99-94fc-48b1-94fa-3571c44cecf9

**Comment by annawen1** [comment]
Actually, testing in codesandbox, I see the issue - I'll open a PR with the fix
