### ISSUE TITLE
add "change" event for <bx-input>

### ISSUE THREAD

**Issue by wnwaynelee** [carbon-design-system/carbon-for-ibm-dotcom#9739]
### The problem

I am replacing \<input type="text"> with \<bx-input>.  The UI renders fine.  But \<bx-input> seems to have "input" event only and not "change" event.  You can test with the html file in [test.zip](https://github.com/carbon-design-system/carbon-web-components/files/9184773/test.zip).

When I inspect the DOM, I can see \<bx-input> is backed by \<input type="text">.  The "input" event is good for implementing typeahead.  For most cases, the "change" event is probably more useful/efficient.

### The solution

Please add "change" event for \<bx-input>.  Please check other input backed by \<input type="text"> and \<textarea>, e.g. number input, text area input, ....  Thanks.

### Application/website

IBM

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by rccc** [comment]
@andy-blum 

This ticket was closed, but the request was not done, bx-input still do not emit input and change event ?

Why doing this ?
