### ISSUE TITLE
Date Picker enabled-range issue

### ISSUE THREAD

**Issue by crichtonibm** [carbon-design-system/carbon-for-ibm-dotcom#9742]
### Description

Strange operation when setting enabled-range for bx-date-picker using v1.21.0 (have not tried older versions). Running the simple test shown below, It ends up showing a range of only one day,  Aug 2, 2027. .
![img1](https://user-images.githubusercontent.com/54896681/201692750-0bdc47e8-d3d5-4108-93ec-a4ac622e623f.png)

```
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="j_id_2">
        <title>Carbon Test Title</title>
        <script type="module" src="https://1.www.s81c.com/common/carbon/web-components/version/v1.21.0/date-picker.min.js"></script>
</head>
<body>
      <bx-date-picker id="j_id_p:j_id_7p_3_d:_ct" enabled-range="2022-11-03/2022-11-23" >
        <bx-date-picker-input id="j_id_p:j_id_7p_3_d:_ct1" placeholder="MM/dd/yyyy" kind="single" helper-text="Help text, using quarter for grid">
                       <span slot="label-text">Date, min/max 10 days pre/post<span class="ibm-required">*</span></span>
            <span slot="validity-message"></span>           
        </bx-date-picker-input>
      </bx-date-picker>
 </body>
</html>
```
If I then open the java console and remove the attr, and add it back, it then behaves as expected with the range being between Aug 3 and 23 inclusive (2nd image). Seems a bug. Current workaround is to do that remove/addback of the attr using a timer, waiting for the component to finish initializing. Not ideal.

![img2](https://user-images.githubusercontent.com/54896681/201692775-b5d42450-6e40-4ad8-9320-43ef1232c581.png)

### Component(s) impacted

datepicker

### Browser

Chrome, Firefox

### Carbon Web Components version

1.21.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

www.ibm.com/technologyconnect

### CodeSandbox example

Simple example provided in desc

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by annawen1** [comment]
@crichtonibm this issue should be the same as this one here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10236 with resolution mention in the comments. 

Closing this ticket, feel free to reopen!
