### ISSUE TITLE
Pagination - Items per page dropdown not working

### ISSUE THREAD

**Issue by Prameela337** [carbon-design-system/carbon-for-ibm-dotcom#9748]
### Description

Carbon design - Datatable sorting with pagination - Items per page dropdown is not working as expected. For example Items per page dropdown initial option value is 3 , when i select 6 from the dropdown 6 items are displayed but still dropdown shows 3. 
When i check the code base "bx-page-sizes-select-changed" event triggered but dropdown select value is not updated with update value.
Here is the code snippet

document.addEventListener('bx-page-sizes-select-changed', ({ detail }) => {
  table.state.setPageSize(detail.value);
});

### Component(s) impacted

Datatable pagination with sorting component issue
<img width="146" alt="Screenshot 2022-09-16 175547" src="https://user-images.githubusercontent.com/113693377/190639627-7077be52-11a9-478d-8d0f-b60317bfb573.png">

### Browser

Chrome

### Carbon Web Components version

carbon-web-components 1.21.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

https://web-components.carbondesignsystem.com/?path=/docs/components-data-table--sortable-with-pagination

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-web-components/tree/main/examples/codesandbox/basic/components/data-table

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by m4olivei** [comment]
Closing as duplicate of https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10553
