### ISSUE TITLE
[Communications]: Add information to the README about upcoming v2 release

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#9750]
### User story

I need to add some messaging to the main README about the upcoming v2 release

### Additional information

Question from an adopter:
>I currently use the [Carbon Web Components](https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_carbon-2Ddesign-2Dsystem_carbon-2Dweb-2Dcomponents&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=UHYoJVu8HBhQhKGrRu2dY7eCmS6PwRVFWwml7HscpmU&m=WGqiHpmR8YwOSvDxcwqrVwsBd-cp-QCI63133fmEMpjaRf50YDCclYNq4Xw8H8E9&s=UjgqwMb1eNL-zQgadmfTR4kKCj5tD1LSS9-XHfbVgfk&e=) library on a project for a client and was wondering whether the v11 update to Carbon Web Components is still in development? On the GitHub repo, I've noticed many pull requests still remain open and most branches are labeled as stale since March 2022. Should we expect the Carbon Web Components to receive any further maintenance?

Answer:
> It’s slated for Q4 release! I will let the team know to update messaging on the repository, but we will actually be:
> 
> - Migrating the project to the team’s (Carbon for IBM.com) centralized monorepo
> - Upgrading to Carbon v11
> - Upgrading to Lit v2
> - Announcing official support for Carbon Web Components from the core Carbon team
>
> This will be a major release, so this would effectively be Carbon Web Components v2 coming soon.

### Acceptance criteria

- [ ] Read me updated with v2 release information
- [ ] Dev team review / approve

**Comment by abdonrd** [comment]
Q4 is over and v2 has not been published.
Is there any new news?
Thanks!

**Comment by kennylam** [comment]
@abdonrd Yep we are on the final issues. Should be available in the next few sprints!

**Comment by abdonrd** [comment]
Is there any update about it? Thank you!
