### ISSUE TITLE
[Spacing]: Content block – Fix top and bottom spacing

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#9813]
### The problem

The current content block has too much spacing when the border is added.

### The solution

Update the `content block` vertical spacing to the below:

`@max` through `@lg`:
* Top spacing: 64px margin ($spacing-10)
* If no bottom border, bottom spacing: 160px margin ($spacing-13)
* if bottom border, bottom spacing _to_ bottom border: 96px margin($spacing-12)
* if bottom border, bottom spacing _from_ bottom border: 64px margin ($spacing-10)

`@md` through `@sm`:
* Top margin: 32px margin ($spacing-07)
* If no bottom border, bottom spacing: 96px margin ($spacing-12)
* if bottom border, bottom spacing _to_ bottom border: 64px margin($spacing-10)
* if bottom border, bottom spacing _from_ bottom border: 32px margin ($spacing-07)

<img width="641" alt="Screen Shot 2022-12-07 at 4 13 01 PM" src="https://user-images.githubusercontent.com/15643582/206297683-c3d1d95c-d749-4bbd-a637-943099078020.png">

Note that the spacing _to_ the bottom border can be either margin or padding. Is there a best practice here?

### Application/website

Carbon for IBM.com

### Business priority

High Priority = pressing release

### What time frame would this ideally be needed by (if applicable)

Soon!!!

### Examples

https://www.ibm.com/standards/carbon/web-components/?path=/story/components-content-block--default

https://www.ibm.com/standards/carbon/react/?path=/story/components-content-block--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ariellalgilmore** [comment]
hmm i might have misunderstood the end of our discussion. We can definitely adjust the border spacing, but it gets a little tricky adjusting the top/bottom spacing since the following components are using this: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/styles/scss/internal/content-block/_content-block.scss#L14-L24
