### ISSUE TITLE
Populate from database

### ISSUE THREAD

**Issue by jparadaa** [carbon-design-system/carbon-for-ibm-dotcom#9822]
Hi,

I am not even close to find documentation that help me to know how can I in a select and in a table load data coming from database query, I would appreciate if you help me to provide some examples or documentation, I'm for now only using Vanilla JavaScript.

I appreciate any help.

Regards,
Javier

**Comment by kennylam** [comment]
@jparadaa do you have an example showing what you are trying to do?
