### ISSUE TITLE
[Image]: additional column width options

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#9828]
### The problem

In preparation for Contentful, we need to add some additional image widths and aspect ratios to the image component to support the migration of all Gatsby content.

### Column widths
The image component currently supports an 8 column width, we need some additional widths:
- 4 columns
- 6 columns
- 12 columns

### Image sizes and aspect ratios
The image component should also be able to accept a wide variety of aspect ratios and custom non-aspect ratio sized images that will maintain the column width

**Aspect ratios**
- 2:1
- 16:9
- 3:2
- 4:3
- 1:1
- 3:2
- 3:4

**Custom images**
On the occasion that an image does not fit into an aspect ratio easily, the designer is able to provide a custom image. This is most common in doc sites, like Carbon and Carbon for IBM.com.

### Application/website

Dotcom & Contentful

### Business priority

High Priority = pressing release

### What time frame would this ideally be needed by (if applicable)

Needed for Contentful

### Examples

<img width="757" alt="Screenshot 2022-12-15 at 3 30 53 PM" src="https://user-images.githubusercontent.com/45692622/207961504-d331930d-c2fe-49ea-b905-9ca447047979.png">

<img width="1048" alt="Screenshot 2022-12-15 at 3 38 25 PM" src="https://user-images.githubusercontent.com/45692622/207962207-ea1aad15-3fcc-4543-8682-d30ffa74ac38.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment]
@oliviaflory I just double-checked and confirmed there is no set column size for images. They column sizes can be set per breakpoint based on how ever the are authored. See [this](https://pddxbh.sse.codesandbox.io/) example.
