### ISSUE TITLE
Carbon gray tag is not displaying correctly

### ISSUE THREAD

**Issue by sirkitree** [carbon-design-system/carbon-for-ibm-dotcom#9890]
### Description

Environment: Product
 
When I add a Carbon tag to a component and pick the color "gray" in the dropdown, the tag will display as green tag, not gray. This needs to be updated so when gray is selected as the tag color, the tag displays as a gray tag.
 
This bug seems to appear where ever Carbon tags are being used and isn't component specific.

### Component(s) impacted

Components: Several including structured list, CTA section with static card, pricing table, and where ever Carbon tags are being used

Mainly the Tag Group component

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

latest

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

IBM.com AEM Sites

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

?

### Steps to reproduce the issue (if applicable)

https://prod-author.roks.cms.cis.ibm.net/content/adobe-cms/language-masters/en/prod-sandbox/testproduct-overview-jw/-test-product-feature—jw.html?wcmmode=disabled

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by IgnacioBecerra** [comment]
@sirkitree Hi there! I'm unable to reproduce the behavior you are mentioning. In the [Storybook page](https://web-components.carbondesignsystem.com/?path=/story/components-tag--default), you can change the color to grey and it does not revert back to green. 

Likewise, in our Tag Group story, you can use individual Carbon tags with different colors, including grey, and they don't default to being green.

That being said, if the `type` isn't set, the tag **will** default to green. 

For example
```
```
