### ISSUE TITLE
[ui-shell]: sync with `@carbon/react` version

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#9894]
Several variations are missing in the `carbon-web-components` implementation. Currently only three exist, and should be renamed to match the React versions:

| `carbon-web-components` | `@carbon/react`                     | notes                              | complete |
|------------------------------ |---------------------------------|---------------------------|------------|
| Side nav                              | Fixed SideNav w/ Divider       |                                        |  
| Side nav with Icons             | Fixed SideNav w/ Icons          | cwc version has divider |
| Header                                | Header Base w/ Navigation    | React version defaults to white theme |
| n/a                                      | Fixed SideNav | |
| n/a                                      | Header Base | |
| n/a                                      | Header Base w/ Actions | | 
| n/a                                      | Header Base w/ Actions and Right Panel | |
| n/a                                      | Header Base w/ Actions and Switcher | |
| n/a                                      | Header Base w/ Navigation, Actions and SideNav | | |
| n/a                                      | Header Base w/ Navigation and Actions | | |
| n/a                                      | Header Base w/ SideNav | | |
| n/a                                      | Header Base w/ SkipToContent | | |
| n/a                                      | SideNav Rail | | |
| n/a                                      | SideNav Rail w/ Header | |
| n/a                                      | SideNav w/ large side nav items | |

**Comment by abdonrd** [comment]
Is there an ETA for this? Thanks!
