### ISSUE TITLE
[Documentation]: Missing documentation for data-table--expandable

### ISSUE THREAD

**Issue by cedricpelle** [carbon-design-system/carbon-for-ibm-dotcom#9901]
### Description

Missing documentation for the data-table--expandable feature
into https://web-components.carbondesignsystem.com/?path=/docs/components-data-table--expandable

### Component(s) impacted

web-component : data-table--expandable

### Browser

Chrome

### Carbon for IBM.com version

v1.25.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

IBM terms

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://web-components.carbondesignsystem.com/?path=/docs/components-data-table--expandable

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by techtolentino** [comment]
Upvoting, I would love to know how to use the expanded row 

I just don't have the syntax... @cedricpelle - did you ever figure out how to use it?
