### ISSUE TITLE
[Carousel]: Update button style

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#9921]
### User story

We need to update the carousel buttons to use the tertiary style instead of the secondary. 

Carbon guidelines state that dual secondary styles should never be used together. 

### Additional information

- [Storybook](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-card-section-carousel--default)
- [Carousel specs](https://ibm.ent.box.com/folder/121172699187?s=hmni7qhero9mf5rn593zij0tcay8h9dw)
- [Card section carousel specs](https://ibm.ent.box.com/folder/126468155543?s=wyj5uboppri7nc3gn4v1f7ft80qc5eir)

### Acceptance criteria

- [x] Review designs with Jeannie
- [x] Update or create design specs in Figma
- [x] Update design specs for `card section carousel` in Figma
- [x] Create development story
- [x] Publish updates to Figma component

**Comment by RichKummer** [comment]
**Design crit 02/02/23**
Moving forward with dual `tertiary` styling to bring in line with Carbon guidance and not introduce too many different styles.
