### ISSUE TITLE
[Feature card]: light variant and border enhancement

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#9922]
### User story

We need to update the feature card to include a light variant to align with the brand expression, and update the tile to align with the Carbon tile enhancements for accessibility.

### Additional information

- Feature card should have a light variant (the same as the default cards) 
   - update type token
   - update background token
   - update icon color
- Icon position should align to new card guidelines
   - Icon aligned right 
   - Icon blue for clickable/actionable cards
- Border 
   - Add the new border to align with accessibility updates
   - _We may need to enhance the WC tile first in order to accomplish this_

### Acceptance criteria

- [x] Review designs with Jeannie
- [x] Update design specs in Figma
- [x] Create story for development – border added
- [x] Create story for development – regular color scheme variant
- [x] Create story for Figma updates
- [x] Added feature request for hover state on `feature card – large` #10060

**Comment by RichKummer** [comment]
**[Thy's Card audit](https://www.figma.com/file/OBynI5wxjmuurgZlhX695e/07.2022_Card-Audit-and-Synthesis?node-id=110%3A1636&t=PCSgX43C5voPL7ck-1)**
