### ISSUE TITLE
[Component]: button

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#9979]
Note:
- `Button - with text and icon`: icon position incorrect

**Comment by emyarod** [comment]
* need to remove `field` button size and add `2xl`
* icon button requires tooltip
![image](https://user-images.githubusercontent.com/8265238/217094966-6da86480-b37b-4849-ad2d-aaf9f9ce33de.png)
* `danger-tertiary` and `danger-ghost` need updates
