### ISSUE TITLE
[Component]: overflow-menu

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#9999]
Notes:
- missing `hover`, `focus`, and `active` styles

**Comment by ariellalgilmore** [comment]
i believe this was fixed when we downgraded the sass version 
<img width="313" alt="Screen Shot 2023-02-16 at 3 19 36 PM" src="https://user-images.githubusercontent.com/20210594/219500060-14e7483f-709a-4002-946a-278a915e6f8b.png">
